"""Scoped accuracy correction; no legacy library or homepage generator."""
import html,json,math,re
from pathlib import Path
R=Path(__file__).resolve().parents[1];SLUG='furnishing-during-escrow'
DESC='Before buying an STR, test preclosing furniture orders against supplier terms, deal failure, cash needs and readiness evidence. No launch date is assured.'
BODY='''<p class="lead">Ordering furnishings during escrow can move part of an STR setup schedule earlier, but it is not automatically the best choice or a risk-free way to save a season. Before committing purchase capital, compare the actual supplier dates, cancellation exposure, closing conditions and complete opening plan. Budget, permits, repairs, access and vendor capacity can all delay readiness; ordering furniture alone does not establish the first lawful guest date.</p>
<p><a href="/apply/">Bring the order schedule and unresolved closing conditions to an STR acquisition discussion</a>. This guide answers when to commit furnishing money before ownership. The <a href="/blog/closing-before-peak-season-str/">peak-season closing comparison</a> separately tests whether acceleration creates supported incremental contribution.</p>
<h2>Replace universal lead times with written milestones</h2>
<p>For beds, dining seating, upholstery and other large pieces, obtain an item-level availability answer and the actual shipment, delivery, assembly and acceptance dates. These are different events. There is no universal four-to-eight-week supplier timetable or six-week minimum launch claimed here. In-stock local items, custom orders, access problems and required trades can produce different schedules.</p>
<p>The last indispensable readiness gate controls the opening plan, not necessarily the last decorative item or the closing date. A delivered bed is not an assembled, safe sleeping place; installed furniture does not establish permission, effective coverage or turnover capacity. Identify which items the accepted guest plan actually needs, and price an approved substitution if an essential item is unavailable. Do not advertise amenities that are not available to the guest.</p>
<h2>Original preclosing order acceptance sheet</h2>
<div class="table-wrap"><table><thead><tr><th>Field</th><th>Actual evidence to obtain</th><th>Decision before paying</th></tr></thead><tbody>
<tr><td>Property fit</td><td>Verified dimensions, conveyed inventory and required occupancy/safety constraints</td><td>Do not order replacements for assets already included</td></tr>
<tr><td>Supplier commitment</td><td>Item, quantity, promised dates, delivery area, assembly and exclusions</td><td>Separate an estimate from accepted scope</td></tr>
<tr><td>Cancellation and delay</td><td>Applicable order terms, deadlines, custom-item treatment, storage and rescheduling costs</td><td>Confirm what can be recovered if purchase or delivery changes</td></tr>
<tr><td>Access and acceptance</td><td>Authorized entry, utilities, recipient, condition checks and installation sign-off</td><td>No assumed right to deliver or work before possession</td></tr>
<tr><td>Funds and authority</td><td>Deposit/balance dates, payment credit, lender concerns and buyer spending approval</td><td>Keep closing cash and retained reserve funded separately</td></tr>
</tbody></table></div>
<p>Use a named recipient and a fallback for every essential item. Inspecting and appraising the house does not remove all financing, title, insurance, permission or seller-performance risks. Clearing a contingency may reduce a buyer's protection; it is not a furnishing-buy signal by itself. Have the retained transaction professional explain the remaining conditions and any valid notices. Review actual supplier terms with appropriate advisers rather than infer a refund or cancellation right from this worksheet.</p>
<h2>Compare early commitment with the failed-purchase branch</h2>
<p>Entirely hypothetical amounts, not vendor quotes, typical fees or client outcomes: suppose the furnishing scope is $30,000 with a $9,000 deposit credited to that same total. The balance is $21,000, not another $30,000. Stipulate that a failed purchase permits a $7,500 completed refund but leaves a $1,500 charge under this invented agreement. That branch costs $1,500; before the refund clears, all $9,000 remains unavailable. No actual supplier's terms are asserted.</p>
<p>For a separate delayed-closing branch, assume the accepted order still costs $30,000 and three weeks of distinct storage cost $250 each. Total is $30,750, with $21,750 remaining after the credited $9,000 payment. Do not add another deposit or the failed-purchase charge to this different branch. Check whether storage is already included, whether installation must be rescheduled and whether any new fee is actually authorized.</p>
<p>Cash example: $280,000 accessible funds and a complete $268,000 purchase/setup allocation already including the $30,000 furnishing scope and a protected $40,000 reserve leave $12,000 unallocated. After paying the credited $9,000, cash is $271,000 and remaining allocation $259,000; margin remains $12,000. Adding only the excluded $750 storage raises remaining allocation to $259,750 and leaves $11,250. The reserve is counted once, not spent to conceal the added cost. This partial example does not establish adequate reserves or an investment return.</p>
<p>Compare waiting to order using its own supported availability and cost case. Do not assign a probability to deal failure or assume peak bookings without evidence. The <a href="/tools/first-str-purchase-budget/">purchase-budget worksheet</a> can record dated outflows; pending refunds and anticipated tax savings are not cleared closing funds. For a different replacement property, rebuild the entire budget after actual unrecovered payments rather than assume the previous furnishing plan transfers.</p>
<h2>Stage orders and accept delivery without assuming access</h2>
<p>Start with the components that have a verified long dependency or qualified installation requirement. Short-lead decor, linens and kitchen equipment can sometimes wait, but stock, quantities and delivery must still be confirmed. A hot tub, pool heater or electrical installation requires its own accepted scope and appropriate permissions; ordering it does not make it usable.</p>
<p>Choose a local project manager, accepted installation service or buyer visit only when its deliverables and dates are confirmed. Identify receipt, damage reporting, assembly, disposal, inventory reconciliation and who may approve substitutions. A driver drop-off is not that full handoff. Any preclosing access requires actual authorization, agreed responsibility and appropriate coverage; the buyer should not assume possession from a purchase contract.</p>
<h2>Photography and listing do not certify readiness</h2>
<p>Schedule photography around installed, accurately represented rooms and amenities. If using staged photography or partial-room images, do not misrepresent what the guest will receive. This page makes no claim that eight photographs outperform twenty or that a furnishing sequence guarantees bookings. Coordinate the first-stay date with all permission, safety, coverage and operator gates in the <a href="/blog/airbnb-house-right-after-closing/">post-closing readiness guide</a>.</p>
<h2>Keep tax readiness separate from an order or listing timestamp</h2>
<p><a href="https://www.irs.gov/publications/p527">IRS Publication 527 (2025), placed-in-service guidance</a> ties rental depreciation timing to readiness and availability for the specific rental use. Its appliance example distinguishes delivery from installation and readiness. Neither paying a furniture deposit nor posting an online listing alone establishes that condition. Ask the tax adviser to assess each applicable asset and the actual evidence; do not infer that every first-year deduction moves together or offsets high W-2 income.</p>
<p>Retain dated completion and availability records with invoices through authorized secure storage. For year-end decisions, use the <a href="/blog/str-placed-in-service-date/">placed-in-service evidence guide</a> and professional review, not a promise to list before midnight. Furnishing expenditure and potential tax treatment do not validate an otherwise unfunded purchase.</p>
<p>Proceed with an early order only when actual recovery exposure, access, supplier commitments and independent cash fit the buyer's accepted risk. Stage or defer unsupported commitments; reprice a viable acquisition when verified additional costs matter. Reject a plan dependent on an assumed refund, unsafe opening or unavailable capital. <a href="/apply/">Review the candidate and preclosing order sheet before committing</a>.</p>
<p class="small">Primary IRS guidance reviewed October 8, 2026; the cited publication is the 2025 edition, not newly issued 2026 rules. BNB Accelerator is the commercially interested acquisition-service publisher; actual contracted scope controls. All worked figures are hypothetical. Educational information, not legal, tax, lending or personalized investment advice. No refund, closing, launch date, bookings, deduction or investment result is guaranteed.</p>
'''
ANSWERS=[
('Yes, generally after inspection and appraisal contingencies clear. Case goods routinely carry four to eight week lead times, so ordering on closing day means launching six weeks later at best.','Only when actual supplier dates, cancellation exposure, remaining closing conditions, authorized access and independently funded cash support the commitment. There is no universal minimum launch timetable.'),
('Manage it by ordering after contingencies clear, favoring suppliers with reasonable cancellation terms on large items, splitting long-lead and short-lead orders, and choosing items that would work in a comparable property.','Review the actual supplier agreement and outstanding purchase conditions before paying. Model unrecovered charges and cash held pending a refund; no cancellation, refund or transfer right is assumed.'),
('Depreciation generally begins when property is placed in service, which for a rental means available for booking. A December closing with a February listing can push an entire first-year deduction into the following tax year.','IRS guidance ties placed-in-service timing to readiness and availability for the specific rental use. An order, delivery or online listing alone does not establish it; have the adviser assess each applicable asset and evidence.')]
if __name__=='__main__':
 p=R/'blog'/SLUG/'index.html';s=p.read_text();assert '"datePublished": "2026-08-15"' in s
 old='Ordering furnishing before closing is the single highest-return scheduling decision in a short-term rental acquisition. How to do it without risk.';assert s.count(old)==4;s=s.replace(old,DESC)
 start=s.index('        <p class="lead">');end=s.index('        <div class="callout">',start);s=s[:start]+BODY+'\n'+s[end:]
 for a,b in ANSWERS:assert s.count(a)==2;s=s.replace(a,b)
 s=s.replace('"dateModified": "2026-09-22"','"dateModified": "2026-10-08"').replace('property="og:type" content="website"','property="og:type" content="article"')
 body=re.search(r'<article class="article">(.*?)</article>',s,re.S)[1];words=len(re.sub('<[^>]+>',' ',body).split());minutes=math.ceil(words/220)
 s=s.replace('<span>6 min read</span>',f'<span>Updated October 8, 2026</span><span>&middot;</span><span>{minutes} min read</span>',1)
 s=s.replace('  "articleSection":',f'  "wordCount": {words},\n  "timeRequired": "PT{minutes}M",\n  "articleSection":',1);p.write_text(s)
 p=R/'blog/index.html';s=p.read_text()
 def card(m):
  c=m[0]
  if '/blog/'+SLUG+'/' not in c:return c
  c=c.replace(old.lower(),html.escape(DESC.lower(),quote=True)).replace('<span>6 min read</span>',f'<span>{minutes} min read</span>')
  return c.replace('Ordering furnishing before closing is the single highest-return scheduling decision in a short-term rental...', 'Before buying an STR, test preclosing furniture orders against supplier terms, deal failure and funded readiness.')
 s=re.sub(r'<article class="post-card".*?</article>',card,s,flags=re.S);p.write_text(s)
 p=R/'sitemap-blog.xml';s=p.read_text();s,n=re.subn(r'(<loc>https://www.bnbaccelerator.com/blog/'+SLUG+r'/</loc>\s*<lastmod>)[^<]+',r'\g<1>2026-10-08',s);assert n==1;p.write_text(s)
 p=R/'blog/buy-str-high-income-large-tax-bill/index.html';s=p.read_text();marker='data-furnishing-order-review-link';assert marker not in s;s=s.replace('</article>',f'<p {marker}>Test <a href="/blog/{SLUG}/">preclosing furnishing commitments, deposit credits and failed-purchase cash</a> before using a year-end launch date in the acquisition plan.</p>\n</article>',1);assert marker in s;p.write_text(s)
 print(f'PASS: scoped correction; {words}words/{minutes}minutes; three original FAQ questions aligned')
