"""Scoped existing owner correction; preserve outer design, author and FAQ questions."""
import html,json,math,re
from pathlib import Path
R=Path(__file__).resolve().parents[1]
SLUG='how-to-finance-airbnb-investment-property'
DESCRIPTION='Compare six Airbnb financing paths using actual eligibility, qualifying rent, lender conditions and a funded closing-and-launch cash worksheet.'
BODY='''
<p>To finance an Airbnb investment property, first find a loan that permits your actual property and rental plan, then compare the complete cash requirement and debt obligations. A lower advertised rate or down payment does not make an ineligible product available. High W-2 income, business income or substantial capital can help support a purchase, but none replaces property eligibility or an accepted borrower file.</p>
<p>This guide compares six financing paths for buyers preparing to purchase an STR. Use it to request address-specific written terms, not as a current rate sheet or a promise of approval. Separate the purchase mortgage from borrowed down-payment funds and from a refinance you hope to obtain after closing.</p>
<h2>Conventional investment property loan</h2>
<p>Ask the lender which agency or portfolio program applies, what borrower income it accepts, how it treats existing debts and which property conditions remain. Obtain the actual down payment, closing cash and reserves for your file. A generic percentage or number of reserve months is not a quote.</p>
<p>Fannie Mae's <a href="https://selling-guide.fanniemae.com/sel/b3-3.8-03/rental-income-subject-property-short-term-rental" rel="noopener">specific STR-income guidance</a>, dated September 2, 2026, permits documented qualifying rent for eligible one-unit investment properties with lawful STR use. Purchase evidence can include a long-term Form 1007 or specified validated comparable STR data. The lender must document a current housing payment; a positive calculated result offsets PITIA rather than adding unlimited qualifying income. Ask about implementation and overlays. This is not permission to use any seller projection or a rule for every conventional lender.</p>
<p>The <a href="/blog/airbnb-income-qualify-conventional-str-loan/">conventional STR-income acceptance worksheet</a> develops those evidence and calculation gates. Here the purchase decision is whether the lender accepts your file and the resulting cash budget is affordable, not whether conventional financing is always better for the first two properties.</p>
<h2>Second-home financing</h2>
<p>Use this path only when your genuine occupancy and management plan fit the program. Fannie Mae's <a href="https://selling-guide.fanniemae.com/sel/b2-1.1-01/occupancy-types" rel="noopener">occupancy guidance</a> requires borrower use for part of the year, a one-unit property suitable for year-round occupancy, exclusive control and no agreement giving a management firm occupancy control. Its rental-income clarification also requires that rent not qualify the borrower and that all remaining second-home requirements be satisfied.</p>
<p>Disclose intended rental activity, personal use and the actual manager agreement. Do not misstate use to obtain another financing label. A lender classification does not establish tax treatment, lawful STR permission or insurance coverage. The <a href="/blog/second-home-loan-rental-intent/">second-home rental-intent guide</a> addresses the narrower approval packet. Compare pricing only after the lender has assessed the real use.</p>
<h2>DSCR loans</h2>
<p>For a proposed debt-service-coverage-ratio loan, ask for the lender's written definition of qualifying income and debt service. Which rental evidence is accepted, which expenses are included, and what happens if the property's accepted rent is below the seller forecast? Do not substitute your operating cash-flow model for its qualification calculation.</p>
<p>Obtain the actual documentation, credit, liquidity, ownership, property and portfolio requirements. Do not assume every DSCR product removes tax returns, all borrower review or every limit on financed properties. Compare payment, points, required reserves, recourse and any prepayment charge using that proposal. No universal current rate premium or minimum ratio is asserted here. Use the <a href="/blog/dscr-loans-for-airbnb/">DSCR guide</a> to organize the lender questions, then verify terms with the lender.</p>
<h2>Portfolio and local bank lending</h2>
<p>For a bank-held proposal, request the permitted geography and property use, borrower and entity requirements, accepted rental evidence, amortization, maturity date and renewal conditions. Relationship lending is not a promise of approval or a reason to assume a bank accepts one market but rejects another.</p>
<p>If the quote has a balloon or short maturity, model the amount due and a no-refinance scenario before choosing it. A longer amortization does not necessarily mean the loan lasts that long. Record whether an extension is contractual, discretionary or absent; do not count a future renewal as committed financing.</p>
<h2>HELOC on your primary residence</h2>
<p>A HELOC is a separate source of borrowed capital, not the STR purchase mortgage. <a href="https://www.consumerfinance.gov/ask-cfpb/what-is-a-home-equity-line-of-credit-heloc-en-107/" rel="noopener">CFPB's HELOC guidance</a> explains that the home secures the borrowing, rates are usually variable, further draws can be frozen in specified circumstances and payments can increase at repayment. Failure to repay can put the home at risk.</p>
<p>Ask both lenders whether the proposed source and related payment are acceptable. Record actual drawable funds, draw conditions, payment changes and the repayment deadline. Test household obligations and both loans against a separately funded low-revenue interval. An intended refinance or future tax benefit is not a repayment commitment. Do not count an undrawn line as cleared cash or assume eighteen months is a universally safe bridge period.</p>
<h2>Delayed financing</h2>
<p>A cash purchase followed by a refinance is two transactions. Fannie Mae's <a href="https://selling-guide.fanniemae.com/sel/b2-1.3-03/cash-out-refinance-transactions" rel="noopener">delayed-financing exception</a> has original-purchase, borrower, title, source-of-funds and cash-out requirements. The loan is limited by documented investment and applicable ratios based on current appraisal, with additional restrictions when purchase funds were borrowed or gifted. Meeting an exception is not a promise to recover the full purchase price.</p>
<p>Budget purchase and launch using funds actually available now. Obtain a prospective refinance assessment and calculate net proceeds after its costs and required paydowns. The <a href="/blog/delayed-financing-cash-str/">delayed-financing net-proceeds worksheet</a> develops smaller or unavailable refinance outcomes. Do not assume a cash offer wins or fund another obligation with proceeds not yet approved and received.</p>
<h2>Compare the same purchase using a cash schedule</h2>
<p>Complete one column per genuinely available lender proposal. Keep deposit credit separate from additional cost, and do not spend the same dollars on setup and retained reserves. Send sensitive borrower and account records through authorized secure channels, not a public worksheet.</p>
<div class="table-scroll"><table><thead><tr><th>Decision field</th><th>Written evidence</th><th>Buyer consequence</th></tr></thead><tbody>
<tr><td>Eligible purchase</td><td>Actual address, unit count, disclosed use, borrower and ownership</td><td>Discard an attractive but unavailable quote</td></tr>
<tr><td>Qualification</td><td>Accepted income or rent, debts and unresolved conditions</td><td>A spreadsheet is not approval</td></tr>
<tr><td>Settlement funds</td><td>Down payment, fees, prepaids and credited deposit</td><td>Identify both early payments and remaining balance</td></tr>
<tr><td>Launch and retained cash</td><td>Separate setup, carrying costs and protected reserves</td><td>Count each obligation once</td></tr>
<tr><td>Future debt event</td><td>Rate changes, maturity, penalties and refinance dependencies</td><td>Test the unfavorable branch without assumed new credit</td></tr>
</tbody></table></div>
<p>Hypothetical example, not an offer or required minimum: a buyer allocates $300,000 of cleared capital to a $700,000 purchase. Available quote A provides a $525,000 loan, requiring $175,000 price cash; closing fees and prepaids total $18,000. A $20,000 already-paid deposit is credited toward the $193,000 settlement allocation, so remaining settlement cash is $173,000, not $193,000 plus the deposit. Add $32,000 setup, $10,000 opening carrying costs and $45,000 retained reserves: total allocation $280,000, leaving $20,000 unallocated.</p>
<p>Available quote B supplies a $490,000 loan with $14,000 closing fees and prepaids. Its settlement allocation is $224,000, including the same credited deposit; remaining settlement cash is $204,000. With the same $87,000 setup, carrying and reserve allocation, total required capital is $311,000, an $11,000 gap. Even an assumed $400 lower monthly payment saves only $4,800 over twelve months; it does not supply missing settlement funds. Verify actual payment and whole-term cost independently.</p>
<p>If A also requires $12,000 of distinct repairs omitted from setup, its allocation becomes $292,000 and margin $8,000. A further non-overlapping $9,000 delay cost creates a $1,000 shortfall. The $45,000 reserve remains protected in every branch. These invented scenarios illustrate cash timing, not lender eligibility, investment return, client experience or tax results.</p>
<h2>Set the financing envelope before the offer</h2>
<p>Proceed only with an honestly disclosed, permitted financing path whose conditions, dates and funded downside you understand. Renegotiate price or select another genuinely available proposal when the budget fails. Delay under valid protection while decisive evidence remains outstanding; reject a financing thesis that depends on inaccurate occupancy or uncommitted future cash.</p>
<p>Resolve intended ownership with the lender, qualified counsel and CPA before applying. Ask about the actual documents before any later transfer; this page does not determine a transfer's legal or tax consequences. Use <a href="/how-it-works/">the acquisition sequence</a> and <a href="/blog/buy-str-high-income-large-tax-bill/">the high-income buying hub</a> to connect funding with the rest of the purchase.</p>
<div class="inline-cta"><h3>Compare financing before choosing the property</h3><p>Bring dated proposals, unresolved eligibility questions and this cash schedule to an acquisition discussion. BNB Accelerator works within its contracted acquisition scope; the lender approves financing and independent advisers determine their professional conclusions.</p><a class="btn btn-primary btn-lg" href="/apply/">Apply Now</a></div>
<p class="small">Primary sources reviewed October 8, 2026: Fannie Mae STR income (September 2, 2026), occupancy (October 5, 2022), cash-out refinance (December 10, 2025); CFPB HELOC guidance (reviewed August 28, 2026). BNB Accelerator is the publisher and an interested acquisition-service provider. Document-based education, not firsthand lender testing, a loan offer or personalized lending, legal, tax or investment advice. No financing, tax benefit or return is guaranteed.</p>
'''
if __name__=='__main__':
 p=R/'blog'/SLUG/'index.html';s=p.read_text();old=s
 s,n=re.subn(r'(<article class="article">).*?(<h2 id="faq">)',lambda m:m[1]+BODY+'\n'+m[2],s,flags=re.S);assert n==1
 answers=[
 ('Yes. A conventional investment property loan works for a short-term rental, typically requiring 20 to 25 percent down, reserves of six months of payments, and qualification based on your personal debt-to-income ratio. Most conventional underwriting will not count projected short-term rental income, which limits how many properties you can stack.', 'Potentially. Fannie Mae permits documented qualifying rent for eligible one-unit investment STR purchases under its specific requirements. Ask the lender about implementation, accepted evidence, current housing payment and all remaining borrower and property conditions; a seller forecast alone is not approval.'),
 ("Second-home financing can go as low as 10 percent down, but only if the property meets the lender's occupancy requirements: reasonable distance from your primary residence, available for your personal use, and not subject to a mandatory rental management agreement. Misrepresenting occupancy on a mortgage application is fraud, not a technicality.", 'There is no universal minimum for every STR purchase. Obtain an address-specific quote for a product that permits your actual use. Compare closing and launch cash plus retained reserves, and exclude a cheaper second-home quote if the disclosed occupancy and management plan is ineligible.'),
 ('Conventional guidelines generally cap financed properties at ten, and many lenders stop at four to six in practice. Beyond that, investors typically move to DSCR loans or portfolio lending, neither of which counts against the conventional limit or against personal debt-to-income.', "Ask the lender how its current program counts your financed properties and related debts and whether additional reserves or restrictions apply. Do not assume a DSCR or bank-held loan eliminates every portfolio limit or has no effect on a later lender's borrower review.")]
 for a,b in answers:
  assert s.count(a)==2;s=s.replace(a,b)
 s=s.replace('content="2026-06-03"','content="2026-08-10"').replace('Updated October 6, 2026','Updated October 8, 2026')
 for name in ['description','og:description','twitter:description']:
  s=re.sub(r'(<meta (?:name|property)="'+name+r'" content=")[^"]*(")',lambda m:m[1]+html.escape(DESCRIPTION,quote=True)+m[2],s)
 body=re.search(r'<article class="article">(.*?)<div class="author-box">',s,re.S)[1];words=len(re.findall(r'\b\w+\b',html.unescape(re.sub('<[^>]+>',' ',body))));minutes=math.ceil(words/220)
 def schema(m):
  d=json.loads(m[2])
  for n in d.get('@graph',[d]):
   if n.get('@type') in ['Article','BlogPosting']:n.update(description=DESCRIPTION,dateModified='2026-10-08',wordCount=len(re.sub(r'\s+',' ',re.sub('<[^>]+>',' ',re.search(r'<article\b[^>]*>(.*?)</article>',s,re.S)[1])).strip().split(' ')))
  return m[1]+json.dumps(d,indent=2)+m[3]
 s=re.sub(r'(<script[^>]*type="application/ld\+json"[^>]*>)(.*?)(</script>)',schema,s,flags=re.S)
 s=re.sub(r'<span>\d+ min read</span>',f'<span>{minutes} min read</span>',s,count=1);p.write_text(s)
 p=R/'blog/index.html';a=p.read_text();matches=0
 def card(m):
  global matches
  c=m[0]
  if '/blog/'+SLUG+'/' not in c:return c
  matches+=1;c=re.sub(r'<p>.*?</p>','<p>'+DESCRIPTION+'</p>',c,count=1,flags=re.S)
  c=re.sub(r'data-search="[^"]*"','data-search="'+html.escape(('How to Finance an Airbnb Investment Property '+DESCRIPTION+' loan eligibility deposit credit capital schedule').lower(),quote=True)+'"',c)
  return re.sub(r'<span>\d+ min read</span>',f'<span>{minutes} min read</span>',c)
 a=re.sub(r'<article class="post-card".*?</article>',card,a,flags=re.S);assert matches==1;p.write_text(a)
 p=R/'blog/buy-str-high-income-large-tax-bill/index.html';h=p.read_text();assert 'data-broad-financing-link' not in h
 h=h.replace('<div class="author-box">','<p data-broad-financing-link>Before selecting a purchase loan, compare <a href="/blog/how-to-finance-airbnb-investment-property/">six financing paths and a credited-deposit closing-and-launch cash schedule</a> using genuinely available lender proposals.</p>\n<div class="author-box">',1);p.write_text(h)
 p=R/'sitemap-blog.xml';x=p.read_text();url='https://www.bnbaccelerator.com/blog/'+SLUG+'/'
 x,n=re.subn(r'(<loc>'+re.escape(url)+r'</loc>\s*<lastmod>)[^<]*(</lastmod>)',lambda m:m[1]+'2026-10-08'+m[2],x);assert n==1;p.write_text(x)
 print(json.dumps({'words':words,'minutes':minutes,'original_publication':'2026-08-10','FAQ_questions':8,'new509':False}))
