"""Correct one existing comparison; preserve owners, publication and shared flow."""
import re
from refresh_dscr_purchase_methods import refresh, publisher

BODY='''<p class="lead">Before buying a property for short-term or mid-term rental use, compare address-specific demand, written operating permissions, owner cash and your responsibilities. Neither model universally wins. For a high-income buyer, an estimated deduction is not a substitute for an affordable purchase and a workable rental plan.</p>
<h2 id="models">Define the proposed stays and responsibilities</h2>
<p>For this comparison, STR means a proposed nightly or weekly stay model; mid-term means a proposed furnished month-or-longer model. These working labels are not legal or tax classifications. Specify the actual lengths, services, utilities, payment terms and customer channel you intend to use. An advertised monthly rate or a signed multi-month agreement does not establish payment collection, uninterrupted occupancy or permission.</p>
<p>Underwrite both at the same address and condition. Ask a local professional for relevant stay-demand evidence, competing furnished offers, concessions and actual collected performance where obtainable. Do not assume a hospital, employer or tourism attraction produces enough demand for this home. Separate a supported record from an asking rate or an unverified projection.</p>
<h2 id="numbers">Compare cash after expenses, not a universal revenue premium</h2>
<p><strong>Original hypothetical worksheet:</strong> the inputs below are stipulated for comparison, not local market figures, provider quotes, lender terms or forecasts. The same property's annual mortgage principal/interest, taxes, insurance and HOA total $30,000 in each model. Confirm those components so escrowed charges are not counted twice. Other operations exclude these fixed payments and the separately listed management fee.</p>
<div class="table-wrap"><table><thead><tr><th>Annual item</th><th>STR base case</th><th>Mid-term base case</th><th>STR lower receipts</th><th>Mid-term three-month gap</th></tr></thead><tbody>
<tr><td>Collected gross rent</td><td>$90,000</td><td>$54,000</td><td>$70,000</td><td>$40,500</td></tr>
<tr><td>Management assumption</td><td>20% = $18,000</td><td>10% = $5,400</td><td>$14,000</td><td>$4,050</td></tr>
<tr><td>Other operating cash</td><td>$21,000</td><td>$14,000</td><td>$21,000</td><td>$14,000</td></tr>
<tr><td>Fixed owner payments</td><td>$30,000</td><td>$30,000</td><td>$30,000</td><td>$30,000</td></tr>
<tr><td>Cash after listed payments</td><td>$21,000</td><td>$4,600</td><td>$5,000</td><td>−$7,550</td></tr>
</tbody></table></div>
<p>The mid-term base assumes $4,500 collected monthly for twelve months; the gap case collects nine months. The percentage fee follows receipts, but all other modeled costs remain unchanged. STR lower receipts reduce management by $4,000; its listed cash falls $16,000. The mid-term gap removes $13,500 rent and $1,350 management, worsening cash $12,150. These are sensitivities, not likelihoods or claims about which model is safer.</p>
<p>Other operating cash needs a real line-item quote: cleaning paid by the owner, retained utilities, supplies, routine repairs, marketing/platform charges, leasing and renewal costs where applicable. Do not assume guest cleaning charges or tenant reimbursements offset owner costs without reconciling collections and payouts. If a manager has minimums or a different fee base, replace the percentage assumption. Major replacements, personal income taxes, unmodeled work and further vacancy are excluded; this is neither NOI nor taxable income.</p>
<h2 id="tax">Keep your tax review separate from the model label</h2>
<p><a href="https://www.irs.gov/publications/p925" target="_blank" rel="noopener">IRS Publication 925 (2025)</a> lists multiple rental-activity exceptions: average customer use of seven days or less, and thirty days or less with significant personal services, among others. Classification alone does not establish a deductible loss; participation and other limits matter. A furnished monthly label does not settle the analysis. Ask your CPA to review actual periods, services, activity boundaries and your circumstances before relying on any offset.</p>
<div class="callout warn"><p>My BnB Accelerator, LLC is a real estate acquisition firm and is not a CPA, legal, or insurance advisory firm. Nothing here is tax, legal, or insurance advice. Our tax partner is <a href="https://aetaxadvisors.com/" target="_blank" rel="noopener">AE Tax Advisors</a>, an independent firm.</p></div>
<p>Keep booking and service records for the professional review. Do not purchase a weaker cash-flowing property because a promotional description promises a six-figure deduction. Put projected or unreceived refund cash at zero in your committed acquisition budget.</p>
<h2 id="hybrid">A mixed booking calendar needs another decision</h2>
<p>Illustrative single-class arithmetic: twenty-six five-day rentals plus one fifty-two-day rental total 182 customer-use days across 27 rentals, or about 6.74 days. Add one thirty-day rental and the arithmetic becomes 212 divided by 28, about 7.57. This is not an eligibility opinion; your CPA must determine the correct periods and activity treatment. A rolling monitor helps identify a changed mix but does not replace the tax-year analysis.</p>
<p>For operating cash, compare the additional booking's collected payment with incremental expenses and any displaced bookings separately. A tax estimate is not cash received today, and a booking mix is not an automatic portfolio grouping election. Model any proposed conversion work and first-payment delay using the <a href="/blog/str-long-term-rental-fallback/">lease-fallback cash worksheet</a> rather than assuming a seamless transition.</p>
<h2 id="choose">Five acquisition checks before choosing</h2>
<ol><li><strong>Permission:</strong> have the applicable local rules, HOA documents, financing and insurance conditions reviewed for each proposed use. A thirty-day minimum is not an automatic exemption. Use the <a href="/blog/str-regulations-before-you-buy/">address-specific permissions checklist</a>.</li><li><strong>Evidence:</strong> record which comparable rents or stay records support each model, which concessions apply and which assumptions remain unverified.</li><li><strong>Scope:</strong> compare manager/leasing deliverables, fee triggers, exclusions, collection responsibility and tasks you retain. Longer stays do not eliminate maintenance, payment disputes or oversight.</li><li><strong>Capital:</strong> fund acquisition and opening separately from retained reserves, with a dated no-payment case. Illustratively, $160,000 down payment/closing plus $35,000 furnishing plus $30,000 retained cash allocate $225,000. That retained $30,000 is protected, not another furnishing allowance or a recommended universal reserve.</li><li><strong>Decision:</strong> choose an evidence-supported model you can afford, negotiate, obtain missing evidence or decline. Neither a tax bill nor a higher gross projection resolves a shortfall.</li></ol>
<div class="inline-cta"><h3>Underwrite both models before you buy</h3><p>Ask which written service deliverable covers alternative stay models, evidence review and downside cash. BNB Accelerator is the interested acquisition-service publisher; this is an original educational worksheet, not a custom contracted underwriting report or firsthand test of a rental provider. Confirm the actual scope and independent professionals needed.</p><a class="btn btn-primary btn-lg" href="/apply/">Apply Now</a></div>
<p class="small">Source and accuracy review: October 7, 2026. Current IRS Publication 925 (2025), not a new 2026 edition, supports the bounded classification discussion only. Hypothetical cash inputs do not establish demand, expected results, tax eligibility or legal permission. No investment return, refund or indexing is guaranteed.</p>
'''
FAQ=[
('Are mid-term rentals better than short-term rentals?','Neither universally wins. Compare supported address-specific receipts, all owner costs, collection delays, permissions and retained responsibilities. The labeled worksheet is a sensitivity comparison, not a market forecast.'),
('Do mid-term rentals qualify for the short-term rental tax strategy?','The label does not decide. Publication 925 lists several exceptions, including seven-day average use and thirty-day average use with significant personal services. Obtain a CPA review; an exception does not automatically permit a loss offset.'),
('Can a few long bookings break my short-term rental tax position?','They can change average customer use. The labeled example moves from 182 days/27 rentals to 212 days/28 rentals. Have your CPA review the tax-year periods, services and other requirements; a monthly monitor is not a final classification.'),
('Can I run short-term and mid-term rentals at the same time?','Consider a mixed calendar or separate properties only after verifying permissions, financing, insurance, service scope and cash. Separate addresses or booking labels do not automatically determine tax activity treatment.')]

if __name__=='__main__':
    old=(publisher.ROOT/'blog/str-vs-midterm-rentals/index.html').read_text()
    keep=re.search(r'<div class="callout">\s*<h3>Keep reading</h3>.*?</div>',old,re.S)[0]
    refresh('str-vs-midterm-rentals','Short-Term vs Mid-Term Rentals: Which Wins in 2026?','Short-Term vs Mid-Term Rentals','Compare STR and mid-term acquisition cash, evidence, permissions, management scope and tax-review limits. No universal revenue or deduction promise.',BODY+keep,FAQ,'2026-08-10','data-midterm-comparison-review-link','Compare <a href="/blog/str-vs-midterm-rentals/">STR and mid-term owner cash and evidence</a> before choosing a stay model. Neither monthly rent nor a short-stay label guarantees a tax offset or permitted use.')
