"""Scoped existing-owner expansion. Source review in adjacent dated record."""
import html,json,re
from pathlib import Path
from expand_reservations_closing import main
R=Path(__file__).resolve().parents[1]
SLUG='pool-slide-liability-str'
BODY='''<p class="lead">Before buying an STR with a pool slide or diving board, decide whether the exact equipment can remain available to guests, needs an accepted restricted-use plan, or must be removed. Seller photographs, a functioning slide and a generic pool-insurance quote do not settle that decision. Separate the installed equipment's condition, applicable requirements, actual coverage and funded opening sequence. A buyer with substantial capital still needs a supported operating plan before releasing purchase protections.</p>
<p><a href="/apply/">Bring the equipment evidence and keep/remove budget to an STR acquisition call</a>. BNB Accelerator assists within its contracted acquisition scope; qualified pool specialists, the relevant authority, licensed insurance professionals and independent counsel determine their respective findings and approvals. This guide is a purchase worksheet, not instructions for modifying a pool or a promise that a feature is safe.</p>
<h2>Product standards, installed condition and insurance are separate</h2>
<p>The <a href="https://www.cpsc.gov/FAQ/Swimming-Pool-Slides-Freestanding" rel="noopener">CPSC's freestanding swimming-pool slide FAQ</a> identifies 16 CFR Part 1207 as the mandatory federal consumer product safety standard for those slides. It also identifies the applicable citation for product certification. That reference does not inspect this installation, approve a diving board, establish local rental permission or supply a universal pool-depth rule. Ask a qualified specialist to identify the actual equipment and the manufacturer documentation applicable to its installation.</p>
<p>A product label is not a finding about the pool's present geometry, mounting, deterioration, surrounding deck or operating conditions. Collect the model, installation records, permits, repairs and available instructions. Have the specialist document what was measured, what could not be verified and which work or further review is required. Do not make a seller's assertion of grandfathering substitute for the actual authority's answer.</p>
<p>For one provider example, <a href="https://www.proper.insure/coverages/amenities-on-and-off-premises/" rel="noopener">Proper Insurance's amenity-liability page</a> advertises protection for pools and other rental amenities. Its policy disclaimer says actual terms, loss circumstances and underwriting eligibility control. This is marketing information, not acceptance of the buyer's slide or diving board. Obtain the actual proposed coverage and disclose the exact equipment, intended guest use, ownership and rental arrangement. Do not assume a general pool answer covers every accessory or that an accessory exclusion necessarily decides every unrelated pool claim.</p>
<h2>Build an equipment-to-opening acceptance register</h2>
<p>Use a separate row for each slide or board. Attach the actual document, name the person responsible for the answer and record its due date relative to the purchase contract. An unresolved row remains an acquisition assumption, not a favorable finding.</p>
<div class="table-wrap"><table><thead><tr><th>Decision gate</th><th>Evidence to request</th><th>Buyer consequence</th></tr></thead><tbody>
<tr><td>Identify equipment and installation</td><td>Model, manufacturer instructions, installation/repair records and dated photographs</td><td>Do not rely on a listing photo or an unidentified replacement part</td></tr>
<tr><td>Match installed condition and geometry</td><td>Qualified specialist's scope, measurements, mounting and condition findings</td><td>Price required work; do not invent a safe depth or owner repair method</td></tr>
<tr><td>Resolve applicable requirements</td><td>Actual authority's classification and required permits/inspections, with counsel review where needed</td><td>Do not infer that residential appearance establishes lawful STR guest use</td></tr>
<tr><td>Obtain an equipment-specific insurance answer</td><td>Disclosed-use response, proposed policy terms, conditions, exclusions and effective dates</td><td>A quote or safety recommendation alone is not accepted coverage</td></tr>
<tr><td>Fund the selected work</td><td>Keep, restrict or removal/reinstatement scope, provider dates and payment schedule</td><td>Confirm who may authorize work before possession and who pays if closing fails</td></tr>
<tr><td>Accept the opening plan</td><td>Named operator, access controls, required completion evidence and accepted service duties</td><td>Do not advertise equipment until the lawful, safe and appropriately insured plan is established</td></tr>
</tbody></table></div>
<p>Restricting access is not simply adding a sign or removing a ladder yourself. Ask qualified advisers what actually prevents guest use and whether the arrangement is acceptable; an improvised restriction can create other hazards. Removal also needs a complete scope for mounts, deck restoration and any resulting inspection or insurance update. Neither route establishes that the rest of the pool can open.</p>
<p>The broader <a href="/blog/pool-inspection-short-term-rental/">pool inspection guide</a> covers the surrounding system, barriers and service evidence. The <a href="/blog/pool-insurance-short-term-rental/">pool insurance review</a> covers general disclosed rental use. This worksheet isolates the extra equipment decision; it does not replace either wider review. A waiver or guest rule does not substitute for appropriate construction, maintenance, permissions and coverage.</p>
<h2>Worked purchase comparison: keep and remove need separate budgets</h2>
<p>Invented planning amounts only, not contractor bids, insurance premiums, provider fees or a client result. Assume $310,000 accessible cash allocated to this acquisition after household and business liquidity have been excluded. The common plan uses $180,000 down payment, $20,000 closing/service charges, $30,000 furnishings, $15,000 repairs unrelated to the equipment and $45,000 retained operating reserves. Total allocation is $290,000, leaving $20,000 outside the plan.</p>
<p>In a hypothetical accepted keep route, add $8,000 of distinct equipment work: total allocation is $298,000 and unallocated cash is $12,000. In a different removal/reinstatement route, add $6,000 instead: total is $296,000 and unallocated cash is $14,000. These are alternatives, not $14,000 of combined work. The $45,000 reserve remains cash once; it is not simultaneously available to pay work while still being called fully protected.</p>
<p>Now stress each route with $9,000 newly identified deck work plus $6,000 actual pre-revenue carrying bills, neither included in the common plan or equipment scope. Keep requires $313,000, creating a $3,000 gap. Removal requires $311,000, creating a $1,000 gap. If the deck work was already included in the original repairs, do not add it twice: only the $6,000 carrying increment applies, producing $304,000 and $302,000 respectively, with $6,000 and $8,000 remaining.</p>
<p>Replace the assumptions with dated quotes and an actual bill schedule. Separate recurring premiums and service charges from one-time work. Confirm which premium and acquisition charges are already in closing costs. A price reduction does not necessarily reduce down-payment cash dollar for dollar; an approved loan may fall too. A seller credit has its own lender and settlement limits. Future bookings, an expected refund or an imagined claim payment cannot fund a contractor's earlier invoice. Use the <a href="/financing/closing-costs-and-reserves/">closing-cost and reserve framework</a> to reconcile the revised acquisition budget.</p>
<h2>Test the work sequence before promising a turnkey opening</h2>
<p>In a separate hypothetical schedule, the buyer's diligence decision is due on day 10, the specialist can inspect on day 12 and closing is planned for day 20. A funded removal quote does not provide the missing day-10 answer. Ask counsel before the actual deadline whether an appropriate extension, documented condition or other lawful course is available. No automatic cancellation, deposit refund or seller-paid work is implied.</p>
<p>If work must be accepted before insurance becomes effective, a buyer-funded post-closing plan does not satisfy that sequence by itself. Resolve access, authorization, work completion, any required inspection and insurer/lender acceptance. Reconfirm after a closing-date change. Spending buyer money on seller-owned property introduces a separate failed-sale exposure that counsel and the relevant insurer/lender should review.</p>
<p>Do not assign an unsupported revenue premium to keeping the slide. Underwrite the acquisition without assuming an accessory pays for itself; evidence about pools generally does not isolate the slide's booking contribution. Removing equipment can change the listing promise, so have the operator plan accurate photographs, descriptions and lawful treatment of affected reservations. An acquisition adviser cannot guarantee guest acceptance or claim protection.</p>
<h2>Choose a supported acquisition outcome</h2>
<p>Proceed when the equipment-specific evidence, actual coverage, permitted work and funded opening plan fit. Renegotiate when verified costs or restrictions change the supported purchase economics. Delay only under valid contractual protection while a decisive answer is obtainable. Reject a purchase dependent on an unidentified installation, unsupported coverage or unfunded readiness work. Removing the accessory is one possible route, not a guarantee of a safe or legally ready pool.</p>
<p>For <a href="/blog/buy-str-high-income-large-tax-bill/">high-income buyers with substantial deployable capital</a>, equipment acceptance belongs in the offer and launch decision before an anticipated tax benefit. <a href="/apply/">Bring both supported equipment routes and their cash timing to an acquisition call</a>. Retain actual findings and approvals in the purchase file; do not replace them with a provider's general marketing description.</p>
<p class="small">Primary CPSC and Proper materials reviewed October 8, 2026. Educational information, not engineering, safety certification, legal, insurance, tax, lending or personalized investment advice. Worked amounts and dates are hypothetical. No lawful opening, coverage, claim payment, booking premium, deduction or investment result is guaranteed.</p>'''
if __name__=='__main__':
    main(slug=SLUG,title='Should an STR Keep a Pool Slide or Diving Board | BNB Accelerator',h1='Should an STR Keep a Pool Slide or Diving Board?',description='Before buying an STR, verify pool slide or diving board acceptance, compare funded keep/remove plans and resolve work and insurance deadlines.',body=BODY,search_terms='pool slide diving board acceptance removal purchase cash insurance deadline',hub_attribute='data-pool-slide-link',hub_block='<p data-pool-slide-link>Pool slide or diving board on a shortlisted STR? Use the <a href="/blog/pool-slide-liability-str/">equipment acceptance register and funded keep/remove comparison</a> before releasing purchase protections.</p>')
    p=R/'blog'/SLUG/'index.html';s=p.read_text().replace('Updated October 6, 2026','Updated October 8, 2026')
    words=len(re.findall(r'\b\w+\b',html.unescape(re.sub('<[^>]+>',' ',BODY))))
    def schema(m):
        d=json.loads(m.group(2))
        for n in d.get('@graph',[d]):
            if n.get('@type') in ['Article','BlogPosting']:n.update(dateModified='2026-10-08',wordCount=words)
        return m.group(1)+json.dumps(d,indent=2)+m.group(3)
    p.write_text(re.sub(r'(<script[^>]*type="application/ld\+json"[^>]*>)(.*?)(</script>)',schema,s,flags=re.S))
    p=R/'sitemap-blog.xml';s=p.read_text();url='https://www.bnbaccelerator.com/blog/'+SLUG+'/'
    s,n=re.subn(r'(<loc>'+re.escape(url)+r'</loc>\s*<lastmod>)[^<]*(</lastmod>)',lambda m:m[1]+'2026-10-08'+m[2],s);assert n==1;p.write_text(s)
