"""Scoped purchase-premium refresh; Airbnb primary sources checked October 6."""
from expand_reservations_closing import main as refresh

SLUG = 'future-booking-calendar-value'
TITLE = 'Buying an STR: What Is Its Future Booking Calendar Worth?'
H1 = 'How much should you pay for future bookings when buying an STR?'
DESCRIPTION = 'Buying a booked STR? Test lawful buyer receipts, service costs and a fresh-launch alternative before paying a purchase-price premium for its calendar.'
BODY = '''<p class="lead">Do not add the seller's gross future bookings to your STR offer. First establish which receipts the buyer can legitimately receive, subtract the costs and risks of earning them, and compare that contribution with a fresh-launch alternative over the same dates. A calendar can have little incremental purchase value even when it contains real reservations. For a funded buyer, this is a price decision, not a reason to skip diligence.</p>
<p><a href="/apply/">Book an STR acquisition call to test the seller's booking-calendar premium before making an offer</a>.</p>
<h2>Screen the calendar before assigning buyer value</h2>
<p><a href="https://www.airbnb.com/help/article/1431" rel="noopener">Airbnb's account-transfer guidance</a> says account ownership cannot transfer to a different host and reservations cannot transfer to a new host or account. A trip-change request does not authorize a reservation-management handoff to a new owner. Buying the deed, furnishings or account credentials does not override those rules. A seller's Airbnb reservation should not be treated as a transferred buyer asset.</p>
<p>Ask the platform about the specific situation and have independent counsel, the insurer and the permitting authority evaluate any proposed arrangement. Do not assume that retaining a manager makes it permissible. Exclude unsupported receipts from the priced case. If guests might independently make new, permitted reservations, that is an uncertain new-booking scenario, not continuity already secured by the purchase.</p>
<p>The <a href="/blog/future-reservations-at-closing/">reservation-closing ledger</a> addresses guest obligations and early service funding. This guide instead isolates the incremental price premium, if any, supported by the calendar. Keep permission, money ownership and valuation as three separate questions: a documented obligation to serve guests is not necessarily an economic benefit.</p>
<h2>Reconcile receipts rather than pricing a screenshot</h2>
<p>Request dated reservation-level records from the authorized seller or operator. <a href="https://www.airbnb.com/help/article/3632" rel="noopener">Airbnb's earnings-report guidance</a> distinguishes Upcoming and Paid transactions and describes reports showing gross earnings, adjustments, host service fees, withheld taxes and net pay. Those records help reconcile amounts; they do not establish the buyer's entitlement or turn upcoming money into cleared cash.</p>
<div class="table-wrap"><table><thead><tr><th>Evidence field</th><th>Question affecting purchase value</th></tr></thead><tbody>
<tr><td>Reservation ID, channel and stay dates</td><td>Is this confirmed demand for the valuation window, an inquiry, or simply a blocked night?</td></tr>
<tr><td>Paid amount, unpaid amount and recipient</td><td>Which funds belong to the seller, and which receipts could actually belong to the buyer?</td></tr>
<tr><td>Documented lawful treatment</td><td>Do platform rules and adviser-reviewed terms support including any buyer benefit?</td></tr>
<tr><td>Costs and cancellation terms</td><td>What service, transition, refund or other cash exposure accompanies the included receipts?</td></tr>
<tr><td>Expected receipt and payment dates</td><td>Is the buyer paying a premium now for uncertain or delayed money later?</td></tr>
</tbody></table></div>
<p>Use IDs and secure records rather than publishing private guest details. Reconcile seller-retained deposits and any transaction settlement separately so the same amount is not counted twice. Match the seller's payout export to source records using the <a href="/blog/reconcile-airbnb-payout-export/">payout-reconciliation checklist</a>. Do not value taxes collected for remittance as freely spendable profit or deduct a fee again from a receipt already net of that fee.</p>
<h2>Compare the calendar with a fresh-launch alternative</h2>
<p>All following figures are hypothetical arithmetic, not a property forecast, platform transfer procedure, market valuation or client result. Suppose a seller advertises a $20,000 calendar and asks for an $8,000 purchase-price premium. After exclusions and seller-retained amounts, a separately verified lawful arrangement is assumed to produce $12,000 of buyer receipts. Assume $6,000 of associated service and transition costs, leaving $6,000 of modeled contribution before tax, financing and other omitted expenses.</p>
<div class="table-wrap"><table><thead><tr><th>Same near-term operating window</th><th>Supported-calendar case</th><th>Calendar downside</th><th>Fresh-launch alternative</th></tr></thead><tbody>
<tr><td>Modeled contribution after the included costs</td><td>$6,000</td><td>$4,000</td><td>$4,000</td></tr>
<tr><td>Advantage over fresh launch, before premium</td><td>$2,000</td><td>$0</td><td>Baseline</td></tr>
<tr><td>Advantage after paying the $8,000 premium</td><td>-$6,000</td><td>-$8,000</td><td>No calendar premium</td></tr>
</tbody></table></div>
<p>The downside assumes an additional $2,000 actual net reduction from cancellation/refund exposure after any avoided costs. It is not a measured cancellation probability. The fresh-launch $4,000 contribution is another explicit assumption that needs its own booking, readiness and cost evidence. Include comparable cost buckets on both paths; hold identical fixed property costs constant in this isolated comparison, then include them in the complete purchase underwriting.</p>
<p>In this constructed example, the calendar's baseline advantage is only $2,000, not its $20,000 headline or $6,000 contribution. Paying $8,000 fails this limited incremental test. The result is not a universal appraisal ceiling: longer-term property economics, timing, financing, alternative uses and independently supported benefits require separate analysis. Discount uncertain later receipts appropriately with an adviser rather than inventing an 80% continuity rate.</p>
<p>Use the <a href="/blog/new-listing-ramp-underwriting/">new-listing ramp worksheet</a> to support the alternative rather than assuming immediate mature occupancy. Use the <a href="/blog/seller-proforma-vs-trailing-revenue/">seller-pro-forma bridge</a> for longer-term uplift. Do not count the same near-term bookings in both the calendar premium and a separate income-based price adjustment.</p>
<h2>Turn the comparison into an offer decision</h2>
<p>Proceed when lawful, documented buyer benefits and the complete purchase economics support your offer without speculative calendar value. Renegotiate an unsupported premium rather than dismissing an otherwise sound property. Delay under valid contractual protection while a decisive payout, permission or cost fact remains unresolved. Reject a deal that requires prohibited transfer, seller-controlled money represented as buyer cash, or a premium supported only by screenshots.</p>
<p>Ask the seller to identify the exact evidence behind each priced benefit and the date at which the calendar will be reconciled again. Have counsel and the lender assess any proposed settlement allocation or adjustment; this worksheet is not a contract clause or an assurance that a credit is permitted. Reprice if closing dates, canceled stays or guest-resolution costs change. A sound property purchase may still deserve zero separately assigned calendar premium.</p>
<p>For <a href="/blog/buy-str-high-income-large-tax-bill/">high-income investors deploying substantial capital</a>, disciplined offer pricing matters even when cash is available. <a href="/apply/">Book a call to compare this STR's supported calendar benefit with a clean-launch purchase</a>. BNB Accelerator supports acquisition within its contracted scope; platform decisions and independent legal, lending, insurance and tax approvals remain separate.</p>
<p class="small">Primary sources reviewed October 6, 2026. Educational information only, not legal, tax, insurance, lending, appraisal or personalized investment advice. All worked numbers are hypothetical. No booking, payout, permit, tax benefit or return is guaranteed.</p>'''

if __name__ == '__main__':
    refresh(slug=SLUG, title=TITLE, h1=H1, description=DESCRIPTION, body=BODY,
            search_terms='calendar purchase premium future bookings incremental value',
            hub_attribute='data-calendar-value-link',
            hub_block='<p data-calendar-value-link>Does a seller want a premium for future bookings? Compare <a href="/blog/future-booking-calendar-value/">documented calendar contribution with a fresh-launch alternative</a> before adding booked revenue to your STR offer.</p>')
