"""One existing furnished/empty transaction comparison, not a new inventory owner."""
from refresh_dscr_purchase_methods import refresh
BODY='''<p class="lead">When selling an STR furnished or empty, compare the actual buyer's use plan, documented inventory, transaction terms and both sides' cash. For the investor preparing to buy, a higher furnished price may still require less opening cash—but only when the included items are usable, truly transfer and replace costs the buyer would otherwise incur.</p>
<p>Neither original retail receipts nor attractive listing photos establish a premium, financing treatment or an earlier opening. Request evidence and compare written alternatives before committing. This is a transaction-choice worksheet, not an appraisal or a reason to add the seller's historical furnishing spend to the real-estate price.</p>
<h2 id="choices">Define furnished and empty alternatives precisely</h2>
<p>Put both proposed offers beside the same address. For a furnished option, identify the item schedule, accepted condition, exclusions, ownership questions, possession date and remaining buyer work. For an empty option, specify what the seller removes, what remains as part of the property, the agreed condition after removal and what the buyer must install. Do not use “everything stays” as the entire agreement.</p>
<div class="table-wrap"><table><thead><tr><th>Comparison field</th><th>Furnished proposal</th><th>Empty proposal</th><th>Evidence before relying on it</th></tr></thead><tbody>
<tr><td>Price and financing</td><td>Package price and proposed asset allocation</td><td>Price with specified removals</td><td>Lender and closing review of actual terms, collateral and cash—not a universal loan percentage</td></tr>
<tr><td>Usable assets</td><td>Included items the buyer can accept</td><td>Remaining fixtures and excluded loose items</td><td>Item schedule, ownership/condition evidence and adviser-reviewed documents</td></tr>
<tr><td>Make-ready cash</td><td>Repair, cleaning, replacements and gaps after handoff</td><td>New purchases, delivery, assembly and preparation</td><td>Complete separate quotes, avoiding overlapping charges</td></tr>
<tr><td>Seller outflows</td><td>Accepted preparation or removal exceptions</td><td>Removal, storage, disposal or other agreed work</td><td>Actual payer, amount and payment date</td></tr>
<tr><td>Time and control</td><td>Possession plus necessary work before opening</td><td>Possession plus procurement and setup</td><td>Confirmed schedule, permissions and named owner; no assumed faster sale or launch</td></tr>
</tbody></table></div>
<p>The <a href="/blog/str-furniture-bill-of-sale/">furniture transfer and acceptance guide</a> supplies the detailed room-level record and missing-item handoff checks. This page instead compares transaction alternatives. Seller-owned usable items, rented equipment, manager supplies and excluded possessions must not be treated as one transferable package.</p>
<h2 id="seller-cash">Worked seller comparison: the package label is not net proceeds</h2>
<p><strong>Hypothetical only:</strong> no real offers, current market prices, provider fees or client outcomes are represented. Assume a $510,000 furnished offer and a $500,000 empty offer. Stipulate $30,000 total seller sale expenses and a $330,000 loan payoff in each case. The empty option also requires a distinct $4,000 removal bill, while the furnished option requires no additional seller work in this simplified case.</p>
<p>Furnished cash before seller income taxes and unmodeled obligations is $510,000−$30,000−$330,000=$150,000. Empty cash is $500,000−$30,000−$330,000−$4,000=$136,000. The difference is $14,000: $10,000 price plus $4,000 avoided removal. If the furnished documents describe an $18,000 inventory allocation already within the $510,000 price, it is not another $18,000 receipt. The example does not authenticate that allocation.</p>
<p>Replace the stipulated expenses with actual quotes, payoff statements, taxes, contract obligations and dates. This net-cash test does not establish taxable gain, the appropriate asking price or the probability that either offer closes. A different buyer or additional seller preparation can change the result. A seller's old $100,000 furnishing receipt total cannot answer those questions by itself.</p>
<h2 id="buyer-cash">Worked buyer comparison: a higher price can require less opening cash</h2>
<p>Use the same fictional alternatives, but assume separately reviewed lender proposals require $150,000 buyer price cash for furnished and $147,000 for empty. These are stipulated cash requirements, not standard down-payment rules, accepted appraisal values or proof that furniture is financeable. Buyer closing/finance outflows are $15,000 in each case. Complete setup is $8,000 for the furnished option versus $32,000 for empty. Both plans retain a protected $40,000 reserve.</p>
<div class="table-wrap"><table><thead><tr><th>Buyer capital allocation</th><th>Furnished</th><th>Empty</th></tr></thead><tbody>
<tr><td>Buyer price cash</td><td>$150,000</td><td>$147,000</td></tr>
<tr><td>Closing/finance outflows</td><td>$15,000</td><td>$15,000</td></tr>
<tr><td>Complete remaining setup</td><td>$8,000</td><td>$32,000</td></tr>
<tr><td>Retained reserve</td><td>$40,000</td><td>$40,000</td></tr>
<tr><td>Total allocated capital</td><td>$213,000</td><td>$234,000</td></tr>
<tr><td>Margin versus $225,000 available</td><td>$12,000</td><td>−$9,000</td></tr>
</tbody></table></div>
<p>The furnished option requires $21,000 less on these assumptions: $24,000 less setup offsets $3,000 more buyer price cash. That is avoided spending within the comparison, not a bank deposit or a used-furniture valuation. Reserve cash is counted once as retained allocation, not expensed and subtracted again. Neither reserve amount nor positive margin establishes an adequate investment plan.</p>
<p>Now assume the final inventory review finds missing or unsuitable included items requiring a distinct $7,000 replacement cost, not already inside the $8,000 setup. Furnished allocation rises to $220,000 and margin falls to $5,000. A separate $3,000 net carrying-cost delay raises it to $223,000 with $2,000 remaining. Do not assume a later seller reimbursement pays an earlier vendor invoice. Another $5,000 distinct bill would create a $3,000 funding gap if the reserve remains protected.</p>
<h2 id="review">Price, allocation and permission are separate reviews</h2>
<p><a href="https://www.irs.gov/publications/p551" target="_blank" rel="noopener">IRS Publication 551 (December 2025)</a> explains allocating a lump-sum acquisition among assets received. Have the CPA determine treatment from the actual transaction; a replacement budget is not established tax basis. The <a href="/blog/cost-seg-furnishings-allocation/">asset-cost reconciliation guide</a> handles source records and duplicate costs separately.</p>
<p>Have the lender and closing professionals review any personal-property terms or proposed credit before relying on the financing plan. Do not invent an appraisal exclusion, a financing allowance or permission for an undisclosed side payment. The <a href="/blog/appraisal-gap-furnished-str/">furnished appraisal-gap worksheet</a> addresses a different question: cash needed when actual accepted collateral or funding differs.</p>
<p>Included beds, amenities or a prior listing do not establish lawful occupancy or STR permission. Verify address-level use, insurance, possession and opening tasks. A furniture package does not transfer a seller's platform account, reviews, reservations or other rights merely because those appear in the marketing; investigate each separately with authorized records and appropriate advisers.</p>
<h2 id="decision">Choose an evidence-supported transaction, not a turnkey adjective</h2>
<p>Proceed when both the accepted package and remaining work fit verified financing, cash and permissions. Negotiate documented exceptions through the actual contract and qualified professionals; do not assume a right to new retail replacements, cancellation or a fee waiver. Compare an empty purchase when the included package does not fit, and decline a purchase that depends on unverified assets or unfunded opening costs.</p>
<p>BNB Accelerator is the interested acquisition-service publisher. This is an original document-based planning worksheet, not firsthand provider testing, an appraisal or a custom contracted report. Ask which inventory and transaction-comparison tasks the signed acquisition scope includes. If you plan to buy within zero to six months, <a href="/apply/">bring the two written alternatives and remaining setup quotes to an acquisition discussion</a>.</p>
<p class="small">Source review: October 7, 2026. Current IRS Publication 551 is the December 2025 edition; it supports only the bounded basis-allocation discussion, not hypothetical valuations or lender figures. Educational only, not personalized tax, legal, lending or investment advice. No sale premium, earlier opening, refund, financing or investment result is guaranteed.</p>
'''
FAQ=[('Does the seller’s original furniture spend establish the package price?','No. Compare documented usable inventory, accepted condition, ownership and the actual buyer replacement scope. Original retail spending does not establish today’s transaction premium or tax allocation.'),('Can a higher furnished price require less buyer cash?','It can under particular written financing and setup assumptions. The hypothetical example requires $213,000 allocated capital furnished versus $234,000 empty; replace those inputs with actual terms rather than assuming a universal result.'),('Is an inventory allocation extra sale cash?','Not when it is already included in the agreed package price. The example’s proposed $18,000 allocation is not another receipt and is not authenticated tax basis.'),('What if included items are missing at handoff?','Document the exception and replacement cash, then ask the transaction professionals what the actual contract permits. Do not assume reimbursement, cancellation rights or new retail replacements; check payment dates and preserve your reserve.')]
if __name__=='__main__':
 refresh('sell-str-with-furniture','Should You Sell an STR Furnished or Empty | BNB Accelerator','Should You Sell an STR Furnished or Empty?','Compare furnished and empty STR offers using documented inventory, seller proceeds, buyer setup cash and financing review—not original retail receipts.',BODY,FAQ,'2026-09-23','data-furnished-sale-review-link','Compare <a href="/blog/sell-str-with-furniture/">furnished versus empty transaction cash</a> before accepting a package. Included inventory can change setup spending but is not extra bank cash or a guaranteed premium.')
