#!/usr/bin/env python3
"""Dated, provider-specific comparisons. Run after gen_compare/gen_alternatives.
Keep one owner URL per comparison/alternatives/contract task; no review clones.
"""
import json, re, sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).parent))
import tpl
from pillars import write
from gen_alternatives import PAGES
ROOT=Path(__file__).resolve().parent.parent
DATE='2026-10-01'
EXTRA=[
 ('elk-ridge-investments','Elk Ridge Investments','managed STR ownership participation','https://www.elkridgeinvestments.com/service/','/compare/elk-ridge-investments/',
  'Do you want managed ownership participation or to approve and buy your own first STR?',
  'Elk Ridge describes capital allocated into professionally managed STR real estate, acquisition through operation and exit, ownership participation, reporting and K-1 issuance. The specific legal ownership, voting rights and exit terms must come from the actual offering documents.',
  [('BNB Accelerator','Buyers who want to approve a specific property and coordinate its purchase and launch.','Confirm the deed or entity structure, scope and separately selected operating agreement.'),('A managed STR offering','Investors who want a sponsor to select and operate assets.','Compare offering documents, fees, distribution policy, reporting and redemption rights.'),('An independent direct purchase','Buyers who want to assemble their own agent, lender and local manager.','You coordinate the search and retain property and vendor decisions.')],
  'Who owns the asset, who controls a sale or refinance, and what rights does the investor have if priorities change?'),
 ('str-search','STR Search','property matching and acquisition analysis','https://strsearch.com/','/compare/str-search/',
  'Do you want a property-matching and analysis service, or a written purchase-to-launch coordination scope?',
  'STR Search markets property matching, data analysis and the Bianchi Method. Its public site distinguishes analysis from a realtor’s transaction role. Confirm exactly which closing, furnishing and operating tasks your proposed tier includes.',
  [('BNB Accelerator','Buyers seeking a coordinated sourcing, underwriting, purchase and launch engagement.','Request a sample deal memo and named owners for closing and launch tasks.'),('STR Search plus local execution','Buyers who want property matching and will arrange any excluded transaction and launch work.','Confirm what the match service includes, the selection conditions and total cost.'),('STR agent plus independent analyst','Buyers who want to hire representation and underwriting separately.','Reconcile assumptions and decide who resolves discrepancies before the offer.')],
  'Does a property match mean a screened listing, an accepted offer, a closing or a live rental, and who owns the work between those milestones?'),
 ('bnb-turnkey','BNB Turnkey','acquisition and management coordination','https://bnb-turnkey.com/services','/blog/bnb-accelerator-vs-bnb-turnkey-str-buyer/',
  'Do you want a coordinated management path after closing or to choose the operator separately?',
  'BNB Turnkey publishes property research, evaluation, inspection and negotiation, design and furnishing, and a management path. Its pre-call material names a management partner. Verify the legal entities and whether that manager is required in your proposal.',
  [('BNB Accelerator','Buyers seeking acquisition and launch coordination with an independently confirmed operating plan.','Verify how management introductions work and which vendors you contract with.'),('BNB Turnkey','Buyers who want to evaluate a connected acquisition and management proposal.','Obtain separate acquisition and management agreements, fee bases and cancellation terms.'),('Local STR agent and manager','Buyers with a chosen market who prefer independently selected specialists.','Assign furnishing, permit verification and the operating handoff explicitly.')],
  'Can I replace the manager without losing listing access, payout records, vendor contacts or the launch support I paid for?'),
 ('kleer-circle','Kleer Circle','acquisition with a self-operation playbook','https://kleercircle.com/','/blog/bnb-accelerator-vs-kleer-circle-str-buyer/',
  'Will you operate your first STR in year one or hire a manager from the outset?',
  'Kleer Circle describes market selection, underwritten deal rounds, transaction coordination, design and listing setup, and a year-one self-operation playbook. Its FAQ describes management introductions later. Confirm any exception in writing before deciding.',
  [('BNB Accelerator','Buyers who want acquisition coordination and to evaluate a local manager or co-host for launch.','Budget the actual operator agreement and confirm the handoff scope.'),('Kleer Circle','Buyers willing to operate in year one using configured systems.','Document buyer hours, guest coverage and the terms for changing the operating model.'),('Agent plus operating coach','Buyers who want separate transaction representation and self-management training.','The buyer must integrate the analysis, vendor schedule and opening plan.')],
  'Who handles a guest emergency in year one, and what happens if I need full management sooner than planned?'),
 ('str-insights','STR Insights','deal data and acquisition service tiers','https://www.strinsights.com/introduction','/blog/bnb-accelerator-vs-str-insights-buyer/',
  'Are you buying portal access, an analysis consultation, or an acquisition-and-launch engagement?',
  'STR Insights publishes a property-deals portal and software, and separately describes a turnkey acquisition path with deal selection, analysis, inspection, negotiation, design and setup. Match your comparison to the tier quoted to you.',
  [('BNB Accelerator','Buyers who want sourcing and purchase-to-launch coordination.','Compare the written service agreement and sample property memo.'),('STR Insights acquisition service','Buyers seeking the company’s higher-touch purchase path.','Make the proposed tier and every included deliverable explicit.'),('Portal plus independent specialists','Buyers who want to screen deals and direct the purchase themselves.','Data access does not establish responsibility for contract deadlines or launch.')],
  'Which tier assigns a person to inspection issues, offer negotiations, legal-use checks and the opening budget?'),
 ('michael-elefante','Michael Elefante / BNB Investor Academy','STR education and mentorship','https://info.bnbinvestoracademy.com/info','/compare/michael-elefante/',
  'Do you want to learn acquisition and operating skills or hire a team to coordinate this purchase?',
  'BNB Investor Academy’s public material presents Michael Elefante’s education for acquiring, designing and managing STRs. Treat a course, mentorship and any separately offered done-for-you service as different contracts.',
  [('BNB Accelerator','Buyers with purchase capital who want coordinated execution.','You still approve the property and fund acquisition and launch.'),('BNB Investor Academy','Buyers who want instruction and intend to apply the skills themselves.','Confirm coaching access, feedback on your real deal and current enrollment terms.'),('Independent study plus local specialists','Buyers who can build the learning plan and execution team.','You own the quality of the underwriting and each vendor handoff.')],
  'Will someone deliver work on my actual purchase or teach me to do that work, and what is guaranteed in the contract?'),
 ('real-estate-robinsons','The Real Estate Robinsons','Alpha Host coaching and resources','https://therealestaterobinsons.com/','/compare/real-estate-robinsons/',
  'Do you need mentorship to become an operator or specialists to coordinate a purchase now?',
  'The Real Estate Robinsons publish STR resources and feature Alpha Host mentorship. The site also lists separate services and investing links. Confirm which business, product and scope you are comparing.',
  [('BNB Accelerator','Buyers seeking a defined acquisition and launch engagement.','Get written deliverables and budget all property costs separately.'),('Alpha Host mentorship','Buyers who want coaching while building their own Airbnb business.','Confirm deal-specific feedback, access and work you must execute yourself.'),('Local agent and operating specialist','Buyers who want selected help on an active listing.','The buyer coordinates the timetable, quotes and decisions.')],
  'Which purchased product includes analysis of my address, and which transaction or launch tasks remain mine?'),
 ('str-university','STR University','Richard Fertig’s STR education','https://www.str.university/courses','/compare/str-university/',
  'Do you want a self-paced buying course or active help executing an STR purchase?',
  'Richard Fertig’s STR University course page describes self-paced finding-and-buying education. It also retains a cohort announcement referring to 2021. Confirm current enrollment, curriculum and support directly; do not treat that old announcement as a current price or start date.',
  [('BNB Accelerator','Buyers who want sourcing and transaction-to-launch coordination.','Ask for current scope and a property-specific decision file.'),('An available STR University course','Buyers who prefer structured study before choosing a property.','Verify that enrollment and support are active and relevant to current rules.'),('Current lender, agent and local professional guidance','Buyers who need answers for a specific purchase.','Advice from several professionals still needs a buyer-owned decision plan.')],
  'Is this course currently supported, and who will answer a question about my live offer before its deadline?'),
 ('str-profit-academy','STR Profit Academy','historical STR coaching program','https://shows.acast.com/get-paid-for-your-pad/episodes/blueprint-to-launch-scale-an-str-business','/compare/str-profit-academy/',
  'Are you seeking a currently available coaching program or an acquisition team for a first purchase?',
  'The Get Paid for Your Pad episode describes STR Profit Academy as a masterclass in a historical program announcement. That establishes historical education context, not current enrollment, fees or an acquisition service. Verify today’s offer directly before paying.',
  [('BNB Accelerator','Buyers ready to fund a property and seeking acquisition coordination.','Confirm current market fit, deliverables and operating handoff.'),('A currently verified coaching program','Buyers who need structured learning and live deal feedback.','Get written enrollment, support and refund terms for the program actually sold today.'),('Independent purchase team','Buyers who want agents, lenders and operators engaged directly.','You set the schedule and hold each specialist accountable.')],
  'What exact product is currently sold, who supports it, and does it teach purchases or execute any work on mine?'),
]
ALL=PAGES+EXTRA
# Correct the older Rabbu description to its broader, currently published scope.
ALL=[(r[:2]+('STR marketplace and optional buyer assistance','https://rabbu.com/about',)+r[4:6]+('Rabbu describes a marketplace, market and revenue tools, agent and lender connections, and optional search consultants from market selection through closing. Tools and done-for-you help are different service levels; obtain the scope for the one you intend to use.',)+r[7:]) if r[0]=='rabbu' else r for r in ALL]
# Each alternatives guide has an original, provider-specific decision exercise.
EXERCISES={
 'the-short-term-shop':('Brokerage representation versus project coordination','Make two columns for one selected market: the agent’s representation agreement and the acquisition coordinator’s scope. Put legal-use verification, the revenue memo, insurance quotes, furnishing orders and opening readiness under a named person. Brokerage can be sufficient if your other specialists are already selected. Pay for extra coordination only where the proposal closes a real gap.', ['Signed representation terms','Address-level decision memo','Named launch coordinator']),
 'techvestor':('Portfolio exposure versus one-property control','Compare a portfolio subscription with a direct purchase using the same amount of available capital. The portfolio case needs distribution policy, liquidity restrictions and investor rights. The property case needs cash to launch, reserves, an operator and an exit estimate. Do not assume a portfolio interest gives you control over a specific house or that a single house offers diversification.', ['Offering and subscription documents','Distribution and redemption policy','Direct-property cash and operator plan']),
 'airdna':('Forecast confidence versus executed diligence','Choose one active listing and recreate its revenue estimate using comparable properties of similar bedroom count, legal occupancy, location and amenities. Then add address-specific taxes, insurance, repairs, HOA charges, financing and management. A data subscription is enough only when you can perform and coordinate those remaining checks before contingencies expire.', ['Comparable listing set','Address-specific expense quotes','Offer and contingency calendar']),
 'rabbu':('Free research versus a paid search engagement','Screen a listing with the marketplace and calculator, then request the scope of any optional search consultant. Mark which assumptions are estimates and which have been checked against records. Require a named owner for permit questions, inspections and closing tasks. Compare the paid tier with another written acquisition proposal rather than equating every tool user with a managed purchase client.', ['Exact tier and compensation disclosure','Verified versus estimated inputs','Search and closing deliverables']),
 'awning':('Connected search and management versus independent vendors','Ask the buying contact and the management contact to quote the same address. Separate representation costs from setup, recurring management charges and excluded services. Confirm availability with the actual local operator and ask whether buying assistance depends on a management contract. Choose a connected provider only if both contracts suit the property and your intended control.', ['Local coverage confirmation','Acquisition and management agreements','Fee base and termination rights']),
 'bnb-mastery':('Operating skill versus property ownership','Write your desired outcome before selecting a program: buying a deed, leasing with permission to sublet, or managing someone else’s rental. Those require different capital and agreements. A co-hosting course can suit a service-business goal without being an acquisition alternative. If ownership is the goal, retain a lender-approved budget and a buyer-owned purchase schedule.', ['Desired ownership or business model','Current curriculum and coaching scope','Property-purchase capital plan']),
 'robuilt':('Creative development versus buying an existing home','Take one distinctive-stay concept and one existing rental candidate. The development case needs land-use feasibility, construction quotes, utility access and holding costs through opening. The existing-home case needs permission, condition, furnishing gaps and a transition plan. Coaching can develop your project skill; it does not remove those costs or transfer project responsibility.', ['Permits and utility feasibility','Build or repair quotes','Zero-revenue holding budget']),
 'rent-to-retirement':('Inventory purchase versus an STR-specific search','Select one available inventory property and one independently sourced STR candidate. Confirm the permitted rental use and model each using its own income and expenses. Identify who is paid by the seller, who provides representation and whether management is tied to purchase. A packaged long-term rental may fit your plan better; never convert its advertised numbers into an Airbnb forecast.', ['Inventory and seller disclosures','Rental-use-specific underwriting','Independent condition and value checks']),
 'alpha-geek-capital':('An offering interest versus a directly selected asset','Compare the exact fund or single-asset offering with buying an individual house. List voting rights, financing liability, operating control, capital calls and exit authority on both sides. An LLC interest can confer economic ownership without unilateral authority over sale or refinancing. Your advisers should read the documents before you value any potential tax allocation.', ['Current offering terms','Control and capital-call provisions','Exit and reporting rules']),
 'elk-ridge-investments':('Managed participation versus your own purchase','Map the actual deed, owning entity and investor interest before comparing either proposal. Request voting, capital-call, distribution and exit provisions for participation. For a direct purchase, document your financing and operator choices. If being able to choose or sell one property is essential, resolve that right before comparing projected income or depreciation.', ['Ownership and governing documents','Capital-call and exit provisions','Named operator and reporting duties']),
 'str-search':('What counts as a completed property match?','Define four milestones: screened listing, buyer approval, accepted offer and live rental. Have the provider place its obligations and any match conditions next to each. A listing can match a model and still fail inspection, insurance or legal-use checks. Your agreement should show who resolves that failure and what support remains when the first candidate is rejected.', ['Matching criteria and remedy','Deal evidence and rejected-property rules','Closing and launch responsibility map']),
 'bnb-turnkey':('A management transition you can actually control','Assume you need to change managers six months after opening. Walk through account permissions, payout access, cleaner contacts, furniture ownership, future bookings and vendor contracts. Obtain the actual termination notice, fees and transfer process. A combined-looking pitch is useful only when the acquisition and operating agreements work together without unclear lock-in.', ['Management entity and fee base','Account and record access','Termination and handoff provisions']),
 'kleer-circle':('Your first-year operating capacity','Build a seven-day duty roster for guest messages, cleaning inspections, repairs, pricing and payout reconciliation. Put a primary and backup person next to each, including holiday coverage. Price those services instead of treating automation as zero labor. If you cannot staff the roster, confirm a management exception or compare another operating model before offering.', ['Buyer and backup duty roster','Actual software and vendor costs','Written management-change terms']),
 'str-insights':('Which product buys accountability?','Put the portal, consultation and acquisition proposal on separate rows. For each, ask who checks an address, who prepares a complete model, who attends the inspection decision and who tracks closing and opening. Select the least extensive tier that covers your gaps. A screen full of deals is useful research, but does not alone establish contract-to-close responsibility.', ['Exact product tier','Deliverables and exclusions','Named transaction and launch owners']),
 'michael-elefante':('Mentorship outputs versus completed tasks','Ask a mentor to define what happens when you submit a live listing: feedback call, edited model, permit-check review or actual execution. Then compare that with an acquisition service’s delivered documents and coordination. Choose education if you want to build repeatable skills and have time to execute; choose professional help for specific work you cannot staff.', ['Current support and curriculum','Actual-deal feedback process','Buyer execution calendar']),
 'real-estate-robinsons':('Choose the product, not just the public brand','Separate Alpha Host mentorship, public resources, design or cleaning services and an investment offer. The same public brand can link to products with very different obligations. Write down the legal entity, promised output and customer work for the exact product quoted. Do not infer acquisition execution from a coaching, event or design purchase.', ['Exact product and contracting entity','Promised output and exclusions','Purchase and launch responsibilities']),
 'str-university':('Confirm active support before buying education','Use the course page as a starting point and request current dates, curriculum updates, support contact and refund terms. A historical cohort announcement is not evidence of a live intake. If a listing is already under contract, confirm whether help can arrive before the diligence deadline; otherwise hire the appropriate specialist for that decision.', ['Current enrollment confirmation','Curriculum update and support details','Deadline-specific professional help']),
 'str-profit-academy':('Historical program name versus today’s offer','Identify the current seller and product before paying for something described in an old episode. Get today’s curriculum, support, price and cancellation terms in writing. If the goal is buying now, compare the current offer’s actual-deal feedback with an acquisition proposal. Historical success stories do not establish present service availability.', ['Current seller and contract','Active support and refund terms','Work performed on your actual deal']),
}
CHECKED={r[0]:DATE for r in ALL}
CHECKED['awning']='2026-09-27' # current re-fetch blocked; retain earlier verified scope
COMPARISON_SLUGS={r[0]:r[4] for r in ALL}
CONTRACTS={
 'elk-ridge-investments':('Elk Ridge Investments Ownership & Exit Questions','/guides/elk-ridge-investments-ownership-questions/','Read the actual ownership documents before joining a managed STR participation arrangement.', [
 ('What exactly will I own?','Request the deed, entity chart, subscription or purchase agreement and governing documents. Identify whether you hold a direct property interest, an LLC interest or another arrangement. Marketing language about ownership participation does not settle that question.'),
 ('Who can commit more capital?','Identify capital-call authority, payment deadlines, dilution or default remedies and limits on borrowing. Ask whether you can decline additional funding and what happens to the existing investment if you do.'),
 ('Who chooses the exit?','Record sale, refinance and redemption rights separately. Ask whether an investor can request an exit, what approval is required, which charges apply and how value is determined. A proposed exit schedule is different from an enforceable liquidity right.'),
 ('What reporting reaches my advisers?','Request a sample investor report, financial statements and a tax-reporting timetable. Have your own CPA assess eligibility and allocation questions from the actual documents; K-1 issuance alone does not establish usable personal tax deductions.')]),
 'str-search':('STR Search Property Match: Questions Before Signing','/guides/str-search-property-match-questions/','Translate a property-match pitch into screening criteria, evidence and enforceable deliverables.', [
 ('What counts as a match?','Write down budget, market, property type, financing, legal use and acceptable downside. Ask what milestone satisfies the service: delivery of a listing, buyer acceptance, an offer or a closing. Confirm conditions and any remedy in the agreement.'),
 ('What happens when a matched house fails diligence?','Request rejected-deal examples and rules for a property that fails insurance, inspections, permit checks or lender approval. Ask whether another search is included and whether the service period or fee changes.'),
 ('Can I recreate the revenue model?','Ask for the comparable set, monthly seasonality, adjustments, expense base and sensitivity case. Treat a model as an estimate and connect important seller claims to records. Ask who revises the model when quotes or inspection findings change.'),
 ('Who owns closing and launch?','Assign representation, inspection decisions, contingency deadlines, furnishing orders and opening readiness to named parties. Identify included coordination versus introductions. A matching service need not cover all of those tasks.')]),
 'bnb-turnkey':('BNB Turnkey Management & Handoff Questions','/guides/bnb-turnkey-management-handoff/','Price the operating agreement and preserve access before choosing a connected acquisition path.', [
 ('Which company manages the property?','Get the legal name and local contact from the actual agreement. Confirm market availability, authority over pricing and vendor selection, and emergency coverage. A named partner in marketing does not establish your contract.'),
 ('What is the fee charged on?','Request gross versus net definitions, cleaning-fee treatment, minimum charges, onboarding, supplies, maintenance markups and excluded services. Use the same revenue case when comparing a separate operator.'),
 ('Who owns accounts and records?','Document listing control, access to booking and payout records, photography rights and software subscriptions. Confirm what remains accessible after termination and who handles existing guests during transfer.'),
 ('How do I change operators?','Read notice periods, termination charges, booking obligations and vendor handoff duties. Test a hypothetical transition six months after opening before committing to the purchase-and-management combination.')]),
 'kleer-circle':('Kleer Circle Year-One Self-Management Questions','/guides/kleer-circle-year-one-operations/','Test whether the year-one operating model fits your time and backup coverage.', [
 ('What work stays with me?','Ask for the daily and weekly duty list behind the operating playbook: guest responses, cleaners, repairs, pricing and bookkeeping. Identify service targets and what the systems automate versus what a person must decide.'),
 ('Who covers nights and holidays?','Name a local primary and backup for lockouts, heating failures and cleaning issues. Get actual availability and prices. A configured messaging system cannot itself repair a failed heater.'),
 ('What does self-operation really cost?','Budget software, cleaning quality checks, maintenance dispatch, backup coverage and buyer time. Compare that case with a written manager quote. Keep labor assumptions separate from provider fees.'),
 ('Can I change the year-one model?','The public FAQ describes first-year buyer operation and management introductions later. Ask for any exception in writing, who approves it, which support changes and what additional costs apply. Ask your own CPA how the actual work pattern affects your situation.')]),
 'str-insights':('STR Insights Portal vs Acquisition Service Questions','/guides/str-insights-service-tiers/','Select a tier by delivered work and accountability, not by the number of listings available.', [
 ('Which tier am I paying for?','Have the proposal name portal access, consultation, property finding or acquisition-and-launch execution explicitly. A description on another service page is not evidence that it is included in your purchase.'),
 ('Who checks a candidate address?','Identify responsibility for legal-use questions, condition, comparable selection and lender assumptions. Ask which checks are performed versus referred to specialists and how findings reach the buyer.'),
 ('Who acts while the contract is live?','List the agent, inspector, lender and acquisition coordinator next to each deadline. Ask who updates the model, recommends a repair request and confirms when contingencies are ready to expire.'),
 ('What is delivered at opening?','Request the furnishing scope, invoices, listing-access handoff, pricing setup, operating agreement and unresolved-items list. Clarify support duration and exclusions for the specific service tier.')]),
}
def esc(s):return tpl.esc(s)
def published(path, fallback=DATE):
 p=ROOT/path.strip('/')/'index.html'
 if p.exists():
  m=re.search(r'"datePublished"\s*:\s*"([^"]+)"',p.read_text());return m[1] if m else fallback
 return fallback
def section(h,p):return f'<section class="section-sm"><div class="wrap wrap-narrow"><h2>{esc(h)}</h2>{p}</div></section>'
def page(path,title,desc,body,pub=None):
 trail=[('Home','/'),('Compare','/compare/'),(title,path)]
 schema=tpl.graph(tpl.breadcrumb_schema(trail),tpl.ORG_SCHEMA)+'\n'+tpl.article_schema(title,desc,tpl.SITE+path,pub or published(path),DATE,section='STR Buyer Comparisons')
 write(path,tpl.page(title=title,description=desc,path=path,body=body,extra_schema=schema,active='/compare/',body_class='buyer-compare',transparent=True))
def hero(h,lead,label='First STR buyer comparison'):
 return f'<section class="hero hero-page"><div class="wrap"><a class="bc-back" href="/compare/">← All comparisons</a><div class="hero-inner"><span class="eyebrow">{esc(label)}</span><h1>{esc(h)}</h1><p class="lead">{esc(lead)}</p><div class="btn-row"><a class="btn btn-accent" href="/apply/">Discuss My First STR</a><a class="btn btn-ghost-light" href="/tools/first-str-purchase-budget/">Check My Purchase Cash</a></div></div></div></section>'
def source(r):
 return f'<p class="bc-source">Published by BNB Accelerator, an acquisition provider with a commercial interest in this comparison. Provider facts summarized from <a href="{esc(r[3])}" rel="noopener noreferrer">{esc(r[1])}’s public material</a>, reviewed {CHECKED[r[0]]}. Availability, fees and agreements may change. This is a public-offer comparison, not a customer review, independent ranking or endorsement. The companies are not affiliated. Verify the actual terms directly.</p>'
def links(r):
 g=CONTRACTS.get(r[0]);more=f' · <a href="{g[1]}">{esc(g[0])}</a>' if g else ''
 return f'<p><a href="{r[4]}">BNB Accelerator vs {esc(r[1])}</a> · <a href="/compare/alternatives-to-{r[0]}/">{esc(r[1])} alternatives</a>{more}</p>'
def alternatives(r):
 slug,name,cat,src,cmp,q,fit,opts,dil=r; h,exercise,records=EXERCISES[slug]
 cards=''.join(f'<article class="bc-option"><span class="eyebrow">Path {i}</span><h3>{esc(n)}</h3><p><strong>Fits:</strong> {esc(w)}</p><p><strong>Tradeoff:</strong> {esc(t)}</p></article>' for i,(n,w,t) in enumerate(opts,1))
 body=hero(f'Alternatives to {name}',q,'Alternatives · Purchase decision')
 body+=section('Start with the outcome you need',f'<p>{esc(fit)}</p><p>For a first STR, decide whether you want to select a particular home, own an interest in managed assets, or learn to execute the purchase yourself. These paths involve different control, capital and work. BNB Accelerator coordinates sourcing, underwriting, purchase and launch for a client-approved property; the signed scope defines the work included.</p>')
 body+=f'<section class="bg-alt"><div class="wrap"><h2>Three credible paths to compare</h2><div class="bc-grid">{cards}</div></div></section>'
 body+=section(h,f'<p>{esc(exercise)}</p><div class="bc-docs"><h3>Build this decision file</h3><ol>'+''.join(f'<li>{esc(x)}</li>' for x in records)+'</ol></div>')
 body+=section('Make the total cash comparable','<p>Use the same property price and current financing terms for direct-purchase proposals. Add down payment, closing, furnishing, repairs, quoted service fees and retained reserves. For an offering, separate the subscription amount from possible future capital obligations and liquidity restrictions. A lower fee is meaningful only when the missing work and buyer responsibilities are visible.</p><p><a href="/tools/first-str-purchase-budget/">Calculate first-STR purchase cash</a> and enter the fees actually quoted to you. Use conservative revenue and address-specific expense evidence; neither a provider’s case study nor potential tax savings funds your down payment.</p>')
 body+=section('Choose before you sign',f'<div class="callout"><p>{esc(dil)}</p></div><p>Proceed when the documents settle that question and the capital, scope and operating plan fit. Request a revision if duties or charges are vague. Pause when legal use, financing, insurance or operator capacity can change the purchase. Compare proposals on the same decision file and keep the right to reject an unsuitable property.</p>{links(r)}{source(r)}')
 body+=tpl.cta_band('Choose support for your first STR','Bring your available cash, target markets and the work you want the team to handle.',primary=('/apply/','Discuss My Purchase'),secondary=('/buy-a-short-term-rental/','First STR Roadmap'))
 page(f'/compare/alternatives-to-{slug}/',f'{name} Alternatives for First STR Buyers',f'Compare alternatives to {name}: service scope, buyer work, ownership and all-in cash. Choose help for your first STR purchase.',body)
def matchup(r):
 slug,name,cat,src,path,q,fit,opts,dil=r
 if path.startswith('/blog/'):return # preserve established, detailed owner URL
 rows=[('Service model','Sourcing, underwriting and purchase-to-launch coordination',cat),('Buyer decision','Client approves the property and commits purchase capital',q),('Work to document','Named purchase, launch and operator handoffs',dil),('Fees','Request current acquisition fee, exclusions and vendor disclosures','Request the actual tier, itemized charges and ongoing terms'),('Evidence','Property-level memo, full cash budget and downside case','Request the records listed below for your exact product')]
 table='<div class="bc-table-scroll" role="region" aria-label="Provider scope comparison" tabindex="0"><table><thead><tr><th scope="col">Decision</th><th scope="col">BNB Accelerator</th><th scope="col">'+esc(name)+'</th></tr></thead><tbody>'+''.join('<tr>'+''.join(f'<{tag}>{esc(v)}</{tag}>' for tag,v in [('th',a),('td',b),('td',c)])+'</tr>' for a,b,c in rows)+'</tbody></table></div>'
 h,exercise,records=EXERCISES[slug]
 body=hero('BNB Accelerator vs '+name,q)
 body+=section('The decision in plain terms',f'<p>{esc(fit)}</p><p>BNB Accelerator’s <a href="/how-it-works/">published process</a> describes coordinating a client-approved purchase and launch. Compare the service you would actually sign for, rather than comparing a brand’s entire website with one proposal. There is no universal winner: ownership rights, the work you want done and your operating capacity decide the fit.</p>')
 body+=f'<section class="section-sm bg-alt"><div class="wrap"><h2>Side-by-side buyer responsibilities</h2>{table}</div></section>'
 body+=section(h,f'<p>{esc(exercise)}</p><h3>Request these records</h3><ul>'+''.join(f'<li>{esc(x)}</li>' for x in records)+'</ul>')
 body+=section('Use one property and one budget','<p>Give each acquisition provider the same active listing, available cash, financing assumptions and intended operating model. Require an address-level permission plan, comparable revenue evidence, an expense model and a maximum offer under a downside case. If you are evaluating education or an offering, compare it to that purpose instead of expecting it to perform a transaction.</p><p>Budget the complete purchase with the <a href="/tools/first-str-purchase-budget/">first-STR cash planner</a>. Verify which professionals you contract with and who monitors contingencies. Financing approval, permits, bookings and investment outcomes remain property- and buyer-specific.</p>')
 body+=section('Which option fits your first purchase?',f'<p>{esc(opts[0][1])} {esc(opts[0][2])}</p><p>{esc(opts[1][1])} {esc(opts[1][2])}</p><p>Choose the proposal that assigns responsibility, explains its model and fits your cash and time limits. Do not sign merely because a sales timeline or tax illustration looks attractive.</p>{links(r)}{source(r)}')
 body+=tpl.cta_band('Test our acquisition scope on your purchase','Bring the same budget and candidate you are discussing with other providers.',primary=('/apply/','Compare My Purchase Plan'),secondary=('/compare/alternatives/','Browse Alternatives'))
 title=f'BNB Accelerator vs {name}: First STR Buyer Guide'
 page(path,title,f'Compare BNB Accelerator and {name} for your first STR: scope, buyer responsibilities, ownership, fees and purchase evidence.',body)
def contract(r):
 if r[0] not in CONTRACTS:return
 title,path,lead,items=CONTRACTS[r[0]]
 body=hero(title,lead,'Before signing · Contract questions')
 body+=section('Turn the proposal into a decision file',f'<p>This guide is for a buyer already considering {esc(r[1])}. It focuses on questions to resolve in the agreement, rather than ranking providers. {esc(r[6])}</p><p>Keep a four-column file: requested record, current answer, responsible person and deadline. An unanswered material question is a decision to defer, not a reason to invent a favorable assumption. Review the actual contract with the appropriate professional before funding.</p>')
 for h,p in items:body+=section(h,f'<p>{esc(p)}</p>')
 # A distinct, usable worksheet belongs to the particular provider's service model.
 rows=''.join(f'<tr><th scope="row">{esc(h)}</th><td>Document / clause / named owner</td><td>Resolved before payment or offer</td></tr>' for h,_ in items)
 body+=f'<section class="section-sm bg-alt"><div class="wrap"><h2>Your proposal review worksheet</h2><div class="bc-table-scroll" role="region" aria-label="Proposal review worksheet" tabindex="0"><table><thead><tr><th scope="col">Question</th><th scope="col">Evidence to record</th><th scope="col">Decision gate</th></tr></thead><tbody>{rows}</tbody></table></div></div></section>'
 body+=section('Use a missing-answer test','<p>Hypothetical example: the provider has explained its search or participation process, but has not documented who pays an unexpected $12,000 property cost. Keep that item unresolved until the governing agreement or a written scope revision identifies the responsible party and your exposure. Re-run available cash with the actual obligation; do not treat the brochure’s initial amount as a cap.</p><p>Proceed when material rights, duties and costs are documented and fit your plan. Request amendments for vague exclusions. Delay funding or an offer when a missing answer can change control, affordability or legal use. A favorable case study cannot substitute for your agreement.</p>')
 body+=section('Continue your buyer comparison',links(r)+source(r))
 body+=tpl.cta_band('Discuss the work you want done','We can explain our own acquisition scope, budget and professional handoffs.',primary=('/apply/','Discuss My First STR'),secondary=('/guides/str-service-responsibility-matrix/','Map Acquisition Duties'))
 page(path,title,lead,body)
def hubs():
 groups=[('Acquisition, brokerage and purchase platforms',['elk-ridge-investments','str-search','bnb-turnkey','kleer-circle','str-insights','the-short-term-shop','awning','rabbu','rent-to-retirement']),('Managed investment offerings',['techvestor','alpha-geek-capital']),('Education and mentorship',['bnb-mastery','robuilt','michael-elefante','real-estate-robinsons','str-university','str-profit-academy']),('Data for buyers',['airdna'])]
 body=hero('Compare help for your first STR purchase','Choose the work you need done, then compare the actual proposal: acquisition, representation, managed ownership, education or data.','Buyer decision library')
 body+='<section class="section-sm"><div class="wrap"><div class="bc-intro"><p>Start with the company you are evaluating. Each profile links to a direct comparison and an alternatives guide; selected acquisition teams also have a contract-question worksheet.</p><a class="btn btn-outline" href="/tools/first-str-purchase-budget/">Build My Purchase Budget</a></div><nav class="bc-jump" aria-label="Comparison categories">'+''.join(f'<a href="#category-{i}">{esc(h)}</a>' for i,(h,_) in enumerate(groups))+'</nav></div></section>'
 for i,(h,slugs) in enumerate(groups):
  cards=''
  for slug in slugs:
   r=next(x for x in ALL if x[0]==slug);g=CONTRACTS.get(slug)
   cards+=f'<article class="bc-option"><span class="eyebrow">{esc(r[2])}</span><h3>{esc(r[1])}</h3><p>{esc(r[5])}</p><div class="bc-card-links"><a href="{r[4]}">Compare with BNB Accelerator →</a><a href="/compare/alternatives-to-{slug}/">Explore alternatives →</a>'+ (f'<a href="{g[1]}">Questions before signing →</a>' if g else '')+'</div></article>'
  body+=f'<section id="category-{i}" class="bc-category"><div class="wrap"><div class="section-head"><span class="eyebrow">Choose your service model</span><h2>{esc(h)}</h2></div><div class="bc-grid">{cards}</div></div></section>'
 body+=section('How these comparisons are written','<p>BNB Accelerator publishes this section and has a commercial interest in offering its acquisition service. Provider descriptions link to public sources and state review dates. We compare the work, ownership model and questions a buyer should resolve; we do not assign unsupported scores or claim to have tested competitors as customers. Historical programs are labeled, and an unavailable price is left for a written quote.</p><p>Fees, service territories, personnel and support can change. The signed agreement and address-level checks control your decision. You may choose a competitor, assemble specialists yourself or defer the purchase if neither route fits.</p>')
 body+=section('Other buying approaches and research','<ul>'+''.join(f'<li><a href="/compare/{s}/">{n}</a></li>' for s,n in [('bnb-accelerator-vs-diy','DIY acquisition'),('bnb-accelerator-vs-real-estate-agent','Independent buyer agent'),('bnb-accelerator-vs-property-manager','Property manager'),('bnb-accelerator-vs-turnkey-providers','Turnkey property inventory'),('bnb-accelerator-vs-airbnb-arbitrage','Rental arbitrage'),('best-done-for-you-airbnb-companies','Done-for-you company selection'),('markets','Market comparisons'),('zuubly','Review publishers')])+'</ul>')
 body+=tpl.cta_band('Bring a purchase plan, not just a provider name','Discuss your available cash, target market and who will operate the property.',primary=('/apply/','Discuss My First STR'),secondary=('/buy-a-short-term-rental/','Buyer Roadmap'))
 page('/compare/','STR Acquisition Companies & Alternatives | First Buyer Guides','Compare 18 STR providers, programs and tools by buyer responsibilities, ownership and cash. Explore alternatives and questions before signing.',body)
 altbody=hero('STR company alternatives for first-time buyers','Browse acquisition teams, brokerage, managed investment, education and data alternatives. Select the company whose proposal you are evaluating.','18 provider guides')
 for h,slugs in groups:
  altbody+=section(h,'<ul class="bc-alternative-list">'+''.join(f'<li><a href="/compare/alternatives-to-{s}/">Alternatives to {esc(next(r[1] for r in ALL if r[0]==s))}</a></li>' for s in slugs)+'</ul>')
 altbody+=section('Choose by your purchase task','<p>Use a direct comparison to evaluate two proposals. Use an alternatives guide to choose a service model or another purchase path. Use a contract-question guide when a proposal is already on the table. These are different buyer tasks; you do not need to read every page before deciding.</p><p><a href="/compare/">View the complete comparison directory</a> · <a href="/buy-a-short-term-rental/">Plan your first STR purchase</a></p>')
 page('/compare/alternatives/','STR Company Alternatives: 18 First-Buyer Guides','Alternatives to 18 STR providers and programs, including Elk Ridge, STR Search, Kleer Circle and BNB Turnkey. Compare ownership, execution and buyer work.',altbody)
def link_existing():
 for r in ALL:
  if not r[4].startswith('/blog/'):continue
  p=ROOT/r[4].strip('/')/'index.html';s=p.read_text();mark='<!-- competitor-paths:start -->'
  block=mark+section('Compare other paths before signing',links(r))+'<!-- competitor-paths:end -->'
  s=re.sub(r'<!-- competitor-paths:start -->.*?<!-- competitor-paths:end -->','',s,flags=re.S)
  s=s.replace('</main>',block+'\n</main>');p.write_text(s)
 # A prominent home discovery block, after first-purchase resources.
 p=ROOT/'index.html';s=p.read_text();s=re.sub(r'<!-- comparison-discovery:start -->.*?<!-- comparison-discovery:end -->','',s,flags=re.S)
 block='<!-- comparison-discovery:start --><section class="section-sm"><div class="wrap"><div class="bc-home-band"><div><span class="eyebrow">Choose your acquisition team</span><h2>Compare the help before you buy.</h2><p>Already considering another STR company? Compare ownership, scope and who handles the work after closing.</p></div><a class="btn btn-outline" href="/compare/">Compare STR Companies →</a></div></div></section><!-- comparison-discovery:end -->'
 s=s.replace('<!-- first-str:end -->','<!-- first-str:end -->'+block,1);p.write_text(s)
def main():
 for r in ALL:alternatives(r);matchup(r);contract(r)
 hubs();link_existing()
 print(f'Expanded {len(ALL)} provider paths; {len(CONTRACTS)} distinct contract guides; existing comparison URLs preserved.')
if __name__=='__main__':main()
