"""Scoped refresh of an existing financing intent; not a new expansion page."""
import expand_hold_period as renderer

renderer.SLUG='blanket-loan-vs-individual-mortgages-str'
renderer.TITLE='Blanket vs Individual STR Loans: Release-Cash Worksheet'
renderer.H1='Blanket loans vs individual mortgages for a short-term rental portfolio'
renderer.DESC='Compare STR portfolio financing before buying: collateral, guarantees, maturity and sale-release conditions, with a worked cash and remaining-pool worksheet.'
renderer.FAQ=[
('Do separate mortgages completely isolate each property’s risk?', 'No. Separate collateral does not establish the limits of personal guarantees, cross-default terms or shared borrower obligations. Have counsel review the actual documents alongside each lender’s written conditions.'),
('Can I sell one STR out of a blanket loan?', 'Only on the terms applicable to your loan and transaction. Obtain the release amount, fees, remaining-pool requirements, approval process and timing in writing before relying on sale proceeds.'),
('Does a blanket loan always have a short term or balloon?', 'No. Provider descriptions and products differ. Compare the actual maturity, amortization, rate period and prepayment conditions; a long amortization schedule alone does not prove a long maturity.'),
('Is the release payment my investment loss or taxable gain?', 'No. It is a settlement cash input under the stated assumptions. Loan balances, asset basis, tax character and total investment return require separate reconciliations.')]
renderer.BODY='''<p class="lead">Before financing another STR, compare the cash and contractual flexibility of separate mortgages with one facility secured by multiple properties. One payment can be convenient, but it does not prove lower total costs, protected personal assets or an easy sale of one rental. If your next acquisition depends on selling a property from the pool, test the written release conditions before committing that money. This guide provides a document register and hypothetical release-cash comparison—not a lender recommendation or an approval estimate.</p>
<p><a href="/apply/">Discuss the next acquisition with a funded budget and a lender-question list</a>. BNB Accelerator does not lend or arrange loans; financing terms and legal conclusions belong to the appropriate independent professionals.</p>
<h2>How each structure works</h2>
<p>With separate mortgages, review the note and security documents for each property. Each loan can have different qualification, payment, maturity and prepayment conditions. With a blanket facility, multiple properties secure one obligation or coordinated facility, and the documents govern how individual assets enter or leave it. Do not assume a product called a portfolio loan necessarily has the same structure as another lender's similarly named product.</p>
<p>Separate collateral and separate liability are different questions. An individual-property loan may still involve a personal guarantee, shared borrower obligations or cross-default provisions. Neither an LLC nor a one-property mortgage, by itself, proves that difficulties cannot affect other assets or financing. Counsel should identify the actual exposure, not infer it from the number of monthly statements. The <a href="/blog/personal-guarantee-llc-str-purchase-loan/">guarantee and entity guide</a> addresses the signer question separately.</p>
<p>Provider-specific example: <a href="https://visiolending.com/lending-process/">Visio's lending-process page</a> says entity owners must sign personal guarantees. That is a statement about that provider's process, not a universal requirement or a description of your proposed loan. Ask who signs, what obligations the document covers and what would release the signer.</p>
<h2>Where consolidation can help—and what to price</h2>
<p>A coordinated facility may simplify administration or support an acquisition plan using several stabilized properties. Request a dated comparison of every closing cost, ongoing reporting obligation, reserve requirement and later release fee. One closing does not eliminate separate title, valuation or legal work. A larger advertised loan amount is not unrestricted cash available for the next down payment.</p>
<p>Ask the lender to reconcile gross proceeds to existing payoffs, financing expenses, restricted reserves and cash actually disbursed. Match each outflow to the relevant property or facility and deduct it once. If stronger rentals support weaker ones in a pooled calculation, retain property-level operating downside as well: passing a combined test does not make the weaker purchase economically sound.</p>
<p><a href="https://www.corevestfinance.com/loan-types/rental-portfolio-loans">CoreVest's rental-portfolio description</a> lists multiple-property financing, several shorter term options and both recourse and non-recourse choices, with exceptions for the latter. Its <a href="https://www.corevestfinance.com/loan-types/short-term-rental-loans">STR product page</a> describes multiple-property financing with a thirty-year term. These are different product descriptions, not quotes or approval for your portfolio. Do not conclude that every blanket loan must have a short balloon—or that any STR qualifies for either product.</p>
<h2>Build a document register before the next offer</h2>
<div class="table-wrap"><table><thead><tr><th>Document or input</th><th>Written question</th><th>Acquisition consequence</th></tr></thead><tbody>
<tr><td>Note and collateral schedule</td><td>Which properties and obligations are actually covered?</td><td>Do not pledge an existing rental unintentionally</td></tr>
<tr><td>Guarantees and cross-default provisions</td><td>Who is responsible, under what triggers and for which obligations?</td><td>Have counsel review exposure beyond each property's lien</td></tr>
<tr><td>Release clause and transaction quote</td><td>What payment, costs, approvals and deadlines apply to this sale?</td><td>Do not earmark unapproved sale cash for the next purchase</td></tr>
<tr><td>Remaining-pool requirements</td><td>What coverage, value, concentration or reserve tests apply after release?</td><td>Test the portfolio without the departing asset</td></tr>
<tr><td>Maturity, amortization and prepayment</td><td>When is principal due, when can the rate change and what does exit cost?</td><td>Fund a timetable consistent with the actual debt</td></tr>
<tr><td>Closing proceeds and restrictions</td><td>Which amounts reach the buyer and which remain restricted?</td><td>Separate cash to close, launch cash and required reserves</td></tr>
</tbody></table></div>
<p>Record the document version, preparer, review date and unresolved issue beside each row. A preliminary term sheet is not the executed release right. Ask the lender and counsel to flag changes between quote and final documents while there is still a valid contractual decision window. Securely share financial and identity records through agreed channels, not public comments or casual messages.</p>
<h2>The sale-release cash worksheet</h2>
<p>Hypothetical arithmetic only, not a client result, current loan quote or typical release formula. Compare two alternative financing structures for the same assumed future $400,000 property sale. Assume $24,000 of distinct selling outflows in both cases. In the individual-loan case, the complete settlement payoff is $260,000, with no additional lender charge under these assumptions. In the blanket case, assume a transaction-specific $300,000 principal release payment and $5,000 of separate release costs. No percentage rule or provider program is implied.</p>
<div class="table-wrap"><table><thead><tr><th>Illustrative case</th><th>Sale cash before tax and other obligations</th></tr></thead><tbody>
<tr><td>Individual mortgage</td><td>$400,000 − $24,000 − $260,000 = $116,000</td></tr>
<tr><td>Blanket release before separate costs</td><td>$400,000 − $24,000 − $300,000 = $76,000</td></tr>
<tr><td>Blanket release including separate costs</td><td>$76,000 − $5,000 = $71,000</td></tr>
<tr><td>Assumed $95,000 next-purchase requirement</td><td>Individual case: $21,000 headroom; blanket case: $24,000 shortfall</td></tr>
</tbody></table></div>
<p>The $45,000 difference between $116,000 and $71,000 is a cash-availability difference, not automatically a loss: the higher principal payment also reduces debt. Tax provisions, remaining portfolio debt, original capital and operating flows are omitted. Replace every input with reviewed figures before judging affordability or return. An unresolved tax or payoff input is not zero. The $95,000 requirement is also invented; build your actual <a href="/blog/str-lender-reserve-requirements/">closing and reserve budget</a> independently.</p>
<h2>A second gate: does the remaining pool qualify?</h2>
<p>Continue the fictional blanket case with $900,000 of facility principal before release. If the entire $300,000 release payment is credited to principal and the $5,000 fee is separate, the remaining balance is $600,000. That calculation does not establish the remaining payment or approval. Request the lender's actual recalculation and accounting treatment.</p>
<p>Suppose, solely for illustration, the remaining properties produce $72,000 of lender-recognized annual net operating income and $60,000 of annual debt service, under a stipulated matching calculation basis. Coverage is 1.20. If this fictional agreement requires 1.25 after release, it would need $75,000 of recognized income at unchanged debt service—a $3,000 gap. These are invented conditions, not a CoreVest or Visio rule. STR income recognition and debt-service definitions must come from your lender.</p>
<p>Thus a buyer could afford the release payment yet fail the remaining-pool test. Do not manufacture extra income, assume further paydown produces a particular payment, or count on an available refinance. Ask for written alternatives and their costs. If release is unavailable, a whole-facility payoff or different transaction may be needed; neither is guaranteed to fit the next property's deadline.</p>
<h2>Rates, terms and prepayment</h2>
<p>Compare rate period, payment calculation, amortization and contractual maturity separately. A thirty-year amortization with earlier maturity can still leave principal due before your intended hold ends. A rate fixed through the full maturity avoids a scheduled rate reset within that period, but not higher insurance, taxes, repairs or a forced early-sale decision. Price the relevant prepayment conditions and release costs instead of treating one fixed-rate label as risk-free financing.</p>
<h2>How to decide</h2>
<p>Separate mortgages may fit staggered sales and different property plans, but confirm actual payoff and liability terms. A blanket facility may fit a documented coordinated hold, provided its release, reserve, reporting and downside conditions are acceptable. Compare written offers on the same proposed assets, dates and cash basis. The lower initial rate cannot decide an unfunded release or maturity problem.</p>
<p>Proceed when the next acquisition is funded without unapproved proceeds, the portfolio downside fits your limits and professionals have resolved decisive document questions. Reprice when verified financing costs change a viable deal. Seek a protected delay when critical lender review is incomplete; do not assume extension or cancellation rights. Decline a transaction that requires an unsupported release, refinance or tax receipt.</p>
<p><a href="/apply/">Bring the shortlist, actual capital timetable and financing comparison to an acquisition call</a>. Continue through the <a href="/blog/buy-str-high-income-large-tax-bill/">high-income buyer roadmap</a>. BNB Accelerator assists within its contracted acquisition scope; independent lenders and legal and tax advisers determine their respective conclusions.</p>
<p class="small">Primary lender pages reviewed October 7, 2026. Product descriptions can change and are not commitments to lend. Educational information only, not personalized investment, lending, legal or tax advice. All example amounts and qualification tests are hypothetical. No financing, release, refinance, sale, tax benefit or investment result is guaranteed.</p>'''

if __name__=='__main__':
 renderer.main('2026-09-24','data-blanket-review-link','Compare the <a href="/blog/blanket-loan-vs-individual-mortgages-str/">blanket-versus-individual release-cash worksheet</a> before funding the next purchase with proceeds from one portfolio property. Separate collateral, guarantees and remaining-pool conditions.')
