"""Source-checked deposit-income decision for an existing investor guide."""
from expand_reservations_closing import main

BODY='''<p class="lead">A bank-statement loan can be worth evaluating for an STR purchase when a self-employed buyer needs an alternative way to document business income. It is not permission to count every deposit as earnings, nor proof the rental is a good acquisition. Before making an offer, get the lender's accepted income calculation and investment-property terms, then test the same property against other available financing paths.</p>
<p><a href="/apply/">Book an STR acquisition call to match your verified business-income financing with a supportable property budget</a>.</p>
<h2>Confirm investment STR eligibility before calculating income</h2>
<p><a href="https://angeloakms.com/programs/bank-statement-mortgage-program/" rel="noopener">Angel Oak's published bank-statement program</a> describes personal or business statements over 12 or 24 months and lists investment properties among eligible uses. It describes a default 50% business expense factor, possible lower factors supported by a third-party professional statement and 70% for some higher-expense industries. These are that provider's published criteria, not a universal underwriting formula or approval for your address and intended short-term rental operation.</p>
<p>Ask the lender or authorized originator which current program accepts your occupancy, rental use, property type, title and business ownership. Confirm whether personal or business statements are needed, whose income is credited, and how ownership share affects the calculation. Do not assume a second-home illustration, a broker's generic preapproval or a “no tax returns” description means no documentation or no financial review. Supply accurate records and disclose the actual use.</p>
<p>If the issue is a short operating history rather than deposit treatment, use the separate <a href="/blog/buy-str-less-than-two-years-self-employed/">less-than-two-years self-employment guide</a>. This page focuses on transforming an existing statement history into an accepted financing decision, not changing business labels or bypassing history requirements.</p>
<h2>Reconcile deposits before applying an expense factor</h2>
<p>Prepare a dated account register showing the lender-requested period, account ownership, monthly deposits, proposed exclusions and supporting explanations. Ask how the lender treats transfers between your own accounts, loan proceeds, owner contributions, refunds, reversals and unusual receipts. Do not classify them yourself as qualifying income just because they increased a bank balance. Avoid counting a business deposit again when the same money is transferred to a personal account.</p>
<div class="table-wrap"><table><thead><tr><th>Evidence to provide securely</th><th>Question for the income calculation</th></tr></thead><tbody>
<tr><td>Complete requested statements and account ownership</td><td>Which accounts and months are accepted, and are any gaps unresolved?</td></tr>
<tr><td>Deposit ledger with transfer matches</td><td>Which deposits are eligible earnings rather than movements of existing cash?</td></tr>
<tr><td>Business ownership and current financial records</td><td>How are ownership, expenses, business debt and recent changes reflected?</td></tr>
<tr><td>Explanation and evidence for unusual receipts</td><td>Is this recurring supportable income, an excluded receipt or a reason for further review?</td></tr>
<tr><td>Authorized professional expense evidence if requested</td><td>Who may prepare it, what must it cover and does the lender accept the supported factor?</td></tr>
</tbody></table></div>
<p>A lender expense factor is not a recommendation to reduce real business expenses or alter tax reporting. It also does not establish freely distributable business cash. Preserve funds required for payroll, working capital and adviser-estimated taxes. Upload statements through approved secure channels; do not place account numbers, employee details or customer payment information in a public property worksheet.</p>
<h2>A deposit-to-income worksheet can change the buying budget</h2>
<p>All figures and rules in this worksheet are hypothetical, not Angel Oak underwriting, a current quote, an approval or a client result. Assume a fully owned business with $360,000 of deposits over 12 months. The hypothetical lender excludes $60,000 of matched transfers and non-income receipts, leaving $300,000 of accepted deposits. The average is $25,000 per month before a business expense adjustment.</p>
<div class="table-wrap"><table><thead><tr><th>Same deposits, two illustrative expense assumptions</th><th>50% expense factor</th><th>70% expense factor</th></tr></thead><tbody>
<tr><td>Monthly accepted deposits before expenses</td><td>$25,000</td><td>$25,000</td></tr>
<tr><td>Monthly income retained after factor</td><td>$12,500</td><td>$7,500</td></tr>
<tr><td>Other monthly debt assumed for this test</td><td>$3,000</td><td>$3,000</td></tr>
<tr><td>Proposed housing obligation assumed for this test</td><td>$2,500</td><td>$2,500</td></tr>
<tr><td>Total debt divided by modeled qualifying income</td><td>44.0%</td><td>73.3%</td></tr>
</tbody></table></div>
<p>For a purely illustrative 45% debt-to-income ceiling, the first column clears this isolated ratio test and the second does not. That ceiling is invented for the example, not a lender limit. The hypothetical maximum housing obligation would be $12,500 × 45% − $3,000 = $2,625 in the first case, but $7,500 × 45% − $3,000 = $375 in the second. Neither figure is a purchase-price approval. Actual debt treatment, other income, credit, loan terms, reserves and property eligibility still need lender review.</p>
<p>Use the expense percentage correctly: a 70% expense factor retains 30%, not 70%, of deposits. If ownership or evidence changes accepted income, rebuild the worksheet from the lender's written answer rather than preserving the more favorable column. Include all housing components the lender requires; principal and interest alone may not be the relevant payment.</p>
<h2>Compare available financing paths without confusing approval and return</h2>
<p>Request a conventional/full-documentation path if your file supports it, a bank-statement path if actually available, and a property-income path where appropriate. <a href="https://visiolending.com/dscr-loans/" rel="noopener">Visio's DSCR explanation</a> uses a rental-income-to-payment calculation. That alternative qualifying lens is not interchangeable with business deposit income. Ask each lender to identify its accepted inputs for this property; do not add unsupported projected Airbnb receipts to whichever formula otherwise fails.</p>
<p>Put available written quotes side by side using the same property, intended use, loan amount and holding plan. Compare rate type, amortization or interest-only period, points, other fees, payment components, prepayment rules, closing conditions and required retained assets. Use the <a href="/blog/reading-a-dscr-term-sheet/">term-sheet and payoff worksheet</a> for total financing cost and the <a href="/blog/str-lender-reserve-requirements/">reserve-versus-launch-cash test</a> for liquidity. No loan type is assumed always cheaper or always better.</p>
<p>Then underwrite property revenue and full operating expenses independently. The business income that supports qualification does not increase the rental's net cash flow. Do not let a strong business subsidize an unsupported offer without explicitly deciding how much cash and downside you are willing to carry. Compare a delayed purchase or lower offer if no available loan leaves a viable owner budget.</p>
<h2>Make the offer only after the decisive evidence is resolved</h2>
<p>Proceed when lender-accepted income, investment STR use, written terms and opening liquidity work alongside independent property underwriting. Renegotiate price or financing when a documented cost or lower accepted income changes your ceiling. Delay under valid contract protection when a specific missing statement, professional expense document or lender answer could change eligibility. Reject a path dependent on unsupported deposit classification, inaccurate occupancy representations or a future refinance that is not approved.</p>
<p>Send the lender your reconciled deposit packet and ask for the accepted calculation, unresolved conditions and financing deadline. Use that answer to set the search budget before bidding. <a href="/apply/">Book a call to compare STR candidates against your documented bank-statement financing and total acquisition cash</a>.</p>
<p class="small">Primary sources checked October 6, 2026. Educational information, not lending, accounting, tax, legal or personalized investment advice. Examples are hypothetical. Independent advisers and lenders determine their respective requirements. No approval, income, refinance, tax benefit or investment result is guaranteed.</p>'''

if __name__=='__main__':
    main(slug='bank-statement-loan-str',title='Bank-Statement Loans for an STR Purchase: Buyer Worksheet',h1='Should you use a bank-statement loan to buy an STR?',description='Evaluate a bank-statement loan for an STR purchase with deposit reconciliation, an expense-factor worksheet and a comparison of available financing paths.',body=BODY,search_terms='business deposits self employed bank statement expense factor',hub_attribute='data-bank-statement-purchase-link',hub_block='<p data-bank-statement-purchase-link>Buying with business income? Use the <a href="/blog/bank-statement-loan-str/">bank-statement deposit and financing-path worksheet</a> to separate lender-accepted earnings from account balances before setting an STR offer budget.</p>')
