"""Refresh an existing return-comparison guide; no library or homepage generation."""
import expand_hold_period as page

page.SLUG='airbnb-vs-long-term-rental-roi'
page.TITLE='Airbnb vs Long Term Rental ROI: Compare Purchase Capital'
page.H1='Airbnb vs Long Term Rental ROI'
page.DESC='Compare STR and long-term rental returns with a purchase-capital register, consistent reserve treatment and a worked downside before making an offer.'
page.FAQ=[
('Does higher Airbnb revenue mean a higher return?', 'No. Compare owner cash after recurring costs and debt against the actual cash committed to each purchase plan. Furnishing, launch work and reserve treatment can change the comparison.'),
('Should retained reserves be included in a rental return denominator?', 'State the convention explicitly. This guide shows both deployed purchase/setup cash and capital committed including funded reserves. Use the same definition for both strategies; neither measure makes reserves free acquisition money.'),
('Is cash-on-cash return the same as total investment ROI?', 'No. Annual pre-tax cash return omits several holding-period and sale effects. A total-return analysis needs dated contributions, distributions, debt payoff, net sale proceeds and separately modeled taxes without double-counting principal.'),
('Does a large tax bill make an STR the better purchase?', 'Not by itself. Obtain an independent CPA assessment of actual eligibility, participation and limitations. Fund the purchase and downside without a speculative tax receipt, and compare both lawful rental strategies on supported evidence.')]
page.BODY='''<p class="lead">Airbnb versus long-term rental ROI is not a comparison of two gross revenue headlines. Before buying, ask how much cash each lawful strategy commits, how much remains available to the owner, and what happens when receipts disappoint. A higher annual cash percentage can still be the wrong acquisition if it consumes too much liquidity or depends on a tax receipt that may not arrive. Use consistent definitions rather than a promised national return range.</p>
<p><a href="/apply/">Bring two supported rental scenarios and your deployable capital to an acquisition call</a>. This guide is for buyers considering a purchase within zero to six months. The <a href="/blog/airbnb-vs-long-term-rentals/">same-property operating comparison</a> addresses revenue evidence, lawful use and the expense stack; this worksheet focuses on the denominator, spendable cash and the decision a percentage can obscure.</p>
<h2>Name the return before comparing it</h2>
<p>For this worksheet, annual pre-tax cash means collected receipts less owner-paid recurring costs and the full debt payment. Property tax and insurance belong in the recurring cost stack once, not again below it. Keep one-time acquisition work separate. Document the exact period: a supported stabilized year is not the same as the first calendar year after a late closing and launch delay.</p>
<p>Cash-on-cash return divides that annual cash by a stated cash-invested denominator. It does not include forecast appreciation or treat an estimated deduction as an operating receipt. Here we show two useful denominators: deployed purchase/setup cash, and total committed capital including funded retained reserves. The second is a conservative liquidity-planning comparison, not a claim that everyone defines cash-on-cash identically.</p>
<p>NOI, debt-inclusive cash and cash available for distribution are different lines. A retained replacement allocation reduces modeled distributions, but transferring money to a reserve account is not an operating expense or a repair already paid. Show both cash before allocation and after allocation. When an actual replacement is paid, reconcile it to the reserve ledger rather than deducting the same provision and expenditure twice.</p>
<h2 id="expense">Build the purchase-capital register from actual evidence</h2>
<div class="table-wrap"><table><thead><tr><th>Register line</th><th>Evidence to request before the offer becomes unprotected</th><th>Consistency check</th></tr></thead><tbody>
<tr><td>Purchase equity and closing cash</td><td>Use-specific lender estimate, cash-paid fees and settlement inputs</td><td>Credit earnest money against closing; do not count it twice</td></tr>
<tr><td>Required setup</td><td>Furnishing, repairs, licensing and launch quotes for each lawful use</td><td>Include required cash even when the seller calls it optional</td></tr>
<tr><td>Carry until receipts</td><td>Closing date, work schedule, debt/utilities and realistic lease-up or launch</td><td>Do not combine a full stabilized numerator with a partial launch budget</td></tr>
<tr><td>Funded retained reserves</td><td>Buyer reserve target and any lender restrictions or verification requirements</td><td>Identify restricted versus accessible funds and state denominator treatment</td></tr>
<tr><td>Annual distribution policy</td><td>Condition-based replacement plan and actual management scope</td><td>Separate retained allocations from repairs already in recurring expenses</td></tr>
</tbody></table></div>
<p>Record the reviewer, amount, source date and unresolved deadline beside each input. A lower down payment can change both the denominator and the payment; it is not a free improvement to the return. If two proposals use different financing, show those actual terms rather than silently holding only the favorable debt assumption constant. Compare the <a href="/tools/first-str-purchase-budget/">all-in purchase budget</a> with cash you can actually access when each bill is due.</p>
<h2 id="side">Worked denominator comparison: the same cash is not the same commitment</h2>
<p>All figures are hypothetical arithmetic, not a client outcome, market average, financing quote or recommended reserve target. Assume the same property has two legally feasible plans. For simplicity, the common purchase/closing amount below includes all modeled early carry; a real file needs dated line items and any additional carry. Setup and funded reserves differ. The annual cash inputs already deduct each scenario's owner-paid recurring costs and full debt service.</p>
<div class="table-wrap"><table><thead><tr><th>Illustrative input or calculation</th><th>Long-term plan</th><th>STR plan</th></tr></thead><tbody>
<tr><td>Purchase, closing and modeled early carry</td><td>$130,000</td><td>$130,000</td></tr>
<tr><td>Required setup cash</td><td>$10,000</td><td>$40,000</td></tr>
<tr><td>Deployed purchase/setup cash</td><td>$140,000</td><td>$170,000</td></tr>
<tr><td>Funded retained reserves</td><td>$20,000</td><td>$30,000</td></tr>
<tr><td>Total committed capital</td><td>$160,000</td><td>$200,000</td></tr>
<tr><td>Annual cash before replacement allocation</td><td>$6,000</td><td>$12,000</td></tr>
<tr><td>Cash / deployed cash, rounded</td><td>4.29%</td><td>7.06%</td></tr>
<tr><td>Cash / total committed capital</td><td>3.75%</td><td>6.00%</td></tr>
<tr><td>Distinct annual retained replacement allocation</td><td>$2,000</td><td>$5,000</td></tr>
<tr><td>Cash available after allocation</td><td>$4,000</td><td>$7,000</td></tr>
<tr><td>After-allocation cash / total committed capital</td><td>2.50%</td><td>3.50%</td></tr>
</tbody></table></div>
<p>The STR produces twice the annual cash before allocation but requires $40,000 more committed capital. Its after-allocation cash advantage is $3,000, not $6,000. Dividing STR cash by the long-term plan's $160,000 would display 7.50%, but it would omit part of the STR commitment. Comparing the STR's deployed-cash percentage with the long-term plan's reserve-inclusive percentage also changes definitions mid-comparison.</p>
<p>The initial reserve and annual allocation are separate concepts: one is cash already committed at purchase; the other is the modeled policy for retaining later operating cash. They are not two repairs charged to year-one expenses. Replace the invented targets with lender conditions, property evidence and the buyer's liquidity plan. Restricted reserve money may not be available for every emergency.</p>
<h2>A higher percentage can fail the buyer's downside test</h2>
<p>Assume the STR downside collects $15,000 less than the base case and avoids only $3,000 of costs. Fixed and continuing expenses remain. Cash before allocation falls from $12,000 to zero: $12,000 − $15,000 + $3,000 = $0. Keeping the $5,000 replacement allocation creates a $5,000 funding gap, equivalent to −2.50% of the original $200,000 committed capital. That negative percentage describes the funding test, not an incurred repair bill.</p>
<p>A buyer starting with $250,000 of deployable cash has $50,000 uncommitted after the STR plan and $90,000 after the long-term plan. The STR's $30,000 funded reserve remains committed property cash, not an additional $30,000 of uncommitted household liquidity. Ask whether the reserve can legally and practically fund the downside, what minimum balance must remain, and which household obligations cannot be deferred.</p>
<p>If the buyer requires at least $60,000 to stay uncommitted, the STR plan fails that constraint by $10,000 even though its base percentage is higher. The long-term plan passes that one constraint, not every acquisition test. Independently stress its vacancy, collection, repairs and possession risks. Do not manufacture a long-term fallback from a percentage of STR revenue; use the <a href="/blog/str-long-term-rental-fallback/">separate fallback evidence checklist</a>.</p>
<h2 id="tax">Keep total return and taxes in separate dated analyses</h2>
<p>For a holding-period comparison, list initial cash, later contributions, distributions and net sale cash on their actual dates. A loan's principal reduction is not spendable annual income. If the projected sale proceeds already subtract the lower remaining loan balance, adding cumulative principal reduction again double-counts that component. Appreciation and the sale timetable remain forecasts, and sale costs can change the outcome. The <a href="/blog/cost-seg-timing-and-hold-period/">hold-period and exit-cash worksheet</a> explains why proceeds are not the same as profit.</p>
<p><a href="https://www.irs.gov/publications/p925">IRS Publication 925</a> separates rental-activity exceptions, material participation and loss limitations. An average customer-use period of seven days or less does not alone establish a salary offset. Active participation is not material participation. Have a CPA evaluate the actual classification, participation, ownership/use facts and applicable basis, at-risk and passive-loss limits. A high income or management contract does not settle those questions. The currently published edition reviewed October 7, 2026 is the 2025 publication.</p>
<p>Request a separately dated estimate of usable tax effects, not a deduction multiplied by a rate and labeled a refund. Do not put an anticipated refund in annual operating cash or spend it before receipt. Test the <a href="/blog/str-tax-benefit-shortfall-purchase/">smaller, delayed or unavailable tax-benefit case</a> before approving the purchase. Neither rental strategy is universally the better tax or investment choice.</p>
<h2 id="ltr-wins">Make the offer from constraints, not the winning percentage</h2>
<p>Proceed only when supported lawful use, receipts, quoted costs, funded setup, reserve access and downside meet the buyer's actual requirements. Reprice when a verified cost changes an otherwise viable plan. Delay within valid protections when decisive evidence is unresolved. Decline a property that needs an omitted cash commitment, inaccessible reserve or speculative tax receipt to look acceptable.</p>
<p><a href="/apply/">Discuss the shortlist with the completed capital and return register</a>. BNB Accelerator assists within its contracted acquisition scope; independent professionals determine tax, legal, lending and insurance conclusions. Keep bank and tax records in agreed secure channels. Educational information only, not personalized investment, tax, legal or lending advice. All example figures are hypothetical; no financing, income, deduction, refund, sale or return is guaranteed.</p>'''

if __name__=='__main__':
 page.main('2026-08-15','data-str-ltr-roi-review-link','Compare the <a href="/blog/airbnb-vs-long-term-rental-roi/">STR and long-term committed-capital return worksheet</a> before treating the higher cash percentage as the better purchase.')
