"""Source-checked in-place loan-fit guide, not a new financing keyword page.
Fannie Mae occupancy and subject STR income sections reviewed Oct6,2026.
Use the scoped refresh helper; never regenerate the homepage or old library.
"""
from expand_reservations_closing import main as refresh

SLUG = 'second-home-loan-rental-intent'
TITLE = 'Second-Home Loan for an STR Purchase: Verify Rental Intent'
H1 = 'Can you use a second-home loan when buying a short-term rental?'
DESCRIPTION = 'Before buying an STR with a second-home loan, disclose rental intent, management control and income needs. Test loan fit and cash before making an offer.'
BODY = '''<p class="lead">Only if your actual occupancy, property and management plan fit the lender's current second-home requirements. Occasional personal use does not automatically make an investment purchase eligible. Equally, the existence of some rental income is not, by itself, a universal prohibition. Before you make an STR offer, disclose the real plan and obtain an address-specific lender assessment rather than selecting the most attractive rate and fitting your story to it.</p>
<p><a href="/apply/">Book an STR acquisition call to align your property search with an honestly disclosed financing plan</a>.</p>
<h2>Check second-home eligibility before comparing loan prices</h2>
<p><a href="https://selling-guide.fanniemae.com/sel/b2-1.1-01/occupancy-types" rel="noopener">Fannie Mae's occupancy guidance</a> requires borrower occupancy for part of the year, a one-unit home suitable for year-round use, exclusive borrower control, and no agreement giving a management firm control of occupancy. Its rental-income clarification permits second-home delivery only when that income is not used to qualify and all other second-home requirements are met. These are Fannie Mae requirements, not a promise that every lender or product accepts your transaction.</p>
<p>Ask the lender to assess your intended rental calendar and the actual management contract, not a generic description of a vacation home. A service provider handling cleaning is not necessarily the same as an agreement controlling occupancy; do not assume either approval or prohibition without reviewing the terms. Supply the proposed agreement, restrictions and owner-use provisions. Ask which current program guidelines and lender overlays apply.</p>
<p>Our <a href="/blog/second-home-vs-investment-property/">personal-use versus investment purchase guide</a> addresses the broader choice of purpose. This page answers the narrower pre-offer question: does the proposed mortgage fit the disclosed rental intent? A lender's occupancy classification also does not settle tax treatment, insurance coverage or local STR permission.</p>
<h2>Send an intended-use packet, not just a price and credit score</h2>
<p>Prepare this packet before seeking a property-specific quote. Use realistic plans rather than changing the planned use to obtain a financing label. Send sensitive income, asset and contract documents through the lender's secure channel.</p>
<div class="table-wrap"><table><thead><tr><th>Buyer fact</th><th>What to disclose</th><th>Written answer needed</th></tr></thead><tbody>
<tr><td>Personal occupancy</td><td>When and how you genuinely plan to occupy the home</td><td>Whether the plan meets this product's occupancy conditions</td></tr>
<tr><td>Rental activity</td><td>Expected rental periods and any existing guest commitments</td><td>Whether the stated rental use is acceptable</td></tr>
<tr><td>Management and control</td><td>Actual agreement; who decides availability and owner access</td><td>Whether contractual occupancy control conflicts with loan terms</td></tr>
<tr><td>Property and title</td><td>Address, unit count, year-round suitability and proposed ownership</td><td>Property eligibility and permitted borrower/title structure</td></tr>
<tr><td>Income qualification</td><td>Whether you need subject-property rent to qualify</td><td>Approved evidence, calculation and occupancy classification</td></tr>
<tr><td>Purchase cash</td><td>Down payment, closing cost, setup funds and separate reserves</td><td>Current cash-to-close and reserve requirements without double-counting</td></tr>
</tbody></table></div>
<p>Record who reviewed the facts, the program, date, remaining conditions and when to recheck. A written preliminary answer is not final loan approval. If you change management terms, title or use before closing, disclose the change promptly and ask the lender to reassess. Read the actual occupancy certification and loan documents before signing.</p>
<h2>Do not use an STR forecast to rescue second-home qualification</h2>
<p>Personal liquidity and high W-2 or business income do not override product eligibility. If the purchase requires subject-property rent for qualification, ask about a suitable investment-property product rather than quietly including it in a second-home application. <a href="https://selling-guide.fanniemae.com/sel/b3-3.8-03/rental-income-subject-property-short-term-rental" rel="noopener">Fannie Mae's current subject-property STR income section</a> applies to eligible one-unit investment properties legally permitted for STR use, with specific documentation and qualifying calculations. It is not blanket permission to qualify a second-home borrower using projected bookings.</p>
<p>The <a href="/blog/airbnb-income-qualify-conventional-str-loan/">conventional STR income guide</a> addresses that evidence question separately. If comparing DSCR financing, obtain that lender's own terms, property rules, reserves and prepayment conditions. Do not assume a seller forecast, business income or available capital guarantees either product.</p>
<p>Illustrative cash comparison only: an $800,000 property is being considered with $250,000 of designated liquid funds. Assume a proposed second-home quote needs $120,000 down, $25,000 in closing costs and $70,000 for setup plus retained liquidity: total $215,000, leaving $35,000. An alternative investment quote assumes $200,000 down with the same other amounts: total $295,000, a $45,000 funding gap. The 15% and 25% down payments are made-up quote inputs, not required minimums or current offers.</p>
<p>If the disclosed plan fails second-home eligibility, the $215,000 column is not an available purchase path. The buyer must find a permitted product with an affordable complete budget, reduce the price or delay. Even if the first quote hypothetically saves $400 monthly, its $4,800 annual payment difference cannot cure product ineligibility or provide the missing $45,000 at closing. Use actual lender quotes; separate required reserves from spendable furniture money and keep household or business reserves outside the property's allocation.</p>
<h2>Make the financing-fit decision before the offer deadline</h2>
<p>Proceed when the lender has assessed the actual address and intended use, remaining conditions are understood, lawful STR use is evidenced, and closing plus launch cash fits a conservative budget. Renegotiate when a permitted financing path is viable only at a lower price or with a lender-approved adjustment. A seller credit does not automatically satisfy a down payment or unrestricted-cash requirement.</p>
<p>Delay under valid contract protection while a material classification, management or property condition is unresolved. Reject a financing plan that works only by understating rental intent or signing an occupancy statement you do not intend to fulfill. Do not assume you can sign for one use and immediately switch to another; ask the lender and qualified counsel about the actual documents and proposed change.</p>
<p>Next, attach the lender's conditions to your <a href="/blog/str-mortgage-preapproval-before-property/">STR financing search envelope</a> and test all-in cash against the actual property. For <a href="/blog/buy-str-high-income-large-tax-bill/">high-income investors considering a purchase for income and tax reasons</a>, ask the CPA to assess tax suitability independently. <a href="/apply/">Book a call to find and underwrite an STR that fits your real financing and acquisition budget</a>. BNB Accelerator supports acquisition within its contracted scope; it does not issue loans or determine mortgage eligibility.</p>
<p class="small">Primary sources reviewed October 6, 2026. Educational information only, not legal, lending, tax or personalized investment advice. All worked figures are hypothetical. No loan approval, rate, permit, income, tax benefit or return is guaranteed.</p>'''

if __name__ == '__main__':
    refresh(slug=SLUG, title=TITLE, h1=H1, description=DESCRIPTION, body=BODY,
            search_terms='second home rental intent occupancy lender purchase',
            hub_attribute='data-secondhome-loan-fit-link',
            hub_block='<p data-secondhome-loan-fit-link>Considering second-home financing for an investment purchase? Use the <a href="/blog/second-home-loan-rental-intent/">rental-intent loan-fit checklist</a> before relying on a lower down payment or rental income to qualify.</p>')
