"""Expand the existing acquisition wind-event liquidity guide in place."""
import html,json,re
from pathlib import Path
from expand_reservations_closing import main
SLUG='wind-deductible-str-reserve'
BODY='''<p class="lead">Before buying a coastal STR, translate the proposed wind deductible into dollars and test whether you can fund a storm interruption without depending on immediate insurance proceeds. The deductible is only one part of the cash need. Uncovered items, continuing bills and payment timing can matter even when the building is insured. A large salary or tax estimate is not a substitute for accessible property cash on the dates bills are due.</p>
<p><a href="/apply/">Book an acquisition call to compare this property's storm cash exposure with your funded purchase budget</a>. Bring the address-specific insurance proposal and endorsements for a qualified insurance professional's review, not just the annual premium.</p>
<h2>Read the actual deductible basis and trigger</h2>
<p>The <a href="https://www.opic.texas.gov/news/decoding-deductibles/" rel="noopener">Texas Office of Public Insurance Counsel's deductible explanation</a> distinguishes percentage deductibles based on insured value from a percentage of the claim. It also distinguishes hurricane, named-storm and wind/hail triggers and cautions that application can differ by policy. This is residential-policy education, not confirmation that any particular STR commercial, landlord or other policy covers your planned use.</p>
<p>Ask your insurance professional to identify the applicable percentage or fixed amount, calculation base, event definition and whether it applies per occurrence, claim, season or another contractual period. Read all relevant endorsements with the declarations, not just the smallest deductible on the quote. Verify the named insured, intended rental use, effective date, exclusions and binding conditions. Do not infer storm coverage from a lender accepting a premium estimate.</p>
<p>The <a href="https://www.tdi.texas.gov/tips/deductibles.html" rel="noopener">Texas Department of Insurance's deductible guide</a> demonstrates that a loss below the deductible produces no insurer payment in its simplified example. Convert the policy's actual basis to dollars before comparing quotes. An insured-value increase can change a percentage deductible's dollar amount even when the printed percentage stays the same.</p>
<h2>Build an event-exposure worksheet before the offer</h2>
<div class="table-scroll"><table><thead><tr><th>Buyer question</th><th>Evidence to obtain</th><th>Budget treatment</th></tr></thead><tbody>
<tr><td>Which event and deductible apply?</td><td>Declarations, endorsements and professional interpretation</td><td>Calculate dollars using the actual contractual basis</td></tr>
<tr><td>How are repairs settled?</td><td>Applicable limits, valuation terms and payment requirements</td><td>Separate covered loss, owner share and cash before payment</td></tr>
<tr><td>What is not covered?</td><td>Item/peril exclusions and separate-policy review</td><td>Use supported owner-cost scenarios, not assumed full reimbursement</td></tr>
<tr><td>What happens while closed?</td><td>Income-cover terms, access and realistic repair/readiness dependencies</td><td>Model actual continuing outflows and any verified receipt timing</td></tr>
<tr><td>Where is storm cash held?</td><td>Accessible funds after closing and setup, with lender restrictions checked</td><td>Do not spend the same balance twice as ordinary and event protection</td></tr>
</tbody></table></div>
<p>Have the adviser review roof settlement, exterior structures, equipment, contents, debris and water-related exposures appropriate to the property. Do not assume a wind contract also covers flood, access-related closure or every lost booking. The <a href="/blog/flood-zone-str-underwriting/">flood underwriting guide</a> addresses that distinct exposure; the <a href="/blog/roof-age-str-policy-binding/">roof underwriting guide</a> addresses whether the proposed policy can bind and on what terms.</p>
<p>For income protection, ask about covered causes, waiting periods, limits, exclusions, continuing expenses and proof required. A deductible reserve is not proof you have interruption coverage. Keep unresolved coverage outside supported reimbursement until clarified; missing evidence is a diligence question, not a reason to invent an exclusion or a claim outcome.</p>
<h2>Worked hypothetical: percentage is not a repair-bill percentage</h2>
<p>Invented illustration only, not an insurance quote, carrier determination or predicted storm. Assume the actual deductible endorsement uses an $800,000 insured building value and a 2% deductible for the modeled event. Deductible dollars are $16,000. Assume a $50,000 covered repair loss, full settlement on the simplified terms used here, and no other adjustment. The modeled insurer share is $34,000 and owner share $16,000. Two percent of the $50,000 repair bill would be $1,000, which is the wrong calculation for this assumed endorsement.</p>
<p>If the otherwise covered repair loss were only $10,000, this simplified insurer share would be zero and owner repair outlay $10,000, not $16,000 plus $10,000. The deductible is not a second invoice added on top of the entire repair cost. It also is not the maximum possible owner exposure when losses are excluded, settlement is limited or other obligations exist. Obtain the actual claims treatment from the insurer and qualified adviser.</p>
<p>For a separate comparison, assume another quote has a 5% deductible on that same $800,000 basis and identical coverage/settlement in this one simplified event. Its deductible is $40,000; for the assumed $50,000 covered repair, insurer share is $10,000 and owner share $40,000. Owner repair exposure is $24,000 greater than in the 2% case. These are hypothetical policy inputs, not typical coastal deductibles or available offers. Compare actual coverage and premiums without inventing event probability or a guaranteed premium-savings payback.</p>
<h2>Count closure cash once, not gross lost revenue twice</h2>
<p>Continue the 2% case with another explicitly invented two-month closure. Assume normal monthly receipts would be $12,000, variable costs avoided during closure $4,000, and fixed property/debt outflows continuing at $6,000. Normal cash after those costs is $2,000 a month. During closure, assume zero receipts and zero variable costs, with the same $6,000 fixed outflow. Actual two-month cash needed for those bills is $12,000.</p>
<p>The difference from the normal two-month result is $16,000: normal positive $4,000 becomes negative $12,000. That measures foregone contribution plus the changed cash result; it is not another $16,000 invoice to add to the $12,000 bills. Nor should you add the entire $24,000 lost gross receipts to those bills as a separate cash payment. Rebuild the model with actual cancellations, unavoidable variable costs, refunds and any applicable coverage rather than copying these assumptions.</p>
<p>Assume $5,000 of separate uncovered owner work, not included in the $50,000 repair loss, and no income-insurance receipt in this planning scenario. Net modeled event cash is $16,000 owner repair share plus $5,000 uncovered work plus $12,000 continuing bills, or $33,000. A $40,000 accessible post-setup cash balance with a separately protected $20,000 routine-operating floor supplies only $20,000 for this event. Preserving that floor requires another $13,000; describing the same $40,000 as both a full routine reserve and a full storm reserve overstates protection.</p>
<h2>The peak funding need can exceed the final owner loss</h2>
<p>For a timing stress, assume all $50,000 repairs, $5,000 uncovered work and $12,000 bills must be funded before the modeled $34,000 insurance proceeds arrive. Gross pre-receipt cash need is $67,000. Against $40,000 accessible cash, the immediate gap is $27,000 if the routine floor is consumed; preserving the $20,000 floor requires $87,000 total accessible funding, a $47,000 gap. This is a stress assumption, not a statement that every insurer pays only after complete repairs.</p>
<p>When the assumed $34,000 proceeds actually arrive, net event outflow becomes $33,000. Do not add both the gross $67,000 and the net $33,000 as separate losses. A funded payment bridge can resolve timing without reducing the ultimate owner share, and any borrowing costs or restrictions must be added separately. Ask providers about actual progress payments and the insurer about payment conditions; a possible later receipt does not pay today's contractor bill.</p>
<p>Use a downside duration based on property-specific repair, access and lawful reopening dependencies, not a universal two-month recommendation. Refresh it when the policy, insured value, cash balance or readiness plan changes. If a second event could trigger another deductible, test that contractual scenario separately rather than assuming the year's first payment exhausted every future obligation.</p>
<h2>Set the buy box from funded event risk</h2>
<p>Proceed when the actual policy can bind for the intended use, the purchase economics survive the reviewed costs and event liquidity is funded. Compare a different deductible, different property or lower acquisition allocation when the gap is unacceptable; available coverage and financing must be confirmed anew. Delay commitment under valid protection while decisive terms remain unresolved. Reject a purchase dependent on unverified coverage or certain immediate claim payment.</p>
<p><a href="/apply/">Bring the policy worksheet, net event case and peak-cash schedule to an acquisition call</a>. BNB Accelerator assists within its contracted acquisition scope; qualified insurance professionals interpret coverage and insurers determine claims. Educational information, not insurance, legal, tax, lending or personalized investment advice. Primary Texas sources reviewed October 6, 2026. All example values, closure durations and receipts are hypothetical. No policy eligibility, claim payment, tax benefit or investment outcome is guaranteed.</p>'''
if __name__=='__main__':
 main(slug=SLUG,title='Coastal STR Wind Deductibles: Event and Peak-Cash Test',h1='How Should a Wind Deductible Be Modeled for a Coastal STR?',description='Before buying a coastal STR, calculate wind deductible dollars, uncovered costs, closure bills and peak cash needed before insurance proceeds arrive.',body=BODY,search_terms='coastal wind deductible insured value storm reserve interruption cash claim payment timing',hub_attribute='data-wind-deductible-link',hub_block='<p data-wind-deductible-link>Comparing coastal acquisitions? Use the <a href="/blog/wind-deductible-str-reserve/">wind-deductible and peak storm-cash worksheet</a> to separate insured-value calculations, closure bills and money needed before claim proceeds arrive.</p>')
 p=Path(__file__).resolve().parents[1]/'blog'/SLUG/'index.html';s=p.read_text();words=len(re.findall(r'\b\w+\b',html.unescape(re.sub('<[^>]+>',' ',BODY))))
 def schema(m):
  d=json.loads(m.group(2))
  for n in d.get('@graph',[d]):
   if n.get('@type') in ['Article','BlogPosting']:n['wordCount']=words
  return m.group(1)+json.dumps(d,indent=2)+m.group(3)
 s=re.sub(r'(<script[^>]*type="application/ld\+json"[^>]*>)(.*?)(</script>)',schema,s,flags=re.S);p.write_text(s)
