"""Existing STR acquisition appraisal-method guide; preserve original route/date."""
from expand_reservations_closing import main

BODY='''<p class="lead">An STR's income can matter to its appraisal, but a seller's Airbnb forecast is not automatically the lender's property value. Before paying an income premium, establish the loan's appraisal requirements, the supporting market evidence and which receipts belong to the real estate versus the operating arrangement. Separately test whether the purchase works for you and whether the lender accepts its income for qualification.</p>
<p><a href="/apply/">Book a call to screen an STR purchase whose asking price depends on projected rental income</a>.</p>
<h2>Ask which appraisal assignment your purchase actually requires</h2>
<p>Start with the lender, not a seller's claimed capitalization rate. Identify the actual property classification, loan product, appraisal requirements and intended rental use. A residential purchase, a two-to-four-unit investment and a commercial hospitality acquisition need not follow the same valuation or underwriting process. Do not classify a house as commercial merely because its listing earns nightly revenue.</p>
<p>For applicable Fannie Mae loans, its <a href="https://selling-guide.fanniemae.com/sel/b4-1.3-10/cost-and-income-approach-value" rel="noopener">income-approach guidance</a> requires this approach for two-to-four-unit properties and recognizes its potential relevance for one-unit properties in substantial rental markets. Adequate rental evidence and the appraiser's determination of what is necessary for credible results matter. The guidance does not accept an appraisal relying solely on the income approach; it calls for supporting rental and sales comparables and gross-rent-multiplier calculations when that approach is used. These are applicable program rules, not a promise that STR projections will be accepted under every investment loan.</p>
<p>The same guidance points lenders using UAD 3.6 to its policy supplement. Ask which reporting requirements apply to your assignment instead of assuming a familiar form number defines every current appraisal. For a non-agency or DSCR product, obtain that lender's own written requirements. Approval to use a revenue report for one underwriting purpose does not establish its use for market valuation.</p>
<h2>Keep three different answers in the purchase file</h2>
<div class="table-wrap"><table><thead><tr><th>Question</th><th>Evidence and decision</th><th>Do not substitute</th></tr></thead><tbody>
<tr><td>Will this STR purchase meet my investment requirements?</td><td>Verified seller activity, buyer-specific revenue, full operating costs, launch cash and downside tests support your offer.</td><td>A lender's minimum ratio is not your owner's return.</td></tr>
<tr><td>What income will this lender accept to qualify the loan?</td><td>The actual product's rent source, adjustments, documentation and debt test determine qualification.</td><td>Your owner forecast is not automatically qualifying rent.</td></tr>
<tr><td>What market value does the appraisal support?</td><td>The lender-ordered assignment, property facts, market comparisons and reconciled appraisal opinion address value.</td><td>Qualifying income is not itself an appraised value.</td></tr>
</tbody></table></div>
<p>Fannie Mae's <a href="https://selling-guide.fanniemae.com/sel/b4-1.2-01/appraisal-report-forms-and-exhibits" rel="noopener">appraisal forms and exhibits guidance</a> describes the Single-Family Comparable Rent Schedule, Form 1007, as an exhibit required for a one-unit investment property when rental income is used to qualify, with other stated uses. A rent schedule is not a separate promise that the purchase price will appraise. Confirm the applicable reporting standard and permitted rental basis with the lender.</p>
<p>If a broker says the deal qualifies, ask which of the three questions that statement answers and which remain outstanding. The <a href="/financing/dscr-loans/">DSCR financing guide</a> addresses property-income qualification. This guide addresses evidence behind valuation before you price an offer; the <a href="/blog/appraisal-gap-furnished-str/">furnished-property appraisal-gap worksheet</a> handles additional cash after a documented funding shortfall.</p>
<h2>Work an income-premium example without pretending to appraise</h2>
<p>Hypothetical buyer analysis only, not an appraisal, current loan quote, market statistic or client result. A seller requests $700,000 and advertises $120,000 of annual gross booking receipts. Your record review identifies $12,000 of cleaning charges within that total. For this simplified example, those charges exactly offset $12,000 of cleaning costs. Removing both leaves $108,000 of accommodation revenue; it does not create an extra $12,000 expense deduction.</p>
<p>Assume your separately researched buyer operating costs, excluding the removed cleaning costs and financing, total $58,000. The resulting modeled operating cash before debt and replacement allocation is $50,000. A $6,000 annual replacement allocation leaves $44,000 before principal and interest. Neither $120,000 of gross receipts nor $44,000 of modeled owner cash is a lender-issued value opinion.</p>
<p>Suppose the lender separately reports accepted rent of $3,800 per month for its qualification test. That is $45,600 annually on that test's basis, not proof that the buyer should replace the entire STR forecast with $45,600 or that the house is worth a particular multiple. Ask what rent period, expenses and adjustments the figure represents. Reconcile the difference; do not silently mix monthly qualifying rent with annual owner net cash.</p>
<p>Finally, assume the completed appraisal reports $650,000. These three results can coexist because they answer different questions. The seller's $700,000 request is not validated by either the booking total or the accepted rent. A buyer may still consider paying above appraised value, but only after investigating the basis, confirming financing and testing the incremental capital. Use the separate gap worksheet for cash consequences; do not invent a market capitalization rate to force the appraisal to the asking price.</p>
<h2>Build a factual evidence packet, not a desired-value argument</h2>
<ul><li><strong>Property and lawful-use facts:</strong> verified unit count, dimensions, condition and jurisdiction-specific permission records. An operating listing does not prove the buyer's legal rental rights.</li>
<li><strong>Historical income:</strong> dated reservation, earnings and expense records with seasonality, owner blocks and pass-through charges identified. Keep guest details private. Use the <a href="/blog/seller-proforma-vs-trailing-revenue/">seller-forecast reconciliation</a> to distinguish history from proposed improvements.</li>
<li><strong>Market context:</strong> relevant rental and sale evidence with addresses, dates, property differences and verifiable sources. Asking prices and forecast tools are not closed transactions or proof of the subject's realized income.</li>
<li><strong>Transaction components:</strong> complete contract and addenda, included furnishings and any separate business arrangements disclosed through the lender's required process. Identify unsupported transfer assumptions rather than bundling them into real-estate value.</li>
<li><strong>Unresolved questions:</strong> a written list of missing evidence, who can obtain it and the deadline before releasing purchase protection.</li></ul>
<p>Have the lender explain how factual corrections or additional evidence may be submitted through its permitted appraisal-review process. A forecast differing from the appraisal is not, by itself, an appraisal error. Do not pressure the appraiser to deliver a target value or assume a review grants more contract time.</p>
<h2>Choose the purchase outcome before waiving protection</h2>
<p>Proceed when the lender's requirements are clear, supported value and buyer economics are understood, and the complete funding plan is acceptable. Renegotiate when an unsupported seller income premium exceeds your evidence-backed offer. Delay under a valid written extension when decisive valuation or rental-use evidence is missing. Reject when the acquisition depends on an unapproved income method, hidden transaction components or capital you cannot responsibly commit.</p>
<p>Ask your transaction adviser about the actual appraisal and financing protections and notice deadlines; this guide supplies no automatic termination or deposit-refund right. For <a href="/blog/buy-str-high-income-large-tax-bill/">high-income STR buyers</a>, available wealth or a hoped-for tax benefit does not resolve an unsupported purchase price. <a href="/apply/">Book a call to compare the lender's valuation requirements with your supported STR offer and alternative properties</a>.</p>
<p class="small">Primary sources checked October 6, 2026. Educational information, not appraisal, legal, lending, tax or personalized investment advice. All worked amounts are hypothetical. Consult your lender, appraiser and qualified advisers. No appraisal increase, loan approval, tax benefit or investment result is guaranteed.</p>'''

if __name__=='__main__':
    main(slug='str-appraisal-income-approach', title='Will STR Income Support an Appraisal Before You Buy?', h1='Will an appraiser count STR income when you buy the property?', description='Separate STR buyer cash flow, lender qualifying rent and appraisal value before paying an income premium. Use a worked example and evidence checklist.', body=BODY, search_terms='income approach appraisal qualifying rent purchase premium', hub_attribute='data-appraisal-income-evidence-link', hub_block='<p data-appraisal-income-evidence-link>Does an STR asking price depend on projected income? Separate <a href="/blog/str-appraisal-income-approach/">buyer cash flow, qualifying rent and appraisal evidence</a> before pricing an offer or committing additional capital.</p>')
