"""In-place buyer underwriting expansion, not a host growth tutorial.
Airbnb 3421/425 reviewed Oct6,2026; all ramp inputs are labeled hypothetical.
Use the scoped content helper without regenerating the homepage/library.
"""
from expand_reservations_closing import main as refresh

SLUG = 'new-listing-ramp-underwriting'
TITLE = 'New-Listing STR Ramp: Cash Test Before Buying'
H1 = 'How should you underwrite a new STR listing before buying?'
DESCRIPTION = 'Before buying an STR, model a new-listing ramp month by month. Test launch discounts, payout delays and peak cash shortfall before setting an offer.'
BODY = '''<p class="lead">Underwrite the buyer's first operating months separately from a stabilized annual forecast. Before buying an STR, assign opening dates, realistic bookable nights, supported rates, discounts, expenses and receipt timing to each month. Then fund the largest cumulative cash shortfall, not just a negative annual total. A property can look profitable after stabilization and still require cash the buyer has not reserved for its launch.</p>
<p><a href="/apply/">Book an STR purchase call to test the new-listing cash ramp before setting your offer</a>.</p>
<h2>Build evidence for the buyer's calendar, not the seller's average</h2>
<p>Start with the earliest date the buyer can lawfully and safely host. The <a href="/blog/str-purchase-to-launch-timeline/">purchase-to-launch timeline</a> handles readiness dependencies; this worksheet handles the first operating period's revenue and cash. A new listing does not inherit the seller's mature conversion history merely because the furnishings remain. Read the <a href="/blog/airbnb-reviews-property-sale/">review-continuity guide</a> before assuming the seller's reputation survives the purchase.</p>
<p>Request comparable new-listing histories from an authorized local operator where available. Record the original publication date, available nights, booked nights, achieved accommodation rate after discounts, opening season and material differences from your property. A live calendar is not proof of booked occupancy: blocked nights can include owner use or maintenance. If genuine launch evidence is unavailable, disclose the gap and use transparent sensitivities rather than inventing a typical ramp percentage.</p>
<p>Keep the first-year launch case, seasonal stabilized case and downside case separate. Do not spread peak-season revenue evenly across twelve months or shift a missed peak into the next month. The <a href="/blog/closing-before-peak-season-str/">peak-season closing guide</a> addresses whether rushing the purchase is worthwhile; it does not establish how quickly a new listing will earn bookings.</p>
<h2>Create a monthly revenue-to-cash bridge</h2>
<p>For each month, enter legally available nights, hypothetical booked nights, achieved nightly rate, accommodation revenue, separately treated cleaning/tax items, operating costs, debt service and cleared receipts. Identify costs due before payout and one-time launch items already included elsewhere. Keep required reserves and money you intend to retain after opening separate from cash consumed during the ramp.</p>
<p><a href="https://www.airbnb.com/help/article/3421" rel="noopener">Airbnb's current discount guidance</a> describes an optional new-listing promotion of 20% on the first three bookings. That is a booking-based offer, not a 20% reduction for every night in the first three months, and it does not guarantee demand. Verify eligibility and actual pricing settings. Model the selected discount only for the stays receiving it, without applying it again to a rate already reported net of discount.</p>
<p>Illustrative arithmetic only: ten nights at an assumed $300 base accommodation rate produce $3,000 before discounts. If every modeled stay covering those nights is eligible and receives a 20% discount, accommodation revenue is $2,400. At an assumed 25% variable-cost fraction, $600 is consumed and $1,800 remains before fixed costs. This is a constructed example, not a forecast, market rate, platform-fee schedule or a recommendation to use the promotion.</p>
<div class="table-wrap"><table><thead><tr><th>First operating period</th><th>Cleared receipts</th><th>Variable costs</th><th>Fixed costs including debt</th><th>Monthly cash flow</th><th>Cumulative cash flow</th></tr></thead><tbody>
<tr><td>Month 1</td><td>$0</td><td>$0</td><td>$3,500</td><td>-$3,500</td><td>-$3,500</td></tr>
<tr><td>Month 2</td><td>$2,400</td><td>$600</td><td>$3,500</td><td>-$1,700</td><td>-$5,200</td></tr>
<tr><td>Month 3</td><td>$4,500</td><td>$1,125</td><td>$3,500</td><td>-$125</td><td>-$5,325</td></tr>
<tr><td>Month 4</td><td>$6,000</td><td>$1,500</td><td>$3,500</td><td>$1,000</td><td>-$4,325</td></tr>
</tbody></table></div>
<p>Every table input is hypothetical. For simplicity all revenue is received and all associated costs are paid in the same modeled month; no separate tax, capital expense or refund is assumed. Replace that simplification with actual payment dates and add missing expense buckets for your acquisition. The required ramp draw in this example is at least $5,325, even though the period ends only $4,325 negative. Month 4 turning positive has not repaid the earlier cash draw.</p>
<h2>Stress receipt timing and the retained cushion separately</h2>
<p><a href="https://www.airbnb.com/help/article/425" rel="noopener">Airbnb's payout timing guidance</a> distinguishes reservation type, new-host status, payout schedule and payment-method processing, with possible reviews and delays. A booked stay, a guest payment and cleared cash in the owner's bank are different events. Check your actual payout setup and dates instead of assuming cash arrives when a reservation is made.</p>
<p>In a separate hypothetical timing stress, the $2,400 Month 2 receipt arrives in Month 3, while its $600 cost remains due in Month 2. Month 2 cumulative cash flow becomes -$7,600 instead of -$5,200. If all other assumptions hold and the receipt arrives in Month 3, the later cumulative balance catches up; the earlier funding requirement still existed. A payout delay is not automatically lost revenue, so do not count the same delay as both permanent revenue loss and a temporary receivable.</p>
<p>Suppose the buyer separately wants $10,500 retained after absorbing the baseline ramp draw. The baseline allocation is $5,325 plus $10,500, or $15,825, beyond separately budgeted closing, furnishing and setup. Under the timing stress, $7,600 plus $10,500 is $18,100. These are not lender reserve requirements or universal recommended amounts. Test a slower booking path and a repair shock too; do not assume an optional tax benefit or unapproved refinance provides the cash.</p>
<h2>Use the ramp to decide the offer and funding plan</h2>
<p>Proceed when the evidence-backed monthly model, lawful opening path and complete cash allocation fit your requirements even with a defensible downside. Renegotiate if the purchase can work at a lower price or after a specific, verified seller-funded repair. Delay under valid contractual protection while a decisive launch or financing fact is unresolved. Reject a purchase that only works by starting at mature occupancy, inheriting unavailable reviews or spending cash reserved for other obligations.</p>
<p>Record the evidence behind each month's assumptions and the specific observation that would change your decision. After launch, compare achieved rates, actual booked nights, costs and bank receipts against that dated model; do not quietly overwrite the forecast. This improves the next acquisition analysis without implying a fixed time to stabilization.</p>
<p>For <a href="/blog/buy-str-high-income-large-tax-bill/">high-income buyers allocating substantial capital</a>, a large account balance is not a substitute for a funded launch plan. <a href="/apply/">Book a call to compare this property's new-listing cash needs with an STR purchase you can fund conservatively</a>. BNB Accelerator supports sourcing and acquisition within its contracted scope; it does not guarantee bookings, platform exposure or investment performance.</p>
<p class="small">Primary sources reviewed October 6, 2026. Educational information only, not personalized investment, lending, tax or legal advice. All numerical examples are hypothetical. No opening date, occupancy, payout, permit, tax benefit or return is guaranteed.</p>'''

if __name__ == '__main__':
    refresh(slug=SLUG, title=TITLE, h1=H1, description=DESCRIPTION, body=BODY,
            search_terms='new listing ramp purchase cash shortfall launch',
            hub_attribute='data-listing-ramp-cash-link',
            hub_block='<p data-listing-ramp-cash-link>Will this purchase start with a new listing? Use the <a href="/blog/new-listing-ramp-underwriting/">monthly launch-ramp cash test</a> to separate mature revenue, early receipts and the cushion you want to retain.</p>')
