"""Scoped existing-URL refresh: realized refunds versus unresolved buyer exposure."""
from expand_reservations_closing import main

BODY = '''<p class="lead">Before buying an operating STR, reconcile refunds and chargebacks against the seller's completed-stay revenue. Then separately test unresolved disputes and the cost of fixing recurring problems. A refund already deducted from a report must not be deducted again when its payout offset appears. A disputed amount is not automatically a final loss, and a repair invoice is not proof that future refunds disappear.</p>
<p><a href="/apply/">Book an STR acquisition call to review seller adjustments and the income your offer can support</a>. This guide isolates revenue reversals and unresolved exposure; the <a href="/blog/str-1099-payout-reconciliation/">1099 scope register</a> first establishes whether an account-level record belongs to the purchased property.</p>
<h2>Identify what each STR refund or chargeback actually changes</h2>
<p>Ask for the property's booking, refund and dispute records for the same covered period. Match each adjustment to a reservation ID, channel, stay dates, amount and status. Separate a guest refund from a platform fee, a disputed card payment, a reversed chargeback and a damage-claim receipt. Do not combine all negative entries into one unexplained percentage or assume every difference between guest payment and bank deposit signals poor operations.</p>
<p><a href="https://www.airbnb.com/help/article/459" rel="noopener">Airbnb's payout calculation guidance</a> describes listing-owner deductions including host service fees and shared co-host payouts, and adjustments associated with refunds or prior cancellations. These are possible explanations, not proof of the cause or responsibility for a specific seller entry.</p>
<p><a href="https://help.vrbo.com/articles/About-partner-payouts" rel="noopener">Vrbo's payout-deduction guidance</a> describes chargebacks, reversals and cancellation charges. It says post-payout traveler refunds and chargebacks can be deducted from future payouts, with deduction details available in reports. That timing can separate the original stay from the later cash effect. It does not establish buyer liability or allow a private agreement to transfer a seller's platform account.</p>
<p>Record both stay dates and adjustment dates. Ask the seller's accountant to explain the report basis and reconcile periods. A later payout offset may be settlement of an adjustment already recorded; it is not necessarily a second refund. Keep accommodation revenue, cleaning pass-through, taxes, refundable deposits, fees and expenses consistently classified before comparing properties.</p>
<h2>Build a reversal evidence register before accepting an addback</h2>
<div class="table-wrap"><table><thead><tr><th>Register field</th><th>Evidence to request</th><th>Purchase decision</th></tr></thead><tbody>
<tr><td>Property, channel and reservation ID</td><td>Authorized booking export and listing-specific records</td><td>Exclude other properties and duplicate channel-manager entries</td></tr>
<tr><td>Original amount and report basis</td><td>Accommodation charges and whether reported revenue already nets adjustments</td><td>Set one consistent starting amount before deductions</td></tr>
<tr><td>Resolved refund and settlement</td><td>Resolution record, payout deduction and matching settlement reference</td><td>Count one economic adjustment rather than both refund and offset</td></tr>
<tr><td>Unresolved dispute</td><td>Amount, current status, requested response and actual deadline</td><td>Show the adverse case separately; do not presume recovery or loss</td></tr>
<tr><td>Cause and proposed remedy</td><td>Dated outage evidence, authorized communications, accepted work and cost</td><td>Keep claimed future improvement out of the supported case until justified</td></tr>
<tr><td>Responsibility around closing</td><td>Professional-reviewed allocation and permitted settlement arrangement</td><td>Identify who must act and fund any obligation without assuming account transfer</td></tr>
</tbody></table></div>
<p>Request authorized records through secure channels. Use IDs and redacted evidence in the acquisition worksheet, not guest names, card details, passwords or public copies of seller statements. A manager's explanation needs matching records; neither an empty dispute log nor an unavailable export proves that exposure is zero. Ask what period and channels the log covers.</p>
<h2>Work the completed-refund case and unresolved case separately</h2>
<p>Hypothetical arithmetic, not a client transaction or market forecast: the same property's completed-stay accommodation receipts before refunds are $120,000. Completed, verified refunds total $6,000. Assume the $120,000 has not already netted them. Other modeled operating expenses are $60,000, excluding those refunds, debt and capital work.</p>
<div class="table-wrap"><table><thead><tr><th>Defined comparison</th><th>Hypothetical result</th></tr></thead><tbody>
<tr><td>Pre-refund accommodation receipts</td><td>$120,000</td></tr>
<tr><td>Less completed refunds, once</td><td>−$6,000</td></tr>
<tr><td>Accommodation receipts after completed refunds</td><td>$114,000</td></tr>
<tr><td>Less other modeled operating expenses</td><td>−$60,000</td></tr>
<tr><td>Baseline before debt and capital work</td><td>$54,000</td></tr>
<tr><td>Separate unresolved-dispute adverse case</td><td>−$2,000</td></tr>
<tr><td>Adverse result on the same basis</td><td>$52,000</td></tr>
</tbody></table></div>
<p>The $2,000 is an expressly assumed additional dispute, not part of the completed $6,000. It is a sensitivity until resolved, not automatically another realized expense. If the starting report already showed $114,000 after completed refunds, begin there; subtracting $6,000 again would incorrectly produce $108,000. Similarly, a later $2,000 payout offset settling this dispute does not justify subtracting the same $2,000 twice. No probability, guaranteed reimbursement or accounting/tax treatment is implied.</p>
<p>These figures are not buyer cash flow or lender qualifying income. Replace expense inputs with buyer quotes and add actual financing and acquisition costs. Keep seller-account cash outside the buyer's available-money schedule unless a lawful, permitted, documented arrangement establishes otherwise. The <a href="/blog/future-reservations-at-closing/">closing reservation ledger</a> handles stay responsibilities and dated service funding separately.</p>
<h2>Do not make a repair an automatic refund addback</h2>
<p>Suppose several historical refunds cite an unreliable hot tub. A documented $8,000 remedy would be a separate hypothetical purchase cash outflow. It does not retroactively undo completed refunds, prove the repair eliminates future complaints, or cure unrelated service failures. An invoice supports the work and cost, not a guaranteed revenue increase. Have an appropriate specialist confirm the scope and accepted completion; model remaining downtime and other costs without counting the same closure twice.</p>
<p>Keep the $54,000 constructed baseline without improvement. If evidence supports a future reduction in refund leakage, identify the affected causes, covered operating period and remaining expenses, then show that scenario separately. Do not restore the whole $6,000 merely because a seller calls it one-time. A retained contingency is not an incurred expense, and spending on a remedy is not automatically a recurring operating expense or a tax deduction. The <a href="/blog/seller-proforma-vs-trailing-revenue/">seller-proforma evidence bridge</a> covers the broader uplift and offer comparison.</p>
<h2>Choose the offer using supported income and funded responsibilities</h2>
<p>Proceed when the register reconciles, recurring causes have an executable plan, actual approvals and buyer costs work, and an adverse case fits your requirements. Reprice when supported net receipts or remedy costs change a still-viable offer. Delay only with valid transaction protection while a decisive record or professional answer is outstanding. Reject unsupported income premiums or a handoff that depends on unidentified obligations and unavailable seller cash.</p>
<p>Have retained counsel, the closing team and lender review responsibility, permissible adjustments and actual deadlines; a worksheet does not create cancellation, extension, reimbursement or escrow-release rights. For <a href="/blog/buy-str-high-income-large-tax-bill/">high-income buyers with substantial capital</a>, personal liquidity or an expected tax benefit does not validate the seller's adjusted revenue. <a href="/apply/">Book a call to reconcile this STR's supported income, remedy budget and acquisition decision</a>.</p>
<p class="small">Primary sources checked October 6, 2026. Educational information only, not personalized investment, accounting, tax, legal or lending advice. All worked figures are hypothetical. Consult qualified professionals; no payout, dispute recovery, approval, tax benefit, rental income or return is guaranteed.</p>'''

if __name__ == '__main__':
    main(slug='str-refunds-chargebacks-underwriting', title='STR Refunds and Chargebacks: Buyer Underwriting Worksheet', h1='How Should Refunds and Chargebacks Change STR Underwriting?', description='Before buying an STR, reconcile refunds once, separate unresolved chargebacks and test repair addbacks with a seller-evidence register and worked example.', body=BODY, search_terms='refund chargeback seller adjustments disputed receipts repair addback', hub_attribute='data-refund-underwriting-link', hub_block='<p data-refund-underwriting-link>Seller income needs adjustment evidence, not automatic addbacks. Use the <a href="/blog/str-refunds-chargebacks-underwriting/">refund and chargeback underwriting worksheet</a> to separate completed reversals from unresolved exposure before making an offer.</p>')
