"""Existing buyer manager-continuity guide, with consent and cash worksheet."""
import html,json,re
from pathlib import Path
from expand_reservations_closing import main
SLUG='assign-str-management-contract-sale'
BODY='''<p class="lead">Do not assume buying an operating STR gives you the seller's management agreement, fee schedule or booking infrastructure. Review the actual agreement with local counsel and obtain the manager's written answer about the proposed buyer and transaction. The acquisition decision is whether a documented, permitted operating arrangement will be ready at possession, with its costs funded. A manager's willingness to talk is not an accepted assignment.</p>
<p><a href="/apply/">Book an acquisition call to compare manager continuity with a new-launch purchase</a>. Bring the seller's complete agreement, amendments, current fee schedule and the buyer proposal. BNB Accelerator assists within its contracted acquisition scope; counsel, lenders, insurers and platforms determine their respective requirements.</p>
<h2>Identify what the manager is actually offering</h2>
<p>Ask whether the proposal is an assignment of an existing agreement, an amendment involving the buyer, a replacement agreement or no continuation at all. Have counsel determine the necessary consents, who retains earlier obligations and whether anyone is released. These labels do not establish a universal legal outcome. Buying the real estate, buying an entity and purchasing selected assets can require different reviews; do not assume an entity purchase avoids consent or change-of-control terms.</p>
<p>A provider-specific example illustrates why fresh terms matter. <a href="https://evolve.com/selling-owner-incentive-terms" rel="noopener">Evolve's selling-owner incentive terms</a> refer to the purchaser signing a management agreement for continued rental. They also describe engagement as the buyer's choice. That incentive program is not your management contract or a general assignment rule. Confirm the currently available buyer arrangement directly; neither a seller incentive nor a provider's marketing page proves your proposed terms are approved.</p>
<p>Compare the seller's economics with the actual buyer quote. Record the commission calculation base, minimum charges, booking/channel charges, cleaning treatment, maintenance markup, startup fees, deposits, services excluded, payment dates and authority to spend. A quoted percentage alone is not a complete annual cost. Verify whether the buyer can retain any seller-negotiated rate; do not carry it into underwriting without documented acceptance.</p>
<h2>Use a consent and handoff worksheet before the decision deadline</h2>
<div class="table-wrap"><table><thead><tr><th>Question</th><th>Evidence to request</th><th>Buyer decision</th></tr></thead><tbody>
<tr><td>Who is bound, and what transaction is permitted?</td><td>Complete signed agreement/amendments; assignment or change-of-control provisions; counsel's review</td><td>Resolve the proposed buyer, required consents and earlier obligations</td></tr>
<tr><td>What terms apply after possession?</td><td>Manager's dated written buyer proposal, accepted scope, fees and effective date</td><td>Use buyer costs rather than the seller's headline commission</td></tr>
<tr><td>What happens if continuity fails?</td><td>Actual notice/termination terms, itemized potential charges and counsel-reviewed responsibility allocation</td><td>Price a funded fallback without assuming free cancellation</td></tr>
<tr><td>What resources can lawfully be handed over?</td><td>Authorized records, asset/vendor ownership schedule and permitted data/account procedures</td><td>Exclude passwords, reviews or guest money assumed to transfer automatically</td></tr>
<tr><td>Who performs the first services?</td><td>Named responsible team, availability, property access plan and written service dates</td><td>Do not promise opening merely because a company remains interested</td></tr>
</tbody></table></div>
<p>For every unresolved item, record the owner of the answer, the evidence still needed and its due date relative to the real contract deadline. Request seller authorization for relevant manager discussions. Store confidential contracts and records securely; use reservation identifiers rather than unnecessary guest details in a broadly shared acquisition worksheet. Counsel should review rights to data use and disclosure, not just the format of an export.</p>
<p>Ask who owns photos, website domains, furnishings supplied by the manager, vendor arrangements and operating deposits. Document any permission or separate transfer required; an inventory of these resources is not proof of ownership or consent. Reconcile seller funds and earlier charges separately from buyer startup money. Do not count a seller's manager-held reserve as accessible buyer cash unless its lawful disposition and receipt are established.</p>
<h2>Manager continuity does not transfer Airbnb reservations</h2>
<p><a href="https://www.airbnb.com/help/article/1431" rel="noopener">Airbnb's account-transfer guidance</a> says account ownership cannot transfer to a different host, and reservations cannot transfer to a new host or account. Co-host designation does not change that restriction; a trip-change request cannot hand reservation management to a new owner. Do not buy account credentials or treat manager consent as a platform exception.</p>
<p>Resolve affected stays through the actual platform and transaction advisers. A continuing manager does not by itself establish permitted hosting, buyer insurance, transferable local permissions or entitlement to payouts. Use the separate <a href="/blog/future-reservations-at-closing/">reservation-closing ledger</a> for guest duties, receipt timing and refund exposure. This worksheet answers manager consent and buyer service costs, not the value or transferability of a booked calendar.</p>
<h2>Worked hypothetical: continuation versus a new arrangement</h2>
<p>Invented planning amounts, not provider quotes, industry averages or a client outcome. Assume $70,000 accessible buyer cash remains after closing and unrelated setup costs. Protect $30,000 for baseline operations, leaving $40,000 spending capacity. For an approved continuation, suppose a $2,000 startup charge, $5,000 funded opening services and $3,000 buyer-held contingency allocation are required. Cash paid immediately is $7,000, leaving $63,000. After ring-fencing the $30,000 baseline and $3,000 contingency, $30,000 is unallocated.</p>
<p>The contingency allocation remains cash, not an incurred $3,000 expense. If a covered obligation later becomes payable, count the actual outflow once. A manager-held deposit would require separate treatment for access and release terms; this example deliberately assumes the buyer controls the contingency money. No seller-held balance or expected guest payout is included.</p>
<p>For a different hypothetical new-manager route, assume $4,000 onboarding, $5,000 opening services, $8,000 additional transition work and $12,000 incremental carrying bills during the delay. Immediate and delayed outflows total $29,000. Remaining cash is $41,000; protect the same $30,000 baseline and $3,000 contingency, leaving $8,000 unallocated. The $22,000 difference from continuation is a modeled transition burden, not an automatic seller liability or guaranteed advantage of retaining a manager.</p>
<p>This cash test answers whether either permitted handoff can be funded, not which manager deserves a revenue premium. Use the separate <a href="/blog/keep-str-manager-after-buying-property/">manager-retention and offer-price guide</a> to compare verified service performance, recurring fees and conservative operating economics. Replace the transition inputs with actual proposals and payment dates; avoid including the same bill twice.</p>
<h2>Test the consent deadline independently of the cash balance</h2>
<p>In a separate hypothetical schedule, the buyer's relevant diligence decision is due on day10, but the manager offers a consent review on day14 and closing is planned for day20. Ample cash does not supply the missing day10answer. Ask counsel before the actual deadline whether supported extension, an appropriate written closing condition or another lawful course is available. Do not assume the later meeting extends protection or that manager approval will arrive before possession. If closing moves, reconfirm the accepted buyer terms and first-service dates rather than relying on an earlier informal promise.</p>
<h2>Choose a supported acquisition outcome</h2>
<p>Proceed when the accepted buyer terms, consents, first-service plan and lawful guest resolution support your purchase case. Renegotiate when verified transition costs require a different supported price or approved allocation. Delay only under valid contractual protection while a decisive consent is pending. Reject a purported turnkey purchase that depends on unsupported account transfer, unavailable service capacity or an unfunded transition. No universal right to cancel, recover earnest money or force the seller to pay a manager fee is implied.</p>
<p>Before signing, ask counsel to review effective dates, earlier liabilities, notice, termination, dispute procedures and what happens if closing moves. Confirm insurer and permitting requirements independently. For <a href="/blog/buy-str-high-income-large-tax-bill/">high-income buyers</a>, manager selection also changes the actual owner work that tax advisers must evaluate; a management arrangement alone does not establish participation or a deductible loss. <a href="/apply/">Bring both documented operating routes and the remaining-cash worksheet to an acquisition call</a>.</p>
<p class="small">Primary Evolve and Airbnb sources reviewed October 6, 2026. Educational information, not legal, tax, insurance, lending or personalized investment advice. All worked figures are hypothetical. No consent, service continuity, booking, tax benefit or investment return is guaranteed.</p>'''
if __name__=='__main__':
 main(slug=SLUG,title='STR Management Contract Transfer: Buyer Consent and Cash',h1='Can an STR Management Contract Transfer to a Buyer?',description='Buying a managed STR? Verify buyer consent, new fees, platform limits and service dates, then compare continuation and transition costs with available cash.',body=BODY,search_terms='management contract assignment buyer consent continuity transition costs operating cash',hub_attribute='data-manager-assignment-link',hub_block='<p data-manager-assignment-link>Buying a managed property? Use the <a href="/blog/assign-str-management-contract-sale/">manager-consent and transition-cash worksheet</a> to compare accepted buyer terms and a funded fallback without assuming platform accounts transfer.</p>')
 p=Path(__file__).resolve().parents[1]/'blog'/SLUG/'index.html';s=p.read_text();words=len(re.findall(r'\b\w+\b',html.unescape(re.sub('<[^>]+>',' ',BODY))))
 def schema(m):
  d=json.loads(m.group(2))
  for n in d.get('@graph',[d]):
   if n.get('@type') in ['Article','BlogPosting']:n['wordCount']=words
  return m.group(1)+json.dumps(d,indent=2)+m.group(3)
 p.write_text(re.sub(r'(<script[^>]*type="application/ld\+json"[^>]*>)(.*?)(</script>)',schema,s,flags=re.S))
