"""Refresh the existing buyer demand-evidence guide, not a host calendar tutorial."""
from expand_reservations_closing import main as refresh

SLUG = 'blocked-calendar-demand-signal'
TITLE = 'Buying an STR: Do Blocked Airbnb Dates Prove Demand?'
H1 = 'Do blocked Airbnb calendar dates prove demand before you buy an STR?'
DESCRIPTION = 'Buying an STR with a busy calendar? Classify paid stays, owner blocks and restrictions, correct occupancy denominators and test the seller revenue claim.'
BODY = '''<p class="lead">No. Unavailable dates on an Airbnb calendar do not prove paid demand for an STR you are considering buying. Before using a busy calendar to justify your offer, match the dates to reservation records, separate non-rental blocks and calculate occupancy with an explicit denominator. Then build a separate buyer forecast. A high-income investor can afford diligence; that does not make an unexplained calendar reliable acquisition evidence.</p>
<p><a href="/apply/">Book an STR purchase call to review the seller's calendar evidence before relying on its occupancy claim</a>.</p>
<h2>Identify what made the dates unavailable</h2>
<p><a href="https://www.airbnb.com/help/article/3612" rel="noopener">Airbnb's blocked-night guidance</a> lists availability settings, linked calendars, connected software, pending or confirmed reservations, canceled or expired requests, missing account information and some legal restrictions among possible causes. A public unavailable night does not tell a buyer which cause applies. A synced block may reflect another channel, but the block itself does not verify that channel's paid stay.</p>
<p><a href="https://www.airbnb.com/help/article/447" rel="noopener">Airbnb's host-calendar guidance</a> explains that hosts can mark nights available or blocked and inspect certain block reasons in their calendar. It also distinguishes inquiries from pending requests and invitations. An inquiry is not a confirmed reservation. Ask the authorized seller or manager for the underlying records rather than drawing conclusions from a guest-facing screenshot.</p>
<p>Use a completed historical period for realized demand analysis and label future dates separately. A future confirmed reservation still is not a completed paid stay; cancellation and payout questions remain. The <a href="/blog/future-booking-calendar-value/">calendar-value comparison</a> addresses purchase premiums for documented future benefits. This guide addresses whether the seller's historical occupancy evidence supports the purchase case at all.</p>
<h2>Build a dated classification worksheet before the offer deadline</h2>
<p>Request a full-period calendar export where available, channel reservation records, canceled-stay records and the operator's explanation of manual blocks. If a reason history is unavailable, disclose that limitation rather than manufacturing it. Record a status for each night, a supporting document, the reviewer and unresolved questions. Keep guest identifiers private in a secure diligence packet.</p>
<div class="table-wrap"><table><thead><tr><th>Night classification</th><th>Buyer evidence to request</th><th>Treatment in the demand analysis</th></tr></thead><tbody>
<tr><td>Completed paid stay</td><td>Property-specific reservation, stay dates and reconciled earnings</td><td>Count once across channels; distinguish gross accommodation revenue from profit</td></tr>
<tr><td>Owner or complimentary use</td><td>Dated owner/operator record and any related charges</td><td>Do not count as paid market demand</td></tr>
<tr><td>Maintenance or preparation</td><td>Work order, service dates and operator explanation</td><td>Identify unavailable supply and potential buyer readiness costs</td></tr>
<tr><td>Pending, canceled or software/settings block</td><td>Reservation status, reason record or authorized system view</td><td>Do not silently convert an unresolved block into a realized stay</td></tr>
<tr><td>Open but unbooked</td><td>Historical availability and price/restriction records where available</td><td>Include in the offered inventory denominator under the stated definition</td></tr>
</tbody></table></div>
<p>When multiple channels list the same home, use one property-night register so a synced date is not counted twice. Match paid stays to the <a href="/blog/reconcile-airbnb-payout-export/">seller income reconciliation</a>, including refunds and timing adjustments. A reservation record can establish a booked night without establishing net profit. Conversely, a later bank deposit may relate to an earlier stay rather than the calendar month under review.</p>
<p>Do not erase unknown dates to improve a percentage. Show known offered inventory and unresolved inventory separately until evidence supports classification. A seller statement that blocks were voluntary is a hypothesis to verify, not proof that paying guests would have filled them.</p>
<h2>Use consistent denominators and a separate buyer forecast</h2>
<p>Illustrative arithmetic only: consider a completed 30-night month with 18 nights appearing unavailable and 12 open nights. Authorized records identify 10 completed paid nights, five owner-use nights and three maintenance nights. The categories sum to 30; assume there are no other restrictions or unresolved dates in this simplified example.</p>
<div class="table-wrap"><table><thead><tr><th>Measure</th><th>Calculation</th><th>What it means</th></tr></thead><tbody>
<tr><td>Apparent unavailable share</td><td>18 / 30 = 60%</td><td>Not paid occupancy</td></tr>
<tr><td>Paid nights as a calendar share</td><td>10 / 30 = 33.3%</td><td>Paid use across the whole month</td></tr>
<tr><td>Paid occupancy of offered inventory</td><td>10 / (10 + 12) = 45.5%</td><td>Observed result on the 22 nights offered under this definition</td></tr>
</tbody></table></div>
<p>At an assumed $250 accommodation rate, the 10 paid nights imply $2,500 of accommodation revenue before other charges and expenses. Misreading all 18 unavailable nights as paid would imply $4,500, an unsupported $2,000 increase. None of these made-up values is a market statistic, property forecast or evidence of transferable listing performance.</p>
<p>Suppose the buyer separately expects 28 lawful, ready-to-rent nights in a comparable month. Explicit sensitivities of 12 paid nights versus 18 at the same assumed $250 rate produce $3,000 versus $4,500 before costs, a $1,500 difference. These are scenarios requiring evidence, not conclusions from the seller's blocks. Do not apply either percentage automatically to reopened owner nights or extrapolate this one month into an annual forecast.</p>
<p>Test season, day of week, achieved rate after discounts, minimum stays, lead time, property capacity and comparable differences. Unavailable peak weekends and unavailable off-season weekdays are not interchangeable. Ask whether historical prices and availability were recorded or merely reconstructed. Support a buyer's new listing with the <a href="/blog/new-listing-ramp-underwriting/">launch-ramp cash worksheet</a>, and test claimed improvements with the <a href="/blog/seller-proforma-vs-trailing-revenue/">seller forecast bridge</a>.</p>
<h2>Decide whether the evidence supports this STR purchase</h2>
<p>Proceed when the property-night register, verified earnings, lawful buyer availability and downside purchase model support the offer. Renegotiate when paid nights or achievable revenue are materially lower than represented. Delay under valid contractual protection if an identifiable missing export or block explanation could change the decision. Reject a demand premium that requires treating unknown or owner-blocked nights as paid bookings.</p>
<p>Put three figures in the acquisition memo: verified paid nights, the explicitly defined offered inventory and the number of unresolved nights. Attach the source dates and summarize what would change your offer. If maintenance or legal blocks affect future availability, obtain transaction-specific advice and quotes; changing a calendar setting is not a permit, insurance approval or repair.</p>
<p>For <a href="/blog/buy-str-high-income-large-tax-bill/">affluent buyers allocating capital to an STR</a>, the next step is a substantiated property model, not an impressive screenshot. <a href="/apply/">Book a call to compare this property's verified demand evidence with your STR buy box</a>. BNB Accelerator assists within its contracted acquisition scope; it does not guarantee demand, bookings, platform exposure or returns.</p>
<p class="small">Primary sources reviewed October 6, 2026. Educational information only, not personalized investment, legal, tax, insurance or lending advice. Numerical examples are hypothetical. No permit, occupancy, revenue, tax benefit or investment result is guaranteed.</p>'''

if __name__ == '__main__':
    refresh(slug=SLUG, title=TITLE, h1=H1, description=DESCRIPTION, body=BODY,
            search_terms='blocked calendar paid demand occupancy denominator seller purchase evidence',
            hub_attribute='data-calendar-demand-link',
            hub_block='<p data-calendar-demand-link>Is a busy calendar being used to sell you an STR? Use the <a href="/blog/blocked-calendar-demand-signal/">paid-night classification and occupancy-denominator worksheet</a> to separate verified demand from owner blocks before pricing the property.</p>')
