"""Expand indexed seller-entity versus asset acquisition decision in place."""
import html,json,re
from pathlib import Path
from expand_reservations_closing import main
SLUG='buy-str-entity-or-assets'
BODY='''<p class="lead">When a seller offers the LLC that owns an STR, compare the complete transaction with buying the property and specified assets—not just the seller's equity asking price. Establish exactly what you acquire, which obligations remain, which approvals are needed and how much usable cash the transaction consumes. An entity-held permit or operating contract is not automatically preserved by a change of owners. A high-income buyer needs an evidence-backed acquisition structure, not an entity label presented as a shortcut.</p>
<p><a href="/apply/">Book an acquisition call to compare the seller's entity proposal with an asset-purchase alternative</a>. Transaction counsel, your CPA, the lender, insurer and relevant authorities should review their respective questions before you release purchase protection.</p>
<h2>Identify what is being sold before comparing terms</h2>
<p>An asset proposal should specify the real estate, furnishings, equipment and any other rights included, the seller that owns each item, and the obligations expressly proposed for assumption. An entity proposal should specify the interests being acquired, ownership percentages, controlling documents, authority to sell and the entity's assets and obligations. Ask counsel what legally remains with each party under the actual structure. Do not assume an asset purchase is free of all historical exposure or an entity purchase automatically makes you personally liable for every company debt.</p>
<p>Buying an existing seller entity is different from forming your own LLC to take title. The <a href="/blog/str-entity-structure-basics/">purchase-structure approval guide</a> aligns title, borrower, insurance, tax classification and permissions; this page compares purchasing an operating entity with purchasing its specified assets. Resolve the seller-entity scope first, then align the buyer's approved ownership and financing plan.</p>
<p>The <a href="https://www.sba.gov/counseling/plan-your-business/" rel="noopener">SBA's buying-an-existing-business guidance</a> recommends reviewing the full purchase and using professional help to evaluate contracts, financial statements, tax returns and price adjustments. It also flags licensing and zoning questions. This is general business diligence, not confirmation that your STR qualifies for SBA financing or that a particular permit transfers.</p>
<h2>Use a side-by-side evidence matrix</h2>
<p>For each row, record the actual document, reviewer, outstanding condition, proposed allocation and deadline. Keep seller account, payroll, guest and tax records secure. A seller summary or certificate of good standing does not answer all the underlying questions; request records appropriate to the transaction and have professionals define their scope of review.</p>
<div class="table-scroll"><table><thead><tr><th>Purchase question</th><th>Asset proposal review</th><th>Seller-entity proposal review</th></tr></thead><tbody>
<tr><td>What is acquired?</td><td>Deed/title, itemized assets, exclusions and rights actually assignable</td><td>Interests, control, ownership records and full asset/obligation schedule</td></tr>
<tr><td>Which debt and liens remain?</td><td>Payoffs, releases and expressly assumed obligations</td><td>Entity debt, security, guarantees and any change-of-control or consent conditions</td></tr>
<tr><td>Does lawful rental use continue?</td><td>Buyer eligibility, required applications and property restrictions</td><td>Authority review of ownership/control changes, not just the permit's entity name</td></tr>
<tr><td>What operating commitments exist?</td><td>Accepted assignments/new agreements and guest-transition obligations</td><td>Contracts, deposits, refunds, employees/providers and conditions affecting continuity</td></tr>
<tr><td>What historical exposure needs resolution?</td><td>Counsel review of liens, assumed/surviving claims and applicable law</td><td>Financial/tax records, claims, litigation, unpaid obligations and negotiated protections</td></tr>
<tr><td>What is the tax and cash treatment?</td><td>CPA-reviewed classification, allocation, basis and reporting</td><td>CPA review of entity classification, interests acquired, elections and actual tax consequences</td></tr>
</tbody></table></div>
<p>Reconcile financial statements to actual receipts, debt statements, tax records and invoices. A profitable income statement does not establish that all bills are paid or that cash in an account is freely distributable. Separate funds held for guests or other obligations from unencumbered cash included in the transaction. Verify any working-capital adjustment rather than adding bank cash to value while ignoring the related liability.</p>
<h2>Do not pay for continuity that has not been established</h2>
<p>For a purported entity-only advantage, identify the specific permit, contract or right and ask who has authority to confirm it survives the proposed transaction. Give the issuing authority and counsel the actual ownership/control change, property and operating plan. If the controlling terms require a fresh approval or terminate the permission on that change, retaining the entity name has not preserved the assumed benefit. This is a conditional diligence question, not a claim every jurisdiction treats control changes the same way.</p>
<p>Ask the lender or servicer about the actual transfer, borrower and collateral, and the insurer about named parties, intended use and continuity. Contact the relevant platform about the proposed operator/account arrangements rather than treating a purchased company as permission to exchange passwords or promise reservation continuity. The <a href="/blog/future-reservations-at-closing/">reservation closing ledger</a> addresses booked-guest obligations separately; do not count unsupported future payouts as money available to close.</p>
<p>For known claims, ask counsel which seller resolutions, conditions, representations, indemnities, holdbacks or other protections are appropriate and enforceable. Record the obligor, resources, limitations and claim procedure. A contractual promise to reimburse a loss is not necessarily cash on the day a bill is due. An unknown liability cannot responsibly be assigned an invented probability or universal reserve amount.</p>
<h2>Worked hypothetical: normalize price and debt first</h2>
<p>Invented all-cash comparison only, not a market valuation, adviser quote, permitted transfer or client outcome. Assume both proposals concern the same property and furnishings, no unrestricted company cash is included, both require the same $25,000 opening work and $30,000 retained operating reserve, and the buyer has $900,000 designated for this acquisition. No new borrowing or tax benefit funds either case.</p>
<div class="table-scroll"><table><thead><tr><th>Cash use</th><th>Asset proposal</th><th>Entity proposal</th></tr></thead><tbody>
<tr><td>Seller consideration</td><td>$800,000 asset price</td><td>$560,000 equity price</td></tr>
<tr><td>Separate debt payoff funded by buyer</td><td>$0 additional; seller payoff is within the asset-sale proceeds</td><td>$240,000 additional under assumed closing terms</td></tr>
<tr><td>Assumed review/closing costs</td><td>$15,000</td><td>$25,000</td></tr>
<tr><td>Opening work / retained reserve</td><td>$25,000 / $30,000</td><td>$25,000 / $30,000</td></tr>
<tr><td>Total capital / cash outside the plan</td><td>$870,000 / $30,000</td><td>$880,000 / $20,000</td></tr>
</tbody></table></div>
<p>The entity's $560,000 headline is not $240,000 cheaper here: its separate $240,000 debt payoff brings the acquisition consideration/debt cash bridge to $800,000. Do not add that same seller payoff again to the asset case, where it is already paid from the assumed $800,000 price. Neither row presumes debt assumption is authorized; both expressly assume the relevant debt is paid off and releases are verified at closing.</p>
<p>Now suppose entity diligence confirms another $30,000 of unpaid obligations not included above, with no entity cash available to meet them. Assume the reviewed proposal requires the buyer to fund their resolution. Capital rises to $910,000, exceeding designated cash by $10,000. A seller promise to pay later does not fund this closing gap. If a documented, accepted amendment reduces equity consideration by $30,000 to $530,000 while the buyer funds those same obligations, the modeled total returns to $880,000; this is a negotiation illustration, not an entitlement to a discount or proof creditors are satisfied.</p>
<p>The original asset row assumes its reviewed closing plan resolves its own relevant obligations; do not copy it to imply all asset deals avoid the extra bills. Rebuild both cases from real documents, assignment costs, approvals, insurance, financing and remaining risks. A lower total does not establish that the structure is legally better. If purported permit continuity remains unsupported, give that claimed benefit no supported purchase premium until decisive evidence arrives.</p>
<h2>Review tax consequences before signing, not from the name</h2>
<p><a href="https://www.irs.gov/forms-pubs/about-form-8594" rel="noopener">IRS Form 8594 guidance</a> requires both parties to report certain sales of a business asset group when goodwill or going-concern value attaches or could attach and the buyer's asset basis is determined only by the amount paid. Ask your CPA whether those conditions apply; this is not a filing requirement for every STR property closing. Have advisers review the actual transaction classification, allocation, basis and reporting before agreeing to an allocation.</p>
<p>Neither the words asset purchase nor LLC purchase guarantee a fresh depreciable basis, immediate deductible loss or offset against high W-2 income. Do not use an estimated refund to bridge closing cash. The <a href="/blog/str-tax-benefit-shortfall-purchase/">smaller or unavailable tax-benefit worksheet</a> tests that separate dependency.</p>
<p>Proceed when the full scope, approvals, obligation resolution and funded purchase case are supported. Renegotiate documented price or structure differences rather than pricing an undocumented benefit. Delay commitment under valid contract protection while decisive evidence remains missing. Reject a proposal dependent on concealed obligations, unapproved continuity or financing nobody has confirmed. <a href="/apply/">Bring both proposals and the completed evidence matrix to an acquisition call</a>; BNB Accelerator assists within its contracted scope, while qualified professionals and authorities make their respective determinations.</p>
<p class="small">Primary SBA and IRS sources reviewed October 6, 2026. Educational information, not legal, tax, lending, insurance or personalized investment advice. All example figures and terms are hypothetical. No liability protection, permit continuity, tax benefit, financing or investment result is guaranteed.</p>'''
if __name__=='__main__':
 main(slug=SLUG,title='Buy the STR Entity or Assets? A Buyer Comparison',h1='Should You Buy the STR Entity or Just the Property and Assets?',description='Compare an STR entity purchase with an asset deal using an evidence matrix, debt-adjusted price bridge and hypothetical obligation shortfall.',body=BODY,search_terms='seller entity asset purchase equity price debt payoff liabilities change of control cash comparison',hub_attribute='data-entity-assets-link',hub_block='<p data-entity-assets-link>When a seller offers the company behind an STR, use the <a href="/blog/buy-str-entity-or-assets/">entity-versus-assets evidence and price comparison</a> to verify continuity and reconcile equity price, debt and remaining obligations.</p>')
 p=Path(__file__).resolve().parents[1]/'blog'/SLUG/'index.html';s=p.read_text();words=len(re.findall(r'\b\w+\b',html.unescape(re.sub('<[^>]+>',' ',BODY))))
 def schema(m):
  d=json.loads(m.group(2))
  for n in d.get('@graph',[d]):
   if n.get('@type') in ['Article','BlogPosting']:n['wordCount']=words
  return m.group(1)+json.dumps(d,indent=2)+m.group(3)
 s=re.sub(r'(<script[^>]*type="application/ld\+json"[^>]*>)(.*?)(</script>)',schema,s,flags=re.S);p.write_text(s)
