"""Expand mandatory seller-note maturity decision; preserve concurrent Q&A."""
import json,re,subprocess
from pathlib import Path
from expand_reservations_closing import main,ROOT
SLUG='seller-financing-balloon-str'
BODY='''<p class="lead">A seller-financed STR can have an affordable monthly payment and an unaffordable final balance. Before offering, calculate the amount due at maturity, test how it could actually be paid and keep the property's operating reserve separate from money allocated to the balloon. A future refinance is one possible repayment path, not an automatic exit. Substantial income and a large tax bill do not eliminate this dated obligation.</p>
<p><a href="/apply/">Book an acquisition call to compare the seller note's maturity exposure with a bank-financed alternative</a>. Local lending and real-estate counsel should review the actual note, security, servicing, lien priority and applicable law before you sign.</p>
<h2>Read maturity and amortization as different terms</h2>
<p><a href="https://www.consumerfinance.gov/ask-cfpb/what-is-a-balloon-payment-when-is-one-allowed-en-104/" rel="noopener">CFPB's balloon-payment explainer</a> describes a large payment at the end of a loan and warns that lower property value or a weakened financial position can prevent refinancing. Its consumer-mortgage discussion is not a ruling on which protections apply to your investment-property seller note. Have counsel identify the applicable requirements rather than assuming every private STR loan is permitted or governed by identical consumer rules.</p>
<p>The amortization period determines the scheduled principal-and-interest payment; maturity determines when remaining principal becomes due. A thirty-year amortization with a five-year maturity is not thirty years to repay without another agreement. For an interest-only note, principal generally has not fallen through the regular interest payments. Extra principal payments, payment timing and the note's interest method can change the result.</p>
<p>Request a written payment schedule, maturity date, due-date convention, interest calculation, prepayment treatment, late/default charges and payoff procedure. Establish whether the borrower holds title at closing and what liens survive. The <a href="/blog/buy-str-with-seller-financing/">seller-financing acquisition guide</a> compares transaction structures and purchase cash; this guide focuses on the dated repayment cliff. Resolve existing senior-debt and consent questions with the responsible lender and counsel, not a verbal seller assurance.</p>
<h2>Worked hypothetical: sixty payments do not repay the note</h2>
<p>Invented arithmetic example, not a quote, client transaction or recommended loan. Assume a $400,000 note, fixed 7% nominal annual interest calculated monthly, 360-month amortization, no extra payments and a balloon immediately after sixty scheduled month-end payments. Ignore fees and assume each payment is on time. The unrounded payment is approximately $2,661.20998; shown to cents, $2,661.21.</p>
<p>Use monthly rate r=0.07/12, initial principal P=$400,000, payment M=P×r/[1−(1+r)<sup>−360</sup>] and balance after k payments B=P×(1+r)<sup>k</sup>−M×[(1+r)<sup>k</sup>−1]/r. With k=60, the remaining balance is approximately $376,526.36. Actual contractual rounding, day-count conventions and payment dates can change the payoff; obtain a dated servicer statement rather than sending this model's number.</p>
<p>Sixty modeled payments total about $159,672.60, but principal falls by only $23,473.64. The rest is interest in this simplified schedule. If instead the note were interest-only at the same principal and rate, monthly interest would be about $2,333.33 and principal would still be $400,000 absent principal reductions. The smaller monthly payment has not reduced the maturity obligation.</p>
<h2>Test net refinancing capacity against the actual payoff</h2>
<p>In the following separate invented future-loan scenarios, assume the advance is limited to the lower of 70% of accepted value and a separately calculated income-based cap. Assume $12,000 of refinancing costs and $15,000 of additional retained cash required by the proposed lender. Existing property reserves are outside these figures. No current lender ratio, five-year rate, approval or future product availability is asserted.</p>
<div class="table-scroll"><table><thead><tr><th>Future scenario</th><th>Value / value cap</th><th>Income cap / gross advance</th><th>After costs and $376,526.36 principal</th><th>After additional reserve</th></tr></thead><tbody>
<tr><td>Planning case</td><td>$600,000 / $420,000</td><td>$410,000 / $410,000</td><td>$21,473.64 remaining</td><td>$6,473.64 remaining</td></tr>
<tr><td>Lower value and income</td><td>$520,000 / $364,000</td><td>$350,000 / $350,000</td><td>$38,526.36 contribution needed</td><td>$53,526.36 total new cash needed</td></tr>
</tbody></table></div>
<p>In the downside, the lender's hypothetical $350,000 advance does not repay the $376,526.36 principal after $12,000 costs. If the buyer has $40,000 specifically available for this obligation, preserving separate household/business and operating reserves, the $53,526.36 total need exceeds that allocation by $13,526.36. A negative proceeds calculation is not approval for financing the shortfall. If the lender cannot fund at all, the entire contractual payoff must be resolved through another executable path.</p>
<p>The real payoff may include accrued interest, charges and other amounts omitted here; add them once and revise the figures. Ask prospective lenders about ownership, seasoning, accepted income, condition, use and documentation today, but recheck before maturity. Higher future rates can both reduce supported loan capacity and weaken owner cash after the new debt payment. The <a href="/blog/refinance-after-str-stabilization/">stabilized-refinance worksheet</a> handles optional capital recycling; here the seller balance has a payment deadline even if no new loan is approved.</p>
<h2>A fallback sale needs net cash and enough time</h2>
<p>For a separate illustrative sale test, assume total sale costs equal 6% of price and use only the $376,526.36 modeled principal as payoff. At a $420,000 sale, $394,800 remains after assumed costs and $18,273.64 after principal, before tax, accrued interest and other omitted obligations. At $390,000, net before payoff is $366,600, leaving a $9,926.36 shortfall. These invented prices are not estimates of this property's future market value; the 6% input is not a typical commission or required charge.</p>
<p>A sale contract is not settlement money, and gross equity is not a check available on the balloon date. Build a transaction-specific backward schedule for counsel review, listing preparation, marketing, an accepted offer, buyer diligence, financing and closing, with a verified alternative if any stage slips. Do not assume the market will supply a buyer on your timetable. Resolve lender and permit conditions, guest obligations and possession before promising a sale can close; use the <a href="/blog/future-reservations-at-closing/">reservation closing ledger</a> for the separate guest-handoff question.</p>
<h2>Negotiate a funded maturity plan before buying</h2>
<p>Ask counsel about the exact extension right, eligibility conditions, notice delivery, decision maker, fee, rate change and default consequences. A seller willing to discuss an extension is not an executed extension. A possible refinance or sale does not suspend the original maturity. No national notice period, automatic renewal, cure right or contract clause is supplied here.</p>
<p>Proceed when purchase economics, legal structure, regular payments and a funded maturity fallback fit your documented capital. Renegotiate price, financed principal, amortization or maturity when the downside cannot be funded; rerun payments and balance after every change. Delay commitment while decisive title, payoff or professional review is missing under valid protection. Reject a structure whose repayment depends entirely on unapproved future financing or a hoped-for seller concession.</p>
<p>Keep a maturity file with the current balance, documentary payoff, earliest warning date, repayment alternatives, designated capital and the person monitoring each condition. Do not count the same cash as both operating protection and balloon repayment. <a href="/blog/buy-str-high-income-large-tax-bill/">High-income STR acquisition planning</a> connects this liability to the broader purchase budget. <a href="/apply/">Bring the seller term sheet and repayment worksheet to an acquisition call</a>; BNB Accelerator works within its contracted scope, while lenders and independent advisers determine their respective approvals.</p>
<p class="small">Primary CFPB source reviewed October 6, 2026. Educational information, not legal, tax, lending or personalized investment advice. All figures and future scenarios are hypothetical. No extension, sale, refinancing, tax benefit or investment outcome is guaranteed.</p>'''
if __name__=='__main__':
 p=ROOT/'blog'/SLUG/'index.html';source=p.read_text()
 block=re.search(r'<!-- preclosing-keywords:start -->.*?<!-- preclosing-keywords:end -->',source,re.S).group()
 faqs=[m.group() for m in re.finditer(r'<script[^>]*type="application/ld\+json"[^>]*>.*?</script>',source,re.S) if json.loads(re.search(r'>(.*?)</script>',m.group(),re.S).group(1)).get('@type')=='FAQPage']
 assert len(faqs)==1
 data=json.loads(re.search(r'>(.*?)</script>',faqs[0],re.S).group(1));assert len(data['mainEntity'])==5
 for q in data['mainEntity']:assert q['name'] in block and q['acceptedAnswer']['text'] in block
 p.write_text(source.replace(faqs[0],''))
 main(slug=SLUG,title='Seller-Financed STR Balloon: Repayment Stress Test',h1='How Do You Stress-Test Seller Financing with a Balloon Payment?',description='Before buying a seller-financed STR, calculate the balloon balance, refinance shortfall and net sale fallback with a worked repayment worksheet.',body=BODY+'\n'+block,search_terms='seller note balloon maturity amortization repayment cash shortfall refinance sale',hub_attribute='data-seller-balloon-link',hub_block='<p data-seller-balloon-link>Considering a seller-financed acquisition? Use the <a href="/blog/seller-financing-balloon-str/">balloon balance and repayment stress test</a> to check maturity cash needs before accepting a lower monthly payment.</p>')
 p.write_text(p.read_text().replace('</head>',faqs[0]+'\n</head>'))
 # Use the approved current normalizer only on this route; retain the five Q&A.
 subprocess.run(['node','--input-type=module','-e',"import {readFileSync,writeFileSync} from 'node:fs';import {expandPreclosingKeywords} from './preclosing_keywords.mjs';const p='blog/seller-financing-balloon-str/index.html';writeFileSync(p,expandPreclosingKeywords(readFileSync(p,'utf8'),p));"],cwd=ROOT,check=True)
 final=p.read_text();assert re.search(r'<!-- preclosing-keywords:start -->.*?<!-- preclosing-keywords:end -->',final,re.S).group()==block
 minutes=re.search(r'<span>(\d+) min read</span>',final).group(1)
 archive=ROOT/'blog/index.html'
 archive.write_text(re.sub(r'<article class="post-card".*?</article>',lambda m:re.sub(r'<span>\d+ min read</span>',f'<span>{minutes} min read</span>',m.group()) if '/blog/'+SLUG+'/' in m.group() else m.group(),archive.read_text(),flags=re.S))
 print('Approved source normalizer: '+minutes+' min; five original visible Q&A preserved with matching schema')
