"""Distinct pre-closing permit extension decision, not another permit-transfer guide."""
import html,json,re
from pathlib import Path
from expand_reservations_closing import main
SLUG='permit-pending-due-diligence-extension'
BODY='''<p class="lead">If an STR permit answer is still pending near your purchase deadline, extend due diligence only when additional time can produce a specific decision-changing answer and the signed terms preserve the protection you need. A pending application is not approval, and moving the closing date alone may not move a separate diligence or notice deadline. Before paying to wait, identify the missing evidence, the governing contract dates and your maximum additional spend.</p>
<p><a href="/apply/">Book an STR acquisition call to compare a protected permit extension with another purchase candidate</a>. Bring the authority's written status and your counsel-reviewed deadline schedule.</p>
<h2>Identify what more time can actually resolve</h2>
<p>Separate four milestones: application received, application complete, substantive review finished and permission issued for the buyer's proposed use. Ask the issuing office which milestone is reached, which documents remain, who supplies them and what outcome it can reasonably address before a proposed extension ends. A payment receipt or place in a queue cannot answer whether the buyer can lawfully host. Keep HOA and deed restrictions in a separate review; municipal progress does not resolve them.</p>
<p>One current primary example is <a href="https://www.austintexas.gov/development-services/short-term-rentals" rel="noopener">Austin's STR application guidance</a>. It distinguishes complete documents and payment from entry into a processing queue and from approval. Partial applications are not processed, and its published timelines are estimates, not this property's deadline commitment. Do not apply Austin's process to another jurisdiction. Request the controlling office's current parcel-specific answer, including whether the buyer can apply or obtain the needed decision before owning the property.</p>
<p>If ownership is required before the decisive application can be made, another two weeks before closing may not deliver the approval your investment case needs. Ask counsel about a lawful alternative transaction structure or evaluate a genuinely acceptable post-closing risk and cash plan. Do not describe either as a guaranteed workaround. The <a href="/blog/permits-that-do-not-transfer/">permit-transfer guide</a> addresses ownership-change eligibility; the <a href="/blog/buy-airbnb-without-str-permit/">missing-permit guide</a> addresses an unverified legal-use purchase.</p>
<h2>Build a deadline register before requesting an amendment</h2>
<p>Have your agent and local counsel read the executed contract and amendments. Record exact dates, times, time zones, required notice method and receipt requirements where applicable. Ask which protections remain, which expire and whether an extension requires additional consideration or lender approval. Never assume a verbal request, unanswered email or application delay automatically changes the contract.</p>
<div class="table-scroll"><table><thead><tr><th>Separate event</th><th>Buyer evidence to obtain</th><th>Question for the extension</th></tr></thead><tbody>
<tr><td>Diligence or permit-review deadline</td><td>Executed contract clause and exact notice requirement</td><td>Does the signed amendment move this specific deadline and preserve an acceptable remedy?</td></tr>
<tr><td>Closing and possession</td><td>Current agreed dates and access arrangements</td><td>Can the seller, closing team and required inspections accommodate the change?</td></tr>
<tr><td>Financing and rate lock</td><td>Written lender expiration, extension price and document requirements</td><td>Is financing still available on acceptable terms at the later date?</td></tr>
<tr><td>Permit milestone</td><td>Authority's written status, missing items and next review step</td><td>What answer will arrive, who pursues it and when must the buyer decide?</td></tr>
<tr><td>Vendor and guest commitments</td><td>Cancellation/rebooking terms and allowed operating dates</td><td>Which expenses or obligations change if purchase or launch moves?</td></tr>
</tbody></table></div>
<p>The <a href="https://www.consumerfinance.gov/owning-a-home/close/close-the-deal/" rel="noopener">CFPB closing guidance</a> warns that breaking a purchase contract may have consequences beyond losing a deposit and that lender fees can also be lost. It does not create an STR permit contingency or a refund right. Ask counsel how the actual contract allocates earnest money, any separate diligence fee, extension consideration and other potential remedies. Do not assume the deposit is the maximum exposure.</p>
<h2>Compare new extension costs, not money already spent</h2>
<p>Hypothetical pre-closing worksheet only; these are invented charges and contract conditions, not typical fees, a state contract rule or a probability of permit approval. Suppose a buyer has already spent $2,000 on completed diligence and an $800 nonrefundable application. A separate $25,000 earnest-money deposit is held under counsel-reviewed terms. Counsel confirms, for this example only, that a properly exercised current termination right returns that deposit. Past $2,800 spending is sunk; it does not become recoverable because the buyer pays for an extension.</p>
<div class="table-scroll"><table><thead><tr><th>Assumed additional cost for one 14-day extension</th><th>Amount</th><th>Modeled treatment</th></tr></thead><tbody>
<tr><td>Seller extension consideration</td><td>$1,200</td><td>Nonrefundable and not credited at closing, solely as assumed here</td></tr>
<tr><td>Lender lock extension</td><td>$900</td><td>Separate written lender charge; no overlap with other costs</td></tr>
<tr><td>Additional counsel review</td><td>$500</td><td>Incremental, not the prior diligence bill</td></tr>
<tr><td>Specialist follow-up inspection</td><td>$400</td><td>Incremental appointment needed for the defined milestone</td></tr>
<tr><td>Total new spend</td><td>$3,000</td><td>Compare with the new information obtained and the buyer's limit</td></tr>
</tbody></table></div>
<p>If the buyer chooses a $5,000 maximum additional pre-closing spend, the first modeled extension leaves $2,000 of that allowance. A second identical $3,000 extension would bring cumulative new spend to $6,000, exceeding the limit by $1,000. The earlier $2,800 is not part of the new-spend allowance but remains part of the buyer's total acquisition economics. The $25,000 held deposit is tied-up liquidity, not another spent fee; it is also not automatically refundable after the new deadline. Document its actual treatment.</p>
<p>More time is useful only if it changes the evidence. A completed inspection followed by a scheduled eligibility decision may justify review of the first extension. Another queue acknowledgment with no decisive path does not justify the second merely because you already paid for the first. Do not invent an approval probability and multiply it by the deposit to claim an expected saving. If seller consideration is credited at closing or a lender charge differs, revise both the cash timing and final purchase economics without counting the same item twice.</p>
<h2>Use a decision date and a stopping rule</h2>
<p>Ask counsel to document the desired milestone, seller cooperation and access, review deadline, permitted notices and remedy if the answer is adverse or still missing. A meaningful review date should leave time for the required decision and delivery; do not substitute this article for a legal clause or automatically send a termination notice while still negotiating. Confirm the fully executed amendment before treating an old deadline as changed.</p>
<p>Proceed when buyer permission, financing and the complete acquisition case are supported. Renegotiate when the use is viable but actual extension charges or launch timing weaken the price case. Delay under valid signed protection when a named milestone can be resolved and the incremental spend fits your limit. Reject the STR thesis when the use is unavailable, the decisive answer cannot arrive within acceptable protection, or recurring extensions require funding you will not commit. A seller's refusal to extend does not establish what termination or damages rights you have; ask counsel before the existing deadline.</p>
<p>Pre-closing extension costs are different from carrying a purchased property while waiting to open. If the chosen plan includes a post-closing approval interval, separately budget zero STR receipts during unauthorized operation, carrying expenses and launch readiness in the <a href="/underwriting/cash-needed-to-buy/">cash-through-launch model</a>. Do not assume seller reservations or a projected tax refund funds either delay. Compare the revised purchase with a candidate that has a documented buyer permission path.</p>
<p><a href="/apply/">Book a call to evaluate whether this pending-permit STR deserves another protected review period or should leave your shortlist</a>. BNB Accelerator assists within its acquisition scope; the authority decides licensing and independent advisers determine legal and financing terms.</p>
<p class="small">Primary sources reviewed October 6, 2026. Educational information, not legal, tax, lending, insurance or personalized investment advice. Worked numbers and timing are hypothetical. No extension, refund, permit, financing, tax benefit or investment result is guaranteed.</p>'''

if __name__=='__main__':
 main(slug=SLUG,title='Pending STR Permit: Should You Extend Due Diligence?',h1='Should you extend due diligence before buying an STR with a pending permit?',description='Buying an STR with a pending permit? Compare signed deadline protection, decision-changing evidence and incremental extension costs before paying to wait.',body=BODY,search_terms='permit extension deadline register incremental cost stopping rule',hub_attribute='data-permit-extension-link',hub_block='<p data-permit-extension-link>Permit answer still pending near your purchase deadline? Use the <a href="/blog/permit-pending-due-diligence-extension/">STR extension deadline register and new-spend worksheet</a> before paying for more time or allowing protection to expire.</p>')
 p=Path(__file__).resolve().parents[1]/'blog'/SLUG/'index.html';s=p.read_text();words=len(re.findall(r'\b\w+\b',html.unescape(re.sub('<[^>]+>',' ',BODY))))
 def schema(m):
  d=json.loads(m.group(2))
  for n in d.get('@graph',[d]):
   if n.get('@type') in ['Article','BlogPosting']:n['wordCount']=words
  return m.group(1)+json.dumps(d,indent=2)+m.group(3)
 s=re.sub(r'(<script[^>]*type="application/ld\+json"[^>]*>)(.*?)(</script>)',schema,s,flags=re.S);p.write_text(s)
