#!/usr/bin/env python3
"""Pre-purchase provider decisions, verified public sources, one URL per intent."""
import json,re,sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).parent))
import tpl
from pillars import write
ROOT=Path(__file__).resolve().parent.parent
DATE='2026-10-06'
P={
'arrived':('Arrived','Investment shares in rental-property offerings','https://help.arrived.com/en/articles/4496428-how-does-arrived-work','Arrived offers property investment shares; a share purchase differs from buying and controlling an entire house.','Which offering, share class and governing documents apply? Who can sell the asset, and what fees and liquidity conditions apply?','/blog/bnb-accelerator-vs-arrived-str-purchase/'),
'ember-flex':('Ember Flex','Co-ownership with optional rental of allocated nights','https://emberhome.com/faqs','Ember Flex combines co-ownership with optional rental of allocated nights. Its Limited product has different use restrictions.','Which product permits rentals? How are dates allocated, expenses shared and rental proceeds assigned?','/blog/bnb-accelerator-vs-ember-flex-str-purchase/'),
'roofstock':('Roofstock','Rental-home marketplace and acquisition services','https://www.roofstock.com/investor-services/acquisitions','Roofstock publishes individual rental-home and portfolio acquisition paths. Match the listing and service to your intended rental strategy.','Does the specific address support your intended STR use, and which underwriting and transaction tasks are actually included?','/blog/bnb-accelerator-vs-roofstock-str-buyer/'),
'stayrnr':('StayRnR','Sourcing, renovation and property-operation services','https://stayrnr.com/property-investment','StayRnR describes sourcing, renovation and operation, including in-house construction and furnishing. A project needs a specific written scope.','Which work is included before settlement, what construction remains after it, and which contract governs each phase?','/blog/bnb-accelerator-vs-stayrnr-str-buyer/'),
'pacaso':('Pacaso','Managed second-home co-ownership for personal use','https://www.pacaso.com/faq/buyer','Pacaso’s managed co-ownership is designed for personal second-home use; its buyer FAQ prohibits public vacation rentals by owners.','Are you comparing a managed co-ownership interest or a separate whole-home listing? What use restrictions bind that exact purchase?','/compare/bnb-accelerator-vs-pacaso/'),
'bnb-turnkey':('BNB Turnkey','Acquisition, furnishing and management coordination','https://bnb-turnkey.com/services','BNB Turnkey describes market research, property evaluation, inspection and negotiation support, design and furnishing, and management coordination.','Which named party owns the condition review, vendor budget and closing calendar? Is a particular manager required?','/blog/bnb-accelerator-vs-bnb-turnkey-str-buyer/'),
'str-search':('STR Search','Property matching and acquisition analysis','https://strsearch.com/','STR Search markets property matching and data analysis, while distinguishing its work from a realtor’s transaction role.','What qualifies as a match, what happens to rejected candidates, and which transaction responsibilities remain with your agent?','/compare/str-search/'),
'kleer-circle':('Kleer Circle','Coordinated STR acquisition and setup','https://kleercircle.com/','Kleer Circle describes coordinated market selection, underwriting, acquisition and setup. Confirm the buyer’s required role in the actual engagement.','What does the buyer personally approve and execute? Which support and operating assumptions are contractual?','/blog/bnb-accelerator-vs-kleer-circle-str-buyer/'),
'str-insights':('STR Insights','Deal tools and separate acquisition-service tiers','https://www.strinsights.com/introduction','STR Insights describes deal tools and a higher-touch acquisition path. Portal access and delivered acquisition work require different comparisons.','Does the quoted tier assign people to address diligence and contract deadlines, or provide access to research?','/blog/bnb-accelerator-vs-str-insights-buyer/'),
'full-shop':('The Short Term Shop','STR-specialist brokerage and buyer education','https://theshorttermshop.com/','The Short Term Shop provides STR-specialist brokerage and buyer education in vacation markets. Confirm local representation and any additional service scope.','Who represents you locally, and who independently owns the revenue memo, legal-use evidence and inspection decisions?','/compare/avery-carl-short-term-shop/'),
'rabbu':('Rabbu','STR marketplace, tools and optional buyer assistance','https://rabbu.com/about','Rabbu describes an STR marketplace, market and revenue tools, agent and lender connections, and optional search assistance through closing.','Which service level are you buying? Are income records seller-reported, and who verifies them against the chosen address?','/compare/rabbu/'),
}
# Bespoke exercises and acquisition risks determine the page, not a brand-name swap.
A={
'arrived':('Buying investment shares versus selecting a whole STR','Start with the right you want to buy. An investment share may offer exposure without giving you unilateral authority to choose financing, change an operator or sell the house. A direct property purchase requires more capital and more decisions. Make a two-column ownership map using the offering documents on one side and the proposed deed and loan on the other. Compare voting, capital-call, distribution and exit rights before comparing projected returns.','Ownership and liquidity','subscription documents; fee schedule; redemption or secondary-market eligibility; property-level liabilities',['ember-flex','pacaso','roofstock']),
'ember-flex':('Co-owned rental nights versus unrestricted calendar control','Write down the dates you actually need, the rental dates allocated to you and how dates are selected. Build an income case using only rentable nights you control. Include shared expenses, usage charges and any financing specific to the interest. Then compare a whole-property purchase with the same personal-use assumptions. If holidays are important, ask what happens when several owners want the same dates before reserving an interest.','Calendar and income rights','product designation; ownership agreement; date-allocation rules; rental-proceeds and expense allocation',['arrived','pacaso','stayrnr']),
'roofstock':('Rental acquisition alternatives for a buyer pursuing STR use','Take one listing and create two cases: the advertised rental strategy and your intended short-term rental strategy. Do not reuse a long-term lease estimate as a nightly-rate forecast. Check the exact address, existing tenancy, lease obligations, insurance and local permit path. Select an STR specialist only when those additional tasks are needed and assigned. Keep a long-term rental fallback separate from the main case so the fallback does not conceal a weak acquisition.','Strategy and address fit','existing lease and occupancy; STR permission; independent comparable set; financing and insurance quotes',['rabbu','str-search','bnb-turnkey']),
'stayrnr':('Renovation-led acquisition versus a ready-to-buy STR','Divide a prospective project into purchase, permitting, construction and opening readiness. Ask which activities must be resolved before the inspection contingency ends and which depend on later permits or contractor availability. Compare a renovation proposal with a property requiring limited work using a common all-in budget. Add holding costs and a delay scenario. A lower purchase price can lose its advantage when uncertain scope and schedule consume the available cash.','Construction commitment before closing','contractor scope; permit feasibility; payment schedule; change-order rules; contingency and holding-cost budget',['bnb-turnkey','roofstock','rabbu']),
'pacaso':('Personal-use co-ownership versus an income-producing STR','Decide whether success means access to a vacation home or rental income from guests. For managed Pacaso co-ownership, public rental restrictions make an STR cash-flow projection the wrong purchase test. Compare usable dates, shared expenses, resale provisions and financing instead. If the goal is a rental business, evaluate a permitted whole-property purchase or a separately documented rental-eligible product. A whole-home listing on a platform should be evaluated under its own documents.','Intended use before ownership structure','exact listing type; owner use restrictions; shared expense commitments; resale process; financing terms',['ember-flex','arrived','bnb-turnkey']),
}
C=[
('bnb-accelerator-vs-pacaso','BNB Accelerator vs Pacaso',None,'pacaso','Are you buying a rental asset or access to a second home?', 'Write your first-year goal in one sentence. If it requires paying guests, verify that the proposed ownership documents permit that activity before comparing forecasts. If it requires personal vacation access, compare dates and ownership obligations. The two models can serve different buyers without either being universally better.', [('Purchase goal','Buyer-selected STR acquisition coordination','Managed personal-use co-ownership'),('Use test','Address-specific permission and rental feasibility','Owner use rules and scheduling'),('Capital test','Purchase, loan, diligence and launch cash','Interest price, financing and shared expenses'),('Decision authority','Confirm deed/entity and individual contracts','Read co-owner governing and resale terms')]),
('bnb-turnkey-vs-str-search','BNB Turnkey vs STR Search','bnb-turnkey','str-search','Do you need a property match or broader purchase coordination?', 'Ask both providers to respond to the same rejected-property scenario: a matched address fails the inspection or insurance check. Record who updates the model, finds another candidate, advises the offer decision and tracks the deadline. The answer should identify a person and a contractual obligation rather than just a list of partners.', [('Initial task','Coordinated property evaluation and acquisition path','Property matching and data analysis'),('Transaction role','Confirm agent and coordinator separately','Confirm separate realtor representation'),('Budget scope','Ask for acquisition and furnishing deliverables','Ask which execution budgets the tier includes'),('Failure remedy','Read re-search and cancellation provisions','Define a qualifying match and rejected-match terms')]),
('kleer-circle-vs-str-insights','Kleer Circle vs STR Insights','kleer-circle','str-insights','Are the two quotes buying the same level of delivered work?', 'Put each deliverable on a row: market shortlist, address memo, offer review, inspection response and closing file. Compare the quoted STR Insights tier with the actual Kleer engagement. Mark research access, advice and completed work separately. Choose by the gaps in your purchase team rather than by the number of listings or a headline performance claim.', [('Service selection','Written acquisition engagement','Exact portal, consultation or acquisition tier'),('Buyer workload','Confirm approval and execution obligations','Confirm work retained under the chosen tier'),('Address evidence','Request an actual property decision memo','Request the tier’s address-level output'),('Deadline ownership','Name agent, lender and coordinator','Do not infer coordination from portal access')]),
('the-short-term-shop-vs-str-search','The Short Term Shop vs STR Search','full-shop','str-search','Do you need local representation, acquisition analysis, or both?', 'Use an actual candidate address to test the division of work. Ask the agent who negotiates and tracks contingencies, then ask the analyst who selects comparables and revises the downside case. Resolve disagreement before an offer. The Short Term Shop’s property-search subdomain is distinct from strsearch.com, the John Bianchi analysis brand discussed here.', [('Core comparison','STR-specialist brokerage','Property matching and analysis'),('Contract work','Confirm representation and local transaction duties','Confirm realtor duties are separately staffed'),('Revenue work','Ask who prepares independent underwriting','Ask for methods, assumptions and revisions'),('Combined team','Useful when local representation is the gap','Useful when property screening is the gap')]),
('roofstock-vs-rabbu','Roofstock vs Rabbu','roofstock','rabbu','Does your purchase require rental-home access or STR-specific screening?', 'Compare the same address under your actual intended rental use. Separate seller-reported history, estimated nightly revenue and current lease income. For an occupied listing, record possession timing and lease obligations. For STR conversion, obtain written legal-use evidence and real insurance and furnishing quotes. Select the platform or service that supplies the missing evidence without treating a listing’s projected yield as a verified result.', [('Starting point','Rental-home and portfolio acquisition paths','STR-focused listings, tools and optional assistance'),('Listing evidence','Check tenancy, condition and advertised strategy','Check seller records versus tool estimates'),('Execution service','Confirm what your specific transaction includes','Confirm marketplace versus consultant tier'),('STR suitability','Verify the exact address independently','STR positioning still requires address diligence')]),
('arrived-vs-ember-flex','Arrived vs Ember Flex','arrived','ember-flex','Are you buying financial exposure or co-owned use and rental rights?', 'Build a rights matrix before a return matrix. With an offering interest, identify distribution rules and who makes property decisions. With rental-eligible co-ownership, identify date allocation, personal use and the income attributable to your dates. Then compare capital commitments, recurring charges and exit conditions. Do not translate ownership percentage directly into unrestricted use or guaranteed distributions.', [('What is purchased','Investment shares in an offering','Co-owned property interest under product documents'),('Personal use','Do not assume use rights from investment shares','Check allocated owner-use dates'),('Income test','Offering distribution and expense policy','Rental-eligible dates and proceeds allocation'),('Exit test','Eligibility and liquidity in actual documents','Co-owner resale and transfer provisions')]),
('stayrnr-vs-bnb-turnkey','StayRnR vs BNB Turnkey','stayrnr','bnb-turnkey','How much construction risk are you accepting before settlement?', 'Send each provider the same scope sheet: address, inspection findings, required repairs, furnishing specification and target cash cap. Ask which tasks are priced, which need a separate vendor contract and which remain estimates. Price a delay and a rejected permit before comparing the proposals. Confirm who can authorize a change order and whether the acquisition decision remains viable if the renovation estimate increases.', [('Published emphasis','Sourcing and renovation with construction capabilities','Acquisition, design and furnishing coordination'),('Before-offer evidence','Permit feasibility and project estimate','Address analysis and expected vendor budget'),('Contract question','Who performs and warrants construction?','Who contracts with and oversees each vendor?'),('Cost comparison','Scope, change orders and holding costs','Included work, third-party charges and contingency')]),
]
def e(s):return tpl.esc(s)
def section(h,html):return f'<section class="section-sm"><div class="wrap wrap-narrow"><h2>{e(h)}</h2>{html}</div></section>'
def p(s):return '<p>'+e(s)+'</p>'
def link(k):return f'<a href="{P[k][5]}">BNB Accelerator vs {e(P[k][0])}</a>'
def source(keys):
 refs='; '.join(f'<a href="{P[k][2]}" rel="noopener noreferrer">{e(P[k][0])} official material</a>' for k in keys)
 return section('Sources and commercial disclosure',f'<p>Reviewed {DATE}: {refs}. Provider statements describe published offers, not independently audited performance. Published by BNB Accelerator, which has a commercial interest in acquisition comparisons. No provider affiliation or independent ranking is implied. Confirm current availability, fees and binding documents directly. No return, financing or tax result is guaranteed.</p>')
def hero(title,lead):return f'<section class="hero hero-page"><div class="wrap"><a class="bc-back" href="/compare/">← All comparisons</a><div class="hero-inner"><span class="eyebrow">Before the purchase · Provider decisions</span><h1>{e(title)}</h1><p class="lead">{e(lead)}</p><div class="btn-row"><a class="btn btn-accent" href="/apply/">Discuss My STR Purchase</a><a class="btn btn-ghost-light" href="/tools/first-str-purchase-budget/">Estimate Purchase Cash</a></div></div></div></section>'
def finish(path,title,desc,body,keys,faqs):
 body+=section('Questions before committing',''.join('<h3>'+e(q)+'</h3>'+p(a) for q,a in faqs))
 body+=section('Compare BNB Accelerator on the same evidence',p('BNB Accelerator helps buyers coordinate sourcing, underwriting and acquisition. Ask for current market coverage, a sample property memo and a written responsibility map. You approve the asset and fund the property purchase. Compare service fees separately from down payment, closing costs, inspections, furnishing and reserves. A useful acquisition engagement makes the decision evidence clearer; it does not eliminate ownership risk.')+'<p><a href="/apply/">Discuss your purchase criteria</a> · <a href="/tools/first-str-purchase-budget/">Build an all-in purchase budget</a> · <a href="/compare/alternatives/">Browse alternatives by service model</a></p>')
 body+=source(keys)
 schema=tpl.graph(tpl.breadcrumb_schema([('Home','/'),('Compare','/compare/'),(title,path)]),tpl.ORG_SCHEMA)+'\n'+tpl.article_schema(title,desc,tpl.SITE+path,DATE,DATE,section='STR Buyer Comparisons')
 schema+='\n<script type="application/ld+json">'+json.dumps({'@context':'https://schema.org','@type':'FAQPage','mainEntity':[{'@type':'Question','name':q,'acceptedAnswer':{'@type':'Answer','text':a}} for q,a in faqs]})+'</script>'
 write(path,tpl.page(title=title,description=desc,path=path,body=body,extra_schema=schema,active='/compare/',body_class='buyer-compare',transparent=True))
 return {'path':path,'title':title,'sources':[P[k][2] for k in keys]}
NEW=[]
for k,(h,exercise,risk,records,others) in A.items():
 name,model,url,fact,question,cmp=P[k];title=f'Alternatives to {name}: Compare Before Buying';path=f'/compare/alternatives-to-{k}/'
 body=hero(title,h)+section('Start with the ownership and service model',p(fact)+p(question))
 body+=section('Named alternatives with different purchase paths',''.join('<h3>'+e(P[o][0])+'</h3>'+p(P[o][3])+p(P[o][4])+link(o) for o in others))
 body+=section(h,p(exercise))+section('Evidence to obtain before paying',p('Request '+records+'. Compare the same cash commitment and downside assumptions. Keep provider charges separate from property costs, and identify the actual seller, adviser and contracting entity. Do not send a deposit based solely on a forecast or brand name.'))
 body+=section('Choose the smallest service scope that fills your gaps',p('A direct buyer can hire a local agent, independent analyst, lender and inspector separately. That path offers choice but leaves integration and deadlines with the buyer. An acquisition coordinator may help organize the purchase when those responsibilities are not already staffed. Shared ownership and investment offerings solve different capital and control needs. Resolve the intended use, legal interest and decision rights before comparing convenience or advertised income.')+link(k))
 faqs=[(f'What should I compare first when looking for {name} alternatives?',h+'. Start with legal ownership, intended use and the work you expect someone else to perform. Then compare the written scope and complete cash budget.'),(f'Is BNB Accelerator the same purchase model as {name}?','Compare the proposed contracts. BNB Accelerator focuses on coordinating a buyer-selected property acquisition. The competitor’s exact product may provide different ownership rights or service responsibilities.'),(f'What documents help compare {name} with another provider?','Request '+records+'. Have the appropriate local professionals resolve property, financing and legal questions before your commitment deadline.'),(f'How do I compare the full cost of {name} alternatives?','Use separate rows for provider fees, acquisition capital, financing, property expenses, diligence, initial work and reserves. For shared or investment ownership, add the product’s recurring and exit charges.')]
 NEW.append(finish(path,title,'Compare '+name+' alternatives by '+risk.lower()+', service scope and purchase evidence before committing capital.',body,[k]+others,faqs))
for slug,title,a,b,lead,exercise,rows in C:
 path='/compare/'+slug+'/';keys=[x for x in [a,b] if x];left=P[a][0] if a else 'BNB Accelerator';right=P[b][0]
 body=hero(title,lead)+section('What the published offers cover',''.join('<h3>'+e(P[k][0])+'</h3>'+p(P[k][3]) for k in keys))
 table='<div class="table-scroll"><table><thead><tr><th>Purchase question</th><th>'+e(left)+'</th><th>'+e(right)+'</th></tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+e(cell)+'</td>' for cell in row)+'</tr>' for row in rows)+'</tbody></table></div>'
 body+=section('Compare the purchase responsibilities',table)+section('Run this decision exercise before an offer',p(exercise))
 body+=section('Compare evidence using one actual candidate',p('Ask for a redacted decision file for a property similar to your target. It should separate source records from estimates, explain rejected comparables and show the purchase cash needed when revenue is below the base case. Obtain current lender and insurance quotes rather than assuming an advertised rate or projected revenue will qualify the deal. Confirm the legal-use question for the exact parcel with the appropriate local authority and advisers.'))
 body+=section('A contract-to-close responsibility map',p('Put a name and due date next to representation, inspections, title, financing, permit questions and the closing funds schedule. Mark introductions separately from completed work. Before a contingency expires, record what has been verified, what remains uncertain and who has authority to accept the risk. The strongest fit is the proposal that covers your actual gaps with documented deliverables and a complete budget.'))
 body+=section('Continue the provider comparison','<p>'+' · '.join(link(k) for k in keys if P[k][5]!=path)+'</p>')
 faqs=[(f'How should a buyer choose between {left} and {right}?',lead+' Use the written deliverables, intended ownership rights and the work your purchase team still needs.'),(f'Can I compare {left} and {right} using advertised returns?','First align ownership, rental strategy, expenses, financing and decision authority. Advertised projections are estimates and should not replace address-specific records and a downside case.'),(f'What should I request before signing with {left} or {right}?','Request current fees, included and excluded tasks, named contracting entities, cancellation terms and a sample address decision file. Resolve the key purchase question: '+lead),(f'Does this comparison establish a current price for {left} or {right}?','No. Request a current written quote for the exact product, market and property scope. Compare total purchase cash separately from provider fees.')]
 NEW.append(finish(path,title,'Compare '+left+' and '+right+' by ownership, acquisition evidence and responsibilities before an STR or second-home purchase.',body,keys,faqs))
# Context links update existing owner URLs without cloning their comparison intent.
for k in ['arrived','ember-flex','roofstock','stayrnr']:
 file=ROOT/P[k][5].strip('/')/'index.html';html=file.read_text();marker='<!-- competitor-decisions-oct6 -->'
 more=[r for r in NEW if k in r['path']]
 block=marker+section('Related purchase comparisons','<p>'+' · '.join('<a href="'+r['path']+'">'+e(r['title'])+'</a>' for r in more)+'</p>')
 if marker not in html:html=html.replace('</main>',block+'</main>',1)
 html=re.sub(r'("dateModified"\s*:\s*")[^"]+',r'\g<1>'+DATE,html)
 file.write_text(html)
for route in ['/compare/','/compare/alternatives/']:
 file=ROOT/route.strip('/')/'index.html';html=file.read_text();marker='<!-- competitor-decisions-oct6 -->';subset=NEW if route=='/compare/' else [r for r in NEW if 'alternatives-to-' in r['path']]
 block=marker+section('New purchase-model comparisons and alternatives','<p>Compare ownership, service scope and the evidence needed before committing to a purchase.</p><ul>'+''.join('<li><a href="'+r['path']+'">'+e(r['title'])+'</a></li>' for r in subset)+'</ul>')
 if marker not in html:html=html.replace('</main>',block+'</main>',1)
 file.write_text(html)
(ROOT/'_gen/competitor-decisions-oct6.json').write_text(json.dumps(NEW,indent=2))
print('Created',len(NEW),'distinct provider decisions')
