"""Expand lender qualification/liquidity decision, not seasonal reserve sizing."""
from expand_reservations_closing import main

BODY='''<p class="lead">Before buying an STR, calculate lender reserve requirements after cash to close, then separately test spendable cash for furnishings, launch and emergencies. An asset accepted for mortgage qualification is not necessarily operating money you can use tomorrow. Conversely, a verified reserve is not automatically cash deposited with the lender. Get the actual treatment in writing before you commit to an offer.</p>
<p><a href="/apply/">Book an STR acquisition call to reconcile lender reserves with your purchase and launch cash</a>.</p>
<h2>Ask which reserve rule applies to your purchase</h2>
<p>Request the reserve calculation for the exact loan product, borrower, title structure and address. Ask for months required, the payment used, eligible asset types, valuation discounts, account ownership, verification dates and any additional requirements for other properties. A headline such as “six months” does not answer all of these questions. Changes in insurance, association dues, loan amount or accepted asset value can change your result.</p>
<p><a href="https://visiolending.com/lending-process/" rel="noopener">Visio's published lending process</a> states a six-month mortgage-payment reserve and requires cash to close in addition for purchases. Its listed accounts include retirement assets credited at 70% and trust accounts at 50%. These are that provider's published criteria, not rules for every DSCR lender or confirmation that your specific account qualifies. Ask the lender to identify the exact payment definition and any current overlay in your written file.</p>
<p><a href="https://selling-guide.fanniemae.com/sel/b3-4.1-01/minimum-reserve-requirements" rel="noopener">Fannie Mae's minimum-reserve guidance</a> defines reserves as assets available after closing and subtracts funds to close from available assets. For its DU investment-property cases, it describes six months plus potentially additional requirements. This is not the rulebook for every DSCR or portfolio product. Its acceptable-source guidance also differs from a lender promising unrestricted spendable cash. Do not carry one product's eligibility decision into another quote.</p>
<h2>Use two asset columns, not one reassuring balance</h2>
<p>Prepare a dated asset register with ownership, balance, pending withdrawals, lender credit and actual availability. Share statements and identifiers only through authorized secure lender channels; a public acquisition worksheet does not need account numbers. For investments, ask how price movements and sale settlement affect verification. For retirement, trusts and pledged accounts, establish withdrawal conditions, penalties, tax consequences and third-party approval with qualified advisers before treating assets as cash.</p>
<div class="table-wrap"><table><thead><tr><th>Asset field</th><th>Lender qualification test</th><th>Buyer spending test</th></tr></thead><tbody>
<tr><td>Cash after closing</td><td>Accepted ownership and evidence; subtract required closing funds</td><td>Deduct contracted setup, launch outflows and separately protected household cash</td></tr>
<tr><td>Investment account</td><td>Accepted value after any lender discount and pending sale</td><td>Cash actually released and settled by the bill's due date, net of adviser-estimated obligations</td></tr>
<tr><td>Retirement or trust assets</td><td>Account-specific eligibility, ownership and any credit percentage</td><td>No assumed withdrawal until authority, timing and consequences are established</td></tr>
<tr><td>Restricted or pledged funds</td><td>Ask whether the lender permits them and what documentation proves availability</td><td>Do not allocate to launch bills while restrictions prevent payment</td></tr>
</tbody></table></div>
<p>These columns answer different questions. A qualification credit is not a commitment to sell an asset, and retained liquidity is not automatically an expense. Ask whether reserves must merely be evidenced, stay in a borrower account, or be deposited into a restricted account. Document the required dates and release conditions rather than labeling every reserve “restricted.”</p>
<h2>A buyer can pass the reserve test and still lack launch cash</h2>
<p>Hypothetical worksheet, not a loan offer, required down payment or client transaction: a $700,000 purchase uses a $525,000 loan. Down payment is $175,000 and cash-paid closing charges are $15,000. Assume $230,000 of designated cash and a separate $50,000 retirement balance. Cash after closing is $40,000. The assumed qualifying payment is $5,000 per month and the lender requires six months, or $30,000.</p>
<p>Assume this hypothetical lender confirms it accepts the retirement account at 70%, giving $35,000 of qualification credit. That credit alone exceeds the $30,000 reserve requirement. It does not put $35,000 in the operating account. The example intentionally leaves retirement funds untouched; it does not recommend a withdrawal or predict taxes.</p>
<div class="table-wrap"><table><thead><tr><th>Cash-only launch bridge</th><th>Hypothetical dollars</th></tr></thead><tbody>
<tr><td>Cash remaining after down payment and closing</td><td>$40,000</td></tr>
<tr><td>Contracted setup spending</td><td>−$28,000</td></tr>
<tr><td>Early launch funding before receipts</td><td>−$9,000</td></tr>
<tr><td>Spendable cash left</td><td>$3,000</td></tr>
<tr><td>Buyer's separately chosen retained emergency floor</td><td>$12,000</td></tr>
<tr><td>Gap to that floor</td><td>$9,000</td></tr>
</tbody></table></div>
<p>The buyer passes the constructed lender test but fails their own cash plan by $9,000. The chosen emergency floor is not a universal recommendation or another lender requirement. It is retained liquidity, not a second deduction of the same launch expense. Do not fill the gap with hoped-for bookings, a future tax benefit or unapproved refinancing. Use the <a href="/blog/new-listing-ramp-underwriting/">monthly launch cash bridge</a> to replace the assumed $9,000 with dated outflows and cleared receipts.</p>
<p>Now remove the hypothetical retirement credit. The $40,000 after closing initially exceeds the $30,000 requirement by $10,000. Paying $28,000 for setup before the lender's final verification leaves $12,000, a potential $18,000 qualification gap under the assumed rule. Ask which spending dates and final balance verification apply before paying vendors. This is a conditional scenario, not a claim that every lender rechecks or locks funds the same way.</p>
<h2>Choose an acquisition adjustment that fixes the real gap</h2>
<ul><li><strong>Proceed:</strong> written eligibility, required balances and dated launch cash all work independently, with protected household/business obligations outside this budget.</li>
<li><strong>Renegotiate:</strong> evaluate a lower price, a properly approved financing alternative or a documented setup change. A price cut does not release dollar-for-dollar down-payment cash, and seller credits are not automatically unrestricted reserve money.</li>
<li><strong>Delay:</strong> an asset sale, account authorization or verification remains outstanding. Obtain a valid transaction extension and update lock/closing costs rather than assuming time is free.</li>
<li><strong>Reject:</strong> purchase viability depends on unavailable assets, duplicating the same funds across purchases, or inaccurate statements to the lender.</li></ul>
<p>For multiple simultaneous purchases, have the lender confirm whether assets can satisfy more than one qualification test; do not infer permission. Even an allowed qualification overlap does not fund two simultaneous launch bills. Reconcile every property's due dates in one cash schedule. The <a href="/blog/reading-a-dscr-term-sheet/">term-sheet checklist</a> covers the wider loan commitment; this guide isolates reserve eligibility and buyer liquidity, not seasonal operating-reserve sizing.</p>
<p><a href="/apply/">Book a call to test your STR purchase budget against verified lender reserves and genuinely available launch cash</a>. For <a href="/blog/buy-str-high-income-large-tax-bill/">high-income buyers</a>, substantial account balances or an expected tax benefit are not substitutes for a documented funding schedule.</p>
<p class="small">Primary sources checked October 6, 2026. Educational information, not lending, tax, legal or personalized investment advice. All worked figures are hypothetical. Consult qualified advisers and your lender; no approval, withdrawal, tax benefit, rental income or investment result is guaranteed.</p>'''

if __name__=='__main__':
    main(slug='str-lender-reserve-requirements',title='STR Lender Reserves: Qualification vs. Launch Cash',h1='How do lender reserves change the cash needed to buy an STR?',description='Test STR lender reserve requirements separately from spendable purchase and launch cash, with an asset register and a worked qualification-gap example.',body=BODY,search_terms='reserve eligibility retirement assets launch liquidity',hub_attribute='data-lender-reserves-link',hub_block='<p data-lender-reserves-link>Account balances are not the same as launch liquidity. Use the <a href="/blog/str-lender-reserve-requirements/">lender reserve and spendable-cash worksheet</a> before setting an STR purchase budget.</p>')
