"""Existing purchase guide: unique reservation evidence, not duplicate report totals."""
from expand_reservations_closing import main

BODY='''<p class="lead">Before buying an STR advertised with Airbnb, Vrbo and direct-booking income, build one property-specific ledger of completed reservations. A channel report, property-management system and payment processor can describe the same stay. Adding their totals can make the seller's income appear larger without adding a single booking. Deduplicate by documented relationships, then reconcile adjustments and cash separately.</p>
<p><a href="/apply/">Book an STR acquisition call to review the seller's channel evidence before setting an offer</a>. This worksheet answers which reservations are unique. The <a href="/blog/reconcile-airbnb-payout-export/">payout-reconciliation guide</a> then follows charges through deductions and deposits; neither proves your future return.</p>
<h2>Map the role of each source before combining revenue</h2>
<p>Ask the authorized seller or manager which channels originate reservations, which system records them, and which service collects or remits money. A property-management system (PMS) may contain both channel bookings and direct stays. A processor may collect direct-booking payments or other charges. A bank statement records receipts, not necessarily accommodation revenue for the same stay period. Write down those roles before totaling any columns.</p>
<p><a href="https://www.airbnb.com/help/article/3632" rel="noopener">Airbnb's earnings-report guidance</a> describes listing, date and payout-method filters, as well as gross earnings, adjustments, fees and net pay. It distinguishes Upcoming from Paid transactions. Request the relevant property-specific records and their definitions; do not place projected or upcoming activity into completed-stay history simply because it appears on the same dashboard.</p>
<p><a href="https://support.stripe.com/questions/compare-dashboard-exports-to-financial-reports" rel="noopener">Stripe's report-comparison guidance</a> identifies differences in processing availability, periods, time zones, included activity and fees. It also distinguishes real-time balances from period financial movements. A report mismatch needs investigation, not an assumption that a processor total is additional rental demand.</p>
<p>Choose a common property, currency, covered period and revenue definition. Accommodation charges should not silently switch to total guest payments or net bank receipts halfway through the worksheet. Keep cleaning charges, taxes, refundable deposits, cancellations and adjustments separately identified. Record whether the period follows stay dates, transaction dates or payout dates, including how cross-period stays are handled by the preparer.</p>
<h2>Use a reservation map with unresolved rows visible</h2>
<div class="table-wrap"><table><thead><tr><th>Mapping field</th><th>Evidence</th><th>Decision check</th></tr></thead><tbody>
<tr><td>Property and source role</td><td>Listing/unit ID and seller's channel/PMS/processor explanation</td><td>Exclude other properties; distinguish booking source from mirrored report</td></tr>
<tr><td>Channel reservation ID</td><td>Completed reservation record and covered stay dates</td><td>Identify the original stay rather than a payout batch</td></tr>
<tr><td>PMS mapping</td><td>PMS reservation ID with channel reference and dated status</td><td>Prove that two records describe the same reservation before deduplicating</td></tr>
<tr><td>Payment references</td><td>Authorized processor transaction and refund references</td><td>Connect installments and adjustments without inventing extra stays</td></tr>
<tr><td>Comparable amounts</td><td>Accommodation amount, currency and separate charge categories</td><td>Do not merge gross guest charges with net settlement totals</td></tr>
<tr><td>Unresolved relationship</td><td>Missing reference, mismatch and responsible reviewer/deadline</td><td>Keep the exception visible; do not silently discard or credit it</td></tr>
</tbody></table></div>
<p>Equal dates and equal amounts are not enough to prove duplication. Different units can have simultaneous stays, and unrelated reservations can have matching prices. Conversely, one stay paid in installments can create several transactions. Have the seller supply a documented mapping using IDs and references. A missing ID is an unresolved record, not permission to delete a legitimate reservation or to count every copy as a new sale.</p>
<p>Use secure, authorized, redacted exports. The working map does not need public guest names, card data, passwords or unrelated account balances. Do not request a seller account login or publish private source documents. Record who supplied and checked each export, the filters used and whether all relevant channels were included.</p>
<h2>A worked example: five totals, only three unique channel cohorts</h2>
<p>Hypothetical completed-stay accommodation amounts for one property, one defined period and one currency: Airbnb reservations total $40,000, Vrbo reservations $30,000, and direct reservations $20,000. The PMS contains those same three cohorts, totaling $90,000. A processor report includes the same $20,000 direct accommodation charges. These are cohorts of reservations, not single stays at those prices.</p>
<div class="table-wrap"><table><thead><tr><th>Source total</th><th>Hypothetical amount</th><th>Unique accommodation contribution</th></tr></thead><tbody>
<tr><td>Airbnb completed reservations</td><td>$40,000</td><td>$40,000</td></tr>
<tr><td>Vrbo completed reservations</td><td>$30,000</td><td>$30,000</td></tr>
<tr><td>Direct completed reservations</td><td>$20,000</td><td>$20,000</td></tr>
<tr><td>PMS mirror of all three cohorts</td><td>$90,000</td><td>$0 additional after proven mapping</td></tr>
<tr><td>Processor mirror of direct accommodation charges</td><td>$20,000</td><td>$0 additional after proven mapping</td></tr>
</tbody></table></div>
<p>The blind sum is $200,000. Documented duplicate representations account for $90,000 plus $20,000, leaving $90,000 of unique accommodation charges. This constructed example expressly excludes future stays, unrelated properties, taxes, cleaning and deposit amounts, and assumes the processor row maps only to the direct accommodation charges. Actual processor reports can include other activity and net deductions; classify them before applying this arithmetic. Do not subtract a whole PMS total without first proving what it contains.</p>
<p>The resulting $90,000 is not profit, buyer cash, lender qualifying income or proof that bookings, listings or permissions transfer. Match refunds and period adjustments once using the <a href="/blog/str-refunds-chargebacks-underwriting/">refund and unresolved-dispute register</a>. Then build the buyer's cost, financing and launch model independently of the seller's report count.</p>
<h2>Do not turn payment matching into new booking revenue</h2>
<p><a href="https://support.stripe.com/questions/find-what-transactions-were-included-in-or-impacted-a-payout-amount" rel="noopener">Stripe's payout-detail guidance</a> describes transaction-level breakdowns for automatic payouts, including charges, refunds, adjustments, gross amounts and fees. It states that manual payouts do not have the same explicit connection between selected payout amounts and specific charges or activity. Ask which process the seller actually uses; do not promise an automatic match for every record.</p>
<p>A grouped payout can cover multiple direct reservations, and a single reservation can have multiple payments. Preserve both relationships rather than forcing a one-to-one match. A manager remittance or bank receipt is settlement evidence, not another originating channel. Keep prior-period receipts and unpaid amounts in a separate timing bridge. An unresolved deposit is not automatically missing rental revenue or extra current-period sales.</p>
<h2>Make the acquisition decision from the unique supported case</h2>
<p>Proceed when property scope, unique reservations, charge definitions and settlement explanations support the price and actual buyer costs. Reprice when the supported income is lower than the seller's combined dashboard claim. Delay only under valid transaction protection while a decisive mapping can be supplied by a named person and actual deadline. Reject an unsupported income premium when the purchase works only by counting repeated records or treating future bookings as completed stays.</p>
<p>Keep a one-page offer memo with the seller claim, unique supported amount, unresolved exceptions, excluded projections and remaining cost/permission questions. Your accountant and lender should review their respective requirements; the worksheet does not establish accounting treatment or approval. For <a href="/blog/buy-str-high-income-large-tax-bill/">high-income buyers with substantial capital</a>, deployable money and a tax estimate cannot validate duplicated seller demand. <a href="/apply/">Book a call to compare this property's verified channel evidence with an acquisition budget and offer worth making</a>.</p>
<p class="small">Primary sources checked October 6, 2026. Educational information only, not personalized investment, accounting, tax, lending or legal advice. All worked amounts are hypothetical. No transfer, approval, rental income, payout, tax benefit or investment result is guaranteed.</p>'''

if __name__=='__main__':
    main(slug='combine-vrbo-direct-airbnb-revenue',title='Combine STR Channel Revenue Without Double Counting',h1='How Do You Combine Airbnb, Vrbo, and Direct-Booking Revenue?',description='Before buying an STR, deduplicate Airbnb, Vrbo, PMS and direct-payment records with a reservation map and worked seller-revenue example.',body=BODY,search_terms='channel deduplication PMS processor unique reservation seller evidence',hub_attribute='data-combined-channel-link',hub_block='<p data-combined-channel-link>Does the seller quote multiple dashboards? Use the <a href="/blog/combine-vrbo-direct-airbnb-revenue/">combined-channel reservation map and duplicate-total example</a> before crediting those amounts in an STR offer.</p>')
