"""Source-checked roof condition/binding acquisition decision, not a new URL."""
import html,json,re
from pathlib import Path
from expand_reservations_closing import main
SLUG='roof-age-str-policy-binding'
BODY='''<p class="lead">An older roof can create an STR purchase problem, but age alone is not a universal reason to refuse insurance. Separate physical condition, applicable underwriting rules, roof-loss settlement terms and the timing of any required work. A seller's claim that the roof does not leak answers none of those questions completely. Before committing substantial capital, establish what coverage can become effective for your actual ownership and rental use, and what must happen first.</p>
<p><a href="/apply/">Book an acquisition call to compare the roof evidence with your closing and launch budget</a>. Have a licensed insurance professional review the proposed policy and local counsel review the transaction protections. A high income or anticipated tax benefit does not make an unresolved binding condition acceptable.</p>
<h2>Roof age, roof condition and insurance approval are different</h2>
<p>The <a href="https://www.tdi.texas.gov/news/2026/tdi09292026.html" rel="noopener">Texas Department of Insurance's September 29, 2026 clarification</a> says home-policy decisions cannot rest simply on the age of a home or roof, while physical condition can inform underwriting. This is Texas home-insurance guidance, not a nationwide rule or proof that a particular STR policy must be issued. Ask the adviser which law, policy type and underwriting requirements apply to the proposed rental use. Do not infer that an old roof is automatically uninsurable or that an age protection guarantees coverage.</p>
<p>For a specific carrier example, <a href="https://www.citizensfla.com/en/web/public/inspections" rel="noopener">Citizens' Florida inspection guidance</a> describes roof documentation and remaining-useful-life requirements. Its older-roof section requires documentation of at least five years of remaining life for soft roofs older than 25 years or hard roofs older than 50 years; below five years, proof of full replacement is required before a policy is written. These are that published program's requirements, not universal STR eligibility rules. Confirm current product applicability, accepted inspector and forms directly rather than copying a threshold into another carrier's application.</p>
<p>A general home inspection, specialist condition report, underwriting acceptance and evidence of effective coverage serve different purposes. A specialist's estimated remaining life is not an insurer commitment, a warranty or a promise of another five trouble-free years. Resolve conflicting installation dates or repair records; distinguish full replacement from resurfacing or a replaced section.</p>
<h2>Use a roof-to-binding evidence worksheet</h2>
<div class="table-wrap"><table><thead><tr><th>Decision input</th><th>Evidence to collect</th><th>Unresolved purchase risk</th></tr></thead><tbody>
<tr><td>Age, material and scope</td><td>Installation invoices, permits, warranties and dated repairs</td><td>A seller estimate may not describe every roof section</td></tr>
<tr><td>Current condition</td><td>Accepted specialist report, photographs, leaks and remaining-life findings</td><td>Functional appearance does not establish acceptable condition</td></tr>
<tr><td>Actual proposed coverage</td><td>Disclosed STR use, buyer/entity, carrier response and endorsements</td><td>A personal-use proposal may not fit the transaction</td></tr>
<tr><td>Required work and completion proof</td><td>Written scope, bid, permit/inspection requirements and insurer's acceptance procedure</td><td>Paid invoices alone may not satisfy the binding condition</td></tr>
<tr><td>Funding and deadlines</td><td>Provider dates, payment schedule, lender/closing approval and executed protections</td><td>A future credit does not fund earlier work or extend a deadline</td></tr>
</tbody></table></div>
<p>Ask the insurance professional to state what remains conditional and who confirms completion. Have the lender confirm acceptability of coverage and any repair arrangement. Local counsel should identify actual notice, extension and termination rights; an insurance, inspection or financing deadline is not automatically interchangeable with another. This is a diligence checklist, not contract language or a promised deposit refund.</p>
<h2>Worked hypothetical: replacement moves into acquisition cash</h2>
<p>Invented figures only, not contractor bids, typical premiums or a client result. Assume a $750,000 price and approved $562,500 loan, leaving $187,500 price cash. Add $17,500 closing costs including the originally budgeted premium, $35,000 setup and a protected $30,000 post-setup reserve. Base capital need is $270,000. With $300,000 designated accessible cash, the apparent extra buffer is $30,000.</p>
<p>Now assume property-specific written requirements and bids add $28,000 roof replacement and $2,000 distinct inspection/permit costs, neither included in setup or closing. Required capital becomes $300,000. The $30,000 reserve still exists, but no unallocated buffer remains. Calling both that reserve and the spent $30,000 a roof buffer counts the same money twice. If opening slips and requires $6,000 additional continuing bills not already budgeted, total becomes $306,000: a $6,000 gap when the reserve is protected.</p>
<p>For a separate approved $20,000 price reduction, assume the lender retains the same 75% price-based loan ratio and other modeled costs stay fixed. Price becomes $730,000, loan $547,500 and price cash $182,500. Total including roof, extra inspections and delay is $301,000. Buyer cash need falls only $5,000, not $20,000, because the loan also falls $15,000. The remaining gap is $1,000. Actual appraisal, loan terms and settlement costs must be recalculated; this is not an available financing offer.</p>
<p>A seller credit is a different case, subject to lender and settlement limits and eligible costs. It does not necessarily pay the roofer, reduce the required down payment or become freely spendable cash. Use the <a href="/blog/seller-credit-str-furnishings/">seller-credit cash framework</a> to distinguish eligible closing relief from a repair-payment plan. Never hide roof work or invent a furniture allocation to obtain funds.</p>
<h2>Check the binding sequence before paying for work</h2>
<p>If accepted coverage requires completion before closing, a buyer-funded post-closing replacement cannot satisfy that sequence by itself. Determine whether the seller will complete the approved work before settlement, whether another fully disclosed insurer arrangement is acceptable, or whether the transaction must change or stop. An assumed future binder is not present coverage.</p>
<p>For example, a contractor's estimated completion on day 18 does not fit a day-15 closing that requires accepted completion evidence first. Even day-14 completion may leave insufficient time for required final inspection and insurer review. These invented dates are not standard inspection periods. Build the actual dependency chain: access, permits, work, completion evidence, underwriting acceptance, lender approval and effective coverage. Obtain any valid extension before a protection expires; neither the contractor nor an acquisition adviser can unilaterally extend it.</p>
<p>Buyer money spent improving seller-owned property before settlement creates a separate exposure if the sale fails. Ask counsel who authorizes work, owns the contract, bears damage risk and owes repayment, and ask the lender and insurer about the proposed arrangement. Do not assume automatic reimbursement or recommend an unsecured advance merely to preserve a closing date.</p>
<h2>Approval does not settle future roof claims</h2>
<p><a href="https://www.tdi.texas.gov/tips/replacing-your-roof.html" rel="noopener">TDI's roof-policy guidance</a> distinguishes replacement-cost and actual-cash-value treatment and warns that old age or wear alone does not earn a new-roof claim payment. Its Texas consumer explanation does not establish the settlement of your STR policy. Review depreciation, any roof schedule, exclusions and deductibles with the qualified adviser even after binding conditions are met. Do not budget an insurance-funded replacement of ordinary worn-out roofing.</p>
<p>The <a href="/blog/wind-deductible-str-reserve/">wind-event cash worksheet</a> separately tests a covered-event deductible and payment timing. The <a href="/blog/str-insurance-quote-before-purchase-offer/">purchase insurance quote guide</a> covers broader policy suitability. This page resolves whether roof evidence and required work fit this acquisition's funded closing sequence; it does not duplicate either decision.</p>
<p>Proceed when actual condition, appropriate coverage, accepted completion evidence and capital timing are documented. Renegotiate price or seller work only when the revised sequence and economics work. Delay under valid protection while decisive evidence is obtainable. Reject a purchase dependent on undisclosed use, an uninsured gap or unfunded pre-closing work. <a href="/apply/">Bring the roof worksheet and dated funding plan to an acquisition call</a>. BNB Accelerator assists within its contracted acquisition scope; licensed insurance professionals, insurers, lenders and independent counsel determine their respective approvals.</p>
<p class="small">Primary sources reviewed October 6, 2026. Educational information only, not insurance, legal, tax, lending or personalized investment advice. All worked amounts and dates are hypothetical. No policy approval, claim payment, reimbursement, deduction or investment result is guaranteed.</p>'''
if __name__=='__main__':
 main(slug=SLUG,title='STR Roof Age and Insurance Binding: Closing Cash Test',h1='Can an Old Roof Prevent STR Insurance Binding?',description='Before buying an STR, verify roof condition, policy binding requirements, replacement timing and funded closing cash without assuming an age-only rejection.',body=BODY,search_terms='roof age condition insurance binding replacement closing cash deadline',hub_attribute='data-roof-binding-link',hub_block='<p data-roof-binding-link>Older roof on a shortlisted property? Use the <a href="/blog/roof-age-str-policy-binding/">roof condition, insurance-binding and closing-cash worksheet</a> before committing to required replacement or an unresolved coverage deadline.</p>')
 p=Path(__file__).resolve().parents[1]/'blog'/SLUG/'index.html';s=p.read_text();words=len(re.findall(r'\b\w+\b',html.unescape(re.sub('<[^>]+>',' ',BODY))))
 def schema(m):
  d=json.loads(m.group(2))
  for n in d.get('@graph',[d]):
   if n.get('@type') in ['Article','BlogPosting']:n['wordCount']=words
  return m.group(1)+json.dumps(d,indent=2)+m.group(3)
 p.write_text(re.sub(r'(<script[^>]*type="application/ld\+json"[^>]*>)(.*?)(</script>)',schema,s,flags=re.S))
