"""Refresh furnishing-credit scope and timed cash; preserve approved Q&A."""
import json,re,subprocess
from pathlib import Path
from expand_reservations_closing import main,ROOT
SLUG='seller-credit-str-furnishings'
BODY='''<p class="lead">A seller credit can preserve some of your own cash at closing, but it is not automatically a furniture payment or money delivered to your bank account. Before an STR offer, establish what furnishings actually convey, what the lender permits and whether your remaining cash covers the dated setup invoices and operating reserve. A large advertised allowance cannot replace a funded rental-readiness plan.</p>
<p><a href="/apply/">Book an acquisition call to review the property inventory and cash-through-opening budget</a>. Bring the proposed credit language and lender response, not just the seller's advertised furnishing value. The lender, closing professional and local counsel must review their respective terms.</p>
<h2>Identify what the seller is really offering</h2>
<p>Separate included personal property, an eligible settlement credit, a seller-paid vendor invoice and a promise of reimbursement after closing. Those are different arrangements. Ask who receives the money, which expense it pays, when payment occurs, who owns delivered items and what happens if the arrangement fails. Submit the actual proposal to the lender before assuming its treatment; do not use an undisclosed side agreement to obtain a different result.</p>
<p>This guide addresses furnishing scope and available setup cash. The <a href="/blog/str-seller-credit-vs-price-reduction/">seller-credit versus price-reduction guide</a> already compares offer structures and debt. The <a href="/blog/appraisal-gap-furnished-str/">furnished-property appraisal-gap worksheet</a> separately tests collateral and financing. A listed furniture package does not establish an equal increase in mortgage collateral value.</p>
<h2>Confirm credit classification before budgeting it</h2>
<p><a href="https://selling-guide.fanniemae.com/sel/b3-4.1-02/interested-party-contributions-ipcs" rel="noopener">Fannie Mae's interested-party contribution guidance</a> excludes such contributions from down payment, reserves and minimum borrower contribution. It limits investment-property financing concessions to 2% of the lower of price or appraised value, with eligible closing-cost constraints and specified exceptions. Excess concessions receive different underwriting treatment; they are not automatically a cash payout.</p>
<p>The same guidance identifies furniture and decorator allowances as examples of non-realty sales concessions and requires a sales-price adjustment for their underwriting treatment. Disclosed classification matters. These are Fannie Mae rules, not universal DSCR or portfolio terms; ask your actual lender to identify applicable treatment, any value adjustment, permitted charges and final cash to close. Do not assume renaming an allowance a closing credit makes it eligible.</p>
<p>Request a revised settlement estimate showing each accepted charge and credit. Check for other contributions consuming the permitted capacity. A credit may save less than its headline when charges or program capacity are smaller; let the lender and closing team resolve any remaining concession under the actual contract and guidelines. Never count the same credit both as reduced closing cash and an extra deposit into the setup account.</p>
<h2>Build the furnishing scope from verified inventory</h2>
<p>Walk through every intended guest space with an agreed inventory, dated photos, condition notes and explicit exclusions. Ask the transaction team to document what conveys and how missing or changed items will be handled. A seller's retail-value list is neither proof the buyer owns those items nor a current replacement quote. Resolve rented, leased or separately owned equipment and any accepted obligations with the appropriate parties.</p>
<div class="table-scroll"><table><thead><tr><th>Scope line</th><th>Evidence before the offer deadline</th><th>Cash consequence</th></tr></thead><tbody>
<tr><td>Items included and usable</td><td>Agreed inventory, condition and exclusions; ownership verification</td><td>Remove only supported purchases from the buyer's setup scope</td></tr>
<tr><td>Missing or unsuitable items</td><td>Required-use plan and itemized replacement quote</td><td>Fund replacement, not advertised original retail value</td></tr>
<tr><td>Delivery and installation</td><td>Accepted vendor quote and realistic timing</td><td>Include freight, assembly, tax and other quoted charges once</td></tr>
<tr><td>Credit or seller payment</td><td>Lender classification and closing documentation</td><td>Record the approved payee, use, amount and payment date</td></tr>
<tr><td>Launch and retained liquidity</td><td>Readiness milestones and reserve allocation</td><td>Do not spend the operating floor on furniture twice</td></tr>
</tbody></table></div>
<p>Included items reduce the required shopping scope only when they are suitable and available. They do not supply cash for a delivery deposit or another invoice. Reconcile the inventory at the agreed pre-closing check and escalate substitutions, damage or exclusions through counsel and the contract process. Do not assume an automatic repair credit, enforceable replacement duty or right to withhold funds without reviewing the actual agreement.</p>
<h2>Worked hypothetical: the credit preserves cash, not furniture</h2>
<p>Invented planning example, not a lender quote, actual appraisal or client transaction. Assume $600,000 price and accepted value, a $450,000 loan, $150,000 buyer price cash, $14,000 eligible closing charges, and a requested $15,000 seller credit. Assume the lender confirms only $12,000 usable against those charges and that the final documented terms contain that amount, not an unresolved extra $3,000 allowance. No other contribution is assumed to consume capacity.</p>
<p>Under those assumptions, cash to close is $150,000 plus $14,000 minus $12,000, or $152,000. Without the credit it would be $164,000. If the buyer has $215,000 designated for the acquisition, $63,000 remains after the approved-credit closing, versus $51,000 without it. The $12,000 saving is already included in that remainder; adding another $12,000 furniture inflow would double-count the benefit.</p>
<p>Suppose independently quoted remaining setup totals $45,000: $31,000 missing furniture/equipment, $8,000 delivery/assembly/tax and $6,000 other opening work. Assume the retained operating-reserve target is $20,000, separate from setup invoices. The approved-credit case leaves $18,000 after setup, $2,000 short of that reserve target. The no-credit case leaves $6,000, $14,000 short. Both need revision despite the first case's lower closing cash.</p>
<p>Now suppose verified included items eliminate $7,000 of purchases already contained in the $31,000 line, without changing the other assumed costs. Setup falls to $38,000; the credit case leaves $25,000, including the $20,000 reserve and $5,000 unallocated. This works only if the inventory is suitable and the financing/contract treatment is confirmed. Do not subtract $7,000 twice or add seller retail value to the buyer's bank balance.</p>
<h2>Check the invoice schedule before scheduling opening</h2>
<p>For that separate $38,000 revised scope, suppose $10,000 is due after closing to place orders, $16,000 on delivery and $12,000 at completion. These three payments total $38,000; they are timing rows, not another $38,000 expense. From the modeled $63,000 remainder, cash falls to $53,000, $37,000 and $25,000. The $20,000 reserve remains available in this simplified schedule, provided no omitted bill or delay consumes the $5,000 buffer.</p>
<p>If a vendor requires a deposit before closing, identify separately funded eligible cash and its effect on the loan file and final balance. Do not assume a closing credit will arrive early to pay it. Refresh the schedule with permit, condition, insurance and contractor dependencies; do not book guests merely because furniture has been ordered. Add actual delay costs and an appropriately chosen downside allowance once, not a fabricated universal contingency percentage.</p>
<p>Proceed when the documented inventory, permitted credit and timed cash plan support lawful readiness while retaining reserves. Renegotiate the scope or permitted terms when setup creates a gap. Delay under valid contract protection while inventory or lender treatment is unresolved; reject arrangements requiring hidden payments or spending money that is not available. <a href="/apply/">Bring the inventory, accepted quotes and settlement cash bridge to an acquisition call</a>. BNB Accelerator works within its contracted scope and does not determine loan eligibility or guarantee an opening date.</p>
<p class="small">Primary Fannie Mae source reviewed October 6, 2026. Educational information, not legal, tax, lending or personalized investment advice. All numerical figures, quotes and timing assumptions are hypothetical. No appraisal, credit approval, tax result, launch timing or investment return is guaranteed.</p>'''
if __name__=='__main__':
 p=ROOT/'blog'/SLUG/'index.html';source=p.read_text()
 block=re.search(r'<!-- preclosing-keywords:start -->.*?<!-- preclosing-keywords:end -->',source,re.S).group()
 faqs=[m.group() for m in re.finditer(r'<script[^>]*type="application/ld\+json"[^>]*>.*?</script>',source,re.S) if json.loads(re.search(r'>(.*?)</script>',m.group(),re.S).group(1)).get('@type')=='FAQPage']
 assert len(faqs)==1
 data=json.loads(re.search(r'>(.*?)</script>',faqs[0],re.S).group(1));assert len(data['mainEntity'])==5
 for q in data['mainEntity']:assert q['name'] in block and q['acceptedAnswer']['text'] in block
 p.write_text(source.replace(faqs[0],''))
 main(slug=SLUG,title='Seller Credits and STR Furnishings: Cash-Through-Setup Test',h1='How Should a Seller Credit Affect an STR Furnishing Budget?',description='Verify seller-credit treatment and included furnishings before buying an STR. Test settlement savings, setup invoices and retained operating cash.',body=BODY+'\n'+block,search_terms='seller credit furnishing allowance inventory setup invoices cash closing reserve',hub_attribute='data-furnishing-credit-link',hub_block='<p data-furnishing-credit-link>For a furnished or allowance-based offer, use the <a href="/blog/seller-credit-str-furnishings/">seller-credit inventory and setup cash bridge</a> to separate permitted closing savings from furniture invoices and retained reserves.</p>')
 p.write_text(p.read_text().replace('</head>',faqs[0]+'\n</head>'))
 subprocess.run(['node','--input-type=module','-e',"import {readFileSync,writeFileSync} from 'node:fs';import {expandPreclosingKeywords} from './preclosing_keywords.mjs';const p='blog/seller-credit-str-furnishings/index.html';writeFileSync(p,expandPreclosingKeywords(readFileSync(p,'utf8'),p));"],cwd=ROOT,check=True)
 final=p.read_text();assert re.search(r'<!-- preclosing-keywords:start -->.*?<!-- preclosing-keywords:end -->',final,re.S).group()==block
 minutes=re.search(r'<span>(\d+) min read</span>',final).group(1)
 archive=ROOT/'blog/index.html'
 archive.write_text(re.sub(r'<article class="post-card".*?</article>',lambda m:re.sub(r'<span>\d+ min read</span>',f'<span>{minutes} min read</span>',m.group()) if '/blog/'+SLUG+'/' in m.group() else m.group(),archive.read_text(),flags=re.S))
 print('Approved normalizer: '+minutes+' min; five original visible Q&A preserved with matching schema')
