"""Expand early seller disbursement risk, preserving original Q&A and dates."""
import json,re,subprocess
from expand_reservations_closing import main,ROOT
SLUG='earnest-money-release-str'
BODY='''<p class="lead">Early earnest-money release means paying some or all of a held deposit to the seller before the STR purchase closes. It is not the same as increasing the deposit held in escrow, letting a contingency expire or receiving your money back after cancellation. Before agreeing, identify the unresolved purchase risks, the actual remedies after disbursement and whether you can move on without prompt recovery. Substantial income does not make a contractual claim equivalent to liquid cash.</p>
<p><a href="/apply/">Book an acquisition call to review the seller's release request alongside the remaining STR diligence</a>. Bring the proposed amendment, deposit receipt and evidence status. Local transaction counsel and the escrow or closing professional must review the actual authority, terms and money handling.</p>
<h2>Find out what changes when money leaves escrow</h2>
<p>Ask who holds the deposit now, who receives the proposed payment, when it is authorized and how it is credited if closing succeeds. Have counsel explain whether refund rights, default remedies, security or other protections change. A promise that the seller will repay after a failed transaction is different from money still held by an independent escrow holder. Do not assume every escrowed deposit is immediately refundable either; disputes and governing procedures can delay disbursement.</p>
<p>The <a href="https://www.trec.texas.gov/node/33" rel="noopener">Texas Real Estate Commission's earnest-money FAQs</a> explain that it does not decide entitlement to earnest money, cannot order damages and does not have jurisdiction over title companies; private counsel is needed for those disputes. It also describes release provisions in its promulgated forms when a broker holds the funds. This is Texas-specific context, not a national refund procedure or authority to release an STR deposit early.</p>
<p>This guide concerns the change from held funds to seller-controlled funds. The <a href="/blog/earnest-money-amount-str-offer/">deposit-size guide</a> addresses offer commitment and staged deposits; the <a href="/blog/inspection-contingency-length-str/">inspection-window worksheet</a> addresses decision-ready evidence before expiry. A release amendment can affect these arrangements, so review the whole executed contract and amendments rather than reading one reassuring sentence alone.</p>
<h2>Use a release review matrix before approving instructions</h2>
<p>For each issue, record the document, independent reviewer, outstanding answer and exact transaction deadline. Ask counsel what remains enforceable after the proposed release. This is an evidence-planning tool, not contract language or a legal conclusion that a particular request is permissible.</p>
<div class="table-scroll"><table><thead><tr><th>Release question</th><th>Evidence to review</th><th>Buyer decision consequence</th></tr></thead><tbody>
<tr><td>What money is leaving?</td><td>Deposit receipt, held balance, exact amount/payee and proposed instructions</td><td>Separate released cash from the remaining held balance</td></tr>
<tr><td>Which purchase conditions remain?</td><td>Permit/association, title, condition, lender/appraisal and insurance records</td><td>Do not treat incomplete review as affirmative approval</td></tr>
<tr><td>What happens if closing fails?</td><td>Counsel's interpretation of actual amended rights, duties and dispute process</td><td>Test delayed/no recovery instead of assuming a quick refund</td></tr>
<tr><td>What supports repayment?</td><td>Adviser-reviewed obligor and any actual protection/security</td><td>A promise or suggested guarantee is not cash availability</td></tr>
<tr><td>How is successful closing credited?</td><td>Lender-approved treatment and revised settlement estimate</td><td>Apply the paid deposit once; avoid another purchase expense</td></tr>
<tr><td>Who can authorize payment?</td><td>Closing professional's verified requirements and counsel-reviewed signatures</td><td>A casual seller request is not sufficient instruction</td></tr>
</tbody></table></div>
<p>Do not call a permit question resolved because the seller has operated rentals. Verify buyer eligibility and intended use with the responsible authority and controlling documents. Likewise, borrower preapproval does not complete property underwriting, and an insurance indication does not establish every binding condition is met. Prioritize the unresolved issue that could defeat the purchase rather than releasing funds merely because the closing date is approaching.</p>
<p>If the seller needs relocation money, that explains the request but does not establish the buyer's risk is acceptable. Ask the transaction team whether waiting for a decisive milestone, reducing the requested amount or retaining funds until closing is an available negotiated alternative. A staged additional deposit in escrow is not identical to early disbursement. Any replacement protection must be reviewed, agreed and documented; no universal clause, recovery period or safe percentage is supplied here.</p>
<h2>Worked hypothetical: a discount does not fund the recovery risk</h2>
<p>Invented comparison only, not a client transaction, loan quote or legal opinion. Assume $300,000 designated buyer cash, a $30,000 deposit already held and $4,000 of completed diligence paid separately. Accessible cash is therefore $266,000. The seller requests release of $20,000 from the held deposit, leaving $10,000 held, and offers an $8,000 price reduction. Moving that $20,000 from the escrow holder to the seller does not change the buyer's current $266,000 bank balance; it changes the location and possible recoverability of money already paid.</p>
<p>For the successful-closing branch, assume an $800,000 original price, $600,000 loan, $20,000 other closing costs, $35,000 setup and $30,000 retained operating reserve. Assume the full $30,000 deposit is correctly credited toward price cash. Remaining closing cash is $200,000 buyer price cash plus $20,000 costs minus $30,000 already paid, or $190,000. From the accessible $266,000, closing, setup and reserve allocate $255,000 and leave $11,000 outside the plan. Do not add the released $20,000 as another expense when it is part of that same credited deposit.</p>
<p>Assume the $8,000 reduction produces a $792,000 price and the lender separately approves a $594,000 loan, retaining the example's 75% loan proportion. Buyer price cash becomes $198,000; remaining closing cash is $188,000 with the same assumed fees and deposit credit. Outside-plan cash rises to $13,000, only $2,000 more immediately, while starting loan principal is $6,000 lower. Actual fees, appraisal and loan treatment must be requoted. The $8,000 headline discount is not an $8,000 cash buffer against the $20,000 early payment.</p>
<h2>Test the failed-purchase branch without expected refunds</h2>
<p>Suppose a later decisive review defeats the STR thesis and advisers identify a valid way to terminate under the actual terms. For planning, assume no deposit money has yet returned; neither the held $10,000 nor the released $20,000 is available. The buyer still has $266,000 accessible after the original deposit and diligence outflows. Assume a different vetted property's complete closing, setup and reserve allocation is $275,000. There is a $9,000 funding gap before any refund, even if the buyer believes the full deposit should eventually come back.</p>
<p>If the $10,000 held balance is actually returned and cleared, accessible funds rise to $276,000, leaving $1,000 beyond that alternative's assumed allocation. If the additional $20,000 is later actually recovered with no costs, accessible funds would rise to $296,000 and leave $21,000. Those are distinct receipt scenarios, not predictions that either party must refund, that escrow money returns faster or that litigation costs nothing. Add actual legal, dispute and funding costs and dates before making another commitment. Do not assign an invented probability to recovery to manufacture an expected-value justification.</p>
<p>The $20,000 released is not necessarily the maximum loss under a breached contract. Counsel should identify other possible remedies, expenses and obligations. Keep the seller's successful-closing discount out of the failed-purchase branch: a reduction on a property not acquired has not replenished the buyer's cash. Never close a newly unsuitable property solely to avoid acknowledging money already at risk.</p>
<h2>Approve a release only from verified terms and affordable downside</h2>
<p>Proceed only when the decisive evidence, amended remedies and cash exposure are understood and acceptable after independent review. Renegotiate the timing, amount or documented structure when an unresolved condition makes the request premature. Delay under actual valid protection while professional or authority answers remain outstanding. Reject a release that relies on unsupported refund promises, hidden instructions or pressure to ignore a defective purchase case.</p>
<p>Before any payment, independently confirm instructions with the known closing professional through an established contact method; verify the authorized recipient, signatures and receipt procedure. Maintain the executed documents and transfer evidence securely. Update the purchase budget and settlement credit once, then preserve household/business liquidity outside this property's cash. <a href="/apply/">Bring the release matrix and both cash branches to an acquisition call</a>. BNB Accelerator assists within its contracted scope; it does not adjudicate deposits, draft personalized legal remedies or guarantee recovery.</p>
<p class="small">Primary TREC guidance reviewed October 6, 2026. Educational information, not legal, tax, lending or personalized investment advice. All numerical assumptions are hypothetical. No release authority, refund, financing, STR permission, tax benefit or investment result is guaranteed.</p>'''
if __name__=='__main__':
 p=ROOT/'blog'/SLUG/'index.html';source=p.read_text()
 block=re.search(r'<!-- preclosing-keywords:start -->.*?<!-- preclosing-keywords:end -->',source,re.S).group()
 faqs=[m.group() for m in re.finditer(r'<script[^>]*type="application/ld\+json"[^>]*>.*?</script>',source,re.S) if json.loads(re.search(r'>(.*?)</script>',m.group(),re.S)[1]).get('@type')=='FAQPage']
 assert len(faqs)==1
 data=json.loads(re.search(r'>(.*?)</script>',faqs[0],re.S)[1]);assert len(data['mainEntity'])==5
 for q in data['mainEntity']:assert q['name'] in block and q['acceptedAnswer']['text'] in block
 p.write_text(source.replace(faqs[0],''))
 main(slug=SLUG,title='Early Earnest-Money Release for an STR: Buyer Cash Test',h1='When Is Early Earnest-Money Release Too Risky for an STR?',description='Review early STR earnest-money release before money leaves escrow. Compare unresolved diligence, recovery risk and cash for a replacement purchase.',body=BODY+'\n'+block,search_terms='early earnest money release seller escrow deposit refund recovery cash alternative purchase',hub_attribute='data-early-deposit-release-link',hub_block='<p data-early-deposit-release-link>Before paying a held deposit to the seller, use the <a href="/blog/earnest-money-release-str/">early-release evidence and recovery cash test</a> to assess unfinished diligence and funding without an assumed quick refund.</p>')
 p.write_text(p.read_text().replace('</head>',faqs[0]+'\n</head>'))
 subprocess.run(['node','--input-type=module','-e',"import {readFileSync,writeFileSync} from 'node:fs';import {expandPreclosingKeywords} from './preclosing_keywords.mjs';const p='blog/earnest-money-release-str/index.html';writeFileSync(p,expandPreclosingKeywords(readFileSync(p,'utf8'),p));"],cwd=ROOT,check=True)
 final=p.read_text();assert re.search(r'<!-- preclosing-keywords:start -->.*?<!-- preclosing-keywords:end -->',final,re.S).group()==block
 minutes=re.search(r'<span>(\d+) min read</span>',final)[1];archive=ROOT/'blog/index.html'
 archive.write_text(re.sub(r'<article class="post-card".*?</article>',lambda m:re.sub(r'<span>\d+ min read</span>',f'<span>{minutes} min read</span>',m.group()) if '/blog/'+SLUG+'/' in m.group() else m.group(),archive.read_text(),flags=re.S))
 print('Approved normalizer: '+minutes+' min; five exact Q&A and schema retained')
