"""Expand the existing pre-launch coverage handoff purchase decision."""
import html,json,re
from pathlib import Path
from expand_reservations_closing import main
SLUG='vacant-renovation-str-coverage'
BODY='''<p class="lead">Before buying an STR that will sit empty or undergo work, arrange coverage for the property you will own on closing day, not only for the guest-ready property you hope to open later. Vacancy, construction and rental operation are different facts to disclose. An operating-policy quote does not establish that the pre-launch interval is covered, and a construction-policy label does not settle every owner exposure.</p>
<p><a href="/apply/">Book an acquisition call to review the coverage phases beside your renovation and opening cash plan</a>. A licensed insurance professional should interpret the actual proposal and endorsements. A well-funded buyer still needs an effective, documented handoff; income and a hoped-for tax deduction cannot repair an uninsured interval.</p>
<h2>Disclose the real work and occupancy before binding</h2>
<p>Give the adviser the buyer/entity, address, possession date, current occupancy, intended STR use, detailed work scope, contractor arrangement, expected duration and first proposed guest date. Distinguish painting and furniture delivery from open walls, roof work, structural changes or major system replacement. State whether the building is usable, utilities remain on, materials are stored elsewhere and any part will be occupied during work. Do not call the property occupied solely because furnishings or contractors are present; ask how the proposed policy defines vacancy and unoccupancy.</p>
<p><a href="https://www.travelers.com/resources/home/insuring/does-homeowners-insurance-cover-renovations" rel="noopener">Travelers' renovation guidance</a> recommends reviewing coverage before work, disclosing improvements and checking contractor/subcontractor insurance. It notes that renovation can change rebuilding needs and liability exposure. That homeowners education is not approval for your commercial rental activity or a guarantee that every renovation requires the same replacement policy.</p>
<p>Ask whether existing coverage with accepted endorsements, a vacant-property arrangement, builders' risk or another tailored combination fits the actual project. The adviser and insurer must determine suitability. Do not publish or rely on a universal 30-, 60- or 90-day vacancy limit; obtain the actual definitions, conditions, dates and notification requirements. The purchase question is whether suitable coverage can be effective when your risk starts, not whether a familiar policy name appears on a quote.</p>
<h2>Record the coverage handoff by phase</h2>
<div class="table-wrap"><table><thead><tr><th>Phase</th><th>Evidence to request</th><th>Decision before moving forward</th></tr></thead><tbody>
<tr><td>Possession before work</td><td>Effective coverage for disclosed occupancy, buyer and property; lender acceptance</td><td>What protects the existing building and owner liability from the actual possession date?</td></tr>
<tr><td>Construction and storage</td><td>Covered property, work scope, materials locations, exclusions and contractor insurance review</td><td>Which losses remain the owner's responsibility, and who funds them?</td></tr>
<tr><td>Work complete but not open</td><td>Completion/inspection evidence, policy end triggers and next coverage effective date</td><td>Does a waiting period for permission or furnishing create a gap?</td></tr>
<tr><td>First guest and operation</td><td>Confirmed rental-use coverage, accepted amenities/capacity and operational limits</td><td>Can guests arrive lawfully and with the intended coverage effective?</td></tr>
</tbody></table></div>
<p>For every phase record the provider, document date, named reviewer, outstanding condition and exact effective/expiry terms. Ask what completion, occupancy, cancellation or expiration does to construction coverage and what starts the next policy. Coordinate an approved sequence before canceling existing coverage. Buying two policies does not automatically resolve exclusions or assure that a loss falls under either.</p>
<p><a href="https://www.travelers.com/business-insurance/inland-marine/construction/builders-risk" rel="noopener">Travelers' builders' risk description</a> identifies construction property and material exposures but expressly makes actual coverage dependent on policy terms, facts, underwriting and applicable law. Treat it as evidence that project-specific review matters, not a promise that this product is available or sufficient for an STR. Ask explicitly about the existing structure, new works, furnishings, materials in transit/storage, water, theft, liability and delay costs. A contractor's insurance document is not confirmation of payment for every owner loss or a substitute for reviewing your own coverage.</p>
<h2>Worked hypothetical: fund the extension, not just the original premium</h2>
<p>Invented amounts only, not available quotes, typical construction costs or a client outcome. Assume $350,000 accessible cash designated for acquisition and launch. The plan needs $220,000 at closing, $45,000 renovation, $25,000 furnishings, $3,000 separately quoted transition coverage, $12,000 no-revenue carry and $2,000 distinct completion/inspection costs. None of these amounts overlap. Add a protected $30,000 operating reserve intended to remain after opening.</p>
<p>Total planned capital is $337,000, leaving $13,000 unallocated. The $12,000 carry assumes two months at $6,000 monthly continuing bills and includes no cost already counted in the $3,000 coverage line. It is spent during readiness; the $30,000 operating reserve is retained. Actual lender reserves, household liquidity and other liabilities must also be reconciled rather than counting the same funds again.</p>
<p>Now assume opening requires two additional months, with another $12,000 of those continuing bills. Assume the adviser obtains an accepted extension costing $1,500 more, with no cancellation refund or insurer-paid delay receipt counted. Revised need is $350,500, a $500 gap while preserving the operating reserve. More cash alone does not secure the extension: obtain actual insurer acceptance and effective dates. The assumed extension and its price are planning inputs, not guaranteed availability.</p>
<p>In a separate scope-change stress, add $18,000 of unexpected owner-funded work not included in the original $45,000 renovation or delay bills. Combined revised need becomes $368,500, an $18,500 gap. Do not add the entire original $45,000 renovation again when only $18,000 changed. If actual work is already paid, show paid-to-date plus remaining obligations; do not subtract completed invoices and still include the full contract as another future payment.</p>
<p>Foregone booking revenue can change the return comparison, but it is not an extra cash invoice to add mechanically to the no-revenue bills. Rebuild the first-year operating case from the revised opening date using the <a href="/blog/str-purchase-to-launch-timeline/">purchase-to-launch dependency guide</a>. Do not assume claim payment, cancellation refund, certain rebooking or a future tax benefit funds today's premium or contractor bill.</p>
<h2>Scope changes require a coverage decision, not only a change order</h2>
<p>If furnishing work reveals water damage or requires structural repairs, notify the qualified adviser with the revised scope, dates and site facts before treating the original insurance plan as still suitable. Record the insurer's answer and revised funding need. Ask about any conditions for safeguards, utilities, access, inspections and material storage; assign responsibility for complying with the actual terms. Do not invent a universal inspection frequency or claim that an unattended building is covered because a camera is installed.</p>
<p>A room-by-room launch is not an automatic solution. Disclose partial occupancy and continuing work, obtain insurer/lender approval where required, and verify local safety and rental permission before making dates available. The <a href="/blog/roof-age-str-policy-binding/">roof-binding guide</a> addresses an existing condition that can control the closing sequence; this guide addresses the later occupancy and construction transitions. Keep both decisions explicit.</p>
<p>Before an offer becomes unprotected, resolve whether the coverage plan, required work, no-revenue interval and funding can fit the transaction. Proceed with documented appropriate coverage and funded timing. Renegotiate scope, seller work or price only when the revised plan remains feasible. Delay under valid contract protection while decisive terms are obtainable. Reject a deal that depends on concealing the work, operating before approval or an unconfirmed extension.</p>
<p><a href="/apply/">Bring the phase ledger, dated insurance responses and delayed-opening cash test to an acquisition call</a>. BNB Accelerator assists within its contracted acquisition scope; licensed insurance professionals, insurers, lenders, permitting authorities and independent counsel determine their respective approvals. Primary Travelers sources reviewed October 6, 2026. Educational information, not insurance, legal, tax, lending or personalized investment advice. All figures and durations are hypothetical. No coverage, reimbursement, tax benefit or investment result is guaranteed.</p>'''
if __name__=='__main__':
 main(slug=SLUG,title='STR Renovation Insurance: Vacancy and Coverage Handoff',h1='What Insurance Covers an STR During Renovation Before Launch?',description='Buying an STR to renovate? Map vacancy, construction and first-guest coverage, confirm handoff conditions and fund an extension without assumed claim proceeds.',body=BODY,search_terms='vacant renovation construction builders risk coverage handoff extension opening cash',hub_attribute='data-renovation-coverage-link',hub_block='<p data-renovation-coverage-link>Buying before renovation and launch? Use the <a href="/blog/vacant-renovation-str-coverage/">vacancy-to-operation coverage handoff and extension-cash test</a> to align insurance with the actual work, occupancy and first-guest dates.</p>')
 p=Path(__file__).resolve().parents[1]/'blog'/SLUG/'index.html';s=p.read_text();words=len(re.findall(r'\b\w+\b',html.unescape(re.sub('<[^>]+>',' ',BODY))))
 def schema(m):
  d=json.loads(m.group(2))
  for n in d.get('@graph',[d]):
   if n.get('@type') in ['Article','BlogPosting']:n['wordCount']=words
  return m.group(1)+json.dumps(d,indent=2)+m.group(3)
 p.write_text(re.sub(r'(<script[^>]*type="application/ld\+json"[^>]*>)(.*?)(</script>)',schema,s,flags=re.S))
