#!/usr/bin/env python3
"""Build BNB review evidence library from existing public case/tracker sources.
No client forecasts, outcomes, quotes, or review ratings are invented.
"""
from pathlib import Path
import csv,html,json,re,sys,xml.etree.ElementTree as ET
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'_gen'))
import tpl
from case_studies import records
DATE='2026-10-08'
START='<!-- BNB review evidence start -->'; END='<!-- BNB review evidence end -->'
CASES=records()
DEALS=json.loads((ROOT/'_gen/deals.json').read_text())['deals']
def esc(s):return html.escape(str(s),quote=True)
def money(n):return f'${n:,.0f}'
def paragraph(s):return '<p>'+s+'</p>'
def section(title,body):return '<section class="section"><div class="container narrow"><h2>'+esc(title)+'</h2>'+body+'</div></section>'
def table(headers,rows):return '<div class="table-scroll"><table><thead><tr>'+''.join('<th scope="col">'+esc(h)+'</th>' for h in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+str(c)+'</td>' for c in r)+'</tr>' for r in rows)+'</tbody></table></div>'
def links(items):return '<ul>'+''.join(f'<li><a href="{url}">{esc(label)}</a></li>' for url,label in items)+'</ul>'
PAGES=[
('case-study-library','BNB Accelerator case studies: browse all 32 published examples','Explore every published BNB case study and see which examples include deal-tracker fields, booking milestones and acquisition details.'),
('pro-forma-library','BNB Accelerator pro formas: deal numbers and missing assumptions','Review 25 company-published deal records, acquisition cost components and the evidence needed to turn summary numbers into a complete property pro forma.'),
('actual-results-vs-projections','BNB Accelerator results: actuals, reports and projections','Learn how to separate client reports, booking milestones, tracker figures and forward projections when reviewing BNB Accelerator results.'),
('cash-to-close-and-furnishing','BNB Accelerator deal costs: cash to close, furnishing and reserves','Examine acquisition cost components across the published tracker and identify the additional costs a complete STR purchase budget needs.'),
('cash-flow-and-return-evidence','BNB Accelerator cash flow and returns: how to verify the figures','Check reporting periods, operating expenses, debt service and invested cash before using a published STR return percentage.'),
('client-experience-and-review-sources','BNB Accelerator client experience: reviews and source checks','Use original public reviews, direct client stories and property records to assess the acquisition experience and ask better reference questions.'),
('acquisition-and-launch-evidence','BNB Accelerator acquisition and launch: what the case studies show','Review purchase, booking and launch evidence, then check which responsibilities belong to the buyer, acquisition team and independent vendors.'),
('due-diligence-checklist','BNB Accelerator review checklist: documents to request before joining','Compare the agreement, fees, property underwriting, launch plan and client references before committing to an acquisition service.')]
NAV=links([('/proformas/','Address-level property models and deal decisions'),('/reviews/','Public BNB Accelerator reviews')]+[(f'/reviews/{s}/',t) for s,t,d in PAGES])
DISC=paragraph('This library is published by BNB Accelerator about its own service. It organizes existing company-published examples and review sources; it is not an independent audit or a guarantee. Selected examples do not establish typical client results. Recorded financial fields may be forecasts or reports with unresolved definitions. Confirm the source, dates, expense coverage and cash denominator before relying on a figure.')
def case_table():
 return table(['Published example','Market / property','Available tracker records','Read next'],[(esc(r['name']),esc(r['market']+' / '+r['prop_type']),str(len(r['deals'])) if r['deals'] else 'No associated tracker fields',f'<a href="/case-studies/{r["slug"]}/">Read the full case study</a>') for r in CASES])
def deal_table():
 owners={d['id']:r['slug'] for r in CASES for d in r['deals']}
 return table(['Record','Market','Purchase-price field','Entry-total field','Component sum','Difference','Source case'],[(esc(d['id']),esc(d['market']),money(d['price']),money(d['entry']),money(d['down']+d['closing']+d['design']),money(d['down']+d['closing']+d['design']-d['entry']),f'<a href="/case-studies/{owners[d["id"]]}/">Source and limitations</a>') for d in DEALS])
def build_content(slug):
 if slug=='case-study-library':
  return section('All published case studies',paragraph(f'The current library contains {len(CASES)} selected examples. Use the original page for the client story, property facts and disclosures. The tracker-count column means financial fields are associated with the story; it does not mean those fields have been independently verified. Some stories include multiple acquisitions, so a property count is not a client count.')+case_table())+section('Choose the evidence that answers your question',paragraph('If you want to understand sourcing and closing, start with acquisition facts and who did each task. If you want to understand launch, distinguish listing readiness, future booked nights and completed stays. If you want to evaluate performance, request the same property’s dated revenue, expenses and debt-service records. A compelling story can explain the process while leaving a return unverified.')+links([('/reviews/pro-forma-library/','Inspect the associated deal numbers'),('/wins/','Browse published client win graphics'),('/testimonials/','See direct feedback and videos')]))+section('Why examples cannot establish your likely outcome',paragraph('The collection is selected by the company. The public library does not identify every purchaser, every unsuccessful search or the complete distribution of operating results. A beach home, a large mountain cabin and a portfolio purchase also have different budgets and seasonal patterns. Use the stories to ask better questions, then underwrite the actual property you are considering. Do not average the examples and call that an expected return.'))
 if slug=='pro-forma-library':
  return section('Published acquisition numbers for 25 records',paragraph('These are summary fields from the company-published deal tracker, not downloadable original signed property pro formas. A pro forma is a forward-looking model with assumptions; a tracker can mix acquisition facts and reported or projected financial fields. The table preserves the source entry total and separately sums its down-payment, closing and design fields. The difference is arithmetic, not a correction to the source.')+deal_table()+paragraph('<a href="/assets/review-evidence/deal-entry-fields.csv" download>Download all 25 acquisition records as CSV</a>. The CSV excludes cash-flow and return claims because their dates and definitions are unresolved.'))+section('What a complete property pro forma needs',paragraph('Specify the address or private deal identifier, model date, legal guest capacity, comparable properties and revenue period. Show available nights, expected occupied nights, average nightly rate, cleaning treatment and other income. Model platform charges, management, utilities, insurance, property taxes, HOA, repairs, replacements and debt service separately. Include launch delay, furnishing invoices, cash reserves and the cash investment basis. An annual net figure without those inputs cannot be independently reproduced.')+paragraph('Ask for base and downside cases using the same expense definitions. Identify which costs move with revenue and which continue when the calendar is empty. Show financing assumptions and whether a rate, insurance premium or permit is confirmed. Mark seller history, market estimates and buyer assumptions in separate columns. The goal is a model you can challenge before making an offer, not a percentage you have to accept.'))+section('Work an example without inventing a client forecast',paragraph('A purely hypothetical model assumes $100,000 of annual rental revenue, $45,000 of operating costs and $30,000 of debt service. Modeled cash flow is $25,000. If invested cash is $250,000, the modeled cash-on-cash ratio is 10%. If revenue falls to $80,000 and the assumed costs remain unchanged, modeled cash flow is $5,000 and the ratio is 2%. This is an arithmetic lesson, not a BNB client result; a real downside case must also adjust variable costs and document its assumptions.')+links([('/revenue-projections/','Learn the property underwriting method'),('/tools/str-revenue-calculator/','Build an illustrative revenue model')]))
 if slug=='actual-results-vs-projections':
  return section('Four kinds of evidence, four different questions',table(['Evidence','What it can help show','What it does not establish'],[('Closing / acquisition record','Price and recorded purchase structure','Future operating profitability'),('Client-reported milestone','What the client or company reported for a stated event','Audited receipts or typical outcomes'),('Tracker summary','Fields entered in a company record','Dates, complete expenses or actual-versus-projected status'),('Property pro forma','A forecast conditional on assumptions','Income already earned')]))+section('A booking milestone is not collected profit',paragraph('Ashley and Billy’s published story reports nearly 80 nights booked within 21 days of launch. The observation period describes how quickly bookings appeared; it is not a claim that 80 nights were stayed during those 21 days. Reservations can change, cancel or carry different payout dates. To evaluate collected revenue, use completed stays and payout records; to evaluate profit, include the costs for the same period.')+links([('/case-studies/ashley-billy-fort-walton-beach/','Read the booking milestone and financial limitations')]))+section('A peak month is not an annual forecast',paragraph('A seasonal property can produce a strong month and weak shoulder months. If the case story reports one month, preserve that period rather than multiplying the result by twelve. Compare every month’s available nights, stayed nights, rates and fixed costs. New ownership can also change debt service, insurance, management fees and tax assessments, so the buyer’s future economics may differ from the previous owner’s history.'))+section('Label your evidence before comparing properties',paragraph('Create a register with a document name, covered dates, source, actual-or-projected label and unresolved questions. Reconcile booking exports to payouts and deposits without counting cleaning charges twice. Reconcile expenses to invoices and statements. Tax illustrations belong in a separate analysis reviewed for the individual taxpayer; they do not turn an unverified operating forecast into cash received.')+links([('/guides/reading-str-case-study-results/','Read the case-study evidence guide'),('/reviews/cash-flow-and-return-evidence/','Check return definitions')]))
 if slug=='cash-to-close-and-furnishing':
  return section('The entry-total field is a starting point',paragraph('Down payment, closing costs and furnishing are three important components of a purchase budget. They do not automatically cover acquisition-service fees, inspection bills, travel, repairs, utility deposits, permit expenses, opening carry or retained cash reserves. Ask whether each charge is already included, separate, paid later or reimbursed. Avoid counting a financed cost as both a cash expense and a loan payment.')+deal_table())+section('A source discrepancy worth checking',paragraph('Ashley and Billy’s tracker fields list $63,000 down, $1,950 closing and $159,750 design. Those components total $224,700. The source entry-total field is $220,800, a $3,900 difference. The public summary does not explain that difference. A settlement statement and itemized project ledger are needed; neither the source total nor the component sum is presented here as a corrected all-in investment.')+links([('/case-studies/ashley-billy-fort-walton-beach/','Inspect the original evidence note')]))+section('Sequence the cash, not just the total',paragraph('Put earnest money, due-diligence bills, cash due at closing, vendor deposits, final furnishing payments and the first operating bills on their actual payment dates. Earnest money credited at closing should not be counted again as additional capital. A refund subject to contract conditions is not available cash until released. Keep operating reserves visible after closing so the model does not assume every remaining dollar can be spent on furnishings.'))+section('Compare like-for-like budgets',paragraph('A furnished acquisition may include inventory in the sale; an unfurnished property may need procurement, delivery, assembly, photography and replacements before opening. Clarify what the design field includes for each record. Obtain current quotes for your property and confirm ownership of inventory. A cheaper purchase can require a larger launch budget, and a large furnishing budget does not by itself prove that revenue will increase.')+links([('/tools/first-str-purchase-budget/','Build your purchase budget'),('/financing/closing-costs-and-reserves/','Review closing costs and reserves'),('/design/','Plan furnishing and launch work')]))
 if slug=='cash-flow-and-return-evidence':
  return section('Start with the period and definition',paragraph('Cash flow needs a reporting window and a definition. Ask whether it includes collected rental revenue, cleaning income and refunds; whether operating costs include management, maintenance and replacements; and whether debt service includes principal and interest. A property’s operating income before financing and an owner’s cash flow after financing answer different questions. Do not put them in the same comparison column.'))+section('Check the denominator before using a percentage',paragraph('Cash-on-cash return ordinarily compares a defined cash-flow amount with a defined cash-investment amount for the same analysis. The published tracker percentages do not consistently reconcile with the displayed entry-cost fields. Recomputing the fraction can identify a question, but it cannot establish which denominator was intended or whether the numerator was actually earned. Keep the source fields and request the investment ledger rather than presenting a replacement percentage as a verified client result.')+links([('/case-studies/adam-florida-panhandle/','See Adam’s unresolved return basis'),('/reviews/pro-forma-library/','Inspect the tracker’s acquisition fields')]))+section('A practical reconciliation sequence',paragraph('First obtain the property-level booking and payout records for the period. Match gross revenue, refunds, platform charges and net receipts, taking payout timing into account. Then match the operating costs and debt service to the same period. Finally reconcile cash invested, including the treatment of improvements, credits, reserves and later contributions. Note whether owner use or downtime reduced available nights. Each unresolved item should remain visible until a source document explains it.'))+section('Keep appreciation, tax and operating cash separate',paragraph('Appreciation is not operating cash and generally becomes spendable only through an exit or financing transaction. Debt principal paid down affects equity but is still a cash outflow when paid. A tax deduction is not the same as a dollar-for-dollar refund. Keeping these mechanisms separate makes it easier to judge whether a property can cover expenses during a weak season. An attractive combined benefit does not resolve an operating shortfall.')+links([('/reviews/actual-results-vs-projections/','Understand evidence labels'),('/deals/','Read company-published deal summaries')]))
 if slug=='client-experience-and-review-sources':
  return section('Read the original public reviews',paragraph('The existing public-review directory links the 27 posts recorded from Trustpilot on September 22, 2026. The platform’s current count and reviews may change. Read the original post and any company response before relying on an editorial summary. A star rating records a reviewer’s opinion; it does not independently verify property income, legal compliance or the service agreement.')+links([('/reviews/','Browse the dated review directory'),('https://www.trustpilot.com/review/mybnbaccelerator.com','Open the current Trustpilot profile')]))+section('Match the review to the stage of service',paragraph('A comment about a helpful conversation answers a different question from a client’s report after purchase and a full operating year. Look for the stage described, the work actually performed and any specific communication or handoff issue. Some brief public comments provide no purchase details. Do not assume that every positive rating represents a completed acquisition.'))+section('Include critical and mixed feedback in your questions',paragraph('The existing directory includes critical and mixed feedback, including questions about fees, transaction communication, tax/entity guidance and comparables. These are topics to examine through original posts, responses and your own documents; the directory does not adjudicate disputed claims. Ask for the fee schedule, representation boundaries, underwriting memo and responsibility matrix before signing. A useful answer identifies the contract clause or source record rather than asking you to rely on a testimonial.'))+section('Ask references questions you can compare',paragraph('Ask what service they purchased, when they closed, what work the team performed and what they arranged separately. Ask about the original budget, additional cash needs, communication frequency and what happened when a task slipped. For financial performance, ask what period the client can document and whether the records include all expenses and financing. Respect the client’s privacy and accept a redacted record rather than requesting personal tax returns.')+links([('/testimonials/','Direct client stories and video material'),('/reviews/case-study-library/','Property examples to pair with reviews'),('/reviews/due-diligence-checklist/','Turn review questions into a document checklist')]))
 if slug=='acquisition-and-launch-evidence':
  return section('Purchase, opening and operations are separate milestones',paragraph('A signed purchase contract, a completed closing, an opening-ready home and a listing with future bookings are different milestones. Each has a date, an owner and dependencies. Reviewing the sequence helps you understand the work delivered without inferring that a booked calendar proves annual profitability. The case studies are a starting point for asking how a particular purchase moved through those stages.'))+section('What the published library can help you examine',paragraph('The library includes acquisition descriptions, property facts and selected launch or booking reports. Where a tracker is associated, you can inspect recorded down-payment, closing and design fields. The public summaries do not consistently supply a complete dated project schedule. Request the planned handoff register for your purchase rather than assuming another client’s timeline applies to your property.')+links([('/reviews/case-study-library/','Browse every published example'),('/case-studies/ashley-billy-fort-walton-beach/','Read the reported launch-booking example')]))+section('Assign every launch deliverable',table(['Task','Evidence to request'],[('Property selection','Address-level underwriting and legal-use questions'),('Financing and closing','Named lender, contingencies and signed settlement records'),('Furnishing','Inventory, quotes, payment dates and acceptance criteria'),('Listing readiness','Permit/insurance status, photographs and approved listing'),('Operating handoff','Manager agreement, access, reservations and reporting cadence')]))+section('Check the distinction between coordination and delivery',paragraph('An introduction to a designer or manager is not the same as a signed project with budget authority, procurement responsibility and a completion date. Confirm which parties you hire directly, who pays them and who resolves delays. BNB’s public process describes acquisition coordination and independent-party introductions. The signed agreement for your engagement should govern what the team actually owes you.')+links([('/how-it-works/','Read the acquisition process'),('/management/','Review operating arrangements'),('/reviews/due-diligence-checklist/','Check documents before engaging')]))
 return section('Before you sign an engagement',paragraph('Obtain the actual agreement, legal contracting entity, service fee, payment triggers, refund or termination terms and scope exclusions. Identify who represents you in the real estate transaction and how each party is paid. Ask whether lender, designer, manager or other vendor choices involve referral compensation. The answers should be in documents you can keep, not just in a discovery call.'))+section('Before you approve a property',paragraph('Request an address-level revenue model, current comparables, complete cash budget and base/downside cases. Check municipal and HOA permission through appropriate current sources, not a generic market claim. Review insurance, physical diligence, financing conditions and the maximum offer supported by your assumptions. Record who owns each unresolved question and the deadline before any contingency expires.'))+section('Before you fund the launch',paragraph('Confirm furnishing inventory and vendor orders, delivery and assembly dates, permit and insurance readiness, listing assets, guest access and management responsibilities. Separate estimated costs from quotes and paid invoices. Maintain enough cash for launch delay and weak early bookings. Future reservations require their own transfer and payout review; they are not automatically the new owner’s collected income.'))+section('Before you rely on an outcome',paragraph('Use the original case page, source review and dated financial records for the same property and period. A tax illustration requires individual professional review and is not a client refund. If a return percentage has an unexplained basis, leave it unresolved. A company-selected library can illustrate possibilities and process; it cannot prove a typical outcome without a complete, consistently measured client dataset.')+links([('/reviews/','Read source-linked public feedback'),('/reviews/pro-forma-library/','Inspect the acquisition fields'),('/guides/str-service-responsibility-matrix/','Use the proposal responsibility matrix'),('/apply/','Discuss the documents for your purchase')]))
def patch(path,block):
 s=path.read_text();s=re.sub(re.escape(START)+r'.*?'+re.escape(END)+r'\n?','',s,flags=re.S)
 assert '</main>' in s,path
 s=s.replace('</main>',START+block+END+'\n</main>',1);path.write_text(s)
def main():
 assets=ROOT/'assets/review-evidence';assets.mkdir(exist_ok=True)
 with (assets/'deal-entry-fields.csv').open('w',newline='') as f:
  fields=['record_id','market','recorded_purchase_price','recorded_down_payment','recorded_closing_costs','recorded_design_costs','recorded_entry_total','component_sum','component_minus_entry_total','evidence_status','source_url']
  w=csv.writer(f);w.writerow(fields)
  for d in DEALS:w.writerow([d['id'],d['market'],d['price'],d['down'],d['closing'],d['design'],d['entry'],d['down']+d['closing']+d['design'],d['down']+d['closing']+d['design']-d['entry'],'Company-recorded fields; not independently verified complete costs',tpl.SITE+'/deals/'])
 for slug,title,desc in PAGES:
  path=f'/reviews/{slug}/'; url=tpl.SITE+path
  schema={'@context':'https://schema.org','@type':'Article','headline':title,'description':desc,'datePublished':DATE,'dateModified':DATE,'author':{'@type':'Organization','name':'BNB Accelerator'},'mainEntityOfPage':url}
  body='<main id="main-content"><section class="page-hero"><div class="container narrow"><p class="eyebrow">BNB Accelerator review evidence</p><h1>'+esc(title)+'</h1><p>'+esc(desc)+'</p><p>Published October 8, 2026 · Company evidence review</p></div></section>'+build_content(slug)+section('Sources and evidence limits',DISC+links([('/case-studies/','Company-published case studies'),('/deals/','Company-published tracker'),('/reviews/','Dated public-review source directory')]))+section('Explore the review evidence library',NAV)+section('Review your own purchase',paragraph('Bring your budget, candidate property and questions about the work you need delivered. Ask for the current scope and supporting records before deciding.')+links([('/apply/','Discuss your STR purchase')]))+'</main>'
  dest=ROOT/path.strip('/')/'index.html';dest.parent.mkdir(parents=True,exist_ok=True)
  dest.write_text(tpl.page(title=title,description=desc,path=path,body=body,extra_schema='<script type="application/ld+json">'+json.dumps(schema)+'</script>',body_class='blog'))
 patch(ROOT/'reviews/index.html',section('Case studies, deal numbers and pro forma evidence',paragraph(f'Explore all {len(CASES)} published case studies and {len(DEALS)} tracker records. These companion pages explain the numbers and the evidence behind them; the public reviews above remain a separate source of customer opinion.')+NAV))
 for r in CASES:
  ds=r['deals'];text=paragraph('Use this example alongside the complete review library. The company-published story and tracker fields are selected evidence, not independent verification of typical results. A forecast needs its own assumptions and dates; a realized result needs records for the same period.')
  if ds:
   text+=table(['Associated record','Listed entry total','Down + closing + design','Difference'],[(esc(d['id']),money(d['entry']),money(d['down']+d['closing']+d['design']),money(d['down']+d['closing']+d['design']-d['entry'])) for d in ds])
   text+=paragraph('The difference column checks only the three displayed acquisition components. A zero difference does not prove that every launch cost, service fee or reserve is included. A nonzero difference needs an itemized reconciliation; it is not automatically an error or a corrected investment amount.')
  else:text+=paragraph('No associated deal-tracker record is published for this example in the current library. Do not fill missing revenue, expenses or invested cash with another client’s numbers. Ask for a property-specific model and, where performance is reported, its supporting records.')
  text+=links([('/reviews/case-study-library/','Browse all case studies'),('/reviews/pro-forma-library/','Inspect deal and pro forma evidence'),('/reviews/actual-results-vs-projections/','Understand reports versus forecasts'),('/reviews/','Read public client reviews')])
  patch(ROOT/f'case-studies/{r["slug"]}/index.html',section('Review evidence and acquisition cost reconciliation',text))
 for path in ['case-studies','deals','wins','testimonials']:
  patch(ROOT/path/'index.html',section('Explore BNB Accelerator review evidence',paragraph('Connect the published stories and result graphics with the source-linked reviews and acquisition-number checks. Use the complete case library to find each example; use the pro forma guide to identify what a forward model still needs.')+NAV))
 # Scoped sitemap edits preserve every existing entry and date outside this library.
 ns='http://www.sitemaps.org/schemas/sitemap/0.9';ET.register_namespace('',ns)
 site=ROOT/'sitemap-proof.xml';tree=ET.parse(site);root=tree.getroot();existing={x.find('{'+ns+'}loc').text:x for x in root}
 for path in ['/reviews/']+[f'/reviews/{s}/' for s,t,d in PAGES]+[f'/case-studies/{r["slug"]}/' for r in CASES]+['/case-studies/','/wins/','/testimonials/']:
  url=tpl.SITE+path
  node=existing.get(url)
  if node is None:node=ET.SubElement(root,'{'+ns+'}url');ET.SubElement(node,'{'+ns+'}loc').text=url
  last=node.find('{'+ns+'}lastmod')
  if last is None:last=ET.SubElement(node,'{'+ns+'}lastmod')
  last.text=DATE
 for node in list(root):
  if node.find('{'+ns+'}loc').text == tpl.SITE+'/deals/': root.remove(node)
 tree.write(site,encoding='utf-8',xml_declaration=True)
 core=ROOT/'sitemap-core.xml';cs=core.read_text()
 pattern=r'(<(?:\w+:)?url>\s*<(?:\w+:)?loc>https://www\.bnbaccelerator\.com/deals/</(?:\w+:)?loc>\s*<(?:\w+:)?lastmod>)[^<]+(</(?:\w+:)?lastmod>)'
 cs,n=re.subn(pattern,lambda m:m[1]+DATE+m[2],cs)
 assert n==1,'deals sitemap owner missing'
 core.write_text(cs)
 print(f'Review library: {len(PAGES)} new pages; {len(CASES)} case-study evidence blocks; {len(DEALS)} CSV records')
if __name__=='__main__':main()
