"""Expand existing seller1099 note; Airbnb414 and IRS sources checked October6.
Distinct intent: account/form scope versus the acquired property's evidence.
Uses the existing scoped content workflow, never older volume generators.
"""
from expand_reservations_closing import main

BODY = '''<p class="lead">A seller's Form 1099-K is supporting evidence, not a property-level profit statement. Before buying an STR, reconcile what the form covers, which listing earned the reported amounts and how those amounts relate to the seller's receipts. An account-level total can be correct while the revenue claimed for the home you are buying remains unsupported. Do not pay an income premium simply because the seller supplies a tax document.</p>
<p><a href="/apply/">Review the seller's income-evidence packet on an STR acquisition call</a> before committing to the offer. Your accountant should review the reporting bridge; purchase underwriting also needs property-specific records, costs and a separate buyer case.</p>
<h2>Start with the form's scope, not the bank total</h2>
<p>The <a href="https://www.irs.gov/businesses/what-to-do-with-form-1099-k" rel="noopener">IRS explains that Form 1099-K reports gross payment amounts</a> without adjustments for items such as fees, credits and refunds. It directs recipients to use other records to check amounts and contact the issuer or payment settlement entity about incorrect information. For an acquisition, that makes the form a cross-check, not a replacement for listing records. Have a CPA determine tax treatment; this guide does not prescribe deductions or filing entries.</p>
<p><a href="https://www.airbnb.com/help/article/414" rel="noopener">Airbnb's US tax-document guidance</a> distinguishes listing-owner gross reporting from co-host payouts and describes account and payout-method reporting scope. Its reconciliation instructions identify gross reportable columns and warn that certain itemized charges are already included. Airbnb-collected and remitted occupancy taxes are excluded from its Gross Amount. Map the actual report definition rather than subtracting every tax or adding every displayed column. Do not generalize those definitions to another platform.</p>
<p>Ask which taxpayer, account, payment types and reporting year the document represents. Compare that scope with the exact property, listing identifiers and dates in the seller's claim. Check whether other listings, experiences, services or payment types appear in the records. A calendar-year tax form and a trailing twelve-month sales presentation are different periods unless the dates actually match.</p>
<h2>Build a document-scope register</h2>
<p>Request records from the authorized seller or manager through a secure channel. Redact full taxpayer identifiers, guest names and unrelated financial activity while retaining enough information for an authorized reviewer to reconcile amounts and scope. Do not request account passwords or publish tax forms. If identifiers or taxpayer assignments need review, have the appropriately authorized accountant handle them privately.</p>
<div class="table-scroll"><table><thead><tr><th>Record</th><th>Scope to establish</th><th>Buyer question</th></tr></thead><tbody>
<tr><td>Information return and any correction</td><td>Issuer, document type, account/payee reference and reporting year</td><td>Is this the relevant gross report or another payment type, taxpayer or period?</td></tr>
<tr><td>Account-level annual report</td><td>Actual gross definition, currency, included listings and adjustments</td><td>Does the report reconcile to the form without duplicating itemized amounts?</td></tr>
<tr><td>Subject-listing export</td><td>Exact listing/property, same dates and consistent reporting basis</td><td>What part of the account total is actually supported for this property?</td></tr>
<tr><td>Fees, refunds and co-host/manager records</td><td>Relevant transactions and whether amounts are already deducted or included</td><td>Can the reviewer explain the gross-to-owner bridge without counting money twice?</td></tr>
<tr><td>Bank or manager remittances</td><td>Authorized property receipts and payment timing</td><td>Which differences are explained and which remain unsupported?</td></tr>
<tr><td>Missing-channel evidence and deadline</td><td>Named record, responsible provider and actual purchase review date</td><td>What evidence could change the supported income case before protection changes?</td></tr>
</tbody></table></div>
<p>The <a href="/blog/reconcile-airbnb-payout-export/">property payout-reconciliation guide</a> provides the detailed charges-to-deposits and timing worksheet. Use it after defining scope. Keep gross reporting, net remittances and future reservations separate; summing those figures creates a larger number, not stronger income evidence.</p>
<h2>Worked purchase example: a valid account total is not the home's income</h2>
<p>Hypothetical allocation only: assume the seller's account-level form reports $240,000 of gross transactions for a completed year. Records prepared on the same documented reporting basis identify $160,000 from other listings and $80,000 from the subject property. The two components reconcile: $160,000 + $80,000 = $240,000. That supports the allocation under the stated assumptions; it does not make $240,000 the purchased home's revenue.</p>
<p>Now suppose the seller's sales presentation claims $110,000 for this property and period. The scoped record supports $80,000, leaving $30,000 of the claim unexplained by this evidence. It does not prove fraud or that other legitimate receipts do not exist. Ask for a documented bridge: another channel's property-specific completed receipts, a reporting-basis difference, or a correction supported by the issuer and underlying transactions.</p>
<p>If the missing amount is only next year's projection, keep it outside historical revenue. If it belongs to another property, exclude it. If it is a manager remittance already derived from the same gross transactions, do not add it again. Until a genuine additional source is reconciled, test the purchase with the substantiated amount rather than converting the seller's unexplained difference into booked income.</p>
<p>These invented amounts are not accommodation revenue, net operating income or buyer cash flow without further classification. Cleaning charges, pass-through items, refunds, actual operating costs, debt and reserves still need review. Do not derive an offer price or lender DSCR from this gross allocation alone. A CPA's form reconciliation also does not establish the buyer's financing, permit or future return.</p>
<h2>Handle missing, corrected and overlapping records explicitly</h2>
<p>An absent form does not establish zero income. Ask for other reliable property-level evidence and have the seller's accountant explain the reporting circumstances. Conversely, several forms do not necessarily represent separate income streams that can all be added. Identify the relevant accounts, payment types and any original/corrected pairs before making an acquisition total.</p>
<p>If a supplied form changes, retain the dated correction trail with the authorized review packet and reconcile the affected transactions. Do not replace a difference with a plug entry merely to force a match. Keep a clear list of explained scope differences, explained timing differences and unresolved amounts. The seller's future correction request is not present proof of the missing property income.</p>
<p>Record what each party actually owes to provide under the signed purchase documents; counsel should identify deadlines and available remedies. Neither this checklist nor a pending accountant response creates an automatic right to extend, cancel or recover a deposit. A seller can protect privacy while still supplying a properly redacted, reviewable property packet.</p>
<h2>Choose what income deserves credit in the offer</h2>
<p>Proceed when the property's supported history, complete costs and independently verified buyer permissions and financing justify the price. Renegotiate when the purchase remains viable on a lower substantiated income case. Seek a protected delay only when a specific decision-changing record can arrive within an acceptable review plan. Reject the unsupported income premium when the deal depends on amounts that cannot be allocated and reconciled to the purchased property.</p>
<p>Use the <a href="/blog/seller-proforma-vs-trailing-revenue/">seller projection-versus-history guide</a> for supported future improvement and the <a href="/blog/str-maximum-offer-price-from-revenue/">maximum-offer framework</a> for actual financing and costs. This page's account-scope test does not replace either. For <a href="/blog/buy-str-high-income-large-tax-bill/">buyers with substantial capital or a large tax bill</a>, liquidity and hoped-for deductions are not substitutes for verified property economics.</p>
<p><a href="/apply/">Bring the scoped income register to BNB Accelerator to compare acquisition candidates</a>. Include the seller claim, supported property amount, unexplained difference, missing evidence and actual decision deadline. BNB Accelerator assists within its contracted acquisition scope; independent accountants, lenders and counsel determine their respective conclusions.</p>
<p class="small">Primary sources reviewed October 6, 2026. Educational information only, not personalized tax, investment, lending or legal advice. Examples are hypothetical. No revenue, permit, financing, tax benefit, booking or investment result is guaranteed.</p>'''

if __name__ == '__main__':
    main(slug='str-1099-payout-reconciliation',
         title='Verify Seller STR 1099 Income Before Buying | BNB Accelerator',
         h1='How Do You Reconcile STR 1099 Amounts to Platform Payouts?',
         description='Before buying an STR, check whether seller 1099 gross belongs to this property. Use a scope register and worked allocation before pricing claimed income.',
         body=BODY, search_terms='seller 1099 property account scope gross allocation income evidence acquisition',
         hub_attribute='data-seller-1099-scope-link',
         hub_block='<p data-seller-1099-scope-link>Given a seller tax document? Use the <a href="/blog/str-1099-payout-reconciliation/">1099 property-scope register and allocation example</a> before crediting an account-level total to the home you are considering.</p>')
