"""Scoped existing acquisition-note expansion; never generate the homepage."""
import json,re
import expand_hold_period as page
page.SLUG='rate-buydown-str-investment'
page.TITLE='Mortgage Rate Buydown for an STR: Cash Worksheet'
page.H1='Is a Mortgage Rate Buydown Worth It on an STR?'
page.DESC='Before buying an STR, compare mortgage points, closing cash and early payoff. Use a quote register and break-even worksheet without assuming a refinance.'
page.FAQ=[
('Are permanent points and a temporary buydown the same?', 'No. Points purchase a lower loan rate under the actual quote; a temporary arrangement funds a limited payment reduction. Verify eligibility, note terms, funding and the full payment separately.'),
('Does a 48-month break-even mean points are automatically worthwhile?', 'No. That simple cash screen omits time value, tax treatment, balance differences and other costs. Test early payoff and whether closing cash still preserves launch and household liquidity.'),
('Can an investment STR use a Fannie Mae temporary buydown?', 'The current cited Fannie Mae guide lists investor properties as ineligible for its temporary plans. Do not change the stated occupancy to obtain an unsuitable loan; ask the actual lender about a truthful use-appropriate product.'),
('Should an expected refinance fund the decision?', 'No. Refinance availability, costs and timing require separate approval. Compare keeping the existing loan and ending it early without assuming a future loan or refund.')]
page.BODY='''<p class="lead">A mortgage rate buydown is worth considering for an STR purchase only when the actual financing permits it, the upfront cash fits the launch budget and the supported loan-life comparison works. A lower quoted rate is not automatically the better acquisition. Compare permanent discount points with a no-point option, then separately examine any proposed temporary payment subsidy. Buyers acquiring within zero to six months need dated quotes and funded bills, not an assumed refinance.</p>
<p><a href="/apply/">Bring both lender quotes and the STR purchase cash plan to an acquisition call</a>. This worksheet preserves the original note's $12,000/$250/48-month cash screen and makes its limits explicit. It does not publish current rates or promise savings, loan approval or tax results.</p>
<h2>Identify what the proposed buydown actually changes</h2>
<p>The <a href="https://www.consumerfinance.gov/ask-cfpb/how-should-i-use-lender-credits-and-points-also-called-discount-points-en-136/">CFPB points-and-lender-credits explanation</a> distinguishes paying more upfront for a lower rate from accepting a higher rate for lower closing costs. One discount point equals one percent of loan amount; the rate change depends on the actual lender and product. Its consumer explanation is a comparison framework, not confirmation that your business-purpose STR loan has the same disclosures or terms.</p>
<p>Ask the lender which charges buy a lower rate and which are other origination fees. Request a comparable quote without points and identify any credit attached to the rate. A seller-funded amount, lender credit and buyer-paid points are different cash sources. Confirm permitted classification and use; do not count an approved closing credit again as a furnishing deposit. The <a href="/blog/str-seller-credit-vs-price-reduction/">seller credit versus price reduction guide</a> addresses the separate offer choice.</p>
<p>A temporary buydown does not mean a permanently lower note payment. <a href="https://selling-guide.fanniemae.com/sel/b2-1.4-04/temporary-interest-rate-buydowns">Fannie Mae's temporary-buydown guide</a> lists investor properties as ineligible and requires qualification at the note rate for its eligible transactions. These are that program's rules, not every portfolio or DSCR product. Verify truthful intended use, actual eligibility and written terms rather than describing an investment property as a second home to obtain an advertised incentive.</p>
<h2>Keep a same-loan quote register</h2>
<div class="table-wrap"><table><thead><tr><th>Comparison row</th><th>Evidence to obtain</th><th>Decision check</th></tr></thead><tbody>
<tr><td>Loan and intended use</td><td>Same loan amount, term, amortization and occupancy/use</td><td>Do not attribute different leverage to points</td></tr>
<tr><td>Quote date and commitment</td><td>Rate, lock period, expiration and conditions</td><td>Compare available offers, not an old rate</td></tr>
<tr><td>Incremental upfront cost</td><td>Points plus changed cash-paid fees minus accepted credits</td><td>Count the actual difference once</td></tr>
<tr><td>Payment</td><td>Principal/interest and separately quoted tax/insurance</td><td>Isolate the rate-related difference</td></tr>
<tr><td>Early payoff</td><td>Balance schedules, charges and applicable restrictions</td><td>Recalculate at possible loan end dates</td></tr>
<tr><td>Launch liquidity</td><td>Cash to close, setup invoices and retained reserve</td><td>Monthly savings cannot pay today's invoice</td></tr>
</tbody></table></div>
<p>Reconcile approved concessions and property-value changes before deciding. The <a href="/blog/appraisal-gap-furnished-str/">appraisal-gap worksheet</a> covers revised loan proceeds. Ask for updated complete terms if the lender changes loan size, fees or lock cost. A rate comparison made on a different amount is not a clean points decision.</p>
<h2>Worked permanent-points screen and early-payoff case</h2>
<p>Original hypothetical arithmetic, not lender pricing or a client result. Assume two otherwise matched approved fixed-payment quotes differ by $12,000 of buyer-paid upfront points and $250 of monthly principal-and-interest payment. Assume no additional fee or credit difference in this simplified screen. The lower-payment option requires the entire extra $12,000 at closing. It is not a retained reserve or a monthly expense charged again.</p>
<div class="table-wrap"><table><thead><tr><th>Illustrative loan duration</th><th>Cumulative payment reduction</th><th>Reduction minus upfront points</th></tr></thead><tbody>
<tr><td>24 months</td><td>24 × $250 = $6,000</td><td>−$6,000</td></tr>
<tr><td>48 months</td><td>48 × $250 = $12,000</td><td>$0</td></tr>
<tr><td>60 months</td><td>60 × $250 = $15,000</td><td>$3,000</td></tr>
</tbody></table></div>
<p>Simple cash break-even is $12,000 divided by $250, or 48 months. These figures compare payment outflows only; they are not total investment return or full mortgage economics. Different remaining principal balances, time value, tax treatment, prepayment charges and any other changed costs are omitted. Obtain lender amortization/payoff schedules and adviser review for a complete comparison. Do not invent a probability of refinancing to make an expected-value result.</p>
<p>At an assumed 24-month sale or refinance, only $6,000 of the points cost has been matched by payment reductions in this screen. The property's ownership period and this loan's duration can differ. A ten-year property hold does not prove the buyer keeps this loan ten years. Conversely, hoping rates fall next year does not establish that refinancing is available or worthwhile. Compare an early end and continued original-loan case; include actual new-loan costs in a separate refinance decision.</p>
<h2>Test closing liquidity before valuing distant savings</h2>
<p>Independent invented acquisition budget: $240,000 available, $145,000 buyer equity, $15,000 other cash-paid closing costs, $35,000 distinct required setup and $30,000 retained operating cash. The no-point plan allocates $225,000, leaving $15,000 outside the plan. Adding the separate $12,000 points cost allocates $237,000 and leaves $3,000. This does not spend the reserve or treat it as an operating expense.</p>
<p>Suppose a verified change adds $8,000 of required opening work not already in setup. The no-point allocation becomes $233,000, leaving $7,000; the points allocation becomes $245,000, a $5,000 shortfall while preserving the stated reserve. Future $250 monthly payment reductions do not fund an invoice due at closing. Reprice, fund a revised approved plan or decline the points; do not label a consumed reserve intact. Use the <a href="/tools/first-str-purchase-budget/">complete purchase budget</a> and keep household/business liquidity separate.</p>
<p>If a different eligible lender product offers a temporary subsidy, first obtain its written funding, payment schedule and disposition terms. Underwrite the full payment after it ends and a case where expected assistance is unavailable. Ask who controls unused funds on early payoff; do not assume they are refundable buyer cash. This is a question register, not an assertion that an investment STR can obtain that plan.</p>
<h2>Choose the funded acquisition rather than the lowest rate</h2>
<p>Proceed when actual use-appropriate quotes, likely loan duration and complete early cash support the choice. Renegotiate a permitted contribution or rate structure when it improves the documented model. Delay within valid protections for missing loan or cash evidence. Reject points that require unavailable reserves, a promised refinance, invented tax savings or an unsupported booking forecast.</p>
<p><a href="/apply/">Compare the STR candidate with both complete financing cases</a>. BNB Accelerator assists within its contracted acquisition scope; independent lenders and advisers determine eligibility, legal and tax conclusions. Primary sources checked October7,2026; CFPB page displays an October2023 review, Fannie Mae topic August2024. These are currently published pages, not newly issued2026 guidance. Educational information only, not personalized lending, legal, tax or investment advice. All figures hypothetical; no rate, financing, refund, refinance or investment result guaranteed.</p>'''
if __name__=='__main__':
 page.main('2026-09-23','data-rate-buydown-review-link','Compare the <a href="/blog/rate-buydown-str-investment/">points quote register, early-payoff screen and launch-liquidity worksheet</a> before choosing the lowest advertised mortgage rate.')
 p=page.ROOT/'blog'/page.SLUG/'index.html';s=p.read_text()
 s=re.sub(r'<span>Updated [^<]+</span>','<span>Updated October 7, 2026</span>',s,count=1)
 if '"@type": "FAQPage"' not in s:
  d={'@context':'https://schema.org','@type':'FAQPage','mainEntity':[{'@type':'Question','name':q,'acceptedAnswer':{'@type':'Answer','text':a}} for q,a in page.FAQ]}
  s=s.replace('</head>','<script type="application/ld+json">'+json.dumps(d)+'</script>\n</head>',1)
 p.write_text(s)
