"""Furnished acquisition appraisal-gap cash decision; no new route."""
from expand_reservations_closing import main

BODY='''<p class="lead">Cover an appraisal gap on a furnished STR only when the revised loan, total cash and independently supported purchase economics still work. Included furniture can reduce actual setup spending; it does not automatically increase the lender's real-estate value or justify a seller premium. Before waiving protection or adding cash, separate the appraisal shortfall, lender funding reduction and usable assets you will actually receive.</p>
<p><a href="/apply/">Book an STR acquisition call to compare an appraisal-gap purchase with a lower offer or another property</a>.</p>
<h2>Calculate the lender funding change, not just the headline gap</h2>
<p>Ask your lender for the accepted appraised value, maximum available loan, any purchase-price adjustments and the resulting cash to close. Obtain the answer for the actual product and transaction, including concessions and non-realty items. Do not infer a new approval from an earlier percentage quote. Income, credit, reserves or another underwriting constraint can limit the loan further.</p>
<p><a href="https://selling-guide.fanniemae.com/sel/b2-1.2-01/loan-value-ltv-ratios" rel="noopener">Fannie Mae's purchase LTV guidance</a> generally uses the lower of sales price and current appraised value, with specific exceptions. This is a reference for applicable Fannie Mae loans, not a universal DSCR rule or required investment-property down payment. Confirm your lender's own valuation basis before using it in a worksheet.</p>
<p>The <a href="/blog/str-appraisal-income-approach/">appraisal-income approach note</a> asks which valuation evidence the lender accepts. This guide addresses the next decision: whether to fund a documented shortfall, renegotiate or leave the purchase. A projected Airbnb-income report is not a commitment to lend against that forecast.</p>
<h2>Test a furnished-purchase cash waterfall</h2>
<p>Hypothetical only, not a current loan quote, appraisal or client transaction. Assume a $650,000 agreed package price and an initial expected value of $650,000. For this example the lender confirms a 75% loan limit on the lower accepted real-estate purchase value or appraisal, with no further price adjustments or other constraint. The actual appraisal is $600,000. The package treatment is assumed accepted for this calculation; actual furniture and concession treatment may produce a different basis.</p>
<div class="table-wrap"><table><thead><tr><th>Same price, changed accepted value</th><th>Initial assumption</th><th>Actual appraisal scenario</th></tr></thead><tbody>
<tr><td>Package price paid</td><td>$650,000</td><td>$650,000</td></tr>
<tr><td>Accepted value used in this example</td><td>$650,000</td><td>$600,000</td></tr>
<tr><td>Maximum loan at assumed 75%</td><td>$487,500</td><td>$450,000</td></tr>
<tr><td>Buyer cash toward package price</td><td>$162,500</td><td>$200,000</td></tr>
<tr><td>Other cash-paid closing costs</td><td>$15,000</td><td>$15,000</td></tr>
<tr><td>Remaining setup and launch spending</td><td>$25,000</td><td>$25,000</td></tr>
<tr><td>Separately retained reserves</td><td>$30,000</td><td>$30,000</td></tr>
<tr><td>Total cash committed through launch/reserves</td><td>$232,500</td><td>$270,000</td></tr>
</tbody></table></div>
<p>The price-to-appraisal difference is $50,000, but additional cash versus the initial financing assumption is $37,500: 75% of that difference. It is not a $50,000 cash increase on top of the original down payment. With $250,000 designated cash, the revised plan falls short by $20,000. The reserve is retained liquidity, not an expense deducted again from projected annual operating cash flow.</p>
<p>If the seller agrees to $620,000 and the lender still accepts $600,000 as the limiting value with a $450,000 loan, buyer price cash becomes $170,000. Keeping the other hypothetical amounts unchanged produces $240,000 total committed cash, leaving $10,000 unallocated. That clears only this invented cash limit; it does not establish fair value, lawful rental use, lender approval or adequate downside protection.</p>
<p>Even a successful value review to $625,000 would not automatically solve this example at the original price: a 75% loan is $468,750, price cash is $181,250 and total committed cash is $251,250. That remains $1,250 over the assumed cash budget. Update actual points, closing charges, lock costs and loan terms rather than holding them constant when they change.</p>
<h2>Credit furniture once, after condition and delivery are verified</h2>
<p>Request an itemized inventory showing what stays, ownership, condition, exclusions, delivery at possession and any replacement needed. Obtain a condition-based used-value estimate and a separate cost-to-complete setup budget. A seller's original retail invoices do not establish today's usable value. Let counsel and the closing agent document agreed personal-property terms; do not invent allocations to make the lender's ratio work.</p>
<p><a href="https://selling-guide.fanniemae.com/sel/b4-1.1-05/disclosure-information-appraisers" rel="noopener">Fannie Mae's appraiser-disclosure guidance</a> includes the complete ratified contract/addenda, financing information, concessions and non-realty items. Disclose the actual arrangement to the lender and follow its applicable requirements. Moving furniture onto a bill of sale does not automatically preserve the same loan amount or make a side agreement acceptable.</p>
<p>In the example, suppose furnishing and readiness would cost $43,000 without included usable items. Verified items avoid $18,000 of actual planned purchases, leaving the modeled $25,000. That savings is already reflected in the cash table. Do not subtract $18,000 again as an appraisal-gap credit or add it as cash available for closing. Avoided spending is not sale proceeds and does not by itself validate paying above appraised real-estate value.</p>
<p>Likewise, do not assume permits, reviews or future bookings are transferable assets. Investigate legal rental use independently and use the <a href="/blog/future-booking-calendar-value/">calendar-premium comparison</a> for documented future benefits rather than counting gross bookings as value. A turnkey label cannot resolve missing lender or transaction evidence.</p>
<h2>Review evidence and purchase protections before choosing an outcome</h2>
<p>Check the appraisal for documented factual errors, missing relevant property information and questions about comparable sales or the actual contract. Send a specific evidence packet through the lender's permitted review process. Ask for timing, scope and any fees; a reconsideration is not a guaranteed value increase or an extension of the purchase contract. Do not pressure an appraiser to hit the offer price.</p>
<p>Have your transaction professional explain the actual appraisal contingency, financing contingency, gap commitment, notice deadline and remedies before signing or waiving anything. There is no universal right to terminate, recover a deposit or compel a seller reduction. If closing or a rate lock moves, recalculate cash and launch timing, not just the loan ratio.</p>
<ul><li><strong>Proceed:</strong> the lender's revised commitment is confirmed, the total cash schedule preserves required liquidity and the investment case supports the actual price without unsupported premiums.</li>
<li><strong>Renegotiate:</strong> request a supported price adjustment or another lender-approved structure, then rerun the cash and return tests.</li>
<li><strong>Delay:</strong> decisive factual review or funding evidence is outstanding and a valid contract extension protects the timeline.</li>
<li><strong>Reject:</strong> closing would consume unavailable reserves or the purchase depends on undisclosed furniture terms, unapproved financing or unsupported income value.</li></ul>
<p>Before deciding, update the <a href="/blog/str-maximum-offer-price-from-revenue/">maximum-offer worksheet</a> with the new loan and total buyer capital. A smaller loan may lower payments while the larger equity commitment can change cash-on-cash return; neither effect alone proves the purchase improved. <a href="/apply/">Book a call to compare this furnished STR's supported price, appraisal-gap cash and clean-launch alternatives</a>.</p>
<p class="small">Primary sources checked October 6, 2026. Educational information, not appraisal, lending, legal, tax or personalized investment advice. Examples are hypothetical. Consult your lender and qualified advisers. No value increase, financing approval, transferable booking, tax benefit or investment result is guaranteed.</p>'''

if __name__=='__main__':
    main(slug='appraisal-gap-furnished-str',title='Furnished STR Appraisal Gap: Buyer Cash and Offer Worksheet',h1='Should you cover an appraisal gap when buying a furnished STR?',description='Test a furnished STR appraisal gap with lender funding, buyer cash, verified furniture savings and price alternatives before waiving purchase protections.',body=BODY,search_terms='appraisal gap funding shortfall furnished purchase',hub_attribute='data-furnished-appraisal-gap-link',hub_block='<p data-furnished-appraisal-gap-link>Did an appraisal come in below your furnished STR offer? Use the <a href="/blog/appraisal-gap-furnished-str/">appraisal-gap cash waterfall and price alternatives</a> before committing additional capital or waiving purchase protection.</p>')
