"""Expand the existing gift-funds acquisition guide, not a new lending intent."""
import html,json,re
from pathlib import Path
from expand_reservations_closing import main
SLUG='gift-funds-str-down-payment'
BODY='''<p class="lead">Family money can make your bank balance larger without making your STR purchase financeable. Before relying on a gift, identify the actual investment-property loan, obtain its source-of-funds decision and test the entire closing-to-launch budget without an unapproved transfer. A high salary, substantial family wealth or a hoped-for tax benefit does not replace an eligible down payment and funded reserves.</p>
<p><a href="/apply/">Book an acquisition call to review your funding plan before making an STR offer</a>. Bring the lender's program identification and a cash-use schedule; share donor and bank records only through secure, authorized channels.</p>
<h2>Start with occupancy and the exact loan program</h2>
<p><a href="https://selling-guide.fanniemae.com/sel/b3-4.3-04/personal-gifts" rel="noopener">Fannie Mae's Personal Gifts guidance</a>, dated February 4, 2026, excludes gifts for investment properties. Its permitted principal-residence and second-home transactions have separate donor, contribution and documentation conditions. That is a specific program rule, not proof every DSCR, portfolio or other lender accepts or rejects gifts. Obtain the applicable investment program's written requirements before treating family funds as eligible.</p>
<p>Describe your planned use truthfully. Do not label a rental investment a second home or principal residence to obtain a funding exception. The <a href="/blog/second-home-loan-rental-intent/">second-home versus investment-loan guide</a> addresses that distinct occupancy decision. A broker's general statement that family gifts are common in home purchases does not establish eligibility for your property, borrower and product.</p>
<h2>Keep three decisions separate</h2>
<p>First, is the proposed transfer genuinely a gift, a repayable loan or an ownership contribution? Record any repayment, interest, profit share, collateral or control arrangement and disclose it to the lender and your advisers. Calling an obligation a gift does not remove it. A family member who expects equity is not merely a donor; the <a href="/blog/cosigner-co-borrower-buy-str/">co-borrower guide</a> and <a href="/blog/str-partnership-structure/">partner purchase guide</a> address separate borrower and ownership responsibilities.</p>
<p>Second, does the specific lender accept that actual source for the intended use? Ask separately about down payment, closing costs, required borrower contribution and reserves. Third, will eligible cash be documented and available by the contract's funding deadline? An acceptable source that arrives too late cannot fund a wire already due. Approval of the source is also not final approval of income, collateral, STR use or the complete loan.</p>
<h2>Build a source-of-funds decision ledger</h2>
<p>Use one row per proposed source rather than one total bank balance. Track amount, actual nature, approved use, missing evidence, responsible person and deadline. Ask the lender to resolve ambiguities before sending earnest money that depends on these funds.</p>
<div class="table-scroll"><table><thead><tr><th>Question</th><th>Evidence to obtain</th><th>Do not assume</th></tr></thead><tbody>
<tr><td>Which rules apply?</td><td>Named lender/product, occupancy, borrower and dated program response</td><td>A primary-home gift rule applies to an investment purchase</td></tr>
<tr><td>What does the family expect?</td><td>Accurate gift, debt or equity terms reviewed by advisers</td><td>A signed gift letter cures an undisclosed repayment agreement</td></tr>
<tr><td>Which cash uses are accepted?</td><td>Written treatment of contribution, closing and reserve requirements</td><td>Eligibility for one use means eligibility for every use</td></tr>
<tr><td>What tracing is needed?</td><td>Required donor/source records and documented transfer route</td><td>Moving money between accounts removes its source history</td></tr>
<tr><td>When will it be usable?</td><td>Documentation cutoff, transfer instructions and cleared-funds confirmation</td><td>A verbal promise or pending transfer is available closing cash</td></tr>
</tbody></table></div>
<p>Where Fannie Mae personal gifts are permitted, its documentation includes a donor-signed letter identifying amount, donor details and relationship, and confirming no expected repayment; it also requires evidence of donor availability and transfer. These documents do not override its investment-property prohibition. For a different product, obtain that lender's actual evidence requirements rather than presenting this list as its universal checklist.</p>
<p>Do not obscure origins through account shuffling, artificial seasoning or a false letter. If money has already moved, disclose the history and ask what documentation and permitted resolution are needed. Verify closing wire instructions independently with the closing professional using an established contact method. Keep account identifiers and donor financial information out of public worksheets.</p>
<h2>Worked hypothetical: closing is not the full capital budget</h2>
<p>All figures below are invented, not a loan quote, lending limit or client result. Assume a $700,000 purchase with a $525,000 loan, $225,000 of the buyer's own documented cash designated for this property and a promised $60,000 family transfer. Assume the selected investment program does not accept the proposed gift as eligible purchase funds. Do not count that transfer as approved capital.</p>
<div class="table-scroll"><table><thead><tr><th>Capital use</th><th>Assumed amount</th></tr></thead><tbody>
<tr><td>Price less loan</td><td>$175,000</td></tr><tr><td>Closing costs</td><td>$15,000</td></tr><tr><td>Setup and rental readiness</td><td>$35,000</td></tr><tr><td>Retained operating reserve</td><td>$30,000</td></tr><tr><td>Total capital allocation</td><td>$255,000</td></tr><tr><td>Own designated cash / shortfall</td><td>$225,000 / $30,000</td></tr>
</tbody></table></div>
<p>Own cash covers the assumed $190,000 closing requirement and leaves $35,000. Spending that balance on setup leaves none of the planned $30,000 operating reserve. A statement that the down payment is covered misses the acquisition's remaining cash dependency. The reserve is retained liquidity, not an expense already incurred; do not deduct it again when later calculating actual operating costs. Lender reserve eligibility and your chosen operating floor require separate checks, even when some cash can meet both tests at the same moment.</p>
<p>For comparison only, assume a different suitable property costs $560,000 with a $420,000 loan and the same $15,000 closing costs, $35,000 setup and $30,000 reserve. Its capital allocation is $140,000 plus $80,000, or $220,000, leaving $5,000 outside the plan from the buyer's $225,000. This illustrates a smaller funded purchase, not an available property, promised discount or proof that identical costs and loan proportions apply. Re-quote financing, condition, permissions, insurance and setup for the actual alternative.</p>
<p>If a different investment product explicitly accepts a documented $60,000 gift and all its conditions are satisfied, the modeled available capital would instead be $285,000, leaving $30,000 beyond the original $255,000 allocation. Compare its full payment, fees, restrictions and timing rather than choosing it solely for gift eligibility. If the transfer remains unapproved or unavailable, that extra capital remains a contingent scenario—not the funded case. Do not route money to another use as a workaround for a lender restriction.</p>
<h2>Choose the purchase before committing the family transfer</h2>
<p>Proceed only when the actual source, loan conditions, closing timing and launch budget are supported. Consider a smaller purchase or additional independently eligible capital when the gift-free case has a gap. Delay commitment under valid contract protection while source approval remains outstanding; contract counsel should explain the actual deadlines and remedies, not an assumed automatic refund. Reject a plan requiring concealed repayment, misstated occupancy or money that nobody has confirmed is eligible.</p>
<p>Have qualified advisers address any donor or recipient reporting and family agreement separately. No tax estimate pays a closing bill before cash is available. Use the <a href="/blog/str-lender-reserve-requirements/">lender versus operating-reserve worksheet</a> and <a href="/blog/str-tax-benefit-shortfall-purchase/">smaller or unavailable tax-benefit case</a> to challenge those other dependencies. <a href="/apply/">Bring the completed funding ledger to an acquisition call</a>; BNB Accelerator helps within its contracted scope, while the lender determines program eligibility and professionals review legal and tax consequences.</p>
<p class="small">Primary Fannie Mae guidance reviewed October 6, 2026. Educational information, not legal, tax, lending or personalized investment advice. All example figures and financing proportions are hypothetical. No gift eligibility, approval, tax benefit or investment result is guaranteed.</p>'''
if __name__=='__main__':
 main(slug=SLUG,title='Gift Funds for an STR Down Payment: Eligibility and Cash Test',h1='Can Gift Funds Be Used for an STR Down Payment?',description='Verify investment-loan gift eligibility before transferring family money. Use a lender evidence ledger and worked closing, setup and reserve cash test.',body=BODY,search_terms='gift funds family transfer investment loan down payment source of funds closing setup reserves cash shortfall',hub_attribute='data-gift-funds-link',hub_block='<p data-gift-funds-link>Before relying on family money, use the <a href="/blog/gift-funds-str-down-payment/">gift-funds eligibility ledger and acquisition cash test</a> to distinguish approved funding from a promised transfer and preserve launch reserves.</p>')
 p=Path(__file__).resolve().parents[1]/'blog'/SLUG/'index.html';s=p.read_text();words=len(re.findall(r'\b\w+\b',html.unescape(re.sub('<[^>]+>',' ',BODY))))
 def schema(m):
  d=json.loads(m.group(2))
  for n in d.get('@graph',[d]):
   if n.get('@type') in ['Article','BlogPosting']:n['wordCount']=words
  return m.group(1)+json.dumps(d,indent=2)+m.group(3)
 s=re.sub(r'(<script[^>]*type="application/ld\+json"[^>]*>)(.*?)(</script>)',schema,s,flags=re.S);p.write_text(s)
