"""Refresh an existing furnished acquisition inventory/acceptance decision."""
import html,json,re
from pathlib import Path
from expand_reservations_closing import main
SLUG='str-furniture-bill-of-sale'
BODY='''<p class="lead">When buying a furnished STR, verify what the seller owns, what actually conveys, what condition you accept and what will be present at possession. A furnished listing or photo album is not a complete transfer record. The purchase decision is whether the verified inventory supports your lawful opening plan at a funded replacement cost, not whether the seller once paid an impressive retail total.</p>
<p><a href="/apply/">Book an acquisition call to compare the inventory handoff with your remaining setup cash</a>. Bring the agreed item schedule and dated condition evidence. Local counsel and the closing professional should determine appropriate documents and remedies; the lender and tax adviser must review their respective treatment.</p>
<h2>Separate ownership promises from condition promises</h2>
<p>As a state-specific example, <a href="https://www.trec.texas.gov/forms/non-realty-items-addendum" rel="noopener">TREC's current Non-Realty Items Addendum page</a> identifies Form 57-0 for additional personal property not already specified in the purchase contract. Its <a href="https://www.trec.texas.gov/sites/default/files/pdf-forms/57-0_1.pdf" rel="noopener">linked form</a> calls for item identification and an ownership representation concerning encumbrances, while disclaiming a condition or future-performance warranty. A signed ownership representation is therefore not proof that every appliance works. This Texas form example is not a national document requirement or advice to use it unchanged in your transaction.</p>
<p>Have counsel distinguish the agreed ownership terms, accepted condition, exclusions, delivery date and any negotiated remedy. Ask how each document interacts with the main contract and lender disclosures. Do not assume a separate bill of sale overrides conflicting terms, creates a replacement obligation or permits an undisclosed side payment. Discuss price allocations with qualified advisers rather than assigning high personal-property values to pursue a deduction or financing result.</p>
<p>Ask the authorized seller for supporting purchase/lease records for material items. Identify rented equipment, financed goods, manager-owned supplies, excluded art and owner-closet items. Resolve who can convey each item and what release or other evidence is needed. A photo shows presence, not ownership. Do not treat an unresolved item as a usable buyer asset until the actual transaction team confirms its status.</p>
<h2>Build a room-level acceptance record</h2>
<div class="table-wrap"><table><thead><tr><th>Record</th><th>Evidence</th><th>Purchase consequence</th></tr></thead><tbody>
<tr><td>Identity and quantity</td><td>Room/location, item description, model/serial where useful, dated photos and counts</td><td>Distinguish the promised item from a similar substitute</td></tr>
<tr><td>Ownership and exclusions</td><td>Seller confirmation, material receipts/lease records and expressly excluded items</td><td>Do not budget third-party property as included</td></tr>
<tr><td>Condition and safety</td><td>Agreed checks, defects, missing parts and model-specific recall review</td><td>Exclude unsafe or unsuitable items from opening readiness</td></tr>
<tr><td>Delivery and exceptions</td><td>Possession schedule, final check, dated exception list and adviser-reviewed resolution</td><td>Price missing or changed items before deciding whether to close</td></tr>
</tbody></table></div>
<p>For linens and smallwares, record counts and accepted condition rather than a vague promise of a stocked house. For beds and furnishings, compare actual inventory with the permitted occupancy and intended room layout. More furniture does not create legal capacity. For smart devices, arrange authorized account removal, reset and buyer setup without taking seller passwords, guest information or unrelated accounts. Device ownership is not ownership of platform reviews or reservations.</p>
<p>Use the <a href="https://www.cpsc.gov/About-CPSC/Division-of-Field-Operations/FAQs-For-Buying-and-Selling-Products-Online" rel="noopener">CPSC's current recall guidance</a> and recall database to check identifiable products. CPSC distinguishes an unlawfully sold recalled item from one with the published remedy applied. Save evidence of the applicable remedy, not just the seller's statement that no problem occurred. Missing identifiers, damaged furniture or an unresolved recall require appropriate investigation; absence of a search match is not a safety certification.</p>
<h2>Worked hypothetical: retained inventory is avoided spending, not cash</h2>
<p>Invented planning figures only, not used-furniture appraisals, actual quotes or a client outcome. Assume a complete replacement plan has $32,000 of items, $4,000 delivery/assembly/tax and $2,000 removal/preparation costs. Total is $38,000. Suppose verified included items eliminate $18,000 of purchases from the item line only, with other costs unchanged. Remaining setup is $14,000 plus $4,000 plus $2,000, or $20,000.</p>
<p>If $55,000 accessible cash remains after closing and $25,000 is protected for operation, setup spending capacity is $30,000. The $20,000 plan leaves $35,000 cash: the protected $25,000 plus $10,000 unallocated. The avoided $18,000 purchases are already reflected in the lower setup bill. They are not another $18,000 bank balance or a fair-market-value conclusion for tax or appraisal.</p>
<p>At the final check, assume missing or unsuitable included items add $6,000 of replacement purchases, already including the specific substitutions needed, without changing other charges. Avoided purchases fall from $18,000 to $12,000. Setup becomes $20,000 of items plus $4,000 delivery/assembly/tax plus $2,000 removal/preparation, or $26,000. Cash after setup is $29,000, leaving only $4,000 above the protected reserve. Do not subtract $6,000 from cash and also reduce the $18,000 savings again in the same total.</p>
<p>For a separate timing stress, an additional $5,000 of continuing bills caused by delivery delay raises total setup-and-delay spending to $31,000. Only $24,000 remains from $55,000, a $1,000 reserve gap. No later seller reimbursement is assumed. A hoped-for credit or claim cannot fund an early replacement invoice until the amount, permitted treatment and payment timing are established.</p>
<h2>Resolve walkthrough exceptions through the actual contract</h2>
<p>Compare the agreed schedule with the property immediately before the relevant closing/possession milestone. Record missing items, substitutions, damage and unresolved ownership with dated evidence. Ask counsel and the closing team what the contract permits: seller completion, a documented accepted adjustment, lawful extension or another supported outcome. Do not assume a right to withhold closing funds, demand new retail replacements, cancel or recover earnest money.</p>
<p>Review any revised price, allocation or settlement credit with the lender before relying on it. The <a href="/blog/seller-credit-str-furnishings/">seller-credit guide</a> explains permitted closing relief versus spendable setup cash; the <a href="/blog/appraisal-gap-furnished-str/">furnished appraisal-gap guide</a> addresses financing shortfalls. Neither proves the seller delivered the particular usable items promised here.</p>
<p>Proceed when the documented transfer and accepted condition support readiness within funded cash. Renegotiate verified exceptions using actual replacement quotes and approved terms. Delay under valid protection while decisive ownership or delivery issues are resolvable. Reject a purchase dependent on unverified inventory, unsafe items or unavailable replacement funds. <a href="/apply/">Bring the exception list and revised replacement budget to an acquisition call</a>. BNB Accelerator assists within its contracted acquisition scope; advisers determine legal documents, lending and tax treatment.</p>
<p class="small">Primary TREC and CPSC sources reviewed October 6, 2026. Educational information, not legal, tax, lending, product-safety certification or personalized investment advice. All example amounts are hypothetical. No transfer, warranty, reimbursement, tax result or investment return is guaranteed.</p>'''
if __name__=='__main__':
 main(slug=SLUG,title='STR Furniture Bill of Sale: Inventory and Closing Checks',h1='What Belongs in an STR Furniture Bill of Sale?',description='Buying a furnished STR? Verify ownership, condition, recalls and delivered inventory, then price walkthrough exceptions against available setup cash.',body=BODY,search_terms='furniture bill sale inventory ownership condition walkthrough missing items replacement',hub_attribute='data-furniture-handoff-link',hub_block='<p data-furniture-handoff-link>For a furnished acquisition, use the <a href="/blog/str-furniture-bill-of-sale/">inventory ownership and closing-acceptance worksheet</a> to verify delivered items and fund replacements without counting retail value as cash.</p>')
 p=Path(__file__).resolve().parents[1]/'blog'/SLUG/'index.html';s=p.read_text();words=len(re.findall(r'\b\w+\b',html.unescape(re.sub('<[^>]+>',' ',BODY))))
 def schema(m):
  d=json.loads(m.group(2))
  for n in d.get('@graph',[d]):
   if n.get('@type') in ['Article','BlogPosting']:n['wordCount']=words
  return m.group(1)+json.dumps(d,indent=2)+m.group(3)
 p.write_text(re.sub(r'(<script[^>]*type="application/ld\+json"[^>]*>)(.*?)(</script>)',schema,s,flags=re.S))
