"""In-place acquisition refinance worksheet; no homepage or legacy generators."""
import html,json,re
from pathlib import Path
from expand_reservations_closing import main
SLUG='refinance-after-str-stabilization'
BODY='''<p class="lead">An STR can operate well and still fail to produce the refinance cash its buyer expected. Before making an offer, distinguish operational stabilization from lender eligibility, acceptable value, qualifying income and net cash actually released. For a high-income buyer planning another acquisition, the useful question is not just when to refinance: it is whether the first property remains affordable if that loan arrives later, returns less capital or never closes.</p>
<p><a href="/apply/">Book an acquisition call to compare this STR's purchase budget with a smaller or unavailable refinance</a>. Obtain lending conclusions from the actual lender; an acquisition model is not loan approval.</p>
<h2>Separate the operating record from the lender's clock</h2>
<p>Define stabilization using the property's own evidence: reconciled receipts, actual expenses, lawful available capacity, completed opening work and a representative operating period. A strong peak season is not automatically representative of a full year. Review refunds, owner stays, channel costs, maintenance and reserves before projecting distributions. Keep seller history separate from the buyer's new operating record.</p>
<p><a href="https://selling-guide.fanniemae.com/sel/b2-1.3-03/cash-out-refinance-transactions" rel="noopener">Fannie Mae's cash-out refinance guidance</a> generally requires an existing first mortgage being paid off to be at least twelve months old, measured between note dates, and at least one borrower to have held title for six months before disbursement, subject to its stated exceptions. These are separate tests, not twelve months of bookings. Confirm applicability and exceptions with the lender. They are not universal DSCR or portfolio-lender requirements.</p>
<p>The <a href="/blog/delayed-financing-cash-str/">delayed-financing guide</a> addresses the separate cash-purchase path and its documentation conditions. This page addresses an already-financed purchase and later cash release after operations develop. A lender's seasoning date, earliest application date and likely funding date can differ. A permitted application does not promise approval, an appraisal or a completed closing.</p>
<h2>Build a lender evidence packet before setting a purchase dependency</h2>
<p>Ask for a dated, product-specific assessment identifying the borrower, intended investment use, ownership structure, property eligibility and every remaining condition. A high salary, substantial liquid assets or large tax bill does not establish that this particular collateral and income qualify. Keep personal/business liquidity outside the property plan separate from cash you have actually allocated to it.</p>
<div class="table-scroll"><table><thead><tr><th>Evidence</th><th>Question for the responsible reviewer</th><th>Purchase-model consequence</th></tr></thead><tbody>
<tr><td>Original note, closing and title records</td><td>Which dates, ownership and payoff requirements apply?</td><td>Do not schedule capital release before a supported funding path</td></tr>
<tr><td>Reconciled operating statements and required tax records</td><td>Which income measure, history and adjustments will this product accept?</td><td>Do not substitute gross Airbnb bookings for qualifying income</td></tr>
<tr><td>Appraisal and property-condition requirements</td><td>What collateral value and completed work support the advance?</td><td>Test less value than the acquisition thesis expects</td></tr>
<tr><td>Permission, insurance and ownership documents</td><td>Does the buyer's actual use and structure meet applicable conditions?</td><td>Unresolved eligibility is not repaired by a larger cash buffer alone</td></tr>
<tr><td>Payoff statement and itemized loan terms</td><td>What penalties, accrued interest, costs and reserve conditions remain?</td><td>Calculate net funds rather than multiplying value by a loan percentage</td></tr>
</tbody></table></div>
<p>Ask whether the product uses accepted STR history, another rental measure or borrower income, and which evidence supports it. Do not assume all lenders use the same DSCR definition. The <a href="/blog/what-lenders-do-with-airdna/">rental-estimate evidence guide</a> and <a href="/blog/reading-a-dscr-term-sheet/">loan-term comparison worksheet</a> address those separate questions. Store sensitive account, tax and seller documents securely; summarize verified figures in the decision file.</p>
<h2>Worked hypothetical: equity is not freely reusable cash</h2>
<p>Invented worksheet only, not current lender terms, allowable ratios, an appraisal or a client result. Assume a $450,000 existing payoff, $14,000 of refinance costs, a separately stated $9,000 prepayment charge, and $12,000 of additional cash retained for required reserves. Here the payoff excludes that charge and the cost line excludes it too; reconcile actual statements so the same item is not deducted twice. Existing operating reserves remain intact outside this example.</p>
<p>For this constructed product, assume the advance cannot exceed either 75% of accepted collateral value or a separately calculated income-based loan cap. Other eligibility conditions must also pass. The lower cap determines the modeled gross loan; the table does not claim this is any lender's actual DSCR calculation.</p>
<div class="table-scroll"><table><thead><tr><th>Hypothetical case</th><th>Value / 75% value cap</th><th>Income cap / gross loan</th><th>Cash after payoff, costs and penalty</th><th>After additional reserve</th></tr></thead><tbody>
<tr><td>Supported planning case</td><td>$800,000 / $600,000</td><td>$560,000 / $560,000</td><td>$87,000</td><td>$75,000 potentially reusable</td></tr>
<tr><td>Lower value and income</td><td>$700,000 / $525,000</td><td>$500,000 / $500,000</td><td>$27,000</td><td>$15,000 potentially reusable</td></tr>
<tr><td>Deeper downside</td><td>$600,000 / $450,000</td><td>$440,000 / $440,000</td><td>$33,000 buyer contribution needed</td><td>$45,000 total new cash needed</td></tr>
</tbody></table></div>
<p>The planning case is $560,000 minus $450,000 minus $14,000 minus $9,000, leaving $87,000 at settlement before the separate $12,000 reserve. It does not return $110,000 of spendable cash merely because the gross loan exceeds payoff by that amount. The downside leaves $60,000 less reusable money. If a second purchase needs an assumed $70,000 allocation, $75,000 covers it with only $5,000 outside that allocation, while $15,000 leaves a $55,000 funding gap.</p>
<p>The deeper downside requires $33,000 to reconcile closing uses before the additional reserve, or $45,000 including it. It is not negative cash that a lender will automatically finance, and the loan may be unavailable altogether. A no-refinance case releases no money, keeps existing debt obligations in force and may still incur application or valuation costs already paid. Record incurred costs once even when no loan closes.</p>
<h2>Test the waiting period and the new debt separately</h2>
<p>Assume a separate four-month delay produces $4,000 per month of net property cash shortfall after actual receipts and all existing expenses: $16,000 must be funded. This is an invented net shortfall, not another deduction of gross debt service already in that figure. If funded from the same free-capital pool, reduce that pool before committing to another property. Do not deduct it again from settlement proceeds if it was already captured in the updated cash balance.</p>
<p>New borrowing also changes future owner cash. In a separate illustrative annual budget, $60,000 after operating costs and replacement allocations but before mortgage payments, less an assumed $50,000 new annual principal-and-interest obligation, leaves $10,000 before tax and other omitted costs. That payment is a hypothetical budget input, not a quote for the table's loan. Recalculate with the actual loan, amortization, escrow treatment and property expenses; avoid counting taxes or insurance both in operating costs and again in an escrowed payment.</p>
<p>Cash-out is borrowing, not extra rental revenue or a tax refund. Ask independent advisers how the proposed debt and use of funds affect your situation; no deduction, refund or investment return is promised. Compare the refinance with keeping the existing debt and retaining capital in the property. For a known maturity obligation, use the distinct <a href="/blog/seller-financing-balloon-str/">seller-financing balloon review</a>; optional cash recycling is not the same as a payment that becomes due.</p>
<h2>Choose the purchase without promising the next loan</h2>
<p>Proceed when the original purchase and existing-debt holding case fit verified use, supportable economics and funded downside needs. Renegotiate price or financing when affordability depends on proceeds the lender cannot support. Delay a second acquisition until usable funds actually arrive and required repayments and reserves are satisfied. Reject a purchase thesis that needs an unapproved refinance to meet unavoidable obligations you cannot otherwise fund.</p>
<p>Record the evidence date, remaining lender conditions, smallest workable cash release, latest affordable funding date and alternative holding plan. Revisit the model when value, revenue, rates, ownership or payoff changes. <a href="/blog/buy-str-high-income-large-tax-bill/">The high-income purchase hub</a> connects capital planning to the rest of the acquisition. <a href="/apply/">Bring this refinance worksheet and your property shortlist to an acquisition call</a>; BNB Accelerator assists within its contracted scope while lenders and independent advisers make their respective determinations.</p>
<p class="small">Primary lender guidance reviewed October 6, 2026. Educational information, not lending, legal, tax or personalized investment advice. All worksheet figures are hypothetical. No refinance, timing, appraisal, proceeds, tax benefit or investment result is guaranteed.</p>'''
if __name__=='__main__':
 main(slug=SLUG,title='STR Refinance After Stabilization: Net-Cash Worksheet',h1='When Can an STR Refinance After It Stabilizes?',description='Before buying an STR, test refinance timing, loan limits, net cash and a smaller or unavailable loan with an original downside worksheet.',body=BODY,search_terms='stabilized refinance net proceeds seasoning lower appraisal income capital recycling',hub_attribute='data-stabilized-refinance-link',hub_block='<p data-stabilized-refinance-link>Planning another purchase after the first STR stabilizes? Use the <a href="/blog/refinance-after-str-stabilization/">refinance net-cash and downside worksheet</a> to separate gross borrowing from capital actually available to redeploy.</p>')
 p=Path(__file__).resolve().parents[1]/'blog'/SLUG/'index.html';s=p.read_text();words=len(re.findall(r'\b\w+\b',html.unescape(re.sub('<[^>]+>',' ',BODY))))
 def schema(m):
  d=json.loads(m.group(2))
  for n in d.get('@graph',[d]):
   if n.get('@type') in ['Article','BlogPosting']:n['wordCount']=words
  return m.group(1)+json.dumps(d,indent=2)+m.group(3)
 s=re.sub(r'(<script[^>]*type="application/ld\+json"[^>]*>)(.*?)(</script>)',schema,s,flags=re.S);p.write_text(s)
