"""Existing acquisition-guide refresh; never a new expansion URL."""
import expand_hold_period as renderer

renderer.SLUG='depreciation-recapture-str'
renderer.TITLE='STR Depreciation Recapture: Review Before You Buy'
renderer.H1='Depreciation recapture: what an STR buyer should review'
renderer.DESC='Before buying an STR, separate sale cash, adjusted basis and asset-level recapture. Use a records worksheet and adviser review without assuming full 1031 deferral.'
renderer.FAQ=[
('Is the loan payoff my adjusted tax basis?', 'No. Request separate basis and settlement-cash reconciliations from the appropriate advisers. The debt balance cannot replace the asset records used for the tax calculation.'),
('Must every earlier deduction return as ordinary income?', 'Do not assume that. Asset classification, depreciation history, realized gain and transaction-specific rules matter. The limited equipment example is not a calculation for the entire property.'),
('Does a 1031 exchange defer all depreciation recapture?', 'No blanket promise is appropriate. Ask qualified exchange and tax advisers to analyze each asset and any current liability; the proposed replacement must also satisfy applicable exchange requirements.'),
('Should a high-income buyer skip cost segregation?', 'Not automatically. Request an adviser-reviewed comparison of usable early effects, study costs, later disposition and independently funded purchase needs. A study estimate alone is not an acquisition decision.')]
renderer.BODY='''<p class="lead">Before buying an STR, ask how depreciation could affect a later disposition—not just how large an early deduction might look. Recapture planning belongs beside your purchase budget, supported operating case and future liquidity needs. A cost-segregation estimate does not prove a refund, an affordable acquisition or a favorable lifetime result. This guide gives you an asset-record worksheet and a limited worked example to take to your CPA, without prescribing a tax election or promising that an exchange removes the issue.</p>
<p><a href="/apply/">Discuss the property acquisition with a funded budget and a clear adviser-question list</a>. BNB Accelerator is not your tax adviser; tax and exchange conclusions require independent qualified professionals.</p>
<h2 id="mechanic">Separate cash, basis and tax character</h2>
<p>Keep three separate questions in your purchase file: what money eventually reaches you after settlement obligations, what adjusted basis your adviser establishes, and how the resulting gain is characterized. A large mortgage can leave little cash even when a tax liability exists. Conversely, cash retained at closing is not automatically all taxable gain. Do not apply your marginal rate to the gross sale price or substitute a lender payoff statement for the depreciation schedule.</p>
<p><a href="https://www.irs.gov/publications/p551">IRS Publication 551</a> explains adjusted basis and reductions for depreciation allowed or allowable. Not claiming a deduction does not automatically preserve basis. Keep acquisition allocations, capital additions and depreciation records together; ask the CPA to reconcile them rather than treating the original purchase price as today's basis.</p>
<p><a href="https://www.irs.gov/publications/p544">IRS Publication 544</a> describes different property categories. For an ordinary taxable sale of section 1245 property, ordinary-income recapture generally cannot exceed either depreciation/amortization allowed or allowable or realized gain. Building-related section 1250 treatment differs. A cost-segregation label or shorter recovery period does not determine every consequence by itself.</p>
<p>For a purchase decision, request the tax calculation and cash calculation in parallel, with dates. If an adviser has not established the asset classifications or the seller's proposed allocation is unsupported, treat that as an unresolved input—not a favorable zero-tax assumption. The <a href="/blog/cost-seg-timing-and-hold-period/">hold-period comparison</a> addresses disposition-cash sensitivity; this page focuses on the records and asset-level distinction behind that review.</p>
<h2 id="why">Build the buyer's asset review register</h2>
<div class="table-wrap"><table><thead><tr><th>Record</th><th>Question for the reviewer</th><th>Before-offer consequence</th></tr></thead><tbody>
<tr><td>Acquisition allocation and closing records</td><td>What supports the amounts assigned to land, building and included assets?</td><td>Do not buy based on an unsupported deduction estimate</td></tr>
<tr><td>Study scope, fee and asset schedule</td><td>Which components were actually analyzed, by whom, and on what evidence?</td><td>Price the study separately from property and launch costs</td></tr>
<tr><td>Depreciation and later additions</td><td>Can the CPA reconcile each asset's history and adjusted basis?</td><td>Identify missing records or classification issues early</td></tr>
<tr><td>Removed or replaced components</td><td>Were prior disposals and replacements tracked without double counting?</td><td>Keep repair bids distinct from supported tax adjustments</td></tr>
<tr><td>Proposed disposition allocations</td><td>What supports the values of assets included in a future sale?</td><td>Use defensible scenarios, not a zero-value furnishing shortcut</td></tr>
<tr><td>Settlement cash and tax provision</td><td>Which obligations are paid when, and what cash must remain available?</td><td>Protect launch reserves and future liquidity independently</td></tr>
</tbody></table></div>
<p>Use one row per material asset or adviser-approved grouping, with a document location, preparer, review date and unresolved question. Do not upload returns, bank details or identity documents through casual messages. Agree secure channels with each adviser. A seller's old study may help identify questions, but its depreciated basis is not automatically the buyer's starting basis; have the transaction's actual ownership and structure reviewed.</p>
<h2>Worked equipment example: depreciation is not the whole gain</h2>
<p>Hypothetical arithmetic, not a client result, market valuation or tax return. Assume a CPA has confirmed one business equipment asset is section 1245 property, its original basis is $24,000, total depreciation through disposition is $18,000, and no other basis adjustment applies. Adjusted basis is $6,000. Assume an ordinary taxable sale and the amounts below are the amount realized for that asset after any properly allocated selling expense. Special transactions and exceptions are outside this illustration.</p>
<div class="table-wrap"><table><thead><tr><th>Illustrative asset case</th><th>Realized gain</th><th>Ordinary recapture under the stated assumptions</th></tr></thead><tbody>
<tr><td>$14,000 amount realized</td><td>$14,000 − $6,000 = $8,000</td><td>Lesser of $18,000 and $8,000: $8,000</td></tr>
<tr><td>$28,000 amount realized</td><td>$28,000 − $6,000 = $22,000</td><td>Lesser of $18,000 and $22,000: $18,000</td></tr>
</tbody></table></div>
<p>The second case leaves $4,000 of gain outside this recapture calculation; its treatment still requires CPA review. The example does not calculate tax due, classify all furnishings, determine a building's gain or establish an allocation for an entire STR sale. It demonstrates why an $18,000 depreciation history is not automatically an $18,000 recapture amount in every sale. Change the supported asset value and the result changes.</p>
<p>As a separate cash check, suppose this equipment is included in a hypothetical $640,000 whole-property sale with $38,000 of distinct sale outflows and a $390,000 payoff. Cash before tax and other obligations is $212,000. Do not add the equipment proceeds again: they are already within the $640,000. That $212,000 is not the property's gain, recapture amount or investment return. Ask for the full asset reconciliation and a tax provision before earmarking it for another purchase.</p>
<h2 id="mistakes">Review exchange claims asset by asset</h2>
<p>Publication 544 limits like-kind nonrecognition to qualifying real property and describes circumstances where section 1245 recapture occurs even when no gain would otherwise be recognized. A proposed 1031 exchange is therefore not a blanket deferral promise for every cost-segregation component. Ask qualified tax and exchange advisers to model the actual assets, replacement property and transaction.</p>
<p>Request separate written outputs for deferred gain, any current taxable amounts, restricted exchange funds, replacement funding and expected household-accessible cash. A real-property exchange plan is not interchangeable with a taxable sale followed by unrestricted reinvestment. For replacement-first timing, use the <a href="/blog/reverse-1031-buy-str-before-selling/">reverse-exchange cash bridge</a>; adviser-approved implementation is still essential.</p>
<h2 id="plan">Make an acquisition decision without a tax promise</h2>
<p>Compare the supported study case with the appropriate no-study depreciation case for the same property and ownership assumptions. Include the provider's fee, when an early effect is actually usable, operating downside, future capital work and adviser-modeled disposition. Do not assume lower future income, appreciation, a ready replacement property or indefinite ownership. Use the <a href="/blog/str-tax-benefit-shortfall-purchase/">smaller-or-delayed-benefit purchase test</a> if the transaction needs a tax receipt to remain funded.</p>
<p>Proceed only when the independently funded purchase and operating plan fit your limits. Reprice a still-viable property when verified costs change the budget. Delay under valid protection while a decisive record or adviser input remains unresolved. Decline a deal that depends on an unverified refund or universal exchange deferral. Tax planning cannot fix rental permission, weak seller evidence or an unfunded launch.</p>
<p><a href="/apply/">Bring the shortlist, funding timetable and bounded tax-review questions to an acquisition call</a>. BNB Accelerator assists within its contracted acquisition scope; independent advisers establish legal, tax, financing and exchange conclusions. Continue through the <a href="/blog/buy-str-high-income-large-tax-bill/">high-income buyer roadmap</a> for the broader purchase sequence.</p>
<p class="small">IRS primary materials reviewed October 7, 2026: Publication 544 (2025) and Publication 551 (12/2025), not newly issued 2026 editions. Educational information only, not personalized investment, tax, legal or lending advice. All example amounts are hypothetical. No deduction, refund, exchange, sale price or investment result is guaranteed.</p>'''

if __name__=='__main__':
 renderer.main('2026-08-10','data-recapture-review-link','Before relying on a deduction estimate, use the <a href="/blog/depreciation-recapture-str/">asset-record register and limited recapture example</a>. Separate the CPA’s gain calculation from debt payoff and cash available for the next acquisition.')
