"""Scoped existing privacy owner; current channel sources and original acceptance worksheet."""
import html,json,re
from pathlib import Path
from expand_reservations_closing import main
R=Path(__file__).resolve().parents[1]
SLUG='security-camera-privacy-str'
BODY='''<p class="lead">Before buying an STR with exterior cameras, separate ownership of the hardware from permission to use it, control of its accounts and accurate guest disclosure. A doorbell included in the sale is not proof that the buyer controls the camera or that its actual view fits the intended rental channels. Resolve these questions while purchase protections still apply, rather than treating camera setup as a routine task after closing.</p>
<p>This guide supplies a device-by-device purchase acceptance worksheet, not installation instructions or a finding that a property is legally compliant. BNB Accelerator is an interested acquisition-service provider and assists within its contracted scope. Independent counsel, qualified installers, insurers and each platform determine their respective requirements. Keep guest footage and account credentials out of public acquisition documents.</p>
<h2>Exterior camera permission differs by rental channel</h2>
<p><a href="https://www.airbnb.com/help/article/3061" rel="noopener">Airbnb's device policy</a> prohibits cameras monitoring a home's interior even when off or disconnected, and prohibits hidden cameras. Exterior devices cannot monitor areas with greater privacy expectations, such as enclosed outdoor showers or saunas. Exterior cameras under the host's control require location disclosure. A disclosed pool camera appears among its examples; this is not permission to disregard other restrictions or applicable law. Decibel monitors assess sound without recording audio, require disclosure and cannot be in bedrooms, bathrooms or sleeping areas. Airbnb encourages, rather than requires, smart-home-device disclosure and a guest disable option.</p>
<p><a href="https://www.vrbo.com/tlp/trust-and-safety/use-of-surveillance-policy" rel="noopener">Vrbo's surveillance policy</a> prohibits interior monitoring, including cameras outside looking in, and hidden devices. Its limited building-common-space exception does not permit cameras inside the rental home or private areas. Outdoor cameras must monitor access points and disclose location and coverage in the listing; photos alone are insufficient. Any visible pool or hot tub requires explicit disclosure both in the listing and visibly at the property. Private exterior areas remain restricted. Vrbo also requires reasonable limits on collection, storage and access, with lawful deletion when no longer needed. Noise monitors require pre-booking disclosure and cannot record or transmit audio. Smart-home devices require pre-booking disclosure and an off option.</p>
<p>Do not flatten those policies into one universal pool-camera rule. Ask which channels will actually distribute this address and evaluate the whole view, not merely the device's mounting location. An entrance camera that also captures a window or private amenity needs a specific answer; the seller's label of security equipment does not provide one.</p>
<p>For listing implementation, <a href="https://www.airbnb.com/help/article/2914" rel="noopener">Airbnb's disclosure instructions</a> call for describing each exterior device, its location and whether it is on or off in the safety-device settings. Reconcile the buyer's actual device setup with the intended listing. Disclosure does not cure a prohibited view. Local privacy and audio rules, association restrictions and proposed insurance terms require separate address-specific review; channel compliance is not legal approval or a coverage binder.</p>
<h2>Build a camera acceptance register before buying</h2>
<p>Create one row for every device, including doorbells, detached-building cameras and devices controlled by a manager. Record absent or unverified evidence explicitly. Do not copy a seller's completed checklist into the buyer's file without testing the changed ownership and operating plan.</p>
<div class="table-wrap"><table><thead><tr><th>Acceptance field</th><th>Evidence to obtain</th><th>Purchase decision</th></tr></thead><tbody>
<tr><td>Hardware and actual view</td><td>Model, location, field-of-view review and installer findings</td><td>Identify indoor, private-area or unintended neighboring views before approving use</td></tr>
<tr><td>Recording and transmission</td><td>Verified video/audio capabilities, enabled settings and connected integrations</td><td>Do not treat an untested microphone setting as a legal or channel determination</td></tr>
<tr><td>Channel and legal acceptance</td><td>Applicable policy, required disclosures and qualified local advice</td><td>Resolve each intended channel, not only the seller's current one</td></tr>
<tr><td>Control after possession</td><td>Vendor-supported ownership process, buyer access and former-user revocation test</td><td>Confirm who can view, change settings, export or share records</td></tr>
<tr><td>Prior recordings and retention</td><td>Authorized controller, lawful handling instructions and accepted retention/access plan</td><td>Hardware sale does not settle entitlement to old guest footage</td></tr>
<tr><td>Opening responsibility</td><td>Named operator, accepted duties, actual completion date and documented test</td><td>Keep an unresolved device out of the supported launch plan</td></tr>
</tbody></table></div>
<p>Ask the vendor for the current procedure applicable to the exact model, account and region. Physical possession, a factory reset or canceling a subscription should not be accepted as proof of completed ownership release without that procedure and a test. Do not purchase seller passwords as a handoff method. Determine separately who will pay ongoing subscriptions and who may authorize changes before possession.</p>
<p>Use secure, authorized evidence sharing. A buyer does not need identifiable guest recordings in a public worksheet to understand the camera's location or proposed responsibilities. Have counsel address any required preservation, deletion or access restrictions before instructing someone to erase records. There is no universal retention period or prior-footage ownership rule established by this guide.</p>
<h2>Worked decision: a paid camera is not an accepted handoff</h2>
<p>Invented acquisition scenario, not a client example: diligence decisions are due on day 10, seller account release is promised on day 12 and possession is planned for day 15. The house includes a front-door camera, a pool-facing camera and an indoor hallway camera. The seller offers passwords and says the indoor camera is disconnected. None of those statements closes the buyer's evidence gaps.</p>
<p>For the front-door device, verify the actual view, channel disclosures, applicable legal answer and vendor-supported buyer control. For the pool-facing device, identify its purpose and full coverage, then apply the distinct channel conditions described above. For the indoor hallway device, turning it off does not resolve Airbnb's prohibition. Arrange the required removal or other compliant plan with qualified help and document completion; do not infer that the exterior policy permits it.</p>
<p>The decisive timing question is whether a supported answer exists before day 10, not whether the buyer can afford replacement equipment. Ask counsel before the actual deadline whether an appropriate extension, documented condition, replacement plan or other lawful course is available. No automatic extension, cancellation right, deposit refund or seller-paid cure is implied.</p>
<p>If the acquisition works without cameras, evaluate that route with the operator, advisers and relevant insurer or lender rather than assuming cameras are mandatory or removal settles all security duties. If replacement is required, obtain the full scope, authorization, lead time and payment dates. Separate device work from other launch repairs and retained reserves in the <a href="/financing/closing-costs-and-reserves/">closing-cash plan</a>; expected bookings or a future tax benefit cannot pay an earlier installer invoice.</p>
<h2>Test the buyer's operation, not the seller's screenshot</h2>
<p>Before guest use, have the responsible installer and operator verify accepted device locations, actual views, settings and buyer permissions. Record the test date and who witnessed it. Reconcile former owners, manager users, shared accounts and third-party integrations; changing one password is not evidence that every other access path is gone. Avoid creating test footage of occupied guest spaces.</p>
<p>Document the buyer's disclosure and retention plan, including who may respond to incidents and lawful access requests. Recheck after a relocation, replacement, software change or manager change. A seller's listing description may no longer describe the buyer's setup. A contract assigning work to a manager needs accepted duties and evidence, not merely the phrase management included.</p>
<p>The <a href="/blog/security-cameras-buying-short-term-rental/">broader camera purchase guide</a> addresses equipment in the acquisition budget; the <a href="/blog/security-cameras-insurance-short-term-rental/">camera insurance guide</a> addresses insurer questions. This page isolates privacy, channel disclosure and post-sale control. Neither a camera nor a guest acknowledgment guarantees safety, prevents liability or replaces actual insurance terms.</p>
<h2>Choose an evidence-backed acquisition outcome</h2>
<p>Proceed when device use, control, disclosure and opening responsibility are supported for the actual property. Renegotiate when verified replacement costs or restrictions change the purchase case. Delay only under valid contractual protection while a specific answer is obtainable. Reject a supposedly turnkey handoff dependent on seller credentials, prohibited monitoring or unidentified access to guest recordings.</p>
<p>For <a href="/blog/buy-str-high-income-large-tax-bill/">high-income buyers with substantial capital</a>, a small device issue can still expose an unresolved ownership or opening obligation. <a href="/apply/">Bring the camera acceptance register and launch deadlines to an STR acquisition call</a>. Evaluate the whole property and supported operating plan before relying on an anticipated tax outcome.</p>
<p class="small">Primary Airbnb and Vrbo materials reviewed October 8, 2026. Document-based guidance, not firsthand device testing, legal, privacy, insurance, lending, tax or personalized investment advice. Dates and property details in the worked scenario are hypothetical. No legal compliance, platform acceptance, coverage, safety, deduction, booking or return is guaranteed.</p>'''
if __name__=='__main__':
    main(slug=SLUG,title='How Should Exterior Cameras Be Handled at an STR | BNB Accelerator',h1='How Should Exterior Cameras Be Handled at an STR?',description='Buying an STR with cameras? Compare Airbnb and Vrbo rules, verify account control and use a device acceptance worksheet before closing.',body=BODY,search_terms='camera privacy acquisition handoff account control Airbnb Vrbo disclosure',hub_attribute='data-camera-privacy-link',hub_block='<p data-camera-privacy-link>Exterior cameras included in a shortlisted STR? Use the <a href="/blog/security-camera-privacy-str/">camera privacy and account-control acceptance register</a> to resolve channel requirements and handoff deadlines before closing.</p>')
    p=R/'blog'/SLUG/'index.html';s=p.read_text().replace('Updated October 6, 2026','Updated October 8, 2026')
    words=len(re.findall(r'\b\w+\b',html.unescape(re.sub('<[^>]+>',' ',BODY))))
    def schema(m):
        d=json.loads(m[2])
        for n in d.get('@graph',[d]):
            if n.get('@type') in ['Article','BlogPosting']:n.update(dateModified='2026-10-08',wordCount=words)
        return m[1]+json.dumps(d,indent=2)+m[3]
    p.write_text(re.sub(r'(<script[^>]*type="application/ld\+json"[^>]*>)(.*?)(</script>)',schema,s,flags=re.S))
    p=R/'sitemap-blog.xml';s=p.read_text();url='https://www.bnbaccelerator.com/blog/'+SLUG+'/'
    s,n=re.subn(r'(<loc>'+re.escape(url)+r'</loc>\s*<lastmod>)[^<]*(</lastmod>)',lambda m:m[1]+'2026-10-08'+m[2],s);assert n==1;p.write_text(s)
