#!/usr/bin/env python3
"""Generate 100 distinct, question-led STR buyer decision guides."""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(__file__))
import blog
from pillars import write

DATE = "2026-09-23"

CLUSTERS = {
    "Contract & Offer": {
        "context": "Treat the purchase agreement as a risk-allocation document. The underwriting only matters if the contract leaves enough time and leverage to verify the assumption before it becomes nonrefundable.",
        "action": "Translate the unresolved item into a dated contingency, document-delivery requirement, credit, escrow holdback, or walk-away condition with local counsel. A verbal promise is not a closing condition.",
        "related": ["/underwriting/", "/blog/negotiating-airbnb-purchase/", "/apply/"],
    },
    "Revenue Evidence": {
        "context": "Revenue evidence has to reconcile nights, rates, fees, refunds, and availability. A screenshot can be true and still answer the wrong question.",
        "action": "Keep the raw export, the normalization worksheet, and the assumptions used for the buyer case. Price the property from the buyer case, not the seller's label for the number.",
        "related": ["/revenue-projections/", "/underwriting/seller-financials/", "/tools/str-revenue-calculator/"],
    },
    "Operating Economics": {
        "context": "Operating expenses behave differently: some follow occupied nights, some follow turns, and some continue even when the home is empty. The model should preserve those differences.",
        "action": "Replace percentage allowances with written quotes or bills for the largest lines, then keep a separate replacement reserve. Do not hide capital wear inside an optimistic maintenance percentage.",
        "related": ["/underwriting/expense-ratio/", "/underwriting/downside-scenario/", "/str-cash-flow-analysis/"],
    },
    "Financing & Closing": {
        "context": "A loan approval answers whether a lender will fund the transaction under its rules. It does not establish that the property will produce the owner's required return.",
        "action": "Put the lender's treatment in writing, mirror it in the cash model, and preserve enough liquidity for closing changes. Compare loan terms on total cash and downside survival, not rate alone.",
        "related": ["/financing/", "/underwriting/cash-needed-to-buy/", "/blog/reading-a-dscr-term-sheet/"],
    },
    "Insurance & Hazard": {
        "context": "Insurability is property-specific. The correct question is not whether coverage exists, but what peril, deductible, occupancy pattern, and lost-income period the quoted policy actually covers.",
        "action": "Obtain a bindable quote for the address and operating plan before the contingency expires. Carry the deductible in the reserve model and record important exclusions beside the revenue case.",
        "related": ["/underwriting/insurance-quote/", "/blog/airbnb-insurance-guide/", "/underwriting/downside-scenario/"],
    },
    "Rules & Permits": {
        "context": "Short-term-rental permission can depend on parcel, owner, structure, license status, and transaction form. Citywide summaries cannot approve an address.",
        "action": "Save the ordinance, map, written official response, and verification date. Make the allowed fallback use work financially; if it does not, the legal-use question is a purchase condition.",
        "related": ["/regulations/", "/underwriting/permit-transfer/", "/underwriting/hoa-restrictions/"],
    },
    "Vendor Operations": {
        "context": "Remote ownership fails at exception handling, not at scheduled messages. The operating plan needs named people, response times, access rules, and a backup for each guest-critical function.",
        "action": "Attach the operating standard to the vendor agreement, test it before launch, and keep a second provider warm. A phone number is not redundancy unless that person has access and accepts the work.",
        "related": ["/management/", "/blog/first-90-days-airbnb-launch/", "/blog/airbnb-cleaning-turnover-systems/"],
    },
    "Pricing & Calendar": {
        "context": "Average annual rate and occupancy conceal the calendar decisions that create them. Price, minimum stay, lead time, and availability must be tested at date level.",
        "action": "Define the rule, the data window, and the review date before changing the calendar. Measure contribution and displacement, not occupancy or nightly rate in isolation.",
        "related": ["/pricing/", "/blog/pricing-the-booking-window/", "/blog/occupancy-versus-rate-which-to-optimize/"],
    },
    "Tax Coordination": {
        "context": "Tax outcomes turn on the owner's facts, records, use, and participation. The property team should preserve evidence and timing without presenting itself as the taxpayer's adviser.",
        "action": "Send the fact pattern and records to the owner's CPA before the deadline or operating decision. Keep the acquisition case viable without a tax benefit; tax treatment should improve a sound deal, not rescue a weak one.",
        "related": ["/tax-strategy/", "/blog/str-tax-documentation-audit/", "/partners/"],
    },
    "Exit & Portfolio": {
        "context": "An exit price depends on what a buyer can verify and retain. Reviews, permits, furnishings, operations, and historical revenue do not all transfer in the same way.",
        "action": "Build the exit file while operating: clean financials, permits, contracts, inventories, maintenance records, and a buyer-ready fallback model. Optionality is created before the listing date.",
        "related": ["/blog/str-exit-strategy/", "/blog/str-portfolio-diversification/", "/case-studies/"],
    },
}

ANGLE_NOTES = (
    "Start with sequence. Map what must be known before the offer, before the deposit becomes hard, before loan commitment, before closing, and before the first guest. An answer that arrives after its decision point has little practical value. Put calendar dates beside every dependency and leave room for a second review when the first response is incomplete.",
    "Treat reversibility as part of price. A condition that can be corrected with a known invoice is different from a right, approval, or operating capability that may never be available. Separate reversible cost from irreversible constraint, then reserve cash for the former and demand certainty on the latter before increasing exposure.",
    "Ask who benefits from the optimistic interpretation. Sellers, brokers, lenders, managers, and buyers can each use the same fact for a different purpose. Record the original source, the definition being used, and the period covered. Reconcile disagreements at the definition level before averaging numbers that do not measure the same thing.",
    "Test the handoff. Determine whether the answer survives a change in owner, manager, insurer, lender, platform account, or calendar year. If it is personal, temporary, or nontransferable, model the buyer obtaining it again. Transition friction belongs in both the opening timeline and the cash requirement.",
    "Measure concentration. One month, channel, vendor, permit, amenity, or favorable assumption should not silently carry the entire case. Remove the strongest contributor and rerun the decision. The result shows whether the issue is a manageable variable or a single point of failure that deserves a larger margin.",
    "Use evidence freshness. A document can be authentic and obsolete because a renewal, policy endorsement, ordinance change, vendor departure, or pricing shift occurred later. Write an as-of date beside the conclusion. Set a trigger for re-verification when the transaction timeline or operating plan moves beyond that date.",
    "Distinguish capacity from intent. A vendor may intend to serve the home but lack labor on turnover day; a lender may like the file but not the property type; a rule may allow a use but cap its scale. Verify both permission and practical capacity under the exact address, dates, and operating pattern.",
    "Reconcile the unit of analysis. Per stay, per occupied night, per available night, per month, and per year can produce plausible figures that are not comparable. Convert the source into the unit used by the model, preserve the conversion, and test the result against a second period before treating it as normalized.",
    "Price delay explicitly. A two-week slip can create extra interest, duplicate housing, missed peak demand, expiring quotes, or a different tax year. Identify which clock matters, calculate the carrying effect, and decide who controls the dependency. Time risk should appear as a number rather than an adjective.",
    "Define the exception path. The normal workflow may be inexpensive and reliable while the first unusual event is slow or costly. Ask what happens on a holiday, during severe weather, after a cancellation, or when the primary contact is unavailable. Fund and document the exception response before judging the system ready.",
)

# cluster, slug, question, direct answer, evidence, decision test, worked example, failure mode
TOPICS = [
 ("Contract & Offer","inspection-contingency-length-str","How Long Should an STR Inspection Contingency Be?","Long enough to inspect the building and verify the commercial use. In a permit-heavy or remote market, a standard residential window may expire before the decisive evidence arrives.","Inspector availability, permit response time, insurance quote timing, HOA documents, lender appraisal schedule, and the date earnest money becomes nonrefundable.","Count business days backward from the deposit deadline. Assign an owner and expected delivery date to each decision-critical item; the window is inadequate if any critical item lands after release.","An illustrative 10-day window looks ample until the cleaner, insurer, septic contractor, and zoning office each need a week. Extending to 15 days costs nothing if negotiated before acceptance.","Using the inspection deadline only for the physical inspection and discovering after release that the use, insurance, or vendor model does not work."),
 ("Contract & Offer","appraisal-gap-furnished-str","Should You Cover an Appraisal Gap on a Furnished STR?","Only when the unsupported amount is justified by transferable assets or a price you can defend without projected STR upside. Furniture and future bookings do not automatically become real-estate value.","Real-estate appraisal, itemized furniture bill of sale, replacement cost, transferable permits, reservation obligations, and the buyer's cash after closing.","Separate real estate, personal property, and goodwill. Cap the gap at the lowest amount that still leaves the required launch and emergency reserves intact.","A $30,000 gap may consume the same cash reserved for furnishing. If included furniture is worth only $12,000 used, the remaining $18,000 needs a different justification.","Calling projected revenue 'value' twice—once in the purchase premium and again in the buyer's return forecast."),
 ("Contract & Offer","seller-credit-str-furnishings","How Should a Seller Credit Affect an STR Furnishing Budget?","Treat a credit as a reduction in closing cash subject to lender limits, not as a substitute for a room-by-room furnishing scope.","Loan estimate, lender credit cap, contractor and furniture quotes, repair addendum, and closing statement treatment.","Model the credit under the lender's allowed-use rules. If unused credit disappears or forces a higher price, compare the net cash result with a direct price reduction.","A $15,000 credit can help with closing costs while the buyer still needs $45,000 after closing for furniture. The credit does not create $15,000 of furniture cash automatically.","Increasing the contract price to manufacture a credit without checking appraisal, lender limits, or the resulting debt service."),
 ("Contract & Offer","future-reservations-at-closing","What Happens to Future Airbnb Reservations When a Property Sells?","They require an explicit transition plan. Platform accounts, guest contracts, payouts, taxes, and refunds may remain with the seller even when the home transfers.","Reservation ledger, platform terms, guest contact plan, cancellation exposure, deposits, tax treatment, and closing-date occupancy.","Classify every stay as honored, moved, or cancelled; assign the revenue, expense, and liability for each outcome in writing before closing.","If six stays cross closing and the seller receives the payouts, the buyer can inherit turns and guest expectations without receiving the corresponding cash unless the settlement adjusts it.","Promising guests continuity before confirming platform rules, insurance, permits, possession, and who controls the listing."),
 ("Contract & Offer","str-furniture-bill-of-sale","What Belongs in an STR Furniture Bill of Sale?","A room-level inventory, ownership warranty, condition standard, exclusions, price allocation, and a delivery condition tied to the final walkthrough.","Photo inventory, serial numbers for major items, linens and smallwares count, leased items, warranties, and seller exclusions.","Walk the inventory against the bill of sale immediately before closing. Price missing or damaged items at realistic replacement cost, including delivery and setup.","A generic 'all furnishings included' clause does not resolve whether TVs, patio furniture, locked-owner supplies, art, linens, or smart devices remain.","Allocating a large value without tax or lender review, or accepting an inventory that does not support the advertised guest capacity."),
 ("Contract & Offer","permit-pending-due-diligence-extension","Should You Extend Due Diligence While an STR Permit Is Pending?","Usually when legal operation is material and the authority has not provided a reliable answer. The extension should be tied to a defined permit milestone, not open-ended hope.","Application receipt, completeness confirmation, agency timeline, cap or waitlist status, inspection requirements, and written seller cooperation.","Compare extension cost with the capital at risk if the permit fails. Require a termination right or fallback valuation rather than merely moving the calendar.","Paying $1,000 for a two-week extension may be rational when $100,000 of earnest money would otherwise become exposed before a cap decision.","Extending repeatedly without a decision rule, or treating application acceptance as permit approval."),
 ("Contract & Offer","earnest-money-release-str","When Is Early Earnest-Money Release Too Risky for an STR?","When unresolved use, insurance, condition, financing, or transfer questions could still kill the investment thesis. Early release converts negotiating leverage into seller liquidity.","Contingency status, title, permit and HOA verification, insurance binder, appraisal, lender conditions, and repair resolution.","List every remaining walk-away reason and its maximum loss. Release only the amount you can lose without pressure to close a newly defective deal.","A seller may request $25,000 early for relocation. If the permit transfer is still unconfirmed, that payment effectively prices the buyer's legal-use risk at $25,000.","Assuming released money remains practically recoverable because the contract says it should be returned."),
 ("Contract & Offer","buy-str-entity-or-assets","Should You Buy the STR Entity or Just the Property and Assets?","Asset purchases are often simpler, while entity purchases may carry contracts and liabilities. The correct structure depends on permit transfer, contracts, debt, taxes, and unknown obligations.","Entity financials, tax returns, debts, litigation, permits, contracts, payroll, platform accounts, and legal transfer restrictions.","Value each benefit that truly requires the entity, then compare it with the cost of legal, tax, and liability diligence plus indemnity risk.","If a permit is entity-held but a change of control terminates it, buying the LLC does not preserve the benefit and may import liabilities for no return.","Using an entity acquisition as a permit workaround without written confirmation from the issuing authority and transaction counsel."),
 ("Contract & Offer","certificate-of-occupancy-str-remodel","Do You Need a New Certificate of Occupancy After an STR Remodel?","Possibly, especially when bedrooms, egress, occupancy, use, or structural systems change. The answer comes from the local building authority for the actual scope.","Approved plans, permits, final inspections, existing certificate, proposed sleeping rooms, septic capacity, and fire requirements.","Map each revenue-driving change to its approval path before pricing it into capacity. Exclude any unapproved bedroom or amenity from the base case.","Converting a den into a fourth bedroom may add projected revenue, but if egress and septic capacity limit the home to three bedrooms, the projection is built on a use that cannot be marketed.","Letting listing language define legal bedroom count, or closing open permits without confirming the final inspection record."),
 ("Contract & Offer","closing-before-peak-season-str","Should You Rush an STR Closing Before Peak Season?","Only if the compressed schedule does not weaken diligence or produce a half-finished launch. Missing the first peak can hurt, but a defective purchase lasts longer than one season.","Closing calendar, furnishing lead times, permit timing, photography, vendor readiness, existing reservations, and realistic listing ramp.","Compare contribution from the recoverable peak nights with rush premiums, incomplete-work risk, and the cost of accepting unresolved deal issues.","Capturing four peak weekends might add illustrative gross revenue, but not if permits arrive afterward or rushed furniture creates refunds and poor first reviews.","Annualizing the best four weeks to justify skipping inspections, reserve funding, or a deliberate launch."),

 ("Revenue Evidence","reconcile-airbnb-payout-export","How Do You Reconcile an Airbnb Payout Export Before Buying?","Bridge each reservation from accommodation charges to fees, adjustments, taxes, refunds, and cash received. The result should tie to deposits, not merely the dashboard total.","Reservation export, transaction history, payout report, bank deposits, refunds, chargebacks, co-host splits, and tax remittances.","Create one row per reservation and one column per deduction. Investigate every unmatched payout and every deposit without a reservation group.","A dashboard can show $140,000 while bank receipts are $118,000 after fees, refunds, and withheld taxes. The buyer model must define which number it uses.","Mixing gross booking value with net cash in the same projection or accepting screenshots that omit cancelled stays."),
 ("Revenue Evidence","normalize-owner-blocks-str","How Should Owner-Blocked Nights Affect STR Occupancy?","Classify them by reason. Personal use, maintenance, and strategic closure each imply a different amount of recoverable demand.","Calendar export, owner-use log, maintenance history, minimum-stay rules, and inquiry or search-demand evidence for blocked dates.","Calculate occupancy on available nights, then separately estimate which blocked nights a buyer could responsibly reopen. Do not assume every block would have booked.","A home booked 180 of 250 available nights shows 72% available-night occupancy, but only 49% of the full year. Reopening 115 nights does not guarantee 72% on them.","Using available-night occupancy as annual occupancy without disclosing the denominator."),
 ("Revenue Evidence","cleaning-fees-gross-revenue","Do Cleaning Fees Count as STR Revenue When Buying?","They count only if the matching cleaning expense is treated consistently. Grossing up revenue while omitting the cleaner creates fictional margin.","Guest cleaning charges, cleaner invoices, laundry, restocking, management markups, and owner-paid shortfalls by stay.","Calculate cleaning contribution per turn: guest fee minus all turn costs. Model turns from stay length rather than as a flat revenue percentage.","A $225 guest fee against a $190 clean and $25 laundry contributes $10. At 80 turns, that is $800—not $18,000 of economic revenue.","Comparing properties on gross revenue when one passes cleaning through and another excludes it."),
 ("Revenue Evidence","combine-vrbo-direct-airbnb-revenue","How Do You Combine Airbnb, Vrbo, and Direct-Booking Revenue?","Normalize reservations to one stay ledger and remove duplicates created by channel managers or payment processors.","Platform exports, direct-booking PMS ledger, processor settlements, tax reports, cancellation records, and reservation IDs.","Match check-in, check-out, guest, and amount; tie net settlements to bank deposits; then separate channel mix from total property demand.","A direct reservation can appear in the PMS and Stripe report, while an Airbnb stay appears in the PMS and Airbnb export. Counting each source total doubles the same stays.","Adding dashboard totals without reservation-level deduplication or ignoring direct-booking chargeback exposure."),
 ("Revenue Evidence","str-refunds-chargebacks-underwriting","How Should Refunds and Chargebacks Change STR Underwriting?","Treat them as evidence about both net revenue and operating quality. Separate extraordinary events from recurring service failures, but do not erase either.","Refund log, resolution messages, chargebacks, damage claims, outage dates, review themes, and management response records.","Calculate refund dollars per booked stay and tag the cause. Carry recurring categories into the buyer case and create a repair plan for preventable causes.","Five refunds tied to an unreliable hot tub are not random. The normalized model should include either the historical leakage or the cost and downtime of replacement.","Adding refunds back as 'one time' without a documented change that prevents recurrence."),
 ("Revenue Evidence","future-booking-calendar-value","How Much Is a Future STR Booking Calendar Worth?","Only the transferable net contribution after cancellations, service costs, ownership transition, and platform rules. It is not equal to gross booked value.","Reservation terms, deposits, cancellation windows, payout timing, channel rules, cleaning and management costs, and transfer consent.","Value each booking at expected net contribution multiplied by a defensible probability it can be honored after closing.","A $40,000 future calendar with 25% operating costs and an 80% continuity probability has an illustrative risk-adjusted contribution of $24,000 before transition expense.","Paying dollar-for-dollar for bookings while the seller keeps deposits or the listing account cannot transfer."),
 ("Revenue Evidence","blocked-calendar-demand-signal","Can Blocked Nights Hide Weak STR Demand?","Yes. Blocking can make available-night occupancy look strong while hiding dates the operator chose not to expose because demand or economics were poor.","Full calendar history, reason codes for blocks, price changes, inquiries, stay restrictions, and comparable availability on the same dates.","Recalculate both available-night and full-calendar occupancy, then test the blocked dates against market demand rather than seller intent.","A 90% occupancy claim based on 120 available nights represents 108 booked nights—30% of the year. The unexposed calendar controls scalability.","Assuming operator preference and market demand are the same thing."),
 ("Revenue Evidence","new-listing-ramp-underwriting","How Should a New Listing Ramp Be Modeled in an STR Purchase?","Month by month, with lower conversion, introductory pricing, and review accumulation rather than immediate stabilized performance.","Comparable new-listing histories, photography and launch dates, promotional pricing, review pace, lead time, and season of launch.","Build a conservative ramp to stabilized rate and occupancy, then compare cash reserves with the cumulative shortfall during the ramp.","Launching 60 days before peak season is different from launching at its end. The same annual target can create opposite first-year cash needs.","Using a stabilized annual average from day one or treating review growth as automatic."),
 ("Revenue Evidence","discounts-coupons-net-adr","Do Airbnb Discounts Distort the Seller's Reported ADR?","They can. Reported rate metrics may be calculated before or after promotions, length-of-stay discounts, refunds, or fee allocation.","Reservation-level base rate, promotions, weekly and monthly discounts, refunds, taxes, fees, and booked nights.","Compute accommodation revenue after discounts divided by occupied nights. Compare that net ADR with the public rate calendar and comparable realized rates.","A displayed $350 rate with a 20% promotion realizes $280 before other adjustments. Underwriting at $350 overstates accommodation revenue by $70 per night.","Using public asking rates as achieved ADR or comparing metrics calculated on different bases."),
 ("Revenue Evidence","seller-proforma-vs-trailing-revenue","When Can a Seller Pro Forma Outweigh Trailing STR Revenue?","Rarely, and only when a specific, evidenced change makes history less representative—such as added legal capacity, completed downtime, or a documented management failure that the buyer can correct.","Trailing ledger, change timeline, permits, renovation completion, comparable set, pricing history, and buyer operating plan.","Start with actuals, isolate the changed driver, and credit only the improvement supported by market evidence after costs and ramp time.","If a legal fourth bedroom opens after renovation, model its supported rate lift. Do not replace the entire trailing year with the seller's best-case pro forma.","Treating every underperforming property as easy upside while paying the price of a stabilized asset."),

 ("Operating Economics","normalize-str-utility-bills","How Do You Normalize Utility Bills for an STR Purchase?","Use at least one seasonal cycle, separate occupancy effects from weather and equipment, and adjust for buyer-paid services the seller omitted.","Monthly electric, gas, water, internet, propane, pool or hot-tub energy, occupancy, weather notes, and rate changes.","Model a monthly base load plus occupied-night and seasonal components. Stress the highest-use quarter rather than applying one annual percentage.","A $450 annual average can conceal $900 winter propane months. Cash reserves need the monthly pattern even when the annual total is correct.","Using a seller's partial bills, ignoring vacant-period consumption, or assuming efficient equipment without inspection."),
 ("Operating Economics","hot-tub-replacement-reserve","How Much Should an STR Reserve for Hot-Tub Replacement?","Base the reserve on installed replacement cost, remaining useful life, repair history, and the revenue exposure of downtime—not a universal percentage.","Model and age, service invoices, cover and electrical condition, water-care contract, replacement quote, access constraints, and booking dependence.","Divide replacement cost by conservative remaining years, then add a downtime allowance if the amenity is central to demand.","An $11,000 installed replacement with four remaining years implies $2,750 annually before repairs. Remote crane access can change the number materially.","Budgeting only chemicals and service while treating the vessel, cover, pump, and heater as permanent."),
 ("Operating Economics","pool-heating-cost-underwriting","How Do You Underwrite Pool-Heating Cost and Guest Fees?","Model energy by season and temperature, then compare optional-fee recovery with guest behavior and operational complexity.","Fuel or electric bills, heater type and efficiency, pool volume, local weather, fee collections, refund disputes, and maintenance history.","Calculate net heating contribution by month: fees collected minus energy, wear, and support. Test a case where guests decline the fee but the pool still needs baseline service.","A $60 daily fee on ten heated stays may look profitable until cold-month gas bills, warm-up days, and refunds are included.","Assuming every winter booking buys heat or marketing a usable pool when the operating policy makes it impractical."),
 ("Operating Economics","snow-removal-cost-str","How Should Snow Removal Be Budgeted for a Mountain STR?","Separate scheduled access, per-storm work, emergency callouts, roof or deck loads, and guest-arrival timing.","Vendor contract, trigger depth, historical storm count, driveway length and grade, municipal plowing, deicing, backup vendor, and response SLA.","Price a normal winter and a severe winter; require arrival-day clearance within the vendor's promised window.","A low seasonal contract may exclude same-day re-plows. Two peak-weekend callouts can erase the apparent savings and create guest refunds.","Treating snow removal as landscaping or relying on a single operator during regional storms."),
 ("Operating Economics","coastal-corrosion-capex-str","How Should Coastal Corrosion Change an STR Capex Budget?","Shorten replacement assumptions for exposed metal, HVAC, railings, fasteners, electronics, and exterior finishes, using local inspection evidence.","Distance and exposure, HVAC coil condition, railings, fasteners, windows, appliances, maintenance logs, and coastal contractor quotes.","Create a coastal exposure register and assign inspection frequency, mitigation cost, and replacement timing to each vulnerable system.","An outdoor condenser that might last 12 years inland may show material corrosion much earlier near salt air; the reserve should follow observed condition, not a national average.","Underwriting beach revenue while using inland maintenance assumptions."),
 ("Operating Economics","linen-par-level-cost","How Many Linen Sets Does an STR Need in the Purchase Budget?","Enough for the beds, turnover timing, laundry method, damage buffer, and owner storage—not simply two sets per bed.","Bed and bath count, sleeper-sofa use, laundry location, same-day turn schedule, cleaner process, loss history, and storage capacity.","Calculate in-use, in-laundry, ready, and damaged stock separately. Price the par level at actual commercial-quality replacement cost.","A ten-guest home with offsite laundry may need three complete turns of inventory. Buying one spare set creates emergency purchases and missed inspections.","Counting decorative bedding as operational linen or failing to budget protectors, towels, kitchen textiles, and locked storage."),
 ("Operating Economics","furniture-replacement-cycle-str","How Do You Build an STR Furniture Replacement Schedule?","Inventory items by guest exposure and revenue importance, then assign inspection and replacement triggers rather than one average life.","Room inventory, purchase dates, warranties, repair history, review comments, photo relevance, and replacement lead times.","Fund annual reserves from the next 36 months of likely replacements, weighted toward beds, seating, dining, and signature listing pieces.","If the sofa and eight dining chairs are all five years old, a flat $2,000 reserve may be inadequate even if the average furniture age looks acceptable.","Replacing only when something breaks on a guest, or refreshing decor while postponing mattresses and seating."),
 ("Operating Economics","str-consumables-cost-per-stay","How Should STR Consumables Be Modeled per Stay?","Build a per-turn kit by guest capacity and average stay, then add subscription, storage, waste, and emergency restocking costs.","Cleaner restock sheets, purchase receipts, guest count, stay length, coffee and toiletries policy, damage and theft, and delivery fees.","Calculate cost per occupied night and per turn. Use the higher driver for each item rather than one percentage of revenue.","Coffee follows occupied mornings while dishwasher pods often follow turns. Modeling both the same way misprices short stays.","Stocking to the maximum guest count on every two-night reservation without measuring use, or relying on cleaner out-of-pocket purchases."),
 ("Operating Economics","trash-service-large-group-str","What Does Trash Service Really Cost for a Large-Group STR?","Include base pickup, overflow, can handling, holiday timing, wildlife control, violations, and emergency hauls.","Pickup contract, can capacity, guest count, local set-out rules, holiday schedule, HOA fines, wildlife requirements, and manager labor.","Map waste volume to guest nights and departure days. Price the peak turnover week, not an average household bill.","A 14-person holiday stay can produce more waste than one residential cart holds. One emergency haul and HOA fine can exceed a month of service.","Assuming municipal service matches commercial guest volume or leaving can movement unassigned."),
 ("Operating Economics","septic-pumping-occupancy-cost","How Should Septic Capacity and Pumping Affect STR Economics?","Legal bedroom capacity and actual guest load should drive inspections, pumping frequency, reserve, and listing occupancy.","Permit capacity, tank and field size, inspection, pump records, occupancy, laundry volume, disposal use, and repair estimate.","Underwrite to the lower of legal and physical capacity, then model preventive pumping and a drain-field reserve.","Advertising 12 guests in a system approved for three bedrooms can raise failure risk and may violate the operating approval even when the house sleeps 12.","Using bed count as septic capacity or treating pump-outs as proof the drain field is healthy."),

 ("Financing & Closing","dscr-vacancy-factor-str","How Does a DSCR Lender Treat STR Vacancy?","Policies differ: some use appraiser revenue, some haircuts, some long-term rent, and some operating history. The lender's ratio may not match the owner's downside case.","Term sheet, qualifying revenue source, vacancy or expense factor, debt service, reserve requirements, appraisal instructions, and recourse terms.","Recalculate DSCR using both lender inputs and a buyer downside case. The lower result controls the owner's risk decision.","A loan may qualify at 1.20 DSCR using a market revenue estimate while the buyer case falls below 1.0 after realistic expenses.","Treating loan approval as independent validation of revenue."),
 ("Financing & Closing","str-appraisal-income-approach","Will an Appraiser Give Value to Short-Term-Rental Income?","Sometimes, but many residential appraisals rely primarily on comparable sales and may use long-term rent or limited STR evidence.","Lender appraisal scope, comparable sales, 1007 rent schedule, legal-use evidence, trailing statements, and furniture treatment.","Underwrite the transaction to the likely real-estate appraisal and keep business or furniture value separate.","Paying a $75,000 premium for STR income can create a matching appraisal gap if recent sales do not support the contract price.","Assuming an AirDNA report will be capitalized directly into residential value."),
 ("Financing & Closing","second-home-loan-rental-intent","Can You Use a Second-Home Loan for a Property You Plan to Rent?","Only when the real occupancy and property facts satisfy the lender's current second-home rules. Rental intent cannot be disguised.","Written lender guidelines, occupancy certification, distance and use, management restrictions, rental plan, and property type.","Describe the planned use accurately and obtain written product fit. Compare payment savings with the constraints and risk of an occupancy misrepresentation.","A lower down payment is not a benefit if the owner's actual plan requires full-time rental management that the product prohibits.","Choosing the loan based on rate before disclosing the intended rental pattern."),
 ("Financing & Closing","str-lender-reserve-requirements","How Do Lender Reserve Requirements Change STR Cash Needed?","Required reserves are additional verified liquidity and may not be spendable furnishing money, even when counted toward qualification.","Months required, eligible account types, seasoning, retirement-account haircut, post-closing verification, and other financed properties.","Add lender reserves to the sources-and-uses schedule as restricted liquidity, then separately fund launch and emergency cash.","Six months of a $5,000 payment is $30,000. Counting that same $30,000 as furniture cash creates a closing shortfall.","Using one dollar for down payment, reserves, furnishing, and emergency buffer in different parts of the model."),
 ("Financing & Closing","rate-buydown-str-investment","Is a Mortgage Rate Buydown Worth It on an STR?","Compare upfront points with monthly payment savings over the expected loan life, then stress refinance and sale timing.","Loan quotes with and without points, payment difference, breakeven month, expected hold, refinance costs, and liquidity needs.","Divide points by monthly savings and compare the breakeven with a conservative hold period. Keep launch reserves senior to a distant breakeven.","Paying $12,000 to save $250 monthly breaks even in 48 months before considering the time value of money. A planned refinance in two years makes it weak.","Choosing the lowest rate while starving furniture, repairs, or reserves."),
 ("Financing & Closing","delayed-financing-cash-str","How Does Delayed Financing Work After an All-Cash STR Purchase?","It may return capital after closing, but the amount, timing, documentation, seasoning, and tax treatment require lender and adviser confirmation.","Source of purchase funds, closing statement, appraisal, lender program, eligible improvements, title, entity ownership, and reserve plan.","Model the acquisition as cash through the longest plausible financing delay. Do not commit returned capital before proceeds fund.","A buyer expecting 75% back in 30 days can face a lower appraisal or documentation delay. The property must remain viable if proceeds are smaller and later.","Treating delayed financing as guaranteed cash at closing."),
 ("Financing & Closing","bank-statement-loan-str","When Does a Bank-Statement Loan Make Sense for an STR Buyer?","When documented cash flow supports qualification better than tax-return income and the higher cost still leaves a sound property case.","Deposit calculation, excluded transfers, business expense factor, rate and points, prepayment penalty, reserves, and property underwriting.","Compare all-in cash, payment, and prepayment cost with DSCR and conventional alternatives under the same property downside case.","A loan that solves qualification can still reduce annual cash flow enough to fail the acquisition target.","Focusing on approval while ignoring points, penalty, adjustable terms, or how deposits are normalized."),
 ("Financing & Closing","gift-funds-str-down-payment","Can Gift Funds Be Used for an STR Down Payment?","Product rules differ, and investment-property programs may limit gifts. The donor, transfer trail, seasoning, and retained reserves matter.","Program guideline, gift letter, donor bank statement, transfer proof, relationship requirement, borrower contribution, and reserve rule.","Confirm eligibility before accepting funds and trace them exactly as the lender requires. Model the gift separately from repayable family debt.","A family transfer labeled a gift but expected to be repaid can create both underwriting and relationship problems.","Moving funds early without documentation or treating a loan as a gift."),
 ("Financing & Closing","seller-financing-balloon-str","How Do You Stress-Test Seller Financing with a Balloon Payment?","Model the balloon as a known maturity risk, not a future refinance assumption. The exit has to work under lower value, higher rate, and weaker income.","Note terms, amortization, balloon date, extension rights, prepayment, lien position, refinance requirements, and fallback sale timeline.","Calculate balance at maturity and test refinance proceeds under a conservative appraisal and DSCR. Start the refinance or sale clock well before maturity.","A five-year balloon can be manageable until a market correction and rate increase leave proceeds below the remaining balance.","Using current lender terms as the five-year refinance case or assuming the seller will extend."),
 ("Financing & Closing","refinance-after-str-stabilization","When Can an STR Refinance After It Stabilizes?","When lender seasoning, appraisal, revenue documentation, legal use, and borrower qualification align. Stabilized operations alone do not guarantee proceeds.","Title seasoning, trailing statements, tax returns if required, appraisal method, DSCR policy, permit, furniture value, and prepayment penalty.","Project proceeds under conservative value and lender revenue treatment, net of closing costs and the existing payoff.","Twelve months of strong bookings can help one lender while another still uses long-term rent. The same property can produce very different proceeds.","Counting refinance cash in the acquisition return before confirming a viable product and seasoning path."),

 ("Insurance & Hazard","wind-deductible-str-reserve","How Should a Wind Deductible Be Modeled for a Coastal STR?","As a separate liquidity requirement based on the policy's percentage and insured value, plus business-interruption exposure.","Wind deductible basis, dwelling limit, named-storm terms, roof settlement, flood policy, reserve balance, and access after a storm.","Calculate the maximum wind deductible in dollars and add realistic uninsured downtime. Keep that liquidity outside routine operating reserves.","A 2% deductible on $800,000 of coverage is $16,000 before lost bookings or excluded exterior items.","Reading 2% as two percent of the repair bill rather than the insured-value basis."),
 ("Insurance & Hazard","flood-zone-str-underwriting","How Should Flood-Zone Risk Change an STR Offer?","Use parcel-specific flood information, elevation, policy terms, access risk, and downtime—not the zone label alone.","Official map, elevation certificate, prior claims, flood quote, building and contents limits, access route, utilities, and mitigation.","Price annual premium, deductible, excluded contents, and an event-driven closure into the downside case. Make missing elevation evidence a diligence item.","A building can avoid structural damage while road access, pool systems, or ground-floor contents still create cancellations and uninsured cost.","Assuming lender-required coverage makes the owner economically whole."),
 ("Insurance & Hazard","wildfire-insurability-str","How Do You Check Wildfire Insurability Before Buying an STR?","Get property-specific carrier appetite, mitigation requirements, deductible, nonrenewal risk, and backup-market pricing before commitment.","Vegetation and defensible space, roof and siding, access, hydrants or water, inspection, carrier quotes, FAIR-plan availability, and evacuation exposure.","Underwrite the bindable quote and a renewal-stress case. Assign mitigation work and completion timing before launch.","A cabin can qualify today only after brush clearance and roof repair. Those costs and launch delay belong in total entry cost.","Using the seller's premium as proof the buyer can obtain equivalent coverage."),
 ("Insurance & Hazard","pool-slide-liability-str","Should an STR Keep a Pool Slide or Diving Board?","Only after insurer acceptance, code verification, inspection, depth and signage review, and a clear guest-safety decision.","Policy exclusions, local code, pool dimensions, equipment condition, fencing, lighting, rules, claims history, and removal quote.","Compare verified guest value with premium, exclusion, inspection, maintenance, and severity risk. Remove it if the risk cannot be transferred or controlled.","An amenity that adds little booking value can create a policy exclusion that affects the entire pool claim.","Keeping equipment because it appears in seller photos without insurer and code review."),
 ("Insurance & Hazard","dock-watercraft-str-liability","How Should a Dock or Guest Watercraft Affect STR Insurance?","Treat the dock, water access, and any provided craft as separate hazards with their own property, liability, maintenance, and use rules.","Dock permit, inspection, water depth, electrical system, railings, watercraft title, life jackets, insurer approval, and guest rules.","Model removal or restricted use as the fallback. Count revenue benefit only if the amenity can be legally and safely offered.","Providing kayaks may seem inexpensive until storage, damage, life-safety equipment, and excluded watercraft liability are included.","Assuming general premises liability automatically covers boats, docks, or swimming access."),
 ("Insurance & Hazard","roof-age-str-policy-binding","Can an Old Roof Prevent STR Insurance Binding?","Yes. Carriers may restrict roof age, settlement method, wind coverage, or require replacement even when the roof is not leaking.","Roof age and permit, material, inspection, remaining life, repair history, carrier underwriting, replacement quote, and closing timeline.","Obtain carrier acceptance before contingency release and price replacement under both seller-credit and buyer-funded cases.","A roof with five functional years can still be uninsurable under a carrier's age rule, turning a future capex item into a closing requirement.","Relying on a general home inspection instead of the insurer's underwriting standard."),
 ("Insurance & Hazard","vacant-renovation-str-coverage","What Insurance Covers an STR During Renovation Before Launch?","A standard occupied-home or active STR policy may not cover extended vacancy or material renovation. Coverage must match the pre-launch condition.","Renovation scope, vacancy duration, contractor insurance, builder's risk need, theft, water, liability, material storage, and intended conversion date.","Map coverage phases from closing through construction and first guest. Require proof before work or possession begins.","A 60-day furnishing job can become a four-month renovation after water damage. A policy written for immediate occupancy may not respond as expected.","Buying the future operating policy and assuming it covers construction, vacancy, and contractor-caused loss."),
 ("Insurance & Hazard","lost-rental-income-limit-str","How Much Lost-Rental-Income Coverage Does an STR Need?","Enough for the realistic restoration period and seasonal revenue pattern, subject to the policy's calculation method and exclusions.","Coverage limit and period, waiting period, actual-loss method, historical revenue, seasonality, permit delay, rebuilding time, and extra expense.","Model a loss just before peak season and a longer permitting delay. Compare the policy limit with gross margin, not gross revenue alone.","Six months of annual-average revenue can materially understate a closure spanning the highest-revenue quarter.","Assuming every cancellation after a covered loss is reimbursed or that projected revenue is automatically accepted."),
 ("Insurance & Hazard","commercial-umbrella-str","When Does an STR Owner Need an Umbrella Policy?","When the owner's asset exposure and severity risks exceed comfortable primary limits, subject to an adviser and insurer reviewing the actual ownership and operations.","Primary policy limits, entity and named insured, pool or water hazards, vehicles, employees or contractors, umbrella exclusions, and personal assets.","Check whether the umbrella sits above the correct STR policy and ownership entity. More nominal limit is not useful when the underlying activity is excluded.","A personal umbrella may not attach to an LLC-owned commercial rental unless structured and endorsed correctly.","Buying a large limit without confirming the STR and entity are scheduled underlying risks."),
 ("Insurance & Hazard","security-camera-privacy-str","How Should Exterior Cameras Be Handled at an STR?","Use only permitted exterior locations, disclose them accurately, minimize recording, secure access, and align platform, law, and insurer requirements.","Current platform policy, local privacy and audio law, camera field of view, disclosure, retention, account access, and vendor permissions.","Document each device, purpose, view, settings, and disclosure. Remove any device whose compliance or guest value cannot be defended.","A doorbell camera aimed at entry may be appropriate while a device capturing a private outdoor amenity can create a serious privacy breach.","Copying seller disclosures after device locations or platform rules change."),

 ("Rules & Permits","parcel-jurisdiction-str","How Do You Confirm Which STR Rules Apply to a Parcel?","Verify parcel and municipal boundaries, zoning, overlays, HOA or deed restrictions, and the issuing authority. Mailing city is not jurisdiction.","Parcel ID, GIS map, zoning designation, municipal boundary, county rules, overlay maps, HOA documents, and written agency response.","Create a one-page jurisdiction stack from public layers to private restrictions and date every source.","Two homes with the same city mailing address can sit on opposite sides of an incorporated boundary and follow different ordinances.","Searching the postal city and stopping at the first rule summary."),
 ("Rules & Permits","nonconforming-str-use-sale","Does a Legal Nonconforming STR Survive a Property Sale?","Only if the ordinance protects the use through the specific ownership transfer and continued-operation conditions.","Original approval, nonconforming-use section, transfer rule, lapse period, violation history, business entity, and written official confirmation.","Test sale, entity change, downtime, renovation, and permit-renewal events separately. Any one may terminate the status.","A property can be legal for the seller but lose protection after 12 months of nonuse or a deed transfer.","Calling a use 'grandfathered' without identifying the ordinance provision and termination events."),
 ("Rules & Permits","str-density-cap-waitlist","How Should an STR Permit Cap or Waitlist Affect an Offer?","Assume no permit until the buyer has a qualifying position and a reliable issuance path. A waitlist is not a transferable license.","Cap count, queue rules, application timing, transferability, lottery, attrition, parcel eligibility, and fallback use.","Value the property under the allowed fallback and treat permit upside as contingent unless the contract protects issuance.","Being number 12 on a list means little without historical issuance pace and rules that preserve the place after closing.","Paying permitted-property pricing for an application opportunity."),
 ("Rules & Permits","primary-residence-str-rule","Can You Buy an STR Where a Primary-Residence Rule Applies?","Only if the owner and operating plan genuinely meet the rule. A nominal address, relative, or entity does not replace actual eligibility.","Residency definition, proof documents, nights allowed, owner absence, entity restrictions, enforcement, and renewal.","Map the owner's actual living pattern to each requirement and obtain local legal guidance before assuming compliance.","A rule requiring the host's principal residence for most of the year may allow occasional hosting but not an investor-operated whole-home rental.","Designing ownership paperwork to appear compliant while the facts are not."),
 ("Rules & Permits","minimum-night-rule-str-economics","How Does a Minimum-Night Rule Change STR Economics?","It changes the guest segment, booking window, turns, occupancy pattern, and sometimes whether the activity is short-term at all.","Required minimum, seasonal exceptions, existing stay-length distribution, monthly demand, utilities, cleaning, and platform setup.","Rebuild the model with compliant stay lengths and realistic monthly demand; do not scale the nightly model by fewer turns.","A 30-night minimum is not a nightly rental with lower cleaning cost. It competes with furnished monthly housing and may realize a different rate.","Keeping nightly ADR while applying the legal minimum stay."),
 ("Rules & Permits","parking-occupancy-str-cap","How Should Parking Limits Set STR Guest Capacity?","Legal occupancy, bedroom count, septic capacity, parking, and fire rules create a capacity ceiling; marketable beds do not override it.","Ordinance, site plan, space dimensions, street-parking rule, HOA, bedroom approval, septic permit, and fire inspection.","Use the lowest binding capacity in revenue and furniture plans. Price any site work before assuming another vehicle or bedroom.","A five-bedroom home may physically sleep 14 but be limited to eight guests by parking or septic approval.","Furnishing to maximum beds before verifying the legal and practical arrival plan."),
 ("Rules & Permits","str-fire-inspection-closing","What Should an STR Fire Inspection Cover Before Closing?","Verify the local checklist and inspect the systems that control legal capacity and life safety before finalizing the launch plan.","Egress, alarms, extinguishers, address visibility, emergency lighting, railings, occupancy posting, fireplace, sprinkler or hood requirements, and reinspection timeline.","Price each correction and assign whether seller, buyer, or operating vendor completes it before the first guest.","A basement bunk room may fail egress, reducing capacity and invalidating the rate model until corrected.","Treating a general home inspection as the local STR fire inspection."),
 ("Rules & Permits","lodging-tax-registration-before-launch","When Should Lodging-Tax Registration Happen for a New STR?","Before accepting taxable stays when required, coordinated across state, county, city, and platform collection rules.","Registration thresholds, account numbers, platform collection scope, direct-booking obligations, filing frequency, and permit dependencies.","Build a responsibility matrix by jurisdiction and channel. Confirm who collects, who files, and who reconciles zero or direct returns.","A platform may remit one state tax while the owner remains responsible for a city assessment and periodic return.","Assuming 'taxes collected by platform' eliminates registration and filing obligations."),
 ("Rules & Permits","str-complaint-permit-revocation","Can Neighbor Complaints Put an STR Permit at Risk?","Yes where ordinances use escalating warnings, fines, local-contact failures, or nuisance findings. The actual revocation path must be read.","Complaint history, ordinance penalty ladder, local-contact requirement, noise and parking records, prior notices, and appeal rights.","Map each violation threshold and build an operating control for the behavior that triggers it.","Two unresolved parking complaints may matter more than dozens of five-star reviews if the permit ladder escalates on the third.","Checking whether a permit is active without checking open violations or renewal eligibility."),
 ("Rules & Permits","str-license-renewal-calendar","How Do You Audit an STR License Renewal Calendar Before Buying?","List every license, tax account, inspection, insurance certificate, responsible-agent filing, and renewal condition with its owner and deadline.","Current permits, issue and expiration dates, renewal forms, inspection cadence, fee status, violations, and transfer rules.","Build a 13-month calendar and confirm which dates reset at sale. Put first renewals into the acquisition transition plan.","Closing two weeks before an annual renewal can require immediate inspection and fees before the buyer's operations are ready.","Treating an active license as durable permission without checking expiration and renewal conditions."),

 ("Vendor Operations","cleaner-capacity-peak-season","How Do You Verify a Cleaner Can Handle STR Peak Season?","Test actual same-day capacity, staffing, laundry, inspection, geographic route, and backup—not the number of properties claimed.","Peak turnover calendar, crew count, service area, laundry method, quality checklist, issue response, references, and backup plan.","Give the vendor a sample peak Saturday and ask for named crews, sequence, travel, and escalation. Reject a plan that depends on perfect timing.","Eight turns across a mountain county can exceed two crews even when average monthly volume looks easy.","Signing on price and availability without testing the hardest turnover day."),
 ("Vendor Operations","backup-cleaner-str","What Makes an STR Backup Cleaner Real?","A real backup has accepted rates, property access, linens, checklist, insurance, contact protocol, and periodic familiarity with the home.","Signed rate, onboarding date, access permissions, photos, supply location, quality standard, and activation rules.","Schedule a paid shadow or independent turnover before launch and refresh access quarterly.","A cleaner who once said 'call me anytime' but has never entered the property is a lead, not a backup.","Listing three phone numbers as redundancy without contracted capacity."),
 ("Vendor Operations","same-day-turn-time-budget","How Much Time Does a Same-Day STR Turnover Need?","Base it on beds, baths, laundry, amenities, inspection, restocking, maintenance buffer, and travel—not a generic four-hour window.","Task timing, team size, laundry cycles, hot tub or pool service, check-out and check-in times, and defect frequency.","Build a critical path and include a repair buffer before guest arrival. Change stay rules or staffing when the path has no slack.","A six-bedroom reset may require 18 labor-hours. Three people have only six clock-hours before considering travel or repairs.","Compressing check-in time after launch without changing crew or scope."),
 ("Vendor Operations","str-maintenance-response-sla","What Response Times Belong in an STR Maintenance SLA?","Tie response to guest and property severity: acknowledge, diagnose, attend, contain, and resolve are different clocks.","Issue categories, acknowledgment time, dispatch time, parts and after-hours terms, authority limit, documentation, and backup vendor.","Run the SLA against lockout, no heat, active leak, appliance failure, and cosmetic issue. Each needs a named path.","A vendor can answer in ten minutes yet arrive the next day. The SLA should measure the arrival that protects the stay.","Using one response-time promise for every issue or failing to authorize emergency spend."),
 ("Vendor Operations","after-hours-guest-support-cost","How Should After-Hours Guest Support Be Staffed and Priced?","Model message coverage, phone escalation, decision authority, handoff, language, and incident volume—not just a monthly subscription.","Coverage hours, response metrics, escalation tree, access to property data, per-incident charges, refunds authority, and QA.","Test three overnight scenarios and price expected incidents plus one severe month. Compare in-house, co-host, and service options.","A low base fee with high per-call charges can exceed a co-host during peak season and still lack local dispatch.","Buying messaging coverage without a physical-response partner."),
 ("Vendor Operations","vendor-smart-lock-access","How Should Vendors Access an STR Without Sharing Master Codes?","Use named, time-limited credentials with logs, revocation, and an offline emergency path.","Lock capability, unique users, schedules, audit logs, battery plan, Wi-Fi failure, key backup, and vendor offboarding.","Assign role-based codes and test access during an internet outage. Review active users monthly.","A cleaner code shared across staff cannot identify access or be revoked from one former worker.","Using the guest-code pattern for vendors or storing the physical backup where guests can find it."),
 ("Vendor Operations","owner-closet-inventory-control","How Do You Control an STR Owner Closet and Supply Inventory?","Separate guest, turnover, maintenance, and personal stock; define counts, access, reorder points, and reconciliation.","Storage map, lock access, par levels, issue log, purchase authority, receipts, and monthly count.","Set minimum and target quantities for high-failure items and assign one person to reconcile purchases with counts.","Bulk supplies do not save money when four vendors use the same closet without accountability.","Locking every supply away so guests and emergency vendors cannot solve simple problems."),
 ("Vendor Operations","offsite-laundry-str","When Does Offsite Laundry Make Sense for an STR?","When quality, inventory, transport, turnaround, and peak capacity outperform onsite cycles at a defensible total cost.","Per-pound or per-piece rate, pickup schedule, loss charges, par requirement, stain policy, peak cutoff, transport, and backup.","Compare cost per turn including inventory capital and emergency runs. Test the busiest turnover day.","Offsite laundry can shorten cleans but require a third linen set and delivery buffer, shifting rather than eliminating cost.","Comparing vendor price only with detergent while ignoring labor and linen inventory."),
 ("Vendor Operations","str-trash-day-operations","Who Should Move STR Trash Cans and Verify Pickup?","Assign a paid role with timing, photo confirmation, holiday rules, overflow, and recovery after missed pickup.","Pickup schedule, HOA and municipal rules, arrival calendar, vendor route, container capacity, wildlife, and fines.","Connect the trash task to departures and holidays; require exception reporting before the next check-in.","A can placed out one day late can remain full through the next guest stay in a weekly-service market.","Leaving trash to guests or assuming cleaners visit on non-turn pickup days."),
 ("Vendor Operations","str-pest-control-response","What Should an STR Pest-Control Plan Include?","Preventive service, pest-specific escalation, guest communication, evidence handling, emergency access, and follow-up inspection.","Service scope, frequency, exclusions, wildlife provider, bed-bug protocol, response time, treatment downtime, and documentation.","Run separate plans for routine insects, rodents, wildlife, and suspected bed bugs because severity and closure differ.","A quarterly spray contract may exclude rodents and provide no same-day response to a guest report.","Promising immediate resolution without knowing treatment, reentry, or refund implications."),

 ("Pricing & Calendar","str-booking-window-season","How Should Booking Window Change STR Pricing by Season?","Use lead-time curves by stay date and guest segment. Peak dates can justify patience while soft dates may need earlier conversion work.","Booking date, stay date, rate, occupancy, cancellation, event calendar, channel, and comparable availability.","For each season, compare current pickup with prior pace at the same days-before-arrival; change price only when pace and market position justify it.","Being 20% occupied 90 days out can be healthy for a market that books in the final month and dangerous for a holiday week that books six months ahead.","Applying one last-minute discount rule across every season."),
 ("Pricing & Calendar","orphan-night-pricing-str","How Should You Price a One-Night Gap Between STR Bookings?","Price and restrict it based on incremental contribution, turn feasibility, and whether filling it blocks a more valuable stay pattern.","Gap length, cleaning economics, minimum stay, arrival rules, lead time, staff capacity, and adjacent reservation value.","Calculate incremental revenue minus platform, turn shortfall, utilities, support, and displacement. Open only when contribution and operations are positive.","A $220 orphan night with a $180 unrecovered clean and $35 variable cost contributes almost nothing before risk.","Discounting every gap because empty nights feel wasteful."),
 ("Pricing & Calendar","minimum-stay-peak-dates","When Should an STR Require Longer Minimum Stays on Peak Dates?","When the longer stay protects scarce arrival dates and raises contribution without pricing the listing out of the actual trip pattern.","Historical stay length, inquiry loss, check-in day, event dates, turn capacity, comparable rules, and contribution.","Test minimum-stay combinations against calendar fragmentation and net revenue, then relax rules by a planned lead-time schedule.","A three-night event weekend may be correct while a seven-night rule leaves the peak empty because guests travel Thursday through Sunday.","Copying competitors' visible rules without knowing whether they convert."),
 ("Pricing & Calendar","gap-night-rule-str","How Do Gap-Night Rules Prevent Calendar Fragmentation?","They block reservations that strand unusable nights, but overly rigid rules can reject profitable demand.","Minimum stay, adjacent openings, arrival patterns, lead time, booking value, and cleaning capacity.","Measure stranded-night cost before and after the rule; create exceptions when the gap can still sell or contribution is high.","Accepting a two-night stay can strand one Saturday in a market where one-night bookings are operationally impossible.","Using a blanket no-gap rule that rejects long, high-value stays."),
 ("Pricing & Calendar","event-calendar-str-pricing","How Do You Build an STR Event Calendar Without Overpricing?","Track demand-changing events, venue distance, historical compression, comparable availability, and booking pace; an event name alone is not pricing power.","Official dates, attendance history, venue, travel pattern, prior pickup, comparable sellout, cancellation, and minimum stays.","Assign evidence tiers and price premiums accordingly. Remove speculative premiums when pickup fails by a defined lead time.","A citywide convention may compress the market; a local festival across town may not affect the property's guest segment.","Loading every event at double rate and reacting too late when the calendar remains empty."),
 ("Pricing & Calendar","last-minute-discount-str","How Large Should an STR Last-Minute Discount Be?","Large enough to improve contribution-positive conversion, not so large that it attracts operationally expensive demand or trains repeat guests to wait.","Days to arrival, current pace, variable cost, channel fee, turn cost, stay length, comparable rates, and cancellation risk.","Set a contribution floor and staged discounts by lead time; measure incremental bookings against the prior rule.","A 25% discount on a two-night stay may fall below the turn-adjusted floor while the same discount on five nights remains profitable.","Optimizing occupancy without a minimum contribution threshold."),
 ("Pricing & Calendar","weekly-discount-str-math","How Do You Calculate an STR Weekly Discount?","Compare the rate reduction with saved turns, lower vacancy between stays, channel economics, and the guest segment attracted.","Nightly rate, typical stay, turn cost, variable cost, vacancy pattern, cancellation, and weekly demand.","Calculate contribution for one seven-night stay versus likely shorter stays plus gap risk; set the discount below the economic savings.","A 10% weekly discount can improve contribution when it avoids two cleans, but destroy it in a sold-out peak week.","Setting the same weekly discount year-round."),
 ("Pricing & Calendar","shoulder-season-str-strategy","How Should an STR Change for Shoulder Season?","Change the offer, calendar, and operating cost to the actual shoulder guest rather than simply discounting the peak-season listing.","Guest origin, trip purpose, stay length, weekday demand, weather, amenity availability, utilities, and comparable messaging.","Define a shoulder segment, package only real value, and compare contribution after discounts and seasonal operating costs.","Remote-work stays may support longer bookings, but only when internet, workspace, and midweek pricing match the promise.","Keeping peak minimum stays and copy while cutting price broadly."),
 ("Pricing & Calendar","weather-cancellation-pricing-str","How Should Weather Risk Affect STR Pricing and Cancellation Rules?","Align policy, insurance options, guest communication, and rate premium with the severity and predictability of local travel disruption.","Platform policy, road access, historical closures, travel insurance, refundable-rate option, owner coverage, and communication templates.","Price flexible and firm options from expected cancellation cost, then disclose access realities before booking.","A mountain home can command winter rates while also carrying storm-driven cancellations; ignoring one side overstates contribution.","Promising refunds outside the selected policy without modeling frequency or training support staff."),
 ("Pricing & Calendar","occupancy-target-by-month-str","Should an STR Have One Annual Occupancy Target?","No. Monthly targets should reflect demand, rate, closures, owner use, and maintenance; the annual average is an output.","Monthly booked and available nights, rate, events, owner blocks, maintenance, lead time, and comparable supply.","Set contribution and pace targets by month, then roll them into an annual case. Investigate misses at the month level.","A 60% annual target can mean 95% in July and 20% in January; pricing both months toward 60% makes neither decision correctly.","Using annual occupancy to set daily prices or evaluate a soft month."),

 ("Tax Coordination","str-placed-in-service-date","When Is an STR Placed in Service for Tax Purposes?","Generally when it is ready and available for its intended rental use, not simply when it closes or receives its first booking. The owner's CPA should apply the rule to the facts.","Closing, permit, furnishing completion, listing activation, availability calendar, inspections, and first reservation evidence.","Create a dated readiness file and ask the CPA which date controls before year-end planning.","Closing December 1 does not establish December service when furniture, permits, and listing availability begin in January.","Backdating availability to chase a deduction or confusing purchase with readiness."),
 ("Tax Coordination","str-personal-use-calendar","How Should STR Personal-Use Days Be Tracked During the Year?","Maintain a contemporaneous calendar separating rental, fair-rent use, personal use, maintenance, and vacancy, with who stayed and why.","Reservation calendar, owner stays, family or discounted stays, maintenance logs, fair-rent support, and travel purpose.","Reconcile the calendar monthly with platform and bank records; send ambiguous stays to the CPA before year end.","A family stay at below-market rent may not belong in the same category as a documented repair trip.","Reconstructing use from memory after filing season."),
 ("Tax Coordination","property-manager-hours-record","How Should Property-Manager Hours Be Documented for Material Participation?","The owner needs credible records of their own work and enough information about others' participation for the applicable test; a CPA should determine the test.","Owner time log, manager scope, cleaner and vendor work, messages, calendar, invoices, and contemporaneous notes.","Record task, date, duration, purpose, and participant while the work occurs; ask the CPA what comparison evidence is needed.","An owner log showing 120 hours may be incomplete if a manager performs 300 hours and the intended test compares participation.","Counting investor-type research or inventing estimates after the year ends."),
 ("Tax Coordination","cost-seg-furnishings-allocation","How Should Furnishings Be Separated From a Cost Segregation Study?","Keep a purchase-date and cost inventory so the CPA and study provider can avoid duplication and classify assets from source records.","Furniture invoices, closing allocation, renovation draws, placed-in-service dates, photos, asset location, and prior depreciation.","Reconcile the fixed-asset ledger to total project cost before the study is finalized.","A refrigerator included in a contractor draw and again in a furnishing spreadsheet can be capitalized twice without reconciliation.","Using rounded room budgets as final tax basis or mixing personal items with rental assets."),
 ("Tax Coordination","lodging-tax-platform-reconciliation","How Do You Reconcile Platform-Collected Lodging Tax?","Match taxable sales, tax charged, tax remitted by each platform, owner-collected amounts, and jurisdiction filings by period.","Platform tax reports, direct-booking sales, registration accounts, returns, bank records, exemptions, and jurisdiction rates.","Build a jurisdiction-by-channel matrix and reconcile every filing period, including zero returns when required.","Airbnb may remit one tax while direct bookings and another platform leave the owner responsible for the same jurisdiction.","Booking gross-tax-inclusive revenue while also recording remitted tax as an expense."),
 ("Tax Coordination","str-repair-vs-improvement-records","What Records Help a CPA Separate STR Repairs From Improvements?","Keep invoices, scope, before-and-after condition, dates, asset affected, and the reason for work; classification depends on facts beyond the vendor label.","Contract, invoice detail, photos, inspection, insurance claim, maintenance history, permit, and placed-in-service date.","Create one project file per scope and avoid bundling unrelated repair and improvement work into one vague invoice.","An invoice reading 'renovation—$40,000' gives the CPA less usable evidence than itemized roof repair, deck expansion, paint, and appliance replacement.","Choosing tax labels in the bookkeeping memo without supporting the underlying work."),
 ("Tax Coordination","str-entity-books-owner-expenses","How Should an STR Entity Record Owner-Paid Expenses?","Record them consistently as contribution, reimbursement, payable, or another adviser-approved treatment so property cost and cash are complete.","Receipt, payer, business purpose, entity account, reimbursement policy, mileage, card statements, and closing ledger.","Reconcile owner-paid items monthly and have the tax professional confirm account treatment before year end.","Leaving furnishings on a personal card outside the books understates project basis and makes the asset ledger incomplete.","Using the entity as a reason to ignore expenses paid personally."),
 ("Tax Coordination","str-1099-payout-reconciliation","How Do You Reconcile STR 1099 Amounts to Platform Payouts?","Bridge reported gross amounts to reservation revenue, fees, refunds, taxes, and net deposits rather than expecting the form to equal bank cash.","1099, annual transaction report, reservation ledger, refunds, platform fees, collected taxes, processor statements, and deposits.","Prepare a gross-to-net reconciliation and retain it with the books for the return preparer.","A gross information return can exceed bank receipts because platform fees and refunds occur after the reported gross sale.","Booking only the bank deposits as revenue and having no explanation for the form difference."),
 ("Tax Coordination","str-mixed-use-expense-allocation","How Should Mixed Personal and Rental STR Expenses Be Allocated?","Use a consistent, adviser-approved method tied to rental and personal use; different expense categories may require different factual treatment.","Use calendar, square footage where relevant, utility and service periods, direct expenses, personal stays, and fair-rent days.","Separate direct rental costs first, then document the allocation driver for shared costs and review it with the CPA.","A repair caused by a guest is different from a whole-property annual utility bill when allocating mixed use.","Applying one rental-day percentage to every cost without adviser review."),
 ("Tax Coordination","str-year-end-document-package","What Should Be in an STR Year-End Package for the CPA?","A reconciled income statement, balance sheet, fixed-asset additions, debt and closing statements, use calendar, participation records, tax reports, and major project files.","Books reconciliation, bank and card statements, 1099s, platform reports, loan interest, taxes, insurance, asset ledger, mileage, and owner activity.","Use a checklist and resolve missing items before the preparer's deadline; label estimates and open questions separately.","Sending hundreds of receipts without reconciled totals shifts bookkeeping into tax-preparation time and can hide missing assets.","Waiting until filing week to ask what participation or placed-in-service evidence was required."),

 ("Exit & Portfolio","airbnb-reviews-property-sale","Do Airbnb Reviews Transfer When You Sell the Property?","Do not price the sale as if they automatically transfer. Platform accounts and review histories follow platform rules and transaction facts, not the deed.","Current platform policy, listing ownership, co-host structure, brand assets, future bookings, and transition plan.","Value the real estate on transferable economics and treat review continuity as conditional unless confirmed.","A five-star history can support the seller's trailing revenue while the buyer still launches a new listing from zero reviews.","Selling goodwill twice—inside the price and inside the buyer's immediate revenue forecast."),
 ("Exit & Portfolio","sell-str-with-furniture","Should You Sell an STR Furnished or Empty?","Compare buyer segment, used replacement value, removal cost, launch speed, and lender or appraisal treatment.","Itemized inventory, condition, replacement cost, used-market value, staging needs, storage, bill of sale, and buyer plan.","Offer a documented furniture package separately when it improves buyer speed without obscuring real-estate value.","A $100,000 original furnishing spend may have a much lower transferable used value after years of guest wear.","Adding original retail cost to the listing price."),
 ("Exit & Portfolio","str-cap-rate-sale-price","Can You Price an STR Sale From Its Cap Rate?","Only with a normalized operating statement and a buyer pool that values the income. Residential comparable sales may still dominate financing and appraisal.","Trailing revenue, normalized expenses, owner use, management replacement cost, capex reserve, legal use, and comparable sales.","Calculate NOI consistently, compare implied value with residential comps, and explain—not hide—the gap.","A self-managed property can show inflated NOI if owner labor is assigned zero cost, producing an unrealistic cap-rate value.","Capitalizing gross revenue or excluding replacement management and reserves."),
 ("Exit & Portfolio","rebrand-str-before-sale","Should You Rebrand an STR Before Selling It?","Only when the brand work improves current conversion or creates transferable assets that the likely buyer values before sale.","Listing performance, domain and direct-booking traffic, social accounts, photography rights, trademark, email consent, and buyer segment.","Price the project against contribution before sale and transferability; prioritize maintenance and clean financials first.","A new logo rarely fixes dated photos, unresolved reviews, or missing records, while those items affect buyers immediately.","Spending on identity without ownership and transfer rights for the digital assets."),
 ("Exit & Portfolio","str-long-term-rental-fallback","How Do You Underwrite a Long-Term-Rental Fallback for an STR?","Use current local rent, leasing costs, utilities, management, turnover, and any furniture disposition—not a percentage of STR revenue.","Rent comps, lease-up time, tenant-paid utilities, property management, furniture plan, legal use, mortgage, and required repairs.","Build a separate long-term P&L and compare cash burn, not just gross rent, with the STR downside case.","A home earning $90,000 gross as an STR may produce $42,000 long-term rent with materially different expenses and vacancy.","Calling the fallback 'break even' without a rent comp and full expense stack."),
 ("Exit & Portfolio","assign-str-management-contract-sale","Can an STR Management Contract Transfer to a Buyer?","Only under the contract's assignment and consent terms. Fees, termination rights, data, listings, and vendor arrangements may change at sale.","Management agreement, assignment, termination fee, notice, listing ownership, data export, vendor contracts, and buyer approval.","Treat the manager as a diligence party and price any required continuation or exit cost into closing.","A buyer may inherit a long contract with a termination fee but not the seller's negotiated commission rate.","Promising turnkey management without manager consent."),
 ("Exit & Portfolio","str-permit-value-sale","How Much Value Does a Transferable STR Permit Add?","At most the risk-adjusted economic advantage it creates over unpermitted alternatives, constrained by transfer conditions and buyer financing.","Permit status, transfer rule, cap, compliance history, remaining term, renewal, alternative use, and comparable permitted sales.","Estimate after-tax contribution difference, duration, transfer probability, and buyer discount rate; compare with observed sales.","A scarce permit can matter, but a one-year renewable permit with complaint exposure is not a permanent annuity.","Adding a round premium without verifying transfer and renewal."),
 ("Exit & Portfolio","str-sale-data-room","What Belongs in an STR Sale Data Room?","Documents that let a buyer verify legal use, revenue, expenses, condition, operations, assets, and transition without relying on seller summaries.","Permits, tax accounts, reservation and payout exports, P&L, bills, policies, inspections, maintenance, inventory, contracts, SOPs, and privacy-redacted guest data.","Index every file, define the covered period, reconcile totals, and remove information the buyer is not entitled to receive.","A polished pro forma cannot replace raw exports and invoices when a buyer needs to reconcile trailing performance.","Uploading guest personal data or mixing projections with actuals without labels."),
 ("Exit & Portfolio","seller-finance-str-sale","Should an STR Seller Offer Financing to the Buyer?","Only after counsel, tax, lien, credit, servicing, default, and liquidity analysis. A higher price or faster sale can exchange cash certainty for borrower risk.","Buyer credit and equity, note terms, collateral, senior debt consent, servicing, insurance, default remedies, balloon, and tax advice.","Compare net present value and loss severity with an all-cash or financed buyer; stress missed payments and property decline.","A premium price is not a gain if a thinly capitalized buyer defaults after the seller released control of operations.","Using seller financing to bridge an appraisal gap without addressing why institutional lenders rejected the value."),
 ("Exit & Portfolio","str-portfolio-concentration-sale","When Should You Sell One STR to Reduce Portfolio Concentration?","When one market, hazard, regulation, season, or debt structure dominates portfolio downside beyond the owner's risk tolerance.","Revenue and cash flow by market and month, debt maturities, insurance hazards, regulation, reserves, equity, tax basis, and sale costs.","Measure correlated downside, not property count. Compare sale proceeds and lost contribution with the reduction in peak cash need.","Three homes in one hurricane-exposed beach market are not diversified because they have different street addresses.","Selling the weakest recent performer without examining correlation, taxes, debt, and replacement opportunity."),
]

assert len(TOPICS) == 100, len(TOPICS)


def link(url):
    label = url.strip("/").split("/")[-1].replace("-", " ").title() or "BNB Accelerator"
    return f'<a href="{url}">{label}</a>'


def make_post(i, row):
    cluster, slug, question, answer, evidence, test, example, risk = row
    cfg = CLUSTERS[cluster]
    title = question.rstrip("?")
    description = re.sub(r"<[^>]+>", "", answer)
    if len(description) > 155:
        description = description[:152].rsplit(" ", 1)[0] + "..."
    subject = title[0].lower() + title[1:]
    evidence_items = [part.strip().rstrip(".") for part in evidence.split(",")]
    first_evidence = evidence_items[0]
    last_evidence = evidence_items[-1]
    check_prompts = (
        "attach the underlying record and note its effective date",
        "identify who can confirm it independently before the deadline",
        "translate a worse result into cash, time, or operating impact",
        "mark whether it transfers to a buyer or must be obtained again",
        "record the conservative input used when the source is incomplete",
        "schedule the next check so the file does not quietly become stale",
    )
    evidence_register = [
        f"{item.capitalize()}: {check_prompts[(i + n) % len(check_prompts)]}."
        for n, item in enumerate(evidence_items)
    ]
    angle_note = ANGLE_NOTES[i % len(ANGLE_NOTES)]
    return {
        "slug": slug,
        "title": title,
        "title_tag": f"{title} | BNB Accelerator",
        "h1": question,
        "description": description,
        "date": DATE,
        "category": cluster,
        "lead": f"{answer} {cfg['context']}",
        "sections": [
            ("The direct answer", [answer, cfg["context"]]),
            ("Evidence to collect before deciding", [evidence, ("callout", f"Decision file: preserve the source, the date checked, and who confirmed it. {cfg['action']}")]),
            ("Run the decision test", [test, "Use the downside version first. If the decision only works when every unresolved item lands favorably, the property has no diligence margin."]),
            ("A worked example", [example, "The example is a planning illustration, not a projection or a substitute for property-specific legal, tax, lending, insurance, or investment advice."]),
            ("Build the underwriting worksheet", [
                f"Give {subject} its own line in the acquisition workbook instead of burying it in a general contingency. Record the base case, a conservative case, the source date, and the person responsible for the next verification. The first source to attach is {first_evidence.lower()}; the final cross-check is {last_evidence.lower()}.",
                f"The worksheet should show what changes if the answer is worse than expected. Recalculate cash required, monthly carrying cost, opening date, and the first twelve months of distributable cash. For this question, the working decision rule is: {test}",
                "Keep facts separate from judgments. A permit record, invoice, policy form, lender email, booking export, or signed agreement is evidence. A broker estimate, seller explanation, or unsigned proposal may help frame the question, but it should remain labeled as an assumption until independently verified.",
            ]),
            ("Use this evidence register", [
                ("ul", evidence_register),
                f"Read the register as one chain, not {len(evidence_register)} isolated boxes. A favorable answer on {first_evidence.lower()} does not cure an unsupported answer on {last_evidence.lower()}. The buyer case should state which item controls the decision and which items merely refine the estimate.",
            ]),
            ("Add a second analytical lens", [
                angle_note,
                f"Apply that lens specifically to {subject}. Compare it with the direct evidence—{evidence}—and document any mismatch before relying on the base case. The purpose is not to manufacture another forecast; it is to expose a dependency that the first-pass answer may conceal.",
                f"For this file, trace the chain in this order: establish {evidence_items[(i + 1) % len(evidence_items)].lower()}, challenge it with {evidence_items[(i + 3) % len(evidence_items)].lower()}, quantify the effect through {evidence_items[(i + 4) % len(evidence_items)].lower()}, and close the loop using {evidence_items[(i + 5) % len(evidence_items)].lower()}. Write the result as one connected explanation so a reviewer can see how each source changes the final answer.",
            ]),
            ("Set a stop, proceed, and renegotiate boundary", [
                f"Write three outcomes before the next deadline. Proceed when the evidence supports the buyer case with room for error. Renegotiate when {risk[0].lower() + risk[1:]} creates a measurable cost that a price change, credit, escrow, or contract term can address. Stop when the unresolved risk cannot be priced or controlled.",
                f"Do not move the boundary simply because the team has invested time in the deal. The relevant conclusion remains: {answer} Apply that conclusion to the current documents, not to the enthusiasm created by projected revenue or an approaching closing date.",
                "A useful escalation note is short: state the unresolved fact, attach the best evidence, quantify the downside, name the deadline, and ask the responsible professional one precise question. That format makes it easier for an attorney, CPA, lender, insurer, inspector, or official to answer without reconstructing the entire acquisition.",
            ]),
            ("Write the one-page decision memo", [
                f"Open the memo with the exact question—“{question}”—and the current conclusion: {answer} Then identify the document or event that could reverse that conclusion. This keeps the team focused on a falsifiable decision instead of accumulating background material that never changes the offer.",
                f"Use the worked case as the numerical anchor: {example} Replace every illustrative number or condition with the address-specific result, retain both versions, and explain the variance. A later reviewer should be able to reproduce the choice without relying on memory or a sales conversation.",
                f"Close the memo with the principal failure mode: {risk} Assign that risk to a contract term, reserve, operating control, professional review, or a decision not to proceed. If none of those responses is credible, the memo has produced a stop signal rather than another item for the post-closing list.",
            ]),
            ("Where buyers get hurt", [risk, cfg["action"]]),
            ("Recheck after closing", [
                f"Closing does not retire the issue behind {subject}. Add it to the first-30-day operating review and compare the decision file with what actually happened. Variances should update pricing rules, reserves, vendor scopes, or the next acquisition's diligence checklist.",
                f"Preserve {evidence.lower()} in the permanent property file. If ownership, policy terms, local rules, vendors, or market conditions change, date the new source rather than overwriting the old one. That history explains why the original decision was reasonable and when a fresh decision became necessary.",
            ]),
            ("What to do before the next deadline", [("ol", ["Replace the largest assumption with a document, quote, export, or written answer.", "Put the downside result into the cash model and the unresolved issue into the contract or operating plan.", "Have the appropriate attorney, CPA, lender, insurer, inspector, or local official review the fact that falls inside their role."]), "BNB Accelerator screens acquisitions for fit, evidence, and downside before a client commits capital. The final decision remains the buyer's, supported by their own advisers."]),
        ],
        "faqs": [
            (question, answer),
            ("What should I verify before making the decision?", evidence),
            ("Can BNB Accelerator make this decision for me?", "BNB Accelerator can help source and underwrite the property, but legal, tax, insurance, lending, inspection, and investment decisions remain with the buyer and the buyer's licensed advisers."),
        ],
        "related": [link(u) for u in cfg["related"]],
        "cta_h": "Want the property screened before you commit?",
        "cta_p": "BNB Accelerator sources and underwrites short-term-rental acquisitions for high-income buyers. Apply for a strategy call to see whether the process fits.",
    }


def main():
    posts = [make_post(i, row) for i, row in enumerate(TOPICS)]
    blog.build(posts)
    print(f"buyer decision batch: {len(TOPICS)} posts generated")


if __name__ == "__main__":
    main()
