#!/usr/bin/env python3
"""Evergreen, question-led STR acquisition and underwriting guides."""
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
import tpl
from pillars import guide, hub, write

DATE = "2026-09-22"
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

PAGES = [
    dict(slug="break-even-occupancy", h1="How to Calculate Break-Even Occupancy for a Short-Term Rental", title="STR Break-Even Occupancy: Formula and Example", description="Calculate the occupancy a short-term rental needs to cover fixed and variable costs, with a worked example and a downside test.", lead="Break-even occupancy tells you how many booked nights a property needs before it produces a dollar of cash flow. It is a more useful first screen than a headline revenue estimate because it connects nightly rate to the actual cost of owning and operating the property.", sections=[
        ("The formula", ["Start with monthly fixed costs: debt service, property tax, insurance, internet, software, minimum utilities, and any HOA dues. Then estimate the contribution from each booked night: average nightly revenue minus the costs that rise with a booking, such as platform fees, consumables, utilities, and any cleaning shortfall. Divide fixed costs by contribution per night. Divide the resulting nights by the number of nights available in the month.", ("callout", "Break-even booked nights = monthly fixed costs ÷ (average nightly revenue − variable cost per booked night). Break-even occupancy = booked nights ÷ available nights."), "Use revenue after discounts and refunds. Treat cleaning fees and cleaning bills consistently: either include both in revenue and expense or exclude both when they offset one another."]),
        ("A worked example", ["Suppose fixed monthly costs are $5,400, an achievable average nightly rate is $300, and booking-related costs average $60 per night. Each booked night contributes $240. The property needs 22.5 booked nights, which means at least 23 nights in a 30-night month, or roughly 77% occupancy, to break even on cash flow.", "If the same property can realistically fill only 18 nights in a typical month, the answer is not to assume a better listing will solve the gap. Test a lower purchase price, a smaller debt payment, a higher justified rate, or reject the deal. The example is arithmetic, not a market forecast."]),
        ("Test the weak months", ["Annual average occupancy hides the calendar. A beach home can be profitable for the year but still need cash injections in winter. Run this formula month by month with season-specific rates and available nights. Carry a reserve for months below break even.", "For a more complete investment view, add recurring capital replacements and management fees. A property that only breaks even before those costs has no economic margin. Compare the result with the <a href=\"/revenue-projections/\">revenue projection guide</a> and the <a href=\"/tools/str-revenue-calculator/\">STR calculator</a>."])
    ], faqs=[("What is a good break-even occupancy for an Airbnb?", "There is no universal target. A lower break-even point gives a larger margin for weak months, but the right threshold depends on seasonal demand, nightly rates, financing, and operating costs."), ("Should cleaning fees count in break-even occupancy?", "Yes, if you include guest cleaning fees as revenue, include the actual cleaning expense too. Excluding both is acceptable when they approximately offset, but do not count the fee and omit the cost.")], related=["/revenue-projections/", "/tools/str-revenue-calculator/", "/blog/airbnb-occupancy-rates-explained/"]),
    dict(slug="seller-financials", h1="How to Verify an Existing Airbnb's Seller Financials", title="Buying an Existing Airbnb: Verify Seller Revenue", description="A buyer's checklist for reconciling platform payouts, expenses, owner stays and transferable assets before buying an operating short-term rental.", lead="An operating Airbnb can give you better evidence than a new listing, but a seller's revenue screenshot is not an income statement. Before you price the asset on its claimed performance, reconcile booked stays to cash received and identify what changes when ownership transfers.", sections=[
        ("Build a revenue bridge", ["Request 12 to 24 months of platform transaction exports, payout records, bank deposits, refunds, discounts, and tax documents where available. Reconcile gross guest charges to platform fees, cancellations, taxes collected on behalf of the host, and net payouts. Ask why any months or channels are missing.", "Separate room revenue, cleaning fees, pet fees, and taxes. A chart labeled 'revenue' might show gross booking value while the owner receives materially less. Note owner blocks and complimentary stays: they reduce bookable inventory and can distort occupancy comparisons."]),
        ("Rebuild operating costs", ["Collect bills for cleaners, utilities, insurance, property tax, management, software, lawn or pool care, repairs, supplies, and permits. Add expenses the seller did not incur but you will, such as a professional manager or a larger mortgage. Normalize one-time repairs separately, but do not pretend the property has no ongoing replacement cost.", "Compare cash receipts and paid invoices to the seller's summary. Ask for a reservation calendar showing booked, blocked, and cancelled nights. Use the <a href=\"/underwriting/expense-ratio/\">expense ratio guide</a> to translate the history into a buyer-specific model."]),
        ("Identify what does not transfer", ["Platform accounts, review histories, permits, vendor relationships, photos, furniture, and future reservations may have different transfer rules. Do not assume that buying the house transfers a listing or its five-star history. Confirm each item in writing and assign a value of zero to anything you cannot legally or practically retain.", "Underwrite a launch period even when the seller has a strong trailing year. Your pricing, photography, reviews, and operations may need to restart. For a broader comparison, see <a href=\"/blog/buy-existing-airbnb-vs-start-from-scratch/\">existing Airbnb versus a new launch</a>."])
    ], faqs=[("Can Airbnb reviews transfer to a new owner?", "Do not assume they can. Platform accounts and listings have their own rules; verify the current platform policy and the proposed transaction structure before treating reviews as a purchased asset."), ("How many months of seller financials should I request?", "At least a full seasonal cycle; 12 to 24 months is more useful when available. A few peak-season screenshots do not show cancellations, winter demand, or recurring costs.")], related=["/underwriting/expense-ratio/", "/blog/buy-existing-airbnb-vs-start-from-scratch/", "/blog/str-due-diligence-checklist/"]),
    dict(slug="permit-transfer", h1="Can a Short-Term Rental Permit Transfer When You Buy the Property?", title="STR Permit Transfer Due Diligence for Buyers", description="How to verify whether an STR permit survives a property sale, and what to ask the city before you make a nonrefundable commitment.", lead="A legal short-term rental today may not be legal for its next owner. Permits can attach to a person, an address, a business entity, or a limited zoning exception. The only safe purchase assumption is the one the local issuing authority confirms for your exact address and transaction.", sections=[
        ("Ask the issuing authority four specific questions", [("ol", ["Is the current permit active, and are there open violations or unpaid fees?", "Does a sale, deed transfer, or change of entity ownership terminate it?", "If it does terminate, can a new owner apply today, and is there a cap, waitlist, lottery, spacing rule, or residency requirement?", "What inspections, tax registrations, fire requirements, and deadlines apply before hosting can resume?"]), "Get the answer in writing or retain the ordinance section and the name and date of the official who explained it. A seller's statement or an agent's listing description is not a permit opinion."]),
        ("Check every layer of restriction", ["City and county rules may differ. A property inside city limits can have different requirements from one with the same mailing city outside the boundary. HOA covenants, condominium rules, deed restrictions, and lender or insurer conditions can also prohibit short stays even when the municipality allows them.", "Compare the address and parcel ID to the ordinance map. Verify minimum stay rules, maximum occupancy, parking, inspections, and the permit renewal calendar. A permit with six months left and no path to renew is different from durable operating permission."]),
        ("Protect the purchase contract", ["Ask a local real estate attorney to make satisfactory permit verification a due-diligence condition when the STR use is central to the deal. Model the property's long-term rental and resale value as a fallback. If the transaction only works with an unverified permit, the underwriting is incomplete.", "Start with our <a href=\"/regulations/\">state regulation guides</a>, then verify the municipality and parcel with current primary sources. Rules change, and a state overview cannot approve a specific address."])
    ], faqs=[("Does an Airbnb permit stay with the house after closing?", "Sometimes, but many permits are owner-specific or require a new application after a sale. Verify the exact local ordinance and obtain written confirmation from the issuing authority."), ("Is a grandfathered STR permit transferable?", "Do not assume so. Grandfathering often protects only the existing owner or use under specified conditions. Ask the issuing authority about the proposed sale and ownership structure.")], related=["/regulations/", "/blog/permits-that-do-not-transfer/", "/underwriting/hoa-restrictions/"]),
    dict(slug="hoa-restrictions", h1="How to Check HOA Rules Before Buying a Short-Term Rental", title="HOA STR Rules: A Buyer's Due Diligence Checklist", description="Review HOA and condo restrictions on minimum stays, rentals, enforcement and rule changes before underwriting a short-term rental purchase.", lead="A city can allow short-term rentals while an HOA bans them. The restriction that matters is the most limiting rule that applies to the property. Read the recorded documents before you rely on an agent's statement that 'other homes in the neighborhood are Airbnbs.'", sections=[
        ("Request the complete document set", ["Get the recorded declaration or CC&Rs, bylaws, current rules, amendments, board resolutions, rental registration policies, and recent meeting minutes. Ask for an estoppel or resale certificate where available. Search for rental, transient, hotel, business use, minimum stay, guest registration, occupancy, parking, and fine provisions.", "A 30-day minimum is effectively a ban on nightly STR use. Some documents allow rentals but restrict the number of rental properties, require a waiting period, or cap guests below what your revenue model assumes."]),
        ("Test enforcement and future risk", ["Ask the association in writing whether the proposed operating plan is allowed for this parcel and ownership structure. Request any violation history and pending amendments. The fact that an existing owner hosted without enforcement does not create a reliable right for you.", "Separate recorded covenants from informal guidance. Counsel can help determine which rule controls when documents conflict. Budget dues, special assessments, guest parking limits, and any required registration in the operating model."]),
        ("Use a fallback valuation", ["If nightly rental rights are uncertain, value the property based on an allowed use. A deal that only clears your return target by assuming a disputed HOA interpretation is not a conservative acquisition. The <a href=\"/underwriting/permit-transfer/\">permit transfer guide</a> covers the municipal side of the same diligence."])
    ], faqs=[("Can an HOA ban Airbnb if the city allows it?", "Yes. Private covenants can impose stricter limits than municipal rules. Review the recorded documents and current association rules for the specific property."), ("Are existing Airbnb listings proof that an HOA permits STRs?", "No. They may be grandfathered, noncompliant, or subject to different parcel rules. Obtain the current governing documents and a written answer for your proposed use.")], related=["/underwriting/permit-transfer/", "/blog/reading-an-hoa-declaration/", "/blog/str-due-diligence-checklist/"]),
    dict(slug="expense-ratio", h1="What Expenses Should an STR Underwriting Model Include?", title="Short-Term Rental Expenses: Underwriting Checklist", description="A practical list of fixed, booking-driven and replacement costs to include when estimating Airbnb net operating income and cash flow.", lead="Gross booking revenue is only the top line. A defensible STR model names each cost, says whether it changes with bookings, and shows who pays it. Missing even modest recurring items can turn projected cash flow into a loss.", sections=[
        ("Separate operating costs from financing", ["Operating costs typically include property tax, insurance, utilities, internet, platform fees, management or co-host fees, software, cleaning net of guest cleaning fees, laundry, supplies, lawn or pool care, pest control, licenses, accounting, repairs, and routine maintenance. Add HOA dues where applicable.", "Net operating income is revenue minus operating expenses, before debt service. Cash flow then subtracts principal and interest payments and any other financing costs. Keeping these lines separate lets you compare properties with different loans."]),
        ("Calculate the expense ratio, then inspect the lines", ["The operating expense ratio is operating expenses divided by gross operating revenue. For example, $32,000 of annual operating costs on $80,000 of revenue is 40%. The ratio excludes debt service; otherwise two identical homes with different loans would appear to operate differently.", "Use the ratio as a warning light, not a universal pass mark. Compare each category with bills, bids, and comparable properties. A percentage shortcut hides cleaning frequency, weather-driven utilities, and insurance premiums that vary by property."]),
        ("Budget for replacements and owner time", ["Furniture, linens, appliances, hot tubs, and HVAC systems wear out. Set aside a recurring replacement reserve based on the actual asset list and condition rather than treating each failure as a surprise. If you self-manage, count your time or model the cost of hiring a manager so the investment comparison is honest.", "Booking-driven costs rise with turns and occupied nights. Fixed costs continue in slow months."]),
        ("Run three cases", ["Build a base case from comparable listings or verified seller history, a downside case with lower occupancy and rate, and an upside case with evidence for the improvement. Hold most fixed expenses constant in the downside case. Calculate <a href=\"/underwriting/break-even-occupancy/\">break-even occupancy</a> and test whether reserves cover a weak season.", "Our <a href=\"/str-cash-flow-analysis/\">cash flow analysis guide</a> explains the return metrics to use after the expense model is complete."])
    ], faqs=[("What is the biggest expense in a short-term rental?", "It varies. Debt service is often the largest cash outflow, while management, cleaning, property tax, insurance, and utilities are major operating lines. Model the actual property rather than using a universal percentage."), ("Should mortgage payments be included in NOI?", "No. Net operating income excludes financing. Subtract debt service after NOI to calculate cash flow to the owner.")], related=["/underwriting/break-even-occupancy/", "/str-cash-flow-analysis/", "/blog/str-capex-planning/"]),
    dict(slug="cash-needed-to-buy", h1="How Much Cash Do You Need to Buy a Short-Term Rental?", title="Cash Needed to Buy an Airbnb: Full Entry Budget", description="Estimate STR purchase cash beyond the down payment, including closing, furnishing, launch, carry costs and reserves.", lead="The down payment is only one part of the cash needed to buy an Airbnb. A buyer can qualify for a loan and still run short during furnishing or the first off-season. Build a sources-and-uses schedule before you make an offer.", sections=[
        ("List every use of cash", ["Start with earnest money and down payment, then lender and title charges, inspections, appraisal, insurance deposit, prepaid tax and interest, and any immediate repair or code work. Add furniture, mattresses, kitchen inventory, linens, exterior amenities, photography, listing setup, permits, and sales or lodging tax registration where required.", "Add working capital for utility deposits, early mortgage payments, vendor retainers, and a revenue ramp. Keep an emergency reserve separate from the furnishing budget; spending every available dollar to launch leaves no buffer for a failed HVAC unit or a weak first quarter."]),
        ("Illustrative math", ["For a $600,000 property with 25% down, the down payment is $150,000. If closing and prepaids are $18,000, repairs and furnishing are $65,000, launch costs are $7,000, and operating reserves are $30,000, total planned cash is $270,000. Those figures are an arithmetic example, not a quote or a typical deal.", "A seller credit may reduce closing cash but cannot fund every category. Financing products differ in what they allow you to roll into the loan. Confirm actual terms with a lender and build the model from written bids."]),
        ("Match the reserve to the risk", ["A property with a hot tub, pool, remote location, or concentrated seasonal demand may need more liquidity than a simple urban unit. Recalculate cash needs if insurance, interest rate, or renovation scope changes. Our <a href=\"/financing/closing-costs-and-reserves/\">closing cost and reserve guide</a> expands the financing side."])
    ], faqs=[("Is the down payment enough to start an Airbnb?", "Usually no. Buyers also need closing funds, setup and furnishing money, permits, early operating cash, and reserves for repairs or slow months."), ("Can I finance STR furniture and setup costs?", "Some products may allow financing for certain improvements, but terms vary. Assume cash is required until your lender confirms the allowable uses in writing.")], related=["/financing/closing-costs-and-reserves/", "/financing/down-payment-strategies/", "/underwriting/insurance-quote/"]),
    dict(slug="insurance-quote", h1="How to Verify STR Insurance Costs Before You Buy", title="STR Insurance Quote Checklist for Buyers", description="Get property-specific short-term rental insurance quotes and test flood, wind, wildfire and liability costs before removing purchase contingencies.", lead="Insurance is both a legal requirement in many transactions and a major underwriting input. A homeowner policy may exclude business hosting, and a cheap online estimate may omit the hazards that matter at the actual address. Get an insurable-property answer before the deal becomes nonrefundable.", sections=[
        ("Quote the real operating plan", ["Give the broker the parcel address, occupancy, property type, amenities, expected rental frequency, whether a manager will operate it, and any pool, hot tub, waterfront, or fireplace exposure. Ask what is covered for guest injury, property damage, lost rental income, and ordinance or law upgrades. Ask about deductibles as well as premiums.", "If a lender requires coverage, request written confirmation that the policy form and limits meet its conditions. Platform host protection is not a substitute for evaluating your own policy and exclusions."]),
        ("Check catastrophe layers separately", ["Flood, wind or hail, wildfire, and earthquake exposure may be excluded, separately priced, or subject to high deductibles. Verify flood zone and elevation information from the appropriate official map, then obtain the actual quote. An old seller premium is weak evidence if the carrier will reprice at transfer.", "Ask whether the insurer can bind coverage on your closing date and what inspections or mitigation are required. A carrier declining the property can change financing and closing timing, not just annual profit."]),
        ("Put the quote into the downside case", ["Use the written premium and deductible in your model, then stress a renewal increase and one uninsured or deductible-sized event. Carry reserves for the deductible. Review the broader <a href=\"/blog/airbnb-insurance-guide/\">Airbnb insurance guide</a> alongside the <a href=\"/underwriting/expense-ratio/\">expense checklist</a>."])
    ], faqs=[("Does homeowners insurance cover Airbnb guests?", "Do not assume it does. Standard homeowner policies may restrict or exclude business rental activity. Ask a licensed insurance professional for a policy covering the exact short-term rental use."), ("When should I get an STR insurance quote?", "Before the purchase contingency expires. The quote can reveal an unworkable premium, exclusion, deductible, or inability to bind coverage at closing.")], related=["/blog/airbnb-insurance-guide/", "/underwriting/expense-ratio/", "/underwriting/cash-needed-to-buy/"]),
    dict(slug="downside-scenario", h1="How to Stress-Test a Short-Term Rental Deal", title="STR Downside Scenario: Stress-Test Cash Flow", description="Run a downside STR investment model for lower occupancy, lower nightly rates, higher expenses and delayed launch before buying.", lead="A base-case projection describes what you expect. A downside case tells you whether the property can survive when that expectation is wrong. Stress testing is especially important when debt service and fixed costs continue through slow months.", sections=[
        ("Change the drivers together", ["Lower occupancy and average daily rate at the same time rather than testing only one variable. Include more empty weekdays, fewer event bookings, and a slower initial review ramp. Keep debt service, property tax, insurance, and many utility costs largely unchanged. Increase management or repair costs where the property is older or remote.", "Avoid a fake downside that merely trims revenue by 5%. Choose scenarios tied to comparable listing histories, weak seasonal periods, and known local risks. Record why each assumption is plausible."]),
        ("Measure cash burn and liquidity", ["For each month, calculate booking revenue, variable expenses, fixed expenses, debt service, and ending cash flow. Add the negative months to estimate the reserve needed to reach the next strong season. Run a delayed-launch case that has costs but no guest income while permitting, furnishing, and photography finish.", "Compare the result with available liquid reserves after closing. If the owner would need to sell or borrow after one weak quarter, the purchase size or financing structure may be too aggressive."]),
        ("Set a decision rule before seeing the listing", ["For example, require the downside case to remain above a chosen minimum liquidity balance and the base case to clear a target return after a capital replacement allowance. Document the rule before falling in love with a property. The <a href=\"/underwriting/break-even-occupancy/\">break-even occupancy guide</a> provides a quick cross-check."])
    ], faqs=[("What variables should I stress-test for an Airbnb?", "Test occupancy, nightly rate, launch delay, operating costs, insurance, repairs, and financing. Model months individually so seasonality does not disappear inside an annual average."), ("How much cash reserve should an STR have?", "There is no universal amount. Model the cumulative cash shortfall in weak months and a plausible major repair, then keep enough liquidity to cover both without relying on immediate refinancing or a sale.")], related=["/underwriting/break-even-occupancy/", "/underwriting/cash-needed-to-buy/", "/blog/str-cash-reserves-seasonality/"]),
]

def render():
    cards = [(f"/underwriting/{p['slug']}/", p["h1"], p["description"]) for p in PAGES]
    intro = [("A sequence for screening a deal", [
        "Start with legal use: <a href=\"/underwriting/permit-transfer/\">permit transfer</a> and <a href=\"/underwriting/hoa-restrictions/\">HOA restrictions</a>. Then verify the revenue evidence, rebuild expenses, obtain an insurance quote, and calculate your full cash requirement. Only after those steps should the base and downside cases determine whether to offer.",
        "Each guide is a separate decision tool with a worked method or document checklist. No single page can approve a property: local rules, lender terms, property condition, and your own finances control the result.",
    ])]
    html = hub(path="/underwriting/", title="Short-Term Rental Underwriting Guides | BNB Accelerator", h1="Short-Term Rental Underwriting: From Listing to Decision", eyebrow="Underwriting", description="Eight practical guides to STR permits, HOA rules, seller financials, expenses, insurance, cash needed, break-even occupancy and downside scenarios.", sub="Use these checks to decide whether a specific vacation rental is legal, financeable, insurable and likely to survive a weak season.", cards=cards, sections=intro, related=['<a href="/deals/">Explore documented deals</a>', '<a href="/tools/str-revenue-calculator/">Model a property</a>'])
    write("/underwriting/", html)
    for p in PAGES:
        related = [f'<a href="{u}">{u.strip("/").replace("-", " ").split("/")[-1].title()}</a>' for u in p["related"]]
        html = guide(slug=p["slug"], parent="/underwriting/", parent_name="Underwriting", title=p["title"], h1=p["h1"], eyebrow="Underwriting", description=p["description"], lead=p["lead"], sections=p["sections"], faqs=p["faqs"], related=related, read_min=4, section_name="STR Underwriting", cta=("Want a second set of eyes on an STR deal?", "See how BNB Accelerator evaluates purchase risk before a client commits capital."))
        write(f"/underwriting/{p['slug']}/", html)
    for p in ["underwriting"] + [f"underwriting/{x['slug']}" for x in PAGES]:
        f = os.path.join(ROOT, p, "index.html")
        s = open(f, encoding="utf-8").read().replace("2026-08-15", DATE).replace("Updated August 2026", "Updated September 2026")
        with open(f, "w", encoding="utf-8") as out:
            out.write(s)

if __name__ == "__main__":
    render()
