#!/usr/bin/env python3
"""Maintain distinct commercial and educational acquisition pillars."""
from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).parent))
import tpl

ROOT = Path(__file__).resolve().parents[1]
PAGES = [
  dict(path='/buy-a-short-term-rental/', title='How to Buy a Short-Term Rental | BNB Accelerator', description='A step-by-step guide to buying a short-term rental: market selection, permits, financing, underwriting, inspections, closing and launch.', label='Acquisition process', h1='How to buy a short-term rental', lead='Start with a property you can legally operate, a full purchase budget, and a downside case you can afford. A projected nightly rate alone is not a purchase decision.', sections=[
    ('1. Set the investment criteria before browsing', 'Choose your maximum total cash commitment, target markets, property size, management approach, and minimum reserves. Set a walk-away rule for uncertain permits or poor downside cash flow. A property that is attractive as a vacation home may fail as an investment.'),
    ('2. Verify the address and operating rights', 'Check the current municipal and county rules, zoning, HOA documents, occupancy limits, parking rules, and whether an existing permit transfers to a buyer. Rules can change between offer and closing. Get written confirmation from the relevant authority and include a satisfactory review period in the purchase contract. <a href="/regulations/">Start with our state regulation guides</a>, then verify the specific address.'),
    ('3. Underwrite revenue and expenses', 'Use comparable properties with similar bedrooms, amenities, location, and operating history. Model monthly booked nights and average daily rate, then subtract management, cleaning shortfalls, utilities, insurance, repairs, taxes, platform fees, and debt service. Stress-test both occupancy and rates together. <a href="/revenue-projections/">See the revenue framework</a> and <a href="/underwriting/downside-scenario/">downside case</a>.'),
    ('4. Count all the cash needed', 'Include earnest money, down payment, closing costs, inspections, initial repairs, furniture, permits, listing setup, and a separate operating reserve. Confirm lender requirements early because STR income treatment and reserve requirements vary by loan program and borrower. <a href="/underwriting/cash-needed-to-buy/">Build a sources-and-uses budget</a> and review <a href="/financing/">financing options</a>.'),
    ('5. Inspect the property and the business', 'Order suitable physical inspections and check insurance availability. If buying an operating rental, reconcile seller booking records to deposits and expenses, ask whether reviews and reservations can transfer, and review vendor agreements. Never assume the previous owner’s listing, license, bookings, or tax treatment will automatically follow the sale. <a href="/blog/buying-an-operating-str/">Review operating STR diligence</a>.'),
    ('6. Close with a launch plan', 'Before closing, confirm who orders furniture, obtains permits and insurance, photographs the property, creates the listing, sets prices, hires cleaners, and handles guest messages. Keep enough cash for a slower ramp. Compare actual monthly performance with the underwriting rather than treating the forecast as a guarantee.')], links=[('/airbnb-investment-property/','Evaluate an Airbnb investment property'),('/short-term-rental-investment/','STR investing fundamentals'),('/markets/','Compare markets'),('/case-studies/','See documented purchases')]),
  dict(path='/airbnb-investment-property/', title='Airbnb Investment Property: Buyer Evaluation Guide | BNB Accelerator', description='Evaluate an Airbnb investment property using legal use, comparable bookings, total entry cash, debt coverage, management costs and downside scenarios.', label='Property evaluation', h1='How to evaluate an Airbnb investment property', lead='An Airbnb investment property is real estate operated as a short-term rental. The purchase succeeds or fails at the address level: legal use, booking demand, total costs, and the cash left after debt service.', sections=[
    ('Start with the address, not a market headline', 'A strong tourism market does not make every parcel eligible or profitable. Verify the property’s permitted use, any HOA restrictions, occupancy, parking, and license conditions. Check how many comparable rentals are competing for the same guests and whether new supply is increasing. <a href="/markets/">Compare active markets</a>, then verify local rules.'),
    ('Compare like with like', 'A four-bedroom home with a pool and walkable access is not a reliable comp for a smaller home without those features. Compare monthly occupancy, nightly price, seasonality, cleaning economics, and booked rather than advertised rates. Ask for raw booking history when the subject property already operates as a rental.'),
    ('Calculate the real return', 'Net operating income equals revenue minus operating expenses before financing and income taxes. Cash flow after debt subtracts debt service and planned capital replacements. Cash-on-cash return divides annual pre-tax cash flow by all entry cash, including furniture and reserves, and can be negative. <a href="/tools/str-revenue-calculator/">Use the revenue calculator</a> as a first pass, then build a property-specific model.'),
    ('Test downside and exit options', 'Reduce both occupancy and average daily rate in a downside scenario; keep fixed mortgage, insurance, property tax, and utility costs in the model. Estimate repairs and the cash needed through a weak season. Check whether a medium-term or long-term rental is legally and economically viable if STR rules or demand change.'),
    ('Decide who will operate it', 'An owner-managed property requires time and reliable local coverage. A manager charges a fee and still needs owner oversight. Clarify cleaning, maintenance, guest support, pricing authority, and reporting before projecting a hands-off investment. <a href="/management/">Review the management plan</a>.')], links=[('/buy-a-short-term-rental/','Buying process and due diligence'),('/short-term-rental-investment/','Investment risks and return metrics'),('/property-types/','Compare property types'),('/deals/','See closed deal examples')]),
  dict(path='/short-term-rental-investment/', title='Short-Term Rental Investment Guide | BNB Accelerator', description='Understand short-term rental investment returns, operating work, financing, regulation and risk before buying an Airbnb or vacation rental property.', label='Investing fundamentals', h1='Short-term rental investment: returns, work and risk', lead='A short-term rental investment earns guest revenue from furnished stays, but it remains a property business with debt, operating costs, local rules, and uncertain demand. Underwrite it as a business and a piece of real estate.', sections=[
    ('How an STR makes money', 'Revenue depends on available nights, booked nights, nightly rate, and ancillary fees. Gross booking revenue is not owner profit. Cleaning, management, utilities, insurance, property tax, repairs, platform fees, furniture replacement, and loan payments consume cash. Appreciation and tax outcomes are uncertain and should not be needed for a property to survive.'),
    ('Which return measures matter', 'Track net operating income before debt, annual cash flow after debt and planned replacements, cash-on-cash return against total entry cash, and the monthly break-even occupancy. Record a base case and a downside case. <a href="/underwriting/break-even-occupancy/">Calculate break-even occupancy</a> before making an offer.'),
    ('Where investors lose money', 'Frequent causes include buying where permits are uncertain, using unlike comps, underestimating setup cash, high leverage, weak reserves, and assuming a manager will solve a poor property. Flood, wildfire, insurance and HOA exposure can change the economics. Inspection and local rule checks belong in the contract diligence period.'),
    ('Ownership is still active oversight', 'Even with a manager, the owner approves capital spending, monitors guest and maintenance problems, checks financial reporting, and responds to rule or insurance changes. Compare self-management with a paid operator before selecting a deal. <a href="/management/">See management responsibilities</a>.'),
    ('Where tax strategy fits', 'Depreciation, material participation and other tax rules depend on individual facts. A tax benefit cannot rescue an uneconomic purchase. Have a qualified tax adviser review facts and records before relying on any offset. <a href="/tax-strategy/">Read the STR tax overview</a>.'),
    ('A practical decision path', 'Set cash and reserve limits, select a legally viable market, compare true rental comps, model all expenses, obtain financing terms, inspect the property, confirm permit rights, and prepare the launch. If you want acquisition help, review the <a href="/how-it-works/">service process</a> and request the fee and scope in writing.')], links=[('/buy-a-short-term-rental/','How to buy an STR'),('/airbnb-investment-property/','Evaluate an investment property'),('/financing/','Financing and entry cash'),('/guides/str-investment/','Browse detailed buying guides')])
]

def make(p):
    path=p['path']; trail=[('Home','/'),(p['h1'],path)]
    blocks=''.join(f'<section class="{"bg-alt" if i%2 else ""}"><div class="wrap wrap-narrow"><h2>{heading}</h2><p>{copy}</p></div></section>' for i,(heading,copy) in enumerate(p['sections']))
    links=''.join(f'<li><a href="{url}">{label}</a></li>' for url,label in p['links'])
    body=(f'<section class="hero hero-page"><div class="wrap">{tpl.breadcrumb_html(trail)}<div class="hero-inner"><span class="eyebrow">{p["label"]}</span><h1>{p["h1"]}</h1><p class="hero-sub">{p["lead"]}</p><div class="btn-row"><a class="btn btn-accent btn-lg" href="/apply/">Book a Call</a><a class="btn btn-ghost-light btn-lg" href="/case-studies/">See Client Purchases</a></div></div></div></section>'+
      blocks+f'<section><div class="wrap wrap-narrow"><h2>Continue your research</h2><ul>{links}</ul></div></section>'+tpl.cta_band('Review a real purchase plan','Discuss your budget, market criteria, and the work needed before making an offer.'))
    schema=tpl.graph(tpl.breadcrumb_schema(trail),tpl.ORG_SCHEMA)
    file=ROOT/path.strip('/')/'index.html'; file.parent.mkdir(exist_ok=True,parents=True)
    file.write_text(tpl.page(title=p['title'],description=p['description'],path=path,body=body,extra_schema=schema,body_class='blog'),encoding='utf-8')

if __name__=='__main__':
    # The buying hub is maintained by gen_buyer_workbook.py.
    for p in PAGES:
        if p['path'] != '/buy-a-short-term-rental/':
            make(p)
