#!/usr/bin/env python3
"""A first-purchase cash planner, distinct from the operating-return calculator."""
from pathlib import Path
import tpl
ROOT=Path(__file__).resolve().parents[1]
PATH='/tools/first-str-purchase-budget/'
TITLE='First STR Purchase Budget Calculator | BNB Accelerator'
DESC='Buying your first STR? Calculate down payment, closing cash, furnishing, repairs, service fees and reserves. Check your cash gap before searching properties.'
fields=[('price','Target property price ($)',400000),('down','Assumed down payment (%)',20),('closing','Estimated closing costs ($)',12000),('furnishing','Furniture and guest-ready setup ($)',25000),('repairs','Repairs and launch work ($)',10000),('fees','Quoted acquisition and other service fees ($)',0),('reserve','Cash you plan to retain for this property ($)',20000),('available','Cash allocated to this purchase ($)',150000)]
inputs=''.join(f'<div class="field"><label for="budget-{id}">{label}</label><input id="budget-{id}" name="{id}" type="number" min="'+('0.01' if id=='down' else '0')+'" '+('max="100" ' if id=='down' else '')+f'step="0.01" value="{value}" required></div>' for id,label,value in fields)
body=f'''<section class="hero hero-page"><div class="wrap">{tpl.breadcrumb_html([('Home','/'),('Tools','/tools/'),('First STR Purchase Budget',PATH)])}<div class="hero-inner"><span class="eyebrow">Before your first purchase</span><h1>How much cash do you need to buy your first STR?</h1><p class="hero-sub">Build a first-property cash plan before setting a listing price filter. Separate the down payment from closing, setup and the cash you need to keep after buying.</p></div></div></section>
<section><div class="wrap wrap-narrow"><article class="article"><p class="lead">If you are ready to buy your first Airbnb investment property, start with the complete cash commitment. This planner helps you compare a candidate purchase with the funds you have allocated, then turn the result into questions for a lender and acquisition team.</p><p>Published October 1, 2026. All starting inputs are hypothetical examples, not prices, lender requirements or a BNB Accelerator service quote. A zero fee means you have not entered a quote; it does not mean the service is free.</p>
<div id="first-str-budget"><form id="first-str-budget-form"><h2>Build your first STR purchase budget</h2><div class="field-row">{inputs}</div><p>Use the lender’s actual down-payment requirement and address-specific cost estimates. Include each cash use only once. If a cost is financed, document that treatment rather than silently omitting it.</p><button class="btn btn-primary" type="submit">Calculate My Purchase Cash</button></form><div id="first-str-budget-results" aria-live="polite" role="status"></div><p>Your inputs are used for the calculation in this page; they are not submitted, emailed or saved by this planner.</p></div><noscript><p>JavaScript is off. Use the worked example and cash equation below, or the <a href="/buy-a-short-term-rental/acquisition-budget-worksheet/">purchase cash worksheet</a>.</p></noscript>
<h2>A worked first-STR cash calculation</h2><table><thead><tr><th>Cash use</th><th>Hypothetical amount</th><th>Evidence to request</th></tr></thead><tbody><tr><td>20% of a $400,000 price</td><td>$80,000</td><td>Lender terms for the intended investment use</td></tr><tr><td>Closing costs</td><td>$12,000</td><td>Current lender and closing-professional estimates</td></tr><tr><td>Furniture and setup</td><td>$25,000</td><td>Itemized quote including delivery and installation</td></tr><tr><td>Repairs and launch work</td><td>$10,000</td><td>Inspection findings, bids and a separate opening plan</td></tr><tr><td>Service fees</td><td>$0 entered</td><td>Add the current written quote before relying on the total</td></tr><tr><td>Retained cash reserve</td><td>$20,000</td><td>Your reserve policy and lender liquidity conditions</td></tr><tr><td>Total cash allocated</td><td>$147,000 before any unentered fee</td><td>Reconcile each use against available funds</td></tr></tbody></table><p>With $150,000 allocated, these assumptions leave $3,000. A hypothetical $10,000 service quote changes the total to $157,000 and produces a $7,000 cash gap. Do not treat the initial $3,000 as spare money until missing costs and retained funds have been verified.</p>
<h2>Use the result to set a search ceiling</h2><p>The cash-only price ceiling is available purchase cash minus closing, setup, repairs, service fees and retained reserves, divided by the assumed down-payment fraction. With the initial example, ($150,000 − $12,000 − $25,000 − $10,000 − $0 − $20,000) ÷ 0.20 = $415,000. Adding the hypothetical $10,000 fee reduces that ceiling to $365,000.</p><p>This is a cash-planning bound, not a loan approval, affordability recommendation or offer price. It holds the other inputs fixed. Closing costs, repairs, insurance and required reserves may change with the address or price. If a lender approves less, or the property’s economics support less, the lower constraint governs your search. A cash purchase can be modeled with 100% down.</p>
<h2>Before choosing a property to buy</h2><ol><li><strong>Get the financing conditions.</strong> State the intended STR investment use and ask which properties and rental evidence fit the loan. The <a href="https://www.consumerfinance.gov/owning-a-home/explore/get-a-preapproval-letter/" rel="noopener">CFPB explains that preapproval is conditional</a>, rather than a guaranteed loan offer. Confirm the process that applies to your investment loan.</li><li><strong>Verify each address separately.</strong> Local permission, association rules, insurance and property condition can eliminate a listing even if the purchase cash fits. Review the <a href="/buy-a-short-term-rental/listing-screening-scorecard/">listing screening scorecard</a>.</li><li><strong>Separate accepted loan income from projected revenue.</strong> Fannie Mae’s <a href="https://selling-guide.fanniemae.com/sel/b3-3.8-03/rental-income-subject-property-short-term-rental" rel="noopener">current subject-property STR income guidance</a> addresses eligible one-unit investment properties legally permitted for STR use and specific documentation. Ask the lender what evidence it accepts; a seller projection is not an approval.</li><li><strong>Test operating cash flow.</strong> This planner covers purchase cash, not future income. Use the <a href="/tools/str-revenue-calculator/">STR operating revenue calculator</a> and a <a href="/underwriting/downside-scenario/">downside case</a> before deciding what the deal is worth.</li></ol><p>Source links checked October 1, 2026. Program terms and local requirements may change; verify the actual purchase with the relevant professionals.</p>
<h2>Bring a usable brief to your first-property call</h2><ul><li>Available purchase cash and the reserve you intend to retain.</li><li>Financing review status, lender conditions and any unresolved documents.</li><li>One or two target markets and property listing links, if available.</li><li>Property price, setup budget, evidence gaps and your intended owner responsibilities.</li><li>The work you want help with: sourcing, analysis, purchase coordination or launch planning.</li></ul><p>BNB Accelerator does not lend money or approve a loan. Review <a href="/done-for-you-airbnb/">help buying your first Airbnb</a>, <a href="/pricing/">service pricing questions</a> and the <a href="/buy-a-short-term-rental/">first-STR buyer roadmap</a>, then <a href="/apply/">book a first-property acquisition discussion</a>.</p></article></div></section>
{tpl.cta_band('Turn your cash plan into a first-STR search','Bring your budget, financing status and candidate listing to a purchase discussion.',('/apply/','Discuss My First STR'),('/buy-a-short-term-rental/','Follow the Buyer Roadmap'))}
<script src="/assets/first-str-budget.js?v=20261001a" defer></script>'''
trail=[('Home','/'),('Tools','/tools/'),('First STR Purchase Budget',PATH)]
p=ROOT/'tools/first-str-purchase-budget/index.html';p.parent.mkdir(parents=True,exist_ok=True);p.write_text(tpl.page(title=TITLE,description=DESC,path=PATH,body=body,extra_schema=tpl.graph(tpl.breadcrumb_schema(trail),tpl.ORG_SCHEMA),active='/buy-a-short-term-rental/'))
print('Generated first-STR purchase cash planner')
