"""Source-checked existing entity architecture guide, distinct from LLC yes/no."""
import improve_dscr_term_sheet as editor

BODY='''<p class="lead">Choose an STR purchase structure by aligning the intended title owner, approved borrower, tax classification, insurance and rental permissions before an offer becomes binding. Forming an LLC answers none of those questions by itself. A high-income buyer should not assume the entity creates deductions, eliminates personal loan exposure or can receive the deed later without review.</p>
<p><a href="/apply/">Book a call to screen an STR acquisition against your lender- and adviser-reviewed ownership plan</a>.</p>
<h2>Prepare a purchase-structure record with separate approvals</h2>
<p>Use the same proposed owner names and property address across the lender, attorney, closing agent, insurer and permitting authority. Record who has answered each question, the document supporting the answer and unresolved conditions. An incorporation certificate is not a financing approval, insurance binder or rental license. Reconcile disagreements before changing the contract or releasing protection.</p>
<div class="table-scroll"><table><thead><tr><th>Decision before purchase</th><th>Evidence to obtain</th><th>Failure to avoid</th></tr></thead><tbody>
<tr><td>Title and control</td><td>Proposed vesting, owners, manager and signing authority reviewed by counsel/closing agent</td><td>A named buyer unable to sign or take the intended title</td></tr>
<tr><td>Borrowing and individual exposure</td><td>Lender-approved borrower and proposed note/guarantee documents</td><td>Treating LLC title as nonrecourse financing</td></tr>
<tr><td>Tax classification</td><td>CPA review of owners, elections, activity and applicable filing obligations</td><td>Assuming entity formation creates a usable deduction</td></tr>
<tr><td>Insurance</td><td>Written review of title, named insureds, STR use, limits, exclusions and coverage start</td><td>Assuming a personal umbrella automatically covers commercial rental use</td></tr>
<tr><td>Rental permission and state administration</td><td>Address/owner-specific authority response and required registrations, fees and deadlines</td><td>Assuming a seller license or out-of-state formation settles eligibility</td></tr>
</tbody></table></div>
<p>The <a href="/blog/llc-for-short-term-rental/">LLC choice guide</a> addresses whether an LLC may fit. This page organizes the complete purchase structure and approval sequence. For joint funding, use the <a href="/blog/str-partnership-structure/">partner contribution worksheet</a>; for individual debt exposure, read the <a href="/blog/personal-guarantee-llc-str-purchase-loan/">guarantee review</a>. Neither substitutes for the remaining approvals.</p>
<h2>Confirm the borrower now and any transfer later</h2>
<p><a href="https://selling-guide.fanniemae.com/sel/b2-2-01/general-borrower-eligibility-requirements" rel="noopener">Fannie Mae's borrower eligibility guidance</a> generally requires natural-person borrowers, with specified exceptions, and addresses individual title and note liability. Do not present this as a rule for every mortgage product. Ask your lender whether your actual investment STR, occupancy and proposed entity fit the selected program. Obtain a different written financing path if entity borrowing is essential; do not assume a DSCR label guarantees eligibility or a particular rate premium.</p>
<p>Do not rely on a promise to close personally and fix title afterward. Equally, do not assume every LLC transfer automatically produces acceleration. <a href="https://servicing-guide.fanniemae.com/svc/d1-4.1-02/allowable-exemptions-due-type-transfer" rel="noopener">Fannie Mae's transfer guidance</a> includes an LLC exemption conditioned on the loan having been purchased or securitized by Fannie Mae on or after June 1, 2016, original-borrower control or majority ownership, and compliance with the security instrument's occupancy requirements. It also addresses returning title to a natural person to meet Fannie Mae refinance eligibility. Those conditions are not blanket permission for your loan.</p>
<p>Before planning a transfer, have the servicer and counsel identify the applicable investor rules, required process, documents and effect on liability. Ask the closing agent about title coverage, recording and possible local charges, and the insurer and permitting authority about ownership changes. A transfer of title does not itself release debt. If a future refinance is essential to the purchase, test a scenario where that refinance is unavailable.</p>
<h2>Keep tax classification separate from liability and insurance</h2>
<p>The <a href="https://www.irs.gov/businesses/small-businesses-self-employed/single-member-limited-liability-companies" rel="noopener">IRS single-member LLC guidance</a> generally treats an LLC without a corporate election as disregarded for federal income tax; employment and certain excise taxes have separate treatment. This is not a claim that all federal, state or local obligations match personal ownership. Ask your CPA about classification, elections, reporting and the actual rental activity before choosing a structure.</p>
<p>An entity name does not establish material participation, qualify every STR loss against salary or guarantee a cost-segregation result. Multi-owner arrangements require separate review; ownership percentages do not establish each person's usable losses. Build the purchase budget without an assumed immediate refund, using the <a href="/blog/str-tax-benefit-shortfall-purchase/">smaller or delayed tax-benefit decision test</a>.</p>
<p>Have a property-state attorney explain the proposed entity's protection, limitations, personal conduct and signed obligations. Separate accounts and records support administration but are not a universal guarantee against claims. Insurance and entity planning answer different questions; neither matters only after a claim exceeds a policy limit. Ask a licensed insurer which actual risks and persons are covered, which are excluded and whether any umbrella applies to the intended STR activity.</p>
<h2>Budget the architecture before selecting an offer</h2>
<p>Hypothetical administrative comparison only, not state fees, adviser quotes, insurance pricing or a lending recommendation. Suppose the otherwise approved purchase and launch require $220,000 including separately retained reserves, against $225,000 designated cash. A professionally reviewed one-entity proposal adds $1,800 in initial administration and requires a $1,200 first-year administration cash allowance. Total capital becomes $223,000, leaving $2,000 unallocated.</p>
<p>A proposed two-entity arrangement instead adds $4,000 initially and a $2,400 first-year administration allowance, producing $226,400 total and a $1,400 shortfall. These assumed costs exclude any changes in financing, insurance or local transfer charges; obtain actual quotes and remove overlaps with the original budget. The cheaper proposal is not thereby legally better, and two entities do not automatically provide maximum isolation. The example identifies a cash question for advisers, not a liability valuation.</p>
<p>For multiple properties or a holding-company proposal, ask counsel to map ownership and creditor exposure and your CPA to identify filing obligations. Record each state's actual formation, foreign-registration and annual requirements rather than declaring Delaware, Wyoming or the property state universally best. Count recurring administration in the operating model as well as its cash timing; retained liquidity is not an additional expense.</p>
<h2>Resolve the structure before the contractual deadline</h2>
<p>Proceed when the parties approve a consistent ownership plan, its actual costs fit and the property works independently of promised tax savings. Renegotiate the price or choose an approved simpler structure if costs breach available capital. Delay only under valid purchase protection while a decisive approval is outstanding. Reject a deal that depends on an undisclosed transfer, unapproved borrower or coverage nobody will confirm.</p>
<p>Give your acquisition team the approved names, funding limits and unresolved items before it negotiates. BNB Accelerator supports its contracted acquisition work; independent advisers and authorities determine their respective approvals. <a href="/apply/">Book a call to compare STR properties that fit your documented ownership, financing and cash plan</a>.</p>
<p class="small">Primary sources checked October 6, 2026. Educational information, not legal, tax, insurance, lending or personalized investment advice. All amounts are hypothetical. Obtain qualified advice and current written terms. No liability shield, loan approval, transfer permission, tax benefit or investment result is guaranteed.</p>
<h2 id="faq">Frequently asked questions</h2>'''
FAQ=[
('Do I need an LLC before buying an STR?','Not automatically. Align proposed title, financing, tax classification, insurance and rental permission with qualified advisers before committing. LLC formation alone does not establish approval, create a deduction or eliminate individual loan exposure.'),
('Can I transfer an STR to an LLC after closing?','Do not assume either blanket permission or automatic acceleration. Applicable loan and investor rules may contain specific exemptions. Obtain a transaction-specific servicer and counsel review, including title, insurance, rental permission and future refinance consequences.'),
('Should I use one entity or multiple entities for an STR purchase?','Compare actual ownership, financing, legal exposure, registrations, administration and cash requirements with advisers. A lower-cost structure is not automatically better protected, and more entities do not automatically provide maximum isolation.')]

if __name__=='__main__':
    editor.SLUG='str-entity-structure-basics';editor.TITLE='STR Purchase Entity Structure: Align Title and Financing'
    editor.DESC='Plan an STR purchase entity structure with approved title, borrowing, tax classification and insurance. Compare costs before committing to an offer.'
    editor.BODY=BODY;editor.FAQ=FAQ;editor.main()
    hub=editor.ROOT/'blog/buy-str-high-income-large-tax-bill/index.html';s=hub.read_text();assert 'data-entity-purchase-plan-link' not in s
    block='<p data-entity-purchase-plan-link>Before choosing how to hold your acquisition, align <a href="/blog/str-entity-structure-basics/">STR title, borrower, tax classification and insurance approvals</a>; an entity certificate is not a complete purchase plan.</p>'
    hub.write_text(s.replace('<div class="author-box">',block+'\n<div class="author-box">',1))
