#!/usr/bin/env python3
"""How each market actually moved through 2021 to 2026.

One line per market per year. Combined with the year block in era.py and the
performance ranges in market_data.json, this is what makes a 2022 Broken Bow
post argue something different from a 2025 Broken Bow post.
"""

ARCS = {
    "austin": {
        2021: "Austin absorbed a wave of relocation and tech hiring, and short-term rental demand rose alongside a housing market that was among the hottest in the country.",
        2022: "The licensing fight that had been running for years continued in the courts while prices peaked, which made Austin a market where the legal position mattered more than the demand.",
        2023: "Cooling tech employment took some heat out of the market at the same time borrowing costs rose, and the event calendar carried more of the year than it had.",
        2024: "The market stabilised around its event calendar, and buyers increasingly looked to unincorporated Hill Country land rather than inside city limits.",
        2025: "Hill Country inventory outside city ordinances continued to be the more workable route, with Austin proper reserved for buyers who had confirmed their licensing position.",
        2026: "Austin is an event-compression market with a contested regulatory history, and most of our Texas activity sits in the Hill Country rather than inside the city.",
    },
    "big-bear": {
        2021: "Los Angeles drive demand overwhelmed Big Bear as travellers avoided flying, and cabins filled at rates the market had not seen.",
        2022: "Local pressure over housing and short-term rental density began building toward the permit restrictions that would follow.",
        2023: "San Bernardino County tightened, and the permit question moved ahead of the property question for anyone buying here.",
        2024: "Caps and density restrictions defined the market, and an existing transferable permit became a material part of a property's value.",
        2025: "The two-season profile kept demand solid while the regulatory position kept the buyer pool thin.",
        2026: "Big Bear has excellent demand geography and one of the harder permit regimes in the country, which is the whole trade.",
    },
    "branson": {
        2021: "Branson's drive-to entertainment economy recovered quickly, and Table Rock Lake absorbed families who would previously have flown somewhere.",
        2022: "The lake and the show corridor both ran strong, and the Ozarks cost basis kept returns healthy while other markets repriced.",
        2023: "Branson held up better than most through the correction because its cost basis was low enough to absorb softer rates.",
        2024: "Supply growth stayed modest and the autumn group traffic continued to give the market a genuine second season.",
        2025: "Branson remained one of the more forgiving markets to underwrite, with two demand drivers and a low entry price.",
        2026: "Branson West on Table Rock is still one of the few lake markets with a real second season, which is why it keeps appearing in our inventory.",
    },
    "broken-bow": {
        2021: "Broken Bow was still a regional secret, and Dallas-Fort Worth demand discovered it in volume during the drive-market boom.",
        2022: "Cabin construction accelerated sharply as investors followed the returns, and the luxury A-frame segment established itself.",
        2023: "The supply that had been under construction arrived, and rate compression began in exactly the way rapid inventory growth predicts.",
        2024: "Hochatown's incorporation created a local government where there had effectively been none, adding a regulatory dimension the market had not had.",
        2025: "Differentiation replaced scarcity as the thing that decided performance, with design-forward cabins holding rates that generic builds could not.",
        2026: "Broken Bow remains one of the strongest cabin markets by demand and one of the most supply-exposed, so basis and design carry the deal.",
    },
    "cape-coral": {
        2021: "Southwest Florida drew an unusual volume of both snowbird and relocation demand, and waterfront inventory moved quickly.",
        2022: "Hurricane Ian in September was the defining event, disrupting the market and beginning a long insurance repricing.",
        2023: "Rebuilding continued while insurance costs rose sharply, and underwriting a Southwest Florida property became substantially harder.",
        2024: "The snowbird season reasserted itself and the market functioned normally again, with insurance now a major line rather than a footnote.",
        2025: "Buyers who modelled insurance honestly found workable deals; buyers using a percentage rule of thumb did not.",
        2026: "Cape Coral and Fort Myers peak in February on snowbird demand, which pairs well against summer-peaking markets in a portfolio.",
    },
    "denver": {
        2021: "Denver's short-term rental market ran into its primary-residence licensing rule, which kept investors out of the city proper even as demand rose.",
        2022: "Investor attention moved to the mountain markets, which then began adopting their own caps.",
        2023: "Summit County and other resort communities adopted licence caps and zone classes, tightening the whole Colorado picture.",
        2024: "Colorado began debating a commercial property tax classification for short-term rentals, adding a cost risk on top of the permit risk.",
        2025: "The direction of travel across Colorado stayed toward restriction, and our activity in the state stayed selective.",
        2026: "Denver proper is closed to conventional investment purchases, and the surrounding jurisdictions have to be verified parcel by parcel.",
    },
    "destin": {
        2021: "Emerald Coast demand was extraordinary as drive-to beach travel surged, and prices rose faster than most buyers had budgeted for.",
        2022: "Prices peaked while rates rose, and the gap between what sellers wanted and what the numbers supported opened.",
        2023: "Coastal insurance repricing became the dominant cost story, and buyers who had modelled inland insurance found their returns had moved.",
        2024: "The market stabilised at a higher cost base, with the long Gulf season continuing to give Destin more billable weeks than Atlantic markets.",
        2025: "Value submarkets like Fort Walton Beach drew more of our activity than premium 30A, on cash-on-cash grounds.",
        2026: "Destin still commands the highest rates on the Gulf, and distance to a beach access point remains the variable that decides them.",
    },
    "gatlinburg": {
        2021: "The Smokies had the strongest year in their history as drive-to national park travel surged and cabins filled at unprecedented rates.",
        2022: "Cabin prices peaked, and buyers were paying for 2021 revenue with 2022 financing costs.",
        2023: "Occupancy normalised from the 2021 peak while supply continued arriving, and the corridor's spread between well-run and poorly-run cabins widened.",
        2024: "Demand held up on the strength of the deepest visitor base in the country, and amenity fit rather than novelty decided which cabins performed.",
        2025: "The market functioned normally with hot tub, view and game room established as the baseline rather than as differentiators.",
        2026: "Gatlinburg is closest to the park entrance with the most walkable downtown, and remains a distinct submarket from Pigeon Forge and Sevierville.",
    },
    "gulf-shores": {
        2021: "Alabama's Gulf Coast filled with drive-to family demand from across the Southeast, and the market ran well beyond its usual season.",
        2022: "Prices rose while the season stayed concentrated in summer, compressing returns for buyers paying peak prices.",
        2023: "Coastal insurance repricing hit Alabama alongside Florida, and condominium assessments became a live underwriting item.",
        2024: "The family beach economy reasserted itself, and single-family houses with private pools separated further from condominium inventory.",
        2025: "Registration and licensing remained straightforward, keeping regulatory risk low relative to comparable beach markets.",
        2026: "Gulf Shores and Orange Beach remain among the easiest beach markets to operate in, with condo rules the main constraint.",
    },
    "joshua-tree": {
        2021: "Design-led desert rentals became a cultural phenomenon, and Los Angeles demand pushed rates on architecturally distinctive properties to remarkable levels.",
        2022: "Supply arrived quickly as investors chased the aesthetic, and the differentiation that had driven rates began to erode at the generic end.",
        2023: "San Bernardino County tightened, adding caps and density restrictions that made the permit position the first question.",
        2024: "Density rules meant a permit could be unavailable because of what neighbours held, which is not assessable from a listing.",
        2025: "The design premium held for genuinely remarkable properties and disappeared for competent ones.",
        2026: "Joshua Tree is one of very few markets where design is close to a fundamental, set against county restrictions that keep the buyer pool small.",
    },
    "kissimmee": {
        2021: "Theme park reopening drove a rapid recovery, and multi-generational groups booked resort homes as an alternative to hotel rooms.",
        2022: "Construction in the resort communities continued at scale, adding inventory to an already deep market.",
        2023: "The corridor's supply depth meant rate competition intensified, and differentiation through theming and amenities became decisive.",
        2024: "The market settled into a differentiation-driven equilibrium where review score and pool heating separated the pricing tiers.",
        2025: "Per-bedroom cost stayed the lowest of any major market, which kept the corridor attractive for capacity-driven buyers.",
        2026: "Champions Gate and Davenport still deliver roughly $81,000 to $87,500 per bedroom, and still demand real differentiation to perform.",
    },
    "lake-tahoe": {
        2021: "Tahoe absorbed enormous Bay Area drive demand across both seasons, and inventory that had been sleepy performed unusually well.",
        2022: "Local pressure over housing and short-term rental density built across multiple jurisdictions around the lake.",
        2023: "Permit caps and restrictions tightened on both sides of the lake, and the jurisdictional map became the first thing to establish.",
        2024: "Wildfire insurance availability became a live constraint alongside the permit position.",
        2025: "The two-season profile kept demand strong while diligence requirements stayed higher than almost anywhere we operate.",
        2026: "Tahoe spans five permitting jurisdictions with different rules, and the permit question outranks the property question.",
    },
    "nashville": {
        2021: "Nashville's group travel demand returned quickly, and permitted whole-house rentals near downtown performed strongly.",
        2022: "The non-owner-occupied permit restriction by zoning district became the defining feature of the investment case.",
        2023: "The permit cap protected operators from the supply growth that compressed rates in unregulated markets.",
        2024: "Event-driven compression nights continued to carry a disproportionate share of annual revenue.",
        2025: "The long-term rental floor stayed genuinely strong on healthcare employment and population growth, which is what makes the permit premium rational.",
        2026: "Nashville is the clearest example of a capped market where the permit is a large part of what you are buying.",
    },
    "panama-city-beach": {
        2021: "Spring break and summer demand surged, and Panama City Beach's value position against Destin drew a wave of investor interest.",
        2022: "Prices rose from a low base while remaining well below the premium Emerald Coast submarkets.",
        2023: "Insurance repricing hit here as across the Gulf, and the value thesis depended increasingly on modelling that cost honestly.",
        2024: "The long season from spring break through an autumn shoulder continued to give the market more billable weeks than Atlantic comparables.",
        2025: "Entry prices stayed accessible relative to Destin and 30A, keeping cash-on-cash returns competitive.",
        2026: "Panama City Beach remains the value entry into Gulf Coast ownership, with a longer season than its price implies.",
    },
    "park-city": {
        2021: "Ski demand rebounded strongly and Park City's summer economy grew, giving the market two genuine seasons.",
        2022: "Prices rose sharply at the top of the market while zone restrictions kept the investable inventory narrow.",
        2023: "High borrowing costs weighed on a market with high absolute prices, and buyers focused on resort-zoned inventory.",
        2024: "The established summer season continued to differentiate Park City from single-season ski markets.",
        2025: "Condominium and homeowner association rules remained the binding constraint on much of the base-area inventory.",
        2026: "Park City works because its summer is real, and where you can operate is decided by zone and by declaration.",
    },
    "phoenix-mesa": {
        2021: "Snowbird and relocation demand surged, and Arizona's state preemption of municipal bans made the metro unusually easy to operate in.",
        2022: "Supply grew quickly as investors recognised the regulatory advantage, and the summer trough remained severe.",
        2023: "Rate competition increased in a deep market, and heated pools separated the pricing tiers more sharply.",
        2024: "Arizona's preemption continued to insulate the metro from the permit risk affecting comparable California markets.",
        2025: "Spring training and the winter season carried the year, and the summer trough stayed a budgeting exercise rather than a surprise.",
        2026: "Phoenix and Mesa remain among the most regulatorily stable large markets in the country, with an inverted calendar that pairs well in a portfolio.",
    },
    "poconos": {
        2021: "New York and Philadelphia drive demand overwhelmed the Poconos, and properties that had been marginal performed strongly.",
        2022: "Township-level ordinances began appearing across Monroe and Carbon counties in response to the growth.",
        2023: "The regulatory patchwork deepened, and private community declarations became as decisive as township rules.",
        2024: "Four genuine seasons kept the annual revenue curve flatter than most vacation markets even as rates normalised.",
        2025: "Verification per parcel remained the defining diligence requirement, and the drive catchment remained the largest in the country.",
        2026: "The Poconos have roughly thirty million people within two hours and a regulatory map that has to be checked township by township.",
    },
    "scottsdale": {
        2021: "Scottsdale filled with winter escape demand, and Arizona's preemption made it one of the more comfortable markets to enter.",
        2022: "Event compression around spring training and the WM Phoenix Open returned to full strength.",
        2023: "Supply growth increased competition, and heated pools and outdoor living became the baseline rather than a differentiator.",
        2024: "Old Town and North Scottsdale continued to diverge into genuinely different investment propositions.",
        2025: "Nuisance and noise enforcement tightened operationally while the underlying right to operate stayed protected by state law.",
        2026: "Scottsdale has some of the most extreme event compression in the country, layered on a severe summer trough.",
    },
    "sedona": {
        2021: "Sedona's constrained housing stock met surging outdoor and wellness travel, and rates rose sharply.",
        2022: "Local political friction over housing and short-term rentals intensified as the share of converted stock grew.",
        2023: "The city pressed against the limits of what Arizona preemption allows, using licensing and nuisance enforcement.",
        2024: "Supply could not expand because of the surrounding national forest, which protected rates through the wider correction.",
        2025: "The flat calendar and constrained supply kept Sedona performing while friction with residents continued.",
        2026: "Sedona combines exceptional demand with a housing stock that cannot grow, and state law that prevents a ban but not the argument.",
    },
    "smoky-mountains": {
        2021: "The Smokies recorded the strongest year in the corridor's history as national park visitation and drive-to travel peaked together.",
        2022: "Cabin prices peaked and large-cabin inventory in particular commanded prices that assumed 2021 revenue would persist.",
        2023: "Occupancy normalised while supply continued to arrive, and seller proformas built on peak-season extrapolation became actively dangerous.",
        2024: "The deepest visitor base in the country absorbed the added supply better than smaller markets did.",
        2025: "Amenity fit against the comparable set decided performance, with hot tub, view and game room the established baseline.",
        2026: "The corridor remains our most-transacted market, with Sevierville, Pigeon Forge and Gatlinburg behaving as three distinct submarkets.",
    },
}
