#!/usr/bin/env python3
"""First-STR purchase intent layer. Run after other content generators."""
from pathlib import Path
import re,json,html
import tpl
from gen_city_buying_guides import ROWS
ROOT=Path(__file__).resolve().parents[1]
DATE='2026-10-01'
HUB='/buy-a-short-term-rental/'
TOOL='/tools/first-str-purchase-budget/'
CONFIG={
'index.html':('Buy Your First Short-Term Rental | BNB Accelerator','Ready to buy your first STR? BNB Accelerator helps you source, evaluate and purchase an Airbnb investment property. Discuss your budget and search plan.','Buy Your First Short-Term Rental'),
'buy-a-short-term-rental/index.html':('Buy Your First STR: Property Buying Guide | BNB Accelerator','Buying your first short-term rental? Set your cash budget, get financing reviewed, find properties for sale and check a deal before making an offer.','Buy Your First Short-Term Rental: The Buyer Roadmap'),
'done-for-you-airbnb/index.html':('Help Buying Your First Airbnb | BNB Accelerator','Get acquisition help for your first Airbnb investment property: sourcing, deal analysis, purchase coordination and launch planning. Review costs and scope.','Help buying your first Airbnb investment property'),
'short-term-rental-investment-service/index.html':('First STR Acquisition Support | BNB Accelerator','Compare first-time STR acquisition support: shortlist, property evidence, offers and launch responsibilities. Review written service scope before hiring a team.','Short-term rental acquisition support for first-time buyers'),
'airbnb-investment-property/index.html':('Buy an Airbnb Investment Property | BNB Accelerator','Looking to buy your first Airbnb investment property? Evaluate legal use, cash needed, financing and net returns before making an offer.','Buying your first Airbnb investment property'),
'airbnb-investment-company/index.html':('Airbnb Property Buying Services | BNB Accelerator','Choosing a company to help buy your first Airbnb? Compare acquisition deliverables, fees, ownership and buyer responsibilities before you commit.','Choose an Airbnb property buying service for your first STR'),
'financing/index.html':('First STR Financing: Compare Loan Options | BNB Accelerator','Buying your first STR with financing? Compare loan options, lender conditions, down payment, closing cash and reserves before searching for a property.',None),
'underwriting/cash-needed-to-buy/index.html':('Cash Needed to Buy Your First STR | BNB Accelerator','Calculate the cash needed to buy your first short-term rental: down payment, closing costs, setup, service fees and reserves. Build a complete purchase budget.','How much cash do you need to buy your first STR?'),
'blog/how-to-buy-first-airbnb/index.html':('How to Buy Your First Airbnb Property | BNB Accelerator','Ready to buy your first Airbnb? Follow the property search, financing, due diligence and offer sequence, with a checklist for your next purchase decision.','How to buy your first Airbnb investment property'),
'blog/how-to-find-str-properties-for-sale/index.html':('Find STR Properties for Sale to Buy | BNB Accelerator','Looking for your first STR to buy? Find Airbnb investment properties for sale, build a shortlist and verify the address, costs and income before an offer.',None),
'blog/buy-existing-airbnb-vs-start-from-scratch/index.html':('Buy an Existing Airbnb or Set One Up? | BNB Accelerator','Buying your first STR? Compare an existing Airbnb with an unfurnished property using verified revenue, transfer requirements, launch cash and owner costs.',None),
'blog/buying-airbnb-out-of-state/index.html':('Buy Your First Airbnb Out of State | BNB Accelerator','Buy your first Airbnb out of state with an address-specific diligence plan, local professionals and a verified operating handoff before closing.',None),
'blog/str-mortgage-preapproval-before-property/index.html':('STR Mortgage Preapproval Before You Buy | BNB Accelerator','Ready to buy your first STR? Get borrower financing reviewed, then verify the address, legal use and loan conditions before making an offer.',None),
'blog/compare-two-str-properties-before-offer/index.html':('Compare STR Properties Before You Buy | BNB Accelerator','Choosing your first STR? Compare two properties on legal use, verified income, all-in cash and downside economics before you make an offer.',None),
'blog/index.html':('First STR Buying Guides & Research | BNB Accelerator','Buying your first short-term rental? Start with property search, financing, purchase budget and due diligence guides, then explore the wider STR library.','Buying your first STR: start with the purchase decision'),
'apply/index.html':('Discuss Buying Your First STR | BNB Accelerator','Ready to buy your first short-term rental? Book a free call to discuss your purchase budget, financing, target markets and acquisition support.','Let’s discuss your first STR purchase'),
}

def update(file,title,desc,h1=None):
 p=ROOT/file;s=p.read_text();s=re.sub(r'<title>.*?</title>',lambda _: '<title>'+html.escape(title)+'</title>',s,count=1,flags=re.S)
 for attr,key,value in [('name','description',desc),('property','og:title',title),('property','og:description',desc),('name','twitter:title',title),('name','twitter:description',desc)]:
  tag=f'<meta {attr}="{key}" content="{html.escape(value,quote=True)}">'
  pattern=rf'<meta {attr}="{key}" content="[^"]*"\s*/?>'
  if re.search(pattern,s):s=re.sub(pattern,lambda _:tag,s,count=1)
  else:s=s.replace('</head>',tag+'\n</head>',1)
 if h1:s=re.sub(r'<h1[^>]*>.*?</h1>',lambda _: '<h1>'+html.escape(h1)+'</h1>',s,count=1,flags=re.S)
 def schema(m):
  obj=json.loads(m[2]);nodes=obj.get('@graph',[obj])
  for node in nodes:
   if node.get('@type') in ['Article','BlogPosting','WebPage']:
    node['description']=desc
    node['headline' if node.get('@type') in ['Article','BlogPosting'] else 'name']=h1 or title
    if node.get('@type') in ['Article','BlogPosting']:node['dateModified']=DATE
  return m[1]+json.dumps(obj,ensure_ascii=False)+m[3]
 s=re.sub(r'(<script[^>]*type="application/ld\+json"[^>]*>)(.*?)(</script>)',schema,s,flags=re.S)
 p.write_text(s)

def block(file,body,early=False):
 p=ROOT/file;s=p.read_text();s=re.sub(r'<!-- first-str:start -->.*?<!-- first-str:end -->','',s,flags=re.S)
 b='<!-- first-str:start --><section class="bg-alt"><div class="wrap wrap-narrow">'+body+'</div></section><!-- first-str:end -->'
 if early:
  m=re.search(r'<section\b[^>]*class="[^"]*hero[^\"]*".*?</section>',s,re.S)
  if m:s=s[:m.end()]+b+s[m.end():]
  else:s=s.replace('</main>',b+'</main>',1)
 else:s=s.replace('</main>',b+'</main>',1)
 p.write_text(s)

for file,args in CONFIG.items():update(file,*args)
p=ROOT/'index.html';s=p.read_text();s=re.sub(r'(<p class="hero-sub"[^>]*>).*?(</p>)',r'\1Ready to buy your first Airbnb investment property? We help you define the search, evaluate real deals, and coordinate the purchase and launch. You provide the capital and make the final decision.\2',s,count=1,flags=re.S);s=s.replace('>Book a Call</a>\n          <a class="btn btn-ghost-light btn-lg" href="/case-studies/">Review Client Deals</a>','>Discuss My First STR</a>\n          <a class="btn btn-ghost-light btn-lg" href="/buy-a-short-term-rental/">See the Buyer Roadmap</a>',1);p.write_text(s)
block('index.html',f'''<span class="eyebrow">Your first purchase</span><h2>Looking for your first STR to buy?</h2><p>Start with a property search you can fund. Build your <a href="{TOOL}">first-STR purchase budget</a>, compare <a href="/markets/">target markets</a>, and use our <a href="/blog/how-to-find-str-properties-for-sale/">STR property search guide</a> to turn listings into a shortlist. If you want help sourcing and coordinating the purchase, review the <a href="/done-for-you-airbnb/">first-Airbnb acquisition service</a>.</p>''',True)
block('buy-a-short-term-rental/index.html',f'''<span class="eyebrow">First-time STR buyers</span><h2>Ready to buy your first STR? Choose your next step.</h2><p>Your first STR purchase starts with the cash you can commit, the property you can finance, and the evidence needed before an offer. This roadmap is for buyers who want to own a short-term rental and are preparing to search, shortlist or buy.</p><table><thead><tr><th>Your position today</th><th>Complete next</th><th>Bring to a purchase discussion</th></tr></thead><tbody><tr><td>I have capital but no property</td><td><a href="{TOOL}">Build a first-STR cash plan</a>, then <a href="/blog/str-mortgage-preapproval-before-property/">confirm financing guardrails</a></td><td>Available cash, loan conditions, desired markets and ownership plan</td></tr><tr><td>I am searching listings now</td><td><a href="/blog/how-to-find-str-properties-for-sale/">Find and screen properties for sale</a></td><td>Two or three listing links and the cash required for each</td></tr><tr><td>I found an existing Airbnb</td><td><a href="/blog/buy-existing-airbnb-vs-start-from-scratch/">Check the existing-business handoff</a></td><td>Seller operating records, included furnishings, permits and proposed transition</td></tr><tr><td>I am ready to make an offer</td><td><a href="/blog/compare-two-str-properties-before-offer/">Compare the deal and downside</a></td><td>Address-specific evidence, unresolved conditions and your maximum offer</td></tr><tr><td>I want a team to help buy</td><td><a href="/done-for-you-airbnb/">Review first-Airbnb acquisition support</a> and <a href="/pricing/">service costs</a></td><td>Your purchase brief and questions about written deliverables</td></tr></tbody></table><p><a class="btn btn-primary" href="/apply/">Discuss My First STR Purchase</a></p><p>Updated October 1, 2026. A target purchase date is a planning goal; financing, inspections, legal use and seller negotiations determine what can actually close.</p>''',True)
for file in CONFIG:
 if file in ['index.html','buy-a-short-term-rental/index.html','blog/index.html','apply/index.html']:continue
 block(file,f'''<h2>Turn this research into your first STR purchase</h2><p>If you are looking to buy now, connect this decision to your <a href="{HUB}">first-STR buyer roadmap</a>. Use the <a href="{TOOL}">first purchase cash planner</a>, obtain <a href="/blog/str-mortgage-preapproval-before-property/">property financing conditions</a>, and bring your budget or candidate listing to a discussion of <a href="/done-for-you-airbnb/">acquisition help for your first Airbnb</a>.</p><p><a class="btn btn-primary" href="/apply/">Discuss My First STR Purchase</a></p>''')
block('blog/index.html',f'''<h2>Start here if you want to buy your first STR</h2><ul><li><a href="{HUB}">First STR buyer roadmap</a>: move from budget to a property decision.</li><li><a href="{TOOL}">First STR purchase budget calculator</a>: see cash needed and the gap to your available funds.</li><li><a href="/blog/how-to-find-str-properties-for-sale/">Find short-term rentals for sale</a>: build a property shortlist.</li><li><a href="/blog/str-mortgage-preapproval-before-property/">Finance the purchase</a>: establish lender guardrails before choosing an address.</li><li><a href="/blog/compare-two-str-properties-before-offer/">Compare properties before an offer</a>: decide on a consistent evidence and cost basis.</li><li><a href="/done-for-you-airbnb/">Get help buying your first Airbnb</a>: review service scope and responsibilities.</li></ul><p>The wider article library below supports deeper due diligence and ownership questions.</p>''',True)
p=ROOT/'blog/index.html';s=p.read_text();s=re.sub(r'(<p class="hero-sub"[^>]*>).*?(</p>)',r'\1Find a property to buy, establish financing, work out the cash needed and check the deal before your first STR offer. Start with the buyer guides, then use the wider library for deeper research.\2',s,count=1,flags=re.S);p.write_text(s)
p=ROOT/'apply/index.html';s=p.read_text().replace('Choose a time below to discuss your short-term rental goals, budget, and timeline. The first call is free and there is no obligation.','Choose a time to discuss buying your first short-term rental. Bring your available cash, financing status, preferred markets and any property links. The first call is free and there is no obligation.');s=s.replace('<div class="calendar-embed">','<p><a href="/tools/first-str-purchase-budget/">Prepare your first-STR purchase budget</a> before the call.</p><div class="calendar-embed">',1);p.write_text(s)
for row in ROWS:
 slug,city,state,profile,alt1,alt2,checks=row
 file=f'markets/{slug}/best-short-term-rentals/index.html'
 update(file,f'Buy an Airbnb in {city} | BNB Accelerator',f'Buying your first STR in {city}? Compare property types, cash needed and address checks. Discuss your property search with BNB Accelerator.',f'Buying your first short-term rental in {city}')
 block(file,f'''<h2>Build a first-property shortlist in {city}</h2><p>For a first STR purchase in {city}, {state}, compare {profile} against your available cash and operating plan. Your shortlist should identify {checks} for each address, with an evidence owner and an unresolved-question list. A guide to property types is not a live listing feed or a statement that a particular property is for sale.</p><ol><li>Calculate your <a href="{TOOL}">first-STR purchase budget</a> before setting a price filter.</li><li>Read the <a href="/markets/{slug}/">{city} market guide</a>, then verify facts for the parcel and association.</li><li>Discuss search and transaction work with a <a href="/markets/{slug}/airbnb-real-estate-agent/">{city} Airbnb buyer’s agent</a> and request separate written agreements for any acquisition support.</li><li>Bring two listing links, available cash and financing conditions to an <a href="/apply/">acquisition discussion for your first {city} STR</a>.</li></ol>''',True)
# Discovery hubs: one link owns the broad first-buyer intent instead of creating synonyms as duplicate pages.
for file in ['guides/index.html','tools/index.html','markets/index.html','financing/index.html']:
 block(file,f'''<h2>Buying your first short-term rental?</h2><p>Use the <a href="{HUB}">first-STR buyer roadmap</a> to choose your next purchase step. Build a <a href="{TOOL}">cash budget for your first STR</a>, shortlist <a href="/blog/how-to-find-str-properties-for-sale/">properties for sale</a>, and review <a href="/done-for-you-airbnb/">help buying your first Airbnb</a> before you book a call.</p>''',file=='markets/index.html')
# Homepage and shared navigation prioritize first purchase. Preserve existing route URLs.
p=ROOT/'_gen/tpl.py';s=p.read_text().replace('("/scenarios/", "Scenarios")','("/buy-a-short-term-rental/", "First STR")');p.write_text(s)
print(f'First-STR intent applied: {len(CONFIG)} core pages, {len(ROWS)} local buyer guides and discovery hubs')
# Replace the older first-Airbnb walkthrough's universal financing/timeline claims
# with an actionable purchase file. The hub remains the task directory.
from pillars import sections_html
sections=[
('1. Write a buy box you can fund',[
 'If you are ready to buy your first Airbnb, write down the cash you can allocate, the liquidity you must retain, the markets you will investigate and the owner work you will accept. Specify a price ceiling, property type, guest profile and the evidence that would make you reject a deal. A first purchase should have a written boundary before you open a listing portal.',
 'Use the <a href="/tools/first-str-purchase-budget/">first-STR purchase cash planner</a>. It separates down payment, closing, furnishing, repairs, service fees and retained reserves. Its inputs are planning assumptions, not lender requirements. Keep a separate personal emergency fund outside the cash you allocate to the property.']),
('2. Confirm financing before searching seriously',[
 'Tell the lender the intended investment use and discuss your borrower profile, available funds and property guardrails. Ask what remains conditional, which property types qualify and what cash must remain after closing. A maximum approval amount is one constraint, not the amount you should automatically spend.',
 'The <a href="https://www.consumerfinance.gov/owning-a-home/explore/get-a-preapproval-letter/" rel="noopener">CFPB explains that a preapproval is not a guaranteed loan offer</a>. Get the actual address reviewed before relying on that letter for a purchase. Use our <a href="/blog/str-mortgage-preapproval-before-property/">STR preapproval guide</a> to organize lender questions.']),
('3. Find properties for sale that fit the first-property plan',[
 'Search ordinary homes as well as listings advertised as existing Airbnbs. A furnished listing can reduce some setup work but may come with maintenance, association fees or transition problems. A listing label does not prove that STR use is legal, the bookings will continue, or its revenue will be yours after closing.',
 'Use the <a href="/blog/how-to-find-str-properties-for-sale/">STR property search guide</a> and the <a href="/markets/">local buying guides</a>. Keep a shortlist with listing links, asking price, jurisdiction, property type, estimated setup and missing evidence. Avoid spending the entire search period on a home that has not passed the basic gates.']),
('4. Build the property decision file before an offer',[
 ('table',['Question','Evidence to obtain','What remains uncertain'],[
 ['Can this address operate as intended?','Parcel jurisdiction, current permit path and association documents','Written permission, transfer conditions or unresolved restrictions'],
 ['What can it earn under my ownership?','Reconciled seller records and relevant comparable rentals','Availability, operating changes and seasonal downside'],
 ['What will ownership cost?','Taxes, STR insurance, management terms, utilities and repair bids','Reassessment, exclusions and expenses omitted from a projection'],
 ['Can I finance and insure this property?','Lender address review, appraisal conditions and an insurance quote','Approval conditions and costs before contingencies expire'],
 ['What am I buying besides the building?','Included inventory, contracts, deposits and proposed handoff','Items that do not transfer or need new agreements']]),
 'For financing that relies on property rent, ask what evidence the lender accepts. Fannie Mae’s <a href="https://selling-guide.fanniemae.com/sel/b3-3.8-03/rental-income-subject-property-short-term-rental" rel="noopener">subject-property STR rental-income guidance</a> applies to eligible, legally permitted one-unit investment properties and specifies documentation. Seller forecasts and loan qualification are different checks.']),
('5. Convert the cash plan into a price decision',[
 'Illustrative first-buyer case: you allocate $150,000. A $400,000 purchase at an assumed 20% down uses $80,000 for the deposit. Add $12,000 closing costs, $25,000 setup, $10,000 repairs, a hypothetical $10,000 service fee and $20,000 retained reserves. The total is $157,000, creating a $7,000 gap. These are invented planning inputs, not a typical deal or a BNB service quote.',
 'With those non-deposit cash uses held fixed, the cash-only price ceiling is ($150,000 − $12,000 − $25,000 − $10,000 − $10,000 − $20,000) ÷ 0.20 = $365,000. This does not establish what the house is worth or what a lender will approve. Resolve the gap, negotiate a supportable price, change the scope, choose another property or pause. Do not double-count lender reserves as money available for furniture.',
 'Next, test owner cash flow with address-specific expenses and a downside revenue case. Use the <a href="/blog/compare-two-str-properties-before-offer/">property comparison framework</a> rather than buying the highest advertised gross revenue.']),
('6. Make an offer that preserves unresolved checks',[
 'Give your licensed buyer representative a clear maximum price and a list of conditions that still need verification. Ask the appropriate professionals to align inspection, financing, appraisal, insurance, permitted use and inventory questions with the contract deadlines. Track who must provide each document and when the purchase commitment changes.',
 'The offer memo should identify the evidence supporting the price, the cash required, the downside case and the conditions that would trigger a renegotiation or rejection. The <a href="/buy-a-short-term-rental/investment-memo-template/">investment memo worksheet</a> keeps that decision explicit.']),
('7. Verify the handoff before you treat the purchase as ready',[
 'An existing Airbnb is not automatically a transferable business. Confirm which furnishings, agreements, guest obligations and operating records are included, and what must be established in your own name. Agree with the relevant professionals on the lawful treatment of reservations, deposits, permits and access; do not assume a host account or rating history becomes yours.',
 'For a new setup, verify quotes, access, contractors, utilities, guest-safety work and the management agreement before choosing an opening target. Ownership and a guest-ready operation are separate milestones. Use the <a href="/buy-a-short-term-rental/launch-handoff-checklist/">launch handoff checklist</a>.']),
('8. Choose the work you want an acquisition team to coordinate',[
 'For a first STR, acquisition support can coordinate sourcing, analysis, transaction milestones and launch planning. You still provide the capital, approve material decisions and separately engage the professionals who perform their contracted work. Ask for deliverables, fees, exclusions and payment timing in writing.',
 'Review <a href="/done-for-you-airbnb/">help buying your first Airbnb</a>, <a href="/pricing/">pricing and the full purchase budget</a> and <a href="/case-studies/">property-specific client examples</a>. If you want to discuss a purchase now, bring available cash, financing status, preferred markets and one or two listing links to a <a href="/apply/">first-STR acquisition call</a>.']),
('Questions first-time STR buyers ask',[
 ('h3','How much money do I need to buy my first Airbnb?'),'There is no universal amount. Add the lender’s required down payment, actual closing costs, setup, repairs, quoted service fees and the cash you intend or are required to retain. Model the address and your financing rather than assuming that a generic percentage covers everything.',
 ('h3','Can BNB Accelerator help me find a first STR to buy?'),'Review the acquisition scope and current written proposal. BNB coordinates property sourcing and purchase work; the website is not a live listing feed and the client makes the purchase decision.',
 ('h3','Should my first STR be an existing Airbnb?'),'Compare legal use, seller evidence, included inventory, total cash, transition work and operating costs. An existing rental may simplify some work, but current bookings or advertised revenue do not prove the result under your ownership.',
 ('h3','How fast can I buy and open my first STR?'),'Set a target, then build a schedule from the contract, lender review, inspections, permitted use, property condition and vendors. No general timeline guarantees that a particular property will close or open by your desired date.']),
]
path='/blog/how-to-buy-first-airbnb/';title,desc,h1=CONFIG['blog/how-to-buy-first-airbnb/index.html'];trail=[('Home','/'),('Buying Guides','/blog/'),('Buying Your First Airbnb',path)]
body=f'''<section class="hero hero-page"><div class="wrap">{tpl.breadcrumb_html(trail)}<div class="hero-inner"><span class="eyebrow">First-property buying guide</span><h1>{h1}</h1><p>Published August 9, 2026 · Updated October 1, 2026</p></div></div></section><section><div class="wrap wrap-narrow"><article class="article"><p class="lead">Ready to buy your first short-term rental? Build a funded search, a property decision file and a clear offer ceiling. This walkthrough takes you from available capital to a purchase decision; use the <a href="/buy-a-short-term-rental/">buyer roadmap</a> to jump to the worksheet for your current stage.</p>{sections_html(sections)}<p>Primary source links checked October 1, 2026. Financing, local permission and costs must be verified for your own property and loan.</p></article></div></section>{tpl.cta_band('Bring your first-property plan to the call','Discuss your cash budget, financing status and candidate property before you commit.',('/apply/','Discuss My First STR'),('/tools/first-str-purchase-budget/','Build My Purchase Budget'))}'''
(ROOT/'blog/how-to-buy-first-airbnb/index.html').write_text(tpl.page(title=title,description=desc,path=path,body=body,extra_schema=tpl.graph(tpl.breadcrumb_schema(trail),tpl.ORG_SCHEMA)+'\n'+tpl.article_schema(h1,desc,tpl.SITE+path,'2026-08-09',DATE,section='First STR Purchase'),body_class='blog',active=HUB))
