"""Prewriting Oct6:95=25distinct/29buyer/14evidence/18fit/9original.
Can my self-directed IRA buy an STR? Whole HTML inventory matches only
incidental coachingpage; read full pension/guarantee guides, distinct account
purchase contract, deposit and paid launch rather than income eligibility.
IRS590A prohibited transactions and 990T IRA/UDFI instructions relevant
sections read, EquityTrust STR/expense/nonrecourse primary read. No volume,
tax savings, service approval, universal lender eligibility or client results.
"""
import blog

POSTS = [{
    "slug": "self-directed-ira-buy-short-term-rental",
    "title": "Can Your Self-Directed IRA Buy a Short-Term Rental?",
    "title_tag": "Self-Directed IRA STR Purchase: Before You Make an Offer",
    "h1": "Can your self-directed IRA buy a short-term rental?",
    "description": "Buying an STR through a self-directed IRA? Check the buyer name, account-paid deposit, nonrecourse financing and launch cash before making an offer.",
    "date": "2026-10-06", "category": "STR Purchase Structure",
    "lead": "Potentially, but an IRA-owned STR is not a personally owned vacation rental funded with retirement money. The account's purchase, payment and financing rules must work before you sign an offer, and personal stays cannot be part of the investment plan. Have your custodian, qualified legal and tax advisers, lender and closing team review the actual structure. This guide is for someone preparing to buy a specific STR in the next zero to six months, not general retirement-account education. <a href=\"/apply/\">Book a call to evaluate the underlying STR purchase after your professionals establish an executable account-owned acquisition path</a>; do not assume an ordinary buyer contract or service-payment arrangement fits an IRA.",
    "sections": [
        ("Choose account ownership before choosing the STR contract", [
            "Start with the intended purchaser: direct IRA ownership, a professionally reviewed IRA-owned entity, or a personally owned purchase using independently reviewed distributions. Those are different transactions. Ask your custodian for the exact buyer and vesting instructions, required direction forms, authorized signatures and document sequence. Align the offer, escrow file, lender application and closing documents before making the deposit nonrefundable.",
            "<a href=\"https://www.trustetc.com/blog/investing-airbnb-rentals-retirement-account/\" rel=\"noopener\">Equity Trust's STR-investment discussion</a> confirms that a self-directed retirement account can potentially purchase an STR, with distinct rules. That establishes a possible structure—not suitability, property approval or acceptance by every custodian. Ask your actual custodian whether it supports the specific ownership, rental use, vendors and transaction. Do not mistake account administration for independent property underwriting.",
            ("table", ["Decision before the offer", "IRA-owned purchase", "Personally owned purchase"], [
                ["Buyer and title", "Custodian-directed account or reviewed entity instructions", "Actual individual or entity purchaser"],
                ["Earnest money and costs", "Account-funded transaction and approved payment process", "Documented personal purchase sources"],
                ["Rental cash", "Account-controlled receipts and expenses", "Owner cash subject to applicable obligations"],
                ["Personal stays", "Do not build them into an IRA investment plan", "Separate loan, legal-use and tax review still needed"],
                ["Loan", "Reviewed nonrecourse account-financing path if financed", "Actual lender's borrower and guarantee requirements"],
            ]),
            "The <a href=\"/blog/pension-retirement-income-buy-str/\">pension and retirement-income guide</a> addresses personally owned purchases supported by income. It does not authorize the IRA itself to buy. Similarly, withdrawing account money and personally buying a property is not the same as account ownership. Have independent advisers evaluate any distribution consequences; this page does not recommend withdrawals or a rollover to make a deal fit.",
        ]),
        ("Screen personal use and related parties before due diligence spending", [
            "Before paying for inspections or drafting the offer, disclose the seller, intended users, service providers and financing parties to your advisers. Is the seller you or a person related to you? Do you expect your household to vacation there? Do you intend to manage, furnish or improve it yourself? Do not answer those questions after committing account money. The acquisition structure must support the actual intended behavior, not only the title printed on a deed.",
            "The prohibited-transaction discussion in <a href=\"https://www.irs.gov/publications/p590a\" rel=\"noopener\">IRS Publication 590-A</a> lists improper traditional-IRA use by the owner, beneficiary or disqualified persons. Examples include selling property to the IRA, borrowing from it, pledging it for a loan and buying property for present or future personal use. Its listed family categories include spouses, ancestors, lineal descendants and descendants' spouses. This is not a complete legal opinion on every related party or transaction; obtain qualified review of your actual participants.",
            "The same IRS discussion says an owner or beneficiary's prohibited transaction generally causes the affected traditional IRA to cease being an IRA from the first day of that year, with its assets treated as distributed and potential taxes or penalties. Do not reduce that risk to a minor paperwork fee or assume a later reimbursement fixes it. If a transaction has already occurred, pause and obtain advice rather than improvising a cure.",
            "For the purchase decision, reject the IRA-owned path when family vacations or a personally controlled rescue plan are essential to why you want the property. Ask advisers about services, compensation and disqualified-person restrictions before engaging vendors or performing work. Independently review another ownership path if it can legally support your goals; do not evade restrictions with a nominal entity or someone else's signature.",
        ]),
        ("Confirm financing and account-paid cash before the deposit deadline", [
            "Do not carry an ordinary personal DSCR approval into an IRA purchase. Ask the actual lender whether it finances the account's proposed structure and this property's intended short stays. Obtain the borrower, collateral, recourse, underwriting, appraisal, reserve and document requirements. A lender offering IRA real-estate loans has not necessarily accepted your STR address or operating plan.",
            "<a href=\"https://www.trustetc.com/self-directed-ira/real-estate/non-recourse-lending/\" rel=\"noopener\">Equity Trust's nonrecourse guidance</a> describes property-only collateral, without liability for other account assets or the account holder personally. Its debt-financed purchase process requests investment direction and loan documents with correct titling and funding, and requires mortgage payments from the account. Use the actual custodian's instructions and professional review; do not sign a personal guarantee to rescue a loan represented as an IRA financing path.",
            "Our <a href=\"/blog/personal-guarantee-llc-str-purchase-loan/\">LLC personal-guarantee guide</a> covers a different purchase structure. Merely putting LLC on a contract does not establish IRA-compatible financing. Ask counsel to reconcile every proposed note, guarantee and collateral document. If no suitable lender accepts the actual rental use, compare a feasible account-cash purchase or another professionally reviewed acquisition—not an undocumented promise to replace the loan after closing.",
            "<a href=\"https://www.trustetc.com/blog/real-estate-expenses-self-directed-account/\" rel=\"noopener\">Equity Trust's expense guidance</a> says account-owned property expenses and proceeds must flow through the account and the earnest-money deposit must come from it. It warns about personal payment followed by reimbursement. Arrange the custodian's payment request and document review before the contract's deadline. Do not use a personal check or card while expecting the account to take over later.",
        ]),
        ("Fund the STR's opening inside the actual account purchase budget", [
            "The account must have a workable launch plan, not just enough money for a down payment. Obtain actual estimates for acquisition costs, furnishing, required work, insurance, permits, management and account administration. Ask the custodian and advisers how contracts, invoices, payments and platform receipts must be set up. Check any acquisition-service fee and its payer before engagement; do not assume BNB Accelerator's ordinary arrangement is approved for an IRA-owned transaction.",
            "Illustrative only—not a lender quote, account recommendation or required reserve: suppose an IRA has $230,000 of accessible cash and a proposed $400,000 STR purchase uses an independently reviewed $240,000 nonrecourse loan. The $160,000 down payment leaves $70,000 in account cash. Assume $13,000 closing and transaction costs, $29,000 preparation and furnishings, and $5,000 initial administration and opening expenses. The remaining account cash is $23,000. Reconcile any already-paid account deposit against the $160,000 rather than adding it twice.",
            "If the property-specific downside plan requires retaining $30,000, the example has a $7,000 gap. A separate personal checking balance is not automatically permitted purchase or operating liquidity for the IRA property. Do not cover the difference by paying the furnishing invoice yourself and seeking reimbursement. Ask professionals about lawful funding options, an effective reduction in cash uses, a different property or waiting; do not assume an unrestricted extra contribution or a hurried transfer is available.",
            "Do not underwrite every dollar earned inside an IRA as automatically untaxed. The <a href=\"https://www.irs.gov/instructions/i990t\" rel=\"noopener\">IRS Form 990-T instructions</a> include IRAs in their filing discussion and address unrelated debt-financed income separately from other taxable business income. Have a qualified tax adviser review this property's debt and services and include applicable taxes and compliance costs in the purchase model. This is not a Form 990-T calculation, a statement that every STR produces taxable income, or a tax-savings forecast.",
            "Require a separately supported property case: address-specific legal STR use, verified seller records where applicable, conservative revenue, professional operating costs and a launch timetable that the account can fund. Custodian acceptance is not evidence those facts are sound. Use the <a href=\"/underwriting/downside-scenario/\">downside purchase framework</a> without assuming free owner labor, personal stays counted as paid nights or an unlimited personal cash bailout.",
        ]),
        ("Make the offer only after the account-owned execution plan passes", [
            "Proceed when the custodian and qualified advisers confirm the actual transaction path, titling and payments are aligned, any lender accepts the intended STR, account cash funds closing and launch, and the property's supported economics and legal use pass. Renegotiate price or deadlines when a verified cash or processing constraint changes feasibility. Delay when required instructions, approved documents or financing evidence are missing. Reject the IRA purchase path when it depends on personal use, a personal guarantee or an unreviewed personal-payment workaround.",
            "Prepare a buyer file with the custodian's transaction instructions, reviewed participant list, lender conditions if financed, account-funded deposit plan, approved launch-payment process and property-specific downside budget. Record who must approve, sign and fund each step and by which contractual date. Do not make a seller's short closing demand your reason to bypass the actual purchaser's requirements.",
            "<a href=\"/apply/\">Book a call to compare STR acquisitions that fit your professionally reviewed purchaser and funding structure</a>. BNB Accelerator can discuss property sourcing, underwriting and acquisition coordination, but is not an IRA custodian, nonrecourse lender or provider of a prohibited-transaction opinion. Confirm service scope and payment treatment before hiring. If this account structure cannot execute the purchase, review an independently supportable alternative rather than force the transaction.",
            "Primary sources were reviewed October 6, 2026. This is educational information, not personalized tax, legal, retirement, lending or investment advice. Obtain independent qualified advice and use secure channels for financial documents; never share passwords. Every model number is illustrative. Financing, account acceptance, permits, bookings, sale timing and investment results are not guaranteed.",
        ]),
    ],
    "faqs": [
        ("Can a self-directed IRA buy an Airbnb investment property?", "Potentially. Confirm the actual custodian-supported buyer structure, account-paid purchase and launch, any accepted financing, and independent legal and tax review before offering. Property legality and economics still require separate diligence."),
        ("Can I pay an IRA STR's earnest money personally and get reimbursed?", "Do not use that workaround. The cited custodian guidance calls for account-funded earnest money and warns about personal payments and reimbursement. Arrange the approved account payment before the contract deadline."),
        ("Can my family use an STR purchased by my IRA?", "Do not include personal stays in the account's investment plan. The referenced IRS guidance identifies buying property for present or future personal use as a prohibited-transaction example. Have qualified advisers review the actual users and participants."),
        ("Does an ordinary LLC DSCR loan qualify for an IRA-owned STR purchase?", "Do not assume so. The account needs an independently reviewed financing structure accepted by the actual custodian and lender for the intended rental use. Entity title alone does not establish nonrecourse or IRA compatibility."),
    ],
    "related": [
        '<a href="/blog/str-lender-reserve-requirements/">Separate lender conditions from usable launch reserves</a>',
        '<a href="/tools/first-str-purchase-budget/">List the full purchase-and-launch cash uses</a>',
        '<a href="/how-it-works/">Define property acquisition support before engagement</a>',
    ],
    "cta_h": "Align the STR purchase with the actual account buyer",
    "cta_p": "Confirm the professionally reviewed structure, account-funded closing and launch plan before comparing properties or making an offer.",
}]

if __name__ == "__main__":
    blog.build(POSTS)
