"""Oct6 prewriting95=25intent/30buyer/13evidence/18fit/9original.
Can I buy a manufactured home as an STR? Existing full HTML and post search
find only incidental mentions; full ADU, mixed-use, second-home-intent pages
read: no dedicated HUD-code vs modular collateral/acquisition funding guide.
Current primary Fannie B5-2-02 investment exclusion, B2-3-02 modular treatment,
Freddie manufactured occupancy, HUD description and TitleI occupancy read.
Real manufactured-Airbnb buyer question appears in search; no volume claim.
Not a property-type swap: construction evidence controls loan availability,
title/land interest and a cash shortfall before earnest money hardens.
"""
import blog

POSTS = [{
    "slug": "buy-manufactured-home-short-term-rental",
    "title": "Can You Buy a Manufactured Home as a Short-Term Rental?",
    "title_tag": "Buying a Manufactured Home as an STR: Financing First",
    "h1": "Can you buy a manufactured home as a short-term rental?",
    "description": "Buying a manufactured home as an STR? Verify HUD-code versus modular status, land title, investment financing and full purchase cash before offering.",
    "date": "2026-10-06", "category": "Acquisition Financing",
    "lead": "Potentially, but do not make an STR offer using a conventional investment-property loan assumption just because the home sits on a foundation and includes land. A manufactured home's construction classification can eliminate that assumed financing path; a modular home is a different category. If you intend to buy in the next zero to six months, establish the actual property type, ownership interest, legal rental use and accepted funding before committing earnest money. <a href=\"/apply/\">Book a call to compare the proposed manufactured-home STR purchase with properties your documented funding can actually acquire</a>. Confirm that BNB Accelerator's service scope covers the candidate; this guide is not a claim that every manufactured property or loan is available through the service.",
    "sections": [
        ("Identify what the manufactured-home STR offer would buy", [
            "Get the classification from records, not the listing's use of cabin, mobile, prefab or modular. Request the manufacturer's information, construction and installation records, any HUD identifiers, recorded deed and legal description, and any separate home-title document. Send the file to the actual lender, title professional and appropriate building authority. They should identify the home, land interest and proposed security before you choose a contract or rely on a loan quote.",
            "<a href=\"https://www.hud.gov/hud-partners/manufactured-home-resources\" rel=\"noopener\">HUD's homeowner resource</a> describes manufactured homes as built to the HUD Code, transported on a permanent chassis and identified by certification labels. That construction classification is not determined by furniture, siding or a seller's description. A permanent foundation does not by itself establish that a HUD-code manufactured home is a modular home for the loan you want.",
            "Fannie Mae's <a href=\"https://selling-guide.fanniemae.com/sel/b2-3-02/special-property-eligibility-and-underwriting-considerations-factory-built-housing\" rel=\"noopener\">factory-built housing guidance</a> separates manufactured homes from modular and other specified factory-built housing. It treats qualifying modular homes as site-built housing under the applicable requirements, including real-property status, local codes and permanent attachment. Do not apply the modular category based on resemblance. Have the lender confirm which documented category and current program govern this property.",
            ("table", ["Record to resolve", "What the buyer needs to know", "Decision before offering"], [
                ["Construction classification", "HUD-code manufactured versus documented modular or another category", "Which property eligibility rules actually apply"],
                ["Home title and land interest", "Home plus land, home-only interest, or leased site", "What transfers and what can secure the proposed loan"],
                ["Actual intended use", "Income-producing short stays and any personal occupancy", "Which loan and legal-use approvals fit the truth"],
                ["Accepted financing", "Specific lender acceptance of both collateral and rental plan", "Whether the quoted loan belongs in the offer budget"],
            ]),
        ]),
        ("Do not assume ordinary manufactured-home mortgages fund an STR investment", [
            "The direct financing issue is occupancy and program eligibility, not simply whether manufactured homes can ever obtain mortgages. <a href=\"https://guide-selling.fanniemae.com/sel/b5-2-02/manufactured-housing-loan-eligibility\" rel=\"noopener\">Fannie Mae's manufactured-housing loan topic</a> lists investment properties as ineligible. Its eligible occupancy categories are principal residences and specified second homes. A qualifying foundation or real-property title does not remove that investment-property exclusion.",
            "<a href=\"https://sf.freddiemac.com/working-with-us/origination-underwriting/mortgage-products/manufactured-homes\" rel=\"noopener\">Freddie Mac's manufactured-home overview</a> likewise says an investment-property mortgage secured by a manufactured home is not eligible for sale to Freddie Mac. Its overview directs lenders to the governing guide and purchase documents. These are constraints on the specified agency paths, not a statement that every lender prohibits every manufactured rental or that cash ownership is illegal.",
            "Describe your actual rental plan accurately. Do not certify a primary residence or second home merely to access a loan when the facts do not fit. Our <a href=\"/blog/second-home-loan-rental-intent/\">second-home rental-intent guide</a> addresses that separate occupancy question. Manufactured collateral eligibility still needs its own answer. Adding occasional personal stays or improving projected nightly income is not evidence that a previously excluded investment transaction is accepted.",
            "Nor is a government home-only program an automatic substitute. <a href=\"https://www.hud.gov/hud-partners/single-family-finance-manuf\" rel=\"noopener\">HUD's Title I page</a> says eligible borrowers must intend to occupy the manufactured home as their principal residence. Do not present it as an owner-absent STR financing solution. If you seek another lender, obtain its current, specific acceptance of the construction type, home age and history, land interest, borrower and intended short stays before relying on terms.",
            "Ask: Does your proposed investment program accept this documented manufactured home and its actual STR use? What title, foundation, insurance, appraisal, loan-size and cash requirements apply? Which conditions remain? Does the approval cover this address or only the borrower? A generic DSCR advertisement or manufactured-home quote is not the answer to that combined eligibility question. Do not invent another lender's acceptance just because its website mentions rentals.",
        ]),
        ("Resolve land and home title without confusing them with STR permission", [
            "Find out whether the seller is conveying the home with owned land, the home on a leased site, or an interest inside a project. Ask your title professional or attorney to reconcile ownership, liens, separate title records and the legal description. Ask what documents and releases are needed for your actual closing under state law. A deed to a parcel is not a substitute for verifying that the transaction also transfers the intended home and clears applicable encumbrances.",
            "The cited Fannie Mae loan topic requires the manufactured home and the borrower's land interest to secure the loan and be legally classified as real property for that program. It contains limited project-related leased-land provisions; do not turn those exceptions into blanket acceptance of park sites. Investment eligibility remains a separate hurdle. The cited HUD Title I page also distinguishes home-only and home-and-lot arrangements and real versus personal-property treatment. Those distinctions help frame questions; they do not authorize your investment loan or decide local title law.",
            "If the site is leased, obtain the complete current lease, transfer requirements, rental restrictions, fees and termination or renewal terms. Have counsel explain whether the intended guest use and buyer's occupancy arrangement fit the documents. Underwrite the actual site charges and a supported downside rather than valuing a home-only interest as fee-simple land ownership. Do not assume a lease can be assigned or amended just because the seller currently receives guests.",
            "Separately obtain address-specific legal STR-use evidence, relevant project or park permission and insurance for the actual construction and guest activity. A HUD label establishes a construction fact, not an Airbnb permit. A local rental approval does not establish loan eligibility. Keep those answers separate in the acquisition file, and use the <a href=\"/regulations/\">regulation library</a> only as a starting point for current local verification.",
        ]),
        ("Rebuild the offer budget when assumed financing disappears", [
            "Illustrative only—not a lender quote, appraisal or recommended leverage: suppose a buyer has $130,000 accessible and models a $250,000 manufactured-home STR using a hypothetical $175,000 loan. The $75,000 down payment plus $12,000 closing and transaction costs, $18,000 launch spending and $20,000 retained downside cash total $125,000. That leaves $5,000 beyond the modeled requirement. The calculation is meaningful only if the actual lender accepts this property and intended use.",
            "If the loan is unavailable and the buyer proposes paying cash without changing the other illustrative amounts, required liquidity becomes $300,000: $250,000 purchase plus $12,000 costs, $18,000 launch and $20,000 retained cash. Against $130,000 available, the gap is $170,000. Reprice actual costs for the new financing path; some may change. Even if a price negotiation improves the model, a modest seller credit does not automatically replace an unavailable $175,000 loan.",
            "Do not make the deposit nonrefundable while assuming you can find a replacement loan after appraisal. Independently verify an alternative program and its complete cash and repayment requirements, delay until funding is established, compare another property or reject this purchase. Seller financing also needs its own professionally reviewed terms; it is not a cure for unclear title, prohibited guest use or unsupported operating economics. Do not borrow against another asset without evaluating that separate obligation and the remaining purchase liquidity.",
            "For a candidate that is documented as modular, rerun the lender's actual terms rather than copying a generic manufactured-home rejection or assuming automatic approval. Compare both properties on verified total cash, conservative net income, legal use, operating costs and exit constraints. Use the <a href=\"/tools/first-str-purchase-budget/\">purchase-and-launch budget</a> and <a href=\"/underwriting/downside-scenario/\">downside model</a>. Construction classification changes the financing question; it does not guarantee bookings, appreciation or an easy resale.",
        ]),
        ("Set classification and funding deadlines before earnest money hardens", [
            "Proceed when the records identify the property, the closing team confirms the ownership transfer, the specific funding path accepts the actual rental use, legal and insurance requirements pass, and the complete purchase-and-launch model remains viable. Renegotiate price or contract timing when a verified cost or document delay can be addressed. Delay if construction classification, title or lender conditions are still unresolved. Reject the deal when required income depends on prohibited short stays or the purchase cannot be funded without an unsupported loan or occupancy statement.",
            "Before the offer becomes binding beyond your permitted protections, give your broker and attorney the unresolved classification and funding issues. Have them define the appropriate diligence, document and financing provisions for the transaction and applicable law. Name who must deliver each answer and by what deadline. Do not assume a generic inspection contingency preserves every lender, title or site-lease concern.",
            "Bring the construction records, home and land-title file, proposed rental plan, lender's property-specific conditions and full cash budget to the acquisition conversation. <a href=\"/apply/\">Book a call to compare this manufactured-home purchase with executable STR alternatives</a>. BNB Accelerator can discuss sourcing, underwriting, negotiation and purchase coordination where the service fits; qualified lenders, title professionals, attorneys, insurers and local officials decide matters within their roles. Confirm scope before engagement rather than assuming specialized collateral work is included.",
            "Primary sources reviewed October 6, 2026. Educational information only, not individualized lending, legal, tax or investment advice. All worked-model amounts are illustrative. Use qualified independent professionals and secure channels for documents; never share account passwords. No financing approval, title outcome, rental permission, bookings, sale proceeds or returns are guaranteed.",
        ]),
    ],
    "faqs": [
        ("Can I buy a manufactured home to use as an Airbnb investment?", "Potentially, if the actual ownership transfer, legal rental use, insurance, funding and economics support it. The cited agency manufactured-housing paths exclude investment properties, so verify a feasible funding plan before offering."),
        ("Does a permanent foundation make a manufactured home modular for an STR mortgage?", "Do not assume so. Establish the construction classification from records and have the actual lender apply its program. Foundation and title conditions do not themselves erase the cited manufactured investment-property exclusion."),
        ("Can FHA Title I finance an owner-absent manufactured STR purchase?", "Do not present that program as an automatic substitute. HUD's cited page requires eligible borrowers to intend principal-residence occupancy. Accurately disclose the real plan and obtain independent lender review."),
        ("What should I do if the manufactured STR loan assumed in my offer is unavailable?", "Rebuild the complete cash requirement, verify another genuinely accepted funding path or another property, and use professionally reviewed contract protections. Do not rely on a hoped-for refinance or an inaccurate occupancy statement."),
    ],
    "related": [
        '<a href="/blog/airbnb-income-qualify-conventional-str-loan/">Separate STR income qualification from property eligibility</a>',
        '<a href="/blog/reading-a-dscr-term-sheet/">Read the conditions behind a rental-loan proposal</a>',
        '<a href="/how-it-works/">Confirm the acquisition coordination scope</a>',
    ],
    "cta_h": "Finance the property you are actually buying",
    "cta_p": "Compare the construction records, land interest, lender acceptance and full opening budget before committing to a manufactured-home STR offer.",
}]

if __name__ == "__main__":
    blog.build(POSTS)
