"""Prewriting Oct6 94=24intent/29buyer/13evidence/18fit/10original.
Distinct apartment-specific share/proprietary-lease acquisition, corporate
blanket debt and maintenance reconciliation, not condo hotel/project review.
Full existing condo financing, mandatory pool and HOA declaration pages read;
cooperative/proprietarylease wholeblog search only incidental1031/FinCEN.
Current Fannie B4-2.3-04 loan and B4-2.3-02 project primary bodies read;
NYAG Cooperatives and BeforeYouBuy pages fully read, board brochure read.
Real buyer questions and offered vacation cooperative examples found; no
volume claimed, no use of foreign/small-ticket platform results as US law.
All financing/use specific; no generic blanket-debt double counting.
"""
import blog

POSTS = [{
    "slug": "buy-coop-apartment-as-short-term-rental",
    "title": "Can You Buy a Co-op Apartment as a Short-Term Rental?",
    "title_tag": "Buying a Co-op as an STR: Shares, Debt and Rental Rights",
    "h1": "Can you buy a co-op apartment as a short-term rental?",
    "description": "Buying a co-op as an STR? Verify the share purchase, proprietary lease, rental rights, corporate debt and full maintenance costs before making an offer.",
    "date": "2026-10-06", "category": "Buying Strategy",
    "lead": "Potentially, but do not price a co-op apartment as though you were buying a separately deeded condo with unrestricted hosting rights. Establish what the shares and occupancy documents give you, whether your exact short-stay plan is allowed, and how the corporation's obligations affect your cash flow. If you intend to buy within the next zero to six months, those answers belong before an STR offer—not in the manager's post-closing checklist. <a href=\"/apply/\">Book a call to compare a co-op STR candidate with separately owned properties using verified rights and complete costs</a>. Confirm that BNB Accelerator's service scope covers the proposed ownership arrangement; do not assume specialized co-op acquisitions are included.",
    "sections": [
        ("Identify the co-op interest your STR offer would purchase", [
            "The <a href=\"https://ag.ny.gov/resources/individuals/tenants-homeowners/cooperatives\" rel=\"noopener\">New York Attorney General's co-operative overview</a> explains that a purchaser buys shares allocated to an apartment, with a long-term proprietary lease and share-based maintenance charges. It describes that state's co-op setting, not every organization calling itself a cooperative. Ask local counsel to identify the actual entity, shares or membership interest, occupancy instrument and unit in your proposed transaction.",
            "Request the stock or membership documents, proprietary lease or occupancy agreement, current bylaws, house rules and amendments, transfer package, relevant offering documents and ownership records. Have counsel reconcile the apartment, shares and rights shown in those materials with the listing and purchase agreement. Clarify the seller's interest, transfer conditions, buyer-approval process and who can give a binding answer. A listing classified as condo on a portal is not proof of a deeded unit.",
            "Do not confuse this purchase with buying a small investment in a portfolio of vacation homes, a personal-use co-ownership membership or a rental-arbitrage lease. The article's decision concerns acquiring the identified apartment's ownership interest and occupancy rights for an intended STR operation. If the documents instead describe a pooled investment or shared-use program, stop using this unit-purchase model and evaluate that actual arrangement separately.",
            "The Attorney General's <a href=\"https://ag.ny.gov/you-buy-co-op-or-condo\" rel=\"noopener\">before-you-buy guide</a> urges offering-plan and attorney review before signing and cautions that resale offering materials may not be current or available. Use current documents for the transaction; do not treat an old sponsor brochure as a complete statement of today's rental, financial or transfer conditions.",
        ]),
        ("Clear the exact short-stay plan, not just permission to sublet", [
            "Write the intended rental plan in plain language for counsel and the authorized co-op representative: owner-absent guest stays of the lengths you intend, booking platforms, turnover arrangements, manager access, guest occupancy and any personal stays. Ask which current document provisions permit or restrict that plan, what approvals are necessary, whether any minimum term or owner-occupancy period applies, and whether a seller's existing permission survives the transfer. An answer about a year-long sublet is not an answer about nightly guests.",
            "In its <a href=\"https://ag.ny.gov/sites/default/files/publications/coop_board_directors.pdf\" rel=\"noopener\">co-op board brochure</a>, the New York Attorney General identifies bylaws, proprietary lease and house rules as relevant internal documents, including sublet provisions, and warns that the original offering plan may not reflect updated documents. Use that as a document-request framework. Have counsel establish the applicable current law and authority; the brochure is not a nationwide STR rule or a buyer-specific approval.",
            "Separately obtain the municipality's address-specific rental requirements and buyer permit path, and confirm insurance for the actual ownership and guest use. Neither a board approval nor a local registration answers all the other questions. Do not infer that an online Airbnb listing establishes legal use or that paying cash removes the co-op's restrictions. A permitted long-term rental fallback should have its own documented rules and economics; it is not interchangeable with the STR income you wanted to purchase.",
            "Ask about the process for future document changes and review current meeting records for relevant proposals. Do not assign a probability to a future ban or promise perpetual permission without evidence. If you cannot establish the intended short stays before your protected review deadline, delay the purchase or compare an alternative rather than paying for hypothetical hosting rights. The <a href=\"/blog/reading-an-hoa-declaration/\">association-document guide</a> addresses a related diligence principle, but a co-op's actual lease and corporate documents still need their own review.",
        ]),
        ("Separate an apartment share loan from the corporation's financing", [
            "Ask the actual lender whether it lends on the shares and occupancy arrangement for your disclosed investment use. Fannie Mae's <a href=\"https://guide-selling.fanniemae.com/sel/b4-2.3-04/loan-eligibility-co-op-share-loans\" rel=\"noopener\">co-op share-loan guidance</a> describes security in the ownership interest and assigned occupancy rights, rather than an ordinary unit mortgage. Its cited purchase eligibility permits principal residences and second homes but prohibits investment properties. Do not put that agency investment loan in your offer model merely because a lender finances owner-occupied co-ops.",
            "That restriction describes the cited Fannie Mae channel, not a conclusion that all other financing is unavailable or all co-op rentals are illegal. If investigating another program, get current, address- and structure-specific acceptance of the shares, occupancy instrument, actual short-stay use, purchaser and corporate documents. A general DSCR advertisement or condo approval does not establish that the provider accepts this co-op investment. Do not misstate occupancy to obtain a share loan.",
            "The corporation may also have its own blanket mortgage, separate from your personal share loan. Fannie Mae's <a href=\"https://guide-selling.fanniemae.com/sel/b4-2.3-02/co-op-project-eligibility\" rel=\"noopener\">co-op project guidance</a> separately addresses project debt and financial statements. Its criteria do not turn an investment share loan into an eligible transaction. For your buyer model, ask for the corporation's current budget, financial statements, debt schedule, maturity and rate terms, planned refinancing or repayment, reserves and any approved assessments.",
            "Have counsel and a qualified financial professional explain how those obligations affect this apartment's maintenance and potential additional charges. Ask whether the proposed share-loan quote and valuation already reflect a portion of corporate debt and how the lender treats it. Do not add an assumed principal balance to the purchase price or count debt service twice without establishing the actual treatment. Financing the corporation's building is not the same transaction as financing your share purchase.",
        ]),
        ("Normalize maintenance before comparing the co-op's price", [
            "Create a cost map from actual statements and documents rather than comparing headline monthly charges. Identify what maintenance includes: applicable corporate debt service, property taxes, insurance, utilities, staffing, upkeep and reserve funding. Identify what you would still pay directly: personal loan payments, unit-level insurance, utilities not included, cleaning, management, repairs, furnishing, licensing and other operating costs. Confirm the included items rather than assuming every co-op bundles them the same way.",
            ("table", ["Cost or obligation", "Buyer evidence", "How to treat it in the STR comparison"], [
                ["Monthly maintenance", "Current statement and supported component explanation", "Include the total; avoid adding its included costs again"],
                ["Corporate debt changes", "Current debt terms and approved budget or refinance information", "Test a documented change; label any unapproved scenario hypothetical"],
                ["Special assessment", "Notice, amount, payment schedule and sale allocation", "Separate closing cash from later payments"],
                ["Sublet or guest-use charges", "Applicable rules and approved fee schedule", "Add the actual fee basis only if intended stays are permitted"],
                ["Transfer or exit charges", "Current documents and counsel's allocation review", "Place each charge with the party and transaction that owes it"],
            ]),
            "Illustrative only, not a co-op budget, market result or financing quote: assume a permitted STR candidate produces $72,000 of annual guest receipts before platform costs, with $20,000 of other operating costs and $18,000 of maintenance. That leaves $34,000 before the buyer's own financing, income taxes and excluded costs. A separately owned comparator has the same hypothetical receipts and $20,000 of comparable operating costs, plus $12,000 of taxes, insurance and association charges paid separately; it leaves $40,000 on the same pre-financing basis. The difference is $6,000, not the full $18,000 maintenance line.",
            "Now suppose the co-op's documented planned charge increases maintenance by $300 monthly, with everything else unchanged. Its pre-financing remainder falls by $3,600 to $30,400; the comparator difference becomes $9,600. Check whether the increase actually applies and when, and replace the invented inputs with supported statements. A lower share purchase price may or may not compensate for those costs once real financing, opening cash and exit constraints are included. Do not convert the annual difference into a universal price discount or investment return.",
            "Use the <a href=\"/underwriting/downside-scenario/\">downside framework</a> to test reduced receipts and increased documented costs, and the <a href=\"/tools/first-str-purchase-budget/\">purchase-and-launch budget</a> for all initial cash uses. A corporate financial review matters even for a cash buyer: absence of a personal loan does not eliminate maintenance or the building's obligations. Do not assume reserves in the corporation's account are cash available to launch your own guest operation.",
        ]),
        ("Make the co-op STR offer conditional on the actual acquisition case", [
            "Proceed when counsel confirms the interest and transfer path, the intended short stays and necessary approvals are established, actual funding accepts the structure, and the full corporate and unit-level cost model works. Renegotiate where documented costs or permitted changes alter the supported price. Delay while material lease, approval, debt or financing questions remain unanswered. Reject if the purchase requires prohibited guest use, inaccurate occupancy representations or a favorable refinancing outcome that has not been established.",
            "Before signing, have your attorney and licensed broker identify the appropriate contract protections for co-op document review, buyer and loan approval, intended use and remaining conditions. Calendar the actual deadlines and what happens if a condition fails. Do not assume a condo resale cancellation right applies, that a board interview is approval or that approval of you as purchaser also approves the proposed STR activity. An independent lender and counsel must explain their own requirements.",
            "Bring the ownership documents, exact rental plan, authorized responses, maintenance cost map, corporate debt information and proposed funding to the acquisition conversation. <a href=\"/apply/\">Book a call to compare the co-op offer with executable STR alternatives on the same rights, cash and downside basis</a>. BNB Accelerator can discuss sourcing, underwriting, negotiation and purchase coordination where the service fits. Local counsel, lenders, co-op representatives, insurers and authorities handle conclusions within their roles; confirm scope before engagement.",
            "Primary sources reviewed October 6, 2026. Educational information only, not legal, corporate, lending, tax, insurance or investment advice. New York resources describe that jurisdiction and are not nationwide rules. All worked-model amounts are illustrative. Share sensitive financial and ownership documents through secure channels. No board approval, financing, rental permission, distributions, resale liquidity, bookings or returns are guaranteed.",
        ]),
    ],
    "faqs": [
        ("Can I buy a co-op apartment to operate as an Airbnb?", "Potentially, but establish the actual ownership and occupancy rights, current co-op and local short-stay permissions, funding and complete costs before offering. Do not assume a general sublet permission allows nightly guests."),
        ("Does Fannie Mae finance a co-op share purchase as an investment?", "The cited co-op share-loan topic prohibits investment properties for that channel. Ask the actual lender about a genuinely available alternative; owner-occupied co-op or condo financing is not approval of this STR purchase."),
        ("Is the co-op's mortgage the same as my apartment loan?", "No. The corporation may have building-level debt while the purchaser has a separate share loan. Verify how corporate obligations enter maintenance and your proposed financing, and avoid double-counting costs."),
        ("Is a cheaper co-op automatically a better STR acquisition than a condo?", "No. Compare the actual interest, permitted guest use, maintenance components, corporate obligations, funding, opening cash and exit constraints. Headline prices alone do not establish comparable investment value."),
    ],
    "related": [
        '<a href="/blog/str-condo-project-financing-eligibility/">Evaluate the separate condo project-financing question</a>',
        '<a href="/blog/mandatory-rental-pool-before-buying-str-condo/">Review a binding condo rental-pool arrangement</a>',
        '<a href="/how-it-works/">Confirm the acquisition service scope</a>',
    ],
    "cta_h": "Compare what each STR purchase actually owns and owes",
    "cta_p": "Evaluate the co-op's occupancy rights, corporate obligations, accepted funding and launch budget against other purchase-ready STR candidates.",
}]

if __name__ == "__main__":
    blog.build(POSTS)
