"""Oct6 prewriting94=25intent/29buyer/13evidence/18fit/9original.
Purchase an STR from a bankruptcy estate, not borrower post-bankruptcy credit.
Full existing entity/assets, foreclosure, title commitment, probate and buyer
bankruptcy pages read. Distinct core: reconcile actual court-approved asset
and interest treatment with the STR opening model, not generic auction dates.
Current primary FLSB Rule6004-1, INSB B6004-4 and USCourts Chapter11 read.
Actual rental-property buyer questions and marketplace results establish a
real decision, not search volume or proof of STR demand. Local examples not
nationwide rules; statutory outcomes left to qualified bankruptcy counsel.
"""
import blog

POSTS = [{
    "slug": "buy-bankruptcy-estate-property-as-str",
    "title": "Should You Buy Bankruptcy-Estate Property as an STR?",
    "title_tag": "Buying Bankruptcy-Estate Property as an STR",
    "h1": "Should you buy property from a bankruptcy estate as an STR?",
    "description": "Buying bankruptcy-estate property as an STR? Reconcile the sale order, asset schedules and launch costs before paying for rights that may not transfer.",
    "date": "2026-10-06", "category": "Acquisition Diligence",
    "lead": "Possibly, but price the property and rights your closing team can establish—not an assumed clean-title, turnkey Airbnb bundle. If you plan to buy an STR within the next six months, a bankruptcy-estate sale needs a reconciliation between the purchase agreement, applicable court orders, title treatment and executable opening plan. A proposed sale order is not an entered order, and court approval is not a substitute for verifying legal short-stay use. <a href=\"/apply/\">Book a call to compare the bankruptcy-sale STR candidate with ordinary purchases using the rights and cash each actually delivers</a>. Confirm BNB Accelerator's scope and engage qualified bankruptcy and local real-estate counsel; this guide does not claim the service handles every court-supervised acquisition.",
    "sections": [
        ("Define the bankruptcy-estate STR purchase before valuing it", [
            "Ask the estate's authorized sale representative and your attorney for the case number, court, seller capacity, asset description, current agreement, sale motion and exhibits, applicable bidding-procedure order and any entered sale order or amendments. Have counsel identify which documents govern your proposed transaction and what still requires approval. Do not treat an owner's willingness to sign, an accepted offer or a pending listing status as the complete authority to close.",
            "The <a href=\"https://www.uscourts.gov/court-programs/bankruptcy/bankruptcy-basics/chapter-11-bankruptcy-basics\" rel=\"noopener\">U.S. Courts' Chapter 11 overview</a> distinguishes ordinary-course activity from sales outside that course requiring court permission, and separately discusses treatment of executory contracts and leases. That overview concerns Chapter 11; it does not decide your Chapter 7 sale, interpret the actual orders or establish a standard timetable. Ask counsel which chapter, sale authority and remaining conditions apply.",
            "Build two lists: what the sale documents actually include, and what your STR model assumes you receive. The first might describe a parcel and specified personal property; the second might assume furnishings, vacant possession, a management arrangement, incoming bookings and permission to host. Every mismatch needs an identified answer before it contributes value. Do not assume buying real estate is the same as buying the seller's operating business.",
            "Our <a href=\"/blog/buy-str-entity-or-assets/\">entity-versus-assets guide</a> addresses the separate choice of acquisition structure. Here the question is narrower: does the particular court-approved transaction deliver the assets and treatment on which this proposed STR purchase relies? A decision to buy assets rather than shares does not answer that question.",
        ]),
        ("Reconcile the actual sale-order package, not the phrase free and clear", [
            "Use current court materials to frame the review, not to copy another court's procedure. For example, the Southern District of Florida's <a href=\"https://www.flsb.uscourts.gov/node/395/\" rel=\"noopener\">Local Rule 6004-1</a> requires a motion seeking a section 363(f) sale to attach the purchase agreement and proposed order, with proposed bidding documents when requested. Its disclosure requirements cover material sale terms, affected interests, known interest holders and personal-information transfers. This is a local rule, not a finding that any particular lien, lease, license or obligation disappears in your purchase.",
            "The Southern District of Indiana's <a href=\"https://www.insb.uscourts.gov/content/b-6004-4-sale-prospective-purchaser-identified-bids-considered\" rel=\"noopener\">B-6004-4 procedure</a> separately addresses an order establishing bid procedures and an order approving the sale. It calls for disclosure of contracts and leases proposed for assumption or rejection; changed terms may require additional notice. These examples support a practical question: which version and entered order govern what you receive? They do not supply nationwide deadlines, required deposits or a guaranteed closing.",
            ("table", ["STR model assumption", "Question for the responsible professional", "Evidence to reconcile"], [
                ["The buyer acquires the whole advertised site", "Does the approved asset description include each parcel and necessary right?", "Agreement schedules, entered order, conveyance and title file"],
                ["A disputed lien or interest will not burden the purchase", "What is its actual court-ordered and title-insured treatment?", "Relevant order provisions and title professional's requirements"],
                ["Furniture and equipment are included", "Which identified items transfer, and on what terms?", "Approved inventory, ownership evidence and conveyance documents"],
                ["An operating contract or lease continues", "What treatment and obligations apply to this named contract?", "Counsel's review of schedules, orders and required documents"],
                ["Existing guest business supports the opening model", "What booking obligations, funds and usable information actually transfer?", "Approved documents, platform requirements and privacy review"],
            ]),
            "Have counsel explain the legal effect and unresolved issues; have the title professional explain the conditions and coverage it will actually provide. Do not infer that every exception in the title file is eliminated because the marketing says free and clear. If the file and intended closing treatment do not align, resolve the discrepancy before funding rather than asking the manager to handle it after ownership changes. The <a href=\"/blog/title-commitment-before-buying-str/\">title-commitment guide</a> covers the separate policy review.",
        ]),
        ("Remove unsupported operating value from the STR offer", [
            "Start the launch budget with the verified real-estate purchase. Add operating assets only when their inclusion, condition and delivery are evidenced. A photographed sofa is not an asset schedule. A proposed management assignment is not proof the manager will serve you on acceptable terms. Ask counsel to identify any assignment, assumption, consent or other required step and any cost the buyer would accept. Do not use generic legal labels to infer which liabilities survive.",
            "Keep future stays separate from historical revenue. Ask who is responsible for each reservation, refund, guest deposit and prepaid amount under the proposed transaction; how the applicable platform treats the ownership change; and which usable records can lawfully reach the buyer. Do not count the same prepaid guest money as both closing liquidity and future operating cash. Do not accept seller account passwords as a transfer plan or put guest identity and payment data into a public diligence folder.",
            "The cited Florida and Indiana rules expressly flag personal-information transfers. That is a reason to involve counsel and use secure, minimized records—not permission to acquire or reuse any guest database. Ask for anonymized reconciliation where sufficient and obtain appropriate professional review before relying on a customer-data asset. Assume no transferable review history, listing account or bookings until the relevant parties establish the actual arrangement.",
            "Independently verify the address's current rental rules, buyer permit path, association restrictions, insurance and possession requirements. Ask the issuing authority and counsel how the ownership change and sale documents affect the intended use; do not infer an exemption from a bankruptcy order. If a local authorization must be obtained anew, exclude revenue until the supported opening path is established. Use our <a href=\"/regulations/\">regulation library</a> as a starting point, not an address-specific approval.",
        ]),
        ("Price a changed asset bundle rather than bidding on the old model", [
            "Illustrative decision exercise only—not a bankruptcy valuation, legal outcome or client result: suppose a buyer sets a $480,000 maximum complete purchase-and-opening basis from independent conservative underwriting. The initial plan budgets $22,000 for transaction and professional costs, $18,000 for furnishing and setup, $10,000 for carrying costs before opening and $30,000 of retained downside cash. Those non-price uses total $80,000, leaving a $400,000 supported purchase ceiling.",
            "Now suppose the reviewed sale package does not establish delivery of the furniture used in that initial setup budget. Actual replacement quotes add $24,000 to the original $18,000 setup allocation, and the supported replacement schedule adds $8,000 carrying cost beyond the original $10,000. Keeping all other illustrative amounts unchanged, non-price uses become $112,000 and the ceiling falls to $368,000. At the old $400,000 price, the revised complete basis is $512,000—$32,000 above the buyer's stated limit.",
            "The $368,000 is a budgeting result, not a lawful bid formula or an instruction to demand a credit. Ask counsel and the sale representative whether a revised asset bundle, price or condition is available under this case's approved process. If not, compare another property or do not bid. Do not cure the gap with hypothetical future bookings, a hoped-for release of a disputed right or a promise that the estate will reimburse diligence spending.",
            "Also run the actual closing-cash schedule. A basis ceiling does not prove your loan and liquid funds satisfy the sale's deposit, closing and qualification terms. Ask the originating lender whether it accepts this court-sale structure and title treatment, what conditions remain and when funds can be delivered. Have counsel verify the binding terms and permitted protections; do not assume an ordinary financing contingency or standard auction deposit. Use the <a href=\"/tools/first-str-purchase-budget/\">purchase-and-launch budget</a> and <a href=\"/underwriting/downside-scenario/\">downside framework</a> without presuming a refinance will rescue the closing.",
        ]),
        ("Make the go decision from the reconciled package", [
            "Proceed only when counsel has explained the operative approvals and asset treatment, the title and funding teams accept the actual closing package, legal STR use and possession support the opening plan, and the revised costs pass your conservative hurdle. Renegotiate where the approved process permits a supported adjustment for missing assets or changed obligations. Delay while material orders, transfer questions or funding conditions remain unresolved. Reject when the deal requires a right, operating asset or rental permission that cannot be established on acceptable terms.",
            "Give the acquisition team a one-page variance memo: assumed asset or right, actual documented treatment, responsible professional, effect on launch cash or revenue timing, and required decision before the next binding commitment. Update it when the agreement, schedules or orders change. An earlier review of a draft is not sign-off on a different entered order or final conveyance package. Ask counsel about remaining stays, challenges or other closing constraints rather than declaring court approval immune from later problems.",
            "The practical next step is to obtain the sale file and compare the reconciled STR candidate with an ordinary purchase that can meet the same budget and conservative operating test. <a href=\"/apply/\">Book a call to evaluate the bankruptcy-sale property using verified purchase rights and a reset launch budget</a>. BNB Accelerator can discuss sourcing, underwriting, negotiation and acquisition coordination where its scope fits. It does not substitute for bankruptcy counsel, interpret an order, approve a loan or guarantee a court-sale outcome.",
            "Primary court sources reviewed October 6, 2026. Educational information only, not bankruptcy, legal, title, privacy, lending, tax or investment advice. Procedures and outcomes depend on the case, applicable law and actual documents; the cited local examples are not nationwide rules. Worked amounts are illustrative. Use independent qualified professionals and secure document channels. No discount, clear title, transfer, permit, possession date, bookings or returns are guaranteed.",
        ]),
    ],
    "faqs": [
        ("Can I buy property from a bankruptcy estate to operate as an STR?", "Potentially. Establish the actual approved purchase, title and funding treatment, legal rental use, possession and complete opening costs. Court-sale status alone does not establish a viable STR acquisition."),
        ("Does free and clear mean every STR-related problem disappears?", "Do not assume that. Qualified counsel and the title professional must explain the actual order and closing treatment. Independently verify the rights, contracts, assets and local rental permission your buyer model requires."),
        ("Is the proposed sale order enough to price the final STR asset bundle?", "It is not an entered order. Reconcile the agreement, schedules, applicable approvals and final conveyance package with counsel, and update the model when the documented transaction changes."),
        ("Should I include existing Airbnb bookings in a bankruptcy-sale offer?", "Only after the actual obligations, funds, platform arrangements and permitted information transfer are established. Historical revenue and a guest list do not prove bookings or listing assets transfer to the buyer."),
    ],
    "related": [
        '<a href="/blog/buy-foreclosure-as-short-term-rental/">Distinguish foreclosure purchase channels</a>',
        '<a href="/blog/buy-probate-property-short-term-rental/">Evaluate the separate probate purchase process</a>',
        '<a href="/how-it-works/">Confirm acquisition coordination scope</a>',
    ],
    "cta_h": "Buy the documented STR opportunity, not an assumed bundle",
    "cta_p": "Compare the sale package, actual transfer questions, accepted funding and reset opening budget with executable STR purchase alternatives.",
}]

if __name__ == "__main__":
    blog.build(POSTS)
