#!/usr/bin/env python3
"""Tax strategy and financing blog posts."""

TAX_WARN = ("This is an explanation, not tax advice. My BnB Accelerator, LLC is a real estate "
            "acquisition firm, not a CPA firm. Work with a qualified professional. Our independent "
            'partner firm is <a href="https://aetaxadvisors.com/short-term-rentals/" target="_blank" '
            'rel="noopener">AE Tax Advisors</a>.')

T = "Tax Strategy"
F = "Financing"

POSTS = [
    dict(
        slug="str-tax-strategy-order-of-operations",
        title="The Order of Operations in the STR Tax Strategy",
        h1="The Order of Operations in the Short-Term Rental Tax Strategy",
        title_tag="STR Tax Strategy: The Correct Order of Operations (2026)",
        description="Three conditions have to hold in sequence for the STR tax strategy to work. Missing any one produces a passive loss and no benefit. Here is the order.",
        category=T,
        lead="The short-term rental tax strategy is three conditions in sequence, and all three have to hold in the same tax year. Most of the disappointment we see comes from someone satisfying two of them and expecting the outcome that requires all three.",
        sections=[
            ("Condition one: the seven-day average", [
                "Section 469 of the Internal Revenue Code generally treats rental activities as passive per se, meaning losses cannot offset non-passive income like wages regardless of how much work the owner does. That default is why conventional long-term rental losses rarely help a high W-2 earner.",
                "The regulations carve out exceptions to the definition of a rental activity. The most relevant applies where the average period of customer use is seven days or less. An activity meeting that description is not a rental activity for these purposes.",
                "The calculation is total rented days divided by total rental periods across the tax year. A property rented 200 days across 50 bookings averages 4 days, which clears comfortably. It is an annual average, not a per-booking cap, so a single long stay does not break it. Accumulation does.",
                ("warn", TAX_WARN),
            ]),
            ("Condition two: material participation", [
                "Clearing the seven-day test removes the automatic passive classification. It does not make the loss non-passive. For that, you must materially participate under one of seven tests in the regulations.",
                "The practical routes for a W-2 earner are more than 500 hours, or more than 100 hours with no other individual participating more, or participation constituting substantially all participation in the activity.",
                "That middle test is where the management structure becomes decisive. If a full-service manager participates more hours than you, the 100-hour test fails. This is the single most common way the strategy breaks, and it is a planning problem rather than an unavoidable one.",
            ]),
            ("Condition three: a deduction large enough to matter", [
                "With both prior conditions satisfied, the loss is non-passive and can offset W-2 income. Whether that changes your tax position depends entirely on how large the loss is.",
                "Ordinary first-year depreciation on a property depreciated across a single long recovery period produces a modest number. A cost segregation study reclassifying components into 5, 7 and 15-year property, combined with accelerated and bonus depreciation treatment, produces a large one.",
                "A study on a property in the low seven figures can produce a first-year deduction in the hundreds of thousands of dollars. Against a top combined federal and state marginal rate, that is a very large reduction in tax for the year, and it is the reason the strategy is worth the operational discipline the first two conditions require.",
            ]),
            ("What happens when the order is wrong", [
                "The most common sequence error is commissioning a cost segregation study before confirming the participation position. The study produces a large loss, the loss is passive because participation was not met, and it is suspended rather than usable.",
                "Suspended passive losses are not lost forever. They carry forward and can offset future passive income or be released on a fully taxable disposition of the activity. But the client who paid for a study expecting a refund this year does not have one.",
                "The second common error is discovering the strategy in March for the prior tax year. Hours either happened or they did not, and no amount of documentation creates participation retroactively.",
            ]),
            ("The practical sequence", [
                ("ol", [
                    "Confirm with your CPA that your income profile makes the strategy worth pursuing at all.",
                    "Select a property and a market where a seven-day average stay is the natural operating pattern.",
                    "Design the management structure before signing any agreement, so material participation is achievable.",
                    "Start a contemporaneous participation log on day one, not in December.",
                    "Track the running average stay monthly so a drift toward seven days is visible in time to act.",
                    "Commission the cost segregation study once the first two conditions are on track.",
                    "Confirm the position with your CPA before filing, and retain the supporting documentation.",
                ]),
            ]),
            ("What this means for property selection", [
                "Not every good short-term rental is a good vehicle for this strategy. A property in a market where snowbird or corporate long stays are the natural demand pattern makes the seven-day condition harder to hold. A property that requires full-service management because of distance or complexity makes the participation condition harder.",
                "That is why we start with the tax position rather than with a listing. A client whose binding constraint is a large tax bill needs a property that supports the strategy structurally, and a beautiful cabin that cannot clear the tests is not the right purchase for them even if it would be for someone else.",
                "It is also why we work alongside an independent partner firm on the tax side rather than pretending to be a CPA firm. The acquisition and the tax position have to be designed together, and that requires both disciplines actually present.",
            ]),
        ],
        faqs=[
            ("What are the three conditions for the STR tax strategy?",
             "A seven-day or shorter average period of customer use, material participation under one of the seven tests, and a deduction large enough to matter, which usually requires a cost segregation study. All three must hold in the same tax year."),
            ("What happens if I do a cost segregation study but do not materially participate?",
             "The loss is passive and generally suspended rather than usable against W-2 income. It carries forward to offset future passive income or is released on a fully taxable disposition, but it does not produce a refund this year."),
            ("Can I set up the strategy after the tax year ends?",
             "No. Participation hours either occurred during the year or they did not, and documentation cannot create them retroactively. The structure has to be designed before the year, not reconstructed after it."),
        ],
        related=[
            '<a href="/tax-strategy/7-day-rule/">The seven day rule in detail</a>',
            '<a href="/tax-strategy/material-participation/">Material participation tests</a>',
            '<a href="/tax-strategy/cost-segregation/">Cost segregation explained</a>',
            '<a href="/blog/suspended-passive-losses/">Suspended passive losses</a>',
        ],
    ),
    dict(
        slug="participation-log-that-survives-audit",
        title="Building a Participation Log That Holds Up",
        h1="Building a Material Participation Log That Actually Holds Up",
        title_tag="STR Material Participation Log Template (2026)",
        description="What a defensible participation log contains, why contemporaneous beats reconstructed, and the corroborating evidence that makes the hours credible.",
        category=T,
        lead="The regulations permit material participation to be established by any reasonable means. In practice, the difference between a defensible position and an expensive one is whether you kept a contemporaneous log or reconstructed one from memory in April.",
        sections=[
            ("Why reconstruction is weak", [
                "A log built after the fact from calendar entries, message threads and recollection is not worthless, and it is substantially weaker than a contemporaneous record. It reads as an argument constructed to reach a conclusion rather than as a record of what happened.",
                "The practical problem is precision. A contemporaneous entry says what was done, for how long, on what date. A reconstructed entry says roughly what happened in a period, which is exactly the kind of imprecision that invites scrutiny.",
                "The cost of doing it properly is small. Fifteen minutes a week of logging is not a burden against a deduction that can run into six figures.",
                ("warn", TAX_WARN),
            ]),
            ("What each entry needs", [
                ("ul", [
                    "<strong>Date.</strong> The specific day, not a week or a month.",
                    "<strong>Duration.</strong> Actual time, recorded honestly. Rounding everything to whole hours is a pattern that reads badly.",
                    "<strong>Task description.</strong> Specific enough to be checkable. 'Responded to guest inquiry about check-in and adjusted door code' rather than 'guest communication'.",
                    "<strong>Who performed it.</strong> You, your spouse, a manager, a cleaner. This matters because two of the seven tests compare your hours to everyone else's.",
                    "<strong>Property.</strong> A separate log per property unless a valid grouping election has been made.",
                ]),
                "The 'who performed it' field is the one people skip and the one that matters most for the 100-hour test, which requires that no other individual participated more than you did. Without hours for everyone else, you cannot demonstrate that.",
            ]),
            ("Corroborating evidence", [
                "A log is stronger when it is supported by independent records that were created for other reasons. These are not something you assemble; they are something you retain.",
                ("ul", [
                    "Platform message threads showing guest communication with timestamps.",
                    "Pricing change history from your revenue management tool.",
                    "Vendor invoices, texts and scheduling records.",
                    "Receipts for supplies purchased, with dates.",
                    "Bank and card statements showing property-related spending.",
                    "Photographs with metadata from maintenance visits.",
                ]),
                "The point is that a log which lines up with a trail of independent records is credible in a way that a standalone spreadsheet is not.",
            ]),
            ("What counts and what does not", [
                "Guest communication, pricing, coordinating cleaning and maintenance, vendor selection, supply purchasing, repairs, listing optimization and property-specific bookkeeping generally count.",
                "Investor-type activities do not. Reviewing financial statements and analyzing performance in a non-managerial capacity is specifically excluded, which catches out owners who spend substantial time in spreadsheets.",
                "Time studying the market before purchase generally does not count either. Neither does personal use of the property, regardless of what maintenance happens to occur while you are there. Travel time is treated inconsistently and should be discussed with your CPA rather than assumed.",
            ]),
            ("The spouse question", [
                "Participation by a spouse generally counts toward the taxpayer's participation, which is a significant planning point for a household where one spouse has a demanding career and the other has more flexibility.",
                "That does not make it automatic, and the hours still have to be real, documented and of a type that counts. A spouse handling guest communication, pricing and vendor coordination is doing genuine participatory work. A spouse listed on the log without performing the tasks is not.",
                "Where this is part of the plan, log the spouse's hours with the same specificity as your own, and be clear in the record about who did what.",
            ]),
            ("Practical systems", [
                "The tool matters less than the habit. A shared spreadsheet, a notes app with dated entries, or a purpose-built tracking application all work if they are used weekly.",
                "What works less well is trying to hold it in a calendar. Calendar entries record intent rather than duration and rarely describe what was actually done.",
                "Set a recurring weekly reminder, log the week, and attach or reference the corroborating items as you go. At year end, total the hours by person and by property, and give the summary and the underlying log to your CPA rather than a single number.",
            ]),
        ],
        faqs=[
            ("What should a material participation log contain?",
             "Date, actual duration, a specific task description, who performed the work, and the property. The 'who performed it' field matters because two of the seven tests compare your hours against everyone else's, including paid managers."),
            ("Does a reconstructed participation log count?",
             "The regulations permit any reasonable means, but a log reconstructed after the fact is substantially weaker than a contemporaneous one. It reads as an argument built toward a conclusion rather than a record of events."),
            ("Do my spouse's hours count toward material participation?",
             "Generally yes, participation by a spouse counts toward the taxpayer's participation. The hours still have to be real, documented and of a type that counts, so log them with the same specificity as your own."),
        ],
        related=[
            '<a href="/tax-strategy/material-participation/">Material participation tests</a>',
            '<a href="/blog/spouse-material-participation/">Spouse material participation</a>',
            '<a href="/blog/str-tax-documentation-audit/">Documentation for an audit</a>',
            '<a href="/management/">How management structure affects participation</a>',
        ],
    ),
    dict(
        slug="cost-seg-timing-and-hold-period",
        title="Cost Segregation and How Long You Plan to Hold",
        h1="Cost Segregation Only Works If You Plan the Hold Period",
        title_tag="Cost Segregation Hold Period & Recapture (2026)",
        description="Accelerated depreciation is deferral, not forgiveness. How hold period, recapture and a 1031 exchange change whether a study is worth doing.",
        category=T,
        lead="A cost segregation study is frequently presented as free money and it is not. It is a timing shift, and how valuable that shift is depends almost entirely on how long you intend to own the property.",
        sections=[
            ("What the study actually moves", [
                "Without a study, a building is depreciated across a single long recovery period. A short-term rental with an average stay of seven days or less is generally classified as nonresidential at 39 years; a residential rental property is 27.5.",
                "A study separates the purchase into components and assigns each to its correct recovery period. Carpet, appliances, decorative lighting, specialty electrical and furnishings may fall into 5 or 7-year property. Driveways, walkways, landscaping, fencing and pools typically fall into 15-year property.",
                "Those shorter-life components become eligible for accelerated and bonus depreciation treatment, which concentrates a large deduction into the first year rather than spreading it across decades. The total deduction over the life of the asset is not larger. It arrives sooner.",
                ("warn", TAX_WARN),
            ]),
            ("Why sooner is worth paying for", [
                "A dollar of deduction against a top marginal rate today is worth more than the same dollar spread across thirty years, for two reasons: the time value of money, and the fact that the cash freed up can be redeployed immediately.",
                "For a high earner, that redeployment is frequently the point. The refund generated by a first-year deduction becomes the down payment on the next property, which compresses the timeline between purchases dramatically.",
                "That mechanism is why several of our clients have moved from one property to three or six faster than their cash flow alone would have permitted. Peter Eck has closed six properties across four years while working full time at IBM, and the tax structure is doing as much work as the cash flow.",
            ]),
            ("Recapture on sale", [
                "When the property sells, depreciation taken is recaptured. Section 1245 recapture on personal property components is taxed as ordinary income. Unrecaptured Section 1250 gain on the real property portion is taxed at its own rate.",
                "That means a large first-year deduction followed by a sale in year three produces a substantially different after-tax outcome from the same deduction followed by a fifteen-year hold. In the short-hold case, much of what was deferred comes back, and it comes back at ordinary rates on the 1245 portion.",
                "Anyone presenting cost segregation without discussing recapture is not giving you the full picture. It is deferral, not forgiveness, and the deferral period is what determines the value.",
            ]),
            ("The 1031 exchange path", [
                "A 1031 exchange defers the gain, including recapture, into a replacement property rather than realizing it at sale. For an investor who intends to keep rolling into larger properties, that changes the calculation substantially.",
                "The mechanics are strict. Forty-five days from the sale to identify replacement property in writing, 180 days to close, and a qualified intermediary must hold the proceeds throughout. Touching the money personally disqualifies the exchange.",
                "The 45-day identification window is the practical difficulty, and it is where an acquisition process that already has properties underwritten has real value. Finding and contracting a genuinely good short-term rental inside 45 days from a standing start is hard.",
            ]),
            ("When to skip the study", [
                ("ul", [
                    "The property does not clear the seven-day average stay test, so the accelerated loss would be passive and largely stranded.",
                    "You do not materially participate, for the same reason.",
                    "Your marginal rate is low enough that the deduction has limited value.",
                    "The purchase price is small enough that the study cost is a large fraction of the benefit.",
                    "You intend to sell within a few years and do not plan a 1031 exchange.",
                ]),
                "The last one is the least discussed and worth weighing seriously. A short hold with a full recapture event can leave you having paid for a study and gained a timing benefit that mostly reversed.",
            ]),
            ("The look-back option", [
                "A study can be applied to a property purchased in a prior year without amending returns, by filing a change in accounting method and claiming the cumulative catch-up adjustment in the current year.",
                "This is genuinely useful for someone who bought before understanding the strategy, and it is frequently the largest single tax opportunity available to an existing short-term rental owner who has been depreciating conventionally.",
                "It also interacts with the participation question. The catch-up deduction is only usable against W-2 income if the property clears the seven-day test and you materially participate in the year you claim it, so the operational structure needs to be in place for that year, not for the year of purchase.",
            ]),
        ],
        faqs=[
            ("Does cost segregation save taxes or just delay them?",
             "It shifts deductions earlier rather than creating additional ones. The value comes from the time value of money at a high marginal rate and from redeploying the freed cash immediately. On sale, the accelerated depreciation is recaptured."),
            ("How does depreciation recapture work on a short-term rental?",
             "Personal property components are recaptured as ordinary income under Section 1245, and the real property portion is subject to unrecaptured Section 1250 gain treatment. A 1031 exchange can defer both into a replacement property."),
            ("Can I do a cost segregation study on a property I already own?",
             "Generally yes, without amending prior returns, through a change in accounting method with a cumulative catch-up adjustment in the current year. The catch-up is only usable against W-2 income if the participation tests are met in that year."),
        ],
        related=[
            '<a href="/tax-strategy/cost-segregation/">Cost segregation explained</a>',
            '<a href="/blog/depreciation-recapture-str/">Depreciation recapture</a>',
            '<a href="/blog/look-back-cost-segregation-study/">Look back cost segregation studies</a>',
            '<a href="/blog/1031-exchange-short-term-rental/">1031 exchanges for STRs</a>',
        ],
    ),
    dict(
        slug="what-a-cpa-needs-from-you",
        title="What Your CPA Actually Needs From You",
        h1="What Your CPA Actually Needs From You at Tax Time",
        title_tag="STR Tax Prep: What Your CPA Needs (2026)",
        description="The records a short-term rental CPA needs to take an aggressive but defensible position, and what happens when they are missing.",
        category=T,
        lead="A CPA can only take the position your records support. The difference between a client who gets the full benefit of the short-term rental strategy and one who gets a hedged version is almost always what arrived in the tax folder, not what the CPA knows.",
        sections=[
            ("The average stay calculation", [
                "Your CPA needs booking-level data showing every reservation with its start and end date across the tax year, so the average period of customer use can be computed rather than estimated.",
                "Most platforms export this. Pull the full-year transaction or reservation history from every channel you use, not just the largest one, and include direct bookings.",
                "A summary figure you calculated yourself is not the same thing. The CPA needs the underlying data because the calculation has to be reproducible if the return is examined.",
                ("warn", TAX_WARN),
            ]),
            ("The participation log", [
                "The contemporaneous log with date, duration, task description and who performed each item, plus totals by person and by property.",
                "Include hours for everyone else who worked on the property, including managers and cleaners. Two of the seven material participation tests depend on comparing your hours to everyone else's, and without their hours the comparison cannot be made.",
                "Bring the log itself, not a total. A number without the underlying record is not something a CPA can rely on.",
            ]),
            ("The financial records", [
                ("ul", [
                    "Gross revenue by month and by channel, including cleaning fees collected from guests.",
                    "Platform fee statements and any 1099-K received.",
                    "Every expense categorized: management, cleaning, supplies, utilities, insurance, property tax, HOA, repairs, software, travel.",
                    "The closing statement from the purchase, which establishes basis.",
                    "Loan documents and the annual interest statement.",
                    "Furnishing and setup invoices, which are frequently depreciable separately.",
                    "Capital improvement invoices, kept separate from repair invoices.",
                ]),
                "The repair versus capital improvement distinction matters and is frequently blurred by owners. A repair is generally deductible currently; an improvement is capitalized and depreciated. Keeping the invoices separate as you go is far easier than reconstructing the distinction in March.",
            ]),
            ("Personal use days", [
                "Track every night you, your family, or anyone connected to you occupied the property, along with the purpose.",
                "Personal use affects the deductibility of expenses and can affect the classification of the property entirely if it exceeds the thresholds. A property used personally for more than the greater of 14 days or 10% of the days rented at fair rental value falls into a different set of rules.",
                "Days spent substantially full time on repairs and maintenance are generally not counted as personal use, but the documentation for that has to exist. Log the dates and the work performed.",
            ]),
            ("The cost segregation study", [
                "If a study was done, the CPA needs the full report, not a summary. The report supports the component classifications and is the primary documentation if the position is examined.",
                "If a study is planned but not yet complete, tell your CPA early. The timing of the study relative to the filing deadline and any extension matters, and a study arriving the week before a deadline creates avoidable pressure.",
                "If you are considering a look-back study on a prior-year purchase, raise it well before year end. The change in accounting method has its own filing requirements.",
            ]),
            ("What happens when records are missing", [
                "A CPA facing incomplete records has two choices, and both cost the client. They can take a conservative position, which means a smaller deduction and a smaller refund than the facts might have supported. Or they can take a position the records do not fully support, which transfers risk to the client.",
                "Most competent CPAs choose the first, which is why clients with poor records consistently report that the strategy delivered less than expected. The strategy did not underdeliver. The documentation did.",
                "The fix is a system rather than an effort. Weekly participation logging, monthly expense categorization, and a single folder that everything goes into as it arrives. Two hours a month through the year is dramatically less work than reconstructing twelve months in March, and it produces a materially better outcome.",
            ]),
        ],
        faqs=[
            ("What records does a short-term rental CPA need?",
             "Booking-level reservation data for the average stay calculation, a contemporaneous participation log with hours for everyone including managers, full revenue and categorized expense records, the purchase closing statement, loan documents, personal use days, and the cost segregation report if one exists."),
            ("Why does my CPA need hours for my property manager?",
             "Because two of the seven material participation tests compare your participation to everyone else's. Without the manager's and cleaners' hours, the comparison cannot be made and those tests cannot be demonstrated."),
            ("How do personal use days affect a short-term rental?",
             "They affect expense deductibility, and exceeding the greater of 14 days or 10% of days rented at fair rental value moves the property into a different set of rules. Days spent substantially full time on repairs are generally not personal use, but need documentation."),
        ],
        related=[
            '<a href="/blog/str-bookkeeping-records/">Bookkeeping for short-term rentals</a>',
            '<a href="/blog/str-personal-use-days/">Personal use days</a>',
            '<a href="/blog/str-tax-planning-calendar/">The STR tax planning calendar</a>',
            '<a href="/tax-strategy/">STR tax strategy overview</a>',
        ],
    ),
    dict(
        slug="when-str-tax-strategy-does-not-fit",
        title="When the STR Tax Strategy Is Not Right For You",
        h1="When the Short-Term Rental Tax Strategy Is Not Right For You",
        title_tag="When the STR Tax Strategy Does Not Work (2026)",
        description="The strategy is powerful for a narrow profile and wrong for everyone else. The situations where we tell people not to pursue it.",
        category=T,
        lead="We turn away more prospective clients than we take. Most of the time it is not because the property is wrong; it is because the strategy does not fit the person, and pursuing it anyway would produce operational burden for no tax benefit.",
        sections=[
            ("Your marginal rate is not high enough", [
                "The entire value proposition rests on converting a deduction into cash at a high marginal rate. A first-year deduction of $300,000 is worth a great deal at a top combined federal and state marginal rate and much less at a moderate one.",
                "This is not a judgment about anyone's income. It is arithmetic. Below a certain marginal rate, the operational burden of maintaining a seven-day average, logging participation hours and running a short-term rental as a business exceeds the tax benefit it produces.",
                "For those buyers, a conventional long-term rental is frequently the better investment: less work, less turnover, less regulatory exposure, and a return that does not depend on a tax position.",
                ("warn", TAX_WARN),
            ]),
            ("You cannot realistically participate", [
                "The material participation requirement is real work. More than 100 hours with nobody participating more, or more than 500 hours, or substantially all participation in the activity.",
                "Some careers make that genuinely infeasible. A surgeon in a demanding practice with no spouse available to participate and no appetite for guest communication at 10pm is not going to meet the test, and structuring around it produces either a failed position or a fiction.",
                "The honest answer in that case is either to accept passive treatment and buy the property as an investment on its own merits, or not to buy it. Both are better than a strategy that depends on hours nobody will actually work.",
            ]),
            ("Your income is already sheltered", [
                "Some high earners have income structures where the strategy adds little. Substantial existing passive losses, an income profile heavily weighted to long-term capital gains, or other planning already in place can mean an additional non-passive deduction has less impact than the headline suggests.",
                "This is exactly the sort of question a CPA answers in thirty minutes and a real estate firm cannot answer at all. It is why we start clients with a tax conversation rather than a property tour.",
                "If the answer is that the deduction would not move the needle, the property should be evaluated purely as a real estate investment, which is a different and more demanding test.",
            ]),
            ("You need the cash flow now", [
                "The strategy optimizes for after-tax total return, not for monthly cash flow. A property producing modest cash flow while amortizing debt, appreciating and generating a large depreciation deduction can be an excellent investment and a poor source of monthly income.",
                "Someone who needs the property to produce meaningful monthly distributions in year one is frequently disappointed, because year one is when the launch costs land, the reviews are still accumulating, and the reserve should not be touched.",
                "If income is the goal rather than tax efficiency and long-term wealth, there are better vehicles.",
            ]),
            ("You are planning a short hold", [
                "Accelerated depreciation is deferral. On sale, Section 1245 recapture on personal property components is taxed as ordinary income and unrecaptured Section 1250 gain applies to the real property portion.",
                "A three-year hold with a full recapture event returns much of what the study deferred, at ordinary rates on part of it. The strategy rewards a long hold or an exit structured as a 1031 exchange.",
                "If the intention is to buy, run it for two years and sell into a strong market, the tax analysis is different and much less favorable than the version usually presented.",
            ]),
            ("What we say instead", [
                "When the strategy does not fit, the useful conversation is about what does. Sometimes that is a long-term rental. Sometimes it is a different asset class entirely. Sometimes it is that the person's tax situation calls for planning we are not qualified to advise on and their CPA is.",
                "We are a real estate acquisition firm. Our incentive is to sell an acquisition service, which is exactly why it is worth saying plainly that the strategy is narrow. It works extremely well for high earners who can participate and intend to hold. It works poorly for everyone else, and the operational burden is identical either way.",
                "If you are unsure which side you are on, the thirty minute conversation with a specialist CPA costs nothing and answers it before you look at a single property.",
            ]),
        ],
        faqs=[
            ("Who is the STR tax strategy actually for?",
             "High earners with a marginal rate high enough that a large first-year deduction converts to meaningful cash, who can realistically meet a material participation test, and who intend to hold the property long term or exit through a 1031 exchange."),
            ("What if I cannot meet the material participation test?",
             "Then the loss is passive and generally suspended. The honest options are to accept passive treatment and evaluate the property purely as a real estate investment, or not to buy it. Structuring around hours nobody will work produces a weak position."),
            ("Is a short-term rental a good source of monthly income?",
             "Not usually in year one. The strategy optimizes for after-tax total return rather than monthly cash flow, and year one carries launch costs while reviews accumulate. If monthly income is the goal, other vehicles suit better."),
        ],
        related=[
            '<a href="/tax-strategy/">STR tax strategy overview</a>',
            '<a href="/blog/airbnb-vs-long-term-rental-roi/">STR versus long-term rental returns</a>',
            '<a href="/blog/str-exit-strategy/">Exit strategy planning</a>',
            '<a href="/apply/">Talk to us about your situation</a>',
        ],
    ),
    dict(
        slug="str-entity-structure-basics",
        title="Entity Structure for a Short-Term Rental",
        h1="Entity Structure for a Short-Term Rental: What Actually Matters",
        title_tag="LLC & Entity Structure for STRs (2026)",
        description="Whether to hold a short-term rental in an LLC, how it interacts with financing and material participation, and what liability protection actually does.",
        category=T,
        lead="Entity structure is the question new investors ask first and the one that matters least at the start. The tax treatment of a single-member LLC is generally identical to holding the property personally, and the financing implications are more consequential than the liability ones.",
        sections=[
            ("What a single-member LLC does and does not do", [
                "A single-member LLC is generally a disregarded entity for federal income tax purposes. The income and expenses flow to your personal return exactly as they would if you held the property directly. Forming one does not change your tax outcome.",
                "What it does provide is a liability shield, separating the property's obligations from your personal assets. That protection is real and it is conditional: it depends on maintaining the entity properly, with separate bank accounts, separate records and no commingling.",
                "An LLC whose bank account is used for personal expenses is an LLC a plaintiff's attorney will argue should be disregarded. The formation is the easy part; the maintenance is what preserves the protection.",
                ("warn", TAX_WARN),
            ]),
            ("The financing complication", [
                "Conventional investment property financing generally does not permit title in an entity. This is the practical constraint that determines many investors' structure, not a tax analysis.",
                "The common workaround, closing personally and transferring to an LLC afterward, triggers the due-on-sale clause in most mortgages. Lenders frequently do not enforce it, and frequently is not never, and the consequence if they do is an accelerated loan.",
                "DSCR loans generally permit entity ownership by design, which is one of the practical reasons investors choose them over conventional financing despite the rate premium. If entity ownership is important to you, that should factor into the financing decision at the start rather than being solved afterward.",
            ]),
            ("Insurance does more work than the entity", [
                "For most single-property owners, a properly structured insurance program provides more practical protection than an entity does. A commercial or short-term rental specific policy with adequate liability limits, plus an umbrella policy, covers the realistic scenarios.",
                "The realistic scenarios are a guest injury, property damage to a neighbor, or a liability claim arising from the property's operation. Insurance responds to those directly. An entity only matters if the claim exceeds coverage.",
                "That is not an argument against an entity. It is an argument for getting the insurance right first, because an entity with inadequate insurance is a worse position than adequate insurance without an entity.",
            ]),
            ("Multi-property structures", [
                "Once you own several properties, structure starts to matter more. The common approaches are a separate LLC per property, a single LLC holding several, or a holding company structure with subsidiaries.",
                ("ul", [
                    "<strong>Separate LLC per property.</strong> Maximum isolation between assets, maximum administrative cost and complexity.",
                    "<strong>One LLC holding several.</strong> Simpler and cheaper, but a claim against one property reaches the others.",
                    "<strong>Holding company with subsidiaries.</strong> Middle ground, more complex to establish, easier to administer at scale.",
                ]),
                "Which is right depends on the number and value of properties, the states involved, and your risk tolerance. It is a conversation for an attorney rather than a rule that applies universally.",
            ]),
            ("Material participation interaction", [
                "Holding a property in an entity does not by itself change the material participation analysis. The hours are still your hours and the tests are still the same tests.",
                "Where it does interact is in partnerships and multi-member arrangements. A passive capital partner may not meet a participation test, which changes the after-tax return for that partner substantially while the active partner's treatment is unaffected.",
                "This needs to be settled in advance when structuring a partnership, because a partner who expected non-passive treatment and receives passive treatment has a materially different investment than they thought they were making.",
            ]),
            ("The state layer", [
                "Some states impose annual franchise taxes or fees on LLCs that make multiple entities expensive. Others impose registration requirements for entities operating in-state that are formed elsewhere.",
                "An out-of-state LLC holding property in another state generally has to register as a foreign entity in the property's state, which means two sets of filings and fees. The Delaware or Wyoming LLC that appears in a lot of online advice frequently produces exactly this outcome without the benefit that motivated it.",
                "For most single-property investors, forming in the state where the property sits is the simpler and cheaper answer. Ask your attorney rather than following a general rule from a forum.",
            ]),
        ],
        faqs=[
            ("Do I need an LLC for a short-term rental?",
             "Not for tax purposes. A single-member LLC is generally disregarded federally, so the tax outcome is the same as holding the property personally. The benefits are liability separation and, in some financing structures, the ability to hold title in an entity."),
            ("Can I get a conventional mortgage in an LLC?",
             "Generally no. Conventional investment financing usually requires personal title. DSCR loans typically permit entity ownership by design, which is one practical reason investors choose them despite the rate premium."),
            ("Should I form an LLC in Delaware or Wyoming?",
             "For most single-property investors, no. An out-of-state entity holding property in another state generally must register as a foreign entity there, producing two sets of filings and fees without the benefit that motivated the choice."),
        ],
        related=[
            '<a href="/blog/llc-for-short-term-rental/">LLCs for short-term rentals</a>',
            '<a href="/blog/airbnb-insurance-guide/">Short-term rental insurance</a>',
            '<a href="/blog/str-partnership-structure/">Partnership structures</a>',
            '<a href="/financing/dscr-loans/">DSCR loans and entity ownership</a>',
        ],
    ),
    dict(
        slug="reading-a-dscr-term-sheet",
        title="Reading a DSCR Term Sheet",
        h1="Reading a DSCR Term Sheet Without Getting Caught Out",
        title_tag="How to Read a DSCR Loan Term Sheet (2026)",
        description="The four terms on a DSCR term sheet that matter most, the prepayment structures worth negotiating, and the income method question to ask first.",
        category=F,
        lead="DSCR term sheets look simpler than conventional loan documents and contain more variability. Two lenders quoting the same rate can produce materially different deals depending on how they credit income, how they structure the prepayment penalty and what reserves they require.",
        sections=[
            ("Ask the income method question first", [
                "Before anything else, ask how the lender credits short-term rental income. There are three approaches and they produce very different qualifying numbers.",
                ("ol", [
                    "<strong>Market data.</strong> A third-party estimate such as AirDNA for a comparable property in the submarket. Most common for a property with no operating history.",
                    "<strong>Trailing twelve months.</strong> Actual platform statements from the property. Most favorable when the property performs well.",
                    "<strong>Long-term rent schedule.</strong> The 1007 estimate, ignoring short-term income entirely. Most conservative and frequently kills otherwise viable deals.",
                ]),
                "This single variable is the largest factor in whether a specific deal is financeable, and it varies enormously between lenders. Confirming it before you are under contract rather than after is the difference between a smooth close and a scramble.",
            ]),
            ("The ratio and the pricing tiers", [
                "DSCR is gross rental income divided by the total monthly obligation, generally principal, interest, taxes, insurance and association dues. Most lenders want 1.0 or better and pricing improves as the ratio rises.",
                "Ask where the tier breaks are. A lender whose pricing improves at 1.20 and again at 1.40 gives you a reason to adjust the down payment, since a slightly larger down payment that moves you across a tier boundary can pay for itself.",
                "Also confirm exactly what goes into the denominator. Some lenders include association dues and some do not, and on a resort community property with substantial dues that difference moves the ratio meaningfully.",
            ]),
            ("The prepayment penalty is negotiable", [
                "Most DSCR products carry a prepayment penalty, commonly stepping down over three to five years. A 5-4-3-2-1 structure charges 5% of the balance in year one, 4% in year two and so on.",
                "This matters if you intend to refinance into conventional financing once the property has an operating history, or if you might sell. A five-year stepdown on a property you plan to refinance in year three is an expensive constraint.",
                "It is negotiable, usually against rate. A shorter stepdown typically costs a slightly higher rate, and whether that trade is worth it depends on your actual plan. Ask for the three-year and the five-year pricing side by side rather than accepting the default.",
            ]),
            ("Reserves and closing costs", [
                "Many DSCR lenders require several months of payments in reserve at closing, and some require an interest reserve. These are real capital requirements that belong in your entry cost calculation, not surprises at the closing table.",
                "Closing costs on DSCR products generally run above conventional financing. Ask for a full itemized estimate early, including origination, underwriting, processing, appraisal and any lender-required inspection.",
                "The appraisal question is worth raising specifically. Short-term rental properties sometimes require a specialized appraisal or an additional income analysis, which adds cost and time.",
                ("ul", [
                    "Months of reserves required at closing.",
                    "Whether an interest reserve is required.",
                    "Full itemized closing cost estimate.",
                    "Appraisal type and whether a specialized STR appraisal is needed.",
                    "Whether a furnishing or personal property component affects the appraised value.",
                ]),
            ]),
            ("Entity ownership and the guarantee", [
                "DSCR products generally permit entity ownership, which is a practical reason many investors choose them. Confirm this explicitly rather than assuming, and confirm what personal guarantee is required.",
                "Most lenders will require a personal guarantee from the entity's principals even when title is held in the entity, which limits how much liability separation the structure actually provides on the debt itself.",
                "Also confirm whether the lender permits the entity to be formed after the application, since forming it late can delay closing while documentation is redone.",
            ]),
            ("What the approval does not tell you", [
                "A DSCR approval based on an aggressive third-party revenue estimate is not validation of the deal. The lender is protecting a loan at roughly 75% of value with a foreclosure remedy. You are buying 100% of it with your own capital at risk.",
                "This is worth stating plainly because a lender approval reads as confirmation, particularly to a first-time buyer. It is not. It is a statement that the lender is comfortable with its own position.",
                "Underwrite the property yourself against actual comparable booking data regardless of what the lender credits, and stress test at 75% of projected revenue. If the deal works only at the lender's revenue assumption, it is the lender's deal, not yours.",
            ]),
        ],
        faqs=[
            ("What is the most important question on a DSCR term sheet?",
             "How the lender credits short-term rental income. Some use third-party market estimates, some use the property's trailing twelve months of platform statements, and some ignore short-term income entirely and use a long-term rent schedule."),
            ("Can I negotiate a DSCR prepayment penalty?",
             "Usually yes, typically against rate. A shorter stepdown costs slightly more in rate. Ask for three-year and five-year pricing side by side rather than accepting the default, particularly if you plan to refinance or sell within five years."),
            ("Does a DSCR approval mean the deal is good?",
             "No. The lender is protecting itself at roughly 75% of value with a foreclosure remedy while you are buying the whole thing. Underwrite independently against comparable booking data and stress test at 75% of projected revenue."),
        ],
        related=[
            '<a href="/financing/dscr-loans/">How DSCR lenders underwrite STRs</a>',
            '<a href="/financing/conventional-vs-dscr/">Conventional versus DSCR</a>',
            '<a href="/revenue-projections/">Building a revenue projection</a>',
            '<a href="/blog/dscr-loans-for-airbnb/">DSCR loans for Airbnb properties</a>',
        ],
    ),
    dict(
        slug="heloc-vs-cash-out-refi-for-str",
        title="HELOC or Cash-Out Refinance for a Down Payment",
        h1="HELOC or Cash-Out Refinance: Funding an STR Down Payment",
        title_tag="HELOC vs Cash-Out Refi for STR Down Payment (2026)",
        description="How to decide between a HELOC and a cash-out refinance for a short-term rental down payment, and the risk both structures transfer to your home.",
        category=F,
        lead="Most first short-term rental down payments come from equity in a primary residence, and the choice between a HELOC and a cash-out refinance turns almost entirely on one number: how far below current market your existing mortgage rate sits.",
        sections=[
            ("The rate arithmetic", [
                "A cash-out refinance replaces your existing mortgage with a larger one. If your current rate is above market, that improves the rate on the entire balance while producing cash, which is straightforwardly good.",
                "If your current rate is well below market, which is true for anyone who financed or refinanced during the low-rate window, a cash-out refinance means repricing the whole balance to access a fraction of it. Giving up a favorable rate on $400,000 to extract $150,000 is usually a poor trade.",
                "A HELOC leaves the first mortgage untouched and prices only the new money. That is why HELOCs have dominated as a down payment source for the last several years, and the reasoning is arithmetic rather than fashion.",
            ]),
            ("HELOC mechanics worth understanding", [
                "A HELOC is a revolving line secured by your home, typically at a variable rate tied to prime, with a draw period followed by a repayment period.",
                "The flexibility is genuinely useful during an acquisition. You can draw for the down payment, draw again for furnishing, and repay as cash flow arrives without reapplying. That fits the actual shape of a short-term rental purchase, where money goes out in stages.",
                "The variable rate is the corresponding risk. A rate increase raises your payment on a balance secured by your home, and the timing of that is not under your control. Size the draw so a rate increase is absorbable.",
            ]),
            ("The fixed-rate alternative", [
                "A home equity loan, as distinct from a line, is a fixed-rate lump sum secured by the same equity. If you are drawing the full amount at once and have no intention of repaying quickly, the fixed structure removes the rate risk.",
                "The tradeoff is the flexibility. You cannot draw again without a new loan, and you begin paying interest on the full amount from day one rather than only on what you have used.",
                "For a buyer who has a firm number and a firm plan, fixed is usually better. For one who is still sizing the furnishing budget, the line is more practical.",
            ]),
            ("The risk transfer nobody discusses", [
                "Both structures secure the debt against your primary residence. That is a genuine transfer of risk: a short-term rental that underperforms now threatens the house you live in.",
                "The discipline that follows is to size the draw so that a bad first year for the rental is survivable from your income alone, without the property contributing anything. If the HELOC payment only works because the rental performs, the structure is fragile.",
                "This is a specific instance of the general rule about reserves. If the deal only works because you skipped the reserve or maximized the draw, the deal does not work.",
                ("warn", "Model twelve months of the short-term rental producing zero net cash flow while you service both the primary mortgage and the home equity debt from income. If that is uncomfortable, reduce the draw or wait."),
            ]),
            ("Other sources worth comparing", [
                ("ul", [
                    "<strong>1031 exchange proceeds.</strong> If the capital is coming from selling another investment property, an exchange defers the gain and leaves substantially more available. The 45-day identification window is the practical constraint.",
                    "<strong>Taxable brokerage assets.</strong> Selling triggers capital gains, but avoids adding debt secured by your home. Worth comparing on an after-tax basis.",
                    "<strong>Securities-based lending.</strong> Borrowing against a portfolio avoids realizing gains and avoids encumbering the house, at the cost of margin risk.",
                    "<strong>Partnership capital.</strong> Splits the down payment and the return. Settle the material participation question before structuring it.",
                    "<strong>A prior-year tax refund.</strong> For owners already running the strategy, the refund from a first property frequently funds the second.",
                ]),
            ]),
            ("Running the comparison properly", [
                "The right comparison is not which source has the lowest rate. It is which source produces the best after-tax position across your whole balance sheet, given what you are giving up.",
                "A cash-out refinance at a lower headline rate than a HELOC can still be worse if it reprices a large low-rate balance. Selling appreciated securities at a favorable rate can beat borrowing at an unfavorable one. There is no universal answer.",
                "Run the actual numbers on your actual balances rather than applying a rule of thumb, and involve your CPA if the choice involves realizing gains. The decision is usually worth more than the effort of modeling it properly.",
            ]),
        ],
        faqs=[
            ("Should I use a HELOC or cash-out refinance for a rental down payment?",
             "It depends on your existing mortgage rate. If it is well below market, a HELOC leaves the first mortgage untouched and prices only the new money. If your existing rate is above market, a cash-out refinance improves the rate on the whole balance while producing cash."),
            ("What is the risk of using home equity for a rental down payment?",
             "The debt is secured by your primary residence, so a rental that underperforms threatens your home. Size the draw so that twelve months of zero net cash flow from the rental is survivable from income alone."),
            ("Is a home equity loan better than a HELOC?",
             "For a buyer with a firm number and a firm plan, the fixed rate removes the risk of a variable payment increase. For one still sizing the furnishing budget, the revolving line's flexibility is more practical."),
        ],
        related=[
            '<a href="/financing/down-payment-strategies/">Down payment strategies</a>',
            '<a href="/financing/closing-costs-and-reserves/">Closing costs and reserves</a>',
            '<a href="/blog/str-cash-out-refinance/">Cash-out refinancing an STR</a>',
            '<a href="/blog/1031-exchange-short-term-rental/">1031 exchanges</a>',
        ],
    ),
    dict(
        slug="what-lenders-do-with-airdna",
        title="What Lenders Actually Do With AirDNA Numbers",
        h1="What Lenders Actually Do With AirDNA Numbers",
        title_tag="How Lenders Use AirDNA for STR Loans (2026)",
        description="Third-party revenue estimates drive many DSCR approvals. How lenders adjust them, why the number is not a projection, and what to do when it is wrong.",
        category=F,
        lead="For a short-term rental with no operating history, many DSCR lenders qualify the loan on a third-party revenue estimate. Understanding what the lender does with that number, and what it does not mean, is worth more than the number itself.",
        sections=[
            ("How the estimate is generated", [
                "Third-party estimate tools work from observed booking data across a submarket, adjusted for bedroom count, property type and sometimes amenities. They produce a projected annual revenue for a property of a given description in a given area.",
                "That is a reasonable screening tool and a poor underwriting tool, for a specific reason: the model cannot see the factors that determine whether an individual property performs. It cannot see the amenity gap against the true comparable set, whether the claimed view is real, whether the road is passable in February, or whether the property is a fifteen-minute drive further from the demand anchor than its comparables.",
                "The estimate is an average of a category. Your property is a specific member of that category, and the variance within categories is large.",
            ]),
            ("What the lender does to it", [
                "Lenders rarely take the estimate at face value. Most apply a haircut, commonly using a percentile below the midpoint, or discount the figure by a fixed percentage to build in conservatism.",
                "Some blend the third-party estimate with the appraiser's long-term rent schedule, using whichever is lower or a weighted combination. Others cap how far above the long-term rent estimate they will credit short-term income.",
                "Ask specifically which adjustment applies, because it determines your qualifying income. A lender that credits 75% of a market estimate and a lender that credits 100% are quoting materially different loans regardless of rate.",
            ]),
            ("Why a lender approval is not validation", [
                "A lender approving a loan at 75% loan-to-value has a very different risk position from a buyer putting in 25% plus closing costs plus furnishing plus a reserve.",
                "If the property underperforms by 30%, the lender is generally still covered by the equity cushion and has a foreclosure remedy. The buyer has lost the return and possibly the reserve.",
                "This asymmetry is why a lender approval based on an aggressive revenue estimate should not substitute for your own underwriting. The lender is answering a different question than the one you need answered.",
                ("warn", "If the deal works only at the lender's revenue assumption, it is the lender's deal, not yours. Build your own twelve-month model from a comparable set you assembled and stress it at 75%."),
            ]),
            ("Building the number the lender should be using", [
                "The defensible approach is to assemble twelve to twenty genuinely competitive listings, same submarket, same bedroom count, same amenity tier, and pull actual booked nights and rates across a full twelve months.",
                ("ul", [
                    "Filter comparables on amenity parity, not just bedroom count and location.",
                    "Model twelve individual months rather than an annual figure divided by twelve.",
                    "Adjust for the subject property's specific gaps and advantages against the set.",
                    "Account for a first-year ramp while reviews accumulate.",
                    "Net out platform fees, and treat guest cleaning fees honestly against actual cleaning cost.",
                ]),
                "That model is more useful than any estimate tool, and it is the one that should drive the purchase decision. If it happens to support the lender's number, good. If it does not, the discrepancy is information.",
            ]),
            ("When the estimate is too low", [
                "The problem also runs the other way. A property that will genuinely outperform its category, because it has an amenity package or a location advantage the model cannot see, may not qualify on the third-party estimate.",
                "Options include bringing a lender that uses trailing twelve month statements if the property has an operating history, increasing the down payment to improve the ratio, or bringing a formal market study to support a higher figure.",
                "Some lenders will consider a supplemental analysis from a qualified source. Ask rather than assuming the estimate is final, particularly when the gap between the estimate and your own model is large and explainable.",
            ]),
            ("The operating history advantage", [
                "A property with a strong trailing twelve months of platform statements is materially easier to finance than one without, because the lender can credit actual performance rather than a category average.",
                "That is an argument for considering existing operating short-term rentals rather than only conversions, and it is one of the genuine advantages of buying a property that already works.",
                "It also argues for keeping impeccable records once you own. Your own trailing twelve months becomes the qualifying document for a refinance, and a clean, complete record supports a better outcome than a partial one.",
            ]),
        ],
        faqs=[
            ("Do lenders use AirDNA for short-term rental loans?",
             "Many DSCR lenders use third-party market estimates for properties with no operating history, usually after applying a haircut or blending with the appraiser's long-term rent schedule. Ask which adjustment applies, since it determines your qualifying income."),
            ("Is an AirDNA estimate accurate for a specific property?",
             "It is an average for a category, and variance within categories is large. The model cannot see amenity gaps against the true comparable set, whether a claimed view is real, or drive time to the demand anchor. Useful for screening, weak for underwriting."),
            ("What if my property will outperform the estimate?",
             "Options include using a lender that credits trailing twelve month statements where an operating history exists, increasing the down payment to improve the ratio, or supplying a formal market study. Ask rather than assuming the estimate is final."),
        ],
        related=[
            '<a href="/revenue-projections/">Building a revenue projection you can defend</a>',
            '<a href="/financing/dscr-loans/">DSCR loan underwriting</a>',
            '<a href="/blog/str-market-research-tools/">Market research tools</a>',
            '<a href="/blog/buy-existing-airbnb-vs-start-from-scratch/">Buying an existing STR</a>',
        ],
    ),
    dict(
        slug="the-refund-loop-explained",
        title="The Refund Loop: How Clients Buy the Second Property",
        h1="The Refund Loop: How Clients Fund the Second Property",
        title_tag="Using an STR Tax Refund to Buy the Next Property (2026)",
        description="A cost segregation study on the first property can produce a refund large enough to fund the next down payment. How the loop works and when it does not.",
        category=T,
        lead="Several of our clients have gone from one property to three or six faster than their cash flow alone would permit. The mechanism is not leverage in the conventional sense. It is that the first property's tax benefit funds the second property's down payment.",
        sections=[
            ("How the loop works", [
                "Buy a property that clears the seven-day average stay test. Materially participate. Commission a cost segregation study. The study reclassifies components into shorter recovery periods, and accelerated and bonus depreciation treatment concentrates a large deduction into the first year.",
                "Because the seven-day and participation conditions are met, that loss is non-passive and offsets W-2 and other ordinary income. Against a high marginal rate, the reduction in tax owed can be substantial.",
                "If withholding through the year was set against the pre-deduction income, that reduction arrives as a refund. That refund becomes the down payment on the next property, which repeats the cycle.",
                ("warn", TAX_WARN),
            ]),
            ("Why the timeline compresses", [
                "Consider the alternative. An investor relying on cash flow alone accumulates a down payment slowly, because a short-term rental's cash flow after debt service, reserves and capital expenditure allowance is a modest fraction of gross revenue.",
                "Saving $175,000 from cash flow on a property producing, say, $30,000 of net annual cash flow takes years. Producing $175,000 from a tax refund can happen once.",
                "Peter Eck, an Associate Partner at IBM, has closed six properties with us across four years. That pace is not achievable on cash flow accumulation from a standing start, and it is achievable when each acquisition contributes to funding the next.",
            ]),
            ("Where the loop breaks", [
                ("ul", [
                    "<strong>Participation fails.</strong> The loss is passive and generally suspended. No refund, no funding for the next purchase.",
                    "<strong>The average stay drifts past seven days.</strong> Same result, and usually caused by accepting long bookings without tracking the annual average.",
                    "<strong>The marginal rate is too low.</strong> The deduction converts to less cash than expected.",
                    "<strong>Withholding was already adjusted down.</strong> Then the benefit shows up as reduced payments through the year rather than as a lump-sum refund, which is the same money on a different schedule but less useful as a down payment.",
                    "<strong>The property is too small.</strong> A modest purchase price produces a modest study result. The mechanism scales with basis.",
                ]),
            ]),
            ("Scaling the participation problem", [
                "The loop has a natural constraint that catches investors around the third or fourth property: material participation has to be established for each activity, and there are only so many hours.",
                "This is where the grouping election becomes relevant. Whether multiple short-term rental activities are grouped changes how hours are counted, and the election has consequences beyond the current year. It is a conversation to have with your CPA before the third property rather than after.",
                "It is also where the management structure has to be designed deliberately. An owner running four properties with full-service management on all of them will struggle with participation. A hybrid structure where the owner handles pricing, guest communication and vendor decisions across the portfolio while local co-hosts handle turnover logistics is more workable.",
            ]),
            ("What the loop does not do", [
                "It does not eliminate the tax. Accelerated depreciation is deferral, and on sale the depreciation taken is recaptured, with Section 1245 recapture on personal property components taxed as ordinary income.",
                "It also does not remove the need for the underlying investment to be sound. A property bought at a poor basis in a compressing market is a poor investment that happens to have generated a refund. The refund does not fix it, and you now own two.",
                "And it does not work in reverse. A refund used for something other than the next down payment is a perfectly reasonable choice, and it ends the loop.",
            ]),
            ("Planning it properly", [
                ("ol", [
                    "Confirm with your CPA that your income profile supports a meaningful refund before relying on the mechanism.",
                    "Design the participation structure before signing any management agreement.",
                    "Track the running average stay monthly, not annually.",
                    "Commission the study early enough that the result is known before filing.",
                    "Discuss the grouping election with your CPA before the third property.",
                    "Underwrite each acquisition on its own merits regardless of how the down payment is funded.",
                ]),
                "The last item matters most. The refund makes the next purchase possible; it does not make it correct. We screen roughly a thousand deals a week and eliminate about 98%, and a client with a funded down payment gets the same filters as anyone else.",
            ]),
        ],
        faqs=[
            ("Can a tax refund fund the next rental property down payment?",
             "For some clients, yes. A cost segregation study on a property meeting the seven-day average stay and material participation tests can produce a large first-year deduction and a substantial refund. Whether it happens depends on your marginal rate and specific facts."),
            ("What stops the refund loop from working?",
             "Failing the material participation test, letting the average stay drift past seven days, a marginal rate too low for the deduction to convert meaningfully, or a purchase price too small for the study to produce a large result."),
            ("How many properties can this scale to?",
             "The constraint is usually material participation, which has to be established for each activity. Around the third or fourth property, the grouping election and the management structure both need deliberate planning with your CPA."),
        ],
        related=[
            '<a href="/tax-strategy/cost-segregation/">Cost segregation explained</a>',
            '<a href="/case-studies/peter-eck-ibm-partner-six-properties/">Case study: six properties in four years</a>',
            '<a href="/blog/scale-from-1-to-10-airbnbs/">Scaling a portfolio</a>',
            '<a href="/financing/down-payment-strategies/">Down payment strategies</a>',
        ],
    ),
    dict(
        slug="lodging-tax-compliance-basics",
        title="Lodging Tax Compliance Without the Surprises",
        h1="Lodging Tax Compliance: What the Platforms Do Not Collect",
        title_tag="STR Lodging & Occupancy Tax Compliance (2026)",
        description="Booking platforms collect some lodging taxes and not others, and the split varies by jurisdiction. How to find out what remains your responsibility.",
        category=T,
        lead="The most common compliance failure among new short-term rental owners is not the income tax. It is lodging and occupancy tax, because platforms collect some of it automatically in some jurisdictions and owners reasonably assume that means all of it everywhere.",
        sections=[
            ("Why the split exists", [
                "Booking platforms have entered into voluntary collection agreements with many states, counties and cities. Where such an agreement exists, the platform collects and remits the covered tax on bookings made through it.",
                "Those agreements are jurisdiction by jurisdiction and tax by tax. A platform may collect state sales tax and not county tourist development tax in the same location. It may collect for one county in a state and not the adjacent one.",
                "The result is a patchwork, and the only reliable way to know your position is to ask the taxing authorities directly for your specific address rather than inferring it from what appears on your payout statements.",
                ("warn", TAX_WARN),
            ]),
            ("The taxes that typically apply", [
                ("ul", [
                    "<strong>State sales or transaction tax</strong> on transient accommodation, which many states impose.",
                    "<strong>County occupancy, tourist development or lodging tax</strong>, frequently a separate registration and filing.",
                    "<strong>City lodging or hotel occupancy tax</strong>, again typically separate.",
                    "<strong>Special district assessments</strong>, such as tourism improvement districts, which exist in some resort areas.",
                ]),
                "Each of these may have its own registration, its own filing frequency and its own return. A property can require three or four separate registrations, and a jurisdiction that is not collected by the platform requires you to file even in months with no revenue in many cases.",
            ]),
            ("Direct bookings change the picture", [
                "Platform collection agreements cover bookings made through that platform. A direct booking taken on your own website or by phone is generally not covered, which means the tax is yours to collect and remit even in a jurisdiction where the platform handles it for platform bookings.",
                "This catches out owners who build a direct booking channel to save platform fees and do not adjust their tax process. The fee saving is real and it comes with a compliance obligation.",
                "If you take direct bookings, build tax collection into the checkout and the remittance into your monthly process from the first reservation rather than retrofitting it later.",
            ]),
            ("Getting registered properly", [
                ("ol", [
                    "Identify every taxing jurisdiction that applies to the specific address: state, county, city and any special district.",
                    "Contact each and ask what registration is required for short-term rental accommodation.",
                    "Ask each specifically whether the platforms you use have a collection agreement covering that tax.",
                    "Register where required, even where the platform collects, since many jurisdictions require registration regardless.",
                    "Confirm filing frequency and whether zero-revenue returns are required.",
                    "Retain the written answers.",
                ]),
                "That last step is worth the effort. A written answer from the authority is a much better position than a recollection of a phone call if a question arises later.",
            ]),
            ("What non-compliance costs", [
                "Lodging tax authorities generally have long look-back periods and impose interest and penalties. An owner who discovers three years later that a county tax was never remitted faces the tax plus interest plus penalties on three years of revenue.",
                "Some jurisdictions also tie the short-term rental permit or license to tax compliance, meaning a delinquency can put the operating permit at risk. In a capped market, that is an existential rather than financial problem.",
                "Several jurisdictions offer voluntary disclosure programs that reduce penalties for owners who come forward before being contacted. If you discover a gap, raising it with your CPA promptly is materially better than hoping it goes unnoticed.",
            ]),
            ("Building it into the operation", [
                "The practical approach is to treat lodging tax as a monthly operating task rather than an annual one, because most jurisdictions file monthly or quarterly.",
                "Set up a separate ledger line for taxes collected so the money is visibly not yours. Owners who treat collected tax as revenue and spend it face a cash problem at filing time that is entirely self-inflicted.",
                "If you own properties in multiple jurisdictions, the administrative load grows quickly, and specialized lodging tax software or a bookkeeper who handles it is usually worth the cost by the second or third property.",
            ]),
        ],
        faqs=[
            ("Do booking platforms collect all lodging taxes?",
             "No. Platforms have voluntary collection agreements jurisdiction by jurisdiction and tax by tax. A platform may collect state tax and not county tax in the same location. Confirm your position directly with each taxing authority for your specific address."),
            ("Do I owe lodging tax on direct bookings?",
             "Generally yes, and the platform's collection agreement does not cover them. If you build a direct booking channel, build tax collection into checkout and remittance into your monthly process from the first reservation."),
            ("What happens if I miss lodging tax filings?",
             "Authorities generally have long look-back periods and impose interest and penalties. Some jurisdictions also tie the operating permit to tax compliance. Voluntary disclosure programs exist in several jurisdictions and reduce penalties for coming forward."),
        ],
        related=[
            '<a href="/regulations/">Short-term rental rules by state</a>',
            '<a href="/blog/str-bookkeeping-records/">Bookkeeping for short-term rentals</a>',
            '<a href="/blog/direct-booking-website/">Building a direct booking channel</a>',
            '<a href="/blog/str-tax-planning-calendar/">The tax planning calendar</a>',
        ],
    ),
    dict(
        slug="furnishing-costs-and-depreciation",
        title="How Furnishing Costs Are Treated for Tax",
        h1="How Furnishing Costs Are Actually Treated for Tax",
        title_tag="STR Furnishing Depreciation & Deductions (2026)",
        description="Furniture, appliances and setup costs are treated differently from the building. What is deductible now, what is depreciated, and why the invoices matter.",
        category=T,
        lead="A $60,000 furnishing package is not one expense. It is a mix of items with different tax treatments, and how they are recorded at the time of purchase determines what your CPA can do with them a year later.",
        sections=[
            ("Why furnishing is treated separately", [
                "The building is real property with a long recovery period. Furniture, appliances, electronics and decor are tangible personal property with much shorter recovery periods, commonly five or seven years.",
                "That distinction is favorable, because shorter-life property becomes eligible for accelerated and bonus depreciation treatment, which concentrates the deduction into the first year rather than spreading it across decades.",
                "It is also the same principle a cost segregation study applies to the building itself, reclassifying components that qualify as personal property or land improvements out of the long recovery period.",
                ("warn", TAX_WARN),
            ]),
            ("What tends to fall where", [
                ("table", ["Category", "Typical treatment"], [
                    ["Furniture, mattresses, rugs", "Personal property, short recovery period"],
                    ["Appliances, electronics, small kitchen goods", "Personal property, short recovery period"],
                    ["Decor, art, lamps", "Personal property, short recovery period"],
                    ["Linens, towels, consumable supplies", "Frequently currently deductible as supplies"],
                    ["Hot tub, pool equipment", "Depends on installation and permanence"],
                    ["Built-in cabinetry, flooring, fixtures", "Frequently building components, subject to a study"],
                    ["Landscaping, driveway, fencing", "Land improvements, longer recovery period"],
                ]),
                "The lines are not always obvious, particularly for items that are installed rather than placed. A freestanding hot tub and a hot tub built into a deck structure can be treated differently, and that is a question for your CPA rather than a rule you can apply from a table.",
            ]),
            ("The de minimis safe harbor", [
                "There is a safe harbor allowing taxpayers to currently deduct amounts paid for tangible property below a per-item or per-invoice threshold, provided the required election is made and, in some cases, an accounting policy is in place.",
                "For a furnishing package composed largely of individually inexpensive items, this can substantially simplify the treatment and accelerate the deduction.",
                "The requirements are specific and the election has to be made properly. Raise it with your CPA before the furnishing spend rather than after, because having a written accounting policy in place at the start of the year matters for some taxpayers.",
            ]),
            ("Why the invoices matter", [
                "The single most useful thing you can do at furnishing time is keep itemized invoices rather than lump-sum receipts.",
                "A receipt reading 'furniture package, $42,000' gives your CPA very little to work with. An itemized invoice showing beds, mattresses, sofas, dining set, appliances and decor with individual prices lets each item be classified correctly and lets the safe harbor be applied where it fits.",
                "This is a genuinely consequential difference. The same $42,000 spent can produce a materially better first-year deduction with good documentation than with poor documentation, and the cost of good documentation is asking the supplier for an itemized invoice.",
            ]),
            ("Placed in service timing", [
                "Depreciation generally begins when property is placed in service, meaning ready and available for its intended use, not when it is purchased.",
                "For a short-term rental, that generally means when the property is available for booking rather than when the last cushion arrives. A property furnished in November and listed in December is generally placed in service in the year of listing.",
                "This matters at year end. A purchase closing in late December where the property is not listed until January can push the entire first-year deduction into the following tax year, which is a large timing difference if the strategy was the reason for the purchase. Plan the launch date with the tax year in view.",
            ]),
            ("Refresh cycles and later years", [
                "Furnishing is not a one-time event. Soft goods have a three to five year replacement cycle and case goods seven to ten, and a property that skips the refresh drifts down the pricing pack one review at a time.",
                "Those replacement purchases are also deductible or depreciable, depending on the item and the amount, which means the tax treatment of furnishing continues past year one.",
                "Keep the same documentation discipline for replacements. An itemized record of what was replaced and when is useful both for tax purposes and for tracking the property's actual capital expenditure pattern, which most owners underestimate.",
            ]),
        ],
        faqs=[
            ("Is furniture for a short-term rental tax deductible?",
             "Furniture is generally tangible personal property with a short recovery period, which makes it eligible for accelerated and bonus depreciation treatment rather than being spread across the building's long recovery period. Some low-cost items may be currently deductible under a safe harbor."),
            ("Why should I get itemized furnishing invoices?",
             "Because a lump-sum receipt gives your CPA nothing to classify. An itemized invoice lets each item be assigned its correct treatment and lets the de minimis safe harbor be applied where it fits, which can materially improve the first-year deduction."),
            ("When does depreciation on a short-term rental start?",
             "Generally when the property is placed in service, meaning ready and available for its intended use, which for a rental usually means available for booking. A property listed in January rather than December pushes the deduction into the following tax year."),
        ],
        related=[
            '<a href="/design/">Design and furnishing playbook</a>',
            '<a href="/tax-strategy/cost-segregation/">Cost segregation explained</a>',
            '<a href="/financing/closing-costs-and-reserves/">Closing costs and furnishing budgets</a>',
            '<a href="/blog/how-to-furnish-an-airbnb/">How to furnish an Airbnb</a>',
        ],
    ),
    dict(
        slug="buying-in-december-vs-january",
        title="Buying in December Versus January",
        h1="Buying in December Versus January: The Timing Decision",
        title_tag="Should You Close an STR in December or January? (2026)",
        description="A year-end close can pull an entire first-year deduction into the current tax year, or miss it entirely if the property is not placed in service.",
        category=T,
        lead="For a buyer whose primary motivation is a large current-year tax bill, the difference between closing on December 20 and January 10 can be an entire year of deduction timing. It is also the situation where buyers most often make an expensive mistake in the opposite direction.",
        sections=[
            ("Why the date matters", [
                "Depreciation generally begins when property is placed in service, meaning ready and available for its intended use. For a short-term rental that generally means available for booking, not the date of closing.",
                "A property that closes on December 20 and is not listed until February is generally placed in service in the following tax year. The closing date alone does not secure the deduction.",
                "That distinction is the trap. Buyers racing to close before year end sometimes achieve a December closing and a March listing, which produces the deduction in the following year anyway, with the added cost of a rushed acquisition.",
                ("warn", TAX_WARN),
            ]),
            ("What placing in service actually requires", [
                "The property has to be ready and available for its intended use. For a short-term rental, that generally means furnished, functional, permitted where a permit is required, and genuinely available for booking.",
                "A listing that exists but is blocked for all dates is a weaker position than one accepting reservations. A property with no furniture is not available for its intended use regardless of what the listing says.",
                "The practical implication is that if a December placement in service is the objective, the furnishing, photography, permitting and listing work has to be substantially complete before the closing rather than started after it.",
            ]),
            ("Sequencing to actually achieve it", [
                ("ol", [
                    "Confirm with your CPA, early, that a current-year deduction is worth the compression and what it is likely to be worth.",
                    "Get the property under contract with enough runway that furnishing can be ordered during escrow.",
                    "Order furnishing on a schedule that has it delivered and installed within days of closing.",
                    "Complete permitting and registration in parallel, since a property that cannot legally operate is not available for its intended use.",
                    "Book photography for the week of closing.",
                    "List and open the calendar before December 31.",
                    "Engage the cost segregation provider early enough that the study is complete before filing.",
                ]),
                "This is achievable and it requires the acquisition timeline to be built around it from the start. It is not achievable by finding a property on December 5.",
            ]),
            ("The case against rushing", [
                "The purchase decision should be driven by the property, not by the calendar. A property bought at a poor basis in December to capture a deduction is a bad investment with a tax benefit attached, and the bad investment lasts far longer than the tax year.",
                "We screen roughly a thousand deals a week and eliminate about 98%. A December deadline does not change the filters, and a client with a year-end motivation gets the same answer about a property that fails them.",
                "The honest advice in many cases is that January is fine. A deduction taken in the following tax year is a timing difference, not a loss, and buying the right property in the first quarter beats buying the wrong one in December.",
            ]),
            ("Bonus depreciation phase considerations", [
                "Bonus depreciation percentages have been subject to statutory phase-down schedules and legislative changes over recent years, which means the value of a first-year deduction has varied by year.",
                "That variation is a genuine reason to discuss timing with your CPA specifically rather than applying general reasoning. In some years the difference between placing in service in one year versus the next has been material beyond simple timing.",
                "Because these provisions change, this is not something to plan from a blog post, including this one. Confirm the current-year treatment with your CPA before making a timing decision that depends on it.",
            ]),
            ("The alternative for existing owners", [
                "If you already own a short-term rental purchased in a prior year and never had a cost segregation study done, the look-back option may be more valuable than rushing a new purchase.",
                "A study can generally be applied to a prior-year purchase without amending returns, through a change in accounting method with a cumulative catch-up adjustment claimed in the current year.",
                "That produces a current-year deduction without buying anything, and for owners who have been depreciating conventionally it is frequently the largest single tax opportunity available to them. It is worth exploring before concluding that a December purchase is the only path to a current-year benefit.",
            ]),
        ],
        faqs=[
            ("Does closing in December guarantee a current-year deduction?",
             "No. Depreciation generally begins when the property is placed in service, meaning ready and available for booking. A December closing with a February listing generally produces the deduction in the following tax year."),
            ("What does placed in service mean for a short-term rental?",
             "Ready and available for its intended use, which generally means furnished, functional, permitted where required, and genuinely available for booking. A listing blocked for all dates is a weaker position than one accepting reservations."),
            ("Is there an alternative to rushing a December purchase?",
             "For existing owners, a look-back cost segregation study on a prior-year purchase can produce a current-year deduction through a change in accounting method, without buying anything. It is frequently the largest opportunity available to owners depreciating conventionally."),
        ],
        related=[
            '<a href="/blog/look-back-cost-segregation-study/">Look back cost segregation studies</a>',
            '<a href="/tax-strategy/cost-segregation/">Cost segregation explained</a>',
            '<a href="/blog/str-tax-planning-calendar/">The tax planning calendar</a>',
            '<a href="/blog/first-90-days-airbnb-launch/">Launching in the first 90 days</a>',
        ],
    ),
]
