"""Reviewed aquatic-resource evidence versus proposed STR work footprint."""
import posts_reverse_exchange_str as publisher
SLUG='wetlands-before-buying-str'
ROUTE=f'/blog/{SLUG}/'
TITLE='Wetlands Before Buying an STR: Verify the Work Footprint'
DESC='Buying an acreage STR? Separate wetland maps, field boundaries, jurisdiction and work permits; compare a feasible site plan with a funded alternative.'
POST={
 'slug':SLUG,'title':TITLE,'title_tag':TITLE,
 'h1':'Wetlands before buying an STR: what can you actually build?',
 'description':DESC,'date':'2026-10-07','category':'Acquisition & Financing',
 'lead':'Before buying an acreage STR, verify wetlands and other aquatic-resource evidence where the acquisition depends on new parking, a driveway, septic work or an outdoor amenity. A wetland map, a surveyed property boundary and a seller’s statement that the land is dry answer different questions. None alone establishes permission to disturb the site. For a purchase within zero to six months, show qualified professionals the complete proposed work footprint and obtain the applicable authority’s response before paying for an expansion assumption. A high income or large tax bill does not make an unapproved site plan executable. <a href="/apply/">Discuss the property and its site-work dependencies</a> alongside the buyer’s funded alternatives.',
 'sections':[
 ('Separate four evidence layers before pricing the land',[
 'The <a href="https://www.fws.gov/program/national-wetlands-inventory/wetlands-mapper">U.S. Fish and Wildlife Service Wetlands Mapper</a> uses a biological inventory definition. USFWS cautions that the data does not establish the presence, absence or extent of wetlands regulated under federal, state, tribal or local laws. Use a screening map to form questions, not certify a buildable parcel. An unmapped area is not automatic clearance, and a mapped area does not by itself decide every proposed activity.',
 ('table',['Deliverable','Question it can help answer','What not to assume'],[
 ['Screening inventory/map','Where should the team investigate possible aquatic resources?','A blank or colored map is a regulatory decision'],
 ['Qualified field delineation and location evidence','Where are the identified resources relative to the actual plan?','A consultant’s boundary alone authorizes work'],
 ['Actual jurisdictional determination','What regulatory status and reviewed area does the authority document?','The determination is a construction permit'],
 ['Activity-specific authorization and other approvals','What work, footprint, conditions and responsible parties are approved?','Every alternative design or later change is covered'],
 ]),
 'Current <a href="https://www.ecfr.gov/current/title-33/chapter-II/part-331/section-331.2">33 CFR331.2 definitions</a> distinguish an approved Corps jurisdictional determination from an advisory preliminary determination. The section also distinguishes jurisdictional determinations from deciding whether a particular activity requires a Department of the Army permit. Ask the district and qualified counsel which actual document is appropriate and what it covers. This is not a recommendation that every buyer obtain the same document or an appeal guide.',
 'Do not reconstruct today’s federal jurisdiction test from an old report or this checklist. The responsible authority and advisers must apply the rules governing the actual parcel, proposed activity and date. A federal conclusion is not complete state, tribal, local, title, building, septic or rental approval. Request separate reviews where applicable, including any buffers or adjacent-area controls; this guide supplies no nationwide distance or exemption.',
 ]),
 ('Overlay the whole project, not just the finished amenity',[
 'Give the qualified environmental/site team the legal parcel description, current survey, earlier resource reports, authority correspondence and a dimensioned concept plan. Ask what field investigation, records and authority coordination are needed, who may request it and what seller access or authorization is required. Do not enter, sample, clear vegetation, drain, dig or place fill to test a seller’s claim. Have counsel arrange a lawful investigation scope and contract protections before access occurs.',
 'Mark the finished feature plus grading, drainage, utility routes, temporary access, equipment staging, excavation and material-placement areas. A parking rectangle can appear clear while its approach or construction footprint conflicts with a resource. Show the existing septic system and proposed repair area to the appropriate specialists; neither a septic permit nor a wetland map resolves the other’s requirements.',
 'Original hypothetical footprint exercise: a listing advertises four acres and an existing house with a small parking area. The buyer sketches a larger guest turnaround on the rear acre. Ask the team to mark the turnaround, connecting drive, drainage changes and temporary staging on the same drawing as the verified resource evidence. Do not subtract a guessed wetland acreage from four and call the remainder buildable. Location, proposed disturbance, rights and applicable rules matter independently of total area.',
 'Keep a version log: drawing date, report date, reviewed boundary, authority file, assumptions and outstanding question. If the designer moves the drive, ask the team whether the earlier review still answers the new plan. A seller’s old determination may cover only part of the acquisition or a different activity. Do not assert that it is expired or reusable from its age alone; request the authority’s actual reliance guidance.',
 'The <a href="/blog/boundary-survey-before-buying-str/">boundary-survey guide</a> establishes the spatial/title foundation. The <a href="/blog/phase-i-environmental-site-assessment-str-purchase/">PhaseI guide</a> treats wetlands as a possible separate non-scope issue, not contamination clearance. This guide owns the narrower aquatic-resource evidence-to-work-footprint decision; a full home inspection or title policy does not replace it.',
 ]),
 ('Resolve the work authorization before accepting a quote',[
 'EPA’s current <a href="https://www.epa.gov/cwa-404/permit-program-under-cwa-section-404">Section404 permit-program overview</a> describes regulation of discharges of dredged or fill material into waters of the United States, including wetlands, subject to applicable exemptions. It discusses avoidance, minimizing impacts and compensation for unavoidable impacts. It also describes Corps and approved state/tribal program roles. Do not infer that any road, septic project or landscaping job qualifies for an exemption or general permit merely because an example appears in agency guidance.',
 'Ask the responsible office and qualified consultant how the specific activity is treated, what submission is required and what other approvals remain. Do not make a promised permit or assumed mitigation purchase the base case. Obtain an executable permitted scope before treating a contractor’s price as complete. Keep application, design, investigation, authorized construction, restoration and any documented continuing conditions in separate cost lines.',
 'Create a bounded decision memo with four answers: which drawing the authority reviewed, which response has actually been obtained, what conditions remain and who must complete each step. A submitted request is not an approval. A contractor start date is not an agency deadline. Preserve the limitation when a final answer requires further design or a formal application; counsel must determine whether the purchase contract protects the needed time and outcome.',
 'Do not import the floodplain building-value threshold into wetlands work. The <a href="/blog/floodplain-substantial-improvement-str-renovation/">floodplain renovation guide</a> addresses a different regulatory question. A dock, shoreline structure or pool may also need the distinct reviews in the <a href="/blog/dock-permit-inspection-before-buying-waterfront-str/">dock</a> and <a href="/blog/pool-hot-tub-utility-easement-before-buying-str/">easement-footprint</a> guides. Clearing one layer does not erase another.',
 ]),
 ('Worked acquisition comparison: redesign is not free clearance',[
 'Original hypothetical cash arithmetic, not market fees, a permit finding, mitigation estimate, client result or revenue forecast. Assume $320,000 accessible designated funds. The initial plan allocates $225,000 to purchase equity and closing, $40,000 to distinct launch work and $40,000 to retained liquidity: $305,000 total allocation and $15,000 outside the plan. The reserve is cash retained, not another expense.',
 'Suppose the $40,000 launch line already includes $15,000 for the original parking work and $25,000 other setup. Qualified review establishes a different feasible plan whose parking scope costs $23,000. Replace the original $15,000 once; revised launch is $48,000, not $63,000. Assume a separate $5,000 professional/authority-review allowance, not already in either scope. These numbers do not establish that any real site is permitable.',
 ('table',['Illustrative decision','Allocation preserving the $40,000 reserve','Cash outside plan'],[
 ['Original plan before the unresolved review','$225,000 + $40,000 + $40,000 = $305,000','$15,000; not permission to proceed'],
 ['Professionally accepted redesign plus distinct review','$225,000 + $48,000 + $5,000 + $40,000 = $318,000','$2,000'],
 ['Same redesign plus $6,000 distinct net carrying cost','$324,000','$4,000 funding gap'],
 ['Different property: verified scope and no assumed redesign','$230,000 + $35,000 + $40,000 = $305,000','$15,000'],
 ]),
 'The third case assumes the $6,000 represents actual additional net bills during a documented delay and excludes costs already in closing or setup. Do not add hypothetical lost gross bookings as another cash bill. Paying the $4,000 gap from the reserve leaves $36,000, not the chosen $40,000 cushion. Expected tax savings, approvals, guest receipts or later seller reimbursement are not available cash in this comparison.',
 'The alternative property is hypothetical and independently requires full diligence. Its lower allocation does not prove better revenue or investment value. Compare independently supported guest capacity, access and revenue for each executable plan. If keeping the smaller parking area is a lawful option, model that actual operating case separately; do not assume a proportional revenue loss or market-wide parking premium.',
 'Keep unbounded work or approval risk unresolved instead of hiding it inside the $5,000 allowance. A funded redesign does not cure a missing right or authorization. Use the <a href="/tools/first-str-purchase-budget/">purchase budget worksheet</a> to reconcile actual scope replacement, dated outflows and retained liquidity before choosing the property.',
 ]),
 ('Make the offer depend on an executable site plan',[
 'Proceed when the resource evidence, applicable authority response, work scope, other permissions, financing and conservative cash plan align. Reprice a confirmed feasible scope through valid transaction terms. Delay within adequate protection when a decisive response remains missing. Decline a plan that needs unsupported buildable acreage or unfunded required work. No checklist creates cancellation rights, a seller cure obligation or an automatic extension.',
 'Bring a non-sensitive memo to the acquisition team: parcel, proposed drawing, reviewed documents, unresolved authority questions, protected deadlines and funded alternatives. Keep full reports, account records and seller documents in agreed secure channels. BNB Accelerator coordinates acquisition work within its agreement; qualified environmental/site professionals, authorities, surveyors, counsel, lenders and insurers determine their respective conclusions.',
 '<a href="/apply/">Compare the acreage STR with a source-supported purchase shortlist</a>. The <a href="/blog/buy-str-high-income-large-tax-bill/">high-income buyer roadmap</a> keeps this decision separate from hoped-for tax benefits. USFWS, EPA and eCFR materials checked October7,2026; eCFR displayed Title33 current through October2,2026. Educational only, not environmental, ecological, engineering, surveying, permitting, legal, tax, lending, insurance or personalized investment advice. All numerical examples are invented. No jurisdiction, permit, financing, deduction, booking or investment result is guaranteed.',
 ]),
 ],
 'faqs':[
 ('Does a blank Wetlands Mapper area prove the STR site is clear?','No. USFWS says the biological inventory does not determine the presence, absence or extent of legally regulated wetlands. Obtain property-specific professional and authority review.'),
 ('Is a wetland jurisdictional determination permission to build?','No. Jurisdiction evidence and activity-specific permit requirements are separate questions. Verify the actual work scope and every applicable approval.'),
 ('Can I subtract mapped wetland acres to calculate buildable land?','Not reliably. Verify resource boundaries, work access and staging, applicable restrictions, legal rights and the complete proposed footprint with qualified reviewers.'),
 ('Should the original parking allowance remain when I add redesign costs?','Replace overlapping scope once. Add only distinct review, construction and carrying costs, preserve the intended reserve and leave unresolved authorization explicit.'),
 ],
 'related':['<a href="/blog/land-use-tax-enrollment-before-buying-str/">Check acreage tax enrollment separately</a>','<a href="/blog/str-purchase-to-launch-timeline/">Reconcile approvals with opening dependencies</a>'],
 'cta_h':'Verify the acreage plan before paying for expansion',
 'cta_p':'Connect aquatic-resource evidence and actual site-work approvals to a funded STR acquisition comparison.',
}
if __name__=='__main__':
 publisher.SLUG,publisher.ROUTE=SLUG,ROUTE
 publisher.TITLE,publisher.DESC,publisher.POST=TITLE,DESC,POST
 publisher.main(744,2485,'data-wetlands-footprint-link',f'Buying acreage with planned site work? Separate <a href="{ROUTE}">wetland maps, field boundaries, jurisdiction and work approvals</a>, then fund the executable alternative.')
