#!/usr/bin/env python3
"""One additional closing section per market post, merged in by run_blog.py."""

EXTRA = {
    "kissimmee-champions-gate-str-market": ("Exit considerations", [
        "The Orlando corridor has an unusually liquid resale market, which is a genuine advantage that most short-term rental markets do not offer. These communities were built as investment product, they trade constantly, and a buyer for an eight-bedroom resort home with an operating history is not hard to find.",
        "That liquidity cuts both ways. A market where everything trades easily is a market where nothing is scarce, and scarcity is what drives appreciation. Buyers here should generally expect the return to come from cash flow and depreciation rather than from outsized price appreciation, which is a different profile from a supply-constrained mountain or coastal market.",
        "It also means the exit is sensitive to the property's operating record. A resort home with three years of strong statements and a high review score sells to another investor at a premium. The same house with mediocre performance sells to a bargain hunter. In a commodity market, the operating history is the differentiator at sale in the same way it is during the hold.",
    ]),
    "cape-coral-fort-myers-str-market": ("Portfolio pairing", [
        "The inverted Southwest Florida calendar is the property's most useful structural feature for anyone planning more than one purchase. A Fort Myers property peaks January through March. A Smokies cabin peaks June through October. A Poconos house peaks in summer with a winter ski component.",
        "Pairing a Southwest Florida property with any summer-peaking market gives a portfolio two revenue seasons rather than one twice. That matters for debt service coverage in a way that is easy to overlook when evaluating properties one at a time: two properties peaking together produce a spectacular quarter and three difficult ones.",
        "It matters for tax planning as well. A material participation strategy requires documented hours, and hours are easier to accumulate across a year when the properties demand attention at different times. An owner running two summer-peaking properties is doing all the work in the same four months.",
    ]),
    "santa-rosa-beach-30a-str-market": ("What a repeat client teaches", [
        "Peter E. has closed six properties with us across four years. The Santa Rosa Beach purchases were not his first, and that sequence is informative about how a portfolio actually develops for a high earner with a demanding career.",
        "The first purchase is almost always the hardest, because everything is unfamiliar: the underwriting, the financing structure, the tax mechanics, the management relationship. By the third, the process is a known quantity and the constraint shifts from knowledge to capital.",
        "That is when the tax strategy starts doing structural work. A cost segregation study on each acquisition, paired with a property meeting the seven-day average stay and material participation tests, produces a first-year deduction that reduces the tax bill enough to fund part of the next down payment. The portfolio compounds faster than the cash flow alone would permit, which is the actual mechanism behind a six-property portfolio built while working full time at IBM.",
    ]),
    "hocking-hills-ohio-str-market": ("Comparing Midwest cabin options", [
        "An investor looking at Midwest cabin markets is usually choosing between Hocking Hills, Brown County in Indiana, the Wisconsin Dells area, and northern Michigan. The differentiating variables are catchment breadth, season length and regulatory posture.",
        "Hocking Hills has the best catchment of that group, with three metros inside two and a half hours. Northern Michigan has the most scenic product and the shortest season. Wisconsin Dells has the strongest attraction-driven demand and the most commoditized inventory. Brown County is the closest analogue to Hocking Hills at a smaller scale.",
        "For an investor whose priority is a lower entry price with a year-round rather than fourteen-week season, Hocking Hills is generally the strongest of the four. For one whose priority is a scenic asset they will also use personally, northern Michigan makes more sense despite the season length, and the personal use days question then needs careful handling for tax purposes.",
    ]),
    "surfside-beach-texas-str-market": ("Comparing the Texas coast", [
        "The Texas Gulf coast breaks into three distinct investment areas. Galveston is the largest and most established, with the deepest inventory, the most tourism infrastructure and the highest prices. Surfside Beach and the Brazoria County stretch are quieter, closer to the southern and western Houston metro, and cheaper. Port Aransas and the Corpus Christi area serve San Antonio and Austin as much as Houston, with better water clarity and a longer drive from the largest metro.",
        "Galveston carries the most competition and the most regulation. Surfside Beach carries less of both and a smaller demand pool. Port Aransas carries better beaches and a more dispersed catchment.",
        "For an investor optimizing purely on proximity to Houston population, the Brazoria County stretch is the strongest. For one who wants better water and can accept a longer drive from the primary metro, Port Aransas is worth comparing. In all three, elevated construction, wind and flood insurance, and storm disruption modeling are non-negotiable parts of the underwriting.",
    ]),
    "saint-augustine-florida-str-market": ("Atlantic Florida alternatives", [
        "An investor looking at Atlantic Florida generally compares Saint Augustine with New Smyrna Beach, Daytona, the Space Coast around Cocoa Beach, and the Amelia Island area to the north.",
        "The trade across all of them is similar: lower purchase prices than the Gulf Panhandle in exchange for a shorter warm-water season and cooler shoulder months. What separates them is the presence or absence of a second demand driver. Saint Augustine has heritage tourism. The Space Coast has launch traffic and Orlando overflow. Amelia Island has resort and golf demand. Daytona has event weekends.",
        "Regulatory posture is the other separator, and it is not correlated with anything obvious. Florida's preemption grandfathering means older cities with older ordinances are frequently the restrictive ones, and a beach town's friendliness has more to do with when it wrote its rules than with how tourism-dependent it is. Verify per parcel in every case.",
    ]),
    "pocono-townships-regulation-map": ("What the region does well", [
        "Setting aside the regulatory complexity, the Poconos have a structural feature almost no other market offers: four genuine seasons with different demand drivers, inside the largest drive catchment in the country.",
        "Summer lake and water sports, autumn foliage, winter ski traffic to Camelback, Blue Mountain and Jack Frost, and a spring shoulder. Each of those pulls a different guest, and the calendar as a result is flatter than any single-season market can achieve.",
        "That flatness has a specific financial consequence. Debt service is a monthly obligation and revenue in most vacation markets is not. A property that earns something meaningful in eleven months of the year has a fundamentally easier financial profile than one earning everything in five, even at the same annual total. It also reduces the size of the cash reserve required to carry the property safely, which frees capital for the next purchase.",
    ]),
    "sedona-arizona-str-market": ("Northern Arizona alternatives", [
        "Sedona's high prices per bedroom lead many investors to compare Flagstaff, Prescott and the Verde Valley communities of Cottonwood and Camp Verde.",
        "Flagstaff has university and highway traffic, a genuine winter season at Arizona Snowbowl, and a much larger housing stock, which means lower prices and less supply constraint. Prescott has a milder climate, a substantial retiree population and a walkable historic downtown. The Verde Valley sits between Sedona and Flagstaff with wine tourism developing and materially lower prices.",
        "All of them benefit from the same Arizona state preemption that protects Sedona. For an investor who wants Northern Arizona exposure without Sedona's price per bedroom, the Verde Valley is the most direct substitute, with the caveat that it lacks the red rock setting that is the entire reason Sedona commands what it does. You are buying a different product at a lower price, not the same product at a discount.",
    ]),
    "park-city-utah-str-market": ("What the Olympics question means", [
        "Salt Lake City's role in future Winter Olympic hosting is a recurring topic in Park City underwriting, and it deserves a measured treatment rather than an enthusiastic one.",
        "A hosting cycle produces a genuine short-term demand spike, infrastructure investment and international visibility. It also produces construction disruption, temporary regulation, and in some host regions a supply response that outlasts the demand.",
        "The reasonable position is to underwrite the property without any Olympic assumption and treat a hosting cycle as upside. A property that only works because of a two-week event a decade out is not an investment thesis. Park City's actual thesis is that it has two real seasons, high base elevation with substantial snowmaking, an established summer economy and a constrained resort-zone housing stock. Those facts hold regardless of what happens with any bid.",
    ]),
    "lake-tahoe-str-market": ("The insurance question", [
        "Wildfire has changed the insurance picture across the Sierra Nevada in ways that materially affect Tahoe underwriting, and it deserves attention early rather than at the binding stage.",
        "Several carriers have reduced or withdrawn coverage in high fire risk areas across California, and pricing where coverage remains available has risen substantially. In some areas the practical fallback is the state FAIR Plan supplemented by a difference in conditions policy, which is a more expensive and more limited structure than conventional coverage.",
        "Confirm insurability for the specific address before an offer, not during escrow. A property that cannot be insured at a reasonable cost is not financeable on conventional terms and is not a viable short-term rental regardless of how well it would otherwise perform. Ask specifically about defensible space requirements, since carriers increasingly condition coverage on vegetation management the seller may not have done.",
    ]),
    "big-bear-california-str-market": ("The permit purchase question", [
        "In a capped market, buyers frequently ask whether to pay a premium for a property that already holds a transferable permit. The answer depends on whether new permits are genuinely unavailable and whether the premium is proportionate.",
        "Where the cap is binding and new permits are not being issued, the permit premium is rational, because it represents the only path to operating the property as intended. Where permits are technically capped but turnover in the cap means new ones periodically become available, the premium should be much smaller.",
        "The way to answer it is to ask the county how many permits are currently issued, what the cap is, whether there is a waiting list, and how many permits have been issued to new applicants in the last twelve months. Those four numbers tell you whether the cap is a wall or a queue, and they are the difference between a rational premium and an expensive one. Get the answers in writing, and model the long-term rental floor in either case.",
    ]),
    "gulf-shores-orange-beach-str-market": ("House versus condo", [
        "The most consequential decision in this market is whether to buy a single-family house or a condominium unit, and the two behave differently enough to be separate investment categories.",
        "Condominium units are cheaper to enter, come with shared amenities that a house cannot match, and require no exterior maintenance. They also carry association dues, assessment risk, potential mandatory rental program participation, and restrictions on how the unit can be operated. The owner controls the interior and very little else.",
        "Single-family houses cost more, carry full maintenance responsibility, and capture the larger family group at a higher nightly rate. They also permit a private pool, which is the single largest amenity differentiator in the market, and they avoid the association constraints entirely. For an investor optimizing returns rather than convenience, the house is generally the better asset, and the entry cost difference is real.",
    ]),
    "dfw-lake-markets-shady-shores": ("Managing event-adjacent demand", [
        "Metro amenity lake properties attract celebration bookings: bachelorette parties, milestone birthdays, family reunions and graduation weekends. That demand pays well and it is the source of most operating problems in this category.",
        "The controls that work are structural rather than aspirational. Occupancy limits written into the house rules and enforced through the booking process. Noise monitoring in shared living areas, disclosed in the listing so it is not a surprise. Minimum stays on high-risk weekends, which filter out one-night party bookings without affecting genuine family stays.",
        "Guest screening matters more here than in a destination market, because a local guest booking a house forty minutes from home for one night has a different intent profile than a family that traveled. Verified identity, a clear cancellation and damage policy, and a security deposit are reasonable requirements, and the bookings they deter are largely the ones you did not want.",
    ]),
    "phoenix-mesa-gilbert-chandler-comparison": ("The summer strategy question", [
        "Every East Valley owner has to decide what to do with June through August, and there are three defensible answers.",
        "The first is to price to cover carry. Dropping rates enough to fill at close to breakeven means the property earns nothing but costs nothing, which preserves cash and keeps review velocity alive through the trough. The risk is that deep summer discounting attracts a different guest profile than the winter season does.",
        "The second is to accept low occupancy and use the window for maintenance, deep cleaning and furnishing refresh. That work has to happen somewhere in the year, and doing it in the trough costs no peak-season revenue. This is the approach we generally recommend for properties with a strong October to April season.",
        "The third is to pursue mid-term stays, though this needs care. A summer of thirty-day bookings can push the annual average stay past seven days and break the tax treatment that made the purchase attractive. Run the annual average before accepting them.",
    ]),
    "denver-metro-str-restrictions": ("The mountain alternative", [
        "Investors drawn to Colorado for the mountain product rather than the metro face a different set of constraints, and they are generally tighter.",
        "Summit County and its towns operate license caps and zone-based license classes. Steamboat Springs has adopted overlay restrictions. Several other resort communities have moved similarly. The direction of travel across Colorado's resort economy has been toward restriction for several years, driven by workforce housing pressure that is genuine and not going away.",
        "For an investor who wants ski market exposure, Utah and Idaho currently offer better regulatory positions. Park City permits nightly rental in defined zones, and Idaho code prevents local governments from prohibiting short-term rentals outright, which protects McCall, Sun Valley and Coeur d'Alene. Both markets have real demand and neither carries Colorado's unresolved property tax classification question. That is not a reason to rule Colorado out, but it is a reason to compare rather than assume.",
    ]),
    "smoky-mountains-submarket-differences": ("What we look for in the corridor", [
        "After transacting more properties here than anywhere else, the filters have narrowed to a consistent set.",
        "Basis below the comparable set for the same amenity tier, because that advantage is permanent and never has to be re-earned. Genuine view verified from the deck rather than from listing photography. Hot tub, game room and view all present, or the gap priced and funded at purchase. Drive time to the Parkway inside a range the comparable set supports. Road access that works in February, since steep gravel switchbacks generate cancellations and refund requests.",
        "And a twelve-month revenue model built from actual booked nights for genuinely comparable inventory, stress tested at 75%. A cabin that clears all of those is rare, which is why we screen roughly a thousand deals a week across all markets and eliminate about 98% of them. The corridor produces more of our transactions than anywhere else not because the filters are looser here but because the inventory is deep enough that something always clears them.",
    ]),
    "blue-ridge-georgia-str-market": ("Comparing Appalachian cabin markets", [
        "Blue Ridge competes for investor attention with the Smokies, Asheville, and the Highlands and Cashiers area of western North Carolina.",
        "The Smokies has a far deeper demand base, drawing nationally rather than from one metro, with correspondingly higher prices and more supply. Asheville restricts whole-house short-term rentals substantially in residential districts, which excludes most investment purchases inside the city. Highlands and Cashiers serves an affluent Atlanta and Florida seasonal population at high price points with a short season.",
        "Blue Ridge sits in a useful middle: lighter regulation than Asheville, lower prices than the Smokies or Highlands, and a real if concentrated catchment. The tradeoff is a smaller ceiling and single-metro dependency. For an investor who wants Appalachian cabin exposure at a moderate basis and is comfortable with Atlanta concentration, it is a reasonable choice. For one who wants the deepest demand pool available, the Smokies remains the answer.",
    ]),
    "johnson-city-texas-hill-country": ("Fredericksburg comparison", [
        "The obvious alternative to Johnson City is Fredericksburg, twenty-five miles west and the corridor's commercial center.",
        "Fredericksburg has the shops, the restaurants, the Main Street that guests walk, and correspondingly higher prices and a permit program with density limits in some districts. Johnson City is quieter, cheaper, and much of the surrounding inventory sits on unincorporated county land outside city ordinances.",
        "The guest calculation is whether the group wants to walk to dinner or drive to it. A wine weekend group with a designated driver is happy to stay fifteen minutes out for a substantially larger house on more land. A couples trip prioritizing walkability will pay the Fredericksburg premium.",
        "For a six-bedroom group property, the Johnson City side of the corridor is generally the better trade: more land, more privacy, lower basis, and a regulatory position that is lighter and less likely to tighten. Verify the parcel's incorporation status either way, because that single fact frequently determines what is permitted.",
    ]),
    "table-rock-lake-branson-west": ("Lake of the Ozarks comparison", [
        "Missouri's other major lake market is Lake of the Ozarks, roughly three hours north, and the two are frequently compared without much precision.",
        "Lake of the Ozarks is larger, closer to Kansas City and St. Louis, and considerably more developed with a party-oriented reputation in parts of the lake. Table Rock is cleaner, quieter, more family-oriented, and has the Branson entertainment corridor as a second demand driver that Lake of the Ozarks lacks.",
        "For a family-oriented large house, Table Rock generally performs better and carries less guest management risk. For a property optimizing pure summer volume from the two Missouri metros, Lake of the Ozarks has the demand edge.",
        "Both are Corps of Engineers or utility-managed in parts, so dock permit diligence applies to each. And both are genuinely seasonal in the summer sense, which makes Table Rock's autumn Branson traffic the more meaningful differentiator over a full year.",
    ]),
    "joshua-tree-str-market": ("Palm Springs comparison", [
        "The obvious California desert alternative is Palm Springs, forty-five minutes south, and the two markets are less similar than the geography suggests.",
        "Palm Springs is a mature resort market with mid-century architecture, a substantial hotel sector, a large event calendar and a permit program with a cap and waiting list. Nightly rates are higher, the season is longer, and the guest skews older and more affluent.",
        "Joshua Tree is smaller, newer as a rental market, more design-dependent and more exposed to San Bernardino County regulatory tightening. Its guest skews younger and its rates depend more heavily on the individual property being remarkable.",
        "The permit position differs in kind. Palm Springs has a cap with a waiting list, which means an existing permit is a defined asset with a known queue behind it. Joshua Tree's county restrictions include density rules that can make a permit unavailable because of what the neighbors hold. For a buyer who values a knowable regulatory position, Palm Springs is the more legible market despite being the more expensive one.",
    ]),
    "nashville-permit-value": ("What the numbers have to clear", [
        "A Nashville four-bedroom carries a purchase price that reflects both the property and the permit, and the underwriting has to account for both.",
        "The revenue side benefits from higher and flatter occupancy than a vacation market, plus compression nights that can run several times baseline. The expense side carries higher turnover cost, tighter guest response requirements, and management that is genuinely more demanding than a weekly beach turnover.",
        "The stress test that matters most here is the long-term rental floor. Model what the property rents for on a twelve-month lease, subtract the same debt service, and confirm the shortfall is one you can carry. In Nashville that floor is unusually strong for a tourism-influenced city, driven by healthcare employment and sustained population growth.",
        "If the property works at the floor, the permit premium is buying upside rather than propping up a deal that fails without it. That is the correct structure for any purchase in a capped market, and it is the discipline that separates a permitted asset from a policy bet.",
    ]),
    "scottsdale-event-compression": ("Old Town versus North Scottsdale", [
        "Scottsdale splits into submarkets that serve different guests, and the difference is larger than the shared city name suggests.",
        "Old Town Scottsdale is walkable, dense, and serves group travel, bachelorette parties and event traffic. Rates are strong, turnover is fast, and neighbor friction is the highest in the city. Noise monitoring and enforced occupancy limits are not optional here.",
        "North Scottsdale is spread out, golf-oriented, and serves families, snowbirds and golf groups. Properties are larger, guests are quieter, stays are longer, and the demand is more seasonal, concentrating harder in the winter months.",
        "For an investor prioritizing rate and volume with active management, Old Town is the stronger position. For one prioritizing lower operational intensity and longer stays, North Scottsdale is the better fit. Both benefit from Arizona's preemption of municipal bans, and both require reading the association declaration separately, since many North Scottsdale communities restrict rentals privately regardless of what state law says about cities.",
    ]),
    "single-metro-drive-market-risk": ("Testing your own exposure", [
        "A practical exercise for any owner with more than one property: write down the primary metro feeding each one, the peak season of each, the governing jurisdiction of each, and the primary climate risk of each.",
        "If two of those columns match across two properties, you have less diversification than the map suggests. Two properties in different states that both feed off Atlanta and both peak in October are one bet.",
        "The same test applies before a purchase. When evaluating a second or third property, the question is not only whether the deal works on its own numbers but whether it adds a genuinely different exposure to what you already hold.",
        "This is the reasoning behind the pairings our multi-property clients have ended up with. Broken Bow with Destin. Shady Shores with Santa Rosa Beach. In each case the second property was chosen partly for what it was not correlated with, and that reasoning is worth making explicit rather than leaving to chance.",
    ]),
    "market-supply-growth-warning-signs": ("The counterintuitive part", [
        "Supply growth in a market is frequently a sign that the market is good, which is why it catches investors out. Capital flows toward returns, and a market producing strong returns attracts building and buying until the returns normalize.",
        "That means the markets with the most alarming supply charts are often the ones that performed best over the prior three years. Broken Bow's inventory grew because Broken Bow worked. The Orlando corridor is saturated because the Orlando corridor made money.",
        "The investment implication is that you cannot use recent performance as a forward indicator without checking what the performance attracted. A market with three excellent years and flat listing counts is a very different proposition from a market with three excellent years and listing counts up 40%.",
        "The second implication is that supply-constrained markets deserve a premium. Sedona cannot expand because it is surrounded by national forest. Nashville's permit cap limits new non-owner-occupied entrants. In both cases the constraint is worth paying for, because it protects the return from the mechanism that erodes it everywhere else.",
    ]),
    "fort-walton-beach-value-thesis": ("The exit consideration", [
        "Value markets have a specific characteristic at sale worth understanding before purchase: the buyer pool is different from the premium market's.",
        "A Destin or 30A property sells to buyers who want that specific location and are comparing it against other premium coastal assets. A Fort Walton Beach property sells to buyers running the same value calculation the original purchaser ran, comparing cash-on-cash returns across submarkets.",
        "That makes the operating record more important at exit. In a premium market, location carries the sale. In a value market, the numbers do, because the buyer is there for the numbers. A property with three years of strong statements, a high review score and documented occupancy sells well. The same house with mediocre performance sells at a discount, because the value thesis it was bought on has not been demonstrated.",
        "The practical implication is to keep clean records from day one. Monthly statements, occupancy and rate history, expense detail and review history are the sale package in a value market, and reconstructing them at listing time is both harder and less credible.",
    ]),
    "how-we-eliminate-98-percent-of-deals": ("What survives", [
        "The properties that clear all five filters share a recognizable profile, and it is less exciting than most buyers expect.",
        "They are usually not the most attractive property in the submarket. They are frequently properties with a fixable problem that suppressed the price: dated furnishing, poor listing photography under the current owner, a management relationship that underperformed, or a seller who needs to transact.",
        "They almost never come from a listing that reads well. A property marketed with a polished proforma and strong photography is priced accordingly, because the seller has already captured that value. The opportunity is in properties where the gap between what the property is and what it appears to be is large, and closing that gap is work rather than luck.",
        "That is the whole business, stated plainly. We are not finding properties nobody knows about. We are finding properties whose price does not reflect what they would produce under competent operation, and buying them before that gap closes. Our client Adam's four-bedroom Sevierville cabin at $775,000 is a straightforward example: a below-market basis in the deepest bedroom-count bracket in the country's largest short-term rental market.",
    ]),
    "hochatown-oklahoma-str-market": ("How to buy into a compressing market", [
        "Buying into a market with rapid supply growth requires two things that a stable market does not: a basis advantage large enough to absorb rate compression, and a property differentiated enough to hold occupancy while neighbors lose it.",
        "The basis advantage is the more reliable of the two. If comparable cabins are transacting at $850,000 and you buy at $760,000, that $90,000 is a permanent improvement to your return that does not depend on execution. It also means you can price below the market and still clear your numbers, which is a genuinely strong position when compression arrives.",
        "The differentiation is harder and more expensive. It means architecture that photographs distinctively, an amenity package above the comparable set rather than at it, and photography that competes with new inventory rather than with what was adequate three years ago.",
        "A property with neither is the one that suffers. Bought at market, furnished to standard, competing on price against cabins that arrived last year with better everything. That is the failure mode in Broken Bow, and it is entirely avoidable at the purchase decision.",
    ]),
}
