"""Reviewed project-stage/parcel-footprint STR acquisition decision; scoped only."""
import posts_reverse_exchange_str as publisher
SLUG='proposed-road-project-before-buying-str'
ROUTE=f'/blog/{SLUG}/'
TITLE='Proposed Road Project Before Buying an STR: What to Verify'
DESC='Buying an STR near a proposed road project? Verify its stage, parcel footprint and access plan; compare purchase cash without assumed compensation.'
POST={
 'slug':SLUG,'title':TITLE,'title_tag':TITLE,
 'h1':'Should a proposed road project change your STR purchase?',
 'description':DESC,'date':'2026-10-07','category':'Acquisition & Financing',
 'lead':'Before buying an STR near a proposed public road project, determine which project is involved, what stage it has reached and what the responsible agency can actually confirm for the property. A corridor line on an old public map is neither proof that construction will occur on a specific date nor proof that the site is unaffected. For a buyer preparing to purchase within zero to six months, connect the current project evidence to guest access, usable parking, planned improvements and independently available cash. Do not price an expected compensation payment as purchase funding. <a href="/apply/">Bring the project evidence and property shortlist to an acquisition call</a> before the relevant diligence deadline.',
 'sections':[
 ('Separate project status from an address-specific impact',[
 'Use the responsible transportation or public-works agency’s official project page, project identifier, current plans and named contact. Request the current status and the date of the answer. Search the seller’s documents for project correspondence or notices, with counsel arranging lawful access to records. A broker’s statement that the road will never change or that construction starts next year is a claim to verify, not a substitute for agency evidence.',
 'The <a href="https://www.txdot.gov/manuals/des/pdp/chapter-1--general-guidance/1-3-txdot-s-project-development-process.html">TxDOT Project Development Process Manual section1.3</a> illustrates why stage matters: it distinguishes planning, programming, preliminary engineering, final design, letting and construction. Those are Texas program terms, not a mandatory nationwide sequence. Ask the agency responsible for the actual property what its own current stage means and which activities or decisions remain.',
 'The same manual’s <a href="https://www.txdot.gov/manuals/des/pdp/chapter-2--planning/2-7-project-authorization.html">section2.7 on project authorization</a> explains that implementation decisions may change with conditions, community needs, environmental findings or costs. It distinguishes feasibility and authorization stages. This supports asking better questions, not assigning this property a construction probability, a guaranteed cancellation, or a compensation entitlement. A funded or authorized activity is not necessarily a completed parcel acquisition or a finished driveway design.',
 'Save the actual drawing version and agency response rather than copying an unlabeled screenshot. Identify whether the drawing shows alternatives, a preferred concept, current design or an acquired interest. Ask the agency to explain that distinction in its own terms. Do not interpret a planning-map line as a surveyed legal boundary or presume that no recorded instrument means no future project question.',
 ]),
 ('Build a parcel-and-project evidence register',[
 ('table',['Question','Evidence and responsible reviewer','Buyer decision'],[
 ['Which project and stage?','Official identifier, current status, dated agency response','Separate an early concept from an active acquisition or construction dependency'],
 ['Which land or right may be affected?','Current plans and parcel correspondence; qualified survey/title/counsel review','Identify the reviewed area, not an approximate online overlay'],
 ['Which access changes are proposed?','Agency driveway/access information and qualified site review','Test guest/vendor access during work and afterward separately'],
 ['Which temporary conditions matter?','Documented staging, easement, closure or utility proposals as applicable','Do not mistake a temporary work area for a permanent change, or vice versa'],
 ['Which purchase obligations remain?','Actual notices, agreements and transaction documents reviewed by counsel','Resolve who must respond, what rights are involved and protected deadlines'],
 ['Which funded alternative works?','Executable site scope, actual quotes and dated cash ledger','Compare without assuming a payment, project delay or revenue premium'],
 ]),
 'Give the appropriate agency contact and qualified team the legal parcel description, current survey, seller-provided correspondence and intended STR site uses. Mark every driveway, parking space, turnaround, utility route and proposed amenity on a dimensioned plan. Ask which item the current project information addresses, what remains undecided and which office can answer it. Do not ask a surveyor to certify project funding or an agency planner to interpret your purchase contract.',
 'The <a href="/blog/boundary-survey-before-buying-str/">boundary-survey guide</a> addresses current spatial evidence; the <a href="/blog/title-commitment-before-buying-str/">title-commitment guide</a> covers actual conveyed interests and proposed policy terms. Neither alone resolves future project execution. Have local counsel and title professionals review relevant notices, instruments, existing access, proposed rights and actual policy treatment. This guide supplies no blanket title-insurance coverage rule.',
 'Keep a log of the project version, document date, parcel reference, reviewer, remaining question and last protected purchase-decision date. If an agency can only supply a preliminary answer, preserve that limitation. A confident-looking map does not convert an unresolved footprint into a supported base-case site plan.',
 ]),
 ('Compare temporary access and the permanent operating plan',[
 'Ask about the property’s access during any documented work and after the proposed project is completed. A temporary detour, construction staging area, new grade, changed entrance or permanent access-control proposal can affect different parts of the purchase case. Request the agency’s actual information; do not invent the duration, severity or available route from a general corridor announcement.',
 'Have the appropriate local and qualified professionals test the intended driveway, turnaround, guest parking, deliveries, refuse, maintenance and emergency access. Where necessary, ask what permits, consents or design work are required for an alternative. An apparent space on the remainder of the parcel is not automatically lawful replacement parking. Do not promise guest safety or emergency response from an online route or casual drive.',
 'The <a href="/blog/private-road-maintenance-agreement-before-buying-str/">private-road guide</a> remains the destination for existing recorded passage, shared-road duties and maintenance. This page focuses on the potential public-project change. Keep present access, future design, legal permission and actual lender acceptance as separate conclusions. Send decisive information to the lender and insurer early rather than assuming a prior approval addressed the new facts.',
 'Re-underwrite the supported property. If the acquisition thesis depends on an unverified entrance or parking area, run an alternative without that feature and obtain independent revenue evidence. Do not assume a percentage revenue loss from a parking-space count, a construction premium, better future demand or automatic bookings after the new road opens. A narrower lawful operating plan may work, but it needs its own evidence.',
 ]),
 ('Original purchase comparison: fund the workable alternative first',[
 'Invented arithmetic only, not a construction quote, agency finding, compensation calculation or client result. Assume $350,000 of available designated funds. The initial plan allocates $240,000 to purchase equity and closing, $45,000 to distinct launch work and $40,000 to retained liquidity. Total allocation is $325,000, leaving $25,000 outside the plan. The reserve remains cash, not an expense already paid.',
 'Assume the $45,000 launch line already includes $10,000 for driveway work. Under a professionally accepted alternative, the necessary driveway scope costs $18,000. Replace the original $10,000 once: revised launch is $53,000. Assume a separate $5,000 review/design amount not included in either driveway scope. These figures do not establish that the real project or alternative will be approved.',
 ('table',['Illustrative choice','Allocation preserving the $40,000 reserve','Outside-plan cash'],[
 ['Original plan, before resolving project impact','$240,000 + $45,000 + $40,000 = $325,000','$25,000; not evidence to proceed'],
 ['Accepted alternative plus distinct review','$240,000 + $53,000 + $5,000 + $40,000 = $338,000','$12,000'],
 ['Same alternative plus $15,000 distinct net delay obligations','$353,000','$3,000 funding gap'],
 ['Different property with independently verified scope','$245,000 + $50,000 + $40,000 = $335,000','$15,000'],
 ]),
 'The third case assumes $15,000 of actual additional net obligations on identified dates, excluding costs already in purchase or launch lines. Replace the input with relevant invoices, avoided costs and the buyer’s real opening schedule. Missing gross guest receipts are not another contractor bill. Paying the $3,000 gap from retained liquidity leaves $37,000, changing the chosen reserve rather than preserving it.',
 'Assume no project-related compensation, seller reimbursement or tax refund has been received. A hoped-for $20,000 later payment cannot erase the $3,000 early funding gap. Do not assume the buyer owns a payment right mentioned in the seller’s correspondence; counsel must evaluate actual entitlement, allocation, agreements and timing. This comparison does not value a taking, calculate damages or say compensation must fund an alternative.',
 'The different property is an invented comparison, not an available listing or guaranteed superior return. It requires independent diligence, actual financing and supported income. Compare both candidates’ usable site, work permissions, debt, recurring costs and launch timing, not merely their allocations. The <a href="/tools/first-str-purchase-budget/">purchase-budget worksheet</a> helps keep overlapping work, dated outflows and retained cash separate.',
 ]),
 ('Resolve decisive project evidence before releasing protection',[
 'Have counsel review actual seller notices, project agreements, property rights and contract terms. Ask how the transaction handles pending correspondence, document delivery, any payment interests, access for investigation and evidence that must exist before funding. Do not sign project documents, release claims, alter access or start work because a seller says it is routine. This is a review instruction, not model legal language or a recommendation to oppose a public project.',
 'Proceed when the agency evidence and its limitations are understood, the accepted site/operating plan is executable, financing and insurance questions are resolved and independently funded downside fits the buyer’s standards. Reprice a still-viable plan when actual scope or cost changes its offer ceiling. Delay under valid protection while a decisive answer is missing, or decline the property when the essential acquisition thesis remains unsupported. No checklist creates an extension or cancellation right.',
 'Set a handoff owner to monitor the official project and update the acquisition file if a new drawing, notice or access answer arrives before closing. After purchase, keep the operating plan aligned with actual conditions and official directions. Store notices, legal analysis, policy documents and financial records in agreed secure channels, not in a public application narrative.',
 '<a href="/apply/">Compare the project-affected STR with a verified acquisition shortlist</a>. BNB Accelerator coordinates purchase work within its agreement; agency officials and independent counsel, surveyors, site professionals, title advisers, lenders and insurers determine their respective conclusions. Use the <a href="/blog/buy-str-high-income-large-tax-bill/">high-income buyer roadmap</a> to connect this decision with available capital rather than anticipated tax savings.',
 'TxDOT primary manual text checked October7,2026. Texas phases are an illustrative program example, not nationwide rules; no image-only table, linked video or intranet content is relied upon. Educational only, not eminent-domain, compensation, title, surveying, engineering, permitting, insurance, lending, tax or personalized investment advice. All example amounts are hypothetical. No project outcome, payment, approval, booking or investment result is guaranteed.',
 ]),
 ],
 'faqs':[
 ('Does a proposed road line prove my STR parcel will be acquired?','No. Verify the official project, stage, drawing version and parcel-specific information with the responsible agency and qualified advisers. A planning line is not a completed legal acquisition or construction schedule.'),
 ('Does a current survey resolve a future road-project impact?','Not by itself. Coordinate current boundaries and rights with current project information, proposed access and the actual work footprint. Different professionals determine the spatial, legal and project-status conclusions.'),
 ('Can expected compensation fund the STR purchase now?','Not before actual accessible funds and entitlement are established. Have counsel review who owns any relevant payment right, its conditions and timing; compare the purchase without assumed receipts.'),
 ('Should I add a full new driveway quote to the original allowance?','Replace overlapping work once, add only distinct review and net delay obligations, and show retained liquidity separately. A funded alternative still needs actual legal and professional acceptance.'),
 ],
 'related':['<a href="/blog/str-due-diligence-checklist/">Translate evidence into the purchase decision</a>','<a href="/blog/str-purchase-to-launch-timeline/">Match work dependencies to opening</a>'],
 'cta_h':'Verify the project before committing to the property',
 'cta_p':'Connect official project evidence and a supported site plan to a funded STR acquisition comparison.',
}
if __name__=='__main__':
 publisher.SLUG,publisher.ROUTE=SLUG,ROUTE
 publisher.TITLE,publisher.DESC,publisher.POST=TITLE,DESC,POST
 publisher.main(745,2486,'data-public-road-project-link',f'Considering a property near planned public works? Verify the <a href="{ROUTE}">road-project stage, parcel footprint and access alternative</a> without treating hoped-for compensation as purchase cash.')
