"""One source-reviewed land-use enrollment acquisition guide; scoped renderer."""
import posts_reverse_exchange_str as publisher

SLUG = 'land-use-tax-enrollment-before-buying-str'
ROUTE = f'/blog/{SLUG}/'
TITLE = 'Land-Use Tax Enrollment Before Buying an STR'
DESC = 'Buying an STR on agricultural or current-use land? Verify enrollment, proposed site changes, possible rollback charges and cash before offering.'
POST = {
 'slug': SLUG, 'title': TITLE, 'title_tag': TITLE,
 'h1': 'Buying an STR on land with agricultural or current-use tax treatment',
 'description': DESC, 'date': '2026-10-07', 'category': 'Acquisition & Financing',
 'lead': 'A rural STR can have a modest current property-tax bill because some land receives agricultural, forest or other use-based treatment. Buying it for guest stays does not tell you whether that treatment continues, what site changes matter or whether an additional charge could become payable. Before offering, identify the actual program and enrolled area, submit the proposed use to the responsible local office and reconcile the buyer’s recurring tax line with any separate transition liability. A large W-2 income or hoped-for income-tax deduction does not fund an unexpected land-use bill. <a href="/apply/">Discuss the acreage property and acquisition budget</a> while local counsel, the assessing authority and your tax adviser resolve their respective questions.',
 'sections': [
 ('Identify the enrollment behind the seller’s low bill', [
 'Request the official parcel assessment, latest tax bill, enrollment or special-appraisal records, application history and relevant maps. Match parcel identifiers to every tract being purchased. Separate the building and residential area from land receiving the special treatment; a listing’s acreage total is not an enrollment map. Record the program name, qualifying activity, current owner and year of each record. Ask which documents are missing rather than interpreting a marketing label as approval.',
 'The <a href="https://comptroller.texas.gov/taxes/property-tax/ag-timber/">Texas Comptroller’s agricultural appraisal guidance</a> describes productivity-based valuation and qualifying use requirements, including locally accepted intensity. Its change-of-use discussion distinguishes agricultural appraisal provisions and possible rollback treatment. “Ag exemption” in a listing is therefore not enough to identify the actual rules. This Texas source was checked October 7, 2026; it is not a nationwide test or a finding about any property.',
 'The existing <a href="/blog/property-tax-reset-after-buying-str/">property-tax reset guide</a> addresses the buyer’s annual assessment, exemptions and closing proration. This guide addresses an additional acquisition decision: whether an enrolled land-use plan survives the actual handoff and proposed site changes, and what separate liability must be funded. Do not replace the broader annual-tax review with an enrollment check.',
 ]),
 ('Give the assessor a real site plan, not just the word Airbnb', [
 'Show the proposed building use, guest areas, parking, driveways, amenity work and any land operation you intend to continue. Identify current farm or forest activities, the relevant operator and what changes at closing. Ask the office which facts determine eligibility, whether a new application or notice is required, who must file it and the actual deadline. Obtain the applicable form and written response where available. A preliminary response can depend on facts that later change; preserve its assumptions.',
 ('table', ['Evidence row', 'Buyer question', 'Decision owner'], [
 ['Enrolled parcel and area', 'Do the official map and proposed conveyance describe the same land?', 'Assessor, surveyor and title counsel'],
 ['Qualifying use and history', 'What activity and records support the existing treatment?', 'Assessing authority and land-use specialist'],
 ['Buyer’s proposed changes', 'Which specific areas or activities require a new eligibility decision?', 'Assessing authority and local counsel'],
 ['Transfer and reporting steps', 'What filing, signature and date apply to this transaction?', 'Buyer’s assigned adviser'],
 ['Possible additional charge', 'What event, calculation, payer and payment date must be resolved?', 'Assessing authority and settlement counsel'],
 ['Ongoing responsibility', 'Who performs and documents the necessary work after purchase?', 'Buyer and contracted operator'],
 ]),
 'Original hypothetical footprint exercise: the sale includes 20 acres, with two acres shown as house and yard and 18 described as enrolled field. The buyer proposes two acres of new parking and a drive within that field. Mark the proposed footprint on the authoritative map and request a determination. Do not simply conclude that 16 acres remain qualified or that only two acres generate a charge. Boundary definitions, program conditions and the actual change can affect the answer. The arithmetic locates the question; it does not decide eligibility.',
 'Preserving a qualifying activity also creates an acquisition responsibility. Ask for the actual lease or service scope, succession arrangements, access rights and a priced work plan. Do not assume a seller’s tenant will continue, a manager will handle farming or token livestock will qualify. Evaluate whether guests, contractors and the land operator can use the site lawfully and safely. Rental permission, insurance and recorded restrictions remain separate gates.',
 ]),
 ('Separate a transfer from a disqualifying change', [
 'The current <a href="https://law.lis.virginia.gov/vacode/title58.1/chapter32/section58.1-3237/">Virginia Code section 58.1-3237</a> addresses rollback consequences for certain nonqualifying use or owner-requested zoning changes. It also distinguishes a title transfer that continues qualifying use under the applicable conditions, and provides local-ordinance qualifications. This source was checked October 7, 2026. It demonstrates why neither “every sale triggers rollback” nor “a sale never matters” is a reliable national rule.',
 'Ask professionals to classify three separate events: what the seller already did, what the conveyance changes and what the buyer proposes after closing. A pending notice, unreported change or unresolved application belongs in the diligence file. Determine the actual tax authority’s treatment rather than declaring a violation from an aerial photo. Also ask whether annual eligibility can change without the same event or amount as an additional historical charge.',
 'Request a parcel-specific calculation or documented method, the covered periods, affected area, any interest or other components and the expected assessment and due dates. Keep an estimate clearly labeled until final. Do not multiply the entire purchase price by a generic penalty percentage. Do not import Texas periods into Virginia or another program. Contract allocation between buyer and seller must be reviewed separately from the authority’s liability rules.',
 'Counsel and the settlement team should resolve disclosed assessments, notices, title issues and any negotiated payment arrangement with the lender where needed. A seller promise to reimburse later is not cleared cash or an automatic release from liability. No checklist creates escrow rights, a cancellation remedy or a deadline extension. Use the <a href="/blog/title-commitment-before-buying-str/">title packet guide</a> to keep these questions tied to the actual conveyance.',
 ]),
 ('Worked purchase test: one-time charge versus recurring tax', [
 'Hypothetical planning figures only, not market data, a statutory calculation, tax advice or a client result. Assume designated available cash is $300,000. The reviewed plan allocates $210,000 to purchase equity and closing outflows, $35,000 to distinct setup work and $35,000 to retained liquidity. Total allocation is $280,000, leaving $20,000 outside the plan. The reserve remains accessible cash, not another expense.',
 'Assume a professional review identifies a separate estimated $24,000 historical land-use charge payable by this buyer before opening, under the example’s accepted documents. It is not already in the closing or setup lines. Total required allocation becomes $304,000, creating a $4,000 gap against available funds while preserving the stated reserve. Removing $4,000 from that reserve balances the numbers but changes the risk decision; it does not eliminate the charge. An unresolved payer or due date must remain unresolved rather than being silently assigned to the seller.',
 'Separately suppose researched full-year property taxes are $10,800 instead of the seller-based $4,200. The recurring increase is $6,600. If the previous model showed $22,000 annual owner cash after its operating costs and debt payments, changing only that tax input leaves $15,400. This is cash sensitivity, not guaranteed income or a lender’s DSCR calculation. The example’s $24,000 charge covers historical periods only; current and future annual taxes are separate. Reconcile the actual charge components to avoid counting a current-year adjustment twice.',
 'A one-time credit, if valid and usable under the actual transaction, can address an immediate outflow but does not permanently pay the $6,600 annual difference. Conversely, a lower annual forecast does not tell you when the $24,000 must be paid. Put both into a dated cash schedule with other independently supported costs and receipts. Do not count an expected tax refund, appeal success, new guest income or discretionary loan proceeds as already available funds. Compare a properly supported continuing-use alternative without assuming its eligibility or economics.',
 ]),
 ('Close only with a workable use and responsibility handoff', [
 'Prepare a bounded purchase memo: program and parcel identifiers, enrolled-area evidence, proposed-use plan, authority’s response and limitations, filing owner and deadlines, charge estimate and payer treatment, revised annual tax and funded cash schedule. Keep full financial and seller records in secure adviser channels; the ordinary acquisition application needs the question and status, not private tax returns or unredacted documents.',
 'Proceed when the actual use, required work and reporting fit a lawful STR opening and acceptable financing, and the conservative cash case remains funded. Renegotiate a confirmed cost through valid contract terms. Delay under adequate protection when a decisive determination is missing. Decline when the deal depends on unsupported enrollment, incompatible land operations or unfunded obligations. The <a href="/financing/closing-costs-and-reserves/">purchase cash framework</a> and <a href="/blog/buy-str-high-income-large-tax-bill/">high-income buyer roadmap</a> keep this property decision separate from assumed income-tax benefits.',
 '<a href="/apply/">Compare the acreage STR with other acquisition candidates</a> using that memo. BNB Accelerator coordinates search, underwriting and transaction work within its agreement; it does not replace the assessing authority, local counsel, land-use specialist, lender or tax adviser. Educational only, not legal, tax, agricultural, forestry, insurance, lending or personalized investment advice. Examples are invented. No continuing qualification, approval, reimbursement, deduction, booking or investment result is guaranteed.',
 ]),
 ],
 'faqs': [
 ('Can I assume the seller’s agricultural tax treatment continues after buying an STR?', 'No. Identify the actual program, enrolled area, proposed buyer use and required transfer or reporting steps with the responsible authority. A listing label is not an eligibility decision.'),
 ('Does every purchase trigger a rollback tax?', 'No nationwide answer applies. The transfer, actual use changes, program and local rules must be reviewed separately. Do not assume either automatic liability or automatic continuation.'),
 ('Is a possible rollback charge the same as the buyer’s annual property tax?', 'No. Reconcile any additional charge and its covered periods separately from recurring annual tax and closing proration. Check whether a current-year adjustment is already included to avoid double counting.'),
 ('Does keeping the land operation make the STR acquisition viable?', 'Not by itself. Confirm qualification, an executable responsibility handoff, lawful guest use, financing and funded cash. Neither a seller’s operator nor a token activity is an approved continuation plan.'),
 ],
 'related': ['<a href="/blog/property-tax-reset-after-buying-str/">Rebuild the annual buyer-case tax line</a>', '<a href="/blog/title-commitment-before-buying-str/">Review the conveyed parcel and title packet</a>'],
 'cta_h': 'Verify the land-use tax handoff before offering',
 'cta_p': 'Connect the parcel evidence, buyer’s site plan and complete cash schedule to the acquisition.',
}

if __name__ == '__main__':
    publisher.SLUG, publisher.ROUTE = SLUG, ROUTE
    publisher.TITLE, publisher.DESC, publisher.POST = TITLE, DESC, POST
    publisher.main(742, 2483, 'data-land-use-tax-link', f'Buying an acreage property with a low tax bill? Verify the <a href="{ROUTE}">land-use enrollment, site changes and possible transition charge</a> before committing cash.')
