"""Record observed release evidence without issuing another Inspection."""
import csv,io,json
from pathlib import Path
R=Path(__file__).resolve().parents[1]/'_gen'
U='https://www.bnbaccelerator.com/blog/cleaning-fees-gross-revenue/'
C='c4496e8cfdc156b63b048c917ce4bddfa1056446';T='2026-10-08T05:49:32.373196+00:00'
I='Prior actual05:35:33.870614UTC NEUTRAL/discoveredcurrentlynotindexed/no reportedcrawl; not revised-body receipt or observed gain'
S='Three changed canonicals IndexNowHTTP200;blogXML2026-10-08T05:49:47.873Zacceptedconfirmedpending/zero reportederrorswarnings;not confirmed indexing'
e={'content_commit':C,'verified_at':T,'exact_changed_public_artifacts':4,'protected_homepage_exact':True,'independent_internal_links_assets_checked':57,'deployment_propagation':'Initial exact-body mismatch; single30second propagation retry passed','records':[{'url':U,'http_status':200,'final_url':U,'canonical':U,'robots_allowed':True,'noindex':False,'exact_public_build_match':True,'server_article_text':True,'publication_date':'2026-09-23','modified_date':'2026-10-08','words':1489,'matched_faqs':4,'sitemap_entries':1,'sitemap_lastmod':'2026-10-08','inbound_public_pages':3,'internal_targets':57,'googlebot_ua_http_200':True}],'indexnow':{'changed_urls':[U,'https://www.bnbaccelerator.com/blog/','https://www.bnbaccelerator.com/blog/buy-str-high-income-large-tax-bill/'],'http_status':200,'meaning':'Accepted for processing, not indexing'},'google_sitemap':{'url':'https://www.bnbaccelerator.com/sitemap-blog.xml','accepted':True,'confirmed':True,'last_submitted':'2026-10-08T05:49:47.873Z','pending':True,'reported_errors':0,'reported_warnings':0},'actual_google_indexing':I,'indexing_baseline':'_gen/cleaning-fees-indexing-baseline-2026-10-08.json','limits':'Serving/eligibility is not actual Google crawl, browser rendering, revised indexing or search/conversion gain; no authenticated Vercel status asserted.'}
(R/'cleaning-fees-purchase-live-evidence.json').write_text(json.dumps(e,indent=2)+'\n')
p=R/'expansion_509_progress.json';raw=p.read_text();d=json.loads(raw);old=d['separately_counted_existing_refreshes'];assert len(old)==69 and not any(x['url']==U for x in old)
entry={'url':U,'content_commit':C,'verified_live_at':T,'evidence':'_gen/cleaning-fees-purchase-live-evidence.json','indexing_baseline':'_gen/cleaning-fees-indexing-baseline-2026-10-08.json','actual_google_indexing':I,'counted_toward_509':False,'improvement':'Original same-reservation acceptance register, equivalent gross/net reporting comparison, allocated fee exposure, buyer-cost/turn-mix sensitivities and incremental launch cash bridge; bounded current Airbnb primary sources','validation':'Required checks plus RevPAR/fullfourpublicdiff/745othercards/math/homehashes/similarity0.014;exactfourartifacts/57links/3inbound/fourmatchedFAQs/GooglebotUA200','submission':S}
needle='"separately_counted_existing_refreshes": [';assert raw.count(needle)==1
raw=raw.replace(needle,needle+'\n'+'\n'.join('    '+x for x in json.dumps(entry,indent=2).splitlines())+',',1);new=json.loads(raw);assert new['separately_counted_existing_refreshes'][1:]==old and new['verified_live_new_pages']==8;p.write_text(raw)
p=R/'blog-indexing-inventory.csv';raw=p.read_bytes().decode();lines=raw.splitlines(keepends=True);reader=csv.DictReader(io.StringIO(raw));fields=reader.fieldnames;row=next(x for x in reader if x['url']==U)
assert row['observed_at']=='2026-10-08T05:35:33.870614+00:00'
row.update(http_status='200',final_url=U,robots_allows_googlebot='True',source_noindex='False',live_noindex='False',source_canonical=U,live_canonical=U,sitemap_included='True',inbound_pages='3',article_text_present='True',probe_error='',recommended_action=f'Existing expansion{C} exactlive{T}/fourartifacts/57links/3inbound. Prior05:35discovered/nocrawl retained, not revisedreceipt/gain/cause. Changedonly submissions accepted; measure later crawl and buyer queries.')
i=next(i for i,l in enumerate(lines) if l.startswith(U+','));out=io.StringIO();w=csv.DictWriter(out,fieldnames=fields,lineterminator='\r\n' if lines[i].endswith('\r\n') else '\n');w.writerow(row);lines[i]=out.getvalue();p.write_bytes(''.join(lines).encode())
note=f'\nCompleted{C} exactlive{T} afterone30secondretry:fourartifacts/57links-assets/3inbound/1489words/fourmatchedFAQs/GooglebotUA200/selfcanonical/robotsallowed/noindexabsent/singleOct8XML/homeexact. {S}. {I}. Existingrefresh70/eightnewof509/sevenaccuracy;comparison15/resource7 unchanged. Content-creation skill shaped same-reservation purchase worksheet; scoped SEO-audit overlap review preserved existing intent owners. Next substantive revenue evidence and actual competing acquisition-owner gaps, not a provider variant. ACTIVEfive-minute schedule preserved.\n'
for name in ['cleaning-fees-purchase-quality-review.md','investor-coverage-ledger.md']:
 p=R/name;s=p.read_text();p.write_text(s+note if name.startswith('cleaning') else s.replace('# Investor acquisition coverage ledger\n','# Investor acquisition coverage ledger\n'+note,1))
print('Recorded existingrefresh70/new8; prior actual discovery preserved without reinspection.')
