"""Record observed live checks, not a new inspection or probe."""
import csv,io,json
from pathlib import Path
R=Path(__file__).resolve().parents[1]/'_gen'
U='https://www.bnbaccelerator.com/blog/str-maintenance-response-sla/'
C='f3be4ff1b1c0fd3380f8c86e8cbdc1f6b4b2b718'
T='2026-10-08T05:02:53.231987+00:00'
I='Prior actual04:47:35.994423UTC NEUTRAL/Discovered-currently-not-indexed/no reportedcrawl retained; not revised-body receipt, trend or diagnosed cause'
S='Three changed canonicals IndexNowHTTP200;blogXML2026-10-08T05:03:07.791Zacceptedconfirmedpending/zero reportederrorswarnings;not confirmed indexing'
e={'content_commit':C,'verified_at':T,'exact_changed_public_artifacts':4,'protected_homepage_exact':True,'independent_internal_links_assets_checked':56,'verification_access':'Initial sandbox DNS failure; authorized network verification passed. No production defect inferred.','records':[{'url':U,'http_status':200,'final_url':U,'canonical':U,'robots_allowed':True,'noindex':False,'exact_public_build_match':True,'server_article_text':True,'publication_date':'2026-09-23','modified_date':'2026-10-08','words':1306,'matched_faqs':4,'sitemap_entries':1,'sitemap_lastmod':'2026-10-08','inbound_public_pages':3,'internal_targets':56,'googlebot_ua_http_200':True}],'indexnow':{'changed_urls':[U,'https://www.bnbaccelerator.com/blog/','https://www.bnbaccelerator.com/blog/buy-str-high-income-large-tax-bill/'],'http_status':200,'meaning':'Accepted for processing, not indexing'},'google_sitemap':{'url':'https://www.bnbaccelerator.com/sitemap-blog.xml','accepted':True,'confirmed':True,'last_submitted':'2026-10-08T05:03:07.791Z','pending':True,'reported_errors':0,'reported_warnings':0},'actual_google_indexing':I,'indexing_baseline':'_gen/maintenance-sla-indexing-baseline-2026-10-08.json','limits':'Independent serving/eligibility checks are not actual Google crawl, browser rendering, indexing or search/conversion gains; no authenticated Vercel deployment status asserted.'}
(R/'maintenance-sla-purchase-live-evidence.json').write_text(json.dumps(e,indent=2)+'\n')
p=R/'expansion_509_progress.json';raw=p.read_text();d=json.loads(raw);a=d['separately_counted_existing_refreshes'];assert len(a)==67 and not any(x['url']==U for x in a)
entry={'url':U,'content_commit':C,'verified_live_at':T,'evidence':'_gen/maintenance-sla-purchase-live-evidence.json','indexing_baseline':'_gen/maintenance-sla-indexing-baseline-2026-10-08.json','actual_google_indexing':I,'counted_toward_509':False,'improvement':'Original accepted-address response-clock register, unavailable-buyer authorization branch and hypothetical retainer/work/launch-cash comparison with bounded current Airbnb primary evidence','validation':'Required checks plus RevPAR/fullfourpublicdiff/745othercards/math/homehashes/similarity0.018;exactfourartifacts/56links/3inbound/fourmatchedFAQs/GooglebotUA200','submission':S}
needle='"separately_counted_existing_refreshes": [';assert raw.count(needle)==1
formatted='\n'.join('    '+x for x in json.dumps(entry,indent=2).splitlines());raw=raw.replace(needle,needle+'\n'+formatted+',',1);new=json.loads(raw)
assert new['separately_counted_existing_refreshes'][1:]==a and new['verified_live_new_pages']==8
p.write_text(raw)
p=R/'blog-indexing-inventory.csv';raw=p.read_bytes().decode();lines=raw.splitlines(keepends=True);reader=csv.DictReader(io.StringIO(raw));fields=reader.fieldnames;row=next(x for x in reader if x['url']==U)
row.update(http_status='200',final_url=U,robots_allows_googlebot='True',source_noindex='False',live_noindex='False',source_canonical=U,live_canonical=U,sitemap_included='True',inbound_pages='3',article_text_present='True',probe_error='',recommended_action=f'Existing expansion {C} exactlive {T}/fourartifacts/56links/3inbound. Prior actual04:47discovered/no reportedcrawl retained, not revisedreceipt or cause; changedonly submissions accepted not indexing. Measure later crawl and buyer queries.')
i=next(i for i,l in enumerate(lines) if l.startswith(U+','));b=io.StringIO();w=csv.DictWriter(b,fieldnames=fields,lineterminator='\r\n' if lines[i].endswith('\r\n') else '\n');w.writerow(row);lines[i]=b.getvalue();p.write_bytes(''.join(lines).encode())
completion=f'\nCompleted{C} exactlive{T}:fourartifacts/56links-assets/3inbound/1306words/fourmatchedFAQs/GooglebotUA200/selfcanonical/robotsallowed/noindexabsent/singleOct8XML/homeexact. Initial sandbox DNS failure resolved by authorized network verification, not a production defect. {S}. {I}. Existingrefresh68/eightnewof509/sevenaccuracy; comparison15/resource7 unchanged. Content-creation skill shaped buyer-first evidence and comparison. Next qualified acquisition-service long-tail gaps; ACTIVEfive-minute schedule preserved.\n'
for name in ['maintenance-sla-purchase-quality-review.md','investor-coverage-ledger.md']:
 p=R/name;s=p.read_text();p.write_text(s+completion if name.startswith('maintenance') else s.replace('# Investor acquisition coverage ledger\n','# Investor acquisition coverage ledger\n'+completion,1))
print('Recorded existingrefresh68/new8/sevenaccuracy; actual Inspection unchanged, no new509 credit.')
