"""Persist observed live results; do not issue another Inspection."""
import csv,io,json
from pathlib import Path
R=Path(__file__).resolve().parents[1]/'_gen'
U='https://www.bnbaccelerator.com/blog/cleaner-capacity-peak-season/'
C='d1f79f8f0aa92e85fc9c630cf6e3ef9233ab2350';T='2026-10-08T05:28:44.157776+00:00'
I='Prior actual05:20:01.415762UTC PASS/submittedandindexed/reported02:13:34mobile successfulcrawl; not revised-body receipt or observed gain'
S='Three changed canonicals IndexNowHTTP200;blogXML2026-10-08T05:28:56.691Zacceptedconfirmedpending/zero reportederrorswarnings;not confirmed revised indexing'
e={'content_commit':C,'verified_at':T,'exact_changed_public_artifacts':4,'protected_homepage_exact':True,'independent_internal_links_assets_checked':56,'deployment_propagation':'Initial exact-body mismatch; single30second propagation retry passed','records':[{'url':U,'http_status':200,'final_url':U,'canonical':U,'robots_allowed':True,'noindex':False,'exact_public_build_match':True,'server_article_text':True,'publication_date':'2026-09-23','modified_date':'2026-10-08','words':1330,'matched_faqs':4,'sitemap_entries':1,'sitemap_lastmod':'2026-10-08','inbound_public_pages':3,'internal_targets':56,'googlebot_ua_http_200':True}],'indexnow':{'changed_urls':[U,'https://www.bnbaccelerator.com/blog/','https://www.bnbaccelerator.com/blog/buy-str-high-income-large-tax-bill/'],'http_status':200,'meaning':'Accepted for processing, not indexing'},'google_sitemap':{'url':'https://www.bnbaccelerator.com/sitemap-blog.xml','accepted':True,'confirmed':True,'last_submitted':'2026-10-08T05:28:56.691Z','pending':True,'reported_errors':0,'reported_warnings':0},'actual_google_indexing':I,'indexing_baseline':'_gen/cleaner-capacity-indexing-baseline-2026-10-08.json','limits':'Serving/eligibility is not actual Google crawl, browser rendering, revised indexing or search/conversion gain; no authenticated Vercel status asserted.'}
(R/'cleaner-capacity-purchase-live-evidence.json').write_text(json.dumps(e,indent=2)+'\n')
p=R/'expansion_509_progress.json';raw=p.read_text();d=json.loads(raw);old=d['separately_counted_existing_refreshes'];assert len(old)==68 and not any(x['url']==U for x in old)
entry={'url':U,'content_commit':C,'verified_live_at':T,'evidence':'_gen/cleaner-capacity-purchase-live-evidence.json','indexing_baseline':'_gen/cleaner-capacity-indexing-baseline-2026-10-08.json','actual_google_indexing':I,'counted_toward_509':False,'improvement':'Original six-field accepted peak-day register, sequential crew/linen bottleneck and incremental readiness cash worksheet; bounded current Airbnb primary source','validation':'Required checks plus RevPAR/fullfourpublicdiff/745othercards/math/homehashes/similarity0.022;exactfourartifacts/56links/3inbound/fourmatchedFAQs/GooglebotUA200','submission':S}
needle='"separately_counted_existing_refreshes": [';assert raw.count(needle)==1
raw=raw.replace(needle,needle+'\n'+'\n'.join('    '+x for x in json.dumps(entry,indent=2).splitlines())+',',1);new=json.loads(raw);assert new['separately_counted_existing_refreshes'][1:]==old and new['verified_live_new_pages']==8;p.write_text(raw)
p=R/'blog-indexing-inventory.csv';raw=p.read_bytes().decode();lines=raw.splitlines(keepends=True);reader=csv.DictReader(io.StringIO(raw));fields=reader.fieldnames;row=next(x for x in reader if x['url']==U)
row.update(http_status='200',final_url=U,robots_allows_googlebot='True',source_noindex='False',live_noindex='False',source_canonical=U,live_canonical=U,sitemap_included='True',inbound_pages='3',article_text_present='True',probe_error='',recommended_action=f'Existing expansion{C} exactlive{T}/fourartifacts/56links/3inbound. Prior05:20PASS/02:13crawl retained, not revisedreceipt/gain. Changedonly submissions accepted; measure later crawl and buyer queries.')
i=next(i for i,l in enumerate(lines) if l.startswith(U+','));out=io.StringIO();w=csv.DictWriter(out,fieldnames=fields,lineterminator='\r\n' if lines[i].endswith('\r\n') else '\n');w.writerow(row);lines[i]=out.getvalue();p.write_bytes(''.join(lines).encode())
note=f'\nCompleted{C} exactlive{T} afterone30secondretry:fourartifacts/56links-assets/3inbound/1330words/fourmatchedFAQs/GooglebotUA200/selfcanonical/robotsallowed/noindexabsent/singleOct8XML/homeexact. {S}. {I}. Existingrefresh69/eightnewof509/sevenaccuracy;comparison15/resource7 unchanged. Content-creation skill shaped buyer-first route/material/cash worksheet. Next substantive buyer gaps; ACTIVEfive-minute schedule preserved.\n'
for name in ['cleaner-capacity-purchase-quality-review.md','investor-coverage-ledger.md']:
 p=R/name;s=p.read_text();p.write_text(s+note if name.startswith('cleaner') else s.replace('# Investor acquisition coverage ledger\n','# Investor acquisition coverage ledger\n'+note,1))
print('Recorded existingrefresh69/new8; prior actual indexed baseline preserved without reinspection.')
