"""Scoped existing comparable-selection owner refresh; no library generator."""
from refresh_dscr_purchase_methods import refresh
BODY='''<p class="lead">Before buying a short-term rental, ask why each property belongs in the revenue comparison. A nearby listing with the same bedroom count can have different lawful capacity, access, amenities, availability or guest purpose. Keep a dated inclusion-and-exclusion record, distinguish estimated results from actual owner records, and test whether the purchase still fits when an attractive comparison is removed. A polished average is not verified future income.</p>
<p><a href="/apply/">Bring the subject property and the comparable-selection record to an acquisition call</a>. BNB Accelerator assists within its contracted acquisition scope. This guide answers which listings support the comparison; the separate <a href="/blog/airbnb-revenue-projections/">revenue-method and owner-cash guide</a> builds the monthly purchase forecast and complete expense case.</p>
<h2>Match the intended purchase, not just the listing label</h2>
<p>Start with the subject address, intended lawful guest capacity, bedroom and bathroom configuration, parking, amenities actually usable at opening, access and likely trip purpose. Check permit and occupancy constraints independently; a listing's advertised guest count is not a legal determination. Define the relevant demand area by the buyer's actual use case rather than assuming every property in one city competes equally.</p>
<p>Record meaningful differences instead of inventing automatic premiums. A claimed mountain view needs verification; a nearby lodge with a pool may compete for a different group than a smaller cabin without one. Geography, photographs and amenities can explain a candidate match, but none establishes a precise revenue adjustment. A proposed upgrade also needs physical feasibility, permission, cost and an opening date before its hoped-for performance enters the purchase case.</p>
<h2>Automated sets are reviewable inputs, not a universal winner or loser</h2>
<p><a href="https://help.airdna.co/en/articles/10559022-rentalizer-revenue-calculator">AirDNA's Rentalizer documentation, dated June 19, 2026</a>, describes an initial nearby set using bedroom, bathroom and guest-count similarities. It also describes editable comparable sets, amenity filters, availability information and monthly projections. Its address projection assumes full 365-day availability and includes cleaning fees. Those features make the old blanket claim that automated tools cannot account for amenities inaccurate. They do not independently verify this property's lawful use, condition, access, buyer opening calendar or future results.</p>
<p>Keep the report date, selected listings and field definitions before changing the set. Document your own reasons for additions and removals and preserve the earlier version. A manually chosen set can be biased too. An automatic selection is not a reason to accept an unsuitable listing; manual selection is not permission to retain only the best performers. This is document-based analysis, not firsthand tool testing or a provider accuracy score.</p>
<h2>Use this original comparable-selection worksheet</h2>
<div class="table-wrap"><table><thead><tr><th>Field</th><th>Evidence to retain</th><th>Purchase consequence if unresolved</th></tr></thead><tbody>
<tr><td>Property identity</td><td>Listing identifier, address where legitimately available, channel and duplicate check</td><td>Two channel listings must not silently become two independent assets</td></tr>
<tr><td>Guest and physical match</td><td>Lawful capacity, layout, access, parking and usable amenities</td><td>Explain the mismatch; do not invent a premium to close it</td></tr>
<tr><td>Period and availability</td><td>Covered dates, available days, opening or outage context</td><td>A peak quarter or partly unavailable year is not a full operating year</td></tr>
<tr><td>Performance provenance</td><td>Authorized owner evidence or named third-party estimate, field definitions and version</td><td>A modeled listing result is not its owner's booking ledger</td></tr>
<tr><td>Selection decision</td><td>Included, excluded or context-only; specific reason recorded before reviewing the desired average</td><td>Removing a low result without a factual mismatch can bias the purchase case</td></tr>
<tr><td>Uncertainty and reviewer</td><td>Missing evidence, qualified review owner and real decision deadline</td><td>Keep the unsupported adjustment outside the relied-on case</td></tr>
</tbody></table></div>
<p>There is no universal count established here. More listings do not repair inconsistent periods or mismatched assets, and a small coherent set may still be too uncertain for the intended decision. Explain coverage, independence and material gaps. If suitable evidence is scarce, report that limitation rather than filling a quota with distant properties. Request additional supported evidence or reconsider the purchase; do not label a small set statistically reliable merely because all results are close.</p>
<h2>Worked selection example: why an attractive average changes</h2>
<p>Every amount and property below is invented, not market data, a client outcome or a reliable sample-size recommendation. Suppose the intended asset has no pool. Candidate A has a comparable layout and an annual lodging-only estimate of $60,000; B is $66,000; C is $72,000. Assume their periods and definitions match solely for this exercise. Candidate D is a materially different pool property with a $110,000 annual estimate. E shows $20,000 for only a peak quarter. F is a second channel record of B, not another property.</p>
<div class="table-wrap"><table><thead><tr><th>Candidate</th><th>Illustrative decision</th><th>Reason</th></tr></thead><tbody>
<tr><td>A: $60,000 annual</td><td>Retain in the exercise</td><td>A lower result alone does not make it unsuitable</td></tr>
<tr><td>B: $66,000 annual</td><td>Retain one asset record</td><td>Matching assumptions; reconcile its other channel record</td></tr>
<tr><td>C: $72,000 annual</td><td>Retain in the exercise</td><td>Matching assumptions, not guaranteed subject performance</td></tr>
<tr><td>D: $110,000 annual</td><td>Context only in this exercise</td><td>Material pool mismatch; no supported adjustment supplied</td></tr>
<tr><td>E: $20,000 peak quarter</td><td>Do not mix into annual average</td><td>Different covered period; no annualization assumed</td></tr>
<tr><td>F: another record of B</td><td>Resolve the duplicate</td><td>Do not overweight one property as two assets</td></tr>
</tbody></table></div>
<p>A, B and C total $198,000; their simple mean is $66,000. Including D gives $308,000 across four assets, or $77,000. That $11,000 change comes from selection, not improved performance of the subject. If someone removes A just because its estimate is lower and keeps D, B/C/D average about $82,667. Neither figure validates an offer. These simple unweighted calculations explain the selection effect, not AirDNA's algorithm or a prediction that your property earns $66,000.</p>
<p>Keep A unless further evidence supplies a genuine reason to exclude it. Weak photographs, few reviews or an apparently static asking rate do not by themselves establish poor management or prove the buyer can achieve more. Likewise, a high-revenue listing is not automatically irrelevant: determine the actual mismatch and whether an adjustment has support. Preserve both the selection decision and the unadjusted comparison so the reviewer can see what changed.</p>
<h2>A visible calendar is not a paid-night ledger</h2>
<p><a href="https://www.airbnb.com/help/article/447">Airbnb's calendar guidance</a> explains that hosts can block nights and that settings and other conditions can make nights unavailable. Do not record every unavailable date on someone else's public calendar as a sold night. <a href="https://www.airbnb.com/help/article/2715">Airbnb's performance definitions</a> distinguish booked nights, available nights, check-ins and nightly revenue. Obtain authorized supporting records when available; otherwise label the third-party method and uncertainty. Do not request account passwords or unnecessary guest data.</p>
<p>Align the comparison periods and fee definitions before averaging. An estimate including cleaning charges is not directly comparable with lodging-only revenue or net platform payouts. A fully available model is not the same opening case as a property awaiting repairs or permissions. Review first-year unavailable dates independently; no review-count rule or fixed ramp guarantees convergence to established performance. The <a href="/blog/blocked-calendar-demand-signal/">blocked-calendar evidence guide</a> and <a href="/blog/reconcile-airbnb-payout-export/">seller payout reconciliation</a> answer those narrower evidence questions.</p>
<h2>Turn the set into a supported purchase decision</h2>
<p>Do not stop at the revised average. Give the analyst the subject's dated opening plan, supported amenities and complete costs; compare downside using consistent geography and periods. Test the largest unsupported inclusion or adjustment separately and show its effect before price or capital is committed. A set of matching estimates can still omit a changing local supply, an unsuitable permit or unaffordable insurance. The <a href="/guides/str-deal-evidence-register/">deal evidence register</a> assigns each unresolved investment assumption an owner and deadline.</p>
<p>Proceed only when the independently checked use, purchase terms and funded downside fit. Reprice when verified evidence changes the economics. Ask the retained transaction adviser about valid protection while essential evidence is missing; do not assume the worksheet creates cancellation rights. Decline a purchase that depends on unexplained cherry-picking or unavailable cash. Use the <a href="/blog/how-to-analyze-airbnb-deal/">complete deal analysis</a> and <a href="/tools/first-str-purchase-budget/">purchase cash budget</a>; a large tax bill does not validate a revenue estimate.</p>
<p><a href="/apply/">Discuss the shortlist with the dated set and exclusion reasons</a>, then follow the <a href="/blog/buy-str-high-income-large-tax-bill/">high-income buyer roadmap</a>. BNB Accelerator is the commercially interested publisher and acquisition provider, not an independent product-review organization. Signed scope and qualified independent advisers govern the actual transaction.</p>
<p class="small">Primary AirDNA and Airbnb materials reviewed October 7, 2026; no publication date is shown for the cited Airbnb help pages. All worked properties and figures are hypothetical. Educational only, not legal, lending, tax or personalized investment advice. No revenue, financing, permit, tax benefit, return or indexing is guaranteed.</p>'''
FAQ=[
 ('How many comparables do I need for a short-term rental analysis?', 'No universal count is established here. Explain comparable coverage, independent assets, matching periods and material gaps. More listings do not repair mismatches, and a small consistent set may still be insufficient for the purchase decision.'),
 ('What is the most common comparable set error?', 'A material risk is accepting nearby properties without checking guest capacity, amenities, availability, performance definitions and data periods. Document inclusion and exclusion reasons rather than selecting results to support a desired price.'),
 ('Should I use an automated comparable tool?', 'It can supply a reviewable starting set. Current AirDNA documentation describes editable sets and amenity filters, but neither an automatic nor a manually selected set verifies the subject property or future income. Preserve the report and explain your changes.')]
if __name__=='__main__':
    refresh('assembling-a-comparable-set','How to Build an STR Comparable Set (2026)','Assembling a Comparable Set That Actually Tells You Something',
      'Build an STR comparable set before offering: document inclusion reasons, reconcile periods and definitions, and test selection bias with a worked worksheet.',
      BODY,FAQ,'2026-08-15','data-comparable-selection-review-link',
      'Use the <a href="/blog/assembling-a-comparable-set/">comparable-selection worksheet and cherry-picking comparison</a> before relying on an attractive revenue average.')
