"""One scoped existing buyer guide; retain dates and shared design."""
from refresh_dscr_purchase_methods import refresh
BODY='''<p class="lead">Choose co-hosting or self-management before approving the STR purchase, not after discovering that your work schedule cannot cover the property. The useful comparison is which tasks each proposal assigns, what the buyer still must do and whether those responsibilities fit the funded purchase. Neither a co-host label nor a high management percentage establishes control, service quality or tax eligibility.</p>
<p>BNB Accelerator publishes this acquisition guide and has a commercial interest in buyer services. This is document-based decision support, not firsthand operator testing or a report of client results. <a href="/apply/">Bring your operating proposals, available hours and cash plan to an acquisition call</a>. BNB's actual contracted scope governs assistance; the selected operator handles day-to-day work.</p>
<h2>The three models describe work splits, not fixed prices</h2>
<p>In a self-managed plan, the owner organizes the operating system and buys whatever outside services are needed. Cleaning, platform fees, software, local response and repair bills do not disappear. Do not call self-management free or treat gross guest receipts as money the owner keeps.</p>
<p>Co-hosting can mean limited support or extensive operation. Full-service management also varies by agreement. Ask each candidate to quote the same address and identify actual tasks, exclusions, fee base and payment triggers. No typical percentage or universal owner-hours range is established here. Compare real written offers using the <a href="/blog/str-property-management-fees/">management-fee register</a>, not a national average presented as your quote.</p>
<p>Account control is a separate question. <a href="https://www.airbnb.com/help/article/1534">Airbnb's co-host guidance</a> permits full-access co-hosts to manage prices and reservations; narrower access does less. Permissions do not define the complete service agreement, and changing access does not change payouts. Confirm the actual listing owner, assigned permissions and contractual spending authority instead of assuming that every co-host leaves pricing with the buyer.</p>
<h2>Original pre-purchase work sample: assign the uncovered shift</h2>
<p>Ask a prospective operator to walk through a late-night lock failure, an absent cleaner and a disputed repair invoice at this address. Record who responds, who can authorize spending, who backs them up and what evidence closes the issue. Do not replace a confirmed local response plan with a phone number and an automation subscription.</p>
<div class="table-wrap"><table><thead><tr><th>Workstream</th><th>Owner commitment to confirm</th><th>Operator or vendor evidence</th></tr></thead><tbody>
<tr><td>Pricing and owner-use calendar</td><td>Who approves changes and monitors agreed limits?</td><td>Permission settings, reporting and override procedure</td></tr>
<tr><td>Guest issues outside business hours</td><td>Who is available when the first contact cannot respond?</td><td>Coverage window, escalation and named local responder</td></tr>
<tr><td>Cleaning and opening readiness</td><td>Who verifies the work rather than only scheduling it?</td><td>Accepted checklist, failed-turnover fallback and invoices</td></tr>
<tr><td>Repairs and supplies</td><td>Who approves amounts and checks recurring bills?</td><td>Spending thresholds, emergency exceptions and separate charges</td></tr>
<tr><td>Records and later switch</td><td>Who owns accounts and accepts the handoff?</td><td>Authorized access, notice duties and existing-booking plan</td></tr>
</tbody></table></div>
<p>Add due dates and cost treatment to each line. An introduced vendor is not necessarily contracted or available. If self-managing, fill the operator column with actual arrangements rather than leaving it blank. If outsourcing, do not presume your approval or backup duties disappear. Use the <a href="/guides/str-service-responsibility-matrix/">responsibility matrix</a> to separate execution from approval.</p>
<h2>Worked comparison: real cash versus a hypothetical value of time</h2>
<p><strong>Invented figures, not market rates, provider quotes or client outcomes:</strong> For the same property, assume $100,000 annual lodging receipts and $65,000 of distinct cash costs including debt, platform charges, cleaning after reconciled reimbursements, insurance, taxes and maintenance. Those costs exclude the service fees below. Before a separate capital-replacement allowance or income-tax consequences, the self-managed case leaves $35,000.</p>
<p>Fictional limited-support Quote A charges $12,000 annually; broader Quote B charges $20,000. With all other assumptions identical, owner cash becomes $23,000 or $15,000. These are alternative work plans, not fees to add together. The $8,000 difference does not establish that either plan delivers better revenue or the same coverage.</p>
<p>Now stipulate owner workloads solely for comparison: self-managed 20 hours monthly, A eight, B three. Annual hours are 240, 96 and 36. A's $12,000 fee divided by 144 hours avoided is about $83.33 per hour. B's additional $8,000 divided by 60 additional hours avoided is about $133.33 per hour. Confirm actual tasks and hours; these figures are not measured savings or a promise that emergencies fit the schedule.</p>
<p>If the buyer chooses an invented $100 hourly value for personal time, the time-adjusted figures are $35,000 − $24,000 = $11,000 self-managed; $23,000 − $9,600 = $13,400 for A; and $15,000 − $3,600 = $11,400 for B. This value-of-time sensitivity is not cash profit, deductible labor, incremental W-2 pay or a tax-participation calculation. A's larger adjusted figure does not settle the decision if it lacks needed local coverage. Keep the time adjustment out of the bank-account cash schedule.</p>
<h2>Fund a fallback without pretending time can pay invoices</h2>
<p>Separately, assume $250,000 accessible purchase cash and $247,000 already assigned to down payment, distinct closing/setup work and retained operating reserves. A separately excluded $2,000 onboarding invoice raises allocation to $249,000, leaving $1,000. A distinct $3,500 backup-response commitment needed before opening raises it to $252,500: a $2,500 gap. If either amount is already included in the $247,000, do not add it again. The annual fees above belong in the operating schedule, not automatically in this opening allocation.</p>
<p>No hypothetical time value or later booking receipt pays that earlier gap. Verify the quote and payment date, keep retained cash once and revise the plan before committing. For lower receipts, rebuild actual fee bases and fixed obligations rather than assuming all costs decline. Use the <a href="/tools/first-str-purchase-budget/">purchase cash worksheet</a> and <a href="/blog/str-cash-reserves-seasonality/">dated reserve schedule</a>.</p>
<h2>Do not buy a co-host label for a tax outcome</h2>
<p><a href="https://www.irs.gov/publications/p925">IRS Publication 925 (2025)</a> provides multiple material-participation tests. One uses more than 100 hours and participation at least equal to each other individual; another uses more than 500 hours. Investor-only monitoring generally does not count without direct day-to-day involvement. A seven-day-or-less average-use exception concerns activity classification, not automatic W-2 loss offsets.</p>
<p>Have an independent qualified adviser evaluate actual work, evidence, the applicable test and other loss limits. Neither a few monthly approval calls nor self-management guarantees qualification; paid support does not automatically defeat every test. Do not manufacture tasks or hours. Use a <a href="/blog/str-tax-benefit-shortfall-purchase/">smaller or absent tax-benefit purchase case</a> so the acquisition does not depend on an assumed refund.</p>
<h2>Control and exit must work for the actual account</h2>
<p><a href="https://www.airbnb.com/help/article/1431">Airbnb's account guidance</a> says account ownership cannot transfer to another host and information/bookings cannot move between accounts. A property purchase or service change does not automatically carry the seller's account, reservations or reviews. Verify each platform separately, and do not solve access with shared passwords or unnecessary guest personal data.</p>
<p>Read the actual agreement with counsel for notice, fees, open stays and permitted records handoff. Account permissions and contract termination are different actions. Use the <a href="/blog/str-management-agreement-termination/">exit-obligation guide</a> before treating a future switch as easy or cost-free.</p>
<h2>Choose a funded, workable operating plan before the offer</h2>
<p>Self-management can fit when the buyer can genuinely cover the tasks and local backups. Limited support can fit when its exclusions match work the buyer accepts. Broader management can fit when verified coverage and its complete cash burden suit the buyer's limits. These are fit conditions, not ranking claims or universal portfolio thresholds.</p>
<p>Proceed when written task ownership, lawful operating arrangements, realistic owner availability and accessible cash support the purchase. Reprice supported costs, seek valid contractual protection while decisive evidence is missing, or decline a deal requiring unavailable owner time or unfunded support. <a href="/apply/">Discuss the shortlist with your completed shift-coverage and cash worksheets</a>. The <a href="/blog/buy-str-high-income-large-tax-bill/">high-income investor roadmap</a> puts this decision alongside funding and diligence.</p>
<p class="small">Primary sources reviewed October 7, 2026. Airbnb help pages show no publication date; the IRS source is the currently published 2025 edition. Educational only, not tax, legal or personalized investment advice. AE Tax Advisors is an independent partner firm. All worked figures are hypothetical; no service performance, tax benefit, refund or return is promised.</p>'''
FAQ=[
('What is the difference between a co-host and a property manager?', 'Compare the actual tasks, permissions, decision rights, exclusions and fee base. Either label can cover different services; no fixed percentage, listing ownership or owner workload follows from the title.'),
('Can I self-manage an Airbnb from another state?', 'Only assess that plan against confirmed local coverage, backup response, actual owner availability, permitted access and its complete cost. Remote access alone does not establish a workable operating plan or a fixed monthly time requirement.'),
('Does co-hosting guarantee material participation for taxes?', 'No. Have an independent adviser evaluate actual work, records, the applicable participation test and other loss limits. A service label or occasional approvals do not establish qualification.')]
if __name__=='__main__':
 refresh('cohosting-vs-self-managing','Co-Hosting vs Self-Managing | BNB Accelerator','Co-Hosting vs Self-Managing Your Airbnb','Before buying an STR, compare co-hosting and self-management tasks, owner time, account control and cash. Use hypothetical cost and coverage worksheets.',BODY,FAQ,'2026-08-10','data-cohosting-review-link','Choose an <a href="/blog/cohosting-vs-self-managing/">operating work split with realistic owner time and funded backup coverage</a> before approving the purchase. Service labels do not establish tax eligibility.')
 from pathlib import Path
 path=Path(__file__).resolve().parents[1]/'blog/cohosting-vs-self-managing/index.html'
 text=path.read_text()
 if 'Updated October 7, 2026' not in text:
  text=text.replace('<span>Published August 10, 2026</span>', '<span>Published August 10, 2026</span><span>&middot;</span><span>Updated October 7, 2026</span>',1)
 path.write_text(text)
