"""Scoped existing queue-risk acquisition guide, not a new URL."""
from refresh_dscr_purchase_methods import refresh

BODY='''<p class="lead">An STR permit cap or waitlist should change an offer when rental permission is part of the purchase thesis. Separate eligibility to apply, acceptance onto a queue, invitation to complete registration and actual authority to operate. A position on a list is not the buyer's permission to host, and a seller's past income cannot fund a period when the buyer has no lawful STR operation. Price the supported use first; keep uncertain permit upside separate.</p>
<p><a href="/apply/">Bring the queue-evidence register and no-STR cash case to an acquisition call</a>. BNB Accelerator can coordinate acquisition work within its agreement; the issuing authority and independent counsel determine the actual rules and buyer rights.</p>
<h2>Identify which gate the property has actually cleared</h2>
<p>A town-wide cap, neighborhood density restriction and association rental limit may apply independently. Establish the jurisdiction, parcel and unit before using a map or market name. Ask whether a stated opening is available to this applicant and property type, rather than assuming a vacancy in the total count guarantees acceptance. Private restrictions and other approvals can still prevent the proposed use.</p>
<p>A geographically limited example is Truckee's <a href="https://townoftruckee.gov/359/Prohibited-from-Joining-the-Waitlist">waitlist eligibility page</a>, reviewed October 7, 2026. It describes a 365-day post-sale waiting period before a new owner may apply, excluded property types and potential denial for an active code case. These are Truckee descriptions, not national rules or a legal determination for a particular property.</p>
<p>The town's <a href="https://www.townoftruckee.gov/358/Registration-Count-Waitlist-Standings">count and standings page</a>, reviewed the same day, states its 1,255 cap has been reached. Its September 8, 2026 snapshot reports a 19.6-month wait trend; it also explains list omissions and standings that can change. Neither that historical trend nor an application's apparent rank promises issuance by a certain date. The <a href="https://www.townoftruckee.com/357/STR-Waitlist-Application-Registration-Pr">application process page</a> distinguishes waitlist steps from registration and renewal.</p>
<p>These examples demonstrate why the time before application and the time waiting for an opening are different. Do not simply add a town's historical trend to a purchase date and advertise the result as an opening forecast. Confirm the actual sequence, applicable exceptions and outstanding conditions with the authority. This guide does not authenticate a buyer's place or offer a current availability guarantee.</p>
<h2>Complete a queue-evidence register before the offer deadline</h2>
<div class="table-wrap"><table><thead><tr><th>Gate</th><th>Evidence to request</th><th>Purchase question</th></tr></thead><tbody>
<tr><td>Applicant and parcel eligibility</td><td>Current rule and property-specific written response</td><td>Can this buyer and actual unit apply, and when?</td></tr>
<tr><td>Cap or density availability</td><td>Dated authority count, geographic area and exclusions</td><td>Is an apparent opening accessible to this application?</td></tr>
<tr><td>Accepted queue status</td><td>Application identifier, acceptance and unresolved conditions</td><td>Is the application actually on the list, not merely submitted?</td></tr>
<tr><td>Ownership-change treatment</td><td>Seller record and response addressing proposed ownership/control</td><td>Does the position survive this transaction, or must the buyer restart?</td></tr>
<tr><td>Invitation and completion</td><td>Actual notice, response deadline, required work and payment</td><td>What remains before registration can be issued?</td></tr>
<tr><td>Operating permission</td><td>Issued record, conditions and other public/private approvals</td><td>What use, guest capacity and dates are actually supported?</td></tr>
</tbody></table></div>
<p>Record the source date, responsible reviewer, missing answer and contract decision date beside each row. Keep application identifiers and private seller records in authorized secure channels, not a public marketing worksheet. Ask counsel whether an unresolved answer can be addressed through valid transaction terms; this table creates no extension, cancellation or refund right.</p>
<p>The <a href="/blog/permits-that-do-not-transfer/">ownership-change guide</a> covers permission continuity across government and private restrictions. This register isolates queue access and uncertain issuance rather than replacing that broader review. The <a href="/blog/primary-residence-str-rule/">primary-residence guide</a> addresses another applicant eligibility question: an entity or nominal address cannot substitute for the buyer's actual facts.</p>
<h2>Do not turn queue rank into a purchase forecast</h2>
<p>A seller's statement that a property is number twelve needs a matching accepted application and current authority response. Ask whether that position is attached to the applicant, parcel or another defined right, and whether the sale changes it. A screenshot without its date and unresolved conditions is not a reliable issuance path.</p>
<p>Even verified historical releases are not a steady production rate. Rule changes, processing conditions, applicants ahead of the buyer and the response process can change timing. Do not calculate twelve divided by last month's releases and call it a permit date. Where the authority cannot promise an interval, preserve a longer-delay case and a no-permission case rather than assigning invented probabilities to them.</p>
<p>Keep a seller's hoped-for permit premium separate from the supported acquisition price. An appraisal, seller estimate or prior reservation calendar does not prove approval for this buyer. A lower price can improve economics but cannot make an excluded property eligible. Request an independently supported lawful-use valuation rather than subtracting a guessed number of rental months from an asking price.</p>
<h2>Worked cash test: how long can capital carry uncertainty?</h2>
<p>All figures are invented arithmetic, not Truckee costs, permit timing, lender terms, market demand or a client outcome. Assume $310,000 cleared buyer capital. Purchase, closing and essential setup consume $240,000; a separate protected $40,000 operating reserve brings initial allocation to $280,000. That leaves $30,000 unassigned. The reserve is included once and is not silently spent to make the delay look affordable.</p>
<p>For a no-STR-receipts case, stipulate $3,000 monthly carrying outflows plus $4,000 distinct application, review and compliance expenses. Six months adds $18,000 carrying plus $4,000 expenses, giving $302,000 total allocation and $8,000 unassigned. Twelve months replaces six months: $36,000 carrying plus $4,000 expenses gives $320,000, a $10,000 gap to available capital.</p>
<div class="table-wrap"><table><thead><tr><th>Hypothetical branch</th><th>Increment beyond $280,000</th><th>Total allocation</th><th>Margin to $310,000</th></tr></thead><tbody>
<tr><td>Six months, no STR receipts</td><td>$18,000 + $4,000</td><td>$302,000</td><td>$8,000</td></tr>
<tr><td>Twelve months, no STR receipts</td><td>$36,000 + $4,000</td><td>$320,000</td><td>-$10,000</td></tr>
<tr><td>Six-month lawful fallback sensitivity</td><td>$3,000 net outflow + $4,000</td><td>$287,000</td><td>$23,000</td></tr>
</tbody></table></div>
<p>The fallback sensitivity independently stipulates that an alternative rental is lawful, lender/insurance compliant and operationally possible, with $2,600 monthly cleared receipts arriving before bills, $900 distinct operating outflows and $2,200 other carrying outflows. Net monthly cash is negative $500; six months consumes $3,000. These inputs need their own evidence. A longer advertised minimum stay does not automatically legalize the use or establish those receipts.</p>
<p>The fallback replaces the no-receipts branch; do not add its $3,000 deficit to the other branch's $18,000 carrying total. Likewise, do not spend the protected reserve and still report it as retained. If fallback receipts start later, deposits are restricted or repairs require advance payment, the dated cash need changes. Use the <a href="/tools/first-str-purchase-budget/">purchase-budget worksheet</a> for the complete payment calendar. No projected STR income or expected tax refund funds these examples.</p>
<h2>Choose a supported offer, a protected delay or another property</h2>
<p>Proceed when the buyer's supported use, complete economics and independently funded downside fit, not merely because there is enough capital to wait. Reprice a still-viable purchase using verified alternative-use evidence. Delay only under available signed protection while a decisive record can arrive. Decline an STR thesis dependent on ineligible application rights, a promised queue date or unavailable cash.</p>
<p>If the buyer needs an operating STR within six months, an uncertain queue may conflict with that objective even when the property has lifestyle appeal. Compare a different property with independently established buyer permission; do not assume a currently operated seller property automatically supplies it. Keep lifestyle spending distinct from the investment model and discuss ownership, financing and legal consequences with qualified advisers.</p>
<p><a href="/apply/">Compare acquisition candidates with the completed eligibility register and no-permission downside</a>. Continue through the <a href="/blog/buy-str-high-income-large-tax-bill/">high-income buyer roadmap</a>. The useful service deliverable is a documented unresolved-condition memo and funded decision, not a promise to bypass a cap.</p>
<p class="small">Truckee primary pages reviewed October 7, 2026; quoted numerical status is a dated published snapshot, not a fresh individualized availability check. BNB Accelerator is the interested acquisition-service publisher. This is document-based education, not firsthand permit testing, legal advice, a valuation or personalized lending, tax or investment advice. All cash examples are hypothetical. No permit, opening date, income, refund, financing or investment result is guaranteed.</p>'''

FAQ=[
('Is an STR waitlist position permission to rent?', 'No. Separate eligibility, accepted queue status, invitation to complete registration and issued operating permission. Confirm the actual buyer and property requirements.'),
('Can I use a published wait trend as my opening date?', 'No. A dated aggregate trend and apparent rank do not promise issuance. Verify the application sequence, outstanding conditions and ownership-change treatment.'),
('Does a longer rental stay automatically provide a lawful fallback?', 'No. Confirm alternative-use permission, private restrictions, financing, insurance and supported demand separately before relying on fallback receipts.'),
('How should a permit waitlist change my offer budget?', 'Fund a no-STR-receipts interval and a no-permission decision separately from expected upside. Keep retained reserves distinct and price only independently supported uses.')]

if __name__=='__main__':
    refresh('str-density-cap-waitlist','STR Permit Caps and Waitlists: Before You Make an Offer','How Should an STR Permit Cap or Waitlist Affect an Offer?','Before buying an STR on a permit waitlist, verify queue eligibility and buyer rights. Use a no-STR cash worksheet before paying for uncertain permission.',BODY,FAQ,'2026-09-23','data-density-waitlist-review-link','Use the <a href="/blog/str-density-cap-waitlist/">permit queue evidence register and no-STR cash comparison</a> before paying for an uncertain opening date.')
