"""Scoped existing inspection owner; no homepage or library regeneration."""
import expand_hold_period as publisher
import re

SLUG='appliances-inspection-short-term-rental'
BODY='''<p class="lead">Before buying a furnished STR, an appliance inspection checklist should identify what was actually examined, what was excluded and which unanswered questions could change the purchase. A refrigerator running during a visit is not a promise of remaining life. An appliance absent from the report is not necessarily a passed appliance. Match the equipment inventory to the inspector's agreement and arrange qualified follow-up before the relevant transaction deadline.</p>
<p><a href="/apply/">Bring the appliance findings and unresolved-item register to a BNB Accelerator acquisition call</a>. We can integrate supported findings within our acquisition agreement; inspectors, qualified trades, lenders and counsel determine their respective conclusions.</p>
<h2>Agree the appliance scope before the site visit</h2>
<p>Send the identified kitchen and laundry inventory to the inspector and ask which units and functions are included. Record the agreed deliverable, access requirements, test conditions, reporting time and exclusions in writing. Ask who will review an item outside that scope. Do not assume the phrase home inspection includes every conveyed appliance or that a booked appointment produces a decision-ready report.</p>
<p>The <a href="https://www.nachi.org/sop.htm">InterNACHI residential Standards of Practice</a> provide one useful boundary example. They describe an accessible, non-invasive visual inspection based on conditions observed at the visit, not future prediction. They allow an agreed scope modification and exclude required determinations of lifespan and proposed-use suitability. Section 3.10 does not require inspection of appliances; section 3.6 also excludes required inspection of clothes washers and their connections.</p>
<p>Those are that organization's standards, last revised October 2022, not a nationwide rule that your inspector cannot inspect appliances. Establish the actual applicable standard, jurisdictional requirements and signed scope with the professional. Supplemental work may be available under a separate agreement. Do not describe a scope exclusion as evidence the equipment is defective, or silence in the report as proof of satisfactory condition.</p>
<p>Use the <a href="/blog/inspection-contingency-length-str/">diligence-window planning guide</a> for the wider evidence path and counsel-reviewed dates. Appliance follow-up must fit that path, but this page does not prescribe a standard contingency length or supply a contract clause.</p>
<h2>Record observations without inventing a diagnosis</h2>
<p>For each appliance, preserve its location, model and serial identifier, dated photograph and the report reference. Identify whether it was examined under the agreed scope, tested in a described way, not operated, inaccessible or referred for follow-up. Record the reason given for a limitation and the professional's exact conclusion. A unit with unavailable utilities is unresolved, not automatically broken or working.</p>
<p>Request safe access and necessary operating conditions through the seller, agent and qualified professional. Do not move a heavy appliance, reconnect gas, energize a shut-down circuit, bypass a control or perform an improvised test yourself. If the professional declines a procedure because it could be unsafe or damaging, preserve that limitation and arrange an appropriate alternative rather than forcing a demonstration.</p>
<p>Request available service and installation records and ask the qualified reviewer to distinguish observed symptoms from a supported cause, repair scope and recommendation. A seller's explanation of a noise or leak is background, not an independent finding. Do not assign a specific failure date from age or appearance. The relevant purchase question may be whether an identified corrective scope and funded alternative are acceptable, even when the exact remaining life cannot be established.</p>
<h2>Use an unresolved-item inspection register</h2>
<div class="table-wrap"><table><thead><tr><th>Item</th><th>Record to preserve</th><th>Decision before releasing protection</th></tr></thead><tbody>
<tr><td>Identity</td><td>Location, model/serial and agreed equipment inventory</td><td>Confirm the inspected unit is the unit expected to convey</td></tr>
<tr><td>Actual scope</td><td>Signed agreement, applicable standard and excluded functions</td><td>Assign separate review where a decisive question is outside scope</td></tr>
<tr><td>Observation</td><td>Dated test description and report reference</td><td>Do not turn limited operation into a lifetime or suitability guarantee</td></tr>
<tr><td>Limitation</td><td>Reason not inspected, not operated or inaccessible</td><td>Obtain valid access and qualified follow-up, or price a supported alternative</td></tr>
<tr><td>Material follow-up</td><td>Named reviewer, actual deliverable and unresolved safety/installation question</td><td>Resolve decisive issues before treating the equipment as opening-ready</td></tr>
<tr><td>Transaction consequence</td><td>Complete quote, delivery evidence, reviewer acceptance and counsel-reviewed deadline</td><td>Update purchase cash and required action, not just the repair list</td></tr>
</tbody></table></div>
<p>A hypothetical refrigerator entry could say normal operation observed under the agreed procedure; remaining life not determined. A dishwasher entry could say not operated because the required conditions were unavailable; follow-up outstanding. A laundry entry could cite a qualified service recommendation with a defined scope. These are examples of record structure, not diagnostic instructions or findings about a real property.</p>
<p>Keep a separate column for whether the actual decision is resolved. A completed visit, a received report, an accepted bid and completed corrective work are different milestones. Someone must own the unanswered item and the next review date. Treat a verbal seller promise as outstanding until the evidence required by the actual transaction process is obtained.</p>
<h2>Check safety notices and installation questions separately</h2>
<p>Use the identified equipment to check <a href="https://www.cpsc.gov/Recalls">CPSC recalls and product safety warnings</a> and any relevant manufacturer notice. Record matching identifiers, the search date and applicable instructions. CPSC cautions that remedy availability can change. No search match is not a safety certification; a remedy is not an immediate cash reimbursement or proof that work has been completed.</p>
<p>Ask the appropriate qualified professional about material installation, connection, ventilation, access or observed safety concerns within their actual scope. Refer code or approval questions to the qualified reviewer and controlling authority. A general inspection and a receipt do not independently establish every installation requirement. Do not operate equipment contrary to applicable stop-use instructions while negotiating its disposition.</p>
<p>For contract identity, substitutions, accepted seller treatment and final handoff, use the separate <a href="/blog/appliances-buying-short-term-rental/">appliance acquisition register</a>. For retained cash and future contributions, use the <a href="/blog/appliances-budget-short-term-rental/">five-year appliance budget</a>. Neither page replaces the physical reviewer.</p>
<h2>Worked findings-to-purchase comparison</h2>
<p>Invented arithmetic only, not an inspection result, quote, client outcome or loan approval. Assume $300,000 of accessible designated funds and a $288,000 acquisition allocation that already includes $1,500 of appliance corrective work and a separately retained property reserve. Initially $12,000 remains outside that allocation. No retained balance is treated as spent money.</p>
<p>Assume two separately priced qualified follow-up services cost $400 and $250, totaling $650, and were absent from the earlier budget. Their written findings lead to a $450 repair and a distinct $2,600 complete installed replacement. Stipulate that these scopes do not overlap and replace the original $1,500 work allowance: $3,050 minus $1,500 adds $1,550. With the $650 reviews, total incremental allocation is $2,200, making the plan $290,200 and leaving $9,800 outside it.</p>
<p>The review fees remain outflows even though subsequent work is needed; they are not another copy of the repair invoice. Conversely, do not add the full $3,050 on top of the unchanged $1,500 allowance. Revise the comparison if a real repair would eliminate part of the replacement scope. This example does not infer that an untested appliance always needs replacement.</p>
<p>Now stipulate that verified delivery timing creates $2,000 of distinct additional opening-delay bills, absent from the existing allocation. The plan becomes $292,200, leaving $7,800 outside it. If this buyer has a documented $8,000 separate commitment, the case is short by $200. That commitment is a hypothetical buyer constraint, not a universal reserve standard. The delay bills are incremental cash outflows, not gross lost bookings deducted again after reducing revenue.</p>
<p>A seller repair proposal cannot automatically erase the $2,200 adjustment or the delivery risk. Identify exactly which work changes owner, whether the review fees remain, what completion evidence is required and whether the relevant dates actually change. Counsel and the lender determine permissible treatment and contract consequences. Do not subtract an unspecified seller credit as unrestricted cash.</p>
<h2>Close the evidence loop before approving the purchase</h2>
<p>Proceed when decisive findings have a documented acceptable disposition, supported work and dates fit the opening plan, and revised cash fits the buyer's limits. Reprice a viable acquisition using confirmed scope. Seek valid transaction protection while a named decisive answer remains outstanding, or decline if the plan depends on an unsafe unit, unresolved use or inaccessible funding. A pending appointment or unanswered repair request does not itself extend a contract deadline.</p>
<p><a href="/apply/">Compare the shortlisted STR with its completed inspection register</a>. Connect these findings to the <a href="/blog/str-due-diligence-checklist/">full purchase diligence checklist</a> and <a href="/blog/buy-str-high-income-large-tax-bill/">high-income buyer roadmap</a>. Keep private seller and financing records in agreed secure channels; do not post credentials or unnecessary guest information in an equipment handoff.</p>
<p class="small">InterNACHI relevant scope, exclusions and sections 3.6/3.10, plus CPSC primary pages, reviewed October 7, 2026. Educational only, not inspection, safety certification, engineering, installation, legal, lending, tax or personalized investment advice. All examples are hypothetical. No remaining life, correction, warranty payment, opening date, financing, tax benefit or investment result is guaranteed.</p>'''
FAQ=[
('Does every home inspection include STR appliances?','No universal scope should be assumed. Confirm the actual standard, applicable requirements and signed agreement, including excluded units or functions and any separate appliance review.'),
('Does an untested appliance count as a passed appliance?','No. Record why it was not operated or examined, arrange appropriate qualified follow-up for a decisive question and keep the purchase decision unresolved until acceptable evidence is available.'),
('Does a working test predict appliance remaining life?','No. Preserve the actual procedure and observation without turning limited operation into a future-life, installation or proposed-use guarantee.'),
('How should inspection findings change the STR offer budget?','Replace earlier allowances with supported distinct corrective scopes, add separate review fees and incremental delay bills once, and confirm remaining cash and actual contract options.')]
if __name__=='__main__':
 source=(publisher.ROOT/'blog'/SLUG/'index.html').read_text();publisher.SLUG=SLUG
 publisher.TITLE=re.search(r'<title>(.*?)</title>',source)[1];publisher.H1=re.search(r'<h1>(.*?)</h1>',source)[1]
 publisher.DESC='Before buying an STR, check appliance inspection scope, untested items and qualified follow-up. Use a findings register to revise costs and purchase decisions.'
 publisher.BODY=BODY;publisher.FAQ=FAQ
 publisher.main(expected_publication='2026-09-22',hub_attribute='data-appliance-inspection-link',hub_paragraph='Resolve <a href="/blog/appliances-inspection-short-term-rental/">appliance scope exclusions and untested items</a> before treating a site visit as a completed purchase decision.')
 path=publisher.ROOT/'sitemap/index.html';s=path.read_text();s=re.sub(r'(<a href="/blog/'+SLUG+r'/">)[^<]+',lambda m:m[1]+publisher.H1,s);path.write_text(s)
