"""Scoped purchase-evidence refresh; does not generate the library or homepage."""
import json
import re
import expand_hold_period as publisher

SLUG = 'cost-seg-furnishings-allocation'
TITLE = 'STR Furnishings Allocation: Purchase Cost Worksheet'
H1 = 'How Should Furnishings Be Separated From a Cost Segregation Study?'
DESC = 'Reconcile STR furnishings allocation before buying: separate included assets, new spending and duplicate costs without treating estimates as tax basis.'
FAQ = [
 ('Does included furniture create extra cash for an STR purchase?', 'No. Included usable items may reduce actual replacement spending, but their estimated value is not another bank balance. Reconcile what transfers and the remaining funded setup scope.'),
 ('Can I use a room budget as the final furnishing tax basis?', 'Do not treat a planning estimate as established basis. Give the CPA source invoices, purchase allocations, closing records and bundled-cost questions for the actual transaction.'),
 ('How do I avoid counting an appliance twice?', 'Match the same physical item to its source record and location. Check whether a contractor draw and furnishing spreadsheet refer to the same cost before adding them together; document the resolution.'),
 ('Does every furnished STR purchase require Form 8594?', 'No universal requirement applies to every property closing. The IRS describes conditions for certain business-asset sales; have your CPA decide whether the actual purchase falls within them.')
]
BODY = '''<p class="lead">Before buying a furnished STR, reconcile the assets in the purchase package with the items you will buy afterward. The cost-segregation file and the cash-through-launch budget need consistent source records, but they answer different questions. One supports your advisers' tax analysis; the other tells you whether the purchase and remaining setup are actually funded. A large tax bill does not turn an estimated furnishing value into closing money or established tax basis.</p>
<p><a href="/apply/">Bring the purchase package and unresolved cost register to an STR acquisition call</a>. BNB Accelerator assists within its contracted acquisition scope; your CPA, study provider, lender and transaction professionals determine their respective conclusions.</p>
<h2 id="allocation-records">Build one source register for STR furnishings allocation</h2>
<p>Start with the signed purchase documents, item schedule, closing statement, invoices and contractor scopes. Identify each physical asset, its location, who owns it, whether it is included, and the document supporting its cost or proposed allocation. Use a stable reference number so a refrigerator in a contractor draw is not entered again as a separate furnishing purchase merely because it appears in two spreadsheets.</p>
<div class="table-wrap"><table><thead><tr><th>Cost group</th><th>Evidence to reconcile</th><th>Question before committing</th></tr></thead><tbody>
<tr><td>Included seller assets</td><td>Accepted inventory, ownership/condition evidence and adviser-reviewed purchase allocation</td><td>Which usable items truly reduce the remaining shopping scope?</td></tr>
<tr><td>New buyer purchases</td><td>Itemized invoices or clearly labeled quotes, delivery terms and asset locations</td><td>What must be paid, when, and from which available funds?</td></tr>
<tr><td>Bundled contractor work</td><td>Draw, invoice, scope and component detail where available</td><td>Is an appliance already inside another paid or quoted amount?</td></tr>
<tr><td>Closing and finance charges</td><td>Actual settlement and loan records, separated for CPA review</td><td>Which costs are acquisition-related, loan-related or another category?</td></tr>
<tr><td>Unresolved items</td><td>Missing record, responsible reviewer and actual protected decision date</td><td>Does the gap change funding, accepted terms or the ability to open?</td></tr>
</tbody></table></div>
<p>Keep quotes, estimates and paid amounts in separate columns. Record credits, returns and cancellations so a superseded invoice does not remain in the total. Mark personal or excluded property rather than silently mixing it with rental assets. Share receipts and tax records through agreed secure channels, with irrelevant personal and guest information removed.</p>
<p>The <a href="/blog/str-furniture-bill-of-sale/">furniture transfer and acceptance guide</a> addresses what actually conveys and its condition. This register follows the money and source records; it does not replace those delivery checks. The <a href="/blog/appraisal-gap-furnished-str/">furnished appraisal-gap worksheet</a> separately tests the lender's accepted collateral value and revised cash requirement.</p>
<h2 id="basis-review">Ask for basis review, not unsupported percentages</h2>
<p><a href="https://www.irs.gov/publications/p551">IRS Publication 551</a> explains allocating a lump-sum purchase among acquired assets and separating land and building basis. It also distinguishes property-acquisition costs from loan costs and excludes amounts escrowed for future taxes and insurance from settlement costs. Have the CPA apply the relevant rules to the actual records. Neither a room budget nor the amount borrowed establishes each asset's basis.</p>
<p>The IRS <a href="https://www.irs.gov/forms-pubs/about-form-8594">Form 8594 overview</a> describes reporting by both parties for certain business-asset sales when goodwill or going-concern value attaches or could attach and the buyer's basis is determined only by the amount paid. Have your CPA determine whether those conditions apply before accepting a proposed allocation. This is not a filing rule for every furnished-property closing.</p>
<p>Ask the study provider and CPA to agree on the reconciliation scope, missing evidence, treatment of bundled amounts and final reviewed schedule. Keep purchase-date records, placed-in-service evidence, photos, asset locations and relevant prior schedules available; the seller's depreciation schedule is not automatically your own basis. Do not choose recovery periods or percentages simply to reach a desired deduction. The <a href="/blog/buy-str-entity-or-assets/">entity-versus-assets comparison</a> addresses the separate question of which transaction you are buying.</p>
<h2 id="cost-reconciliation">Worked reconciliation: remove a duplicate without inventing cash</h2>
<p>Original hypothetical planning arithmetic, not a tax-basis calculation, current quote, valuation or client outcome. Assume an $800,000 furnished purchase package, $17,000 of distinct cash-paid closing/finance charges, $26,000 of contractor work and a $14,000 new-furnishings list. The raw project-cost register totals $857,000 before reserves. No classification of the $17,000 charges is assumed.</p>
<p>Suppose the same $3,000 refrigerator appears within the $26,000 contractor scope and as a separate line in the $14,000 list. Confirm through the actual scope and supplier record that this is one item and one payment, not two refrigerators or an unpaid addition. Remove that duplicate from the furnishing list, leaving $11,000. The reconciled raw project total is $854,000: $800,000 + $17,000 + $26,000 + $11,000. This is not a conclusion that all $854,000 is depreciable basis.</p>
<p>The seller also describes included furnishings as worth $20,000. They are already within the assumed $800,000 package. Do not add $20,000 again to total purchase cost, subtract it again from the reconciled setup bill, or treat it as bank cash. Supported allocation and usable replacement savings require their own evidence; a seller estimate supplies neither automatically.</p>
<h2 id="funded-launch">Use the reconciled scope to test available acquisition cash</h2>
<p>For a separate cash test, assume the lender actually funds $600,000 of the $800,000 price and all other example amounts are buyer cash outflows. Buyer price cash is $200,000, not $800,000. With $300,000 designated accessible funds and a separately retained $35,000 reserve, the unreconciled plan needs $292,000: $200,000 + $17,000 + $26,000 + $14,000 + $35,000. It leaves $8,000 outside the plan.</p>
<p>After verifying the duplicate, the requirement is $289,000 and the unallocated amount is $11,000. The $3,000 difference corrects the planning total; it is not a tax refund or reimbursement. Now suppose an actual missing-item quote adds $9,000 of separate required setup not included above. Required capital becomes $298,000, leaving $2,000. A further $4,000 of distinct net carrying outflows during a documented delay raises it to $302,000, a $2,000 funding gap if the $35,000 reserve is preserved.</p>
<p>These invented costs and delay are sensitivities, not market prices or promised timelines. Replace them with actual terms, avoid double-counting existing setup or carrying costs, and confirm payment dates. Do not let a lower reconciled total conceal unknown ownership, permission or lending questions. Use the <a href="/tools/first-str-purchase-budget/">all-in purchase budget</a> for the complete funding picture; an estimated tax receipt is not assumed here.</p>
<h2>Resolve the evidence before relying on the purchase case</h2>
<p>Proceed when the agreed transfer, remaining setup scope and available cash are supported and advisers have a workable record-review plan. Reprice a still-viable purchase when verified missing items change the funded scope. Delay only under actual valid protection while decisive records or funding remain unresolved. Decline a purchase dependent on invented allocations, unavailable cash or a deduction promise.</p>
<p><a href="/apply/">Discuss the shortlist with a reconciled asset-and-cash register</a>: included items, remaining purchases, duplicates resolved, missing evidence, dated outflows and responsible reviewers. Follow the <a href="/blog/buy-str-high-income-large-tax-bill/">high-income buyer roadmap</a> for the other acquisition gates. This worksheet does not prepare a study, approve an allocation or establish the buyer's usable tax benefit.</p>
<p class="small">IRS sources reviewed October 7, 2026; Publication 551 is the currently published December 2025 edition, not a newly issued 2026 edition. Educational information, not tax, legal, lending or personalized investment advice. All figures are hypothetical. Qualified professionals determine treatment from actual records. No deduction, refund, financing, transfer or investment result is guaranteed.</p>'''

if __name__ == '__main__':
    publisher.SLUG, publisher.TITLE, publisher.H1 = SLUG, TITLE, H1
    publisher.DESC, publisher.BODY, publisher.FAQ = DESC, BODY, FAQ
    publisher.main('2026-09-23', 'data-furnishings-allocation-review-link', 'Before relying on a furnishing estimate, use the <a href="/blog/cost-seg-furnishings-allocation/">purchase-cost reconciliation register and independently funded setup test</a>. Included assets, new spending and tax basis are not interchangeable.')
    p = publisher.ROOT / 'blog' / SLUG / 'index.html'
    s = p.read_text()
    assert 'FAQPage' not in s
    schema = {'@context':'https://schema.org', '@type':'FAQPage', 'mainEntity':[{'@type':'Question','name':q,'acceptedAnswer':{'@type':'Answer','text':a}} for q,a in FAQ]}
    s = s.replace('</head>', '<script type="application/ld+json">'+json.dumps(schema, indent=2)+'</script>\n</head>', 1)
    assert s.count('<span>Updated October 6, 2026</span>') == 1
    s = s.replace('<span>Updated October 6, 2026</span>', '<span>Updated October 7, 2026</span>')
    p.write_text(s)
