"""Scoped expansion of the canonical acquisition-versus-operator comparison."""
import json,re
from pathlib import Path
R=Path(__file__).resolve().parents[1]
p=R/'compare/bnb-accelerator-vs-property-manager/index.html';t=p.read_text()
marker='<section class="section-sm"><div class="wrap wrap-narrow"><h2>Read the scope before choosing</h2>'
assert marker in t and 'Original operator-acceptance work sample' not in t
addition='''<section class="section-sm"><div class="wrap wrap-narrow"><h2>Buyer fit: purchase support and operating support are different purchases</h2>
<p>A manager-led operating plan may be sufficient when you already have a supported candidate, a qualified transaction team and the ability to coordinate the remaining purchase work. Acquisition support may fit when sourcing, underwriting and transaction handoffs remain unassigned. You may need both, but a second agreement should close a documented gap rather than duplicate a deliverable.</p>
<p>BNB's <a href="/how-it-works/">published process and scope</a> describe purchase coordination and manager/vendor pairings, with daily operation assigned to the buyer's operator. Your signed engagement determines what is actually included. For a named agent-led alternative, <a href="https://theshorttermshop.com/" target="_blank" rel="noopener">The Short Term Shop</a> describes local agents helping investors buy and sell, with education. That is not a promise of management or launch execution; see its <a href="/compare/alternatives-to-the-short-term-shop/">buyer-fit alternatives</a>.</p>
<p>For operating help, <a href="https://www.airbnb.com/help/article/1534" target="_blank" rel="noopener">Airbnb's co-host guidance</a> describes different service and permission arrangements. Co-host support is an operating option, not a substitute for purchase diligence or a local brokerage engagement. Compare <a href="/blog/cohosting-vs-self-managing/">co-hosting with self-management</a> against your actual responsibilities. No option here is ranked or claimed to deliver the same scope.</p>
</div></section>
<section class="section-sm bg-alt"><div class="wrap"><h2>Original operator-acceptance work sample</h2>
<p>Before committing to a candidate, give the proposed manager and acquisition team this same-address request. Fill in the legal provider, evidence, deadline, price and buyer decision for each row. This is an original buyer template, not either provider's contracted scope or a guarantee that a manager will accept the property.</p>
<div class="bc-table-scroll" role="region" aria-label="Operator acceptance before purchase" tabindex="0"><table><thead><tr><th scope="col">Gate</th><th scope="col">Evidence to request</th><th scope="col">Buyer decision retained</th></tr></thead><tbody>
<tr><th scope="row">Address and launch capacity</th><td>Written acceptance of this address, planned start, excluded tasks and prerequisites; named acquisition-side handoff owner</td><td>Whether a supported operating plan exists before the applicable purchase deadline</td></tr>
<tr><th scope="row">Revenue and costs</th><td>Comparable rationale and expense assumptions; complete operator quote with fee base, minimums, setup, held funds and pass-through charges</td><td>Whether the offer ceiling still works after inserting the actual quote</td></tr>
<tr><th scope="row">Spending authority</th><td>Repair approval threshold, emergency exception, receipt/reporting duties and who can commit to vendors</td><td>Which authority is delegated, which approvals stay with you and what additional cash is required</td></tr>
<tr><th scope="row">Accounts and guest responsibility</th><td>Listing/account ownership, permission level, payout access, guest-response owner and escalation path</td><td>Whether those permissions match the written duties and preserve necessary visibility</td></tr>
<tr><th scope="row">Payment and exit</th><td>When each acquisition or management charge is earned/due, cancellation terms, held-fund release conditions and remaining guest duties</td><td>Whether to accept the obligations if the purchase or launch does not proceed</td></tr>
</tbody></table></div>
<p>Example: an operator can accept the address but cannot start until a safety repair and access setup are complete. A referral alone has not satisfied that gate. Ask who obtains the quotes, approves the repair and confirms readiness; revise the opening date and funding model. An operator's favorable revenue estimate also does not establish legal STR permission or satisfy lender conditions.</p>
<p>Airbnb explains that co-host permissions govern listing access, not the service expectations you must agree separately. Full access can include reservations and pricing; listing-owner payout methods and taxpayer information are not editable by the co-host. Do not confuse platform permissions with contract authority or assume a management contract transfers a seller's account. For a seller's incumbent operator, use the <a href="/blog/keep-str-manager-after-buying-property/">retain-or-replace decision guide</a>; for a named provider's transition, use the <a href="/guides/bnb-turnkey-management-handoff/">handoff acceptance guide</a>.</p>
</div></section>
<section class="section-sm"><div class="wrap wrap-narrow"><h2>Original acquisition-to-operation cash comparison</h2>
<p><strong>Hypothetical only—not BNB or manager prices, a forecast or a client result:</strong> a buyer has $340,000 available. The same property allocates $195,000 to down payment, $15,000 to ordinary closing costs including the assumed brokerage obligation, $25,000 to furnishings, $10,000 to repairs and $30,000 to protected operating reserves: $275,000. Separately listed acquisition, onboarding and held-fund amounts below are excluded from those common costs.</p>
<p>In a buyer-coordinated purchase, assume $14,000 of uncovered acquisition/launch work, $4,000 manager onboarding and $6,000 held by the operator. Total allocated cash is $299,000, leaving $41,000 unallocated. With separate acquisition support, assume a $24,000 acquisition fee, the same $4,000 onboarding and $6,000 held funds, plus $5,000 uncovered work: $314,000, leaving $26,000. These paths use different hypothetical work assumptions; verify each actual quote. The $15,000 difference does not establish equal scope, time saved or better performance.</p>
<p>The held $6,000 is allocated cash, not automatically a consumed expense or a guaranteed refund. Do not also count it inside the protected reserve. A $10,000 launch delay cost changes the paths to $309,000 and $324,000, leaving $31,000 and $16,000. A further $20,000 required repair leaves $11,000 on the buyer-coordinated path and creates a $4,000 shortfall with acquisition support, without spending the protected reserve. The original $10,000 repair allowance remains in both totals; the additional repair is distinct.</p>
<p>Recurring management fees belong in the operating expense model and reserve forecast. Charge them again in the acquisition bridge only when a separate pre-opening payment actually requires cash and has not already been allocated. Reconcile fee bases, minimums, timing and invoices using the <a href="/blog/str-property-management-fees/">management-fee purchase worksheet</a>. Neither a prospective tax benefit nor an uncleared refund fills a current funding gap.</p>
<p>Choose the operating-only engagement when purchase work is already covered and the quote fits the downside model. Consider acquisition plus management when the added outputs address specific gaps and total cash remains sufficient. Renegotiate overlapping scope or unclear earning triggers; pause or reject the candidate when permissions, financing, operator readiness or cash cannot be supported. Do not buy an unsuitable property merely to justify fees already paid.</p>
</div></section>
'''
t=t.replace(marker,addition+marker)
t=t.replace('Updated October 1, 2026.','Source review and meaningful update: October 7, 2026. Originally published August 11, 2026. This is document-based analysis, not firsthand provider testing or an independent rating. BNB is the interested acquisition-service publisher; no private engagement or management agreement was authenticated. Published sources describe roles and platform permissions, not guaranteed contracted scope or results. Educational information only—not legal, tax, lending or personalized investment advice. Use independent qualified professionals and secure channels for sensitive documents; do not share account passwords.')
desc='Compare BNB acquisition support with an STR property manager using operator acceptance, fee triggers, decision rights and a worked purchase cash bridge.'
t=re.sub(r'(<meta (?:name="(?:description|twitter:description)"|property="og:description") content=")[^"]*(")',lambda m:m[1]+desc+m[2],t)
def schema(m):
 d=json.loads(m[1])
 for n in d.get('@graph',[d]):
  if n.get('@type')=='Article':n.update(dateModified='2026-10-07',description=desc)
 return '<script type="application/ld+json">\n'+json.dumps(d,indent=2)+'\n</script>'
t=re.sub(r'<script[^>]*type="application/ld\+json"[^>]*>(.*?)</script>',schema,t,flags=re.S)
p.write_text(t)
s=R/'sitemap-core.xml';v=s.read_text();v,n=re.subn(r'(<loc>https://www.bnbaccelerator.com/compare/bnb-accelerator-vs-property-manager/</loc>\s*<lastmod>)[^<]+',r'\g<1>2026-10-07',v);assert n==1;s.write_text(v)
print('Expanded existing manager comparison; no new blog intent, FAQ or homepage change.')
