"""Single existing umbrella acquisition-note expansion; no library/homepage generation."""
import json,re
import expand_hold_period as publisher
SLUG='commercial-umbrella-str'
TITLE='When Does an STR Owner Need an Umbrella Policy | BNB Accelerator'
H1='When Does an STR Owner Need an Umbrella Policy?'
DESC='Before buying an STR, review the actual liability stack, named insureds, underlying limits and exclusions; use an attachment-gap and funded-cost worksheet.'
FAQ=[
 ('Does a personal umbrella automatically cover an LLC-owned STR?','No. Have a licensed adviser review the actual insured parties, rental operations, underlying policies and umbrella terms. Personal coverage and commercial coverage are not interchangeable labels.'),
 ('Does a larger umbrella limit cure every primary exclusion?','No. Some umbrella forms may address particular gaps, but the actual contract governs. Ask the adviser to identify any claimed broader coverage and its conditions rather than assuming every excluded activity is protected.'),
 ('Is an attachment-gap example a predicted claim payment?','No. It is an invented arithmetic exercise under explicit assumptions. Actual insured liability, exhaustion, defense costs, retentions and policy wording determine any real payment.'),
 ('Should umbrella cost be counted twice in an STR cash budget?','No. Separate incremental annual cost from the amounts actually due before closing and a retained cash reserve. Count each dated payment once; a liability limit is not accessible purchase money.')
]
BODY='''<p class="lead">Before purchasing an STR, review whether additional liability insurance fits the property, owner and operation—not just how many millions appear on a proposal. For a high-income buyer, substantial assets can make this review important, but neither net worth nor an LLC tells you what a policy covers. Ask a licensed insurance professional to map the primary and excess layers before the relevant acquisition deadlines. This guide expands the existing umbrella question; it does not recommend a universal limit or declare a particular claim insured.</p>
<p><a href="/apply/">Bring the adviser-reviewed liability stack to a BNB Accelerator acquisition call</a>. The acquisition team can integrate confirmed costs and outstanding conditions within its agreement; it does not sell insurance or interpret your coverage.</p>
<h2>Personal, commercial and excess labels are not a coverage map</h2>
<p>The <a href="https://content.naic.org/article/whats-umbrella-policy">NAIC's December 15, 2022 umbrella explanation</a> describes personal liability and defense protection that may extend beyond primary insurance. It also distinguishes liability from damage to the owner's own property. That general guidance does not establish coverage for an LLC-owned nightly rental or a particular business activity. A larger liability limit is not a furnishing-replacement fund or an income-interruption policy.</p>
<p><a href="https://www.travelers.com/umbrella-insurance">Travelers' personal umbrella overview</a> identifies business-related limitations and directs readers to appropriate business insurance. This is an insurer's current general explanation, not a determination that every personal policy excludes every rental. Give the adviser the actual ownership, guest use, amenities and management arrangement; request a documented answer for those facts rather than assuming your household umbrella follows your new property.</p>
<p><a href="https://www.travelers.com/business-insurance/commercial-umbrella">Travelers' commercial umbrella and excess overview</a> describes additional liability layers, underlying-limit requirements and possible broader protection for certain losses. It expressly says its materials do not establish coverage for a particular claim. Product forms and availability vary. Do not assume all umbrella policies follow the primary wording exactly, or that a commercial label fixes every exclusion.</p>
<h2>Build an adviser-reviewed stack before comparing limits</h2>
<p>Request the proposed declarations, actual forms, endorsements and schedules for every relevant layer. Identify which documents are indications and which remain subject to underwriting. Give the adviser the purchase entity, intended insured parties, property address, booking channels, guest capacity, amenities, management and actual contractor or vehicle arrangements. Disclose changes and ask whether they need additional review before binding or opening.</p>
<div class="table-wrap"><table><thead><tr><th>Stack question</th><th>Evidence to request</th><th>Purchase consequence</th></tr></thead><tbody>
<tr><td>Who is insured?</td><td>Actual named-insured and other insured-party provisions across layers</td><td>Do not equate title ownership, management authority and insured status</td></tr>
<tr><td>Which operations are addressed?</td><td>Rental-use, location, activity and exclusion review with referenced wording</td><td>A nominal limit does not resolve an unanswered guest-use condition</td></tr>
<tr><td>Where does the next layer start?</td><td>Required underlying limits, attachment, retention and exhaustion terms</td><td>Resolve any mismatch before treating layers as continuous</td></tr>
<tr><td>What happens to limits during claims?</td><td>Per-occurrence/aggregate, defense-cost and other applicable provisions</td><td>Do not add advertised limits without reviewing how they operate</td></tr>
<tr><td>When can coverage be effective?</td><td>Carrier conditions, payment dates and evidence acceptable to lender</td><td>Compare with closing, possession and first-guest dates</td></tr>
</tbody></table></div>
<p>Ask who must respond to each open item, the actual deadline and the document provision supporting the answer. A certificate, broker summary or seller's policy is not the entire issued contract. Use the <a href="/blog/str-insurance-quote-before-purchase-offer/">pre-offer quote register</a> for premium and binding workflow; this page focuses on how the liability layers fit, not a second generic insurance checklist.</p>
<p>Have the adviser explain the treatment of a realistic alleged guest injury at the actual amenity, a claim involving the manager or contractor, and any activity the owner plans to add. Counsel evaluates legal responsibility and contract allocation separately. These are review scenarios, not predictions of coverage, litigation, liability or claim frequency. Do not assume a manager's policy protects the buyer merely because the manager supplies a certificate.</p>
<h2>Original attachment-gap exercise: stated assumptions matter</h2>
<p>Invented arithmetic only, not a policy interpretation, settlement forecast or recommended limit. Assume solely for this exercise that a $1.4 million covered liability amount is payable, a primary layer pays up to $500,000, and an otherwise applicable excess layer starts at $1 million with enough remaining limit. Assume no separate defense costs, retention, aggregate erosion or other adjustments. No real policy or claim is established by these assumptions.</p>
<div class="table-wrap"><table><thead><tr><th>Illustrative layer</th><th>Amount under these assumptions</th></tr></thead><tbody>
<tr><td>Primary through $500,000</td><td>$500,000</td></tr>
<tr><td>Interval from $500,000 to $1 million</td><td>$500,000 unresolved owner-funded interval</td></tr>
<tr><td>Assumed applicable excess above $1 million</td><td>$400,000</td></tr>
<tr><td>Reconciliation</td><td>$500,000 + $500,000 + $400,000 = $1.4 million</td></tr>
</tbody></table></div>
<p>The example does not promise that an excess carrier pays $400,000 while underlying insurance is deficient. Ask how the actual maintenance-of-underlying-insurance and exhaustion provisions affect the answer. Increasing the advertised excess limit alone does not change this exercise's assumed attachment point. A different properly reviewed primary/attachment structure may produce a different result; obtain the actual answer rather than borrowing the example as coverage advice.</p>
<h2>Keep liability limits separate from purchase liquidity</h2>
<p>Another invented funding exercise: suppose $250,000 is available for the acquisition, and distinct down-payment/closing, setup and retained-reserve allocations total $246,000. The initial flexibility is $4,000. If the accepted insurance stack adds a hypothetical $1,200 annual cost, operating margin falls by $1,200 before other effects. That annual change is not automatically the cash due at settlement.</p>
<p>Assume the $246,000 already includes all previously budgeted insurance payments. If a separately confirmed $1,200 incremental payment is due before closing, the revised allocation is $247,200, leaving $2,800. If another distinct $3,000 of required safety work is also due then, the allocation becomes $250,200: a $200 gap. Do not add the same $1,200 again as both an upfront payment and another reserve requirement. These are not typical premiums, repair prices or a recommended reserve.</p>
<p>A potential $500,000 liability interval is not an instruction to pretend $500,000 is funded because $2,800 remains. It signals a separate risk decision with the adviser and counsel. Nor does a liability limit provide cash for earnest money, repairs or operating bills. High income, projected tax benefits or expected claim receipts do not resolve a current shortfall.</p>
<h2>Make the accepted stack part of the proceed decision</h2>
<p>Proceed only when actual use and insured parties have been reviewed, the buyer accepts the supported terms and residual risks, relevant lender conditions are resolved, and dated payments fit available cash. Reprice or consider another property when confirmed costs change the buy box. Delay under valid contract protection while decisive documents are missing. Counsel determines actual extension, renegotiation or termination rights; this page does not supply a universal insurance contingency.</p>
<p>Document who must update the coverage review if ownership, amenities, operations or primary policies change after purchase. Keep private policy, asset and financial documents in agreed secure channels, not in a public comment or application narrative. An entity may affect legal exposure but is not a promise of protection and does not pay claims. Continue with the <a href="/blog/airbnb-insurance-guide/">general insurance distinctions</a> and <a href="/blog/str-condo-master-policy-insurance-gap/">condo master-policy boundary</a> where relevant.</p>
<p><a href="/apply/">Compare the purchase plan and adviser-confirmed liability conditions</a>, then return to the <a href="/blog/buy-str-high-income-large-tax-bill/">high-income buyer roadmap</a>. BNB Accelerator assists within its acquisition agreement; independent licensed insurance professionals and counsel establish their own conclusions.</p>
<p class="small">NAIC and Travelers primary materials reviewed October 7, 2026. NAIC personal-umbrella article dated December 15, 2022; insurer product descriptions are not issued policy forms or proof of STR availability. Educational only, not insurance, claims, legal, lending, tax or personalized investment advice. All numbers are invented. No coverage, defense, payment, approval, refund or investment result is guaranteed.</p>'''
if __name__=='__main__':
 si=publisher.ROOT/'sitemap/index.html';old=si.read_text();label=re.search(r'(<a href="/blog/'+SLUG+r'/">)[^<]+',old)[0]
 publisher.SLUG,publisher.TITLE,publisher.H1=SLUG,TITLE,H1
 publisher.DESC,publisher.BODY,publisher.FAQ=DESC,BODY,FAQ
 publisher.main('2026-09-23','data-commercial-umbrella-review-link','Before adding advertised liability limits, review the <a href="/blog/commercial-umbrella-str/">umbrella attachment and insured-party register</a>. Actual policy layers and dated purchase cash are separate decisions.')
 si.write_text(re.sub(r'(<a href="/blog/'+SLUG+r'/">)[^<]+',lambda m:label,si.read_text()))
 p=publisher.ROOT/'blog'/SLUG/'index.html';s=p.read_text();assert 'FAQPage' not in s
 node={'@context':'https://schema.org','@type':'FAQPage','mainEntity':[{'@type':'Question','name':q,'acceptedAnswer':{'@type':'Answer','text':a}} for q,a in FAQ]}
 s=s.replace('</head>','<script type="application/ld+json">'+json.dumps(node,indent=2)+'</script>\n</head>',1)
 s=s.replace('<span>Updated October 6, 2026</span>','<span>Updated October 7, 2026</span>',1).replace('property="og:type" content="website"','property="og:type" content="article"',1)
 p.write_text(s)
