from refresh_dscr_purchase_methods import refresh

BODY = '''<p>A done-for-you Airbnb acquisition service can coordinate parts of finding, evaluating, buying and preparing a short-term rental. The label does not establish which tasks are included, who performs them, what they cost or whether the property is suitable. For a buyer preparing to invest within six months, the useful question is: which purchase responsibilities will someone deliver, and which decisions and bills remain mine?</p>
<p><strong>Commercial-interest and evidence disclosure:</strong> BNB Accelerator publishes this guide and sells acquisition assistance. This is document-based analysis, not firsthand testing or a review of an individual client contract. Source review: October 7, 2026. Examples below are invented decision exercises, not market averages, provider quotes, client outcomes or promised savings. This is not individualized legal, tax, lending or investment advice.</p>
<h2>Define the delegated work before comparing prices</h2>
<p>BNB's <a href="/how-it-works/">published acquisition process</a> describes market selection, sourcing and underwriting, diligence and closing coordination, setup/vendor pairing and management placement. It also separates buyer decisions from independent lender, legal, tax and operating responsibilities. That public description is a starting point; obtain the specific signed scope, exclusions and outside costs for your proposal. An introduction is not the same deliverable as completed professional work.</p>
<p>For brokerage relationships, <a href="https://www.nar.realtor/the-facts/written-buyer-agreements-101" target="_blank" rel="noopener">NAR's written-buyer-agreement guidance</a> discusses clear services, compensation, term and termination, and appropriate outside professionals. It does not prescribe a universal service package or compensation amount. Its MLS-participant guidance is not a certification of every acquisition consultant's contract. Have the applicable agreements reviewed for your transaction and jurisdiction.</p>
<p>Use this nine-workstream acceptance sheet to request evidence. These are possible acquisition needs, not a claim that every company supplies all nine:</p>
<table><thead><tr><th>Workstream</th><th>Output to request</th><th>Retained decision or outside role</th></tr></thead><tbody>
<tr><td>Market selection</td><td>Shortlist with permission, insurance, seasonality and exit assumptions</td><td>Buyer approves target and risk limits; authorities determine permissions</td></tr>
<tr><td>Property sourcing</td><td>Candidate log with criteria, exclusions and rejection reasons</td><td>Buyer approves a candidate; define any search term or replacement limit</td></tr>
<tr><td>Underwriting</td><td>Comparable evidence, full-cost model and downside case</td><td>Buyer decides; lender qualification is a separate analysis</td></tr>
<tr><td>Offer coordination</td><td>Written price, contingencies, deadlines and negotiation authority</td><td>Buyer authorizes terms; licensed representation must be identified</td></tr>
<tr><td>Diligence</td><td>Inspection, insurance, HOA and permission evidence with unresolved items</td><td>Independent specialists evaluate their scope; buyer accepts or rejects risk</td></tr>
<tr><td>Financing and closing</td><td>Dated lender/title handoff and funding checklist</td><td>Lender approves credit; title/closing professionals handle their work</td></tr>
<tr><td>Setup</td><td>Inventory, specifications, quotes, installation acceptance and exceptions</td><td>Buyer approves spend and change orders; separate goods from coordination fees</td></tr>
<tr><td>Rental readiness</td><td>Access, photos, account permissions and launch acceptance checklist</td><td>Confirm who owns accounts and who can authorize publication or pricing</td></tr>
<tr><td>Operating handoff</td><td>Named manager, coverage schedule, agreement and unresolved-work list</td><td>Owner retains oversight; manager performs its contracted operations</td></tr>
</tbody></table>
<p>Add a named accountable person, due date and acceptance evidence to each row. Mark an omitted task as “buyer must arrange,” not zero cost. If a proposal covers only selected steps, compare it with a local broker, analysis support or setup specialist for those steps. A narrower service can be useful without being an end-to-end package.</p>
<h2>Turn the fee into a payment-trigger register</h2>
<p>Do not assume a flat fee, percentage or revenue share is automatically more aligned. Each can have incentives and exclusions. Ask for the amount or calculation, invoice recipient, payment trigger and supporting deliverable. For a percentage, specify the base and whether price changes alter the fee. For recurring charges, specify duration, revenue definition, minimums, owner-use treatment and termination obligations.</p>
<ol><li><strong>At engagement:</strong> What starts the search? Is any retainer credited later, refundable under stated conditions, or earned immediately? Which agreement supplies the answer?</li>
<li><strong>At an offer or closing:</strong> Does payment follow an accepted offer, a completed acquisition or another event? What happens if inspection fails, financing is denied or the buyer rejects a candidate?</li>
<li><strong>At setup or handoff:</strong> Is payment tied to ordering goods, installation, a documented acceptance test or elapsed time? Who approves substitutions and incomplete work?</li>
<li><strong>After stopping:</strong> Which commissions, carryover provisions, vendor commitments, subscriptions or operating fees remain? Do not assume cancellation erases obligations.</li></ol>
<p>List brokerage compensation, consulting fees, referral relationships, furniture markups, vendor invoices and management fees separately. Ask whether a seller credit or another payment reduces an obligation and where that credit appears. Do not subtract an expected credit twice or treat an unresolved refund as available cash. Use the <a href="/guides/str-service-responsibility-matrix/">service responsibility matrix</a> for named decision rights and the <a href="/compare/">comparison hub</a> for existing provider-specific answers rather than infer equal services from equal labels.</p>
<h2>A delegation worksheet: cash is not the same as time value</h2>
<p>Consider an invented buyer who estimates 200 hours for self-coordination and 60 hours for a delegated route. The difference is 140 hours. A hypothetical $24,000 service fee plus $5,000 of incremental outside work costs $29,000 more than the buyer's defined self-coordinated case. The comparison assumes the same property, core bills and accepted outputs; it does not assume those services prevent a mistake or increase revenue.</p>
<table><thead><tr><th>Chosen value per freed hour</th><th>140-hour imputed value</th><th>Value less $29,000 incremental cash</th></tr></thead><tbody><tr><td>$100</td><td>$14,000</td><td>-$15,000</td></tr><tr><td>$200</td><td>$28,000</td><td>-$1,000</td></tr><tr><td>$300</td><td>$42,000</td><td>$13,000</td></tr></tbody></table>
<p>The $13,000 is not rental profit or money received. A salaried buyer may earn no additional cash by freeing those hours. A business owner might redeploy some time, but availability, actual billable demand and incremental earnings need separate evidence. Lifestyle value can matter without turning into a cash receipt. Re-estimate retained meetings, approval work, travel and ongoing owner oversight; “done for you” does not mean no owner hours.</p>
<p>Next check affordability independently. Suppose the same fictional buyer has $300,000 available. Before these incremental service costs, the allocation is $160,000 down payment, $15,000 closing costs, $32,000 goods/setup, $15,000 repairs and $40,000 retained reserve: $262,000. Adding the $24,000 fee and $5,000 outside work gives $291,000, leaving $9,000 outside that protected reserve. A new, unbudgeted $12,000 repair raises the allocation to $303,000: a $3,000 gap if the reserve is preserved.</p>
<p>The $40,000 reserve is allocated once, not spent and subtracted again. The $5,000 outside work must be genuinely additional, not an inspection or setup bill already in the base. Reducing the reserve could change the cash result but changes the risk decision too. A proposed future tax benefit, refinance or booking is not funding available today. Replace every input with dated estimates and cleared funds using the <a href="/tools/first-str-purchase-budget/">first-STR purchase budget</a>.</p>
<h2>When delegation fits—and when to narrow or stop</h2>
<p>Delegation may fit a buyer who needs coordinated local execution, can fund the complete acquisition and wants documented outputs more than personal involvement in each task. Self-coordination or a limited-scope engagement may fit someone with time, local access and reliable independent professionals. High income alone proves neither suitability nor affordability. The relevant comparison is your actual missing work, accepted evidence, cash buffer and retained responsibilities.</p>
<p>Pause before signing when essential deliverables lack an owner, permissions remain unresolved, downside underwriting fails your criteria or the complete cash budget cannot be funded. Request corrections rather than infer misconduct from an unanswered marketing statement. Have your CPA evaluate personal tax suitability before relying on a benefit; neither a service label nor a manager arrangement establishes your tax result. No refund, deduction, rental performance, timing or investment outcome is promised.</p>
<p>For the next decision, bring one candidate property, the completed acceptance sheet and both cash/time cases to a service call. Ask what the proposed team will deliver and what it will not. Compare the same scope fairly with alternatives, and retain final purchase and professional-advice decisions.</p>
<div class="inline-cta"><h3>Ask us the scope and payment questions</h3><p>Discuss your acquisition needs, retained responsibilities, deliverables and outside costs before choosing a service.</p><a class="btn btn-primary btn-lg" href="/apply/">Apply Now</a></div>'''

FAQ = [
    ('What does a done-for-you Airbnb company actually do?', 'It may coordinate selected acquisition, diligence, setup and operating-handoff tasks. The label does not establish an end-to-end package. Verify named deliverables, outside professionals, exclusions and retained buyer decisions in the applicable agreement.'),
    ('How much does a done-for-you Airbnb service cost?', 'Use a dated written proposal rather than a universal typical fee. Confirm the calculation, payment trigger, credits, refund conditions, outside bills, recurring charges and obligations after stopping. The worksheet uses invented costs, not provider prices.'),
    ('Is a done-for-you Airbnb service worth it?', 'Compare accepted work, complete cash needs and your own retained hours. Imputed time value is not money received, and high income alone does not establish suitability. A narrower service or self-coordination may fit; no savings or investment result is promised.')
]

if __name__ == '__main__':
    refresh('done-for-you-airbnb-model', 'The Done-For-You Airbnb Model Explained', 'The Done-For-You Airbnb Model Explained', 'Evaluate a done-for-you Airbnb purchase service with a nine-workstream checklist, payment-trigger register and separate cash and time-value worksheets.', BODY, FAQ, '2026-08-10', 'data-done-for-you-model-review-link', 'Compare the <a href="/blog/done-for-you-airbnb-model/">done-for-you acquisition acceptance sheet and cash/time worksheets</a>. Delegated work, retained decision rights and affordability need separate evidence; imputed time is not cash.')
    from pathlib import Path
    p = Path(__file__).resolve().parents[1] / 'blog/done-for-you-airbnb-model/index.html'
    s = p.read_text()
    s = s.replace('<span>Published August 10, 2026</span>', '<span>Published August 10, 2026</span><span>&middot;</span><span>Updated October 7, 2026</span>', 1)
    p.write_text(s)
