"""Develop the existing Rabbu alternatives owner, preserving URL and design."""
from pathlib import Path
import re
ROOT=Path(__file__).resolve().parents[1]
p=ROOT/'compare/alternatives-to-rabbu/index.html';t=p.read_text();assert 'reviewed 2026-10-01' in t
t=t.replace('"dateModified": "2026-10-01"','"dateModified": "2026-10-07"')
marker='<section class="section-sm"><div class="wrap wrap-narrow"><h2>Choose before you sign</h2>';assert t.count(marker)==1
body='''<section class="section-sm"><div class="wrap wrap-narrow"><h2>Separate the marketplace, calculator and consultant</h2>
<p>Rabbu’s <a href="https://rabbu.com/" rel="noopener noreferrer">homepage</a> distinguishes active rental listings with historical income from homes with modeled projections, and links to agents, lenders and concierge help. Its current concierge link leads to an <a href="https://rabbu.com/services/str-search" rel="noopener noreferrer">STR Search consultant profile</a>. That profile describes acquisition analysis and says buyers still close with a licensed agent and lender. Do not assume every Rabbu connection is a Rabbu-operated end-to-end contract—or treat STR Search reached through Rabbu as an unrelated alternative without checking the actual relationship.</p>
<p>Rabbu’s <a href="https://rabbu.com/airbnb-calculator" rel="noopener noreferrer">calculator documentation</a> describes editable comparable selection and gross revenue figures that exclude cleaning fees, Airbnb fees, other service fees and management fees. It says projection accuracy depends on comparables and property performance. This can support an initial screen; it does not certify your future net cash, permitted use or financing.</p>
<div class="bc-docs"><h3>Request one candidate’s evidence and decision register</h3><ol>
<li><strong>Listing evidence:</strong> Label each figure as seller history or modeled projection, preserving period, source and receipt definitions. Request authorized supporting records without exposing guest or banking details. Use the <a href="/blog/reconcile-airbnb-payout-export/">seller payout reconciliation</a> where actual history is supplied.</li>
<li><strong>Analysis:</strong> Record which comparable homes were excluded and why, intended availability, cleaning treatment and current insurance, tax and manager evidence. Request a revised offer case when a verified expense changes; a high estimate is not permission to skip diligence.</li>
<li><strong>Engagement:</strong> Identify the contracting consultant, licensed representative and lender separately. Write down deliverables, fees, referral relationships, payment triggers, cancellation conditions and excluded launch work. No free tool automatically includes paid purchase support.</li>
<li><strong>Buyer authority:</strong> Name who resolves permission, inspection and funding questions and who tracks deadlines. Preserve your approval of the offer, contingency decisions and spend. Ask who coordinates opening after closing rather than infer that a referral includes execution.</li>
</ol></div>
<p>For a data-led alternative, compare the chosen <a href="/compare/alternatives-to-str-insights/">STR Insights tier</a> or <a href="/compare/airdna/">AirDNA tool</a> for the research task—not as interchangeable transaction representation. For acquisition help, compare the actual <a href="/compare/alternatives-to-str-search/">STR Search engagement</a>, a <a href="/compare/alternatives-to-the-short-term-shop/">specialist brokerage</a>, and BNB Accelerator’s signed scope against the same register. BNB’s <a href="/how-it-works/">published process</a> does not establish the inclusions of an unseen executed agreement. There is no universal winner.</p>
</div></section><section class="section-sm"><div class="wrap wrap-narrow"><h2>Worked decision: a modeled income advantage does not fund the purchase</h2>
<p><strong>Fictional example—not a Rabbu estimate, provider quote or client outcome:</strong> A candidate is initially screened with $120,000 annual lodging revenue. Assume distinct non-cleaning variable costs of 20% of lodging revenue, $30,000 fixed operating costs and $48,000 principal-and-interest debt payments. Fixed costs include property taxes and insurance. Cleaning receipts exactly match cleaning invoices and are excluded from both lodging cases. Initial modeled owner cash is $120,000 − $24,000 − $30,000 − $48,000 = <strong>$18,000</strong>, before capital replacements and income-tax consequences.</p>
<p>Later evidence supports a separate conservative $90,000 lodging case, not a prediction. With the same cost definitions, variable costs are $18,000 and annual owner cash becomes $90,000 − $18,000 − $30,000 − $48,000 = <strong>negative $6,000</strong>. The $30,000 revenue difference changes cash by $24,000 because the stipulated variable costs also fall. These are alternative cases, not deficits to add together. Ask each team to explain whether the candidate remains acceptable under the supported downside.</p>
<p>Separately, suppose a $600,000 purchase needs $150,000 down, $18,000 closing costs, $28,000 furnishing, $14,000 repairs, an invented $8,000 acquisition-service charge and $35,000 retained reserves. Total capital allocation is <strong>$253,000</strong>: <strong>$3,000 short</strong> against $250,000 available. The service charge is fictional and attributed to no provider. A forecast $18,000 annual surplus cannot pay that closing-day gap. Do not count the retained reserve twice or silently use it to make the plan fit.</p>
<p>A conservative annual deficit also requires a monthly receipt-and-bill schedule; it is not a second closing invoice. Reprice the property, change actual funded terms or reject an unsupported plan under applicable contract rights. Do not make a larger tax bill or advertised low down payment substitute for lender approval and accessible cash. Continue with the <a href="/blog/airbnb-revenue-projections/">revenue evidence worksheet</a> and <a href="/tools/first-str-purchase-budget/">purchase cash budget</a>.</p>
</div></section>'''
t=t.replace(marker,body+marker)
t=t.replace('Provider facts summarized from <a href="https://rabbu.com/about" rel="noopener noreferrer">Rabbu’s public material</a>, reviewed 2026-10-01.','Document-based analysis of the linked Rabbu homepage, calculator documentation and consultant profile, reviewed 2026-10-07. This is not firsthand testing, a verified customer-experience review or an analysis of an unseen client contract. Advertised ratings and outcomes are not independently established here.')
p.write_text(t)
p=ROOT/'sitemap-core.xml';t=p.read_text();t,n=re.subn(r'(<loc>https://www.bnbaccelerator.com/compare/alternatives-to-rabbu/</loc>\s*<lastmod>)[^<]+(</lastmod>)',r'\g<1>2026-10-07\2',t);assert n==1;p.write_text(t)
