"""Expand one existing comparison; preserve homepage, FAQ and publication."""
from pathlib import Path
import re
R=Path(__file__).resolve().parents[1]
p=R/'compare/bnb-turnkey-vs-str-search/index.html';s=p.read_text()
assert '"datePublished": "2026-10-06"' in s and '"dateModified": "2026-10-06"' in s
s=s.replace('"dateModified": "2026-10-06"','"dateModified": "2026-10-07"')
marker='<section class="section-sm"><div class="wrap wrap-narrow"><h2>Compare evidence using one actual candidate</h2>'
assert s.count(marker)==1
body='''<section class="section-sm"><div class="wrap wrap-narrow"><h2>Buyer fit: compare the next obligation, not just the first match</h2>
<p>For a buyer purchasing in the next six months, the useful distinction is which missing work the signed engagement fills. <a href="https://bnb-turnkey.com/services">BNB Turnkey's services page</a> describes market selection, forecasting, virtual tours, inspection and negotiation support, design/furnishing management and budget oversight. That makes it a relevant proposal for broader coordination. It does not authenticate your package, a fixed launch price or any obligation to replace a rejected property.</p>
<p><a href="https://go.strsearch.com/1">STR Search's matching page</a> emphasizes screening data, market saturation, revenue and amenities. Its <a href="https://strsearch.com/">main site</a> discusses a separate realtor role and disclaims guaranteed financial performance. Evaluate the actual matching tier if your gap is candidate selection and analysis. Neither a marketing match promise nor a forecast establishes lender approval, insurability, permit eligibility or a contractual refund. This comparison is document-based analysis, not firsthand testing, a customer rating or verification of either firm's results.</p>
<p>Broader is not automatically better. An investor with an established agent, contractor and manager may already have execution coverage; another buyer may need a named coordinator to reconcile those parties. Ask each firm to identify supplied work, exclusions and the actual decision-maker. Treat BNB Accelerator's proposal the same way: published positioning is not a substitute for signed scope.</p>
<h2>Original rejected-candidate and replacement-search register</h2>
<p>Give both providers this work sample: a candidate passes revenue screening, but a dated insurer response excludes the intended use and an inspection identifies a previously omitted repair. The buyer has not approved the risk or waived a contingency. Request a redacted example showing how the team would record the following items; this worksheet does not claim either provider is contractually obliged to deliver them.</p>
<div class="table-scroll"><table><thead><tr><th>Decision field</th><th>Evidence to request from each proposal</th><th>Buyer acceptance test</th></tr></thead><tbody>
<tr><td>Candidate acceptance</td><td>Written criteria, missing evidence and who can approve a match</td><td>A forwarded listing is not silent buyer approval; record acceptance explicitly</td></tr>
<tr><td>Rejection and transaction notice</td><td>Who documents the failed condition and who handles any authorized contract notice</td><td>A service-team rejection does not itself terminate the purchase contract</td></tr>
<tr><td>Replacement work</td><td>Whether re-search, revised underwriting and another candidate are included; limits and end date</td><td>Distinguish a new address from a correction to the same analysis</td></tr>
<tr><td>Fee trigger and exclusions</td><td>Invoice milestone, earned amounts, extra tasks and written refund/credit conditions</td><td>Do not assume rejected property means unearned fee, cash refund or transferable credit</td></tr>
<tr><td>Launch commitments</td><td>Design/vendor deposits, cancellation terms and authority to approve spending</td><td>Identify which commitments can wait until the property is accepted</td></tr>
<tr><td>Decision rights</td><td>Named analyst, coordinator, transaction representative and independent professional roles</td><td>Buyer authorizes risk and spending; the right professional resolves the disputed condition</td></tr>
</tbody></table></div>
<p>Ask for the replacement-search clock in writing: when it starts, whether rejected candidates consume it, and what happens if a replacement arrives after the service period or your financing deadline. A thirty-day marketing message is not evidence that a rejected match restarts the clock. Do not infer a particular remedy without the actual terms. Use the <a href="/guides/str-search-property-match-questions/">matching-contract questions</a> and <a href="/guides/bnb-turnkey-management-handoff/">coordination-to-management handoff</a> to investigate the distinct obligations.</p>
<h2>Worked purchase cash: a replacement can cost money even without another service invoice</h2>
<p><strong>Hypothetical arithmetic only, not either provider's fee, a client result or a refund promise:</strong> assume $320,000 available. A replacement property's complete plan assigns $165,000 down payment, $18,000 distinct closing/service costs, $38,000 setup, $19,000 repairs and $50,000 retained operating cash. Allocation is $290,000, leaving $30,000 outside the plan. This plan excludes all costs of the rejected candidate. Replace the invented figures with dated quotes; the retained cash is assigned once, not spent again to make a gap disappear.</p>
<p>Suppose the rejected candidate separately consumed $1,200 in inspection, $800 in appraisal and $2,500 in a nonrefundable vendor commitment: $4,500 total. Those invented losses are not included in the replacement's $290,000. Combined cash use is $294,500 and remaining margin is $25,500. If the actual contract requires an additional $6,000 replacement-search invoice, cash use becomes $300,500 and margin $19,500. If replacement work is already included, do not add that invoice; the margin remains $25,500. Neither treatment is a published provider quote.</p>
<p>A separate $12,000 repair discovered on the replacement reduces those margins to $7,500 with the incremental invoice, or $13,500 without it. An expected $3,000 credit restricted to a future service is not cleared purchase cash and does not increase either margin. If an actual $3,000 cash refund clears before the relevant payment deadline, recalculate from the documented receipt—not from the promise. This exercise excludes any additional holding/delay costs, taxes or other losses; add actual obligations without counting them twice. It establishes neither profit nor financing qualification.</p>
<h2>Fair alternatives and the next purchase decision</h2>
<p>If neither proposal fills the missing role, compare <a href="/compare/alternatives-to-str-insights/">STR Insights' actual service tier</a> for analysis/support or <a href="/compare/alternatives-to-the-short-term-shop/">The Short Term Shop's local representation and education proposal</a>. These are fair alternatives to investigate, not interchangeable packages or declared winners. BNB Accelerator is the interested publisher; request its <a href="/how-it-works/">current contracted acquisition scope</a>, the same rejected-candidate work sample and its exclusions. Keep buyer authority, lender/insurance decisions and professional tax/legal advice separate from provider recommendations.</p>
<p>Before choosing, complete the register against one real candidate and the <a href="/tools/first-str-purchase-budget/">purchase cash worksheet</a>. Then <a href="/apply/">discuss the acquisition responsibilities you need covered</a>. Use the <a href="/compare/">comparison hub</a> to follow the existing canonical reviews rather than treat additional page count as additional evidence.</p>
</div></section>'''
s=s.replace(marker,body+marker)
s=s.replace('Reviewed 2026-10-06:', 'Reviewed October 7, 2026:')
s=s.replace('Provider statements describe published offers, not independently audited performance.', 'Provider statements describe published offers, not independently audited performance. The services page, main site and linked matching page were reviewed October 7, 2026; unseen client agreements and individual fees were not authenticated. All worked cash figures are hypothetical. No firsthand testing, review score, affiliation, superiority or guaranteed outcome is claimed.')
p.write_text(s)
p=R/'sitemap-core.xml';s=p.read_text();s,n=re.subn(r'(<loc>https://www.bnbaccelerator.com/compare/bnb-turnkey-vs-str-search/</loc>\s*<lastmod>)[^<]+',lambda m:m[1]+'2026-10-07',s);assert n==1;p.write_text(s)
