"""Scoped existing comparison development, not a new blog guide."""
from pathlib import Path
import re
R=Path(__file__).resolve().parents[1]
p=R/'compare/awning/index.html';s=p.read_text()
assert '"datePublished": "2026-08-15"' in s and '"dateModified": "2026-10-01"' in s
s=s.replace('"dateModified": "2026-10-01"','"dateModified": "2026-10-07"')
s=s.replace('<td>Sourcing, underwriting and purchase-to-launch coordination</td>','<td>Published acquisition coordination; actual signed scope governs</td>')
marker='<section class="section-sm"><div class="wrap wrap-narrow"><h2>Which option fits your first purchase?</h2>'
assert s.count(marker)==1
body='''<section class="section-sm"><div class="wrap wrap-narrow"><h2>What the current public materials establish</h2>
<p>Awning’s <a href="https://website.awning.com/vacation-rental-buying" rel="noopener noreferrer">buying page</a> describes investment search, agent-assisted evaluation and brokerage, plus furnishing/design and management connections. It says brokerage commission funds its buying service. That can be a useful connected route; it does not establish zero buyer-paid transaction costs or that furniture and vendor invoices are included.</p>
<p>The <a href="https://website.awning.com/airbnb-management" rel="noopener noreferrer">management page</a> describes listing, guest, cleaning and maintenance work. Its pricing depends on the property, location and services; its advertised cancellation policy uses 90 days’ notice. Request the actual contract and booking-handoff obligations rather than interpreting that advertisement as immediate release. This comparison does not verify advertised revenue lifts, ratings or an individual operator’s availability.</p>
<p>BNB’s <a href="/how-it-works/">published process</a> describes purchase coordination and designer/operator pairing while retaining the buyer’s final decisions and capital. Pairing is not an executed vendor engagement or day-to-day management. Lending, legal and tax advice are separate licensed roles. Obtain BNB’s actual signed scope and fee triggers too; this document analysis has not authenticated either provider’s client agreement.</p>
</div></section><section class="section-sm"><div class="wrap wrap-narrow"><h2>Original work sample: one address, two readiness plans</h2>
<p>Before an offer, give both contacts the same listing, financing assumptions and intended opening date. Ask each to complete this five-line work sample with names, evidence and deadlines. A polished revenue estimate is not proof that the property can open on time.</p>
<div class="bc-docs"><ol>
<li><strong>Buy:</strong> Identify the licensed representative, contracting entity, compensation recipient and payment trigger. State any conditions linking acquisition help to a management engagement, and who submits offer or contingency notices.</li>
<li><strong>Permit:</strong> Name who obtains address-level municipal and HOA documents, identifies unresolved use limits and escalates them to counsel. Record the buyer’s stop/go decision before protection expires; a provider's market coverage is not legal permission.</li>
<li><strong>Install:</strong> Name who orders and pays for furnishings, checks deliveries and approves substitutions. Separate introductions, coordination fees and actual supplier invoices. State how a missed delivery changes the opening plan.</li>
<li><strong>Accept:</strong> Name who verifies safety, insurance, cleaning, photographs, listing access and operator readiness. Assign written acceptance and spending authority; “launch assistance” alone does not allocate these tasks.</li>
<li><strong>Operate or exit:</strong> Identify the actual manager, revenue-based fee definition, excluded costs, repair limits and owner reporting. Document termination notice, existing bookings and account access. Do not assume a booking account or its reviews can freely transfer.</li>
</ol></div>
<p>Compare the answers with the <a href="/guides/str-service-responsibility-matrix/">service responsibility matrix</a> and <a href="/blog/str-management-agreement-termination/">management exit guide</a>. An unresolved line is a question to settle—not evidence that one firm fails to perform. A buyer choosing separate vendors should explicitly budget the extra handoff work; a connected route still needs named accountability.</p>
</div></section><section class="section-sm"><div class="wrap wrap-narrow"><h2>Worked purchase case: funded at closing, short after a delay</h2>
<p><strong>Invented illustration—not Awning or BNB fees, an opening forecast or a client result:</strong> A buyer has $300,000 spendable cash. Allocate $180,000 down payment, $18,000 closing/service charges, $35,000 furnishings, $12,000 repairs and $45,000 retained operating reserves. Total is <strong>$290,000</strong>, leaving <strong>$10,000</strong> outside the plan. Assume those categories include all originally quoted work, with no deposit or vendor charge added twice.</p>
<p>Now stipulate a two-month opening delay with $4,000 monthly cash obligations before revenue, plus a distinct $5,000 rush-install bill not in the original furnishings budget. Additional funding required is $8,000 + $5,000 = <strong>$13,000</strong>. Keeping the assigned $45,000 reserve intact requires <strong>$303,000</strong>, a <strong>$3,000 shortfall</strong>. The original $10,000 cushion is spent first; silently reducing the reserve by $3,000 is a changed risk plan, not the original funded purchase.</p>
<p>Alternatively, if the rush bill is already included in the $35,000 furniture allocation, do not add it again. Only the $8,000 incremental delay cash applies: allocation becomes <strong>$298,000</strong> and the remaining cushion is <strong>$2,000</strong>. These are alternative cases, not cumulative expenses. Principal/interest, insurance and utilities included in the stipulated monthly amount must not also be counted as separate delay costs.</p>
<p>Have each proposal identify who confirms delivery dates and who approves extra spending, then replace the assumptions with actual lender/vendor/insurance figures. If a provider’s fee is not in the closing/service allocation, add its verified amount once. Do not assume future bookings, a tax refund or a promised faster launch can close the cash gap. A lower recurring percentage does not fund an earlier bill. Use the <a href="/tools/first-str-purchase-budget/">purchase cash planner</a> before committing.</p>
</div></section><section class="section-sm"><div class="wrap wrap-narrow"><h2>Fair alternatives when the work split does not fit</h2>
<p><a href="/compare/avery-carl-short-term-shop/">The Short Term Shop</a> offers a specialist brokerage route with publicly described training/vendor support; compare the tasks you will still direct. For matching and analysis, review <a href="/compare/str-search/">STR Search’s actual proposal</a> rather than assuming it includes representation and operation. Neither is automatically an equivalent replacement. The <a href="/compare/alternatives-to-awning/">Awning alternatives page</a> examines broader service paths and recurring fee-base arithmetic; this direct comparison focuses on purchase-to-opening accountability and delay cash. Continue through the <a href="/compare/">crawlable comparison hub</a>.</p>
</div></section>'''
s=s.replace(marker,body+marker)
s=s.replace('Provider facts summarized from <a href="https://awning.com/vacation-rental-buying" rel="noopener noreferrer">Awning’s public material</a>, reviewed 2026-09-27.','Document-based analysis of the linked Awning buying/management materials and BNB published process, reviewed October 7, 2026. This is not firsthand testing, a verified customer-experience review or evaluation of unseen executed agreements.')
p.write_text(s)
p=R/'sitemap-core.xml';s=p.read_text();s,n=re.subn(r'(<loc>https://www.bnbaccelerator.com/compare/awning/</loc>\s*<lastmod>)[^<]+',lambda m:m[1]+'2026-10-07',s);assert n==1;p.write_text(s)
