"""Expand the existing cleaning-receipt underwriting owner, not a new URL."""
from refresh_dscr_purchase_methods import refresh,publisher
BODY='''<p class="lead">Cleaning fees can appear in an STR seller's gross receipts, but they are not automatically profit or transferable buyer income. Before buying, match the fee actually retained from each reservation with the corresponding cleaning, laundry and other distinct turnover charges. Then include any platform and management charges that apply to that fee. Comparing a property that reports cleaning gross with one that reports only accommodation can distort an offer without changing the underlying economics.</p>
<p>This original worksheet answers a purchase question: how much supported cleaning contribution belongs in the buyer's operating case, and what changes under the buyer's accepted service terms? <a href="/apply/">Bring the reconciled cleaning bridge to an STR acquisition call</a>. Do not pay an income premium for an unreconciled pass-through.</p>
<h2>Define the receipts before labeling them revenue</h2>
<p><a href="https://www.airbnb.com/help/article/2812">Airbnb's cleaning-fee guidance</a> describes a host-set, one-off charge included in the total price. Its current refund explanation depends on cancellation timing, the applicable policy and, for older bookings, a stated booking-date exception. A displayed fee is therefore not proof that the host retained that amount. Review actual completed adjustments rather than assuming every reservation earns a full fee.</p>
<p><a href="https://www.airbnb.com/help/article/1857">Airbnb's service-fee guidance</a> describes different structures and a transition to a single fee. It says host fees are deducted from payout and, in its split-fee explanation, the calculation includes host-charged fees while excluding guest service fees and taxes. Review the actual transaction charge and applicable buyer arrangement; a seller's historic percentage is not a universal future fee. The examples below use an invented rate, not a quoted Airbnb rate.</p>
<p>Both primary pages were reviewed October 8, 2026; this is a review date, not a publication date supplied by the sources. This page uses platform guidance to identify evidence questions, not to certify seller records, establish accounting treatment or promise a refund. Keep collected taxes, refundable deposits, guest platform charges and retained owner receipts separately identified. Ask the accountant how the actual records should be reported.</p>
<h2>Original same-reservation acceptance register</h2>
<div class="table-wrap"><table><thead><tr><th>Field</th><th>Evidence to reconcile</th><th>Purchase decision</th></tr></thead><tbody>
<tr><td>Property and period</td><td>Listing identifier, currency, covered stays, report basis and all channels</td><td>Are these the same reservations, not cash from a different period?</td></tr>
<tr><td>Cleaning retained</td><td>Guest charge, completed refund or adjustment and payout detail</td><td>What amount actually remains on the defined basis?</td></tr>
<tr><td>Turn work</td><td>Accepted invoice, date, scope, laundry, supplies and included services</td><td>Are separately billed services omitted or counted twice?</td></tr>
<tr><td>Fee exposure</td><td>Actual platform deduction and manager's signed rate and fee base</td><td>Does charging a cleaning fee also incur another charge?</td></tr>
<tr><td>Exceptional work</td><td>Deep clean, owner stay, interrupted booking or separately authorized work</td><td>Why does invoice count differ from guest checkouts?</td></tr>
<tr><td>Buyer replacement</td><td>Accepted buyer quote, availability, exclusions and payment dates</td><td>Will the buyer face the same cost and usable capacity?</td></tr>
</tbody></table></div>
<p>Request authorized, redacted property records through secure channels. Do not request passwords or publish guest identities, bank details or cleaner access codes. Missing support is an unresolved input, not proof of misconduct or zero expense. The <a href="/blog/str-owner-statement-review/">owner-statement worksheet</a> handles manager remittances and held reserves; this register isolates reservation-level cleaning contribution. The <a href="/blog/str-seller-wont-share-revenue-records/">missing-records purchase guide</a> handles evidence deadlines and an unsupported income premium.</p>
<h2>Worked comparison: two reporting styles, one economic result</h2>
<p>Every number below is hypothetical, not a seller file, market benchmark, provider quote or client outcome. Assume 80 completed stays covering 240 sold nights in one defined period. Supported accommodation receipts are $96,000 and retained cleaning receipts are 80 × $225 = $18,000. Assume no outstanding refunds or other adjustments in these starting figures. Cleaner work is $190 and distinct laundry $25 per stay: 80 × $215 = $17,200. Before other fees, cleaning contributes $800, not $18,000.</p>
<p>Now stipulate an invented 10% platform deduction on accommodation plus cleaning and an invented 20% management fee on accommodation alone. Platform charges total $11,400, of which $1,800 relates to cleaning. Management totals $19,200. Cleaning's defined contribution after its allocated platform charge is $18,000 − $1,800 − $17,200 = negative $1,000. Do not add another manager charge to cleaning under this stipulated agreement; a different signed fee base requires a different calculation.</p>
<div class="table-wrap"><table><thead><tr><th>Presentation of the same records</th><th>Defined contribution before other costs</th></tr></thead><tbody>
<tr><td>Show accommodation and cleaning gross</td><td>$114,000 − $11,400 platform − $19,200 management − $17,200 turn costs = $66,200</td></tr>
<tr><td>Show accommodation and net cleaning separately</td><td>$96,000 − $9,600 accommodation platform − $19,200 management − $1,000 net cleaning shortfall = $66,200</td></tr>
<tr><td>Incorrectly use the pre-platform $800 cleaning margin</td><td>$96,000 − $9,600 − $19,200 + $800 = $68,000; overstates this defined result by $1,800</td></tr>
</tbody></table></div>
<p>These are two presentations of identical economics, not two properties with identical future performance. The subtotal omits utilities, insurance, property taxes, maintenance, debt, capital work and other obligations. It is not tax profit, standardized net operating income, qualifying lender income or an investment return. Do not multiply a short seasonal sample into an annual forecast or add the same net cleaning amount to gross receipts again.</p>
<h2>Replace seller costs and test the stay mix</h2>
<p>Suppose the buyer's separately accepted quote is $240 cleaning plus $30 laundry, with no overlapping allowance. At 80 turns, costs become $21,600. Keeping the example's other inputs fixed solely for sensitivity, cleaning contribution becomes $18,000 − $1,800 − $21,600 = negative $5,400. The defined property subtotal falls $4,400 to $61,800. A seller's service agreement or prepaid balance does not automatically follow the deed; verify actual buyer terms and <a href="/blog/cleaner-capacity-peak-season/">accepted peak-day capacity</a>.</p>
<p>For a separate sensitivity, hold 240 sold nights and $96,000 accommodation receipts constant but assume 120 completed stays averaging two nights instead of 80 averaging three. These fixed inputs are not a demand forecast or evidence that a minimum-stay change preserves bookings. Retained cleaning receipts become $27,000; their invented platform charge is $2,700; buyer turn costs become $32,400. Net cleaning is negative $8,100 and the defined property subtotal $59,100, another $2,700 below the buyer's 80-turn case.</p>
<p>The difference follows from 40 extra turns at negative $67.50 cleaning contribution each under these assumptions. Reconcile actual booking dates, stay length, refunds and exceptional services rather than modeling turns as a flat percentage of revenue. Changing displayed fees or minimum stays is a separate operating decision requiring evidence; it does not cure an unsupported purchase model.</p>
<h2>Make the offer and cash decision on supported buyer terms</h2>
<p>Annual or period contribution is not cash available for launch. Separate hypothetical cash example: $300,000 genuinely available, with purchase, closing, setup and a protected $40,000 reserve already allocating $280,000. Distinct excluded buyer-readiness items are a $600 authorized trial, $1,800 additional linen stock and $900 vendor-held deposit. Allocation becomes $283,300, leaving $16,700 unassigned. The deposit consumes available cash but is not automatically an operating expense; confirm its use and return terms.</p>
<p>If that original $280,000 already budgets eight turns at $215, replacing them with eight $270 turns adds only $440, not another $2,160. Allocation becomes $283,740 and unassigned margin $16,260. Do not add the entire $4,400 period sensitivity again as a closing invoice or count included linens twice. Reconcile due dates, actual cleared cash and protected reserves with the <a href="/tools/first-str-purchase-budget/">purchase-budget worksheet</a>; these partial inputs do not establish adequate reserves.</p>
<p>Proceed when matched records, buyer service terms, lawful use, financing and the complete downside support the offer. Reprice a viable acquisition when supported cost changes matter. Seek valid protection through the retained transaction professional while decisive invoices or acceptance remain missing; a worksheet creates no extension or refund right. Decline an income premium that only works by counting gross cleaning without its costs. A large tax bill or substantial personal capital does not validate the property's margin.</p>
<p><a href="/apply/">Compare candidate STRs using supported receipts, turn costs and dated buyer cash</a>, then continue through the <a href="/blog/buy-str-high-income-large-tax-bill/">high-income purchase roadmap</a>. BNB Accelerator assists within its actual contracted acquisition scope; independent accountants, lenders and counsel determine their respective conclusions.</p>
<p class="small">BNB Accelerator is the commercially interested acquisition-service publisher. Document-based education, not firsthand vendor testing, a review score or professional accounting, tax, legal, lending or investment advice. All worked figures are hypothetical. No records, refund, availability, booking, deduction, financing or investment result is guaranteed.</p>'''
FAQ=[('Do gross cleaning fees establish STR profit?','No. Reconcile retained cleaning receipts with matching turn costs and applicable platform and management charges. Gross receipts alone do not establish buyer profit.'),('How do I compare sellers that report cleaning differently?','Normalize the same covered reservations and definitions. Show either gross cleaning and all matching deductions or net cleaning once; do not add net contribution to gross receipts again.'),('Should I assume one cleaner invoice for every checkout?','No. Request scope and support for deep cleans, owner stays, interrupted bookings and separately authorized work. A count difference requires explanation, not an accusation.'),('Does the seller’s cleaning cost transfer to the buyer?','Not automatically. Obtain accepted buyer pricing, scope, capacity and payment dates. Model replacement costs and distinct launch commitments without duplicating existing allowances.')]
if __name__=='__main__':
 publisher.DATE='2026-10-08'
 refresh('cleaning-fees-gross-revenue','Do Cleaning Fees Count as STR Revenue When Buying | BNB Accelerator','Do Cleaning Fees Count as STR Revenue When Buying?','Before buying an STR, reconcile cleaning receipts, turn costs and fee bases. Use a same-reservation comparison and buyer cash worksheet.',BODY,FAQ,'2026-09-23','data-cleaning-fees-review-link','Normalize <a href="/blog/cleaning-fees-gross-revenue/">cleaning receipts, matching costs and buyer fee exposure</a> before comparing headline seller revenue or funding launch.')
 p=publisher.ROOT/'blog/cleaning-fees-gross-revenue/index.html';p.write_text(p.read_text().replace('<span>Updated October 7, 2026</span>','<span>Updated October 8, 2026</span>',1))
