"""Scoped existing signing-guide refresh; not a new 509 acquisition guide."""
from pathlib import Path
import re
R=Path(__file__).resolve().parents[1]
p=R/'guides/str-search-property-match-questions/index.html'
s=p.read_text()
assert '"datePublished": "2026-10-01"' in s and '"dateModified": "2026-10-01"' in s
s=s.replace('"dateModified": "2026-10-01"','"dateModified": "2026-10-07"')
old='Translate a property-match pitch into screening criteria, evidence and enforceable deliverables.'
new='Before signing an STR Search proposal, define match acceptance, model revisions, payment triggers and the cash needed for unresolved work.'
assert s.count(old)==5
s=s.replace(old,new)
start=s.index('<section class="section-sm bg-alt"><div class="wrap"><h2>Your proposal review worksheet</h2>')
end=s.index('<section class="section-sm"><div class="wrap wrap-narrow"><h2>Continue your buyer comparison</h2>',start)
body='''<section class="section-sm bg-alt"><div class="wrap"><h2>Your proposal review worksheet</h2><p>Use this original signing register for your actual proposal. The entries below are requests, not a description of STR Search's contractual promises. Keep each answer tied to a dated attachment or clause rather than recording “discussed on call.”</p><div class="bc-table-scroll" role="region" aria-label="Proposal review worksheet" tabindex="0"><table><thead><tr><th scope="col">Question</th><th scope="col">Evidence to record</th><th scope="col">Decision gate</th></tr></thead><tbody>
<tr><th scope="row">What counts as a match?</th><td>Criteria version; required inputs; definition of delivery versus buyer acceptance; any remedy and exclusions in the agreement</td><td>Before paying, confirm whether receiving a candidate completes the obligation even when a material input remains open</td></tr>
<tr><th scope="row">What happens when a matched house fails diligence?</th><td>Reason for rejection; who decides; treatment of a replacement, service clock, earlier payments and third-party bills</td><td>Do not assume a new search, refund or extension is included; request the actual terms before commitment</td></tr>
<tr><th scope="row">Can I recreate the revenue model?</th><td>Comparable addresses, observation periods, availability assumptions, expense quotes, sensitivity case and model revision owner</td><td>Before authorizing an offer, explain which numbers remain estimates and who updates them when evidence changes</td></tr>
<tr><th scope="row">Who owns closing and launch?</th><td>Named broker, notice sender, inspection reviewer, setup coordinator and operator; accepted handoff and separate charges</td><td>Before each deadline, distinguish analysis or introduction from authority to act or an executed task</td></tr>
</tbody></table></div></div></section>
<section class="section-sm"><div class="wrap wrap-narrow"><h2>Read the promise and the paid agreement separately</h2>
<p>The <a href="https://strsearch.com/">STR Search homepage</a> currently advertises a time-bound matching promise while its investment disclaimer says financial performance is not guaranteed. That distinction matters: a service milestone, a successful closing and an investment result are different events. Record the exact milestone, starting event, buyer-response requirements and any remedy in your proposed engagement. This guide does not establish that a refund or a profitable property is owed.</p>
<p>The linked <a href="https://strsearch.com/terms--conditions">website Terms &amp; Conditions</a> describe access to its websites and informational services. We have not authenticated your paid-client agreement. Do not substitute those public terms for the document naming your service tier, contracting entity, payment schedule, exclusions and dispute process. Ask the provider which documents govern, and have your lawyer resolve any inconsistent promise before signing. These are purchase-review questions, not a legal opinion about enforceability.</p>
<h2>Original acceptance work sample: a candidate is not an approval</h2>
<p>Hypothetical work sample, not an actual provider file or client outcome: a buyer's screening brief requires a financeable house, a documented path to lawful STR use and a complete cash plan. Candidate version 1 fits the asking-price limit. The model uses an estimated insurance allowance, but no address-specific quote has arrived. The permit information is a seller statement rather than a response from the relevant authority. Mark the candidate “received; insurance and permitted use unresolved,” not “approved to buy.”</p>
<p>Ask the matching team to identify the model version and unresolved assumptions. Ask the licensed transaction professional who may communicate an authorized offer and track its deadlines. Ask the relevant insurance and permitting professionals for the missing evidence. These requests do not automatically create a contractual right to delay, cancel or extend anything. If an offer is already signed, obtain advice about its actual conditions and notice deadlines; an internal spreadsheet flag is not a contract notice.</p>
<p>When the quote or permit response arrives, record the date, source and resulting decision. If the model changes, preserve both versions and the reason rather than overwriting the original conclusion. The buyer can then distinguish a revised economic choice from a service-delivery dispute. For a reproducible comp selection file, use the <a href="/blog/assembling-a-comparable-set/">comparable-set guide</a>; for named handoffs, use the <a href="/guides/str-service-responsibility-matrix/">acquisition responsibility matrix</a>. This signing guide focuses on recording acceptance and payment exposure rather than ranking matching services.</p>
</div></section>
<section class="section-sm"><div class="wrap wrap-narrow"><h2>Use a missing-answer test</h2>
<p>Hypothetical capital worksheet only; no STR Search or BNB price is implied. Suppose $300,000 is accessible for the purchase. Allocate $160,000 to the down payment, $18,000 to closing costs, $12,000 to an invented service allowance, $30,000 to furnishing, $15,000 to known repairs and $40,000 to a retained operating reserve. The complete allocation is $275,000, leaving $25,000 of unallocated margin. The reserve remains cash reserved for the investment; it is counted once, not expensed and subtracted again.</p>
<p>The provider has discussed the process, but responsibility for an additional $12,000 opening task is unresolved. If your signed scope already includes that same task inside an existing allowance, do not add it again. If it is a distinct buyer-paid obligation, total allocation becomes $287,000 and margin falls to $13,000. Do not assume an introduction includes vendor labor or treat an expected credit as available cash without written confirmation.</p>
<p>Now consider a separate $25,000 repair discovered later. If both additional costs apply, allocation rises to $312,000, creating a $12,000 funding shortfall. If only the new repair applies, the $300,000 allocation uses all initially unallocated margin while keeping the stated reserve. Neither outcome establishes adequate reserves or an acceptable investment; replace every assumption with actual quotes, financing terms and your own requirements. Do not use an expected tax refund to close the gap.</p>
<p>For every unresolved cost, record the task, actual payer, payment date, amount or range, evidence and whether it is already included elsewhere. “Unknown” is a valid entry. Proceed only when material rights, duties and costs are documented and fit your plan; request a scope revision or defer commitment when the unanswered item changes affordability or control. A favorable case study cannot replace your agreement. Your tax, legal, lending and insurance advisers remain responsible for their own professional assessments.</p>
</div></section>'''
s=s[:start]+body+s[end:]
s=s.replace('<a href="/guides/str-search-property-match-questions/">STR Search Property Match: Questions Before Signing</a></p>', '<a href="/compare/the-short-term-shop-vs-str-search/">Brokerage versus matching proposals</a></p>')
s=s.replace('reviewed 2026-10-01.', 'reviewed October 7, 2026. Neither primary page displays an article publication date; this is the source-review date, not a provider publication date.')
s=s.replace('This is a public-offer comparison, not a customer review, independent ranking or endorsement.', 'This is document-based analysis, not firsthand testing, a customer review, independent ranking or endorsement. No paid-client contract, fee quote or provider outcome has been authenticated here. BNB Accelerator\'s own deliverables depend on its signed engagement, not this worksheet.')
p.write_text(s)
p=R/'sitemap-core.xml';s=p.read_text()
s,n=re.subn(r'(<loc>https://www\.bnbaccelerator\.com/guides/str-search-property-match-questions/</loc>\s*<lastmod>)2026-10-01',r'\g<1>2026-10-07',s)
assert n==1;p.write_text(s)
