"""Scoped existing acquisition guide; preserve URLs, homepage and sibling articles."""
import expand_hold_period as publisher
from pathlib import Path
import re

SLUG='appliances-buying-short-term-rental'
BODY='''<p class="lead">Before buying a furnished STR, turn the appliance package into an item-by-item closing decision. Listing photographs do not establish which refrigerator, range, dishwasher or laundry units convey, whether they work, or what you must pay before opening. Compare the equipment actually included in the contract with the inspected equipment, installed replacement bids and a dated cash budget. A seller credit, a working test and a warranty each answer a different question.</p>
<p><a href="/apply/">Bring the equipment inventory and funded make-ready comparison to a BNB Accelerator acquisition call</a>. We help evaluate the purchase within our contracted scope; inspectors, installers, counsel, lenders and manufacturers determine their own conclusions.</p>
<h2>Define the package before assigning value to it</h2>
<p>Ask the seller and agent for a room-by-room inventory identifying the appliance, brand, model, serial number, location and proposed disposition. Record leased equipment, exclusions and promised substitutions separately. Have the transaction professionals establish how the agreed inventory is incorporated into the purchase documents. Do not infer a nationwide fixture rule or assume an appliance shown in marketing automatically transfers.</p>
<p>Compare that inventory with dated photographs and the actual units at the property. A description such as stainless kitchen is not an identity record. Note included accessories and required controls, and request invoices or service records without inventing age from appearance. A missing invoice leaves age or ownership unresolved; it does not prove theft or a defect. The <a href="/blog/str-furniture-bill-of-sale/">furnished-asset handoff guide</a> covers the wider asset bundle.</p>
<h2>Separate a test, a safety check and a warranty</h2>
<p>Ask the inspector what is and is not included in the actual inspection agreement. A unit operating during a visit does not establish remaining useful life, installation compliance, future repair availability or suitability for the intended turnover workload. Request qualified follow-up where an observed condition or untested function matters to the offer. Do not open electrical panels, disconnect gas or perform an improvised test to settle the question yourself.</p>
<p>Check the identified equipment against the <a href="https://www.cpsc.gov/Recalls">CPSC recalls and product safety warnings</a> and the manufacturer's relevant notice. Save the search date, matching identifiers and any applicable action instructions. CPSC notes that remedy availability can change. A search with no match is not a safety certification, and a possible remedy is not cash available for closing. Do not operate equipment contrary to applicable stop-use instructions while waiting for a seller response.</p>
<p>Request the actual warranty or service-contract document and written confirmation of buyer eligibility, use restrictions, transfer procedure, effective date, covered work, exclusions and fees. Never assume coverage follows the property, permits rental use or replaces an installation review. For the physical inspection scope, use the separate <a href="/blog/appliances-inspection-short-term-rental/">appliance inspection page</a>; this guide turns the resulting facts into an acquisition decision.</p>
<h2>Build an equipment disposition register</h2>
<div class="table-wrap"><table><thead><tr><th>Record</th><th>Evidence to attach</th><th>Purchase consequence</th></tr></thead><tbody>
<tr><td>Included identity</td><td>Contract inventory, location and model/serial photographs</td><td>Price what will actually convey, not an unspecified substitute</td></tr>
<tr><td>Condition and limitations</td><td>Dated inspection scope, tested functions and unresolved findings</td><td>Define specialist review or replacement before the deadline</td></tr>
<tr><td>Safety disposition</td><td>Recall match, instructions and documented completed remedy where applicable</td><td>Do not advertise unavailable or unsafe equipment</td></tr>
<tr><td>Installed alternative</td><td>Named units, delivery/access, removal, connections and qualified work</td><td>Replace the equipment-only estimate with the complete scope</td></tr>
<tr><td>Seller treatment</td><td>Agreed repair, replacement, credit or exclusion and reviewer acceptance</td><td>Separate a contract promise from cash or completed work</td></tr>
<tr><td>Payment and opening</td><td>Order/deposit/balance dates, clearance and readiness verification</td><td>Fund bills before expected guest receipts</td></tr>
</tbody></table></div>
<p>Ask the installer to confirm dimensions, doorways, stairs and clearances, existing connections, delivery arrangements and any required qualified work. Obtain separately identified taxes, removal and disposal costs if they apply. Not every unit needs every item; the point is to reconcile the actual bid, not add a standard percentage to every property. Keep unresolved scope visible rather than assigning a precise useful life without support.</p>
<h2>Compare repair, replacement and credit on the same facts</h2>
<p>For seller work, identify the specific outcome, completion date and evidence the buyer's reviewers require. A receipt alone may not establish the agreed model or completed installation. For buyer work, establish delivery availability and a funded alternative if a required unit cannot be ready for the intended opening. Counsel determines contract rights, notice methods and available remedies; a missed date does not automatically authorize withholding funds or canceling.</p>
<p>The <a href="https://selling-guide.fanniemae.com/sel/b3-4.1-02/interested-party-contributions-ipcs">Fannie Mae interested-party-contribution guide</a> illustrates why a negotiated credit is not unrestricted buyer cash. For covered mortgages, it restricts using these contributions for down payment or required reserves, and distinguishes financing from sales concessions with underwriting consequences. This is that program's framework, not a rule for every DSCR or cash acquisition. Have the actual lender and closing team approve the disclosed treatment and revised cash requirements. Do not arrange an undisclosed side payment.</p>
<p>A price reduction may change the loan and buyer contribution rather than release the same dollar amount for an appliance invoice. A closing-cost credit may reduce an eligible settlement outflow without funding a pre-close deposit. A repair promise changes the work owner but does not eliminate verification. Compare these alternatives using the same scope, loan assumptions and payment dates.</p>
<h2>Worked cash comparison: the credit is not a second savings</h2>
<p>Hypothetical arithmetic only, not a client result, quote, approved loan or forecast. Assume $250,000 of cleared buyer funds. The initial acquisition plan allocates $230,000, including a $40,000 retained cash balance and $4,000 for appliance make-ready. That leaves $20,000 outside the planned allocation. The retained balance is not a recurring expense or another source to count twice.</p>
<p>A complete invented replacement bid is $9,000: $6,800 for equipment, $900 delivery and removal, $800 qualified connection work and $500 taxes. Replacing the included $4,000 estimate adds $5,000, bringing the allocation to $235,000 and leaving $15,000 outside it. Do not add all $9,000 on top of the earlier $4,000; that would count the same scope twice.</p>
<p>For a separate credit alternative, stipulate that the actual loan and closing reviewers accept a disclosed $3,000 seller credit solely against $3,000 of otherwise payable eligible closing costs already in the allocation. Under that invented condition, the $235,000 allocation becomes $232,000 and outside cash becomes $18,000. The credit is not another $3,000 check to add to buyer funds, and acceptance is not presumed for a real transaction.</p>
<p>Now assume a $2,000 appliance order deposit is due before that settlement reduction takes effect. Fund the deposit from existing buyer cash. It is part of the $9,000 bid, not an additional $2,000 capital cost. The payment schedule must show the deposit, remaining bid balance, settlement outflow and retained balance on their actual dates. A hypothetical $8,000 distinct opening-delay outflow would raise the credit-case allocation to $240,000, leaving $10,000 outside it; if $12,000 must remain outside this plan for another documented obligation, the stressed case is short by $2,000. Delay costs are stipulated separate bills, not gross lost revenue deducted again.</p>
<h2>Reconcile the final walk-through and opening handoff</h2>
<p>Before authorizing the purchase under the actual contract process, compare the on-site equipment identifiers, exclusions, substitutions and completed work with the agreed register. Obtain the reviewer acceptance needed for unresolved material findings. Preserve ordinary evidence without collecting seller passwords or unnecessary guest data. Keep manuals, service contacts, installation records and any accepted warranty-transfer confirmation in the agreed handoff file.</p>
<p>Set the manager's scope only after the purchase facts are settled: who confirms readiness, receives a fault report, can authorize a repair, and updates the advertised amenity when equipment is unavailable? That is a handoff requirement, not a reason to turn this buying guide into generic host tips. Do not promise a particular response time without an actual service arrangement.</p>
<p>Proceed when the agreed equipment and actual condition are understood, any safety issue has an acceptable documented disposition, the funded work fits the opening plan and the disclosed financing treatment is accepted. Reprice a viable transaction when verified scope changes. Delay using valid contract protection while decisive evidence is missing, or decline when the plan depends on unavailable equipment, unapproved credit or inaccessible cash. For <a href="/blog/buy-str-high-income-large-tax-bill/">buyers with high income or a large tax bill</a>, an estimated deduction does not replace these purchase funds.</p>
<p><a href="/apply/">Compare the shortlisted property with the completed equipment and cash register</a>. Use the <a href="/tools/first-str-purchase-budget/">total purchase-budget worksheet</a> and <a href="/blog/appliances-budget-short-term-rental/">appliance budget page</a> for the broader allocation. This refresh preserves those existing destinations rather than creating another package-buying URL.</p>
<p class="small">CPSC and Fannie Mae primary pages reviewed October 7, 2026; the Fannie Mae section is dated May 7, 2025, not a newly issued 2026 rule. Educational only, not inspection, installation, safety certification, lending, legal, tax or personalized investment advice. Every worked number is hypothetical. No approval, repair result, tax benefit, booking income or return is guaranteed.</p>'''
FAQ=[
('Do appliances shown in the STR listing automatically convey?','Do not assume that. Reconcile an identified equipment inventory with the actual purchase documents, exclusions and substitutions through the transaction professionals.'),
('Does a working appliance test establish remaining useful life?','No. Record the inspection scope and limitations, obtain qualified follow-up for material unresolved findings and price supported alternatives without inventing a remaining-life guarantee.'),
('Can a seller appliance credit pay my down payment or launch invoices?','Have the actual lender and closing team approve its disclosed treatment. A credit may reduce an eligible settlement outflow but is not automatically unrestricted cash or available before closing.'),
('How do I avoid counting appliance replacement twice?','Replace the included estimate with the complete installed bid. Track deposits within that bid, credits against the specific accepted outflow, retained cash separately and distinct delay bills only once.')]

if __name__=='__main__':
 source=(publisher.ROOT/'blog'/SLUG/'index.html').read_text()
 publisher.SLUG=SLUG
 publisher.TITLE=re.search(r'<title>(.*?)</title>',source)[1]
 publisher.H1=re.search(r'<h1>(.*?)</h1>',source)[1]
 publisher.DESC='Before buying a furnished STR, verify which appliances convey, price installed replacements and compare seller credits with a funded closing and opening plan.'
 publisher.BODY=BODY
 publisher.FAQ=FAQ
 publisher.main(expected_publication='2026-09-22',hub_attribute='data-appliance-acquisition-link',hub_paragraph='Compare <a href="/blog/appliances-buying-short-term-rental/">the appliance inventory, accepted seller treatment and dated replacement cash</a> before relying on a furnished STR package.')
 # The title is unchanged, so preserve the existing shorter HTML sitemap label.
 path=publisher.ROOT/'sitemap/index.html'
 s=path.read_text();s=re.sub(r'(<a href="/blog/'+SLUG+r'/">)[^<]+',lambda m:m[1]+publisher.H1,s);path.write_text(s)
