"""Scoped existing vendor-access acquisition guide; no new URL."""
from refresh_dscr_purchase_methods import refresh

BODY='''<p class="lead">Before buying an STR, verify that the buyer can control vendor access without depending on the seller's account or a permanent shared master code. A working keypad during a tour does not establish ownership of the app account, authority to revoke former workers, or a usable emergency entry path. Treat the access handoff as a dated purchase-readiness task with evidence, an authorized tester and a funded fallback.</p>
<p><a href="/apply/">Bring the access handoff register and opening cash budget to an acquisition call</a>. BNB Accelerator assists within its contracted scope; it does not certify lock security, administer your credentials or guarantee vendor response.</p>
<h2>Separate the equipment purchase from control of access</h2>
<p>Identify every relevant door, installed model, physical key, account owner and connected management system. Ask which hardware is included in the sale and which equipment, subscription or account belongs to a manager or vendor. Confirm the authorized transition process with the actual provider. Do not assume that acquiring the house transfers the seller's personal account, software license or integration.</p>
<p>For a manufacturer-specific example, <a href="https://www.schlage.com/en/home/smart-locks/encode.html">Schlage's Encode product page</a> describes customized access codes and lock history through its app. Those published features do not prove that this property's installed model, configuration or connected service supports every proposed vendor schedule. Request a demonstration using the actual system rather than infer capability from the brand.</p>
<p><a href="https://schlage-res.zendesk.com/hc/en-us/articles/38578821343252-How-to-Perform-a-Factory-Default-Reset">Schlage's factory-reset guidance</a> describes reset as a step for preparing a lock for new homeowners and warns that programmed codes are removed. This is not a universal transfer method. Follow the installed model's current instructions and account requirements with an authorized qualified person; plan the replacement access before disrupting an occupied property.</p>
<p>The <a href="/blog/smart-lock-inspection-short-term-rental/">equipment inspection guide</a> handles condition and door fit. This guide isolates buyer control, vendor permission and handoff acceptance. The <a href="/blog/backup-cleaner-str/">backup-cleaner register</a> separately establishes accepted service capacity: possession of an entry code does not mean someone accepted a cleaning job.</p>
<h2>Complete the buyer's access acceptance register</h2>
<div class="table-wrap"><table><thead><tr><th>Field</th><th>Evidence to request</th><th>Unresolved purchase consequence</th></tr></thead><tbody>
<tr><td>Included hardware</td><td>Door/model inventory, keys, sale inclusion and accepted condition</td><td>Price excluded or unsuitable equipment rather than assume it transfers</td></tr>
<tr><td>Account authority</td><td>Actual transfer/reset procedure, authorized owner and recovery contact</td><td>Buyer control remains unverified while the seller is the only administrator</td></tr>
<tr><td>Vendor permission</td><td>Named user, accepted task, allowed time window and revocation owner</td><td>A shared credential cannot isolate one former worker's permission</td></tr>
<tr><td>Connected systems</td><td>Manager/app/integration inventory and current buyer-side requirements</td><td>Old automations or subscriptions may need authorized reconfiguration</td></tr>
<tr><td>Failure and backup</td><td>Manufacturer-supported offline entry and authorized local response</td><td>A remote app alone is not demonstrated outage coverage</td></tr>
<tr><td>Acceptance</td><td>Dated test result, exceptions, corrective quote and opening approver</td><td>A pending test stays pending; do not mark it passed from a screenshot</td></tr>
</tbody></table></div>
<p>Keep secret values outside this register. Record that credentials were issued or revoked, not the credentials themselves. Use agreed secure channels for necessary account records; do not publish codes, keys, private guest information or recovery details in a listing, public worksheet or broadly shared contractor chat. Access history is evidence to interpret, not proof of identity or a security guarantee.</p>
<h2>Test the handoff under authorized conditions</h2>
<p>Agree with the seller and transaction professionals when testing and transition may occur. Do not reset locks, remove users or enter a property before authorization. Protect existing occupants and outstanding stays; ownership transfer and guest-arrival scheduling are different events. If the handoff cannot be completed before closing, document the funded post-closing task and approval needed before opening.</p>
<p>Have an authorized tester demonstrate the buyer's administration rights, issue a limited vendor credential, confirm its permitted use, then revoke it and verify the result on the actual system. Separately test the supported offline entry path without trapping occupants or defeating required egress. Record configuration, test date and exceptions. Do not assume changes propagate instantly through every connected app.</p>
<p>A vendor credential should match an accepted role and work window. A cleaner normally does not need account-owner authority merely to enter for a scheduled turnover. Assign the person who removes access when a worker leaves or the agreement ends. Review physical keys and other entry paths too: revoking an app user does not demonstrate that an old key can no longer open the door. Qualified local professionals determine appropriate hardware and safety work.</p>
<h2>Worked purchase comparison: keep or replace the installed system</h2>
<p>Hypothetical only, not actual contractor quotes, product prices or client results. A buyer has $260,000 spendable acquisition capital and $250,000 already allocated to down payment, closing, setup and a protected $35,000 reserve. That allocation includes a $500 access-handoff allowance. Unassigned margin is $10,000; the reserve is already inside the allocation, not additional spending money.</p>
<p>Assume a verified keep-and-reconfigure scope costs $350 for authorized account/setup work, $180 for distinct physical-key work and $120 for an acceptance test: $650 total. Replacing the existing $500 allowance adds $150, not $650. Total allocation becomes $250,150 and margin $9,850.</p>
<p>Assume a separately verified replacement scope costs $1,200 installed hardware, $250 account/integration setup and $150 acceptance testing: $1,600 total. Replacing the same allowance adds $1,100. Allocation becomes $251,100 and margin $8,900. The $950 difference is not proof that either system is safer or more reliable. Compare accepted capabilities, control and unresolved work before selecting the lower cost.</p>
<p>If a distinct $900 opening-delay bill becomes payable, the two allocations rise to $251,050 and $252,000, leaving $8,950 and $8,000. No lost-booking revenue, insurance reimbursement or seller credit is assumed. If an additional unrelated $8,500 repair is then required, margins become $450 and a $500 shortfall respectively without using the protected reserve. Obtain current complete quotes and place payments on their actual due dates in the <a href="/tools/first-str-purchase-budget/">purchase cash worksheet</a>.</p>
<h2>Decide from accepted control and affordable readiness</h2>
<p>Proceed when the buyer's control, vendor permissions, physical backup and acceptance plan are verified and funded. Reprice a viable purchase when equipment or transition costs change. Delay opening while decisive tests remain unresolved; counsel determines any transaction extension or remedy. Reject a plan that depends on unauthorized access, seller credentials or spending a reserve twice.</p>
<p><a href="/apply/">Discuss the candidate with a bounded access-readiness memo</a>: included equipment, authorized transition, accepted vendor roles, remaining tests and cash effect. The <a href="/blog/buy-str-high-income-large-tax-bill/">high-income buyer roadmap</a> connects this handoff to the broader acquisition. Substantial income does not resolve account control or make projected receipts available today.</p>
<p class="small">Schlage primary materials reviewed October 7, 2026. Model capabilities, instructions and provider terms may change. BNB Accelerator is the interested acquisition-service publisher; this is document-based educational analysis, not firsthand product testing or a security certification. Not legal, safety, insurance, tax or personalized investment advice. All numerical examples are hypothetical; no opening date, reimbursement or investment result is guaranteed.</p>'''

FAQ=[
('Does buying an STR transfer the seller\'s smart-lock account?', 'No transfer is assumed. Verify included equipment and the installed model\'s authorized account transition with the actual provider; do not rely on the seller\'s personal credentials.'),
('Should every vendor receive the master access code?', 'Use accepted role-specific permissions where the actual system supports them. Identify the person who issues, tests and revokes access, including physical keys and connected systems.'),
('Does a factory reset prove the property is ready to open?', 'No. Follow model-specific authorized instructions, re-establish required access and test buyer control, vendor permissions and supported backup before accepting readiness.'),
('How do access changes affect purchase cash?', 'Replace existing allowances with verified complete quotes, then add distinct costs once. Keep protected reserves separate and fund payments before their due dates.')]

if __name__=='__main__':
    refresh('vendor-smart-lock-access','STR Vendor Access: Verify the Purchase Handoff','How Should Vendors Access an STR Without Sharing Master Codes?', 'Before buying an STR, verify lock account control, vendor permissions and backup access. Compare handoff quotes without spending launch reserves twice.',BODY,FAQ,'2026-09-23','data-vendor-access-review-link','Verify the <a href="/blog/vendor-smart-lock-access/">vendor-access acceptance register and handoff cash comparison</a> before relying on seller accounts or an untested opening plan.')
