"""Scoped canonical broker/coordination comparison; preserve shared design."""
from pathlib import Path
import re
R=Path(__file__).resolve().parents[1]
p=R/'compare/avery-carl-short-term-shop/index.html';s=p.read_text()
assert '"datePublished": "2026-08-15"' in s and '"dateModified": "2026-10-01"' in s
s=s.replace('"dateModified": "2026-10-01"','"dateModified": "2026-10-07"')
s=s.replace('Do you want an STR specialist agent in a chosen market, or a team coordinating the acquisition and launch across several disciplines?', 'Compare specialist brokerage, training and vendor support with the acquisition coordination actually included in each proposal.')
s=s.replace('A specialist brokerage can be the right call when you have a market selected and want local representation while directing your own underwriting and launch.', 'The Short Term Shop can be a relevant route for STR-focused representation, with its published training and vendor support. Compare that actual package with BNB’s coordination scope; do not assume that brokerage means showings only or that coordination means every task is included.')
s=s.replace('<td>Sourcing, underwriting and purchase-to-launch coordination</td>', '<td>Published sourcing, underwriting and purchase-to-launch coordination, subject to signed scope</td>')
s=s.replace('<td>specialist STR brokerage</td>', '<td>STR-focused brokerage with publicly described post-closing training and vendor connections; verify actual inclusions</td>')
marker='<section class="section-sm"><div class="wrap wrap-narrow"><h2>Which option fits your first purchase?</h2>'
assert s.count(marker)==1
body='''<section class="section-sm"><div class="wrap wrap-narrow"><h2>Current evidence: representation is not the entire support package</h2>
<p>The Short Term Shop’s <a href="https://theshorttermshop.com/how-to-buy-a-short-term-rental/" rel="noopener noreferrer">March 11, 2026 buying guide</a> describes STR-specialized agents, local-use and HOA checks, vendor connections and systems/training after closing. That may suit a buyer who wants to learn operation with specialist representation. These public descriptions do not establish a particular agent’s deliverables, your training access, vendor availability or a paid launch-management obligation. Request the actual offer, including any additional memberships or services; absence of detail in this comparison does not prove the provider excludes the work.</p>
<p>BNB Accelerator’s <a href="/how-it-works/">published process</a> describes sourcing, underwriting, offer/inspection/closing coordination and designer/operator pairing. The buyer retains capital and final approval; lending, legal/tax conclusions and day-to-day operation remain with independent parties. An introduction is not a contracted vendor project. Require BNB’s signed scope too: this analysis has not authenticated either provider’s individual client agreement and does not promise financing, permission, income or tax benefits.</p>
<p>The <a href="https://www.nar.realtor/the-facts/consumer-guide-to-negotiating-written-buyer-agreements" rel="noopener noreferrer">NAR consumer guide</a> explains that agent services, compensation and agreement duration are negotiable. Changes and termination depend on the agreement and applicable law. Have the agent and counsel explain your actual document rather than treating a generic rule as a cancellation right or assuming seller payment covers the fee.</p>
</div></section><section class="section-sm"><div class="wrap wrap-narrow"><h2>Put two engagements on one deadline-and-authority sheet</h2>
<div class="bc-docs"><ol>
<li><strong>Representation:</strong> Record the licensed broker, geography, property coverage, duration, exclusivity and negotiated compensation. If you hire an acquisition coordinator as well, identify its role and any actual offset/referral arrangement. Do not assume a second service changes the first agreement.</li>
<li><strong>Property evidence:</strong> Ask both teams to walk through the same address, seller records, revenue assumptions and missing legal-use evidence. Name who obtains the municipal and HOA documents and who explains unresolved restrictions. Neither market familiarity nor a spreadsheet certifies permission.</li>
<li><strong>Inspection decision:</strong> Identify who revises the property budget, who submits a negotiated request, who monitors notice dates and who makes the buyer's final decision. The analysis team recommending rejection and the representative delivering a valid notice perform different tasks.</li>
<li><strong>Launch handoff:</strong> List training access, vendor introductions, contracted orders, spend approvals and work acceptance. Ask who acts when a suggested vendor cannot meet the opening date; do not assume a training resource is a project manager or that a coordinator runs the rental.</li>
<li><strong>Payment and failed-deal exposure:</strong> Record each fee recipient, trigger, exclusions and termination conditions. Separate possible broker compensation, third-party diligence bills, service fees and deposits. Confirm refund and release steps rather than presuming all cash immediately returns.</li>
</ol></div>
<p>Use the <a href="/guides/str-service-responsibility-matrix/">responsibility matrix</a> and <a href="/blog/str-buyer-agent-vs-acquisition-team/">buyer-agent versus acquisition-team guide</a>. A buyer already equipped to manage vendors may not need additional coordination; a time-constrained buyer should verify the proposed handoffs before paying for them. These are fit questions, not a claim about either firm's performance.</p>
</div></section><section class="section-sm"><div class="wrap wrap-narrow"><h2>Worked cash timing: credited earnest money versus a pending refund</h2>
<p><strong>Hypothetical arithmetic only—not either provider’s fee, local escrow rule or client result:</strong> Assume $320,000 spendable cash. A purchase needs $200,000 down payment, $16,000 distinct closing/service charges, $36,000 furnishings, $12,000 repairs and $40,000 retained operating cash. Total allocation is $304,000, leaving $16,000 outside the plan. The closing/service figure is a stipulated aggregate, not a published commission or actual quote.</p>
<p>For that same purchase, assume $20,000 earnest money is already paid and will be credited toward the $200,000 down payment at closing. The remaining down payment is $180,000. Remaining allocation is $180,000 + $16,000 + $36,000 + $12,000 + $40,000 = $284,000. With $300,000 cash outside escrow, the remaining margin is still $16,000. Adding the earnest money again to the original $304,000 would double-count it.</p>
<div class="bc-table-scroll" role="region" aria-label="Separate failed-deal cash timing example" tabindex="0"><table><thead><tr><th scope="col">Separate replacement-purchase case</th><th scope="col">Cash available now</th><th scope="col">Against $304,000 allocation</th></tr></thead><tbody>
<tr><th scope="row">$20,000 prior-deal refund pending, no other prior loss</th><td>$300,000</td><td>$4,000 short</td></tr>
<tr><th scope="row">Also $1,000 prior inspection spent, unreimbursed</th><td>$299,000</td><td>$5,000 short</td></tr>
<tr><th scope="row">After the assumed $20,000 refund clears, inspection remains spent</th><td>$319,000</td><td>$15,000 outside allocation</td></tr>
</tbody></table></div>
<p>This table is an alternative case, not another cost added to the first purchase. It assumes the first deal does not close and a documented refund is pending; it does not establish a legal entitlement or release date. The second property otherwise requires the same $304,000. A refund expected later cannot pay an earlier earnest-money or closing obligation. Do not credit the old deposit toward the new purchase unless the actual authorized transaction documents support that treatment. The $1,000 inspection is genuinely spent and not refunded in this example.</p>
<p>Record the money holder, required release documents, verified status, expected date and the next purchase deadline with your representative and counsel. Delay only within valid protection or secure an actually available funding plan. Do not remove the already assigned $40,000 reserve, presume an extension or treat a lender's approval as cleared cash. The <a href="/tools/first-str-purchase-budget/">purchase cash planner</a> supports the allocations; obtain transaction-specific advice for escrow and contract rights.</p>
</div></section><section class="section-sm"><div class="wrap wrap-narrow"><h2>Fair alternatives if the needed work remains unassigned</h2>
<p>For analysis or matching needs, compare the actual <a href="/compare/str-search/">STR Search proposal</a> or <a href="/compare/alternatives-to-str-insights/">STR Insights service tier</a>, then identify the representation and launch work still required. Do not assume these firms replace a local broker or deliver identical packages. The <a href="/compare/alternatives-to-the-short-term-shop/">Short Term Shop alternatives owner</a> examines broader buying paths and broker-compensation cash; this page focuses on the direct engagement and deposit-to-next-deal handoff. Continue through the <a href="/compare/">comparison hub</a> without turning vendor names into duplicate reviews.</p>
</div></section>'''
s=s.replace(marker,body+marker)
s=s.replace('Provider facts summarized from <a href="https://theshorttermshop.com/how-to-buy-a-short-term-rental/" rel="noopener noreferrer">The Short Term Shop’s public material</a>, reviewed 2026-10-01.', 'Document-based analysis of the linked Short Term Shop buying guide, NAR consumer guidance and BNB published scope, reviewed October 7, 2026. This is not firsthand testing, a verified customer-experience review or an evaluation of unseen client agreements.')
p.write_text(s)
p=R/'sitemap-core.xml';s=p.read_text();s,n=re.subn(r'(<loc>https://www.bnbaccelerator.com/compare/avery-carl-short-term-shop/</loc>\s*<lastmod>)[^<]+',lambda m:m[1]+'2026-10-07',s);assert n==1;p.write_text(s)
