"""One researched existing acquisition owner; no homepage generation."""
from refresh_dscr_purchase_methods import refresh
BODY='''<p class="lead">Selling one STR may reduce portfolio concentration when it removes a shared exposure you can no longer accept. It does not automatically make the next purchase safer or release enough cash to fund it. Before buying a replacement within the next six months, compare the remaining properties' downside, the contribution you give up, actual sale cash and the new address's obligations. Three homes exposed to the same coastal disruption do not lose that shared exposure simply because they have different street addresses.</p>
<p><a href="/apply/">Bring the remaining-portfolio and replacement-property comparison to an acquisition call</a>. BNB Accelerator assists within its contracted acquisition scope; independent advisers determine sale, lending, insurance, legal and tax conclusions. This is a decision worksheet, not an instruction to sell a particular property.</p>
<h2>Identify the exposure a sale would actually remove</h2>
<p>Begin with one defined disruption, not a property-count target: a permission restriction affecting several addresses, overlapping insurance hazards, the same demand season, one critical vendor or debt obligations arriving together. Use actual records and dated professional inputs. A recent weak month at one home does not demonstrate that it contributes most to shared downside; a stronger performer may carry more of the exposure you want to remove.</p>
<p><a href="https://www.investor.gov/introduction-investing/investing-basics/save-and-invest/diversify-your-investments">Investor.gov's general diversification guidance</a> says diversification does not guarantee protection from losses. It is general investor education, not a recommendation to own a particular number of STRs or buy in a specific market. Apply the question to actual obligations rather than inventing correlation coefficients, storm probabilities or claims that another city is immune.</p>
<div class="table-wrap"><table><thead><tr><th>Sale-review field</th><th>Evidence to request</th><th>Replacement purchase question</th></tr></thead><tbody>
<tr><td>Exposure removed</td><td>Addresses, common event, dated permission/insurance/debt facts</td><td>Does the next address recreate the same problem?</td></tr>
<tr><td>Contribution surrendered</td><td>Reconciled actual receipts and distinct operating/financing outflows</td><td>What supports bills after that contribution stops?</td></tr>
<tr><td>Settlement cash</td><td>Sale price scenario, payoff quote, sale charges and CPA provision</td><td>Which cleared funds can actually enter the purchase budget?</td></tr>
<tr><td>Transition obligations</td><td>Guest, manager, vendor and other unresolved contracts</td><td>Which obligations remain after the property changes hands?</td></tr>
<tr><td>Decision dates</td><td>Sale conditions, expected settlement, new earnest/closing/launch deadlines</td><td>What happens if the sale is late or does not close?</td></tr>
</tbody></table></div>
<p>Record unresolved facts and the independent person responsible for reviewing them. Do not assume a sale transfers permits, releases a guarantee or ends a management agreement. Obtain address-specific written conclusions. Keep private guest, owner and lender records in agreed secure channels. The <a href="/blog/str-sale-data-room/">sale data-room guide</a> is a separate records checklist, not proof of transfer rights.</p>
<h2>Compare peak cash reduction with contribution lost</h2>
<p>Hypothetical arithmetic only: a stipulated shared disruption requires $30,000 at property A, $24,000 at B and $36,000 at C, all additional cash needs over the same period. Holding all three requires $90,000. Assume C is sold before the event, all relevant C obligations are resolved and no C cash call remains with the seller. A and B still require $54,000, a $36,000 reduction. These are invented event inputs, not measured losses or a forecast.</p>
<p>Separately assume C contributed $14,000 over the prior year after the outflows included in that particular ledger. Selling it gives up that historical contribution; the amount is not promised future earnings and may omit tax or other items. A $36,000 one-event cash reduction and $14,000 annual contribution are different periods and measures. Subtracting them does not establish investment profit or prove the sale is worthwhile.</p>
<p>If a proposed replacement has a stipulated $30,000 need in the same disruption, the remaining A/B-plus-replacement case requires $84,000. The assumed reduction from the original $90,000 is now only $6,000. That does not establish the replacement is suitable: purchase/launch cash, normal operations and other events remain outside this stress. Review several separate disruptions without silently adding incompatible worst cases or treating hypothetical differences as probabilities. The <a href="/blog/str-portfolio-diversification/">next-property diversification register</a> addresses candidate selection; this guide isolates the decision to sell first.</p>
<h2>Calculate sale cash before allocating it to a new offer</h2>
<p><a href="https://www.irs.gov/publications/p551">IRS Publication 551</a> distinguishes tax basis from market value and explains basis adjustments, including depreciation allowed or allowable. Provide acquisition allocations, improvements, depreciation and other basis records to your CPA. A loan payoff is a cash settlement item, not adjusted tax basis. This worksheet does not compute taxable gain, recapture, suspended losses or a tax rate.</p>
<p>For a separate invented taxable-sale case, assume a $680,000 sale, $40,000 distinct sale charges, $420,000 loan payoff and $55,000 CPA-provision placeholder. The resulting cash is $165,000: $680,000 minus $40,000 minus $420,000 minus $55,000. The provision is an invented sensitivity input, not a tax estimate or a claim about cost segregation. Replace it and every other item with dated transaction evidence; subtract other actual obligations once.</p>
<p>Assume the buyer has $95,000 independently available outside household needs and all existing protected reserves. After this sale cash clears, available replacement capital would be $260,000. An invented replacement allocation of $180,000 down, $12,000 distinct closing charges, $28,000 launch work and $50,000 retained cash totals $270,000. The purchase is $10,000 short. Retained cash is not an expense or a spare source for concealing the gap.</p>
<p>If another $45,000 genuinely becomes available, the combined capital is $305,000 and the margin after the $270,000 allocation is $35,000. Do not assume that contribution, a future refund or a refinance exists. An exchange is a different transaction: restricted proceeds and asset-specific tax consequences cannot simply be treated as this taxable-sale cash. Use the <a href="/blog/1031-exchange-short-term-rental/">exchange guide</a> and <a href="/blog/cost-seg-timing-and-hold-period/">hold-period cash comparison</a> with qualified advisers before choosing that route.</p>
<h2>Test timing and the no-sale branch</h2>
<p>Until settlement, the projected $165,000 is not spendable. In a separate timing sensitivity, suppose $30,000 of additional, distinct holding outflows must be paid before the sale; the original $40,000 sale charges explicitly exclude them. The independent $95,000 falls to $65,000. Adding the same hypothetical $165,000 later leaves $230,000, now $40,000 short of the replacement allocation. This timing case is not combined with the earlier shared-disruption illustration; those were different assumptions.</p>
<p>List each early payment date and fallback before accepting a new obligation. If the sale does not close, set its receipt to zero and retain the actual existing-property liabilities. Do not sign a replacement contract on the assumption that an extension, cancellation right, lender bridge or sale proceeds will appear. Counsel and lenders must review the actual protections and financing, including ownership and guarantee terms.</p>
<p>Keep when holding fits the buyer's accepted downside and no independently supported replacement improves the decision. Sell only after reviewing exposure removed, lost contribution, transaction consequences and usable capital. Reprice, delay under valid protection or decline the replacement when the funded plan fails. A no-purchase interval can be a legitimate outcome, not a failure to deploy capital.</p>
<p><a href="/apply/">Review the replacement shortlist with a completed sale-and-cash memo</a>: event assumptions, remaining obligations, cleared funds, dated purchase outflows and unresolved adviser decisions. Continue with the <a href="/blog/buy-str-high-income-large-tax-bill/">high-income buyer roadmap</a>. A large salary or tax bill does not resolve concentration, make a sale certain or validate a weak acquisition.</p>
<p class="small">Primary sources reviewed October 7, 2026; IRS Publication 551 is the currently published December 2025 revision, not a newly issued 2026 publication. BNB Accelerator is the interested acquisition-service publisher; analysis is document-based, not firsthand transaction testing. Educational only, not legal, tax, lending or personalized investment advice. All examples are hypothetical. No sale, refund, financing, diversification benefit, replacement, profit or indexing is guaranteed.</p>'''
FAQ=[
('Does selling one STR automatically diversify the portfolio?', 'No. Identify the shared exposure removed, remaining obligations and any exposure recreated by the replacement. Property count or a different address does not establish risk reduction.'),
('Should I sell the weakest recent performer?', 'Not solely for that reason. Review shared downside, lost contribution, debt, sale charges, adviser-modeled taxes and replacement opportunities using comparable dates and evidence.'),
('Can projected sale equity fund the next STR now?', 'No. Calculate actual settlement cash after payoff, distinct charges, adviser provisions and unresolved obligations, then match cleared receipts to purchase deadlines. Projected sale cash is not an available balance.'),
('What if the sale closes late or no replacement clears the budget?', 'Use a separately funded fallback and actual contract/lender protections. Do not assume proceeds, extensions or refinancing. Delay or decline an unfunded replacement; keeping cash can be a legitimate outcome.')]
if __name__=='__main__':
 refresh('str-portfolio-concentration-sale','When Should You Sell One STR to Reduce Portfolio Concentration | BNB Accelerator','When Should You Sell One STR to Reduce Portfolio Concentration?','Before replacing an STR, compare shared downside removed, contribution lost, net sale cash and dated funding. Use a sale-versus-hold purchase worksheet.',BODY,FAQ,'2026-09-23','data-concentration-sale-review-link','Before committing replacement capital, use the <a href="/blog/str-portfolio-concentration-sale/">concentration-sale and dated-cash worksheet</a>. Selling one address does not automatically fund or de-risk the next purchase.')
