"""Existing appliance budget owner: dated funding, not a new package variant."""
import expand_hold_period as publisher
import re

SLUG='appliances-budget-short-term-rental'
BODY='''<p class="lead">An appliance budget for an STR purchase needs two schedules: what the equipment costs over the intended hold, and when cash must be available to pay it. A replacement reserve is money retained, not another equipment invoice. An annual allowance does not pay a deposit due next week. Before offering on a furnished property, reconcile identified appliances, installed bids, recurring costs and an independently funded replacement case with the rest of the acquisition budget.</p>
<p><a href="/apply/">Bring the dated appliance cash schedule to a BNB Accelerator acquisition call</a>. The goal is a supported property decision within our contracted scope, not a guaranteed equipment lifespan, efficiency saving or return.</p>
<h2>Set the scope without paying for the same package twice</h2>
<p>List the identified equipment expected to convey and the work needed before opening. Ask the appropriate professionals to establish ownership, actual condition, installation requirements and unresolved findings. The <a href="/blog/appliances-buying-short-term-rental/">appliance buying guide</a> handles the contract inventory, seller treatment and closing handoff; this page follows the resulting scope through a dated cost and funding schedule.</p>
<p>For each accepted bid, separate equipment, delivery and access, removal, taxes, required connections and qualified installation work. Record what is excluded, who pays and when a deposit and balance are due. A deposit within a complete bid is a payment timing item, not a second capital cost. Replace an earlier allowance with the accepted scope instead of adding the entire new invoice on top of it.</p>
<p>Keep optional upgrades separate from work required for the planned opening. An attractive appliance finish is not evidence of incremental bookings. Do not make a mandatory purchase affordable by silently spending cash already assigned to lender requirements, household obligations or a different property system. The <a href="/tools/first-str-purchase-budget/">complete purchase-budget worksheet</a> is the parent allocation; appliance spending is one component.</p>
<h2>Build a cost register and a separate funding register</h2>
<div class="table-wrap"><table><thead><tr><th>Budget line</th><th>Evidence and timing</th><th>Avoid this double count</th></tr></thead><tbody>
<tr><td>Initial installed scope</td><td>Identified units, accepted scope, exclusions, deposit and balance dates</td><td>Equipment invoice plus the same included installation or deposit again</td></tr>
<tr><td>Recurring use and service</td><td>Buyer-use assumptions, actual service terms and payment periods</td><td>All utility bills here and the same bills again in the property model</td></tr>
<tr><td>Replacement sensitivity</td><td>Condition evidence, qualified advice, current replacement scope and earlier/later cases</td><td>A reserve contribution treated as both expense and replacement invoice</td></tr>
<tr><td>Retained cash</td><td>Accessible balance, restrictions, chosen floor and replenishment dates</td><td>One balance allocated in full to several independent risks</td></tr>
<tr><td>Disruption case</td><td>Distinct repair or delay bills and supported operating changes</td><td>Gross lost bookings deducted again after revenue already decreased</td></tr>
</tbody></table></div>
<p>For each unit, record the source date and uncertainty rather than inventing a standard useful life. A general inspection, a warranty duration and a manufacturer's marketing claim do not establish when this property's equipment will fail. Model an earlier replacement as a sensitivity when the decision depends on timing. Qualified inspectors and service professionals determine their actual scope and conclusions; the budget is not an inspection or safety certification.</p>
<p>Show restricted and freely accessible funds separately. A lender may require evidence of reserves under its actual program, while the owner may choose an additional operating floor. Confirm the actual treatment with the lender rather than assuming one earmarked dollar meets every requirement and can also be immediately spent. An expected tax benefit, warranty reimbursement or future booking payment is not cleared acquisition cash.</p>
<h2>Use EnergyGuide estimates as comparisons, not promised STR savings</h2>
<p>The <a href="https://consumer.ftc.gov/articles/how-use-energyguide-label-shop-home-appliances">FTC's EnergyGuide explanation</a> says the label permits comparison with similar appliances. Its operating-cost estimate uses typical use and a national average energy price; actual cost depends on use and local energy price. Not every appliance has this label. Save the actual model information, but do not substitute a tag's annual dollar figure for this property's supported utility budget.</p>
<p>Reconcile the applicable local service terms and intended workload with the <a href="/blog/normalize-str-utility-bills/">utility normalization register</a>. If an accepted equipment change creates an incremental cost or saving, change the existing utility line by that difference once. Do not add the full label estimate on top of an unchanged baseline that already includes that appliance. Label unsupported differences as sensitivities, not measured consumption.</p>
<p>For an optional-upgrade illustration only, suppose one complete installed alternative costs $2,500 more and an unverified sensitivity assumes $100 less energy spending each year. Five years would recover only $500 of that premium before other differences, leaving $2,000 unrecovered by energy savings alone. That arithmetic is not a forecast of lifespan, tariffs, maintenance or revenue. A $100 assumed saving cannot justify a $2,500 premium merely because an efficiency badge is present; investigate the actual alternatives and other supported benefits.</p>
<h2>Worked five-year schedule: spending and retained cash differ</h2>
<p>Every number below is invented educational arithmetic, not a quote, client result, recommended reserve or failure forecast. Assume an accepted initial installed scope of $8,400, plus $6,000 of freely accessible cash specifically earmarked for this equipment plan. The initial allocation is $14,400, but only $8,400 is an initial equipment outflow. Assume a separate $1,200 contribution arrives at the beginning of each modeled year before that year's bills.</p>
<p>Stipulate $900 of annual recurring appliance-related outflows: $600 energy and $300 service. These amounts belong in the overall operating model once. Stipulate one $3,200 replacement invoice in year three, solely to test funding; it is not an estimated life or guaranteed future price. This simplified example omits other equipment, inflation, financing, taxes, all property revenue and other property outflows. It cannot establish adequate reserves for the whole investment.</p>
<div class="table-wrap"><table><thead><tr><th>Year</th><th>Cash before contribution</th><th>Contribution</th><th>Actual modeled outflows</th><th>Ending equipment cash</th></tr></thead><tbody>
<tr><td>1</td><td>$6,000</td><td>$1,200</td><td>$900</td><td>$6,300</td></tr>
<tr><td>2</td><td>$6,300</td><td>$1,200</td><td>$900</td><td>$6,600</td></tr>
<tr><td>3</td><td>$6,600</td><td>$1,200</td><td>$900 + $3,200</td><td>$3,700</td></tr>
<tr><td>4</td><td>$3,700</td><td>$1,200</td><td>$900</td><td>$4,000</td></tr>
<tr><td>5</td><td>$4,000</td><td>$1,200</td><td>$900</td><td>$4,300</td></tr>
</tbody></table></div>
<p>Total spending is $8,400 initial work + $4,500 recurring outflows + $3,200 replacement = $16,100. Total cash assigned is the initial $14,400 plus five $1,200 contributions = $20,400. The difference is the $4,300 remaining balance. Do not call all $20,400 an equipment expense and then subtract the $16,100 again. For return analysis, state the convention for invested capital and retained liquidity; this schedule is not an investment return calculation.</p>
<p>The $1,200 annual contribution averages $100 monthly, but an average is not a bank balance. If a real contribution depends on peak-season receipts arriving after an invoice, rearrange the rows to the actual dates and test the pre-receipt low point. Do not assume the household can make every contribution because its income is high. Confirm other commitments and the source of accessible funds.</p>
<h2>Stress an earlier bill before deciding the offer fits</h2>
<p>In a separate downside, assume a distinct $2,500 repair bill is paid in year two, without reducing the stipulated year-three replacement. Year two's ending balance becomes $4,100. After the next $1,200 contribution and $4,100 of year-three bills, it becomes $1,200. If the buyer chose a $2,000 equipment cash floor, that case misses it by $800. The floor is this hypothetical buyer's choice, not a lending rule or universal adequacy standard.</p>
<p>Replace this assumption if the actual repair eliminates, delays or duplicates part of the replacement scope; do not insist on both invoices regardless of evidence. If the repair must be paid before the scheduled contribution, test that earlier cash date too. Any warranty payment remains an uncertain later receipt until entitlement, amount and timing are supported; do not use it to fund today's bill.</p>
<p>Compare the corrected schedule with the full-property seasonal downside and other retained balances. This equipment worksheet should feed the <a href="/blog/str-cash-reserves-seasonality/">property-level reserve review</a>, not consume the same dollars again without showing the lower balance. A funded base case may still fail the buyer's downside or liquidity limits.</p>
<p>Proceed when the installed scope, recurring assumptions, dated payments and supported downside fit accessible funds. Reprice a viable purchase when verified equipment costs change the offer ceiling. Seek valid transaction protection while decisive facts are missing, or decline when the plan relies on inaccessible cash or unsupported savings. Counsel determines actual contract options; this worksheet does not authorize a buyer to withhold funds or cancel.</p>
<p><a href="/apply/">Compare the shortlisted STR with its complete dated equipment budget</a>. Bring the accepted scope, source dates, unresolved findings, retained balances and earlier-replacement case. For <a href="/blog/buy-str-high-income-large-tax-bill/">high-income buyers with a large tax bill</a>, independently fund the purchase rather than treating an estimated deduction as an equipment contribution. Keep seller records and financing documents in agreed secure channels.</p>
<p class="small">FTC primary guidance reviewed October 7, 2026; the page is dated August 2022, not newly issued 2026 guidance. Educational only, not inspection, engineering, installation, lending, legal, tax or personalized investment advice. All worked figures are hypothetical. No equipment life, reimbursement, efficiency saving, booking income, tax benefit or return is guaranteed.</p>'''
FAQ=[
('Is an appliance replacement reserve another expense?','No. Retained cash and later contributions fund modeled outflows. Show the actual invoice once and track the remaining accessible balance separately.'),
('Can an EnergyGuide label establish my STR appliance utility bill?','No. FTC guidance describes estimates based on typical use and a national average energy price. Support this property’s use and local service terms separately.'),
('How should I budget an earlier appliance repair?','Place the distinct bill on its actual payment date, reconcile whether it changes the replacement scope and test the resulting cash balance against your chosen floor.'),
('Can high income or an expected tax benefit replace the cash schedule?','No. Confirm accessible funds and dated contributions alongside other obligations. An estimated deduction or later receipt does not pay an invoice due earlier.')]

if __name__=='__main__':
 source=(publisher.ROOT/'blog'/SLUG/'index.html').read_text()
 publisher.SLUG=SLUG
 publisher.TITLE=re.search(r'<title>(.*?)</title>',source)[1]
 publisher.H1=re.search(r'<h1>(.*?)</h1>',source)[1]
 publisher.DESC='Budget appliances before buying an STR: compare installed costs, five-year spending, retained cash and an early-repair case without counting reserves twice.'
 publisher.BODY=BODY;publisher.FAQ=FAQ
 publisher.main(expected_publication='2026-09-22',hub_attribute='data-appliance-budget-link',hub_paragraph='Test <a href="/blog/appliances-budget-short-term-rental/">appliance spending, retained cash and the earlier-repair budget case</a> before allocating the same reserve to several purchase risks.')
 path=publisher.ROOT/'sitemap/index.html';s=path.read_text();s=re.sub(r'(<a href="/blog/'+SLUG+r'/">)[^<]+',lambda m:m[1]+publisher.H1,s);path.write_text(s)
