"""Scoped acquisition-to-operation handoff correction, not a new guide."""
import re
import expand_hold_period as page
page.SLUG='first-90-days-airbnb-launch'
page.TITLE='First 90 Days of an Airbnb Launch: Buyer Handoff Plan'
page.H1='The First 90 Days of an Airbnb Launch'
page.DESC='Before buying an STR, assign launch responsibilities, confirm readiness and test pricing costs. Use a 90-day handoff plan without buying reviews or promising rank.'
page.FAQ=[
('What should I do first after closing on a short-term rental?', 'Confirm possession, buyer-specific rental permission, effective coverage, safety and required work before hosting. Assign utilities, furnishing, access, cleaners and guest-response responsibilities with dated acceptance evidence; filing an application is not assumed approval.'),
('Should I discount my Airbnb when it first launches?', 'Not automatically. Compare the actual eligible promotion and net contribution with a no-discount case. Do not exchange discounts or refunds for reviews or assume a fixed number of discounted stays guarantees ranking or demand.'),
('When is a short-term rental considered placed in service?', 'IRS Publication 527 describes readiness and availability for the specific rental use, not simply purchase or first guest arrival. Keep dated evidence and have your CPA determine the facts, applicable asset treatment and usable tax effect.'),
('What should I track from the first day?', 'Track readiness evidence, available and booked nights, achieved rate after discounts, reservation obligations, dated receipts and outflows, retained cash, vendor issues and adviser-requested tax records. Keep the original acquisition assumptions for comparison.')]
page.BODY='''<p class="lead">Plan the first 90 days of an Airbnb launch before buying the property. The practical acquisition question is who will make the home ready, pay the remaining bills and accept responsibility for the first guests. Ninety days is a review window, not a universal launch timetable or a rule that fixes years of rankings. A high-income buyer should approve a documented handoff and a funded downside rather than rely on an assumed review boost or tax refund.</p>
<p><a href="/apply/">Bring the purchase candidate and written launch scope to an STR acquisition call</a>. Match every promise to the signed service scope. An acquisition firm, manager, furnishing provider and tax adviser have different roles; “done for you” is not a substitute for identifying the responsible party, fee and acceptance evidence.</p>
<h2 id="week1">Before the first stay: accept readiness, not a calendar target</h2>
<p>Start with possession and lawful access, required repairs and safety checks, buyer-specific permissions and insurance effective for the intended use. Then confirm installed furnishing, utilities, tested entry, cleaning coverage and truthful listing information. A delivered box is not an assembled bed; a permit application is not an issued approval. Do not open availability simply because a target day has arrived.</p>
<div class="table-wrap"><table><thead><tr><th>Handoff item</th><th>Assign before the offer</th><th>Accept before guest use</th></tr></thead><tbody>
<tr><td>Permission and coverage</td><td>Buyer, counsel/authority and insurer as applicable</td><td>Written applicable approvals and effective policy</td></tr>
<tr><td>Required work and inventory</td><td>Contractor/furnishing scope, buyer approval and payment dates</td><td>Verified completed work and installed inventory</td></tr>
<tr><td>Access and turnover</td><td>Manager or named operator; cleaner coverage and fallback</td><td>Tested arrival instructions and trial turnover</td></tr>
<tr><td>Listing and reservation handoff</td><td>Authorized account owner, operator and guest-obligation plan</td><td>Accurate photos, availability and responsibility for existing stays</td></tr>
<tr><td>Money and records</td><td>Buyer bookkeeping controls and adviser-requested evidence</td><td>Reconciled paid/committed costs, receipts and cash retained</td></tr>
</tbody></table></div>
<p>Enter a named owner and completion document beside each item. Confirm coverage for guest issues and emergency escalation in the actual management arrangement, including who can authorize repairs and at what spending limit. Do not invent a required number of cleaners or a universal minutes-to-response standard. Have a supported fallback if the assigned vendor cannot attend.</p>
<p>The <a href="/blog/str-purchase-to-launch-timeline/">purchase-to-launch dependency guide</a> handles opening delays; the <a href="/blog/future-reservations-at-closing/">future-reservations guide</a> handles existing guest obligations. Keep the acquisition timeline, guest responsibility and bank receipts distinct. The first stay is not automatically the first payout or the seller’s review history.</p>
<h2 id="week3">At the opening review: reconcile the quoted scope and cash</h2>
<p>Original hypothetical scope comparison, not provider pricing or a client result. Suppose an opening package is quoted at $18,000. The signed quote excludes $1,200 of required utility deposits, $900 of entry equipment/installation and $1,500 of a separately scoped initial deep clean. With no overlap, the complete known opening requirement is $21,600. These exclusions are acquisition funding facts, not later booking revenue.</p>
<p>If the buyer allocated only $20,000 to those opening items, the known shortfall is $1,600. A separate $12,000 operating cushion is intended to remain after opening. Using $1,600 from it leaves $10,400, not the original $12,000. Re-fund or revise the plan and record the changed retained amount; do not claim the quote includes excluded services or spend the same dollars twice. Closing equity, other settlement costs and household liquidity are outside this example and still require separate funding.</p>
<p>Mark each invoice paid, still committed or optional. Record its payer, due date and acceptance condition. Avoid nonrefundable preclosing purchases unless the buyer has accepted the failed-closing exposure and access/delivery arrangements. At handoff, distinguish delivered goods from accepted work and identify any remaining owner task before opening.</p>
<h2 id="reviews">During early stays: test pricing without purchasing reviews</h2>
<p><a href="https://www.airbnb.com/help/article/2673">Airbnb’s Reviews Policy</a> prohibits manipulating or pressuring reviews and exchanging reviews for something of value, including a discount or refund. Offer truthful service and address genuine issues. Do not condition compensation on a positive review, withdrawal or silence. A normal pricing promotion is not permission to buy reviews.</p>
<p><a href="https://www.airbnb.com/e/new-listing-promotion">Airbnb’s current new-listing promotion</a> is optional: a 20% discount for the next three bookings after activation on eligible listings. The cited page requires fewer than three existing bookings and Smart Pricing turned off, and says the offer does not stack with other discounts. Verify the actual settings and current eligibility. This is not a mandatory six-to-eight-booking strategy or a reduction applied to every night of three months. Do not use platform-wide promotional statistics as this property’s forecast.</p>
<p>Separate invented arithmetic: assume three two-night stays at a $400 base lodging rate. Six nights produce $2,400 before discount, or $1,920 after 20%. Assume a distinct 20% variable-outflow allowance on lodging receipts plus $100 cleaning outflow per stay, with no cleaning receipt in this example. Discounted contribution is $1,920 − $384 − $300 = $1,236 before fixed costs and debt. Without the discount, the same booked nights yield $2,400 − $480 − $300 = $1,620. The difference is $384, not the $480 gross discount alone.</p>
<p>These assumed percentages are not platform fee schedules. Actual fees, taxes, cleaning charges, discounts and stay lengths need their own treatment. The equal-booking comparison isolates price; it does not show whether either plan gets those bookings. Use supported alternative booking cases in the <a href="/blog/new-listing-ramp-underwriting/">monthly new-listing cash worksheet</a>. No discount guarantees reviews, search placement or future demand.</p>
<h2 id="track">At 30, 60 and 90 days: compare evidence with the acquisition plan</h2>
<p>Use these as optional review checkpoints after the actual opening, not promised stabilization dates. Preserve the original underwriting file. Compare available nights, achieved booked nights, rate after discounts, cancellations, required outflows and cleared receipts with the dated assumptions. Record unresolved vendor issues, repairs and the cash cushion actually remaining. A full calendar is not proof of paid occupancy; a booking is not cleared owner cash.</p>
<p>Keep a dated readiness file and adviser-requested records from the outset. <a href="https://www.irs.gov/publications/p527">IRS Publication 527</a> describes property placed in service when ready and available for its specific rental use. Its residential-rental example distinguishes purchase, readiness and a later actual tenant. This is not a universal furnishing/listing checklist that automatically settles every STR asset or deduction. Ask the CPA to determine applicable facts and tax treatment; closing, first revenue or a screenshot alone does not resolve it.</p>
<p>Records of guest stays, owner use, participation activities and invoices help professional review; they do not automatically establish a W-2 offset, building classification, deductible loss or refund. See the <a href="/blog/str-placed-in-service-date/">readiness-evidence note</a> and keep sensitive records in agreed secure channels. Continue funding the purchase independently of projected tax cash.</p>
<p>Before the offer, proceed only when the written handoff, complete funding and lawful readiness path fit the buyer’s constraints. Reprice missing scope, obtain valid extensions for unresolved evidence or decline a purchase requiring assumed guest cash or guarantees. After opening, repair the specific evidenced problem and update the model rather than quietly replacing the initial assumptions with the achieved result.</p>
<p><a href="/apply/">Review the property and launch responsibility register before committing capital</a>. BNB Accelerator assists within its contracted acquisition scope; independent operators, lenders, counsel, insurers and tax advisers retain their respective decisions. The <a href="/blog/buy-str-high-income-large-tax-bill/">high-income buyer roadmap</a> connects the wider purchase path.</p>
<p class="small">Primary sources checked October 7, 2026. IRS Publication 527 above is the currently published 2025 edition, not newly issued 2026 guidance. Educational information only, not personalized legal, tax, lending or investment advice. All figures are hypothetical. No opening date, review, ranking, booking, refund or return is guaranteed. My BnB Accelerator, LLC is an acquisition firm, not a CPA firm; AE Tax Advisors is an independent partner.</p>'''
if __name__=='__main__':
 page.main('2026-08-11','data-first-90-review-link','Before buying, use the <a href="/blog/first-90-days-airbnb-launch/">first-90-days responsibility register and scope/pricing cost checks</a>; a launch discount is not a purchased review or a guaranteed ranking benefit.')
 p=page.ROOT/'blog'/page.SLUG/'index.html';s=p.read_text()
 if '<span>Updated ' not in s:
  s=s.replace('<span>Published August 11, 2026</span>','<span>Published August 11, 2026</span><span>&middot;</span><span>Updated October 7, 2026</span>',1)
 else:s=re.sub(r'<span>Updated [^<]+</span>','<span>Updated October 7, 2026</span>',s,count=1)
 p.write_text(s)
