"""Refresh the existing pair's distinct rental-use decision, not a new blog."""
from pathlib import Path
import re
R=Path(__file__).resolve().parents[1]
BODY='''<section class="section-sm"><div class="wrap wrap-narrow"><h2>Buyer-fit answer from current primary materials</h2>
<p>Roofstock's <a href="https://www.roofstock.com/investor-services/acquisitions">acquisition page</a> separates individual homes powered by Stessa, scattered-site rental portfolios and build-to-rent communities. Its combined-team description includes a footnote limiting property and asset management counsel there to institutional customers. Its disclosure says agency is not assumed unless expressly specified by Roofstock Realty, LLC, and some partners may pay referral compensation. Determine the actual individual-home agreement rather than assuming every advertised service applies.</p>
<p><a href="https://rabbu.com/about">Rabbu's about page</a> distinguishes operating STR listings with seller-reported history from potential properties with projections. It describes STR tools, professional connections and optional search consultants through closing. Those descriptions identify possible service paths, not authenticated property receipts, an executed representation agreement or approval to rent the chosen address.</p>
<p>A rental-home discovery path can fit a buyer with the right intended use and an already staffed diligence team. An STR-focused screen can fit a buyer who needs candidate and comparable discovery. Neither proves that existing occupancy, possession, local use, financing, insurance or setup can meet the buyer's actual opening plan. This comparison does not label Roofstock LTR-only: the <a href="/blog/bnb-accelerator-vs-roofstock-str-buyer/">existing Roofstock acquisition-path guide</a> separately examines its STR operator arrangements. A company's broader capability does not establish acceptance for your address.</p>
<h2>Original work sample: one property, two rental-use cases</h2>
<p>Ask each actual adviser to complete these five rows for the same candidate and real decision deadline. Record evidence, named responsibility, payment trigger, exclusions and the buyer's acceptance. A platform estimate is not the final deliverable.</p>
<div class="table-scroll"><table><thead><tr><th>Decision</th><th>Existing rental-use case</th><th>Proposed STR case</th><th>Accept before offering</th></tr></thead><tbody>
<tr><td>Possession and use</td><td>Actual occupancy, lease and other continuing obligations</td><td>Lawful available access, independent permission evidence and unresolved conditions</td><td>Retained counsel reviews rights; do not assume a vacant delivery or tenant departure</td></tr>
<tr><td>Income evidence</td><td>Supported lease receipts, costs and covered period</td><td>Reconciled seller STR records or separately labeled forward estimate</td><td>Analyst explains different periods and assumptions, not a renamed rent figure</td></tr>
<tr><td>Representation and fees</td><td>Actual buyer agreement, payer and compensation recipient</td><td>Separate consultant/analysis engagement if needed</td><td>Buyer approves scope, offset if actually documented, and fees surviving a rejected property</td></tr>
<tr><td>Physical readiness</td><td>Condition, included assets and required work</td><td>Accepted furnishing, safety, insurance and operator requirements</td><td>Named reviewer prices excluded work and authorizes substitutions</td></tr>
<tr><td>Funding and decision rights</td><td>Current lender terms and dated acquisition outflows</td><td>No-STR delay cash and separately accepted operating budget</td><td>Buyer accepts risk; licensed representative handles valid notices under the actual agreement</td></tr>
</tbody></table></div>
<p>Test an adverse discovery: the home is affordable but the documented available possession date moves later. Ask who revises the acquisition cash file, who obtains appropriate legal review and who communicates before contractual protection expires. Do not assign zero carrying costs or count lease receipts the buyer has not verified and cannot access. The <a href="/blog/buy-tenant-occupied-property-for-str/">tenant-occupied purchase guide</a> addresses that separate diligence process; this provider work sample creates no eviction, termination or extension right. Keep private lease, guest and banking records in authorized secure channels.</p>
<h2>Worked cash comparison: a lower starting allocation can lose its margin</h2>
<p><strong>Hypothetical arithmetic only, not provider fees, possession forecasts, quotes or client results:</strong> assume $320,000 genuinely available. Candidate A's complete initial purchase, closing and setup plan allocates $285,000, including a protected $40,000 reserve. Stipulate three distinct exclusions: $18,000 of accepted conversion work, $4,000 of additional analysis/coordination and three months at $4,000 of net owner carrying obligations before STR operation. No rent or STR receipts are assumed in this defined delay input.</p>
<p>Additional allocation is $18,000 + $4,000 + $12,000 = $34,000. A therefore needs $319,000, leaving $1,000 outside the plan while preserving the assigned reserve. If the delay is six months instead, replace $12,000 with $24,000; do not add both periods. Allocation becomes $331,000, an $11,000 gap. A cheaper starting plan did not establish enough cash for the longer readiness path.</p>
<p>Candidate B has a separate stipulated $300,000 initial allocation including the same $40,000 reserve. Assume its accepted scope already includes the comparable conversion work and it needs only the distinct $4,000 analysis charge, with no further delay obligation in this limited case. Allocation is $304,000, leaving $16,000. These are conditional different-property examples, not an assertion that either platform supplies vacant or ready homes or that B produces better returns. If B also has an omitted delay, model it.</p>
<p>If A's $18,000 conversion work is already inside its $285,000 initial plan, exclude that duplicate addition: its three-month case is $301,000 with $19,000 remaining. Verify scope before ranking cash requirements. Check due dates and cleared funds with the <a href="/tools/first-str-purchase-budget/">purchase-budget worksheet</a>; retained reserves are allocated once, and projected bookings or a tax refund are not today's funding. None of these partial allocations measures investment profit or establishes adequate reserves.</p>
<h2>Fair alternatives and the decision before commitment</h2>
<p>For specialist transaction representation, investigate <a href="/compare/avery-carl-short-term-shop/">The Short Term Shop's actual local proposal</a>. For matching and analysis, investigate <a href="/compare/str-search/">STR Search's actual tier</a>; Rabbu's connected consultant may be the same route, so do not count two introductions as independent providers without checking. These are named research paths, not equivalent scopes, endorsements or rankings.</p>
<p>BNB Accelerator's <a href="/how-it-works/">published acquisition process</a> is another path to compare against the work sample; its signed scope, fees and exclusions govern. Proceed when the chosen team covers actual missing work and supported use, possession, financing and funded downside fit. Reprice a viable property or scope when verified obligations change; seek valid protection while decisive evidence remains unresolved. Reject a purchase thesis requiring assumed rights or unavailable cash. <a href="/apply/">Bring both rental-use cases and the dated cash bridge to an acquisition discussion</a>, and continue through the <a href="/compare/">crawlable comparison hub</a>.</p>
</div></section>'''
if __name__=='__main__':
 p=R/'compare/roofstock-vs-rabbu/index.html';s=p.read_text()
 assert '"datePublished": "2026-10-06"' in s
 marker='<section class="section-sm"><div class="wrap wrap-narrow"><h2>Compare evidence using one actual candidate</h2>'
 assert s.count(marker)==1
 if BODY not in s:
  assert '"dateModified": "2026-10-06"' in s
  s=s.replace(marker,BODY+marker)
 s=s.replace('"dateModified": "2026-10-06"','"dateModified": "2026-10-08"',1)
 s=s.replace('Reviewed 2026-10-06:','Reviewed October 8, 2026:',1)
 disclosure=' The two linked primary pages were reviewed; unseen signed agreements were not authenticated. This is document-based analysis, not firsthand testing, a customer-experience score or professional legal, tax, lending or investment advice. Worked cash figures are hypothetical.'
 s=s.replace(disclosure,'')
 s=s.replace('Provider statements describe published offers, not independently audited performance.','Provider statements describe published offers, not independently audited performance.'+disclosure,1)
 p.write_text(s)
 p=R/'sitemap-core.xml';s=p.read_text();s,n=re.subn(r'(<(?:ns0:)?loc>https://www.bnbaccelerator.com/compare/roofstock-vs-rabbu/</(?:ns0:)?loc>\s*<(?:ns0:)?lastmod>)[^<]+',lambda m:m[1]+'2026-10-08',s);assert n==1;p.write_text(s)
