"""Scoped existing hot-tub acquisition guide; no homepage generator."""
import re
import expand_hold_period as publisher
SLUG='hot-tub-buying-short-term-rental'
BODY='''<p class="lead">Buying a property with a hot tub means deciding what you actually acquire, what must be corrected before guests arrive and whether the purchase remains viable without the amenity. A functioning heater at a showing does not establish ownership, rental permission, safe installation, insurance acceptance or future cash requirements. For an STR purchase in the next zero to six months, resolve those different questions before relying on a seller's claimed booking premium.</p>
<p><a href="/apply/">Bring the property candidate and hot-tub purchase register to an acquisition call</a>. High income or an anticipated tax benefit does not remove the need to fund corrective work and retained reserves independently. This guide is an acquisition comparison, not an operating manual or a guarantee of returns.</p>
<h2>Identify exactly what conveys with the property</h2>
<p>Ask the transaction professionals to document the specific unit, accessories and included equipment in the appropriate purchase documents. Photograph the manufacturer label and serial number, cover, controls and surrounding installation. Establish whether equipment is owned, leased, financed, excluded or subject to another agreement. Do not assume a listing photograph or an appliance inventory transfers title or discharges another party's rights.</p>
<p>Request purchase and service records, actual warranty or service-contract terms, known repairs and the seller's disclosures. Identify whether transfer requires consent or a fee and whether intended rental use is eligible. Unknown age is not a verified remaining-life estimate; an active service relationship is not a promised contract for the buyer. Keep sensitive ownership and financial documents in agreed secure channels.</p>
<div class="table-wrap"><table><thead><tr><th>Purchase question</th><th>Evidence and responsible reviewer</th><th>Unresolved consequence</th></tr></thead><tbody>
<tr><td>Which equipment and accessories convey?</td><td>Identity photos, included-item schedule and transaction documents reviewed by the appropriate professional</td><td>Resolve exclusions and third-party interests, not just price</td></tr>
<tr><td>Can this installation serve the intended rental?</td><td>Applicable authority's requirements, approvals and specialist findings</td><td>Do not advertise or model use as permitted while unresolved</td></tr>
<tr><td>What condition and work are established?</td><td>Dated specialist report, test limitations and complete corrective bid</td><td>Separate repairable cost from unanswered safety questions</td></tr>
<tr><td>Who accepts and operates the risk?</td><td>Actual insurer response and proposed service/management scope</td><td>Obtain a usable plan rather than inheriting seller arrangements</td></tr>
<tr><td>How will the purchase be funded?</td><td>Buyer cash allocation, dated payments and independently supported reserve plan</td><td>Revise the offer or capital plan before committing</td></tr>
</tbody></table></div>
<h2>Separate condition, permission and health safeguards</h2>
<p>Use a qualified specialist for equipment, installation and electrical or structural questions within the person's actual scope. Record tests performed, access restrictions and items not assessed. A general home inspection is not assurance of all hot-tub risks or future performance. Ask what additional specialist review is needed when the purchase depends on a particular finding. The <a href="/blog/hot-tub-inspection-short-term-rental/">inspection owner guide</a> addresses the separate inspection question.</p>
<p>Ask the applicable building and health authorities which rules apply to this property's intended rental use, including any permit, barrier, operating or inspection requirements. Confirm relevant private restrictions and insurer conditions separately. This guide does not classify every STR hot tub as a residential or public facility. A missing approval cannot be cured in a spreadsheet by adding a larger reserve.</p>
<p><a href="https://www.cdc.gov/healthy-swimming/safety/what-you-can-do-to-stay-healthy-in-hot-tubs.html">CDC's hot-tub health guidance</a>, published May 20, 2025 and reviewed October 7, 2026, explains illness risks from contaminated water and recommends limits on temperature, disinfectant and pH. It prompts users to ask about testing, inspection results and trained weekend staff. Those recommendations show why a buyer needs a qualified operating plan; they do not certify a property, replace local rules or promise that all illness can be prevented.</p>
<p>If relocation or replacement is proposed, check the full footprint, access and utilities before accepting an equipment-only bid. The <a href="/blog/pool-hot-tub-utility-easement-before-buying-str/">easement and planned-installation guide</a> addresses that separate diligence question. Do not assume an existing location automatically authorizes a new one.</p>
<h2>Compare corrective treatments before negotiating</h2>
<p>Ask for a complete dated scope: equipment, delivery, removal, access, required installation work, approvals, taxes and startup as applicable. Separate required corrections from optional upgrades. Obtain written responsibility, completion evidence and reinspection arrangements through the appropriate professionals if the seller will perform work. A promised repair is not the same as accepted completion.</p>
<p>A negotiated price reduction, closing credit and seller-completed work have different cash and transaction effects. Confirm the actual lender and settlement treatment; a $12,000 price reduction does not necessarily produce $12,000 of usable contractor cash at closing. Do not rely on an unapproved credit, hoped-for claim payment, refinance or tax refund to bridge a bill.</p>
<h3>Worked purchase-capital comparison</h3>
<p>Independent hypothetical arithmetic only, not quotes, local prices, client results or a recommendation. Assume $300,000 of accessible buyer funds. A base acquisition-and-launch allocation of $255,000 excludes all hot-tub treatment and separately retained reserves. Preserve $30,000 for other property risks. Assume all necessary permission and safety questions are independently resolved for each feasible treatment; the arithmetic cannot establish those conclusions.</p>
<div class="table-wrap"><table><thead><tr><th>Stipulated feasible treatment</th><th>Assigned cash, counted once</th><th>Cash outside acquisition</th></tr></thead><tbody>
<tr><td>Keep and correct: $6,000 work plus $9,000 hot-tub reserve</td><td>$255,000 + $30,000 + $6,000 + $9,000 = $300,000</td><td>$0</td></tr>
<tr><td>Replace: $12,000 complete work plus $3,000 hot-tub reserve</td><td>$255,000 + $30,000 + $12,000 + $3,000 = $300,000</td><td>$0</td></tr>
<tr><td>Remove and make area safe: $4,000 complete work; no hot-tub reserve in this case</td><td>$255,000 + $30,000 + $4,000 = $289,000</td><td>$11,000</td></tr>
</tbody></table></div>
<p>If a separate household obligation requires $15,000 outside the property, the first two cases are $15,000 short and the removal case is $4,000 short. These cases assign a budget; retained reserves are still cash, not already-paid expenses. None meets that household constraint without a verified change or additional available capital. Reallocating the other $30,000 changes which risks remain funded rather than creating money.</p>
<p>The reserve amounts are deliberately chosen sensitivity inputs, not manufacturer life estimates or universal safe minimums. Replacement does not eliminate operating costs or all future failures. Use the <a href="/blog/hot-tub-replacement-reserve/">earlier-invoice funding worksheet</a> to test actual contribution timing. Obtain a removal scope that addresses disconnection, disposal, remaining surfaces and required approvals; do not treat removal as automatically allowed or cost-free.</p>
<h2>Underwrite the no-hot-tub alternative independently</h2>
<p>Do not assume removal preserves the seller's revenue, or that retaining the feature guarantees a premium. Use supported comparable evidence and matched periods, then test a no-uplift case with all ongoing hot-tub costs. If a removal case is feasible, model its own lodging receipts, operating scope and launch timing. The <a href="/blog/amenity-roi-ranking/">amenity contribution comparison</a> develops the separate incremental-return question.</p>
<p>Before closing, assign responsibility for water care, testing records, service coverage, guest instructions and escalation within a qualified plan. An untrained turnover cleaner should not silently inherit specialist duties. Confirm what happens if the feature is unavailable before launch, and remove unsupported listing promises. A purchase register cannot substitute for a site-specific safety procedure or insurer acceptance.</p>
<p>Proceed only when conveyed identity, decisive diligence, acceptable treatment, operating responsibility and funded downside fit the buyer's requirements. Negotiate verified costs within a still-viable purchase. Seek a properly documented extension or other protection when decisive evidence remains unavailable; ask advisers about the actual contractual options. Decline an amenity-dependent acquisition when safe permitted use or affordable treatment cannot be established.</p>
<p><a href="/apply/">Compare the shortlist using a completed purchase register</a>, the <a href="/blog/str-due-diligence-checklist/">broader diligence checklist</a> and the <a href="/blog/buy-str-high-income-large-tax-bill/">high-income buyer roadmap</a>. BNB Accelerator assists within its contracted acquisition scope. Independent transaction, lending, insurance, tax and specialist professionals retain their respective decisions.</p>
<p class="small">Primary health guidance reviewed October 7, 2026. Educational information only, not personalized investment, legal, lending, insurance, tax or health advice. All worked figures are hypothetical. No safety certification, permitted use, financing, tax benefit, booking premium or investment return is guaranteed.</p>'''
FAQ=[
('Does a seller photo prove the hot tub conveys?', 'No. Identify the specific equipment and accessories, establish ownership or third-party agreements and have the appropriate transaction professionals document what is included.'),
('Can a larger reserve solve missing hot-tub permission?', 'No. Permission, safety and insurer acceptance need their own evidence. A cash allowance does not establish that intended rental use is approved.'),
('Is a price reduction the same as cash for repairs?', 'Not necessarily. Verify the actual lender and settlement treatment and the separately available money needed when contractor bills become payable.'),
('Should a buyer compare removing the hot tub?', 'Yes, when removal is a feasible approved treatment. Obtain the complete scope and separately underwrite the no-hot-tub case; do not assume seller revenue or zero remaining costs.')]
if __name__=='__main__':
 publisher.SLUG=SLUG;publisher.H1='Buying a Property With Hot Tub'
 publisher.TITLE='Buying an STR With a Hot Tub: Purchase Decision Guide'
 publisher.DESC='Buying an STR with a hot tub? Verify what conveys, permissions, corrective work and retained cash. Compare keep, replace and removal before committing.'
 publisher.BODY=BODY;publisher.FAQ=FAQ
 si=publisher.ROOT/'sitemap/index.html';old_sitemap=si.read_text()
 publisher.main(expected_publication='2026-09-22',hub_attribute='data-hot-tub-buying-review-link',hub_paragraph='Before committing to a hot-tub property, reconcile <a href="/blog/hot-tub-buying-short-term-rental/">conveyed equipment, corrective treatment and separately retained buyer cash</a>. Permission and safety are separate gates.')
 p=publisher.ROOT/'blog'/SLUG/'index.html';s=p.read_text()
 if '<span>Updated October 7, 2026</span>' not in s:
  s,n=re.subn(re.escape('<span>Published September 22, 2026</span><span>&middot;</span>'),'<span>Published September 22, 2026</span><span>&middot;</span><span>Updated October 7, 2026</span><span>&middot;</span>',s,count=1);assert n==1
 p.write_text(s);si.write_text(old_sitemap)
