"""Scoped existing comparison; no provider-swapped new article."""
from pathlib import Path
import re
R=Path(__file__).resolve().parents[1]
p=R/'compare/the-short-term-shop-vs-str-search/index.html';s=p.read_text()
assert '"datePublished": "2026-10-06"' in s and '"dateModified": "2026-10-06"' in s
s=s.replace('"dateModified": "2026-10-06"','"dateModified": "2026-10-07"')
s=s.replace('The Short Term Shop provides STR-specialist brokerage and buyer education in vacation markets. Confirm local representation and any additional service scope.', 'The Short Term Shop describes local STR-specialist brokerage plus education, systems and vendor connections. Confirm the individual representation agreement and additional services; this is not necessarily a showings-only package.')
s=s.replace('STR Search markets property matching and data analysis, while distinguishing its work from a realtor’s transaction role.', 'STR Search markets property matching and analysis. Its published FAQ discusses a separate realtor role; confirm the actual service tier rather than assuming the matching engagement includes representation or launch execution.')
marker='<section class="section-sm"><div class="wrap wrap-narrow"><h2>Compare evidence using one actual candidate</h2>'
assert s.count(marker)==1
body='''<section class="section-sm"><div class="wrap wrap-narrow"><h2>Buyer-fit answer from current primary materials</h2>
<p>If your gap is local property representation, The Short Term Shop is a relevant proposal to evaluate. Its <a href="https://theshorttermshop.com/how-to-buy-a-short-term-rental/">March 11, 2026 buying guide</a> describes specialized agents, vendor connections and post-closing systems and training. If the gap is property screening and financial analysis, evaluate the actual STR Search matching proposal. Its <a href="https://strsearch.com/">current public site</a> describes matching and analysis but also disclaims guaranteed financial performance. Neither public description authenticates your individual engagement, fees, insurance, lender approval or lawful use.</p>
<p>You may need both roles, but first identify work already supplied. A brokerage can supply analysis and education; a matching team can offer additional coordination. Do not pay twice merely because the tasks have different labels. Ask each provider what it will actually deliver for your address and which exclusions remain. A recommendation, vendor introduction, model and executed project are different outputs. This is document-based analysis, not firsthand testing or a customer-experience score.</p>
<h2>Original combined-team proposal worksheet</h2>
<div class="table-scroll"><table><thead><tr><th>Issue</th><th>Representation proposal</th><th>Matching proposal</th><th>Buyer decision</th></tr></thead><tbody>
<tr><td>Deliverable and acceptance</td><td>Property coverage and transaction tasks in the written engagement</td><td>Candidate criteria, evidence file and revision responsibilities in the actual tier</td><td>Record who accepts each output and what remains unresolved</td></tr>
<tr><td>Payment trigger</td><td>Actual compensation terms, payer and any documented credit</td><td>Actual payment milestone and any contracted offset or additional invoice</td><td>Count separate obligations once; do not invent either provider's price</td></tr>
<tr><td>Exclusions and failed candidate</td><td>Contract notice, release and continuing representation terms</td><td>Re-search, revision, service-period and termination conditions</td><td>A rejected house does not automatically end either engagement</td></tr>
<tr><td>Decision rights</td><td>Who negotiates and sends authorized notices under the actual agreement</td><td>Who recommends or revises the analysis and reports missing evidence</td><td>Buyer approval and professional conclusions are not replaced by a spreadsheet</td></tr>
</tbody></table></div>
<p>Test a disagreement before offering: the analyst uses one revenue case while the representative supplies a different comparable set. Ask both to show source records, periods, fees and exclusions, then request a reconciled downside file. Name who updates the cash plan and who handles the real contract deadline. Do not let conflicting forecasts become silent approval. The <a href="/blog/assembling-a-comparable-set/">selection worksheet</a> and <a href="/guides/str-search-property-match-questions/">matching contract questions</a> support this work sample without assuming either firm must provide an uncontracted task.</p>
<h2>Worked cash test: a bundled task is not always a second invoice</h2>
<p><strong>Hypothetical arithmetic only, not published provider fees or a client result:</strong> suppose $280,000 is available. The complete acquisition plan allocates $150,000 down payment, $16,000 distinct closing and service costs, $34,000 setup, $15,000 repairs and $45,000 retained operating cash. Total allocation is $260,000, leaving $20,000 outside the plan. Treat the $16,000 as an invented aggregate, not a brokerage commission or STR Search quote.</p>
<p>A proposed $8,000 analysis/coordination task has two possible treatments. If it is an additional cash-paid invoice excluded from the $16,000, allocation becomes $268,000 and the margin is $12,000. If the same task is already included and paid within the $16,000, allocation remains $260,000 and the margin remains $20,000. Do not infer an offset, free service or transferable credit: obtain the written breakdown and payer confirmation.</p>
<p>Separately, an additional $14,000 repair finding produces $282,000 and a $2,000 gap in the incremental-invoice case, or $274,000 and a $6,000 margin in the included-task case. The repair is not counted in the original $15,000. Retained operating cash is assigned once and preserved. These totals do not establish profit, financing qualification or opening readiness; replace every invented figure with dated accepted obligations and account for any delay separately.</p>
<p>If paying for both roles leaves a material task uncovered or cash short, compare a genuinely available proposal rather than assume either fee disappears. Fair named alternatives include <a href="/compare/alternatives-to-str-insights/">STR Insights tiers</a> for the specific analysis/support needed and BNB Accelerator's <a href="/how-it-works/">contracted acquisition coordination</a>. Neither is declared superior or identical. Use the <a href="/compare/">crawlable comparison hub</a> and <a href="/tools/first-str-purchase-budget/">purchase budget</a>, then <a href="/apply/">discuss the responsibilities you need filled</a>. Signed scope and independent professional decisions govern; this worksheet creates no refund or cancellation rights.</p>
</div></section>'''
s=s.replace(marker,body+marker)
s=s.replace('Reviewed 2026-10-06:', 'Reviewed October 7, 2026:')
s=s.replace('Provider statements describe published offers, not independently audited performance.', 'Provider statements describe published offers, not independently audited performance. The linked March11 buying guide and current public sites were reviewed; unseen client contracts were not authenticated. This is document-based analysis, not firsthand testing or a review score. All cash figures are hypothetical.')
p.write_text(s)
p=R/'sitemap-core.xml';s=p.read_text();s,n=re.subn(r'(<loc>https://www.bnbaccelerator.com/compare/the-short-term-shop-vs-str-search/</loc>\s*<lastmod>)[^<]+',lambda m:m[1]+'2026-10-07',s);assert n==1;p.write_text(s)
