"""Existing review-transfer buyer owner only; no homepage/library generator."""
from refresh_dscr_purchase_methods import refresh
BODY = '''<p class="lead">Do not buy an STR as if the seller's Airbnb reviews automatically convey with the deed. A favorable review history can be evidence of past guest experience without being an asset the buyer can use. Before paying a goodwill premium, separate what physically transfers, what requires permission, and what the buyer's own operating case supports without inherited reviews. Substantial available capital does not make uncertain account continuity a sound acquisition assumption.</p>
<p><a href="/apply/">Bring the seller's claimed review premium and your independent launch case to an acquisition call</a>. BNB Accelerator assists within its contracted acquisition scope; Airbnb and independent transaction advisers determine their respective rules and approvals.</p>
<h2>Account ownership is not a furnishing or deed transfer</h2>
<p><a href="https://www.airbnb.com/help/article/1431">Airbnb's current account-transfer guidance</a> says account ownership cannot transfer to a different host and reservations cannot transfer to a new host or account. It distinguishes co-host designation from transfer and does not allow a trip-change request to hand reservation management to a new owner. Buying login credentials, retaining a manager or changing possession does not establish an exception.</p>
<p>Do not interpret a broker's promise that reviews will stay as platform approval. Identify the actual account owner, listing and proposed arrangement; ask Airbnb about the transaction before relying on continuity. Counsel should evaluate the sale documents, lawful operating arrangement and rights to use other assets. A platform response is not a permit, insurance acceptance or a management agreement for the buyer.</p>
<p>The seller's review history is not automatically buyer-owned goodwill merely because guests reviewed the same address. This guide does not promise review migration, a new-listing ranking, a retention percentage or a procedure to transfer an account. Model a buyer launch without inherited reviews unless actual permitted facts support the specific alternative; do not assume every unusual transaction has the same outcome.</p>
<h2>Use a goodwill-evidence worksheet before offering</h2>
<div class="table-wrap"><table><thead><tr><th>Claimed benefit</th><th>Evidence to request</th><th>Buyer treatment if unresolved</th></tr></thead><tbody>
<tr><td>Existing listing and reviews</td><td>Actual listing/account owner and platform answer for the proposed transaction</td><td>Do not price automatic review continuity</td></tr>
<tr><td>Past guest satisfaction</td><td>Dated review themes, service records and verified condition</td><td>Treat as historical evidence, not a future conversion forecast</td></tr>
<tr><td>Photos, name and website</td><td>Ownership, licenses and agreed permitted use of each asset</td><td>Budget replacement where buyer use is unsupported</td></tr>
<tr><td>Operator contribution</td><td>Actual buyer proposal, scope, cost and accepted service dates</td><td>Use buyer terms rather than the seller's relationship</td></tr>
<tr><td>Future stays and receipts</td><td>Stay-level lawful resolution, money recipient and dated obligations</td><td>Separate the booked-calendar decision from review goodwill</td></tr>
</tbody></table></div>
<p>Record the named reviewer, unresolved question and decision deadline beside each row. A favorable answer for one asset does not approve all the others. Permission to use seller-owned photographs would not establish ownership of account reviews. Likewise, a manager agreeing to serve the buyer would not prove that the seller's platform history becomes the buyer's history.</p>
<p>Read review themes alongside physical and operating diligence. Compliments about a view may describe an enduring property feature; comments about a specific host's responsiveness describe a service the buyer must separately arrange. Neither proves a measured causal effect on revenue. Do not convert a rating difference into a percentage revenue uplift without appropriate evidence, or accuse a seller of misconduct because continuity is unsupported.</p>
<h2>Compare the same property without assuming inherited reviews</h2>
<p>Build the buyer's own conservative opening case using permitted use, condition, supported comparable demand, actual fees, readiness and costs. Do not copy mature seller performance into the first buyer year solely because the historical rating is attractive. The <a href="/blog/seller-proforma-vs-trailing-revenue/">seller forecast bridge</a> tests each claimed improvement; the <a href="/blog/keep-str-manager-after-buying-property/">manager-retention comparison</a> isolates recurring service economics.</p>
<p>Keep review goodwill separate from the <a href="/blog/future-booking-calendar-value/">future-booking premium worksheet</a>. The calendar owner already compares permitted buyer receipts with a fresh-launch alternative. Do not count the same assumed booking advantage once as calendar value, again as review goodwill and again in an income-based price increase.</p>
<p>For an illustrative cash test, assume $300,000 accessible acquisition funds. A complete hypothetical purchase-and-launch allocation is $270,000, including $40,000 protected operational reserve and all originally modeled closing and setup items. It excludes a proposed $24,000 additional purchase outlay attributed by the seller to goodwill. The allocation is stipulated as cash for this exercise; a real financed price change needs the lender's actual cash calculation.</p>
<div class="table-wrap"><table><thead><tr><th>Invented scenario</th><th>Total allocation</th><th>Outside the allocation</th></tr></thead><tbody>
<tr><td>No separately paid goodwill premium</td><td>$270,000</td><td>$30,000 of accessible funds</td></tr>
<tr><td>Add $24,000 cash premium</td><td>$294,000</td><td>$6,000 of accessible funds</td></tr>
<tr><td>Premium plus $12,000 distinct launch-delay bills</td><td>$306,000</td><td>$6,000 funding gap</td></tr>
<tr><td>No premium plus those same delay bills</td><td>$282,000</td><td>$18,000 of accessible funds</td></tr>
</tbody></table></div>
<p>All amounts are invented, not an appraisal, provider quote, client result or estimate of what reviews are worth. The $12,000 stress represents additional actual cash bills excluded from the original allocation, not both lost gross revenue and invoices. Do not subtract the $40,000 reserve again or treat an allocation as an incurred expense. If a proposed goodwill amount is already included in the baseline, remove it before adding a separate premium. An expected tax refund or later guest payout is not today's cleared funding.</p>
<p>This worksheet tests liquidity exposure, not investment profit or a maximum valuation. The actual price must work under supported property economics and financing. A buyer could reject an unsupported goodwill premium while still accepting an otherwise useful physical property at a justified price.</p>
<h2>Make the decision before relying on continuity</h2>
<p>Proceed when the real estate, lawful operating path and independently supported buyer launch work at the price, without an unsupported review assumption. Reprice a viable purchase when replacement branding, operator terms or additional opening costs change the economics. Seek a delay only under valid contractual protection while a decisive platform or adviser answer remains outstanding. Reject a purchase that requires prohibited account transfer or unverified review-driven earnings to meet the buyer's requirements.</p>
<p>Keep authorized source records and platform responses in the private deal file. Use listing identifiers and redacted relevant evidence rather than guest names, passwords or public copies of seller documents. The <a href="/blog/str-sale-data-room/">seller-file acceptance index</a> helps retain current versions; the <a href="/blog/future-reservations-at-closing/">reservation-closing ledger</a> handles guest obligations independently.</p>
<p><a href="/apply/">Compare the acquisition shortlist with the no-inherited-reviews case and funded opening plan</a>. For <a href="/blog/buy-str-high-income-large-tax-bill/">high-income buyers</a>, keep tax suitability separate from an unsupported goodwill claim. BNB Accelerator is the publisher and interested acquisition-service provider. This is document-based educational analysis, not firsthand testing, a valuation certificate or professional approval of a particular transaction.</p>
<p class="small">Airbnb primary guidance reviewed October 7, 2026. Hypothetical figures are not property forecasts. Educational only, not legal, appraisal, tax, lending, privacy or personalized investment advice. No review continuity, account transfer, ranking, bookings, permit, tax benefit or return is guaranteed.</p>'''
FAQ = [
 ('Do Airbnb reviews automatically convey with a property sale?', 'Do not assume they do. Airbnb prohibits transfer of account ownership to a different host, and the deed does not establish review continuity. Ask the platform about the actual arrangement and model an independent buyer launch.'),
 ('Does keeping the seller’s manager prove I can use the reviews?', 'No. Manager service acceptance and platform account rules are separate questions. Confirm actual buyer terms, account ownership and the permitted operating plan before assigning value.'),
 ('Should I pay a separate premium for the seller’s review history?', 'Only a supported purchase case can justify the actual price. Treat reviews as historical evidence, test a no-inherited-reviews case and avoid counting the same booking benefit as both calendar and goodwill value.')
]
if __name__ == '__main__':
    refresh('airbnb-reviews-property-sale', 'Do Airbnb Reviews Transfer When You Sell the Property | BNB Accelerator', 'Do Airbnb Reviews Transfer When You Sell the Property?', 'Buying an STR? Verify account rules and claimed goodwill before pricing seller reviews. Use a no-inherited-reviews case and opening-cash comparison.', BODY, FAQ, '2026-09-23', 'data-review-transfer-review-link', 'Compare the <a href="/blog/airbnb-reviews-property-sale/">review-goodwill evidence worksheet and no-inherited-reviews cash test</a>. A favorable seller history is not automatic buyer account continuity.')
