"""Expand the existing maintenance owner; no new URL or homepage generation."""
from refresh_dscr_purchase_methods import refresh, publisher
BODY='''<p class="lead">Before buying an STR, require a maintenance SLA to distinguish acknowledgment, diagnosis, dispatch, attendance, containment and resolution. A contractor answering in ten minutes but arriving the next day has not delivered ten-minute onsite response. The purchase decision is whether this address has an accepted, affordable response arrangement for the proposed buyer—not whether the seller knows a handyman. Substantial capital or a large tax bill does not create local coverage.</p>
<p><a href="/apply/">Bring the actual maintenance proposal and readiness budget to an acquisition call</a>. BNB Accelerator assists within its contracted acquisition scope; ongoing repairs, response guarantees and property management are not assumed included.</p>
<h2>Price the clock that actually protects the property</h2>
<p>Define when each clock starts, what stops it, how elapsed time is recorded and which exceptions apply. Does acknowledgment mean a human accepts the job, or an automated message arrives? Does attendance mean a qualified person reaches this address, or a dispatch request is sent? Can containment occur without complete repair? Parts availability, specialist work and owner approval can change the resolution path even after someone attends.</p>
<p>Ask for separate paths for a lockout, loss of heat, active leak, major-appliance failure and cosmetic defect. These categories do not establish universal severity or acceptable response times. Agree on the actual property's conditions and escalation with competent professionals. For emergencies, follow appropriate emergency procedures and contact emergency services where needed; this worksheet is not a safety protocol or repair instruction.</p>
<p>Keep physical response separate from the <a href="/blog/after-hours-guest-support-cost/">remote guest-support pricing worksheet</a>. A messaging desk may notify someone without accepting repair work. Likewise, a <a href="/blog/backup-cleaner-str/">backup cleaner's accepted turnover</a> does not establish maintenance competence or attendance. Do not pay twice for one dispatch already included in another agreement.</p>
<h2>Use an accepted-address response register</h2>
<div class="table-wrap"><table><thead><tr><th>Purchase field</th><th>Evidence to request</th><th>Unresolved decision</th></tr></thead><tbody>
<tr><td>Address and severity</td><td>Buyer, service area, issue categories, competent trades and exclusions</td><td>Who has accepted this property rather than only an introduction?</td></tr>
<tr><td>Response clocks</td><td>Start/stop events for acknowledgment, dispatch, attendance, containment and resolution</td><td>Which event is actually promised and which is only an estimate?</td></tr>
<tr><td>Coverage window</td><td>Time zone, nights, holidays, unavailable periods and parts exceptions</td><td>What happens outside the accepted window?</td></tr>
<tr><td>Decision rights</td><td>Named approver, authorized scope, spending ceiling and escalation</td><td>Who decides when the buyer cannot answer?</td></tr>
<tr><td>Fees and remedies</td><td>Retainer purpose, callout, labor, parts, minimums, credits and cancellation terms</td><td>Does payment buy capacity, included work or only a discount?</td></tr>
<tr><td>Acceptance and records</td><td>Start date, access test, job record, completion approver and accepted backup</td><td>Who authorizes reopening when repair or inspection remains incomplete?</td></tr>
</tbody></table></div>
<p>Record each answer's source, date and reviewer. Obtain buyer-specific acceptance; do not presume the seller's agreement, deposit or relationship transfers. A vendor contact list is discovery evidence, not contracted coverage. Have the actual parties and qualified advisers review assignment, remedies, licensing, insurance and any mandatory obligations. A worksheet cannot certify those matters.</p>
<h2>Authorize the decision without giving unrestricted access</h2>
<p>Specify what a vendor can assess, contain and repair without further approval, plus who receives the record. A hypothetical $500 ceiling needs a definition: per event, invoice, visit or day; included taxes and materials; and treatment of further work. Splitting a larger job into smaller bills should not silently bypass the agreed approval. That number is an invented discussion input, not a recommended limit or a legal emergency exception.</p>
<p>Provide an alternate authorized decision-maker and an unavailable-owner branch. Ask what happens when nobody can accept attendance, an estimate exceeds authority or the specialist cannot source a part. Repair approval is separate from guest refunds, reservation changes and permission to reopen. Give only necessary authorized property access; use the <a href="/blog/vendor-smart-lock-access/">vendor-access handoff</a> rather than sharing seller passwords or permanent guest codes.</p>
<p>Run an agreed tabletop exercise before relying on coverage: trace a leak report from receipt through accepted attendance, authorized containment, further approval and documented completion. Arrange any physical test only with permission, an agreed price and protection for occupied stays. Do not fabricate an emergency. A successful exercise documents that test, not future reliability.</p>
<h2>Worked purchase comparison: retainer plus distinct work</h2>
<p>All numbers are invented, not vendor quotes, incident forecasts, market prices or client results. Suppose proposal A has a $1,200 annual retainer and three separately accepted incident invoices of $1,400, $1,800 and $900. Total modeled annual cash is $1,200 + $4,100 = $5,300. Proposal B has a $3,600 annual retainer and invoices of $900, $1,100 and $600: $3,600 + $2,600 = $6,200. B is $900 more under this stipulated workload.</p>
<p>For comparison only, stipulate identical work definitions and no retainer credits, taxes or additional minimums. Actual proposals may differ. Lower incident prices do not make B cheaper overall, and the cash difference does not establish equal attendance, competence or remedies. Read accepted coverage separately before selecting a price. The example assigns no monetary value to a claimed faster response and assumes no refund, insurance recovery or avoided damage.</p>
<p>Separate hypothetical launch allocation: $300,000 is genuinely available. Purchase, closing, setup and a protected $40,000 reserve together already require $288,000, leaving $12,000 unassigned. They exclude maintenance. If A's $1,200 retainer is payable before opening, allocation becomes $289,200 and margin $10,800. Earmarking another distinct $2,000 maintenance contingency raises allocation to $291,200 and leaves $8,800. The protected reserve is counted once, and earmarked money is not necessarily already spent.</p>
<p>If a verified, distinct $4,000 pre-opening repair arises outside both existing allowances, allocation becomes $295,200 and margin $4,800. If that work is instead covered by an existing allowance, reconcile the line rather than adding it again. Do not add the annual $4,100 incident scenario to this launch case automatically: its dates, workload and relationship to the contingency are not supplied. Use the <a href="/tools/first-str-purchase-budget/">dated purchase-budget worksheet</a>; these partial allocations do not establish adequate reserves or profit.</p>
<h2>Keep platform outcomes separate from contractor promises</h2>
<p><a href="https://www.airbnb.com/help/article/2868">Airbnb's rebooking and refund policy for homes</a>, effective February 6, 2025 and reviewed October 8, 2026, covers specified reservation issues, including failed access and certain advertised amenities that do not function. It states a 72-hour guest-reporting window after discovery and describes outcomes that depend on severity, impact and evidence. That reporting window is not a contractor response target or permission to postpone urgent action. It does not guarantee a particular refund or fund the buyer's repair budget.</p>
<p>Proceed when accepted physical coverage, decision rights, competent completion and independently funded costs fit the actual property plan. Reprice a viable acquisition when verified costs change. Seek valid transaction protection or delay opening while essential acceptance remains unresolved; counsel determines contract rights. Reject a rental-ready assumption dependent on unaccepted vendors or unavailable money.</p>
<p><a href="/apply/">Compare the shortlist with the completed response register and cash bridge</a>. Continue through the <a href="/blog/buy-str-high-income-large-tax-bill/">high-income acquisition roadmap</a>. BNB Accelerator is the interested acquisition-service publisher; this is document-based education, not firsthand vendor testing or a provider rating. Keep guest, seller and access records in authorized secure channels. Educational only, not legal, insurance, tax or personalized investment advice. Examples are hypothetical. No response time, repair, safety, opening, reimbursement, tax benefit or investment result is guaranteed.</p>'''
FAQ=[
('Does a ten-minute acknowledgment mean ten-minute onsite response?', 'No. Define acknowledgment, dispatch, attendance, containment and resolution separately, with start and stop events and accepted exceptions for this address.'),
('Does a maintenance retainer guarantee attendance?', 'Not by itself. Check what payment buys, the accepted address and windows, activation, exclusions, competent provider and actual contractual remedies.'),
('Who approves work when the STR buyer is unavailable?', 'Identify the authorized alternate, scope and spending limit in the actual arrangement. Repair approval, guest-refund authority and reopening decisions are separate duties.'),
('Is Airbnb’s guest-reporting window a contractor repair deadline?', 'No. A platform reporting rule is separate from accepted contractor response and safety procedures. Review both without assuming a refund, repair guarantee or funding.')]
if __name__=='__main__':
 publisher.DATE='2026-10-08'
 refresh('str-maintenance-response-sla','What Response Times Belong in an STR Maintenance SLA | BNB Accelerator','What Response Times Belong in an STR Maintenance SLA?','Before buying an STR, verify accepted maintenance response clocks, spending authority and exclusions. Compare fictional retainers and a dated launch cash bridge.',BODY,FAQ,'2026-09-23','data-maintenance-sla-review-link','Test the <a href="/blog/str-maintenance-response-sla/">accepted-address maintenance clocks, decision rights and launch cash bridge</a> before treating a candidate as rental-ready.')
 p=publisher.ROOT/'blog/str-maintenance-response-sla/index.html';p.write_text(p.read_text().replace('<span>Updated October 7, 2026</span>','<span>Updated October 8, 2026</span>',1))
