"""Develop the existing alternatives owner; preserve URLs, dates and design."""
from pathlib import Path
import re
ROOT=Path(__file__).resolve().parents[1]
p=ROOT/'compare/alternatives-to-str-search/index.html'
t=p.read_text();assert 'reviewed 2026-10-01' in t
t=t.replace('"dateModified": "2026-10-01"','"dateModified": "2026-10-07"')
marker='<section class="section-sm"><div class="wrap wrap-narrow"><h2>Choose before you sign</h2>'
assert t.count(marker)==1
body='''<section class="section-sm"><div class="wrap wrap-narrow"><h2>Compare a match promise with a purchase decision</h2>
<p>STR Search’s <a href="https://strsearch.com/" rel="noopener noreferrer">homepage</a> and <a href="https://go.strsearch.com/1" rel="noopener noreferrer">property-match page</a> advertise a 30-day matching promise. Their footers separately state that property financial performance is not guaranteed. Its <a href="https://strsearch.com/terms--conditions" rel="noopener noreferrer">public website terms</a> describe website use and broad service conditions. Do not treat these pages as the complete agreement for a paid search engagement. Ask for the current signed-package terms, eligibility conditions and remedy; this analysis does not determine enforceability or whether any customer qualifies.</p>
<p>That distinction applies to BNB Accelerator and every alternative. Delivering a candidate is not the same milestone as obtaining an acceptable inspection, financing the purchase or opening legally. Choose support by the decision still unresolved—not by counting properties presented.</p>
<div class="bc-docs"><h3>Use the same rejected-candidate test with each provider</h3><ol>
<li><strong>Search criteria:</strong> Give each team your maximum complete cash allocation, markets, intended use and financing constraints. Ask for a candidate memo that explains why an address qualifies, including evidence missing from the model.</li>
<li><strong>Model revision:</strong> Request a sample response to a higher insurance quote or inspection cost. Record who updates the offer ceiling and who decides that the candidate no longer fits. A gross-revenue estimate alone cannot settle that choice.</li>
<li><strong>Buyer acceptance:</strong> Identify the buyer’s approval step and the licensed representative. Ask whether rejecting a listing, losing an offer or terminating under a valid contingency changes the remaining search period or number of candidates.</li>
<li><strong>Fee exposure:</strong> Record the signing, matching, closing and launch payment triggers, plus cancellation, refund and restart conditions. Distinguish a possible contractual remedy from third-party diligence costs that may remain yours. No automatic refund or replacement search is assumed here.</li>
<li><strong>Purchase-to-launch handoff:</strong> Name the people monitoring contract dates, legal-use evidence, lender conditions, furnishing commitments and operator readiness. Record introductions separately from contracted execution and paid specialist work.</li>
</ol></div>
<p>For an analysis-led route, compare STR Search with the quoted <a href="/compare/alternatives-to-str-insights/">STR Insights service tier</a>. For a chosen-market representation route, investigate <a href="/compare/avery-carl-short-term-shop/">The Short Term Shop</a> plus any separately needed analyst or launch coordinator. For broader coordination, compare BNB Accelerator’s <a href="/how-it-works/">published process</a> with the actual signed scope. None of these labels proves a provider covers every task, and BNB does not replace your lender, attorney, tax adviser or day-to-day operator.</p>
</div></section><section class="section-sm"><div class="wrap wrap-narrow"><h2>Worked example: a rejected match can consume the next deal’s cash</h2>
<p><strong>Illustrative only—not a provider quotation, client outcome or prediction:</strong> A buyer has $300,000 available. The planned allocation is $175,000 down payment, $15,000 closing costs, $32,000 furnishing, $10,000 repairs, an invented $8,000 service fee and $40,000 retained reserves. Total: $280,000, leaving $20,000 outside the purchase allocation.</p>
<p>The first candidate fails a documented diligence requirement. The buyer has already spent $900 on an inspection and $700 on an appraisal, with no assumed reimbursement: $1,600 spent without buying the house. A second candidate otherwise has the same budget but needs $15,000 more repairs. The revised committed-and-spent capital is $280,000 + $1,600 + $15,000 = <strong>$296,600</strong>. Only <strong>$3,400</strong> remains outside the allocation. If the buyer must also retain $5,000 for an unrelated obligation, the plan is <strong>$1,600 short</strong>.</p>
<p>If the actual agreement instead adds a $6,000 restart charge, that separate alternative case reaches <strong>$302,600</strong>, exceeding the entire $300,000 by $2,600 before the unrelated obligation. These fictional fees describe neither STR Search nor BNB Accelerator. If no restart charge applies, do not add one; if any expense is reimbursed, document its timing before treating it as available cash.</p>
<p>The $40,000 reserve is already inside both allocations; do not subtract it again or silently spend it to make the candidate pass. Request a revised scope, funding plan or candidate rather than accept a failed cash gate because the search was fast. Keep the agent’s actual contract deadlines in view: a search-service period is not permission to miss an inspection or financing contingency. Use the <a href="/tools/first-str-purchase-budget/">purchase cash worksheet</a> for amounts and the <a href="/guides/str-search-property-match-questions/">property-match contract questions</a> to examine your chosen engagement.</p>
</div></section>'''
t=t.replace(marker,body+marker)
t=t.replace('Provider facts summarized from <a href="https://strsearch.com/" rel="noopener noreferrer">STR Search’s public material</a>, reviewed 2026-10-01.','Document-based analysis of STR Search’s linked homepage, property-match page and public website terms, reviewed 2026-10-07. This is not firsthand testing, a verified customer-experience review or an evaluation of an unseen client agreement. Advertised outcomes are not independently established here. Alternative-provider links lead to separate scope comparisons, not an assertion of identical services.')
p.write_text(t)
p=ROOT/'sitemap-core.xml';t=p.read_text()
t,n=re.subn(r'(<loc>https://www.bnbaccelerator.com/compare/alternatives-to-str-search/</loc>\s*<lastmod>)[^<]+(</lastmod>)',r'\g<1>2026-10-07\2',t);assert n==1;p.write_text(t)
