"""Scoped existing acquisition guide refresh, not a new 509 intent."""
from pathlib import Path
from refresh_dscr_purchase_methods import refresh

BODY='''<p class="lead">Before buying an STR for potential tax benefits, compare the work you can actually perform with the work an operator will do. Material participation is a tax determination, not a feature delivered by a co-host contract. A large salary, an expensive property or a cost-segregation estimate does not establish usable losses. Decide whether the purchase still fits your calendar and cash if the intended-year benefit is unavailable.</p>
<p>BNB Accelerator is an acquisition service provider and commercially interested publisher, not a CPA firm. This source-based guide is educational, not an individual tax opinion or client outcome. <a href="/apply/">Discuss the property shortlist with an operating plan and independently reviewed assumptions</a>. BNB's written scope governs acquisition assistance; an independent qualified adviser determines the tax analysis. AE Tax Advisors is an independent partner firm.</p>
<h2 id="why">Classification, participation and usable loss are different questions</h2>
<p><a href="https://www.irs.gov/publications/p925">IRS Publication 925 (2025)</a> explains that average customer use of seven days or less is an exception to rental-activity classification for passive-activity purposes. It is not an automatic wage offset. The publication also distinguishes active from material participation and describes basis, at-risk, passive-loss and excess-business-loss limits. Classification alone does not settle the return.</p>
<p>Ask your adviser to identify the actual activity, relevant tax year, ownership and personal-use facts, evidence required and remaining limits. Do not assume a depreciation estimate equals a refund or that every disallowed amount is permanently lost. The <a href="/blog/str-tax-benefit-shortfall-purchase/">smaller, delayed or absent benefit guide</a> handles the investment sensitivity; this page isolates the work plan that must be reviewed before relying on that estimate.</p>
<h2 id="tests">Review the applicable material-participation test, not a magic number</h2>
<p><a href="https://www.ecfr.gov/current/title-26/section-1.469-5T">26 CFR 1.469-5T</a> contains seven tests and additional conditions. Three distinct tests address more than 500 hours; substantially all participation; or more than 100 hours with participation at least equal to each other individual. Those are not interchangeable. Other tests and entity restrictions require separate review; this is not a complete eligibility checklist.</p>
<p>Identify which test the adviser considers applicable and what facts could invalidate the conclusion. Do not describe one route as universally easiest, most defensible or customary for BNB clients. A forecast of future work is not proof that the buyer performed it. Do not simply divide an annual threshold by the weeks left before year-end and treat that target as an available workload.</p>
<h2>Original buyer worksheet: separate availability, work and evidence</h2>
<p>Use one register for the actual address and operating proposal. Complete it before an offer depends on the tax case, and revisit it when the management scope changes. Its purpose is to reveal an unsupported assumption, not produce qualifying hours on demand.</p>
<div class="table-wrap"><table><thead><tr><th>Field</th><th>Evidence to bring</th><th>Acquisition question</th></tr></thead><tbody>
<tr><td>Activity and year</td><td>Proposed ownership, use, opening dependencies and adviser scope</td><td>Which facts must be resolved before relying on the illustration?</td></tr>
<tr><td>Owner availability</td><td>Work calendar, accepted responsibilities and realistic backup plan</td><td>Can the buyer execute the plan without unavailable time?</td></tr>
<tr><td>Actual work</td><td>Person, date, task, duration basis and supporting record</td><td>Is this performed work or only a future intention?</td></tr>
<tr><td>Outside participants</td><td>Named individuals and available task/time evidence</td><td>What is known, unknown or merely a firm-level total?</td></tr>
<tr><td>Review and change trigger</td><td>Adviser questions, responsible person and decision deadline</td><td>Does a scope change require a new operating and tax review?</td></tr>
</tbody></table></div>
<p>Unknown operator hours are not zero. A company invoice may establish expense but not hours for each individual. Ask for a permitted evidence process at engagement, without demanding unnecessary employee or guest personal information. Keep sensitive documents in authorized channels; the acquisition team needs the decision and unresolved conditions, not unrestricted tax-return access.</p>
<h2>Worked comparison: one narrow hours condition, not a tax opinion</h2>
<p><strong>Hypothetical, simplified arithmetic only:</strong> Assume an adviser has already accepted 120 hours as this owner's actual participation and considers the more-than-100-hours comparison relevant. Stipulate three other individuals with 110, 85 and 60 hours in the same activity and year. The largest individual figure is 110; the owner is 10 above it. The outside total is 255, not the individual comparator for this one condition.</p>
<p>If one individual's revised supported hours are 135, the owner is 15 below that individual. If the owner's 120 includes 25 hours the adviser excludes, only 95 remain—five below 100 and not more than 100. These alternative changes are not additional hours to stack into one case. Exactly 100 would also not be more than 100. This exercise does not establish the other facts, a complete test, usable loss, return treatment or any refund.</p>
<p>Do not cure the changed result with an invented 16-hour entry, a guessed cleaner schedule or a request that a vendor underreport work. Ask the adviser to reconsider the complete facts and other applicable tests. Operationally, decide whether a supported work plan still fits the buyer. Retaining more tasks can have real coverage and time costs; tax classification is not a reason to leave guests or repairs without a responder.</p>
<h2 id="log">Maintain useful records without claiming a guaranteed audit result</h2>
<p>The regulation permits reasonable proof; daily contemporaneous logs are not mandatory when participation can be established otherwise. Spousal participation can count even without joint filing or an ownership interest. Investor-only work is excluded unless connected to direct day-to-day management or operation.</p>
<p>As a practical recordkeeping choice, write down what actually happened near the event. State the work, person, date, duration basis and record supporting it. A platform message timestamp does not by itself prove three hours of work. A calendar reservation is not the same as a completed task. Mark estimated durations honestly, preserve corrections and ask the adviser about uncertain travel, preparatory work or overlapping entries instead of labeling all time eligible.</p>
<p>Review a small sample together: an invoice approval, a pricing change and a financial report. Explain whether each involved execution, supervision or investment monitoring, what evidence exists and whether time overlaps another entry. That conversation is more useful than a spreadsheet formatted to land on a preferred total. No worksheet, software or neat log guarantees acceptance.</p>
<h2 id="management">Buy a workable service scope, not a promised tax position</h2>
<p>Self-management, co-hosting and full-service proposals can assign different actual tasks. Read the agreement and permissions rather than assuming the title reserves pricing or guest communication to you. Neither outsourcing nor self-management automatically resolves every participation test. Have the adviser assess the selected scope before the acquisition budget depends on its tax result.</p>
<p>The <a href="/blog/cohosting-vs-self-managing/">work-split and time-versus-cash comparison</a> helps verify responder coverage; the <a href="/blog/str-property-management-fees/">fee register</a> reconciles actual charges. Confirm what BNB, the operator and the buyer each deliver. An introduction is not a signed operator commitment, and occasional approvals are not an individualized tax opinion.</p>
<h2>Keep the expected benefit out of the opening bank balance</h2>
<p>For a separate invented acquisition case, assume $300,000 accessible funds and $286,000 assigned to down payment, distinct closing/setup costs and $45,000 retained operating cash. That leaves $14,000 outside the plan. A hypothetical $30,000 future tax benefit does not make $330,000 available now.</p>
<p>Suppose the verified operating proposal would require another $18,000 in distinct cash before opening. The allocation becomes $304,000, a $4,000 gap. Do not add that invoice if it is already included, or count the retained $45,000 twice. Without the extra invoice, a smaller or absent benefit does not itself change the $286,000 opening allocation; it changes the separate after-tax investment case. Neither a later refund nor a spreadsheet time value pays an earlier invoice.</p>
<p>Reconcile payment dates, actual spendable funds and retained cash using the <a href="/tools/first-str-purchase-budget/">purchase budget</a>. Proceed only when the property economics, lawful use, operating coverage and available capital fit the buyer, with uncertain tax outcomes clearly labeled. Reprice supported costs or seek valid contractual protection while decisive facts are missing; decline a plan that requires unavailable time or a promised refund. <a href="/apply/">Bring the completed work register and no-benefit cash case to an acquisition discussion</a>. Continue through the <a href="/blog/buy-str-high-income-large-tax-bill/">high-income buyer roadmap</a>.</p>
<p class="small">Primary sources reviewed October 7, 2026: currently published IRS Publication 925 (2025) and eCFR 26 CFR 1.469-5T. Educational only, not tax, legal or personalized investment advice. All numerical scenarios are invented; no deduction, refund, audit acceptance, investment result or indexing is guaranteed.</p>'''
FAQ=[
 ('Is 100 hours automatically enough for STR material participation?', 'No. Identify the applicable test and have an independent adviser verify actual facts. The hours comparison shown here is only one condition, not proof of a usable loss or refund.'),
 ('Does hiring a property manager automatically eliminate an STR tax benefit?', 'No automatic conclusion follows from the service label. Review actual duties, evidence, the applicable test and other loss limits with an independent adviser before relying on an estimate.'),
 ('Does a neatly completed hours log guarantee qualification?', 'No. Records should describe real work and a supportable duration basis. A target total, software report or message timestamp alone does not establish eligibility or guaranteed audit acceptance.'),
 ('Should I add an expected tax refund to purchase cash?', 'Not unless actual funds are accessible and allocated. Test opening obligations against available cash separately from the adviser-supported tax illustration and a smaller or absent benefit case.')]

if __name__=='__main__':
 refresh('material-participation-str','STR Material Participation Before Buying | BNB Accelerator','Material Participation for Short-Term Rental Owners','Before buying an STR, review material participation evidence, actual operating work and cash without a tax benefit. Use original buyer worksheets.',BODY,FAQ,'2026-08-10','data-participation-review-link','Review the <a href="/blog/material-participation-str/">actual-work evidence register and no-benefit purchase-cash case</a>. An operating service label does not establish usable losses.')
 p=Path(__file__).resolve().parents[1]/'blog/material-participation-str/index.html'
 s=p.read_text()
 if 'Updated October 7, 2026' not in s:s=s.replace('<span>Published August 10, 2026</span>','<span>Published August 10, 2026</span><span>&middot;</span><span>Updated October 7, 2026</span>',1)
 p.write_text(s)
