"""Expand the existing utility purchase note, without library/homepage generation."""
import json,re
import expand_hold_period as publisher
SLUG='normalize-str-utility-bills'
TITLE='How Do You Normalize Utility Bills for an STR Purchase | BNB Accelerator'
H1='How Do You Normalize Utility Bills for an STR Purchase?'
DESC='Before buying an STR, reconcile utility bills, rates and buyer changes. Use a monthly worksheet and hypothetical seasonal cash test, not a seller average.'
FAQ=[
 ('Is a seller\'s monthly utility average enough for an STR offer?','No. Reconcile service periods, usage, charges and missing services over a seasonal cycle. Record seller occupancy and equipment conditions, then support the buyer\'s intended use separately.'),
 ('Can state electricity averages replace the property\'s tariff?','No. EIA average retail prices are not individual utility rates. Obtain the actual applicable service terms and charges for the buyer and address; a statistical average is only background.'),
 ('Should all STR utility cost disappear on vacant nights?','No. Identify fixed charges and ongoing equipment or seasonal needs separately. Occupied-night use, weather and equipment can interact; do not infer a reliable consumption model from a few bills.'),
 ('Should I add annual utility spending to the reserve twice?','No. Separate annual operating outflows, dated bills, retained liquidity, activation costs and deposits. A bill paid from a reserve reduces that cash balance; it is not a second copy of the annual expense.')
]
BODY='''<p class="lead">Before buying an STR, normalize utility bills by reconciling a seasonal record with the buyer's actual services, equipment and intended use. A seller's average can omit winter fuel deliveries, a separately paid internet account or months when the home was mostly empty. The purchase decision is whether supported recurring costs and dated early bills still fit the offer and available cash, not whether a generic utility percentage makes the spreadsheet attractive.</p>
<p><a href="/apply/">Bring the monthly utility register and acquisition budget to an STR purchase call</a>. BNB Accelerator can integrate supported costs within its agreement; service providers and qualified property professionals resolve account, equipment and technical questions.</p>
<h2>Reconcile the service record before annualizing it</h2>
<p>Request at least one complete seasonal cycle where available, including electricity, gas, water/sewer, propane or other delivered fuel, internet and buyer-paid services outside the seller's presentation. Identify the address, meter or delivery account, billing-period dates, consumption units and itemized charges. Redact account credentials and private personal information; arrange authorized records access rather than requesting a public account screenshot.</p>
<p>Make a missing-month list. A bank withdrawal may combine arrears, a deposit or a budget-plan payment rather than that month's consumption cost. Ask the provider or appropriate account holder to explain credits, corrections, estimated readings, delivery quantities, prepaid balances and settlement adjustments. Do not assume a seller's equal monthly payment is the property's level monthly usage.</p>
<p>Record the seller's occupied nights, owner stays, unavailable dates, significant equipment and documented weather or repair conditions for the same periods. Keep uncertainty visible. A low vacant-month bill does not establish the operating cost of your planned guest capacity. Conversely, a single high charge is not automatically a recurring annual expense. The <a href="/blog/seller-proforma-vs-trailing-revenue/">seller-projection reconciliation</a> addresses the revenue bridge; this worksheet isolates utility evidence and buyer adjustments.</p>
<h2>Confirm actual rates and buyer-paid services</h2>
<p>The <a href="https://www.eia.gov/tools/faqs/faq.php?id=507&amp;t=5">U.S. Energy Information Administration's electricity price FAQ</a> distinguishes published average retail prices from utility rates. Its averages include delivered-electricity costs and come from revenues divided by sales; individual rates depend on applicable service and customer circumstances. A state statistic cannot establish this property's bill or the buyer's tariff.</p>
<p>Ask the actual provider which service classification, fixed charges, consumption charges, time-dependent terms, taxes and other charges apply to the proposed ownership and use. Obtain dated written information and identify anything still unresolved. Do not assume a residential seller account establishes the buyer's account treatment, or invent a commercial reclassification from the mere existence of an STR listing.</p>
<p>Separate recurring service from refundable deposits, activation, connection or physical service work. Confirm the payer, amount, due date and actual refund conditions. A potentially refundable deposit is still unavailable cash while held; it is not assumed income. Existing equipment, a meter or apparent internet coverage does not certify available capacity or service activation by your opening date.</p>
<h2>Build twelve rows and a buyer-change register</h2>
<div class="table-wrap"><table><thead><tr><th>Monthly line</th><th>Evidence to preserve</th><th>Buyer adjustment</th></tr></thead><tbody>
<tr><td>Service period and quantity</td><td>Provider bill, reading or delivery record; days and units</td><td>Resolve missing or unequal periods before comparing totals</td></tr>
<tr><td>Fixed and usage charges</td><td>Actual applicable service terms and itemized charges</td><td>Reprice supported consumption when actual terms differ</td></tr>
<tr><td>Occupation and season</td><td>Same-period use calendar and documented conditions</td><td>Keep base, guest and seasonal components separate where supported</td></tr>
<tr><td>Equipment or amenity change</td><td>Actual scope, qualified assessment and operating plan</td><td>Add the distinct incremental cost, not a second full baseline</td></tr>
<tr><td>Omitted buyer service</td><td>Provider quote, responsibility and intended start date</td><td>Add only charges absent from the existing budget</td></tr>
<tr><td>Dated account cash</td><td>Deposit, activation and payment schedule</td><td>Separate early liquidity from annual operating expense</td></tr>
</tbody></table></div>
<p>Do not force a simple per-occupied-night model onto sparse observations. Heating or cooling, weather, equipment, turnover and guest use can overlap. Label unsupported adjustments as sensitivities, not measured consumption. Ask qualified professionals to investigate unexplained spikes or proposed equipment changes; a listing description does not prove efficiency or absence of a leak.</p>
<p>The <a href="/blog/pool-heating-cost-underwriting/">pool-heating contribution note</a> separately compares heating fees, take-up and incremental costs. Count its accepted incremental energy once in this utility budget, not again as the entire pool's recurring cost. Permission and service access are separate from bills; the <a href="/blog/pool-hot-tub-utility-easement-before-buying-str/">utility-easement guide</a> handles the proposed improvement's footprint. Tax allocation for personal use belongs with the CPA, not this operating-cost worksheet.</p>
<h2>Original monthly comparison: the same average can hide timing</h2>
<p>Invented arithmetic only, not a utility quote, typical property, weather forecast or client result. Suppose six available seller bills total $2,700. Annualizing that partial $450 monthly average produces $5,400, but it does not verify the omitted months. Assume a completed, buyer-reviewed energy case instead has the following twelve monthly inputs, including all energy service charges for this example:</p>
<div class="table-wrap"><table><thead><tr><th>Months</th><th>Each month's assumed energy cost</th><th>Three-month total</th></tr></thead><tbody>
<tr><td>January, February, March</td><td>$750, $750, $750</td><td>$2,250</td></tr>
<tr><td>April, May, June</td><td>$350, $350, $350</td><td>$1,050</td></tr>
<tr><td>July, August, September</td><td>$450, $450, $450</td><td>$1,350</td></tr>
<tr><td>October, November, December</td><td>$650, $650, $650</td><td>$1,950</td></tr>
</tbody></table></div>
<p>These inputs sum to $6,600, averaging $550 per month: $1,200 more than the unsupported annualization. A different property's $900 winter propane month would require its own delivery and consumption evidence, not substitution into this example. The table describes energy only, not every operating service.</p>
<p>Assume a separately paid internet service was absent from both energy and the buyer's other operating costs. At an invented $100 per month, add $1,200 once: $7,800 total. Now assume a changed amenity adds a supported $600 in the first quarter and no further incremental amount in this simplified case. Total becomes $8,400. These deliberately chosen amounts do not estimate actual take-up, consumption or amenity return.</p>
<p>If the earlier annual owner-cash model already included $5,400 utilities and showed $16,000 after all other modeled costs and debt, the $3,000 correction reduces it to $13,000, holding all other inputs constant. Subtract only the difference, not another $8,400. Rework revenue and other costs when the actual operating change affects them. The <a href="/blog/dscr-vacancy-factor-str/">lender-income note</a> explains why qualification inputs and owner economics need separate reviews.</p>
<h2>Check first-quarter bills without duplicating reserves</h2>
<p>The example's first quarter needs $2,250 energy, $300 internet and $600 incremental amenity cost: $3,150. One quarter of the annual $8,400 is only $2,100; that average allocation understates the dated quarter by $1,050. Build the actual payment dates and independently supported receipts rather than pretending an annual surplus is available every month.</p>
<p>For a separate purchase-cash illustration, assume $300,000 available: $220,000 purchase and closing, $30,000 setup and $40,000 retained liquidity total $290,000, leaving $10,000 outside the plan. Assume a distinct $800 refundable service deposit and $200 activation charge were omitted from setup. Add $1,000 once, giving $291,000 allocation and $9,000 outside. The deposit is cash held, not automatically a permanent expense or immediate refund.</p>
<p>If all $3,150 first-quarter bills are paid from the retained $40,000 before any modeled receipts replenish it, that cash balance becomes $36,850. These bills already belong in the annual $8,400; do not add another annual utility expense or pretend the reserve still equals $40,000. Establish whether the remaining liquidity meets the buyer's chosen floor. This example omits all other first-quarter flows and cannot certify adequate reserves. Use the <a href="/tools/first-str-purchase-budget/">purchase-budget worksheet</a> for the complete dated plan.</p>
<h2>Turn verified costs into an acquisition decision</h2>
<p>Proceed when the service record, actual buyer terms, equipment assumptions and funded monthly downside support the price. Reprice when supported recurring costs change the offer ceiling. Seek valid transaction protection while decisive bills or service confirmations are missing; decline a deal that depends on unexplained savings or unavailable cash. Counsel determines actual contract rights, not this worksheet.</p>
<p><a href="/apply/">Compare the STR shortlist with the completed utility register</a>. Keep bills, private seller records and lender documents in agreed secure channels. Use the <a href="/blog/buy-str-high-income-large-tax-bill/">high-income purchase roadmap</a> to connect these costs with the wider acquisition plan, not a presumed tax refund.</p>
<p class="small">EIA primary FAQ text reviewed October 7, 2026. No current tariff, rate, consumption norm or statistical price is quoted. Educational only, not engineering, utility, tax, lending, legal or personalized investment advice. All numerical examples are hypothetical. No efficiency saving, service approval, opening date, tax benefit or investment result is guaranteed.</p>'''
if __name__=='__main__':
 si=publisher.ROOT/'sitemap/index.html';old=si.read_text();label=re.search(r'(<a href="/blog/'+SLUG+r'/">)[^<]+',old)[0]
 publisher.SLUG,publisher.TITLE,publisher.H1=SLUG,TITLE,H1
 publisher.DESC,publisher.BODY,publisher.FAQ=DESC,BODY,FAQ
 publisher.main('2026-09-23','data-utility-normalization-review-link','Before accepting a seller average, review the <a href="/blog/normalize-str-utility-bills/">monthly utility register and seasonal purchase-cash comparison</a>. Annual expenses, dated bills and retained reserves are separate inputs.')
 si.write_text(re.sub(r'(<a href="/blog/'+SLUG+r'/">)[^<]+',lambda m:label,si.read_text()))
 p=publisher.ROOT/'blog'/SLUG/'index.html';s=p.read_text();assert 'FAQPage' not in s
 node={'@context':'https://schema.org','@type':'FAQPage','mainEntity':[{'@type':'Question','name':q,'acceptedAnswer':{'@type':'Answer','text':a}} for q,a in FAQ]}
 s=s.replace('</head>','<script type="application/ld+json">'+json.dumps(node,indent=2)+'</script>\n</head>',1)
 s=s.replace('<span>Updated October 6, 2026</span>','<span>Updated October 7, 2026</span>',1).replace('property="og:type" content="website"','property="og:type" content="article"',1)
 p.write_text(s)
