"""Existing first-property sequence decision; no new public intent or homepage generation."""
import re
from refresh_dscr_purchase_methods import refresh
from expand_hold_period import ROOT

BODY='''<p class="lead">Decide whether your first short-term rental must stand alone or also preserve the option to buy again. Planning a portfolio does not require committing to three properties today. The first purchase should work on its own supported economics, permission and funded downside, without a promised refund or next refinance. A later purchase is a separate approval, not the inevitable result of a large tax bill or successful closing.</p>
<p>For buyers considering an STR within the next six months, the practical comparison is one property with capital retained versus one property followed by a conditional next purchase. State the conditions for the second deal before approving the first. Buying both immediately is a different decision addressed in the <a href="/blog/buy-two-short-term-rentals-at-once/">two-simultaneous-acquisitions guide</a>; choosing another market is addressed in the <a href="/blog/str-portfolio-diversification/">shared-risk portfolio worksheet</a>.</p>
<h2>Make the first property viable without a second purchase</h2>
<p>Write the first property's offer ceiling, verified legal use, financing conditions, full closing and launch budget, operating downside and management responsibilities. Ask whether the buyer would still accept it if no other property were acquired. A first deal that only looks attractive when paired with speculative appreciation, a tax receipt or shared costs from future holdings has unresolved economics.</p>
<p>Learning can have value, but it is not a substitute for return or safety. Define which records and decisions you want to understand: actual bookings versus the forecast, expenses and capital work, permit obligations, operator performance and cash timing. Request authorized reporting and control from the proposed operator. The owner need not perform every task, and learning does not make otherwise unacceptable debt or permissions acceptable.</p>
<p>Do not buy a larger property merely to maximize a projected depreciation basis. Compare complete acquisition costs and your own capacity first. With <a href="/tools/first-str-purchase-budget/">the first-STR purchase-budget worksheet</a>, distinguish paid expenses, funds retained for the property and money available for a later offer. An operating reserve is not free second-purchase capital simply because it remains in the account.</p>
<h2>Use a second-purchase release register</h2>
<p>The following is an original planning work sample, not a lender's approval form or a prescribed waiting period. Replace each condition with a buyer-specific limit, dated evidence and a responsible reviewer. A calendar date alone cannot release capital when a decisive condition is still missing.</p>
<div class="table-wrap"><table><thead><tr><th>Gate</th><th>Evidence before another commitment</th><th>Stop or adjustment</th></tr></thead><tbody>
<tr><td>First property acceptance</td><td>Actual permission, completion records and unresolved work list</td><td>Resolve or separately fund material launch obligations</td></tr>
<tr><td>Operating evidence</td><td>Receipts, supported costs and monthly cash reconciliation</td><td>Re-underwrite a material forecast mismatch before reusing it</td></tr>
<tr><td>Capital release</td><td>Cleared funds minus protected obligations and dated commitments</td><td>Do not spend first-property reserves or uncleared receipts twice</td></tr>
<tr><td>Financing capacity</td><td>Lender review including current debt and intended next purchase</td><td>Replace an indicative plan with actual available terms</td></tr>
<tr><td>Responsibilities</td><td>Named operators, buyer workload and backup coverage for both</td><td>Delay if the same bottleneck leaves either property unsupported</td></tr>
</tbody></table></div>
<p>Set the review interval to the missing evidence, rather than a universal three-, six- or twelve-month rule. A few weeks of bookings may not represent a full seasonal pattern; several months of ownership may still leave important records missing. Conversely, a second candidate can be independently well-supported before the first completes a full operating year. The point is to disclose what remains assumed, not force every buyer onto the same timeline.</p>
<h2>Recheck financing rather than assuming a product switch</h2>
<p><a href="https://selling-guide.fanniemae.com/sel/b3-4.1-01/minimum-reserve-requirements">Fannie Mae's minimum-reserve guidance</a> describes requirements that vary with transaction characteristics and other financed properties. It also describes additional reserve calculations and specified simultaneous-application treatment. This is program guidance, not proof this buyer or STR qualifies. Ask the lender for the applicable asset and post-closing requirements using the actual ownership, debt and intended use.</p>
<p>Lender qualification and genuinely spendable cash are different tests. An asset that qualifies toward a lending requirement is not necessarily money available for a furniture bill. Similarly, the guide's simultaneous-application reserve treatment does not let the same dollars pay two closings. The <a href="/blog/str-lender-reserve-requirements/">reserve review owner</a> separates these purposes.</p>
<p>There is no automatic move from conventional to DSCR at the second or third property assumed here. Obtain actual eligible alternatives, rates, guarantees, fees, maturities and early-payoff conditions. Recalculate the first property's effect on the next financing file. A future loan or refinance is not committed liquidity; do not misrepresent intended occupancy to fit a product.</p>
<h2>Separate tax estimates from funds that have arrived</h2>
<p><a href="https://www.irs.gov/publications/p925">IRS Publication 925</a> describes the short-average-customer-use exception, material participation and multiple loss limitations. Meeting a use condition alone does not prove a deduction offsets W-2 income or creates a cash refund. Grouping depends on an appropriate economic unit and applicable restrictions, consistency and disclosures; property count does not create an automatic third-property election.</p>
<p>Ask the CPA for a supported estimate of usable tax effects and their timing, separately from an estimated deduction. Do not assume a study, high marginal rate or manager arrangement supplies the answer. The <a href="/blog/str-tax-benefit-shortfall-purchase/">smaller-or-delayed-benefit purchase guide</a> supplies a distinct downside test. A received tax benefit may increase available capital, but the purchase sequence must still work with the actual amount and other obligations.</p>
<h2>Worked sequence: a first-property bill changes the next offer</h2>
<p>All figures are invented, not a client outcome, market forecast, tax estimate or recommended budget. Assume $500,000 genuinely available for the investment plan after household and business needs are separately protected. The first purchase allocates $170,000 down, $12,000 closing costs, $18,000 launch work and $50,000 retained property cash: $250,000 total. That leaves $250,000 outside the first plan.</p>
<p>A hypothetical second purchase requires $145,000 down, $10,000 closing costs, $35,000 launch work and $40,000 retained cash: $230,000. The original sequential plan therefore leaves $20,000 unallocated. It does not establish adequate reserves, approved loans or profit. Dates matter: the second deposit and inspection can be due before its final financing is accepted.</p>
<div class="table-wrap"><table><thead><tr><th>Separate sequence case</th><th>Available for the $230,000 second plan</th><th>Result</th></tr></thead><tbody>
<tr><td>No additional first-property bill or tax receipt</td><td>$250,000</td><td>$20,000 margin</td></tr>
<tr><td>Additional $35,000 first-property work; no tax cash received</td><td>$215,000</td><td>$15,000 shortfall</td></tr>
<tr><td>Same work; only $10,000 hypothetical tax cash actually received</td><td>$225,000</td><td>$5,000 shortfall</td></tr>
<tr><td>Same work; $40,000 hypothetical tax cash actually received instead</td><td>$255,000</td><td>$25,000 margin</td></tr>
</tbody></table></div>
<p>The last two rows are alternatives: do not add the $10,000 and $40,000 together. The work is expressly additional to the first closing/launch allocation and is counted once. Both stated reserves remain protected in this comparison; any authorized draw must be shown as a different plan with lower retained liquidity. A $40,000 estimate that has not arrived leaves the buyer in the no-receipt case. None of these assumed receipts is a forecast of tax entitlement.</p>
<h2>Keep the choice to stop at one</h2>
<p>Buy again when the first property's unresolved obligations are funded, the next candidate independently clears diligence, lenders accept the combined plan and responsibilities fit the buyer's limits. Reprice a viable second candidate when actual costs change. Wait when evidence or cash is not ready; stop at one when another purchase does not improve the buyer's plan. Property count is not a performance metric.</p>
<p><a href="/apply/">Discuss a first-property shortlist with your conditional second-purchase register</a>. BNB Accelerator is the publisher and an interested acquisition-service provider; contracted scope determines its responsibilities. This is document-based planning support, not firsthand testing or an authenticated repeat-client statistic. Keep seller, guest, lender and tax records in agreed secure channels. Independent professionals determine lending, legal and tax conclusions; AE Tax Advisors is an independent partner firm.</p>
<p class="small">Primary sources reviewed October 7, 2026: currently published IRS925 is the 2025 edition; cited Fannie Mae topic is dated August 7, 2024. Educational only, not personalized investment, lending, tax or legal advice. All example figures are hypothetical. No repeat purchase, deduction, refund, financing, income or investment result is guaranteed.</p>'''

FAQ=[
('Should I buy one short-term rental or build a portfolio?', 'Compare one independently viable property with a conditional future purchase. Buy again only when funded obligations, actual financing, supported next-property economics and operating responsibilities fit your limits; stopping at one is valid.'),
('How should the first property differ if I plan to buy more?', 'It should work without another purchase and preserve capital, reporting and operating capacity for a later decision. Do not choose solely for a large depreciation estimate or an expected refund.'),
('What gets harder as a portfolio grows?', 'Combined financing, dated cash needs, shared exposure and operator capacity need review. Tax activity grouping and participation depend on facts; there is no automatic third-property election or required switch to DSCR assumed here.')]

if __name__=='__main__':
    original=(ROOT/'blog/one-property-or-three/index.html').read_text()
    keep=re.search(r'<div class="callout">\s*<h3>Keep reading</h3>.*?</div>',original,re.S)[0]
    refresh('one-property-or-three','One STR or a Portfolio? (2026)','Should You Buy One Property or Build Toward Three','Before buying your first STR, preserve the option to buy again. Compare release conditions and a second-purchase cash worksheet without promised refunds.',BODY+keep,FAQ,'2026-08-15','data-first-property-plan-review-link','Before the first offer, use the <a href="/blog/one-property-or-three/">conditional second-purchase register and cash worksheet</a>. An estimated refund is not committed capital for another property.')
