"""Expand an existing comparison owner; no new URLs or design changes."""
from pathlib import Path
import re
ROOT=Path(__file__).resolve().parents[1]
p=ROOT/'compare/alternatives-to-awning/index.html';t=p.read_text()
assert 'reviewed 2026-09-27' in t
t=t.replace('"dateModified": "2026-10-01"','"dateModified": "2026-10-07"')
marker='<section class="section-sm"><div class="wrap wrap-narrow"><h2>Choose before you sign</h2>'
assert t.count(marker)==1
body='''<section class="section-sm"><div class="wrap wrap-narrow"><h2>Compare the purchase relationship and the operating relationship separately</h2>
<p>Awning’s <a href="https://website.awning.com/vacation-rental-buying" rel="noopener noreferrer">buying page</a> describes brokerage-supported search and analysis alongside furnishing, design and management. It says brokerage commission funds its buying service. Its <a href="https://website.awning.com/airbnb-management" rel="noopener noreferrer">management page</a> describes operating services and property-dependent pricing. A connected path may reduce handoff work, but a buying-service advertisement does not establish that every launch expense is included or that you have accepted an operating contract.</p>
<p>The public pages display differing management starting percentages, including 10% and 15%. Treat these as advertising, not an address-specific quote or evidence of the fee you will receive. Request a dated proposal identifying the rate, revenue definition and exclusions. This comparison does not independently establish advertised revenue gains, ratings or customer outcomes.</p>
<div class="bc-docs"><h3>Your same-address proposal register</h3><ol>
<li><strong>Buying:</strong> Name the licensed representative and the contracting entity, brokerage compensation and who funds it. Record any relationship or referral incentive between the acquisition and management contacts. Ask whether either engagement depends on signing the other.</li>
<li><strong>Opening:</strong> Name who accepts furnishings, vendor bills, permits and readiness evidence. Record setup charges, payment dates and tasks excluded from the quotation. An introduction is different from paid execution.</li>
<li><strong>Operating:</strong> Identify the actual manager for this address, written availability, fee base, owner statement, repair-spend approval and escalation contact. Separate service coordination from the underlying cleaning or repair invoice.</li>
<li><strong>Control and exit:</strong> Document owner-use dates, price-setting authority, listing/account access, notice mechanics and existing-booking duties. Read the <a href="/blog/str-management-agreement-termination/">management exit guide</a>; do not presume accounts, reviews or guest records can transfer freely.</li>
</ol></div>
<p>Compare <a href="/compare/alternatives-to-the-short-term-shop/">specialist brokerage plus selected vendors</a>, the existing <a href="/guides/bnb-turnkey-management-handoff/">BNB Turnkey handoff questions</a>, and BNB Accelerator’s <a href="/how-it-works/">published acquisition process</a> against this register. They are different service paths, not identical packages. BNB’s actual signed scope governs its work; an independent operator, lender, attorney and tax adviser remain separate responsibilities unless the relevant agreement expressly establishes otherwise.</p>
</div></section><section class="section-sm"><div class="wrap wrap-narrow"><h2>Worked comparison: the lower percentage can have the larger fee</h2>
<p><strong>Invented illustration—not Awning or BNB prices, a forecast or a client outcome:</strong> Use the same property and $100,000 annual lodging receipts plus $20,000 separately collected cleaning fees. Assume cleaning invoices also total $20,000. Neither cleaning receipts nor occupancy taxes are extra lodging profit; this example excludes occupancy taxes entirely.</p>
<p>Fictional Proposal A charges 16% on lodging receipts plus cleaning fees: 16% × $120,000 = <strong>$19,200</strong>. Proposal B charges 18% on lodging receipts only: 18% × $100,000 = <strong>$18,000</strong>. With otherwise identical services and exclusions, B’s higher percentage costs <strong>$1,200 less annually</strong>. Under A, $120,000 receipts minus $20,000 cleaning invoices minus $19,200 management leaves $80,800. Under B the same calculation leaves $82,000. These are intermediate balances before platform fees, maintenance, utilities, insurance, taxes, debt service and other owner costs—not net income or investment returns.</p>
<p>Now separate acquisition cash. Suppose the down payment, closing costs, furnishings, repairs and retained reserves total $250,000 before an invented $7,000 acquisition charge. That gives <strong>$257,000</strong> upfront. If a fictional management proposal separately requires $3,000 opening work not included in the base budget, upfront capital becomes <strong>$260,000</strong>. Do not add it again if it was already included in furnishings or closing costs. Ongoing management charges belong in the operating forecast rather than being silently treated as covered by the acquisition fee.</p>
<p>Request the same fictional statement format using your actual quotes. Test lower lodging receipts and actual opening delays without assuming a provider improves revenue enough to offset its fee. Choose the combination that fits your funded acquisition and operating plan, not the lowest advertised percentage. Use the <a href="/tools/first-str-purchase-budget/">purchase cash worksheet</a> and a separate recurring-expense model.</p>
</div></section>'''
t=t.replace(marker,body+marker)
t=t.replace('Provider facts summarized from <a href="https://awning.com/vacation-rental-buying" rel="noopener noreferrer">Awning’s public material</a>, reviewed 2026-09-27.','Document-based analysis of the linked Awning buying and management materials, reviewed 2026-10-07. This is not firsthand testing, a verified customer-experience review or analysis of an unseen executed agreement.')
p.write_text(t)
p=ROOT/'sitemap-core.xml';t=p.read_text()
t,n=re.subn(r'(<loc>https://www.bnbaccelerator.com/compare/alternatives-to-awning/</loc>\s*<lastmod>)[^<]+(</lastmod>)',r'\g<1>2026-10-07\2',t);assert n==1;p.write_text(t)
