"""Scoped existing fallback guide refresh; never invokes the library generator."""
from refresh_dscr_purchase_methods import refresh

BODY = '''<p class="lead">Underwrite a long-term-rental fallback as a separate business plan before buying the STR. Verify achievable lease rent, permitted use, owner-paid costs and the cash needed to reach the first collected payment. A lower revenue number alone does not tell you whether the fallback can support the purchase.</p>
<p><strong>Decision in brief:</strong> a property can show a small positive stabilized annual lease surplus and still consume substantial cash during conversion. Accept the fallback only when its evidence, restrictions and dated cash needs fit your available capital without using protected reserves or an assumed tax refund.</p>
<h2 id="evidence">Five items to put in the acquisition file</h2>
<p>Ask the local leasing professional, lender, insurer and appropriate legal advisers for address-specific answers. This is a buyer-created acceptance register, not a promise that a particular professional or BNB Accelerator supplies every item.</p>
<div class="table-wrap"><table><thead><tr><th>Decision</th><th>Evidence to request</th><th>Acceptance check before the offer becomes nonrefundable</th></tr></thead><tbody>
<tr><td>Lease rent and demand</td><td>Dated nearby signed-lease evidence when obtainable, current competing listings, concessions, lease length and unfurnished versus furnished terms</td><td>Adjust for bedrooms, condition, location and included services; an asking rent is not a collected rent</td></tr>
<tr><td>Permission and financing</td><td>Written review of applicable local/HOA restrictions, mortgage conditions and insurance terms</td><td>Identify who confirms the proposed use, unresolved conditions and the decision deadline; an STR problem does not automatically authorize another use</td></tr>
<tr><td>Owner expense stack</td><td>Actual payment schedule, tax/insurance estimates, HOA, utilities, maintenance allowance and leasing/management quote</td><td>Separate fixed costs, collected-rent fees, one-time charges and future replacements; avoid counting escrowed taxes twice</td></tr>
<tr><td>Conversion work</td><td>Furniture inventory, removal/storage bids, repair scope, leasing preparation and existing reservation obligations</td><td>Record cost, payer and completion date; do not assume furniture can be sold immediately at its original retail cost</td></tr>
<tr><td>Time and cash</td><td>Earliest realistic possession, work, listing, lease signing and first-payment dates</td><td>Fund a slower no-rent case and preserve your minimum cash floor; a signed lease is not yet a receipt</td></tr>
</tbody></table></div>
<p>Keep an evidence status beside each field: received and usable, received but mismatched, or missing. If the fallback is essential to your purchase ceiling, unresolved permission or rent support is a condition to resolve—not a blank cell to fill with optimism. See the <a href="/guides/str-market-analysis-report/">market-report acceptance worksheet</a> for assessing a report rather than its headline projection.</p>
<h2 id="cash">Worked example: stabilized surplus versus first-year cash</h2>
<p><strong>Hypothetical only:</strong> these are stipulated inputs, not local rents, lender terms, manager prices, a client result or a forecast. The analysis starts when conversion begins after possession. Acquisition down payment and closing cash must be funded separately; this is not a complete purchase budget.</p>
<ul><li>Monthly collected lease rent: $3,500 once occupied. The base conversion case has three full months with no rent and nine months collected within the 12-month window.</li><li>Monthly mortgage principal/interest, property taxes, insurance and HOA combined: $2,500. Other owner-paid fixed costs: $300 monthly. Confirm the actual components so nothing is omitted or duplicated.</li><li>Maintenance allowance: $2,400 for the year. Management: 8% of collected rent only, under the stipulated fee basis.</li><li>One-time leasing fee: $3,500. Separate removal, storage and preparation: $6,000. These do not overlap with the maintenance allowance.</li></ul>
<div class="table-wrap"><table><thead><tr><th>12-month cash item</th><th>Stabilized comparison</th><th>Three-month no-rent conversion</th><th>Five-month no-rent conversion</th></tr></thead><tbody>
<tr><td>Collected rent</td><td>$42,000 (12 months)</td><td>$31,500 (9 months)</td><td>$24,500 (7 months)</td></tr>
<tr><td>Fixed owner payments</td><td>$33,600</td><td>$33,600</td><td>$33,600</td></tr>
<tr><td>Maintenance allowance</td><td>$2,400</td><td>$2,400</td><td>$2,400</td></tr>
<tr><td>Management</td><td>$3,360</td><td>$2,520</td><td>$1,960</td></tr>
<tr><td>One-time leasing fee</td><td>$0 in this comparison</td><td>$3,500</td><td>$3,500</td></tr>
<tr><td>Conversion work</td><td>$0 in this comparison</td><td>$6,000</td><td>$6,000</td></tr>
<tr><td>Net cash after these items</td><td>$2,640</td><td>−$16,520</td><td>−$22,960</td></tr>
</tbody></table></div>
<p>The stabilized column excludes another turnover or leasing charge, does not reserve for major capital replacement, and assumes all 12 months are collected. It is not an ongoing guaranteed surplus. Actual quotes may include minimums, renewal fees or other charges that must be added. Loan principal is included as a cash payment; this is not NOI, taxable income or a tax-loss calculation.</p>
<p>Two extra months without rent reduce collected revenue by $7,000 while the stipulated percentage management fee falls $560: annual cash worsens $6,440. Fixed costs already run for all 12 months, so do not add those two months again to the annual table. If $42,000 gross lease rent was your only fallback number, this difference would be invisible.</p>
<h2 id="timing">Dated cash matters before the annual total</h2>
<p>Suppose $30,000 is genuinely available for conversion <em>outside</em> your protected household and property reserves. Pay $6,000 preparation at the start, $8,400 fixed costs across the first three no-rent months, and the $3,500 leasing fee before first rent. That uses $17,900 and leaves $12,100 before maintenance bills or any other unmodeled payment. A two-month extra delay consumes another $5,600 fixed cash before rent arrives, leaving $6,500 on those assumptions.</p>
<p>This early cash test is a timing view of expenses already represented in the annual model, not an additional $17,900 charge to add to the annual loss. Build a month-by-month schedule with actual bill dates, receipts and a minimum balance. Maintenance may arrive sooner than the annual allowance suggests; the $30,000 is not a recommended reserve level or proof that the slower case is safe.</p>
<p>A refundable tenant deposit is not assumed available for owner spending. IRS <a href="https://www.irs.gov/publications/p527" target="_blank" rel="noopener">Publication 527 (2025)</a> says a deposit intended to be returned is not rental income when received; amounts retained for lease noncompliance have different income treatment. That federal income rule does not determine custody, use or return obligations. Obtain local legal guidance and keep deposit obligations separate from spendable owner cash.</p>
<h2 id="offer">Translate the fallback into an offer decision</h2>
<p>Before committing, write down the maximum purchase price supported by the intended STR model, the verified lease fallback and a no-rent delay case. Do not solve a fallback shortfall by assuming a tax benefit, appreciation, refinancing or a quick furniture sale. For high-income buyers, a large tax bill is not evidence of liquidity or deductible-loss eligibility; the <a href="/blog/buy-str-high-income-large-tax-bill/">high-income acquisition path</a> keeps those reviews separate.</p>
<p>Possible decisions include negotiating price, obtaining better evidence, funding a separately affordable shortfall, choosing another property or declining. The fallback need not outperform the intended STR use, but its downside must be something you can knowingly carry. Review furniture disposition separately with the <a href="/blog/sell-str-with-furniture/">furnished-property inventory checks</a>; transaction proceeds and timing are not guaranteed.</p>
<h2 id="scope">What to ask an acquisition service</h2>
<p>Ask which contract deliverable covers lease-fallback evidence, whether the adviser compares an actual local leasing quote, who owns the legal/lender/insurance confirmations, and what happens if the fallback fails your threshold. Request the work sample and exclusions before paying. BNB Accelerator publishes this guide and is an interested acquisition service provider; this original worksheet is educational document analysis, not a contracted custom report, professional legal/tax advice or firsthand testing of a leasing service.</p>
<p><strong>Source review: October 7, 2026.</strong> The linked current IRS publication supports only the deposit-income discussion, not the hypothetical rent, fee or reserve assumptions. No client outcomes or market figures are claimed. If you plan to buy within zero to six months, <a href="/apply/">apply to discuss your acquisition criteria and written service scope</a>, including whether a fallback worksheet is included and which independent specialists you need.</p>
'''
FAQ = [
('Can I estimate long-term rent as a percentage of STR revenue?', 'No. Use current address-relevant lease evidence and actual expense quotes. Different lease terms, furnished status, concessions and owner-paid services can change the comparison.'),
('Why can a positive stabilized fallback still require cash?', 'A stabilized full-year comparison omits the no-rent transition and may omit leasing and conversion charges. In the labeled example, a $2,640 stabilized cash surplus becomes a $16,520 first-year cash deficit with three no-rent months and separate transition costs.'),
('Should I add the early conversion cash test to the annual loss?', 'No. It checks when modeled expenses are paid before rent arrives. Adding those same expenses again to the annual result double-counts them; use a dated cash schedule and add only genuinely omitted costs.'),
('Does an STR restriction mean a long-term lease is automatically allowed?', 'No. Verify the proposed use against address-specific rules, HOA documents, financing and insurance conditions with the appropriate professionals before relying on the fallback.')
]

if __name__ == '__main__':
    refresh('str-long-term-rental-fallback','How Do You Underwrite a Long-Term-Rental Fallback for an STR | BNB Accelerator','How Do You Underwrite a Long-Term-Rental Fallback for an STR?','Before buying an STR, verify lease fallback evidence and compare stabilized cash with conversion costs, a no-rent delay and protected reserves.',BODY,FAQ,'2026-09-23','data-long-term-fallback-review-link','Test the <a href="/blog/str-long-term-rental-fallback/">long-term lease fallback and dated conversion cash worksheet</a>. Stabilized rent does not fund the no-rent transition or establish permitted use.')
