"""Scoped existing comparison refresh; no new blog or homepage generation."""
from pathlib import Path
import re
R=Path(__file__).resolve().parents[1]
BODY='''<section class="section-sm"><div class="wrap wrap-narrow"><h2>Buyer-fit answer: settle the use before comparing capital</h2>
<p>The <a href="https://www.pacaso.com/faq/buyer">Pacaso buyer FAQ</a> describes purchasing an interest in a property-specific LLC and prohibits owners from renting or selling their time through public vacation-rental services. It also distinguishes available co-owned homes from other listings, which may show whole-home prices. Identify the exact product rather than treating every displayed property as the same purchase. These published descriptions do not authenticate your proposed agreement.</p>
<p>For a buyer whose required outcome is an income-producing STR, managed personal-use co-ownership does not answer that rental objective. That is a fit distinction, not a claim that personal-use ownership is inferior. BNB Accelerator's <a href="/how-it-works/">published process</a> describes acquisition coordination, with funding and final decisions retained by the buyer and lending, legal advice and daily operations handled separately. Its signed engagement governs included deliverables and exclusions; it does not guarantee a rental-eligible property or investment result.</p>
<h2>Original work sample: the ownership and use acceptance sheet</h2>
<p>Complete these rows for the actual proposal before authorizing a deposit. Attach the governing document, name the reviewer and record the commitment deadline. A sales presentation is not acceptance evidence.</p>
<div class="table-scroll"><table><thead><tr><th>Decision</th><th>Personal-use co-ownership proposal</th><th>Whole-property STR proposal</th></tr></thead><tbody>
<tr><td>Interest and permitted use</td><td>Exact LLC interest, governing restrictions and allocated use</td><td>Exact deed/entity interest and independently supported rental permission</td></tr>
<tr><td>Deliverable and exclusions</td><td>Actual scheduling, shared-cost and management commitments</td><td>Named sourcing, analysis, transaction and launch tasks; introductions versus execution</td></tr>
<tr><td>Payment trigger</td><td>Deposit, purchase balance and recurring obligations under this agreement</td><td>Credited earnest money, property closing and distinct service invoices under their agreements</td></tr>
<tr><td>Decision rights</td><td>Who controls use, expenses, changes and sale of the interest</td><td>Buyer approval, licensed representation and separate lender/operator decisions</td></tr>
<tr><td>Unsuccessful purchase or exit</td><td>Actual cancellation, refund, resale and continuing expense conditions</td><td>Contract remedies, fees surviving a rejected candidate and replacement-search terms</td></tr>
</tbody></table></div>
<p>Test the work sample with one adverse fact: a proposed property cannot support the intended rental use. Who documents the answer, who sends any valid notice, what cash remains committed and what happens next? Do not assume a marketing restriction can be waived, a deposit refunded or another asset substituted. Local counsel and the actual contracting parties must resolve rights; protect private ownership and banking records in authorized channels.</p>
<h2>Worked capital test: cash remaining is not rental income</h2>
<p><strong>Hypothetical arithmetic only, not Pacaso prices, BNB fees, loan terms or client results:</strong> assume $300,000 of accessible cash. A stipulated personal-use purchase plan allocates $180,000 to the interest, $10,000 to separate transaction costs and $20,000 to a retained obligation reserve. Total allocation is $210,000, leaving $90,000 outside the plan. No rental receipts are included, and this does not establish that the reserve is sufficient.</p>
<p>A separate whole-property STR plan allocates $150,000 down payment, $20,000 distinct closing and service costs, $35,000 setup, $15,000 repairs and $45,000 protected reserves. Its $265,000 allocation leaves $35,000. These are different ownership and use cases, not equivalent assets or a return ranking. The larger cash margin in the personal-use case cannot establish a rental-income substitute.</p>
<p>If the STR plan incurs an additional $12,000 of net owner obligations during a defined no-revenue delay, allocation becomes $277,000, leaving $23,000. If another distinct $30,000 repair is required, it becomes $307,000, a $7,000 gap. Neither addition is included in the original plan. Reprice, change scope or reject an unfunded case; do not spend the protected reserve twice or assume future bookings, appreciation or a tax refund funds today's obligation.</p>
<p>If a $15,000 deposit is credited against the original STR acquisition allocation, $285,000 cash remains available and $250,000 of the original plan remains to fund: the margin stays $35,000. If that deposit instead belongs to an abandoned purchase and its refund is pending, the fresh $265,000 plan has only $20,000 outside it until funds actually clear. This is not a promise of refund rights. Match each payment to its actual transaction and agreement using the <a href="/tools/first-str-purchase-budget/">purchase-cash worksheet</a>.</p>
<h2>Fair alternatives by the work you need</h2>
<p>If whole-property STR acquisition is the objective, investigate <a href="/compare/avery-carl-short-term-shop/">The Short Term Shop</a> for its actual local representation proposal or <a href="/compare/str-search/">STR Search</a> for its actual matching and analysis tier. These are research paths with different responsibilities, not asserted equivalents or rankings. Compare BNB Accelerator's written scope against the same acceptance sheet. If personal use remains the objective, start with the existing <a href="/compare/alternatives-to-pacaso/">Pacaso alternatives owner</a> and its ownership distinctions rather than an STR forecast.</p>
<p>Proceed only when the purchased rights serve your objective and the funded downside fits. Bring the completed ownership/use sheet and dated cash plan to an <a href="/apply/">acquisition discussion</a>, or continue through the <a href="/compare/">crawlable comparison hub</a>. This document-based analysis is not firsthand testing, a customer score or legal, tax, lending or investment advice.</p>
</div></section>'''
if __name__=='__main__':
 p=R/'compare/bnb-accelerator-vs-pacaso/index.html';s=p.read_text()
 assert '"datePublished": "2026-10-06"' in s and '"dateModified": "2026-10-06"' in s
 marker='<section class="section-sm"><div class="wrap wrap-narrow"><h2>Compare evidence using one actual candidate</h2>'
 assert s.count(marker)==1;s=s.replace(marker,BODY+marker)
 s=s.replace('<h2>Continue the provider comparison</h2><p></p>','<h2>Continue the provider comparison</h2><p><a href="/compare/alternatives-to-pacaso/">Pacaso alternatives by ownership model</a> · <a href="/compare/">All purchase comparisons</a></p>')
 s=s.replace('"dateModified": "2026-10-06"','"dateModified": "2026-10-08"',1).replace('Reviewed 2026-10-06:','Reviewed October 8, 2026:',1)
 s=s.replace('Provider statements describe published offers, not independently audited performance.','Provider statements describe published offers, not independently audited performance. The buyer FAQ was reviewed through its current search-accessible primary text after direct retrieval failed; unseen signed contracts were not authenticated. The linked BNB process was also reviewed. This is document-based analysis, not firsthand testing or a review score. All cash figures are hypothetical.',1)
 p.write_text(s)
 p=R/'sitemap-core.xml';s=p.read_text();s,n=re.subn(r'(<(?:ns0:)?loc>https://www.bnbaccelerator.com/compare/bnb-accelerator-vs-pacaso/</(?:ns0:)?loc>\s*<(?:ns0:)?lastmod>)[^<]+',lambda m:m[1]+'2026-10-08',s);assert n==1;p.write_text(s)
