"""Scoped refresh of the existing before-offer amenity comparison owner."""
import re
import expand_hold_period as publisher
SLUG='amenity-roi-ranking'
BODY='''<p class="lead">How should you rank short-term rental amenities before buying a property? Start with the acquisition you can independently fund, then compare documented readiness needs and optional upgrades. An amenity appearing in neighboring listings is a reason to investigate, not proof of a booking premium or a requirement to copy it. The decision is whether to buy this property with a funded plan, choose an alternative, or leave an unsupported upgrade out of the purchase case.</p>
<p><a href="/apply/">Bring your shortlisted properties and amenity evidence register to a BNB Accelerator acquisition call</a>. We help evaluate supported purchase assumptions within the acquisition agreement; no amenity return, demand or investment result is promised.</p>
<h2>Rank the decision gates before the amenities</h2>
<p>First establish permitted rental use, usable occupancy and the condition of what will convey. Required corrective work is not an optional revenue upgrade. A proposed game room cannot create a permitted bedroom, and an attractive pool photograph does not establish usable access, condition or coverage. Assign unresolved items to qualified reviewers before treating them as available guest features.</p>
<p>Next distinguish a documented competitive gap from a personal preference. Describe the exact feature: private versus shared, available year-round versus seasonal, accessible to paying guests versus restricted. A listing label alone is not enough to establish that your proposed property offers an equivalent experience.</p>
<p>Finally compare discretionary packages. There is no universal ranking in which every mountain hot tub, coastal feature or game room earns more than its cost. Nor does a premium appliance automatically fail or succeed. The <a href="/blog/appliances-roi-short-term-rental/">optional appliance contribution test</a> handles that narrower choice; this worksheet compares the broader property-and-amenity plan.</p>
<h2>Build a comparable-evidence register</h2>
<div class="table-wrap"><table><thead><tr><th>Record</th><th>Question to resolve</th><th>Purchase use</th></tr></thead><tbody>
<tr><td>Property and review date</td><td>Same submarket, size, condition, capacity and intended guest use?</td><td>Exclude weak matches rather than forcing a comparison</td></tr>
<tr><td>Amenity availability</td><td>Actual access, season, private/shared status and condition verified?</td><td>Distinguish the feature being priced from the listing label</td></tr>
<tr><td>Revenue evidence</td><td>Advertised rate or supported achieved receipts for a defined period?</td><td>Do not treat an asking rate as collected income</td></tr>
<tr><td>Other differences</td><td>Views, location, bedrooms, management, minimum stays and season?</td><td>Do not assign the entire price difference to one amenity</td></tr>
<tr><td>Complete scope and cost</td><td>Installed work, permissions, recurring service and replacement exposure?</td><td>Compare complete alternatives rather than equipment prices alone</td></tr>
<tr><td>Reviewer and unresolved input</td><td>Who supplied evidence and what still needs confirmation?</td><td>Use bounded sensitivities or retain a purchase protection</td></tr>
</tbody></table></div>
<p>Choose comparables because they match the purchase question, not because they produce a preferred answer. Record rejected matches and the reason. Reviews can identify questions about availability or comfort, but a positive mention does not measure incremental revenue. Unavailable calendar dates do not independently establish paid bookings. Retain seller records securely and obtain permission before publishing private acquisition examples.</p>
<p><a href="https://www.airbnb.com/help/article/479">Airbnb's current search-filter guidance</a> describes filtering by amenities among other criteria. That supports investigating search visibility, not a specific filter-use percentage, market-wide mandatory feature or causal revenue lift. Do not turn the existence of a filter into a forecast of the bookings your property will receive.</p>
<p>Comparable prevalence is descriptive. Even a feature shown by many sampled listings does not establish why those listings earned their receipts or whether your property should add it. If you use a chosen prevalence threshold internally, label it as a screening convention, explain the sample and test the economics separately. Do not present a fixed percentage as a verified market rule.</p>
<h2>Price feasibility and recurring responsibilities separately</h2>
<p>Obtain property-specific installed scopes before relying on a gap-closing plan. Include access, preparation, connection work, finishes, applicable approvals, completion dates and what remains excluded. Ask qualified professionals about physical and permission constraints; this guide supplies no construction approval or safety certification. Keep documented limits visible rather than assuming every gap can be closed.</p>
<p>List recurring responsibilities and their actual providers, terms and payment dates. Reconcile service, utilities, consumables, insurance differences, repair and later capital work. A quoted installation price is not the full ownership cost. An unused household reserve cannot simultaneously fund equipment work, another purchase and a separate family obligation.</p>
<p>The <a href="https://content.naic.org/article/consumer-insight-renting-out-your-home-you-need-insurance-coverage-home-sharing-rentals">NAIC's March 2020 home-sharing guidance</a> advises reviewing rental use and coverage with the insurer and cautions about recreational equipment liability. It is background, not an issued policy or approval of a particular amenity. Request terms addressing the actual property, paying-guest use, equipment and effective dates; do not presume platform protection replaces the required coverage. Use the <a href="/blog/airbnb-insurance-guide/">insurance acquisition review</a> for that separate gate.</p>
<h2>Worked purchase comparison: a lower price can require more cash</h2>
<p>Invented educational figures only, not market prices, quotes, client outcomes or recommended reserve levels. Assume $450,000 of cleared accessible funds. Property A initially needs $425,000 of total assigned cash, including a $10,000 amenity-work allowance and a separately retained $60,000 property reserve. The total includes all other stipulated acquisition and launch uses; the reserve is not another expense added on top.</p>
<p>Suppose the complete work scope is instead $28,000 and distinct pre-purchase review costs are $2,000. Replace the included $10,000 allowance with $28,000, adding $18,000, then add the $2,000 review once. Corrected assigned cash is $445,000, leaving $5,000 outside this plan. If a separate household obligation requires $15,000, the purchase plan is $10,000 short despite retaining the stipulated property reserve.</p>
<p>For comparison, stipulate that Property B's fully reconciled acquisition and launch plan totals $430,000, including the same $60,000 retained reserve and its existing verified functional amenities. It leaves $20,000 outside, or $5,000 beyond the separate obligation. This does not prove B has a better investment return: financing, permissions, property condition and supported operating downside still need independent comparison.</p>
<p>If A additionally incurs $4,000 of distinct launch-delay bills not included in the work or other allocation, assigned cash becomes $449,000. Only $1,000 remains outside, creating a $14,000 shortfall against the household need. Count actual lost contribution separately from extra bills only when they are not already captured by the operating case. An anticipated seller concession or tax benefit is not cleared cash; use only documented accepted treatment and actual availability.</p>
<h2>Test an optional package without assuming a premium</h2>
<p>In a separate simplified comparison of A with and without its optional package, assume the incremental upfront difference is the $18,000 additional work plus $2,000 review, or $20,000. Stipulate 150 common booked nights and an unverified $20 higher receipt per night: $3,000 annual extra gross receipts. Assume solely for this example that revenue-linked incremental costs absorb 25%, or $750, leaving $2,250 contribution. Distinct extra annual service and utility bills of $1,800 leave $450 incremental annual net cash.</p>
<p>Over a chosen five-year comparison horizon, unchanged $450 annual cash totals $2,250 against $20,000 upfront, leaving $17,750 unrecovered. The horizon is not an equipment-life forecast or tax recovery period. With zero revenue lift and the same $1,800 recurring difference, five years of extra bills plus upfront spending leave the optional path $29,000 behind. These are sensitivities, not expected outcomes or probabilities.</p>
<p>Under these exact assumptions, recovering $4,000 per year of chosen upfront allocation and covering $1,800 recurring bills requires $5,800 annual contribution. Dividing by the stipulated 75% contribution fraction requires about $7,733.33 extra gross receipts, or about $51.56 per common booked night. That is a hurdle to investigate, not a claimed achievable rate increase. Debt, tax, discounting, residual value, later replacement and other omitted differences require separate analysis.</p>
<p>Do not count higher receipts on common nights and the same receipts again as new nights. Reconcile stay-based and revenue-based fees using actual contracts. The <a href="/underwriting/break-even-occupancy/">whole-property break-even worksheet</a> asks a different question: whether total receipts cover the property's obligations. Recovering one optional package does not establish that the acquisition works.</p>
<h2>Make a bounded before-offer decision</h2>
<p>Proceed only with independently funded closing and launch, verified use and condition, and a supported operating downside. Reprice a viable property when a documented installed scope changes its cash requirements. Defer discretionary work when the functional baseline works but the premium lacks evidence. Choose another property when the necessary plan does not fit your real cash or permission limits.</p>
<p><a href="/apply/">Discuss the shortlist with the comparable register and funded no-lift case</a>. BNB Accelerator coordinates acquisition work within the agreed scope; independent professionals determine inspection, construction, insurance, legal, lending and tax conclusions. Use the <a href="/blog/buy-str-high-income-large-tax-bill/">high-income buyer roadmap</a> for the broader purchase sequence. Do not depend on household income alone, future appreciation or an estimated refund to pay dated invoices.</p>
<div class="callout"><h3>Keep the specialist decisions separate</h3><p>Use the <a href="/blog/airbnb-hot-tub-roi/">hot-tub cost questions</a> and <a href="/blog/the-game-room-question/">game-room space questions</a> as starting points for property-specific evidence, not as proof of a market-wide premium. Continue with the <a href="/design/">design and furnishing resource</a>, <a href="/property-types/">property-type guides</a> and <a href="/topics/revenue-optimization/">revenue decision resources</a> as applicable.</p></div>
<p class="small">Primary Airbnb and NAIC guidance reviewed October 7, 2026; NAIC material is dated March 19, 2020, not a newly issued 2026 policy. Educational only, not valuation, engineering, insurance, legal, tax, lending or personalized investment advice. All worked figures are hypothetical. No amenity premium, demand, lifespan, approval, tax benefit or return is guaranteed.</p>'''
FAQ=[
('Which STR amenity has the best return before buying?', 'There is no universal ranking. Compare the actual property, documented comparable evidence, complete installed costs, recurring responsibilities and independently funded downside before approving an upgrade.'),
('Does amenity prevalence prove a booking premium?', 'No. Listing prevalence and search filters do not establish achieved revenue or causation. Record comparison limitations and test unsupported lift as a sensitivity, including zero lift.'),
('How do I include an amenity gap in purchase cash?', 'Replace any included work allowance with the complete verified scope, add distinct review costs once and retain separately assigned reserves. Reconcile invoice dates and other household commitments before relying on future receipts.'),
('Should I choose a cheaper STR that needs upgrades?', 'Compare complete acquisition and launch allocations, permitted use, condition and supported operating downside with the alternative property. A lower asking price does not establish lower cash needed or a better return.')]
if __name__=='__main__':
 source=(publisher.ROOT/'blog'/SLUG/'index.html').read_text();publisher.SLUG=SLUG
 publisher.TITLE=re.search(r'<title>(.*?)</title>',source)[1];publisher.H1=re.search(r'<h1>(.*?)</h1>',source)[1]
 publisher.DESC='Before buying an STR, rank amenity spending with a comparable-evidence register, complete purchase cash and an original no-revenue-lift comparison.'
 publisher.BODY=BODY;publisher.FAQ=FAQ
 publisher.main(expected_publication='2026-08-15',hub_attribute='data-amenity-ranking-link',hub_paragraph='Compare <a href="/blog/amenity-roi-ranking/">amenity evidence, complete purchase cash and a funded no-lift alternative</a> before treating a missing feature as a profitable upgrade.')
 path=publisher.ROOT/'sitemap/index.html';s=path.read_text();s=re.sub(r'(<a href="/blog/'+SLUG+r'/">)[^<]+',lambda m:m[1]+publisher.H1,s);path.write_text(s)
