"""Existing statement owner: contract-fee and held-reserve evidence, not a new payout owner."""
import re, subprocess
from pathlib import Path
from refresh_dscr_purchase_methods import refresh
ROOT=Path(__file__).resolve().parents[1]
BODY='''<p class="lead">Before buying a manager-operated STR, review the seller's owner statements to understand what the manager deducted, retained and actually remitted. A bank transfer is not a property's complete profit. The purchase question is whether the statement reconciles to records and whether the buyer's own management terms, costs and cash plan support the offer—not whether an attractive payout screenshot looks convincing.</p>
<p>Use this original statement-review worksheet alongside the <a href="/blog/str-1099-payout-reconciliation/">account and property scope register</a> and the <a href="/blog/str-refunds-chargebacks-underwriting/">refund and dispute review</a>. Those guides handle separate evidence questions. Here the focus is management fee bases, invoices, held reserves and the transition from seller remittance to buyer economics.</p>
<h2>Define the statement before comparing its totals</h2>
<p>Request the actual property's statement, underlying reservation and payout exports, relevant manager agreement, expense support and reserve ledger for the same covered period. Record listing identifiers, currency, statement dates, stay dates and whether the report uses booking, stay or cash dates. Ask the preparer to explain its method. A report covering cash received in September need not describe only September stays.</p>
<p><a href="https://www.airbnb.com/help/article/3632">Airbnb's earnings-report guidance</a> describes monthly and annual reports broken down by listing and payout method, with gross earnings, adjustments, host service fees, taxes withheld and net pay. It also describes configurable CSV exports. These are available report features, not authentication of a seller's file or a guarantee that the manager's statement uses the same definitions.</p>
<p><a href="https://www.airbnb.com/help/article/2666">Airbnb's extra-payout guidance</a> notes that bank receipt dates can differ from platform sending dates, payouts may be grouped and overpayment deductions may occur across future payouts. Ask for a dated bridge rather than treating every mismatch as another expense or evidence of misconduct. Do not assume this specific explanation applies to an unexplained transaction.</p>
<p>Obtain authorized, securely shared records with guest and unrelated financial details redacted. Do not ask for passwords, publish bank statements or copy private seller data into a public worksheet. An accountant can review sensitive identifiers privately. Missing records mean an unresolved question, not proof that revenue or exposure is zero.</p>
<h2>Use a fee-and-reserve acceptance register</h2>
<div class="table-wrap"><table><thead><tr><th>Statement field</th><th>Supporting evidence</th><th>Buyer decision before relying on it</th></tr></thead><tbody>
<tr><td>Reservation and channel totals</td><td>Property-specific exports and documented period/basis</td><td>Explain omitted channels and overlapping exports without adding the same stay twice</td></tr>
<tr><td>Management fee</td><td>Actual rate, included revenue, refund treatment and calculation clause</td><td>Recalculate on the agreed base, then obtain the buyer's separate proposed terms</td></tr>
<tr><td>Cleaning and other pass-throughs</td><td>Guest receipts, vendor invoices and included services</td><td>Match services rather than assuming every clean equals a checkout or every item is extra</td></tr>
<tr><td>Repairs and markup</td><td>Work order, accepted invoice, authorization and any fee provision</td><td>Explain charge and payer without declaring an unsupported fee lawful or recoverable</td></tr>
<tr><td>Held reserve</td><td>Opening balance, contributions, draws and ending balance</td><td>Separate retained buyer/seller money from incurred expense and confirm closing treatment</td></tr>
<tr><td>Owner transfer</td><td>Statement amount, sending reference and authorized bank receipt</td><td>Explain timing and grouping; identify property bills paid outside the manager</td></tr>
</tbody></table></div>
<p>Ask for explanations of linen, supply and coordination charges that may overlap an existing allowance. A round amount or more cleans than checkouts is a reason to request support, not proof of an error: deep cleaning, interrupted stays or agreed work may explain it. The <a href="/blog/str-property-management-fees/">management-fee guide</a> provides background; the signed scope and applicable professional advice control the actual obligation.</p>
<h2>Worked statement: payout and economic contribution differ</h2>
<p>Hypothetical one-period example only, not a seller file, manager quote, market benchmark or client result. Assume $15,000 accommodation charges and $1,500 cleaning receipts, less $600 platform charges and $900 completed accommodation refunds: $15,000 reaches the manager on this defined basis. The refunds have not already been deducted from the starting amounts.</p>
<p>For this invented agreement, management is 20% of accommodation after those refunds, excluding cleaning: $14,100 × 20% = $2,820. Assume $1,600 cleaner invoices, $1,200 distinct current repairs and $500 moved into a held reserve. The owner transfer is $15,000 − $2,820 − $1,600 − $1,200 − $500 = $8,880. The reserve contribution is retained money, not another operating expense.</p>
<p>The reserve opens at $4,000. After the $500 contribution and an $800 payment for a separate older maintenance obligation, it ends at $3,700. That $800 is not included in the $1,200 current repairs above. The defined operating cash contribution before debt and other outside bills is $15,000 − $2,820 − $1,600 − $1,200 − $800 = $8,580. The same bridge is $8,880 remitted plus the $3,700 ending reserve minus the $4,000 starting reserve. Do not add the whole ending reserve to earnings.</p>
<p>If $3,000 debt payments and $700 utilities are paid outside the manager, the bank transfer leaves $5,180 after those bills. The defined contribution after those bills is $4,880 because held cash fell $300. These are illustrative cash measures, not tax profit, standardized net operating income or lender qualifying income; principal, accruals, capital classification and omitted costs require appropriate review. One month must not be multiplied by twelve to manufacture an annual forecast.</p>
<h2>Replace seller terms with the buyer's actual cost case</h2>
<p>If the actual fee base instead included the $1,500 cleaning receipts while still netting the same refunds, the base would be $15,600 before platform charges. At 20%, the fee would be $3,120: $300 more than this example's $2,820. Do not confuse that fee base with the $15,000 cash received after platform charges. Whether the fee is correct depends on the agreement, not which calculation is cheaper. Ask the manager to explain a difference and request correction only when the evidence supports it.</p>
<p>Now suppose the buyer receives a separate hypothetical 25% quote on the original $14,100 accommodation base. Management becomes $3,525, increasing cost $705 for this period. Holding all other illustrative inputs fixed, contribution before outside bills falls from $8,580 to $7,875; after the stated debt and utilities it is $4,175. This is a same-period sensitivity, not a claim that a new manager reproduces the seller's bookings, costs or service.</p>
<p>Confirm replacement reporting, reserve requirements, recurring services, setup charges and payment dates. Do not assume the seller's agreement, reserve money or platform account transfers with the house. Use the <a href="/blog/str-management-agreement-termination/">management handoff review</a> and retained counsel to resolve continuing obligations and permitted arrangements. Any distinct opening fee or repair needs a separate acquisition cash line; a later seller settlement or hoped-for tax refund cannot fund an earlier invoice.</p>
<h2>Resolve discrepancies before crediting the purchase income</h2>
<p>Keep each query factual: record, expected calculation, reported amount, requested support, responsible person and real diligence deadline. Preserve explanations and revised versions. A difference can involve timing, scope, classification or an error; do not accuse the manager or claim most discrepancies are clerical without evidence. A reporting worksheet does not create termination, reimbursement or transaction-extension rights.</p>
<p>Proceed when supported history and buyer costs justify the offer with verified permissions, financing and funded downside. Reprice a viable acquisition when supported costs change. Seek a protected delay through the retained transaction professional when a decisive record is still missing. Decline an income premium that depends on unreconciled statements or seller cash the buyer cannot lawfully access.</p>
<p><a href="/apply/">Bring the statement acceptance register to an STR acquisition call</a>: supported property receipts, fee base, reserve movement, outside bills, proposed buyer terms and unresolved evidence. For <a href="/blog/buy-str-high-income-large-tax-bill/">buyers with substantial capital or a large tax bill</a>, liquidity does not validate a seller's profit claim. BNB Accelerator assists within its actual contracted acquisition scope; accountants, lenders and counsel determine their respective conclusions. No post-purchase benchmarking service is promised here.</p>
<p class="small">Airbnb primary guidance reviewed October 7, 2026; the linked pages do not supply a publication date, and this is a source-review date. Document-based educational analysis, not firsthand manager testing, an independent rating or professional accounting, legal, tax, lending or investment advice. BNB Accelerator is the commercially interested acquisition-service publisher. All worked numbers are hypothetical; no reporting remedy, approval, booking, deduction or investment result is guaranteed.</p>'''
FAQ=[
('How often should I review my STR owner statement?', 'Before buying, reconcile the covered seller periods and resolve decision-changing gaps before actual diligence deadlines. After closing, agree a recurring review and deeper reconciliation with the reporting professional; no fixed review time guarantees completeness.'),
("What should a property manager's owner statement include?", 'Request the property and period definitions, reservation and payout detail, fee rate and base, supported expenses, held-reserve movement and owner transfer. Reporting rights depend on the actual agreement; reconcile bills paid outside the manager separately.'),
('Is it normal for managers to mark up maintenance invoices?', 'Do not infer prevalence or legal acceptability. Verify the actual authorization, invoice, agreed markup or coordination fee and applicable advice. An unexplained charge needs evidence before it is accepted in the purchase model.'),
('Which KPIs matter most when reviewing a manager?', 'For an acquisition, first reconcile supported property receipts, fee bases, expenses, reserve movement and outside bills. Compare like periods and definitions for occupancy and rates; a KPI or remittance alone does not establish buyer profit.')]
if __name__=='__main__':
 s=subprocess.check_output(['git','show','HEAD:blog/str-owner-statement-review/index.html'],cwd=ROOT,text=True)
 keep=re.search(r'<div class="callout">\s*<h3>Keep reading</h3>.*?</div>',s,re.S)
 assert keep
 refresh('str-owner-statement-review','How to Review an STR Owner Statement | BNB Accelerator',"How to review a property manager's monthly owner statement",'Before buying a manager-operated STR, reconcile fees, invoices, reserves and remittances. Use an owner-statement worksheet and separate buyer-cost case.',BODY+(keep[0] if keep else ''),FAQ,'2026-09-24','data-owner-statement-purchase-link','Review the <a href="/blog/str-owner-statement-review/">manager-statement acceptance register and fee/reserve cash bridge</a> before relying on seller remittances. Rebuild the acquisition using actual buyer costs.')
 p=ROOT/'blog/str-owner-statement-review/index.html'; updated=p.read_text()
 if '<span>Updated October 7, 2026</span>' not in updated:
  updated=updated.replace('<span>Published September 24, 2026</span>','<span>Published September 24, 2026</span><span>Updated October 7, 2026</span>',1)
 p.write_text(updated)
