"""Review buyer exit exposure; preserve publication and align four revised FAQs."""
import html,json,re
from pathlib import Path
from expand_reservations_closing import main,ROOT
SLUG='str-management-agreement-termination'
FAQS=[
('Can I cancel an Airbnb property management contract early?', 'Read the signed agreement, amendments, notice mechanics, renewal dates and any cause or cure provisions with local counsel. No universal early-cancellation right, notice period or fee waiver is assumed.'),
('Who keeps the Airbnb listing and reviews when I change managers?', 'Identify the actual account and listing owner. Airbnb does not permit account ownership or reservations to transfer to another host or account. Co-host access is not ownership; confirm the permitted operating path with Airbnb.'),
('Are termination fees normal for STR managers?', 'Do not rely on a typical fee claim. Identify each charge in the actual agreement, its trigger, calculation base and due date, then ask counsel which obligations apply to your proposed exit.'),
('What records should a manager hand over at termination?', 'Agree on authorized financial records, inventory, service responsibilities and asset access through secure procedures. Review privacy, contractual rights and vendor permissions; do not assume unrestricted guest data or account passwords can be transferred.')]
BODY='''<p class="lead">Before buying an STR and signing or continuing a management agreement, test how you could leave it later. A purchase that works only with one operator may have more downside than its current fee suggests. STR management agreement termination terms affect the earliest lawful switch date, cash still owed, access to operating records and the resources available for a replacement. Review actual signed documents with local counsel rather than budgeting a supposedly standard notice period or exit fee.</p>
<p><a href="/apply/">Book an STR acquisition call with the proposed agreement and a funded fallback plan</a>. BNB Accelerator assists within its contracted acquisition scope; counsel reviews legal rights and obligations, while the insurer, lender and platform determine their respective requirements. This guide concerns exit exposure before committing to an operating arrangement, not a template termination notice.</p>
<h2>Find the actual notice and renewal mechanics</h2>
<p>Collect the agreement, amendments, fee schedules and relevant written representations. Record the initial term, renewal date, deadline for notice, required delivery method and recipient, effective termination date, any cure process and duties during the notice period. Ask counsel how receipt, weekends, disputed breaches or a sale affect your particular terms. Do not assume sending an email, changing a calendar or removing access ends the contract.</p>
<p>For a provider-specific example, <a href="https://www.vacasa.com/property-management/faq" rel="noopener">Vacasa's current property-management FAQ</a> describes cancellation with 90 days' notice and honoring already-booked reservations during that window. This is a provider's published summary, not proof of the terms applying to a particular property or a universal notice period. Request the actual agreement and written clarification of booked stays, charges and effective dates. A short marketing promise does not resolve every exit obligation.</p>
<p>Before signing, ask whether the proposed terms support the flexibility your acquisition case needs. If the manager will not accept a requested change, underwrite the actual offer rather than assuming future negotiation. Obtain counsel-reviewed agreed amendments; a verbal assurance of an easy exit is not a documented amendment. Set reminders from the verified deadlines, with enough time for adviser review.</p>
<h2>Build an exit-obligation schedule</h2>
<div class="table-wrap"><table><thead><tr><th>Item to resolve</th><th>Evidence</th><th>Funding or control decision</th></tr></thead><tbody>
<tr><td>Services during notice</td><td>Effective dates, accepted scope and actual fee base</td><td>Budget continuing duties without assuming duplicate replacement work is free</td></tr>
<tr><td>Exit or unrecovered startup charge</td><td>Contract trigger, calculation, cap if any and due date</td><td>Do not invent a declining fee or automatic sale waiver</td></tr>
<tr><td>Existing stays and commissions</td><td>Channel records, service party, applicable terms and reconciled charges</td><td>Identify obligations once; avoid counting the same commission twice</td></tr>
<tr><td>Reserves, deposits and final accounting</td><td>Ownership, permitted offsets, release conditions and dated statements</td><td>Exclude unavailable funds from early switching bills</td></tr>
<tr><td>Records, vendors and assets</td><td>Authorized handoff scope, ownership, permissions and actual availability</td><td>Price replacement work where access or service cannot continue</td></tr>
</tbody></table></div>
<p>Separate your obligations from the seller's and from any claim still disputed. Ask counsel about exclusivity, restrictions on hiring vendors, surviving liabilities, dispute procedures and applicable law. Ask the insurance adviser what each party's coverage does during transition; a manager's policy does not automatically establish protection for every owner loss. Do not assume reciprocal indemnities, additional-insured status, reserve release or fee enforceability without actual documents and professional review.</p>
<p>For acquisition-day consent and earlier-liability questions, use the <a href="/blog/assign-str-management-contract-sale/">management-assignment guide</a>. For deciding whether an incumbent deserves a price premium based on verified performance, use the <a href="/blog/keep-str-manager-after-buying-property/">manager-retention comparison</a>. Neither replaces this later-exit liability and timing schedule.</p>
<h2>Do not promise account transfer or unrestricted data handover</h2>
<p><a href="https://www.airbnb.com/help/article/1431" rel="noopener">Airbnb's account guidance</a> says ownership cannot transfer to a different host and reservations cannot transfer to a new host or account. A manager's private promise cannot override that restriction. Identify the actual account and listing owner, not only who appears as primary host. Do not buy credentials or assume reviews become a separately transferable property asset.</p>
<p><a href="https://www.airbnb.com/help/article/1534" rel="noopener">Airbnb's co-host guidance</a> distinguishes permissions from ownership and describes different access levels. It also separates permission changes from co-host payouts. If the listing is legitimately held by the continuing owner, review appropriate permission and payout changes through Airbnb's supported procedures; that is different from transferring the manager's or seller's account. Verify each other channel independently and resolve affected stays using the <a href="/blog/future-reservations-at-closing/">reservation-duty ledger</a>.</p>
<p>Agree on secure delivery of records the recipient is actually entitled to use. Request accounting support, inventory, asset ownership and vendor contacts with appropriate permissions. Have counsel review guest-data purpose, consent or other lawful basis, retention and disclosure requirements. Use reservation identifiers for diligence and avoid publicly shared guest details. Arrange authorized device/account removal and replacement access without taking unrelated passwords. Photos, domains, software subscriptions and vendor availability each need their own ownership or permission check.</p>
<h2>Worked hypothetical: delayed reserve release is not exit cash</h2>
<p>Invented planning figures only, not manager quotes, industry averages or a client outcome. Assume $55,000 of accessible buyer cash remains after purchase and unrelated launch costs. Protect $25,000 for baseline operations. A hypothetical later exit requires $6,000 of continuing management fees, $4,000 of contractual exit charges, $3,000 replacement onboarding and $5,000 of distinct transition work. Total early outflows are $18,000, leaving $37,000 accessible cash and $12,000 above the protected floor.</p>
<p>Assume a separate $8,000 owner balance is held by the manager and cannot be released before the final reconciliation. It is excluded from the initial $55,000. If only $6,000 is later released after documented $2,000 offsets, cash becomes $43,000. Those offsets reduce the separate receivable; they do not also reduce the original accessible cash in this example. If the stated $55,000 already included that held balance, first remove it and recalculate. No release amount or date is guaranteed.</p>
<p>Now test an additional $15,000 of actual carrying and replacement-service bills during a longer transition, separate from all four original lines. Before any reserve release, $55,000 minus $18,000 minus $15,000 leaves $22,000, a $3,000 shortfall against the protected $25,000. Even a later $6,000 release cannot pay earlier invoices on their due dates. Forecast receipts, a hoped-for tax refund or an unapproved seller adjustment do not solve that timing gap. Do not also charge hypothetical lost gross bookings as an invoice: analyze revenue effects separately from actual cash bills.</p>
<h2>Use the exit test in your purchase decision</h2>
<p>Proceed when accepted terms, a permitted operating fallback and accessible cash support both the base purchase and a reasonable exit stress. Renegotiate proposed management terms or the acquisition economics when verified restrictions create an unacceptable funded burden. Delay only under valid purchase protection while a decisive agreement or platform answer is missing. Reject an acquisition dependent on an unavailable account, unfunded switch or unsupported right to leave. A modeled shortfall does not itself create a contractual cancellation right.</p>
<p>Keep the signed documents, dated obligation schedule and approved access plan in the acquisition file. For <a href="/blog/buy-str-high-income-large-tax-bill/">high-income buyers with substantial capital</a>, a future switch can also change real owner responsibilities; have tax advisers evaluate actual participation and facts rather than assuming management status ensures a deduction. <a href="/apply/">Bring the exit schedule and cash stress to an acquisition call</a>. No manager performance, lawful opening, tax benefit or return is promised.</p>
<p class="small">Primary Vacasa and Airbnb sources reviewed October 6, 2026. Educational information, not legal, tax, insurance, lending or personalized investment advice. Worked amounts are hypothetical; use actual contract terms, dates and adviser review.</p>'''
if __name__=='__main__':
 p=ROOT/'blog'/SLUG/'index.html';s=p.read_text()
 def remove_faq(m):
  d=json.loads(m.group(2));assert not any(x.get('@type')=='FAQPage' for x in d.get('@graph',[]))
  return '' if d.get('@type')=='FAQPage' else m.group()
 s=re.sub(r'(<script[^>]*type="application/ld\+json"[^>]*>)(.*?)(</script>)',remove_faq,s,flags=re.S);p.write_text(s)
 faq_body='<h2 id="faq">Frequently asked questions</h2>'+''.join('<div class="faq-group"><h3>'+html.escape(q)+'</h3><div class="faq-answer"><p>'+html.escape(a)+'</p></div></div>' for q,a in FAQS)
 main(slug=SLUG,title='STR Management Agreement Termination: Buyer Exit Test',h1='STR management agreement termination clauses: what to check before you sign',description='Review STR management agreement termination before buying: actual notice, exit charges, platform limits, secure records and a funded switching plan.',body=BODY+faq_body,search_terms='management agreement termination exit notice renewal charges reserve release switching cash',hub_attribute='data-manager-exit-link',hub_block='<p data-manager-exit-link>Before committing to a manager, use the <a href="/blog/str-management-agreement-termination/">contract exit and delayed-reserve cash test</a> to evaluate actual notice, remaining duties and a permitted operating fallback.</p>')
 s=p.read_text().replace('Updated September 24, 2026','Updated October 6, 2026')
 if 'Updated October 6, 2026' not in s:
  s=s.replace('<span>Published September 24, 2026</span>','<span>Published September 24, 2026</span><span>&middot;</span><span>Updated October 6, 2026</span>',1)
 count=len(re.findall(r'\b\w+\b',html.unescape(re.sub('<[^>]+>',' ',BODY+faq_body))))
 def schema(m):
  d=json.loads(m.group(2))
  for n in d.get('@graph',[d]):
   if n.get('@type') in ['Article','BlogPosting']:n['wordCount']=count
  return m.group(1)+json.dumps(d,indent=2)+m.group(3)
 s=re.sub(r'(<script[^>]*type="application/ld\+json"[^>]*>)(.*?)(</script>)',schema,s,flags=re.S)
 faq={'@context':'https://schema.org','@type':'FAQPage','mainEntity':[{'@type':'Question','name':q,'acceptedAnswer':{'@type':'Answer','text':a}} for q,a in FAQS]}
 s=s.replace('</head>','<script type="application/ld+json">'+json.dumps(faq,indent=2)+'</script>\n</head>',1);p.write_text(s)
 xml=ROOT/'sitemap-blog.xml';x=xml.read_text();pattern=r'(<loc>https://www\.bnbaccelerator\.com/blog/'+SLUG+r'/</loc>\s*<lastmod>)[^<]*(</lastmod>)';x,n=re.subn(pattern,r'\g<1>2026-10-06\2',x);assert n==1;xml.write_text(x)
