"""Expand one existing first-renewal acquisition owner, not a library generator."""
from refresh_dscr_purchase_methods import refresh
BODY = '''<p class="lead">Audit an STR license renewal calendar before buying by connecting each deadline to the actual buyer's permission, required evidence and accepted responsible person. An active seller permit is not durable buyer authorization, and a reminder calendar is not a completed renewal. If closing is close to expiry, the first renewal can become an immediate acquisition decision rather than a routine task for later. Build the handoff before approving the purchase and fund a no-guest-receipts interval where lawful operation is unconfirmed.</p>
<p><a href="/apply/">Bring the first-renewal register and unresolved permission dates to an STR acquisition call</a>. BNB Accelerator assists within its contracted acquisition scope. The issuing authority decides permission, while independent counsel and other professionals evaluate transaction rights and their respective requirements.</p>
<h2>Check whether sale changes the process before copying dates</h2>
<p>Obtain the actual permit, holder, address/unit, issue date, expiry, conditions and current official status. Ask the authority whether the proposed buyer and ownership change require a new application, an update, a permitted transfer or some other documented action. Do not assume the seller's annual anniversary or remaining term carries forward. Describe entity and control changes accurately; an entity purchase is not an automatic continuity workaround.</p>
<p>Use the <a href="/blog/permits-that-do-not-transfer/">buyer permission guide</a> for eligibility and the <a href="/blog/str-permit-value-sale/">permit-premium comparison</a> for pricing. This calendar addresses a separate acquisition task: who must produce, submit, pay for and verify the first required buyer event before the operating plan relies on it?</p>
<p>A bounded current example is <a href="https://www.nashville.gov/departments/codes/short-term-rentals/renew-short-term-rental-property-permit">Nashville's renewal guidance</a>. It describes 365-day permits with renewal before expiry, assigns timely renewal responsibility to the owner, and describes affidavit review followed by payment instructions. It says the permit is not renewed until payment is made. Those steps illustrate why emailing a form alone is not completion. They do not establish that a seller's permit transfers, that this buyer qualifies, or that another jurisdiction follows the same calendar.</p>
<h2>Build a first-renewal acceptance register</h2>
<div class="table-wrap"><table><thead><tr><th>Required event</th><th>Evidence to retain privately</th><th>Acceptance question</th></tr></thead><tbody>
<tr><td>Buyer permission path</td><td>Authority answer for exact parcel, buyer and use</td><td>Is this actually a renewal, or a new buyer application?</td></tr>
<tr><td>Prerequisite documents</td><td>Current forms, insurance evidence, contact filing or applicable inspection</td><td>Are the documents valid for this buyer and period?</td></tr>
<tr><td>Responsible submitter</td><td>Named owner/agent, written accepted scope and backup contact</td><td>Who is authorized, available and accountable for the step?</td></tr>
<tr><td>Submission and review</td><td>Receipt, missing-item notice and response date</td><td>What is received, incomplete, under review or decided?</td></tr>
<tr><td>Fee and official status</td><td>Actual required charge, payment evidence and issuer's current status</td><td>What establishes completion under the controlling process?</td></tr>
<tr><td>Operating and purchase deadlines</td><td>Effective permission, expiry and counsel-reviewed contract dates</td><td>Can buyer operation begin, and when must the purchase decision occur?</td></tr>
</tbody></table></div>
<p>Record the actual due date, time zone where applicable, source version, reviewer, unresolved item and next action beside each row. Keep statuses literal: an inspection appointment is not a passed inspection; a passed inspection is not every other approval; a payment confirmation is not proof of an unrelated permit. Verify the issuer's status and effective scope rather than relying on a manager's screenshot label.</p>
<p>Inventory separate licenses, tax registrations, association approvals, insurance documents and local-contact filings. Not all are annual, not all require inspection, and not all reset at sale. Ask the relevant issuer or professional which events apply. A seller's tax account should not be silently treated as the buyer's registration. A compliant public permit does not answer a separate <a href="/blog/hoa-rental-cap-before-buying-str/">HOA allocation question</a>.</p>
<h2>Worked closing-relative schedule: a calendar does not extend rights</h2>
<p>This is an invented scheduling work sample, not a local legal deadline, promised processing time or recommendation to close before approval. Assume proposed closing is Day 0 and the seller's document shows expiry on Day +14. The authority has not yet confirmed the buyer's process. The executed purchase terms, as interpreted by counsel for this hypothetical only, require a decisive buyer-use review by Day −10. Those are separate dates.</p>
<div class="table-wrap"><table><thead><tr><th>Illustrative target</th><th>Required work product</th><th>If still missing</th></tr></thead><tbody>
<tr><td>Day −18</td><td>Owner/parcel status and buyer-process question submitted to the proper office</td><td>Escalate the missing decisive answer, not merely the reminder</td></tr>
<tr><td>Day −14</td><td>Required records and any applicable inspection access confirmed</td><td>Identify actual prerequisite and accepted responsible person</td></tr>
<tr><td>Before Day −10</td><td>Counsel-reviewed permission and remedy decision</td><td>Assess available protection before the contractual deadline</td></tr>
<tr><td>Before buyer operation</td><td>Actual effective permission and all other opening gates verified</td><td>Do not assume Day 0 or Day +14 authorizes hosting</td></tr>
</tbody></table></div>
<p>The proposed inspection could be unavailable or unnecessary under the actual rule. A delayed office response does not change the contract, and the seller's expiry does not create a buyer grace period. Ask counsel about the valid notices and any fully executed amendment; the <a href="/blog/permit-pending-due-diligence-extension/">protected-extension guide</a> treats that distinct decision. Do not send a legal notice based on this sample.</p>
<p>After the actual buyer process is established, build a rolling 13-month view so the first repeat event is visible beyond a one-year screen. Include prerequisite lead time and proof of completion, not just expiry reminders. This is a planning horizon, not a claim that every license lasts 13 months or that every application can start before ownership.</p>
<h2>Itemize first-renewal cash without counting reserves twice</h2>
<p>For separate invented arithmetic, assume $330,000 accessible funds and a complete $290,000 acquisition-and-launch allocation that includes $40,000 protected reserve. Stipulate that it excludes newly identified $600 filing, $400 inspection, $1,200 corrective work and $300 document expenses. Those distinct charges total $2,500; they are not actual local fees or an assertion that all four are required.</p>
<p>Also assume an 18-day unsupported-opening interval creates $125 per day of actual carrying bills excluded from that initial allocation. With no guest receipts modeled, that adds $2,250. Total allocation becomes $294,750, leaving $35,250 outside it. If the interval is instead 30 days, carrying bills are $3,750 and total allocation becomes $296,250, leaving $33,750. Neither duration predicts an authority's processing time.</p>
<p>Do not subtract the $40,000 reserve again, or add these bills again to an annual case already containing them. Lost gross revenue is not a second invoice. Replace hypothetical fees and day counts with actual quotes, required work and dated obligations; do not assume a tax refund or seller reservation pays for them. The <a href="/tools/first-str-purchase-budget/">purchase cash worksheet</a> tests the wider budget. Cash capacity does not resolve unavailable permission.</p>
<h2>Make readiness an acquisition decision</h2>
<p>Proceed when the buyer permission path, timely completion evidence, accepted responsibilities and funded opening plan meet your requirements. Reprice when supported extra work changes an otherwise viable purchase. Delay only under valid contractual protection while a decisive answer remains outstanding. Reject the STR thesis if the required permission is unavailable or the transaction needs immediate unauthorized operation to work. Check <a href="/blog/str-complaint-permit-revocation/">open enforcement and renewal issues</a> separately; do not assume every complaint is a confirmed violation.</p>
<p><a href="/apply/">Compare the shortlist with the first-renewal register and funded downside</a>. For <a href="/blog/buy-str-high-income-large-tax-bill/">high-income buyers</a>, ample capital does not replace timely authorization. BNB Accelerator is the publisher and interested acquisition-service provider. This is document-based educational analysis, not firsthand testing or professional approval. Keep permit, seller and borrower records in agreed private channels.</p>
<p class="small">Nashville primary renewal guidance reviewed October 7, 2026; the page reports a March 11, 2026 update. Confirm current buyer-specific rules before relying on it. All sample dates and amounts are hypothetical. Educational only, not legal, tax, lending, insurance or personalized investment advice. No transfer, renewal, opening date, financing, tax benefit or return is guaranteed.</p>'''
FAQ = [
 ('Can I copy the seller’s STR renewal date into my buyer calendar?', 'Only after the authority confirms the actual buyer process. A sale may require a new application or other action; the seller’s remaining term does not establish buyer permission.'),
 ('Does submitting a renewal form mean the STR permit is renewed?', 'Do not assume it does. Record the controlling process, required review and payment, and verify official status and effective scope. Submission, inspection and approval are separate milestones.'),
 ('Does the seller’s expiry date extend my purchase contingency?', 'No automatic extension is assumed. Have counsel read the executed dates, notice requirements and remedies; an office delay or calendar reminder does not amend the contract.')
]
if __name__ == '__main__':
    refresh('str-license-renewal-calendar', 'How Do You Audit an STR License Renewal Calendar Before Buying | BNB Accelerator', 'How Do You Audit an STR License Renewal Calendar Before Buying?', 'Buying an STR near license renewal? Verify buyer deadlines, accepted responsibilities and approval evidence. Use a first-renewal handoff and cash worksheet.', BODY, FAQ, '2026-09-23', 'data-renewal-calendar-review-link', 'Use the <a href="/blog/str-license-renewal-calendar/">first-renewal acceptance register and closing-relative schedule</a>. Seller expiry, buyer permission and contract deadlines are separate.')
