"""Scoped existing acquisition guide refresh; no homepage or library generator."""
from refresh_dscr_purchase_methods import refresh
from pathlib import Path
import re, subprocess

BODY = '''<p class="lead">Before buying a short-term rental, compare management quotes in dollars and responsibilities, not just percentages. A lower advertised rate can cost more when the fee base, extra services and opening charges differ. The purchase question is whether the actual operating scope, owner obligations and downside cash fit this property and your available time. A manager's revenue estimate is not verified future income.</p>
<p>BNB Accelerator publishes this guide and has a commercial interest in acquisition services. This is document-based decision support, not firsthand manager testing, an independent ranking or a report of client results. <a href="/apply/">Bring written manager proposals and the complete purchase budget to an acquisition call</a>; assistance is limited to BNB's contracted scope.</p>
<h2 id="range">Get a comparable quote, not an assumed market range</h2>
<p>No universal management percentage or typical co-host price is established here. Request dated proposals for the same address, intended opening date, guest capacity and service scope. Specify the party actually operating the property and whether local work is performed directly or by separately contracted vendors. A platform permission, marketing label or nationwide service page is not an address-specific operating commitment.</p>
<p>Identify the denominator: lodging charges, total guest receipts, receipts after refunds, or another defined amount. Ask whether cleaning, taxes, platform fees, discounts, canceled stays and owner use enter that base. Then identify when a fee is earned and paid: booking, completed stay, collected receipt, onboarding or termination. Do not treat a charge to guests as cash the owner necessarily retains.</p>
<h2 id="included">Use a deliverable and decision-rights register</h2>
<div class="table-wrap"><table><thead><tr><th>Quote field</th><th>Evidence to request</th><th>Purchase consequence</th></tr></thead><tbody>
<tr><td>Pricing and calendar</td><td>Named decision maker, owner override, minimum-stay and owner-use rules</td><td>Check whether the proposed availability matches your revenue case</td></tr>
<tr><td>Guest and local response</td><td>Coverage hours, escalation process, local responder and measurable response commitment</td><td>Assign uncovered tasks and cash rather than assuming around-the-clock service</td></tr>
<tr><td>Cleaning and restocking</td><td>Guest charges, vendor invoices, retained difference, supplies and inspection scope</td><td>Separate pass-through receipts from costs and management earnings</td></tr>
<tr><td>Repairs and vendor work</td><td>Markup, coordination fee, related vendors, approval threshold and emergency authority</td><td>Budget service charges separately from the actual repair invoice</td></tr>
<tr><td>Opening and reporting</td><td>Onboarding deliverables, excluded furnishings/photos, statement sample and access rights</td><td>Fund opening invoices before projected bookings arrive</td></tr>
<tr><td>Exit and reservations</td><td>Notice, termination costs, pending-stay responsibility and lawful transition process</td><td>Do not assume listing history or reservations transfer with a management change</td></tr>
</tbody></table></div>
<p>Ask for a redacted sample statement and reconcile one month's receipts, refunds, percentage base, service fees and vendor outflows. A related vendor is not proof of misconduct; disclose the relationship and compare the proposed price and scope. Ask how bookings are allocated when a provider operates competing inventory, without asserting favoritism. A promise of better occupancy needs evidence, not an automatic premium in your forecast.</p>
<p>For actual provider alternatives, use the <a href="/compare/">crawlable comparison hub</a>, including the <a href="/compare/alternatives-to-awning/">Awning buying-versus-operating scope comparison</a>. Acquisition assistance, analytics, brokerage and ongoing management are not interchangeable deliverables. Compare the actual agreements before assigning any provider the same role.</p>
<h2 id="math">Worked quote comparison: the higher percentage can cost less</h2>
<p>All numbers below are invented arithmetic, not market rates, provider quotes or client outcomes. Assume identical $140,000 annual lodging revenue. Both fictional quotes calculate their percentage only on lodging, excluding cleaning receipts and taxes. Ordinary cleaning, platform charges, utilities, insurance, taxes, repairs and debt are outside both fee totals. They must still enter the full owner-cash forecast.</p>
<div class="table-wrap"><table><thead><tr><th>Identical assumed scope</th><th>Quote A</th><th>Quote B</th></tr></thead><tbody>
<tr><td>Percentage fee</td><td>18% × $140,000 = $25,200</td><td>20% × $140,000 = $28,000</td></tr>
<tr><td>Specified annual coordination/reporting services</td><td>$4,200 extra</td><td>Included in percentage fee</td></tr>
<tr><td>Recurring service-fee total</td><td>$29,400</td><td>$28,000</td></tr>
<tr><td>One-time onboarding</td><td>$1,500</td><td>$2,000</td></tr>
<tr><td>First-year service-fee total</td><td>$30,900</td><td>$30,000</td></tr>
</tbody></table></div>
<p>Quote B costs $900 less in year one and $1,400 less in a later unchanged year despite the higher percentage. Relative to the same lodging base, recurring service charges are 21% for A and 20% for B; first-year charges are about 22.1% and 21.4%. These are effective service-fee ratios, not profit margins. The $4,200 is a stipulated service charge, not an underlying repair bill or a second expense already included elsewhere.</p>
<p>For an intentionally constant five-year comparison, A totals $1,500 + five × $29,400 = $148,500; B totals $2,000 + five × $28,000 = $142,000. The difference is $6,500. This holds revenue, scope and rates fixed and excludes inflation, taxes, time value and all other costs; it is not a five-year forecast or a claim that B is better. Actual service quality, owner work and changed terms could reverse the decision.</p>
<h2>Stress the property, not just the fee ratio</h2>
<p>In a separate fictional downside, lodging falls to $110,000 while those specified service charges remain unchanged. A costs $19,800 + $4,200 = $24,000 recurring; B costs $22,000. These replace the base recurring fees rather than adding to them. Determine which actual fees change with receipts and which remain due when bookings fall. Rebuild the property's complete cash case using the <a href="/blog/airbnb-revenue-projections/">revenue-to-owner-cash worksheet</a>.</p>
<p>For a separate purchase-capital check, assume $250,000 available and $249,000 already assigned to down payment, distinct closing bills, furnishings and retained operating cash. If onboarding is excluded from that assignment, A raises the required allocation to $250,500, a $500 gap; B raises it to $251,000, a $1,000 gap. B's lower modeled annual fee does not pay its earlier onboarding invoice. Do not remove retained cash to conceal the gap or count it again as a recurring expense. Use the <a href="/tools/first-str-purchase-budget/">dated purchase-budget tool</a> and <a href="/blog/str-cash-reserves-seasonality/">receipt-and-reserve schedule</a>.</p>
<h2>Account permissions are not a transferable business</h2>
<p><a href="https://www.airbnb.com/help/article/1534">Airbnb's co-host permissions</a> distinguish full access from narrower calendar/messaging access. Permissions determine platform access, not your complete service agreement; changing permissions does not itself change co-host payouts. Separately, <a href="https://www.airbnb.com/help/article/1431">Airbnb's account-transfer guidance</a> says account ownership and reservations cannot be transferred to another host or account. Do not promise that buying a house or changing managers carries its account, bookings or reviews intact. Confirm listing ownership, contractual exit duties and a platform-compliant transition before underwriting inherited reservations. Never share passwords or unnecessary guest personal data to solve an access problem.</p>
<h2 id="tax">Management labels do not decide material participation</h2>
<p><a href="https://www.irs.gov/publications/p925">IRS Publication 925 (2025)</a> describes multiple material-participation tests. One requires more than 100 hours and at least as much participation as any other individual; a separate test requires more than 500 hours. Failure of the first does not prove failure of every test. Investor-only financial review generally does not count unless directly involved in day-to-day management or operations. Average customer use of seven days or less is a rental-activity classification exception, not automatic permission to offset W-2 income.</p>
<p>Ask a qualified independent tax adviser to evaluate actual tasks, credible records, other people's work and applicable loss limits. Neither a co-host label, a few hours each week nor a full-service agreement guarantees or automatically destroys a tax benefit. Do not manufacture tasks or hours to fit a test. Evaluate the purchase with a <a href="/blog/str-tax-benefit-shortfall-purchase/">smaller or absent tax benefit</a>, not an assumed refund funding management bills.</p>
<h2>Make the operating choice before approving the offer</h2>
<p>Proceed when written scope, local execution, owner responsibilities and the independently funded downside fit. Reprice a viable acquisition when supported operating costs change. Seek valid contract protection or a negotiated extension when a decisive quote or permission remains missing; counsel determines available rights. Decline a purchase dependent on an unverified manager forecast, unavailable owner time or unfunded opening invoices.</p>
<p><a href="/apply/">Discuss the shortlist with the completed fee-base register, task assignments and cash comparison</a>. Continue through the <a href="/blog/buy-str-high-income-large-tax-bill/">high-income buyer roadmap</a>. A large salary or tax bill does not establish that the property, manager or participation plan works.</p>
<div class="callout warn"><p>My BnB Accelerator, LLC is a real estate acquisition firm, not a CPA firm. <a href="https://aetaxadvisors.com/" target="_blank" rel="noopener">AE Tax Advisors</a> is an independent partner firm. Educational only, not legal, tax, lending or personalized investment advice. Primary documents reviewed October 7, 2026; Airbnb shows no publication date on these help pages. The IRS source is its currently published 2025 edition. Examples are hypothetical, not internal averages. No income, deduction, refund, return or indexing is guaranteed.</p></div>'''

FAQ = [
('How much does short-term rental management cost?', 'Obtain address-specific written quotes. Compare the defined fee base, service charges, opening costs and responsibilities in dollars; this guide does not establish a universal market rate.'),
('What fees should I check beyond the percentage?', 'Check onboarding, cleaning receipts versus invoices, supplies, vendor markups, coordination, reporting and termination. Separate included services from underlying bills and avoid counting either twice.'),
('What should I ask before signing a management agreement?', 'Confirm pricing authority, calendar control, local response, spending approvals, reporting access, exclusions, payment triggers and exit duties. Verify the actual operator and listing permissions rather than relying on a service label.'),
('Does full-service management automatically prevent an STR tax benefit?', 'No automatic conclusion follows from the label. Multiple participation tests and other loss limits can apply. Have an independent adviser evaluate actual work and records; co-hosting does not guarantee qualification either.')
]

if __name__ == '__main__':
 refresh('str-property-management-fees', 'STR Management Fees: Compare Quotes Before Buying', 'Short-Term Rental Management Fees', 'Compare STR management quotes before buying: fee bases, included work, decision rights, opening cash and a worked higher-percentage versus lower-cost example.', BODY, FAQ, '2026-08-11', 'data-management-fees-review-link', 'Compare the <a href="/blog/str-property-management-fees/">management quote register and service-fee cash worksheet</a>. Operating labels do not establish tax eligibility or a funded opening plan.')
 root = Path(__file__).resolve().parents[1]
 p = root/'blog/str-property-management-fees/index.html'
 s = subprocess.check_output(['node','--input-type=module','-e', "import {readFileSync} from 'node:fs'; import {expandPreclosingKeywords} from './preclosing_keywords.mjs'; const p='blog/str-property-management-fees/index.html'; process.stdout.write(expandPreclosingKeywords(readFileSync(p,'utf8'),p));"], cwd=root, text=True)
 p.write_text(s)
 minutes = re.search(r'<span>(\d+) min read</span>',s)[1]
 a=root/'blog/index.html'
 a.write_text(re.sub(r'<article class="post-card".*?</article>',lambda m: re.sub(r'<span>\d+ min read</span>','<span>'+minutes+' min read</span>',m[0]) if '/blog/str-property-management-fees/' in m[0] else m[0],a.read_text(),flags=re.S))
