"""Existing capacity reconciliation owner; no new acquisition URL."""
from refresh_dscr_purchase_methods import refresh

BODY='''<p class="lead">Before buying an STR, reconcile the intended guest count with rental permission, approved room use, applicable parking requirements, wastewater capacity and fire or building restrictions. Physical beds do not establish legal guest capacity. Parking spaces, bedrooms and system-design records also use different units: obtain the responsible authority's property-specific interpretation rather than taking the smallest raw number in a seller's folder.</p>
<p><a href="/apply/">Bring the capacity constraint worksheet to an acquisition call</a>. BNB Accelerator assists within its contracted scope; qualified independent reviewers and authorities determine actual restrictions and approvals.</p>
<h2>Translate each constraint into the same intended use</h2>
<p>Start with the proposed layout, guest count and rental use, then identify what each document actually measures. A permit might specify overnight occupants; a parking rule might specify vehicles or qualifying spaces; a wastewater record might describe bedrooms or design flow. These are not interchangeable quantities. Ask the relevant reviewer how the rule applies to this address, and record any unresolved conversion as unresolved.</p>
<p>A geographically limited primary example is <a href="https://www.washoecounty.gov/csd/planning_and_development/short_term_rentals/str_inspection_checklist.php">Washoe County's STR inspection checklist</a>, marked updated December 12, 2025 and reviewed here October 7, 2026. It separately checks off-street parking requirements determined in Accela for Tahoe, the layout and room use against the floor plan, and a posted maximum-occupancy placard. This demonstrates separate evidence checks, not a national parking-to-guest formula. Obtain the applicable current rules and approved record for the actual jurisdiction; this page does not certify a Washoe property.</p>
<p>Only after the constraints have been interpreted for the same use can you identify a binding guest limit. The tightest applicable restriction may control that proposed operation, but a list of numbers does not establish that operation is permitted at all. Check buyer eligibility, ownership-change treatment and private restrictions separately. Neither a seller's permit nor a furnished floor plan automatically supplies the buyer's approval.</p>
<h2>Complete a capacity reconciliation worksheet</h2>
<div class="table-wrap"><table><thead><tr><th>Constraint</th><th>Evidence and units</th><th>Question for the responsible reviewer</th></tr></thead><tbody>
<tr><td>Rental authorization</td><td>Address-specific issued record, permitted use and occupancy conditions</td><td>Does this buyer and proposed operation qualify under current rules?</td></tr>
<tr><td>Approved sleeping areas</td><td>Plans, actual room use and applicable completion records</td><td>Which rooms may support the proposed sleeping use?</td></tr>
<tr><td>Parking</td><td>Survey/site plan, assigned rights, dimensions and applicable rule</td><td>Which spaces count, and what restriction applies to intended occupancy?</td></tr>
<tr><td>Wastewater or utility limits</td><td>Actual approval/design records and qualified interpretation</td><td>What does the record allow for this rental use, rather than a guessed guest count?</td></tr>
<tr><td>Fire and building conditions</td><td>Applicable inspection findings, approved scope and acceptance evidence</td><td>Is proposed capacity supported without unresolved safety work?</td></tr>
<tr><td>Association or deed restrictions</td><td>Current governing documents and property-specific rights</td><td>Is the use restricted even if the public authority permits it?</td></tr>
</tbody></table></div>
<p>Add the document date, source, reviewer, unresolved question and transaction deadline to every row. Do not publish private occupant records, gate codes or seller information in the worksheet. Have counsel and appropriate specialists resolve conflicting documents; this register is not a legal determination or septic-design calculation.</p>
<p>For parking, distinguish an owned or assigned qualifying space from overflow, street parking, an access easement or a visually wide driveway. Ask whether the intended layout obstructs another unit, emergency access or required circulation. A manager's ability to squeeze in cars does not establish a permitted space. The <a href="/blog/parking-inspection-short-term-rental/">parking inspection owner</a> addresses physical evidence; this page reconciles constraints into the acquisition case.</p>
<h2>Example: fourteen beds do not prove fourteen guests</h2>
<p>Illustrative records only, not actual local rules: imagine a property with fourteen physical bed places, an issued rental record stating ten overnight occupants, and separate qualified reviews concluding that wastewater and parking each constrain the proposed use to eight guests. Assume all other requirements and buyer eligibility are independently established for the example. The supported purchase model would use eight, not fourteen or ten. Without those stipulated confirmations, eight is only another assumption.</p>
<p>Now imagine the seller proposes adding a parking space. If the independently applicable wastewater limit remains eight, solving parking alone does not establish ten-guest operation. Ask which constraint changes, what issued evidence changes it and whether another binding restriction remains. Do not spend money on a single improvement while pricing a capacity increase that still has no demonstrated approval path.</p>
<p>The <a href="/blog/certificate-of-occupancy-str-remodel/">proposed-work approval guide</a> separates existing from altered use. The <a href="/blog/str-fire-inspection-closing/">fire acceptance guide</a> separates correction work from required acceptance. Both support this reconciliation without replacing rental eligibility or the other reviewer. Fewer beds are not a universal cure for an unauthorized use.</p>
<h2>Worked purchase comparison: re-underwrite, not prorate</h2>
<p>All figures are hypothetical arithmetic, not market rates, lender terms, client outcomes or appraised values. For Property A, the seller's unsupported fourteen-guest scenario assumes $110,000 annual revenue, $42,000 distinct operating costs and $50,000 debt-service/property-tax/insurance/HOA cash obligations. That produces $18,000 annual owner cash before omitted capital work and tax consequences. The result is irrelevant as a supported base if fourteen guests are not permitted.</p>
<p>For an eight-guest sensitivity, assume separately researched inputs would instead be $82,000 revenue and $34,000 distinct operating costs, with the same $50,000 obligations. Owner cash becomes negative $2,000. These inputs require their own comparable-demand and expense evidence; the exercise does not establish that eight guests cause those amounts. Do not multiply revenue by eight divided by fourteen: guest segments, stay length, prices, occupied nights and costs need independent research.</p>
<div class="table-wrap"><table><thead><tr><th>Hypothetical annual case</th><th>Revenue</th><th>Distinct operating costs</th><th>Other modeled cash obligations</th><th>Owner cash</th></tr></thead><tbody>
<tr><td>A: unsupported fourteen-guest assumption</td><td>$110,000</td><td>$42,000</td><td>$50,000</td><td>$18,000</td></tr>
<tr><td>A: eight-guest sensitivity</td><td>$82,000</td><td>$34,000</td><td>$50,000</td><td>-$2,000</td></tr>
<tr><td>B: separate permitted-use alternative, assumed</td><td>$87,000</td><td>$35,000</td><td>$48,000</td><td>$4,000</td></tr>
</tbody></table></div>
<p>Property B's eligibility and economic inputs are also stipulated, not a verified listing. Its $6,000 modeled cash advantage over A's eight-guest sensitivity is not guaranteed superiority: condition, capital work, financing and evidence quality can change the decision. Operating costs exclude the taxes, insurance and HOA already in the other-obligation column. Debt service includes principal as a cash outflow, so these are not NOI or taxable-profit calculations.</p>
<p>At A's stipulated $34,000 operating costs and $50,000 obligations, $84,000 revenue would produce zero modeled annual owner cash before omitted items. That arithmetic is not a lender threshold or safe minimum. Actual costs change with use; an annual result also does not identify the month cash is needed.</p>
<h2>Price the improvement only for its demonstrated benefit</h2>
<p>For a separate initial-cash comparison, assume A needs $245,000 and B $255,000 for their respective purchase, closing, basic setup and a protected $35,000 reserve already included once. A is initially $10,000 cheaper. An additional $18,000 parking project would raise A's allocation to $263,000, or $8,000 above B. Assume it has no demonstrated guest-capacity benefit because another eight-guest restriction remains. This isolates the project; it does not establish that B is the better investment.</p>
<p>Do not subtract that one-time $18,000 again as an annual recurring cost. Separately evaluate any evidenced access, condition or risk benefit and actual ongoing maintenance. Obtain approvals and an accepted scope before assigning the project's benefit, and do not describe an extra space as a guaranteed occupancy or rate increase. Use the <a href="/tools/first-str-purchase-budget/">complete purchase-budget worksheet</a> for actual dated cash requirements and distinct repair or carrying costs omitted here.</p>
<p>Proceed when the documented permitted-use case and complete economics fit. Reprice a viable acquisition when constraints reduce the supported case. Delay only under available signed protection while a decisive record can arrive. Decline a transaction requiring unsupported capacity to meet the buyer's limits. Counsel determines contractual remedies; a lower guest count does not create automatic cancellation or refund rights.</p>
<p><a href="/apply/">Compare the shortlist using the completed constraint worksheet and permitted-use economics</a>. For <a href="/blog/buy-str-high-income-large-tax-bill/">high-income investors deploying substantial capital</a>, affordability does not justify pricing imaginary capacity. Keep unresolved limits visible before furnishing, offering or advertising the property.</p>
<p class="small">Washoe County primary checklist reviewed October 7, 2026, geographically limited as labeled. BNB Accelerator is the interested acquisition-service publisher; this is document-based education, not a site inspection, appraisal, engineering specification or approval. Not legal, engineering, tax, insurance, lending or personalized investment advice. All numerical assumptions are hypothetical. No permitted capacity, revenue, refund, financing, tax benefit or investment result is guaranteed.</p>'''

FAQ=[
('Do more beds establish a higher legal STR guest count?', 'No. Reconcile rental authorization, approved room use and other applicable restrictions for the intended operation; physical sleeping places do not establish permitted capacity.'),
('Should I take the smallest number in every capacity document?', 'Not mechanically. Spaces, bedrooms, design flow and overnight occupants use different units. Obtain property-specific interpretation for the same proposed use before identifying a binding guest limit.'),
('Does an added parking space increase STR occupancy?', 'Not automatically. Establish how it changes the actual applicable restriction and whether another binding limit or approval condition remains.'),
('How should a lower guest limit change purchase underwriting?', 'Research demand and complete costs for the supported use rather than prorating seller revenue by guest count. Compare another permitted-use acquisition and fund the dated cash requirements.')]

if __name__=='__main__':
    refresh('parking-occupancy-str-cap','STR Parking and Guest Capacity: Check Before Buying','How Should Parking Limits Set STR Guest Capacity?','Before buying an STR, reconcile parking, bedrooms and other guest limits. Use a capacity worksheet and lower-capacity purchase comparison.',BODY,FAQ,'2026-09-23','data-parking-capacity-review-link','Compare the <a href="/blog/parking-occupancy-str-cap/">capacity constraint worksheet and lower-guest-count acquisition case</a> before pricing physical beds as permitted occupancy.')
