"""Source-checked development of existing canonical comparison."""
from pathlib import Path
import re
R=Path(__file__).resolve().parents[1]
p=R/'compare/rabbu/index.html';s=p.read_text()
assert '"datePublished": "2026-08-15"' in s and '"dateModified": "2026-10-01"' in s
s=s.replace('"dateModified": "2026-10-01"','"dateModified": "2026-10-07"')
s=s.replace('Do you need market estimates, or a buyer-side process that turns estimates into a closed and launched property?', 'Compare Rabbu’s discovery tools and connected consultants with BNB’s actual acquisition scope—not a calculator with a paid engagement.')
s=s.replace('<td>Sourcing, underwriting and purchase-to-launch coordination</td>','<td>Published acquisition coordination, subject to signed scope</td>')
marker='<section class="section-sm"><div class="wrap wrap-narrow"><h2>Which option fits your first purchase?</h2>';assert s.count(marker)==1
body='''<section class="section-sm"><div class="wrap wrap-narrow"><h2>Current evidence: identify the party doing the purchase work</h2>
<p>Rabbu’s <a href="https://rabbu.com/" rel="noopener noreferrer">marketplace</a> presents historical income and modeled projections as different listing inputs, alongside agent, lender and concierge connections. Its current concierge destination is an <a href="https://rabbu.com/services/str-search" rel="noopener noreferrer">STR Search consultant profile</a>, describing market selection, shortlists, underwriting and launch guidance while retaining separate licensed agent and lender roles. Do not assume the platform and consultant are one contracting entity, or present the connected consultant as an entirely unrelated alternative.</p>
<p>The <a href="https://rabbu.com/airbnb-calculator" rel="noopener noreferrer">calculator documentation</a> describes editable comparables and gross revenue that excludes cleaning and specified platform/service/management fees. This is screening support, not confirmed seller receipts, net owner cash or legal-use approval. Neither a listing badge nor a public testimonial independently establishes the investment case for your address.</p>
<p>BNB’s <a href="/how-it-works/">published process</a> describes sourcing, underwriting, purchase coordination and designer/operator pairing. Final decisions and capital remain with the buyer; lender, legal/tax advisers and daily operator have separate roles. Ask for BNB’s actual signed scope too. This comparison has not authenticated an executed client contract for either route and does not establish provider fees, refund rights or guaranteed outcomes.</p>
</div></section><section class="section-sm"><div class="wrap wrap-narrow"><h2>Original work sample: move a discovered listing into an offer decision</h2>
<p>Ask the consultant or acquisition team to complete this evidence-to-offer register for one real candidate before relying on the initial screen. Keep each source, unresolved item, owner, due date and your approval in the file.</p>
<div class="bc-docs"><ol>
<li><strong>Receipts:</strong> Label history versus estimate, the dates covered, lodging versus cleaning/tax receipts and owner-use assumptions. Reconcile authorized seller records where supplied; do not publish guest or banking information. Explain excluded comparables rather than treating all nearby homes as interchangeable.</li>
<li><strong>Expenses:</strong> Replace placeholder insurance, tax, repair and operating costs with address-specific evidence. Identify excluded work, vendor invoices and platform/manager fees once. Name who updates the model when inspection changes the scope.</li>
<li><strong>Representation:</strong> Identify the consultant, broker and lender separately, along with compensation recipients, referral relationships, deliverables and payment triggers. Ask which fees survive a rejected candidate and which work transfers to the next search. Do not presume a free platform introduction includes paid execution.</li>
<li><strong>Permission and deadlines:</strong> Name who obtains municipal/HOA documents, escalates unresolved rights and monitors contract dates. Identify who delivers valid notices and who makes the final buyer decision. A sourcing team’s analysis does not itself create a cancellation right.</li>
<li><strong>Offer and launch:</strong> Show the cash ceiling and downside operating case separately. Name who submits an approved offer, accepts opening work and obtains a contracted operator. A service's estimate of speed is not a funded launch schedule.</li>
</ol></div>
<p>Use the <a href="/guides/str-service-responsibility-matrix/">responsibility matrix</a> for assignment and the <a href="/blog/reconcile-airbnb-payout-export/">seller payout guide</a> for history. Missing evidence calls for clarification, not an accusation about either firm. Preserve the buyer’s authority to decline an unsupported purchase.</p>
</div></section><section class="section-sm"><div class="wrap wrap-narrow"><h2>Worked cash ceiling: a price cut does not free its full amount</h2>
<p><strong>Hypothetical worksheet—not Rabbu or BNB pricing, a loan offer or a client result:</strong> Assume $270,000 spendable cash, a $600,000 property and a lender-approved structure requiring 25% down. Stipulate $18,000 closing charges, $30,000 furnishing, $20,000 repairs, $40,000 retained reserves and a fictional $10,000 acquisition-service charge. Fixed non-down-payment allocation is $118,000. With $150,000 down, total allocation is <strong>$268,000</strong>, leaving <strong>$2,000</strong>.</p>
<p>Inspection now identifies a distinct $18,000 repair increase, making fixed allocation $136,000 and total capital <strong>$286,000</strong>: <strong>$16,000 short</strong>. With all those fixed amounts and the 25% down structure unchanged, a $16,000 price reduction frees only $4,000 of down-payment cash. At $584,000, down is $146,000 and total is <strong>$282,000</strong>, still <strong>$12,000 short</strong>. The remaining price reduction lowers the loan amount, not closing-day cash.</p>
<p>The arithmetic cash ceiling is ($270,000 − $136,000) ÷ 25% = <strong>$536,000</strong>. That is a $64,000 price reduction to remove the $16,000 funding gap, under these stipulated assumptions. At that ceiling, $134,000 down plus $136,000 fixed allocation uses all $270,000; the assigned $40,000 reserve remains, but no additional cushion is left. This is not a market valuation, an acceptable offer recommendation or a prediction the seller will agree.</p>
<p>Actual lender terms, appraisal, rate, insurance, tax and price-linked closing charges can change with the price and property condition; re-underwrite them rather than treating this illustration as universal. A repair credit or escrow arrangement is not automatically available cash: have lender, title and advisers verify the actual treatment. Lower debt payments may improve a separately modeled operating case, but cannot be counted as an additional closing-day cash contribution. Keep reserves once, and do not assume a tax refund or projected bookings close the gap.</p>
<p>Ask each team to distinguish cash feasibility from purchase value and income durability. Reprice only with supported evidence and actual approval; retain valid contract protection while decisive evidence is unresolved. Use the <a href="/tools/first-str-purchase-budget/">purchase cash planner</a>. A financially infeasible candidate should not become acceptable merely because a platform estimate is attractive.</p>
</div></section><section class="section-sm"><div class="wrap wrap-narrow"><h2>Fair alternatives for the actual task</h2>
<p>For a separate analysis service, compare the chosen <a href="/compare/alternatives-to-str-insights/">STR Insights tier</a>; for brokerage with training/vendor support, examine <a href="/compare/avery-carl-short-term-shop/">The Short Term Shop</a>. Evaluate STR Search reached through Rabbu using its <a href="/compare/str-search/">existing direct comparison</a>, without assuming identical scope or fees. The <a href="/compare/alternatives-to-rabbu/">Rabbu alternatives owner</a> covers broader discovery paths and income-downside arithmetic; this direct page develops the evidence-to-offer work and price/cash ceiling. Browse the <a href="/compare/">comparison hub</a> for those distinct choices.</p>
</div></section>'''
s=s.replace(marker,body+marker)
s=s.replace('Provider facts summarized from <a href="https://rabbu.com/about" rel="noopener noreferrer">Rabbu’s public material</a>, reviewed 2026-10-01.','Document-based analysis of the linked Rabbu marketplace, calculator and consultant profile, reviewed October 7, 2026. This is not firsthand testing, a verified customer-experience review or analysis of unseen client agreements.')
p.write_text(s)
p=R/'sitemap-core.xml';s=p.read_text();s,n=re.subn(r'(<loc>https://www.bnbaccelerator.com/compare/rabbu/</loc>\s*<lastmod>)[^<]+',lambda m:m[1]+'2026-10-07',s);assert n==1;p.write_text(s)
