"""Existing STR research-method comparison; no new provider-variant page."""
from refresh_dscr_purchase_methods import refresh
from pathlib import Path

BODY = '''<p class="lead">Compare short-term rental data tools by the acquisition question they help you answer, not by which screen shows the highest revenue. A buyer considering an offer within zero to six months needs useful market evidence, an address-specific decision file and people responsible for unresolved diligence. A subscription, free listing research and an acquisition engagement can each help, but they are not interchangeable deliverables.</p>
<p>BNB Accelerator is the publisher and an interested acquisition-service provider. This is public-document analysis and an original buyer worksheet, not firsthand software testing, an independent ranking or a customer review. No provider accuracy score or universal winner is established. <a href="/apply/">Discuss the candidate property with your evidence register and named diligence responsibilities</a>.</p>
<h2 id="good">What the tool actually documents</h2>
<p><a href="https://help.airdna.co/en/articles/10559022-rentalizer-revenue-calculator">AirDNA's Rentalizer guide</a>, dated June 19, 2026, describes address-level projections, editable bedroom/bath/guest capacity, configurable comparable sets, amenity filters and monthly ranges. It also describes entering operating and startup costs. This supports evaluating the tool as an input to property analysis, not categorically dismissing all data products as screening-only or unable to consider amenities.</p>
<p>The documented projection assumes full 365-day availability and includes cleaning fees. Save the exact report version and reconcile availability, period and fee definitions with the buyer's intended use. The provider describes Comp Set Strength using variability within the chosen comparisons; that is not independent confirmation of legal use, building condition or a promised forecast outcome. Default expense inputs need address-specific evidence, even when a calculator lets you edit them.</p>
<p>This is one documented example, not a claim that every product has the same features. Ask any other provider for its actual methodology, covered channels, data period, geography, availability definition, export options and service tier. More products agreeing on a headline number does not necessarily provide independent evidence: find out whether they share source data or assumptions before treating agreement as corroboration.</p>
<h2 id="bad">What a report does not settle for this purchase</h2>
<p>Match the subject's lawful capacity, location, amenities, access and operating calendar to the actual comparison set. Record each exclusion and the reason for any adjustment. No fixed count of ten, fifteen or twenty listings is a universal quality test. A small relevant set can be more informative than a large mismatched one, while sparse evidence may justify a wider downside rather than false precision. Do not select only the most successful listings and call the result a typical property.</p>
<p>Resolve permission with current address-specific records and qualified local advice, not the presence of a listing in a data product. Obtain suitable insurance, physical diligence, taxes, management scope and financing terms from the responsible professionals. A publicly visible property can still leave these questions unanswered. Review <a href="/blog/str-regulations-before-you-buy/">rental permission diligence</a> and <a href="/blog/airbnb-insurance-guide/">insurance for the actual use</a> rather than assuming a research subscription handles them.</p>
<p>Reviews and listing photos can reveal questions to inspect, but a review count does not prove a specific revenue advantage. Amenity prevalence is not evidence that adding that amenity creates a certain return. Track supply with consistent geography, platform coverage and active-listing definitions; a historical count is not a guaranteed leading indicator of future revenue. Use the <a href="/blog/airbnb-market-saturation/">market saturation guide</a> as a separate question, not a substitute for a supported purchase case.</p>
<h2 id="use">Compare three research paths on the same decision file</h2>
<div class="table-wrap"><table><thead><tr><th>Path</th><th>Possible buyer fit</th><th>Responsibility to document</th></tr></thead><tbody>
<tr><td>Public listing research plus local professionals</td><td>Buyer can collect evidence and coordinate deadlines</td><td>Who verifies calendars, permission, condition and costs; which tasks require paid work?</td></tr>
<tr><td>Paid analytics plus the buyer's team</td><td>Buyer needs documented comparables, structured exports or repeatable screening</td><td>Exact report scope, assumptions, access terms and remaining address checks</td></tr>
<tr><td>Contracted acquisition assistance</td><td>Buyer wants specified sourcing, analysis and transaction coordination</td><td>Named deliverables, professional handoffs, fees, exclusions and approval rights</td></tr>
</tbody></table></div>
<p>Start with one candidate address, available capital, financing assumptions, intended use and offer deadline. For each path, assign a person, evidence source, cost and due date to every unresolved issue. Ask whether the same deliverable is included, optional or outside scope; do not compare a free calculator with a full service proposal as if only price differs. Account for buyer time and specialists, without inventing a standard value for that time.</p>
<p>The existing <a href="/compare/alternatives-to-airdna/">AirDNA alternatives</a>, <a href="/compare/rabbu/">Rabbu service-tier comparison</a> and <a href="/compare/alternatives-to-rabbu/">Rabbu alternatives</a> cover broad provider choices. Verify their current written offers directly. This article instead compares evidence and responsibilities; it does not add another brand-swapped alternative page or claim BNB Accelerator replaces the underlying records.</p>
<h2 id="free">Public calendars: an observation, not booked demand</h2>
<p><a href="https://www.airbnb.com/help/article/3612">Airbnb's blocked-night guidance</a> identifies availability rules, linked calendars, pending or canceled requests and other reasons nights can be unavailable. Thus a blocked public calendar six months out is not direct proof of paid reservations or demand depth. The reason may require authorized host-side records. Do not impersonate a guest, create a fake reservation or request unnecessary guest personal information to test it.</p>
<p><a href="https://www.airbnb.com/help/article/2715">Airbnb's professional-hosting definitions</a> separately identify booked nights, available nights, blocks and check-ins. Record the screenshot date and exact stay settings used in a public search. A lack of availability for one date combination is not an occupancy measurement, nor does an available night show what rate would actually sell. Request properly authorized, redacted reservation and payout evidence for the seller's own property; comparisons may remain estimates.</p>
<h2>A worked calendar-evidence comparison before an offer</h2>
<p>Invented arithmetic only, not a real listing, provider test, market forecast or client result. Suppose a buyer sees 30 unavailable nights in a 90-night window and multiplies them by an assumed $300 lodging rate. That creates a $9,000 figure, but neither paid nights nor realized rate is established by the public calendar. A screenshot of another property cannot establish the subject's revenue.</p>
<p>For a separate fictional seller-owned property with authorized records, assume the team classifies those 30 nights as ten confirmed reserved nights, twelve owner-use nights and eight preparation nights. At a stipulated $300 lodging rate, the ten reservations total $3,000 before cancellation, refunds, fees or receipt timing. The other twenty unavailable nights do not create another $6,000 of reservations. This is not proof of cleared cash, and it is not a forecast for the 60 remaining nights.</p>
<p>To isolate the effect of the unsupported $6,000 difference, assume distinct non-cleaning variable outflows equal 20% of lodging revenue and all other costs stay unchanged. The contribution difference would be $4,800, not $6,000. Do not call that difference a provider error, estimate annual revenue by multiplying this window, or infer a reserve requirement without bill dates. Use the <a href="/blog/airbnb-revenue-projections/">full revenue-to-owner-cash worksheet</a> and <a href="/blog/reconcile-airbnb-payout-export/">seller payout reconciliation</a> for the separate forecast and cleared-receipt work.</p>
<h2>Buy useful evidence, not a reassuring number</h2>
<p>For each purchase question, label the answer verified, modeled, observed but unexplained, or missing. Record what would change the maximum offer or prevent closing. Select the research path that can complete necessary work within the actual transaction window and your available budget. Free access may still require paid inspections, professional advice or substantial time; a subscription or engagement fee alone does not establish completeness.</p>
<p>Proceed only when supported economics, permission and funded opening cash fit. Reprice a viable asset when evidence changes costs or income. Seek valid contract protection or a negotiated extension for missing decisive records; counsel determines rights and deadlines. Decline a purchase that requires unexplained blocks or a projected tax benefit to become booked income. <a href="/apply/">Bring the completed evidence register and remaining professional handoffs to an acquisition discussion</a>, with the <a href="/tools/first-str-purchase-budget/">complete cash budget</a> and <a href="/blog/buy-str-high-income-large-tax-bill/">high-income buyer roadmap</a>.</p>
<div class="callout warn"><p>My BnB Accelerator, LLC is an acquisition firm, not a CPA firm. <a href="https://aetaxadvisors.com/" target="_blank" rel="noopener">AE Tax Advisors</a> is an independent partner. Primary documents reviewed October 7, 2026; cited Airbnb help pages display no publication date. Educational only, not personalized investment, lending, legal or tax advice. All example figures are hypothetical. No permit, financing, revenue, tax benefit or return is guaranteed.</p></div>'''

FAQ = [
 ('Are short-term rental data tools accurate?', 'This review does not establish a universal accuracy result. Check the actual methodology, comparable selection, period and definitions, then verify address-specific permission, condition and costs separately.'),
 ('Do blocked Airbnb calendars prove booked demand?', 'No. Nights can be unavailable for settings, linked calendars, pending or canceled requests and other reasons. Public availability alone does not establish paid reservations, realized rates or cleared receipts.'),
 ('How should I compare STR research alternatives before buying?', 'Use one property and decision file. Assign an evidence source, responsible person, cost and deadline to each unresolved purchase issue, comparing actual product or service scope rather than brand labels alone.'),
 ('Does free research always beat a paid data tool?', 'No universal winner is established. Compare what each path verifies and what remains missing, including professional work and buyer time. A lower access fee does not prove a complete acquisition decision.')
]

if __name__ == '__main__':
 BODY = BODY.replace('/blog/airbnb-market-saturation/', '/blog/str-market-saturation/')
 refresh('str-market-research-tools', 'STR Data Tools: Compare Evidence Before Buying', 'Short-Term Rental Data Tools', 'Compare STR data tools, free listing research and acquisition help before buying. Use a calendar-evidence worksheet and document who verifies each input.', BODY, FAQ, '2026-08-11', 'data-tools-evidence-review-link', 'Use the <a href="/blog/str-market-research-tools/">research-path comparison and calendar-evidence exercise</a> before treating unavailable nights or a subscription report as a complete purchase decision.')
 p=Path(__file__).resolve().parents[1]/'blog/str-market-research-tools/index.html'
 s=p.read_text()
 if '<span>Updated October 7, 2026</span>' not in s:
  s=s.replace('<span>Published August 11, 2026</span><span>&middot;</span>', '<span>Published August 11, 2026</span><span>&middot;</span><span>Updated October 7, 2026</span><span>&middot;</span>', 1)
 p.write_text(s)
