"""Single existing purchase-guide refresh; no family or homepage generator."""
import re
import expand_hold_period as publisher
SLUG='septic-system-buying-short-term-rental'
TITLE='Buying a Property With Septic System | STR Owner Guide'
H1='Buying a Property With Septic System'
DESC='Buying an STR with septic? Verify approved use, inspection scope and drainfield access; compare a feasible repair with lower-capacity and funding alternatives.'
FAQ=[
 ('Does a recent septic pumping receipt prove the system is suitable for an STR?','No. It documents a service event, not complete condition, drainfield performance, legal capacity or suitability for the proposed guest and laundry load. Obtain the defined specialist scope and authority response.'),
 ('Can the listing’s bed count establish septic capacity?','No. Reconcile the actual approved system and proposed use with the controlling authority and qualified professionals. Bedroom, wastewater and rental limits are separate evidence questions.'),
 ('Can a seller credit solve an unsuitable septic system?','Not by itself. Establish a feasible authorized correction, complete scope, payment dates and financing treatment. A credit does not create site area, approval or guest capacity.'),
 ('Should a septic repair quote be added to an existing allowance in full?','Replace the same scope once and add only distinct review, work and net carrying costs. Preserve the intended reserve and keep unknown feasibility or approval explicitly unresolved.')
]
BODY='''<p class="lead">Before buying a property with a septic system for STR use, resolve three separate questions: what is approved, what the qualified inspection actually supports and whether the proposed guest operation fits the site. A tank that was recently pumped is not a documented drainfield assessment. Beds in listing photographs are not wastewater capacity. For a purchase within zero to six months, use the actual records and professional findings to compare a feasible correction, a genuinely lawful lower-capacity operation and another property before the contract protections expire.</p>
<p><a href="/apply/">Discuss the septic evidence and funded purchase alternatives with BNB Accelerator</a>. High income or an expected tax benefit does not fund an unknown replacement or authorize a larger guest count.</p>
<h2>Make septic purchase diligence a records-to-use decision</h2>
<p>EPA’s currently hosted <a href="https://www.epa.gov/sites/default/files/2017-08/documents/170803-homebuyerssepticguide_508c.pdf">New Homebuyer’s Guide to Septic Systems</a> recommends obtaining available as-built records and a septic-service-provider inspection before purchase. Its inspection discussion includes records, tank and pipe condition, drainfield signs and the distribution box. The guide was issued August 2017; it is not a new 2026 inspection standard, life guarantee or current fee schedule. Have local professionals specify the actual transaction scope.</p>
<p>Request the health or permitting authority’s available installation approval, as-built plan, approved design basis, changes, notices and completion records, plus seller maintenance, pumping and repair history. Match parcel and component identifiers to the property being conveyed. Ask what records do not exist or could not be found. Missing paperwork is an unresolved question, not automatic proof of an illegal system or a reason to assume compliance.</p>
<div class="table-wrap"><table><thead><tr><th>Purchase evidence</th><th>Question to resolve</th><th>Responsible reviewer</th></tr></thead><tbody>
<tr><td>Approval and installed configuration</td><td>Do the actual system, additions and proposed use match reviewed records?</td><td>Controlling authority and qualified septic professional</td></tr>
<tr><td>Inspection scope and limitations</td><td>Which components were located, accessed and assessed; what remains unverified?</td><td>Qualified inspecting provider</td></tr>
<tr><td>Guest and turnover load</td><td>Does the planned occupancy, laundry and other use fit supported capacity?</td><td>Authority, design professional and buyer’s operations reviewer</td></tr>
<tr><td>Drainfield and future work area</td><td>Where are the actual field, service routes and any required repair/reserve area?</td><td>Specialist, surveyor and applicable authority</td></tr>
<tr><td>Correction and funding</td><td>Is the remedy feasible, authorized, priced and payable before opening?</td><td>Designer, contractor, lender and transaction counsel</td></tr>
</tbody></table></div>
<p>Give each row a document date, unresolved item and decision deadline. A report that says no failure was observed under the inspection conditions does not guarantee remaining life, performance at a different load or approval for the planned rental. Ask the provider to explain the limits in writing; do not expand a limited observation into a certification.</p>
<h2>Reconcile guest capacity separately from bed and bedroom claims</h2>
<p>Show the actual proposed rental use to the relevant authority and specialist: guest count, bedrooms being used, turnover pattern, laundry location, seasonal operation and planned changes. Ask how the governing approval and rules treat those facts. This guide provides no universal guests-per-bedroom ratio, gallons-per-guest conversion or assumption that adding a bigger tank authorizes more guests. Zoning, building, fire, rental and wastewater requirements can constrain different parts of the plan.</p>
<p>Original hypothetical question: a listing markets twelve sleeping places, while the available system file describes a three-bedroom design. Those facts require review; they do not let this article declare twelve guests permitted or prohibited. Ask professionals to resolve the real configuration and load. If the supported operating plan is smaller than the listing claim, rebuild the revenue case using suitably matched evidence, not a proportional deduction from seller gross revenue.</p>
<p>The <a href="/blog/converted-bedroom-count-before-buying-str/">converted-bedroom guide</a> addresses lawful rooms; the <a href="/blog/septic-pumping-occupancy-cost/">septic load note</a> addresses occupancy and maintenance evidence. Keep those questions connected without treating either as a permit. Ask the lender and insurer how material findings affect their actual approval. A lower guest count cannot cure an unresolved defect merely because the financial forecast looks acceptable.</p>
<h2>Protect the site footprint and obtain a real inspection scope</h2>
<p>EPA’s current <a href="https://www.epa.gov/septic/how-care-your-septic-system">septic care guidance</a> warns against parking or driving on a drainfield and directs owners to keep excess drainage away. It also links household water use and concentrated laundry to system load. For the acquisition, plot actual guest parking, contractor access, grading and drainage against the professionally located components and any required future work area. Do not put a hot tub, driveway or construction staging on an assumed spare lawn.</p>
<p>Ask the designer and controlling authority whether future repair or replacement has an executable path on this site. A reserved area drawn on an old plan is not permission for the buyer’s new work. Easements, setbacks, wells, boundaries and aquatic resources can need separate review. The <a href="/blog/wetlands-before-buying-str/">wetlands work-footprint guide</a> explains why a screening map cannot establish that path. Do not invent a replacement design, soil suitability or site clearance yourself.</p>
<p>Scope the inspection before ordering. Ask which records, tank, distribution components, pumps, controls and field observations the qualified service includes, and what access or seller cooperation is required. If pumping, further testing or excavation is appropriate, professionals must determine its sequence and safe scope. Do not enter a tank, remove covers, handle wastewater, run improvised load tests or sample during a showing. Keep guests away from unresolved health or safety conditions.</p>
<p>Compare corrective bids on the same documented design, approvals, installation, electrical work, access, removal, restoration, inspection and completion conditions. Keep exclusions visible. A tank-only number may not price a field problem. Counsel must address actual seller completion, credits or holdbacks; the lender and closing team must confirm treatment. Neither a credit nor a promise establishes capacity or guarantees that correction can occur by closing.</p>
<h2>Worked purchase cash test: replace the allowance once</h2>
<p>Original hypothetical arithmetic only, not market prices, an inspection result, a repair recommendation or a client outcome. Assume $300,000 designated accessible cash. The initial plan allocates $220,000 to purchase equity and closing, $25,000 to launch spending and $35,000 to retained liquidity. The $280,000 total leaves $20,000 outside the plan. The reserve remains cash, not another expense.</p>
<p>Assume the $25,000 setup line already includes a $3,000 septic allowance plus $22,000 other work. Qualified professionals establish a feasible authorized $12,000 corrective scope replacing that allowance. New setup is $34,000, not $37,000. A separately identified $2,000 specialist/design review is not already in either scope.</p>
<div class="table-wrap"><table><thead><tr><th>Hypothetical case</th><th>Allocation preserving $35,000 reserve</th><th>Cash outside plan</th></tr></thead><tbody>
<tr><td>Original allowance, not verified feasibility</td><td>$220,000 + $25,000 + $35,000 = $280,000</td><td>$20,000</td></tr>
<tr><td>Replace allowance with defined correction</td><td>$220,000 + $34,000 + $35,000 = $289,000</td><td>$11,000</td></tr>
<tr><td>Add distinct specialist/design review</td><td>$291,000</td><td>$9,000</td></tr>
<tr><td>Add $10,000 distinct net carrying outflows</td><td>$301,000</td><td>$1,000 funding gap</td></tr>
</tbody></table></div>
<p>The delay input includes only additional net bills not already budgeted. Do not add lost hypothetical gross bookings as another bill. Using the reserve to cover the gap leaves $34,000, not the selected $35,000 cushion. Tax savings, future guest revenue and later seller reimbursement are not accessible starting cash here. A real transaction must reconcile costs and payment dates from accepted terms.</p>
<p>A smaller lawful operating plan is an alternative only if condition, authority, lender and insurer conclusions support it. Compare independent capacity-matched revenue and recurring costs, not an assumed repair saving or linear guest premium. Another property might avoid this correction but needs its own complete diligence. If feasibility remains unknown, the $12,000 placeholder does not bound replacement risk. Use the <a href="/tools/first-str-purchase-budget/">purchase budget worksheet</a> and decline to call an unresolved plan funded.</p>
<h2>Hand off a supported operation, not a generic service schedule</h2>
<p>Before closing, assign responsibility for specialist service, actual required inspections, records, alarms where installed, manager escalation and safe reopening after problems. EPA’s household guidance explains that service needs vary with wastewater, solids, tank size and system type. Do not paste a generic household pumping interval into a high-turnover STR agreement. Ask the provider and authority for the property-specific plan and price it separately from initial correction.</p>
<p>Proceed when approval, condition, proposed use, service access, feasible work and dated funds align. Renegotiate a defined feasible correction through valid terms. Delay under adequate contract protection when decisive evidence is missing. Decline unsupported capacity or unbounded work that drives the acquisition case. Do not invent termination, inspection or extension rights.</p>
<p><a href="/apply/">Compare the property with an evidence-backed STR shortlist</a>. Bring a non-sensitive memo with the approved configuration, provider scope, proposed load, site constraints, corrective path and funded alternatives; keep full reports and private seller records in agreed channels. BNB Accelerator coordinates acquisition work within its agreement; authorities and qualified septic, design, legal, lending, insurance and tax professionals make their own conclusions. See the <a href="/blog/buy-str-high-income-large-tax-bill/">high-income buyer roadmap</a> for other purchase gates.</p>
<p class="small">EPA primary materials checked October 7, 2026. Homebuyer PDF issued August 2017; current care page updated August 17, 2026. No old nationwide fee or lifespan estimate reused. Educational only, not septic design, environmental, health, engineering, permitting, legal, lending, insurance, tax or personalized investment advice. Examples are invented; no approval, useful life, repair result, tax benefit, booking or investment result is guaranteed.</p>'''
if __name__=='__main__':
 si=publisher.ROOT/'sitemap/index.html';old=si.read_text();label=re.search(r'(<a href="/blog/'+SLUG+r'/">)[^<]+',old)[0]
 publisher.SLUG,publisher.TITLE,publisher.H1=SLUG,TITLE,H1
 publisher.DESC,publisher.BODY,publisher.FAQ=DESC,BODY,FAQ
 publisher.main('2026-09-22','data-septic-purchase-review-link','Before buying with septic, compare the <a href="/blog/septic-system-buying-short-term-rental/">approval/condition/load evidence register and funded corrective-work alternatives</a>. A pumping receipt or price credit is not verified capacity.')
 si.write_text(re.sub(r'(<a href="/blog/'+SLUG+r'/">)[^<]+',lambda m:label,si.read_text()))
 p=publisher.ROOT/'blog'/SLUG/'index.html';s=p.read_text();needle='<span>Published September 22, 2026</span>'
 assert s.count(needle)==1
 if '<span>Updated' not in s:
  p.write_text(s.replace(needle,needle+'<span>&middot;</span><span>Updated October 7, 2026</span>',1))
