"""Scoped substantive refresh of the existing alternatives owner."""
from pathlib import Path
import re
ROOT=Path(__file__).resolve().parents[1]
p=ROOT/'compare/alternatives-to-the-short-term-shop/index.html'
t=p.read_text();assert 'reviewed 2026-10-01' in t
t=t.replace('"dateModified": "2026-10-01"','"dateModified": "2026-10-07"')
marker='<section class="section-sm"><div class="wrap wrap-narrow"><h2>Choose before you sign</h2>'
assert t.count(marker)==1
body='''<section class="section-sm"><div class="wrap wrap-narrow"><h2>Do not reduce the brokerage route to property showings</h2>
<p>The Short Term Shop’s <a href="https://theshorttermshop.com/how-to-buy-a-short-term-rental/" rel="noopener noreferrer">March 11, 2026 buying guide</a> describes STR-focused representation, post-closing training and vendor connections. That can be useful for a buyer who already knows the market. It does not establish the exact deliverables in your individual engagement. Ask whether revenue analysis, local-use evidence and launch support mean advice, introductions or contracted execution.</p>
<p>Compare that proposal fairly with an analysis-led <a href="/compare/alternatives-to-str-insights/">STR Insights tier</a>, a <a href="/compare/alternatives-to-str-search/">STR Search matching engagement</a>, or BNB Accelerator’s <a href="/how-it-works/">published coordination process</a>. Each may close a different gap. The actual signed scope—not the provider label—determines responsibilities. This page does not verify an executed BNB or competitor contract.</p>
<div class="bc-docs"><h3>Ask for this same-property work sample</h3><ol>
<li><strong>Representation:</strong> Identify the licensed representative, territory, duration, exclusivity, agreed compensation and termination provisions. Use the <a href="/blog/str-buyer-agent-vs-acquisition-team/">buyer-agent versus acquisition-team guide</a> for the broader distinction.</li>
<li><strong>Decision memo:</strong> Request one candidate’s evidence-backed revenue and expense assumptions, missing permit or HOA evidence, financing constraints and an explicit buyer approval step. An analyst’s recommendation is not your authorization to waive a contingency.</li>
<li><strong>Fee register:</strong> List each brokerage, analysis and coordination charge, who receives it, when it is earned and what survives a failed purchase. Record any referral relationship and documented offset; never assume one fee cancels another.</li>
<li><strong>Launch handoff:</strong> Ask who orders furnishings, approves spend and verifies operating readiness. Separate a vendor introduction from management of that vendor’s work. Keep independent lender, legal, tax and operator responsibilities visible in the <a href="/guides/str-service-responsibility-matrix/">responsibility matrix</a>.</li>
</ol></div>
<p>The <a href="https://www.nar.realtor/the-facts/consumer-guide-to-negotiating-written-buyer-agreements" rel="noopener noreferrer">National Association of REALTORS® consumer guide</a> explains that buyer-agreement services and compensation are negotiable, and seller-paid agent compensation can be requested rather than presumed. It also cautions that agreement changes and termination depend on the contract and applicable law. Ask your agent and attorney how your actual agreement works.</p>
</div></section><section class="section-sm"><div class="wrap wrap-narrow"><h2>Worked cash comparison: broker compensation is not a launch budget</h2>
<p><strong>Fictional illustration only—not standard commissions, provider prices or a client result:</strong> A $700,000 purchase with an assumed 75% loan needs $175,000 down. Add $18,000 closing costs, $30,000 furnishings, $12,000 repairs and $40,000 retained reserves: <strong>$275,000</strong> before brokerage or separate acquisition-service compensation. Here the closing-cost estimate excludes those separately listed fees.</p>
<p>Assume a fictional negotiated buyer-broker fee of $14,000. If the transaction documents provide $10,500 from another party toward that fee, and the lender and closing professionals confirm that treatment, the buyer’s remaining fee is $3,500. Base cash becomes <strong>$278,500</strong>. That payment is not an extra $10,500 available for furniture; it addresses the broker fee once.</p>
<p>Route A adds an invented $9,000 quote for independent analysis and launch coordination: <strong>$287,500</strong>. Route B uses an invented $12,000 broader coordination quote instead, covering the same work: <strong>$290,500</strong>. Both retain the same $3,500 buyer-broker balance. Do not add Route A’s $9,000 to Route B if that work is included. With $290,000 deployable cash, Route A leaves $2,500 outside the allocation and Route B is $500 short. A real scope advantage must be evaluated separately; a larger fee does not prove better support.</p>
<p>If the $10,500 other-party payment is not obtained, those routes require <strong>$298,000</strong> and <strong>$301,000</strong>: short by $8,000 and $11,000 against the same cash limit. Confirm payment commitments before relying on them. Keep the $40,000 reserve intact and count it once. Revise the candidate, financing or actual scope if the budget fails; do not fill the gap with projected revenue or a hoped-for tax benefit. Use the <a href="/tools/first-str-purchase-budget/">purchase cash worksheet</a> with your real closing estimates and signed quotes.</p>
</div></section>'''
t=t.replace(marker,body+marker)
t=t.replace('Provider facts summarized from <a href="https://theshorttermshop.com/how-to-buy-a-short-term-rental/" rel="noopener noreferrer">The Short Term Shop’s public material</a>, reviewed 2026-10-01.','Document-based analysis of the linked Short Term Shop buying guide and NAR consumer guidance, reviewed 2026-10-07. This is not firsthand testing or a verified customer-experience review. Provider claims are not independently established outcomes; obtain current written proposals.')
p.write_text(t)
p=ROOT/'sitemap-core.xml';t=p.read_text()
t,n=re.subn(r'(<loc>https://www.bnbaccelerator.com/compare/alternatives-to-the-short-term-shop/</loc>\s*<lastmod>)[^<]+(</lastmod>)',r'\g<1>2026-10-07\2',t);assert n==1;p.write_text(t)
