"""Scoped expansion of an existing operating-model purchase resource."""
from pathlib import Path
import re
R=Path(__file__).resolve().parents[1]
p=R/'guides/kleer-circle-year-one-operations/index.html';s=p.read_text()
assert '"datePublished": "2026-10-01"' in s and '"dateModified": "2026-10-01"' in s
s=s.replace('"dateModified": "2026-10-01"','"dateModified": "2026-10-07"')
rows=[('What work stays with me?','Task schedule separating automated messages, human decisions and on-site work','Accept only duties with a named person and a defined escalation path'),('Who covers nights and holidays?','Primary and backup acceptance, unavailable periods, dispatch limits and price','Close critical coverage gaps before relying on the operating plan'),('What does self-operation really cost?','Same-property cost sheet: software, coverage, labor and excluded services','Compare complete accepted scopes, not a platform subscription with a manager fee'),('Can I change the year-one model?','Written approval, affected support, revised fees and effective date','Do not treat a future introduction as an approved first-year exception')]
for q,e,g in rows:
 old=f'<tr><th scope="row">{q}</th><td>Document / clause / named owner</td><td>Resolved before payment or offer</td></tr>'
 assert s.count(old)==1;s=s.replace(old,f'<tr><th scope="row">{q}</th><td>{e}</td><td>{g}</td></tr>')
marker='<section class="section-sm"><div class="wrap wrap-narrow"><h2>Continue your buyer comparison</h2>'
assert s.count(marker)==1
body='''<section class="section-sm"><div class="wrap wrap-narrow"><h2>What the current public offer establishes—and what it does not</h2>
<p>Kleer Circle's <a href="https://kleercircle.com/">public service page and management FAQ</a>, reviewed October 7, 2026, describe acquisition and launch coordination, a self-management playbook in year one, configured messaging and pricing tools, and later management introductions. This is a public-description reading, not firsthand testing or inspection of a signed customer agreement. The description does not establish who accepts emergency responsibility for your candidate property, an agreed response time, a backup's availability or your actual operating costs. Ask for those answers in your own proposal.</p>
<h2>Build a duty-and-availability sheet before choosing a property</h2>
<p>Use one row per consequential duty, not one row labeled “self-manage.” Start with guest-message triage, physical access problems, cleaning acceptance, repair authorization, pricing decisions and financial record reconciliation. For each, record the trigger, necessary human action, remote or local location, primary person, backup, unavailable periods, spending authority, escalation contact and accepted cost. These are original buyer planning fields, not a claim about Kleer Circle's contracted deliverables.</p>
<p>Separate notification from completion. An automatic access message can send instructions; it does not prove a guest can enter or identify who is allowed to authorize a locksmith. A cleaner may report a fault without accepting repair dispatch. Request explicit acceptance from each proposed support person, including geography, hours, exclusions and how to contact them. Do not invent universal response-time standards or assume a provider referral has accepted the job. For an actual emergency, use appropriate emergency services; a buyer planning exercise is not an emergency procedure.</p>
<h2>Original worked coverage-gap test</h2>
<p><strong>Invented pre-purchase scenario, not a client result or recommended service standard:</strong> buyer A can handle remote decisions except Tuesday and Thursday from 6–10pm. Proposed backup B can cover Tuesday but is also unavailable Thursday. The cleaner accepts cleaning checks but has not accepted access or repair duties. Automated messages remain active. The sheet therefore shows a four-hour Thursday gap for human decisions; it does not show coverage simply because messages are scheduled.</p>
<p>Assume a prospective local support provider offers Thursday coverage for $90 per four-hour window and requires a separate $150 dispatch charge for each accepted callout. For 12 distinct weekly windows and two callouts, the illustrative incremental cost is (12 × $90) + (2 × $150) = $1,380. These are invented quotes, not Kleer Circle prices or market averages. Twelve weeks is a defined planning period, not a full-year budget; repairs, parts, software and other excluded work remain separate. Do not count dispatch twice if your real availability price already includes it.</p>
<p>The gap closes only if the proposed person actually accepts the property, window, duties and authority. A quote without acceptance still leaves it unresolved. If that support arrangement is inconsistent with the actual year-one agreement, ask for written clarification or an approved change before relying on it. If the buyer cannot establish an acceptable plan, reconsider the property, operating arrangement or timing with the retained advisers. This exercise does not assume guests can be displaced, deadlines extended or agreements cancelled without consequences.</p>
<h2>Compare operating models on the same purchase decision</h2>
<p>Build separate complete budgets for owner operation and a proposed management arrangement using the same address, opening assumptions and period. Under owner operation, distinguish provider acquisition fees from software, local coverage, cleaning, maintenance, recordkeeping and the buyer's remaining duties. Under management, request the calculation base, minimums, onboarding, pass-through costs, excluded work and retained owner duties. Mark unknowns rather than silently assigning them zero. A lower known subtotal cannot settle which arrangement costs less when material obligations are missing.</p>
<p>Keep time feasibility separate from tax suitability. Being available for four hours, paying a backup, or completing this sheet is not four hours of qualifying participation. Do not count another person's work as your own or assume a self-management label guarantees a deduction. Give your own qualified tax adviser accurate actual work records and the proposed operating structure. <a href="https://www.irs.gov/publications/p925">IRS Publication 925</a>, reviewed October 7, 2026, discusses evidence of services performed and approximate hours, not this availability worksheet as an eligibility test. This guide makes no eligibility, tax-savings or investment-return conclusion.</p>
<h2>Get a decision-ready exception, not an informal reassurance</h2>
<p>If you require full management immediately, state that before paying for an acquisition program or relying on a candidate. Request the actual approver, allowed arrangement, effective date, affected services, added fees and continuing buyer duties in writing. An introduction promised later is not approval today. No signed agreement was reviewed here, so this worksheet creates no amendment, refund, cancellation or outsourcing right.</p>
<p>For the broader choice, the existing <a href="/blog/bnb-accelerator-vs-kleer-circle-str-buyer/">BNB Accelerator versus Kleer Circle buyer comparison</a> covers acquisition scope and operator-versus-manager economics. Use <a href="/compare/alternatives-to-kleer-circle/">named alternatives</a> for fair buyer-fit options and the <a href="/guides/str-service-responsibility-matrix/">service responsibility matrix</a> to request BNB Accelerator's own actual scope rather than assume it accepts ongoing operations. These complementary owners answer different questions; this resource is the pre-purchase availability acceptance test.</p>
<p>BNB Accelerator is the commercially interested publisher and an acquisition provider. These original document-based worksheets are not independent ratings, authenticated outcomes or firsthand provider testing. Keep seller, guest and client evidence secure and authorized; do not request passwords or unrelated customer records. Actual agreements and qualified legal, tax, lending and investment advisers govern your decisions. No continuity of service, revenue, permission, deduction or return is promised.</p></div></section>'''
s=s.replace(marker,body+marker).replace('reviewed 2026-10-01. Availability, fees and agreements may change.','reviewed 2026-10-07. Availability, fees and agreements may change.')
p.write_text(s)
p=R/'sitemap-core.xml';s=p.read_text();s,n=re.subn(r'(<loc>https://www\.bnbaccelerator\.com/guides/kleer-circle-year-one-operations/</loc>\s*<lastmod>)2026-10-01',r'\g<1>2026-10-07',s);assert n==1;p.write_text(s)
