"""Existing Tennessee accuracy correction; preserve URL and publication."""
import re
from refresh_dscr_purchase_methods import refresh, publisher

BODY='''<p class="lead">Tennessee grandfathering is a permission question to resolve before buying, not a guarantee of rental income or protection for a new owner. A seller's lawful operation, the buyer's proposed ownership and the property's private restrictions require separate evidence. Do not pay a permit premium because a listing says grandfathered, or rush a purchase to precede a rule change. Establish the actual buyer's supported use and fund a no-continuity case first.</p>
<p><a href="/apply/">Bring the legacy-status evidence register to an acquisition call</a>. BNB Accelerator coordinates acquisition work within its agreement; independent counsel and the responsible authority determine legal eligibility and the effect of the actual transaction.</p>
<h2>Read the state summary as a starting point, not buyer approval</h2>
<p>The University of Tennessee's <a href="https://www.mtas.tennessee.edu/reference/summary-short-term-rental-unit-act">Municipal Technical Advisory Service summary</a>, marked reviewed July 9, 2026 and consulted here October 8, describes legacy protection under the Short-Term Rental Unit Act. It discusses defined prior-use evidence and events affecting continued use, including sale or transfer. It also distinguishes private restrictions. This is an advisory summary, not an individualized legal opinion or a complete reconciliation of all current statutory exceptions and amendments.</p>
<p>Ask counsel for the current controlling provisions and a written explanation addressing the buyer, parcel, proposed ownership and operation. A prior listing or an old permit alone cannot resolve every defined eligibility condition. Identify the relevant rule's effective date and the evidence supporting the seller's claim; do not infer a protected right simply from furniture, bookings or a property's market history.</p>
<p>Keep the original approval, dated operating evidence, renewals, notices, ownership records and actual public/private restrictions together. Where documents conflict, record the unresolved question and reviewer rather than writing grandfathered on the underwriting sheet. This guide supplies no universal transfer exception, nonuse period or legal workaround.</p>
<h2>Nashville demonstrates why renewal and buyer permission differ</h2>
<p><a href="https://www.nashville.gov/departments/codes/short-term-rentals/permit-types">Nashville's permit-types page</a>, updated March 13, 2026 and reviewed here October 8, says new non-owner-occupied permits are not allowed in its listed residential zoning districts. Existing holders there may be eligible for renewal, but the page states those permits are not transferable on sale or transfer. That illustrates a seller/buyer distinction, not a statewide transfer rule. Obtain a response for the actual ownership event and current zoning conditions.</p>
<p>A legacy permit's scarcity does not establish higher future rates, stable property value or investment superiority. Demand, competing accommodation, costs, financing and buyer permission still need independent evidence. A property's acquisition can fail the buyer's STR thesis even while the seller operates lawfully. The <a href="/blog/permits-that-do-not-transfer/">permission-continuity guide</a> covers broader government and private approvals; the <a href="/blog/nonconforming-str-use-sale/">nonconforming-use owner</a> addresses distinct transaction triggers.</p>
<h2>Use an ownership-event evidence register</h2>
<div class="table-wrap"><table><thead><tr><th>Event or claim</th><th>Evidence and responsible review</th><th>Purchase decision</th></tr></thead><tbody>
<tr><td>Prior protected operation</td><td>Applicable current definition, original records and counsel review</td><td>Do not substitute an advertised history for qualifying evidence</td></tr>
<tr><td>Deed or ownership/control change</td><td>Actual proposed structure and authority/counsel response</td><td>Separate seller renewal from buyer permission</td></tr>
<tr><td>Downtime or altered use</td><td>Dates, planned work and controlling provisions</td><td>Identify unresolved continuity before changing the operation</td></tr>
<tr><td>Notices and renewals</td><td>Current issued records, conditions and open matters</td><td>Do not assume old approval resolves new conditions</td></tr>
<tr><td>Private rental restrictions</td><td>Recorded covenants, association documents and counsel interpretation</td><td>Public permission does not settle the private-use question</td></tr>
</tbody></table></div>
<p>Add the review deadline, responsible party and required answer to each row. Keep private seller and ownership records in authorized secure channels. Buying an entity is not an automatic permit-preservation method or a reason to omit disclosure; counsel must assess the actual rights, obligations and control change. Contractual review or refund rights come from the applicable signed terms, not this table.</p>
<p>Apply the same discipline in the Smokies. A long-established cabin rental economy does not prove regulatory stability or make restrictive change impossible. Establish the exact city/county boundary, parcel, buyer eligibility, capacity and private restrictions. Service availability is a separate commercial question; no demand, most-transacted-market statistic or future policy forecast is asserted here.</p>
<h2>Worked no-continuity cash test before approving an offer</h2>
<p>Hypothetical arithmetic only, not Tennessee costs, an approval timeline, market forecast or client outcome: assume $300,000 genuinely available. Purchase, closing and essential setup need $235,000, with a separate protected $35,000 reserve included once. Initial allocation is $270,000, leaving $30,000 unassigned.</p>
<p>Stipulate no STR receipts while buyer permission remains unresolved, $3,000 monthly distinct carrying obligations and $6,000 separate review, application and required-work outflows. Four months adds $12,000 plus $6,000: total allocation $288,000, leaving $12,000. Eight months replaces four, adding $24,000 plus $6,000: total $300,000, leaving nothing unassigned before omitted costs.</p>
<p>A further separate $9,000 repair makes the eight-month allocation $309,000, a $9,000 gap. Do not call the original $35,000 both protected reserve and money already spent to conceal that gap. A stipulated genuine $10,000 reduction in cash required for the purchase would reduce that stressed allocation to $299,000, leaving $1,000. That is not a lender credit rule, realistic concession or adequate safety margin; verify actual settlement and financing effects.</p>
<p>A price change does not grant rental permission. If buyer operation cannot be established, evaluate another independently lawful use with its own costs and supported receipts, or reject the STR thesis. Seller future bookings and an expected tax refund are not cleared buyer funds. Use the <a href="/tools/first-str-purchase-budget/">complete purchase-budget worksheet</a> to place actual bills, deposits, work and available cash on dates; this partial example is not a valuation or return calculation.</p>
<h2>Choose on documented rights and complete economics</h2>
<p>Proceed when buyer permission, condition, financing and independently funded downside fit. Reprice a viable acquisition using supported use evidence. Seek a valid negotiated extension if decisive records can arrive within protected terms. Decline a purchase that depends on unverified legacy rights or speculative approval. Prior use can be important without making acquisition timing a race or guaranteeing protection for a buyer.</p>
<p>Keep tax registration and investment-tax suitability in a separate adviser review. A salary-tax headline does not answer the treatment of rental income, entity taxes, occupancy/sales taxes or the buyer's home-state obligations. This page does not calculate or certify any Tennessee or federal tax liability. Avoid a purchase thesis based on supposedly simpler taxes without evaluating the actual ownership and transactions.</p>
<p><a href="/apply/">Compare the Tennessee shortlist with a completed continuity register and funded downside</a>. Continue through the <a href="/blog/buy-str-high-income-large-tax-bill/">high-income buyer roadmap</a>; substantial capital does not validate a claimed right. BNB cannot guarantee permission, policy stability, income, tax benefit or an opening date.</p>
<p class="small">Primary advisory and Nashville materials reviewed October 8, 2026 with their own dates above. BNB Accelerator is the interested acquisition-service publisher. Document-based education only, not firsthand legal testing, legal advice, a valuation or personalized tax, lending or investment advice. Numerical examples are hypothetical; no client result or market prediction is represented.</p>'''

FAQ=[
("What does Tennessee's short-term rental act protect?", "The MTAS summary describes conditional legacy protection and relevant prior-use evidence. Obtain current controlling provisions and buyer-specific legal review; a seller's prior operation is not guaranteed permission after your transaction."),
('Can Nashville still restrict short-term rentals?', 'Its current permit-types page distinguishes new non-owner-occupied permission from renewal by existing holders and states listed residential-district permits do not transfer on sale or transfer. Check the actual parcel, buyer and ownership event.'),
('Does Tennessee have state income tax on rental income?', 'A statement about wage taxes does not answer rental-income or entity-tax treatment. Have qualified tax advisers review the actual ownership, rental activity and federal, state and local obligations; this guide does not certify liability.')]

if __name__=='__main__':
    original=(publisher.ROOT/'blog/tennessee-grandfathering-explained/index.html').read_text()
    keep=re.search(r'<div class="callout">\s*<h3>Keep reading</h3>.*?</div>',original,re.S)[0]
    BODY+=keep
    publisher.DATE='2026-10-08'
    article=publisher.ROOT/'blog/tennessee-grandfathering-explained/index.html'
    if '<span>Updated October 8, 2026</span>' not in original:
        article.write_text(original.replace('<span>Published August 15, 2026</span>', '<span>Published August 15, 2026</span><span>&middot;</span><span>Updated October 8, 2026</span>', 1))
    # Preserve the original encoded title without double-encoding social metadata.
    refresh('tennessee-grandfathering-explained','Tennessee STR Act &amp; Grandfathering (2026)',"Tennessee's Grandfathering Protection and What It Actually Covers",'Before buying a Tennessee STR, verify legacy-use evidence and buyer permission. Compare a no-continuity cash case without assuming protected rates or returns.',BODY,FAQ,'2026-08-15','data-tennessee-legacy-review-link','Use the <a href="/blog/tennessee-grandfathering-explained/">Tennessee continuity register and no-permission cash test</a> before pricing a seller’s legacy-status claim.')
    article.write_text(article.read_text().replace('STR Act &amp;amp; Grandfathering', 'STR Act &amp; Grandfathering'))
