"""Scoped existing manager handoff owner expansion; no new provider contract claims."""
from pathlib import Path
import re
R=Path(__file__).resolve().parents[1];p=R/'guides/bnb-turnkey-management-handoff/index.html';s=p.read_text()
assert '"datePublished": "2026-10-01"' in s and '"dateModified": "2026-10-01"' in s
s=s.replace('"dateModified": "2026-10-01"','"dateModified": "2026-10-07"')
rows=[('Which company manages the property?','Dated buyer proposal, legal entity, local team and accepted first-service date','Do not assume a named marketing partner has accepted this address'),('What is the fee charged on?','Calculation base, sample invoice, minimums, pass-throughs and payment triggers','Compare total buyer costs on the same operating case'),('Who owns accounts and records?','Authorized access/ownership schedule, permitted exports and continuing booking duties','Resolve control and evidence access without buying credentials'),('How do I change operators?','Actual notice, termination costs, guest obligations and handoff responsibilities','Price a permitted future change without inventing free cancellation')]
for q,e,g in rows:
 old=f'<tr><th scope="row">{q}</th><td>Document / clause / named owner</td><td>Resolved before payment or offer</td></tr>'
 assert s.count(old)==1;s=s.replace(old,f'<tr><th scope="row">{q}</th><td>{e}</td><td>{g}</td></tr>')
marker='<section class="section-sm"><div class="wrap wrap-narrow"><h2>Continue your buyer comparison</h2>'
assert s.count(marker)==1
body='''<section class="section-sm"><div class="wrap wrap-narrow"><h2>Check the published path against your actual buyer proposal</h2>
<p>BNB Turnkey's <a href="https://bnb-turnkey.com/services">services page</a> describes market research, revenue forecasting, inspection and negotiation support, design and furnishing coordination. Its <a href="https://bnb-turnkey.com/pre-call">pre-call page</a> describes project oversight and a management partnership with Home Team Vacation Rentals. Both public materials were reviewed October 7, 2026. These descriptions support asking about a connected acquisition-to-operation path; they do not establish the manager entity, price, mandatory engagement or accepted start date in your own transaction. No signed customer agreement was reviewed here.</p>
<h2>Original one-address management acceptance sample</h2>
<p>Before relying on a connected operator, give the proposed manager the actual candidate address, intended use, closing date and opening work still pending. Request a dated answer identifying the buyer and contracting entity, included first services, excluded work, access dependencies, decision authority and fee triggers. Record which answers remain conditional. A vendor introduction or project update is not the manager's acceptance of a ready-to-operate property.</p>
<p><strong>Invented schedule only:</strong> a purchase decision is due on day10, the manager offers a proposal on day12, and the buyer hopes to close on day20. The later proposal does not resolve the day10 question or extend protection. Ask the transaction adviser before the real deadline how to address missing decisive evidence under the actual agreement. A future service date also does not prove insurance, permissions, completed installation or lawful booking procedures. Keep unresolved dependencies visible rather than calling the property turnkey.</p>
<h2>Worked fee-base comparison before choosing the operator</h2>
<p><strong>All amounts and percentages are invented, not BNB Turnkey or Home Team quotes, industry averages or client results.</strong> Suppose the same modeled year contains $80,000 lodging revenue and $12,000 cleaning charges. For hypothetical proposal A, a 20% fee applies only to lodging: $16,000. For hypothetical proposal B, the same rate applies to lodging plus cleaning: $18,400. The $2,400 difference comes from the fee base, not a different rate or independently demonstrated service quality.</p>
<p>Separately itemize cleaning labor, supplies, maintenance, payment charges, onboarding and minimums under each actual proposal. Do not subtract the $12,000 cleaning charges twice or assume charges collected from guests equal the cleaning bill. A base comparison alone does not establish total owner cash or which manager is cheaper once exclusions and service coverage differ. Ask for a sample invoice calculated from the same inputs, then replace the illustration with accepted buyer terms.</p>
<h2>Opening cash when a manager deposit is not freely available</h2>
<p><strong>Separate hypothetical cash exercise:</strong> the buyer has $300,000 accessible capital. The complete acquisition-and-launch allocation is $278,000, including a retained $45,000 operating reserve; $22,000 remains outside those commitments. Suppose additional manager onboarding is $4,000 and a distinct $6,000 manager-held deposit is required. Total committed capital becomes $288,000, leaving $12,000. The deposit is not automatically an expense, but it is not freely available buyer cash while held.</p>
<p>A distinct $9,000 access-and-transition bill then raises commitments to $297,000 and leaves $3,000. If a further, previously excluded $7,000 opening obligation becomes payable, commitments reach $304,000: a $4,000 gap without consuming the retained reserve. This is not a reserve-adequacy recommendation. Count every bill once and establish payment dates. A hoped-for release of the $6,000 deposit does not cure the gap unless entitlement, release conditions and actual availability are documented; this example promises no refund right or timing.</p>
<p>For alternative operating arrangements, use the existing <a href="/blog/keep-str-manager-after-buying-property/">retain-versus-replace purchase analysis</a>. The <a href="/blog/assign-str-management-contract-sale/">manager consent and assignment worksheet</a> covers buying an operating property with an existing agreement. Those different purchase questions do not disappear because an acquisition provider introduces an operator. Use the <a href="/guides/str-service-responsibility-matrix/">responsibility matrix</a> to define what BNB Accelerator or another retained team actually coordinates, and keep professional approvals separate.</p>
<p>These are original document-based decision aids, not firsthand provider testing, authenticated performance or a review score. BNB Accelerator is the commercially interested publisher and acquisition provider. Keep client, seller and guest evidence secure and authorized; do not request account passwords. Qualified advisers and actual agreements determine legal, tax, lending and investment decisions. No management continuity, permission, revenue, tax benefit or return is promised.</p></div></section>'''
s=s.replace(marker,body+marker).replace('reviewed 2026-10-01. Availability, fees and agreements may change.','reviewed 2026-10-07. Availability, fees and agreements may change.')
p.write_text(s)
p=R/'sitemap-core.xml';s=p.read_text();s,n=re.subn(r'(<loc>https://www\.bnbaccelerator\.com/guides/bnb-turnkey-management-handoff/</loc>\s*<lastmod>)2026-10-01',r'\g<1>2026-10-07',s);assert n==1;p.write_text(s)
