"""Individually researched existing portfolio-decision refresh, not new509."""
import re
from refresh_dscr_purchase_methods import refresh
from expand_hold_period import ROOT

BODY='''<p class="lead">Before buying another short-term rental, compare the new property's risks with the assets you already own. A second address in a familiar market can simplify execution, but it can also increase exposure to the same permission, weather, demand and vendor problems. A different market can reduce a particular shared exposure while introducing unfamiliar operations. Neither property count nor state boundaries establish which choice fits your capital and workload.</p>
<p>This is a purchase comparison, not a rule to concentrate until a particular property number. Compare two actual candidates and the option to buy neither. Each candidate must first pass its own permission, financing, underwriting and launch tests; diversification does not rehabilitate a weak acquisition. The <a href="/blog/buy-two-short-term-rentals-at-once/">simultaneous-purchase guide</a> addresses two closings at once, a separate timing decision.</p>
<h2 id="concentration">Measure the value of familiarity before assuming savings</h2>
<p>Ask the incumbent manager and vendors which services they can actually extend to the proposed address, on what dates and at what prices. Shared geography does not prove spare cleaner capacity, identical permit eligibility or a discounted management agreement. Request a property-specific onboarding schedule, backup coverage and written scope. Existing relationships are useful evidence to investigate, not automatic savings to put in a forecast.</p>
<p>For the other-market candidate, list the work that must be recreated: local diligence, inspections, permission confirmation, insurance placement, operating contacts and launch acceptance. Assign each task an owner and deadline. Price uncovered work rather than asserting that two markets always double—or more than double—the workload. A second established team could make that burden manageable; a familiar team's lack of capacity could make the closer property harder.</p>
<p>Compare <a href="/compare/bnb-accelerator-vs-property-manager/">acquisition work and operator responsibilities</a> separately. A manager's recurring fee is not necessarily an acquisition or renovation service. BNB Accelerator is this page's publisher and an interested acquisition-service provider; its responsibilities depend on the actual agreement. This analysis is document-based decision support, not a client result, firsthand market test or provider rating.</p>
<h2 id="risk">Build a shared-risk acceptance register</h2>
<p>The SEC's <a href="https://www.investor.gov/introduction-investing/investing-basics/save-and-invest/diversify-your-investments">Investor.gov diversification guidance</a> explains spreading investments to reduce exposure while warning that it does not guarantee protection against losses. That is general investor education, not an endorsement of an STR market or a numerical property threshold. The following register is our original acquisition work sample, not a regulator's required form.</p>
<div class="table-wrap"><table><thead><tr><th>Exposure</th><th>Evidence for existing holdings and candidate</th><th>Acceptance question</th></tr></thead><tbody>
<tr><td>Legal use</td><td>Address-level permit type, jurisdiction, renewal and restrictions</td><td>Could one rule change interrupt both? Who reviews the unresolved condition?</td></tr>
<tr><td>Demand and receipt timing</td><td>Verified monthly history, supported comparables and actual payout timing</td><td>Would both need owner cash in the same weeks?</td></tr>
<tr><td>Hazards and insurance</td><td>Address-specific risk review, issued/proposed forms, deductibles and exclusions</td><td>Could one event create two uncovered bills or delayed receipts?</td></tr>
<tr><td>Execution capacity</td><td>Named operators, onboarding dates and backup arrangements</td><td>Does losing one vendor interrupt both launches or operations?</td></tr>
<tr><td>Debt and liquidity</td><td>Loan obligations, maturities, guarantees and dated available capital</td><td>Could both require cash while income or refinancing is unavailable?</td></tr>
</tbody></table></div>
<p>Record the source, review date, person responsible and unresolved assumption in each row. Mark a risk shared, different or unknown; do not turn unknown into low risk. Different peak seasons might change cash timing, but only a combined monthly schedule can show the effect for these properties. Different jurisdictions can still share a regional hazard, insurer, demand source or access route. Distance is not a measured correlation coefficient.</p>
<p>Test one defined shared event at a time and then a combined downside the buyer can explain. Do not assign event probabilities, presume insurance pays immediately or subtract foregone gross revenue as though it were a separate invoice. Use complete cash receipts and outflows. The <a href="/blog/how-to-choose-str-market/">market-selection owner</a> provides broader diligence context; this register isolates what the next acquisition adds to existing exposure.</p>
<h2 id="threshold">Replace a property-count threshold with a cash decision</h2>
<p>Hypothetical arithmetic only: assume $300,000 genuinely available for another purchase after separately protecting household needs and existing obligations. Candidate A in the existing market needs $160,000 down, $12,000 distinct closing costs, $28,000 launch work and $50,000 retained cash. Its complete allocation is $250,000, leaving $50,000 outside that plan. Candidate B in another market has the same first three amounts but $60,000 retained cash and $8,000 additional diligence/onboarding work: $268,000 allocated, leaving $32,000.</p>
<p>The additional retained cash is not an expense or a proven adequate reserve; the onboarding amount is an invented cost, not a quote. Neither allocation measures return. Lender asset eligibility and required liquidity are separate confirmations, and the capital already set aside for existing holdings must not be promised to the new closing.</p>
<div class="table-wrap"><table><thead><tr><th>Stipulated additional cash need</th><th>A: existing market</th><th>B: other market</th></tr></thead><tbody>
<tr><td>Base allocation / outside margin</td><td>$250,000 / $50,000</td><td>$268,000 / $32,000</td></tr>
<tr><td>Defined shared-event funding call</td><td>$36,000 across both holdings: total $286,000 / $14,000 margin</td><td>$18,000 at the existing holding only: total $286,000 / $14,000 margin</td></tr>
<tr><td>Plus distinct $20,000 new-property repair</td><td>$306,000 total / $6,000 shortfall</td><td>$306,000 total / $6,000 shortfall</td></tr>
</tbody></table></div>
<p>This stress deliberately stipulates that the event affects both A holdings but only the existing holding under B. It is not evidence that another market avoids that event. The funding calls are additional to the previously funded obligations, launch work and retained cash, with no duplicate item. If costs are already covered in another line, reconcile them instead of adding them again.</p>
<p>The example holds the stated reserves untouched so the buyer can compare affordability without silently consuming them. It does not prohibit using an authorized operating reserve; it makes any draw an explicit different scenario. A different event affecting B, or a delayed B launch, could reverse the comparison. Update the <a href="/tools/first-str-purchase-budget/">dated purchase-budget worksheet</a> with actual amounts and receipts; prospective insurance settlements, refunds and a future refinance are not today's available funds.</p>
<h2 id="tax">Tax activities are not simply a count of houses</h2>
<p><a href="https://www.irs.gov/publications/p925">IRS Publication 925</a> allows qualifying activities to be grouped when they form an appropriate economic unit; facts, restrictions, consistency and disclosure rules matter. Grouping can change how material participation is evaluated and how a partial disposition is treated. An additional house does not automatically mean a separately tested activity, and there is no third-property election trigger supplied here.</p>
<p>The publication's short-average-customer-use exception is not by itself proof of a W-2 loss offset. Have the CPA evaluate actual activities, participation and applicable loss limits before the purchase. Do not select a market to manufacture a tax conclusion or count an estimated deduction as purchase cash. See <a href="/blog/str-tax-benefit-shortfall-purchase/">the smaller-or-delayed-tax-benefit purchase test</a>. My BnB Accelerator, LLC is not a CPA firm; AE Tax Advisors is an independent partner firm.</p>
<h2>Choose same market, another market, wait or stop</h2>
<p>Choose the familiar-market candidate only if its verified economics, usable vendor capacity and added shared exposure fit your limits. Choose the other-market candidate only if its distinct risks and extra execution requirements are funded and acceptable. Reprice or seek valid transaction protection when decisive costs or permissions remain unresolved. Wait when neither acquisition passes without speculative receipts; retaining liquidity is a legitimate comparison, not a failed portfolio plan.</p>
<p><a href="/apply/">Bring two candidate addresses and the completed shared-risk register to an acquisition call</a>. Include available capital, separately protected obligations, funding dates, operator quotes and each property's stop conditions. Keep bank, guest and seller records in agreed secure channels. A high income or large tax bill does not establish suitable portfolio exposure. Use the <a href="/blog/buy-str-high-income-large-tax-bill/">high-income purchase roadmap</a> for the rest of the buying journey.</p>
<p class="small">Primary SEC and IRS materials reviewed October 7, 2026; Publication 925 is the currently published 2025 edition. Educational information only, not personalized investment, tax, legal, insurance or lending advice. All example figures and event assumptions are invented. No diversification, permission, financing, tax benefit, income or investment result is guaranteed.</p>'''

FAQ=[
('Should my second short-term rental be in the same market?', 'Not automatically. Compare supported property economics, actual vendor capacity, added shared exposure and dated cash needs with a specific other-market candidate and the option to wait.'),
('When should a short-term rental portfolio diversify?', 'There is no universal property-count threshold here. Evaluate how the next acquisition changes shared permission, demand, hazard, vendor, debt and liquidity exposure against your own limits.'),
('What does real diversification look like for short-term rentals?', 'Compare underlying exposures rather than addresses alone: jurisdictions, demand sources, cash-flow timing, hazards, vendors and debt. Different locations can still share important risks, and losses remain possible.'),
('Does portfolio size affect the tax strategy?', 'Additional acquisitions require adviser review, but houses are not automatically separate tax activities. Grouping, participation, use and loss limits depend on facts and rules; a property count does not guarantee a deduction or refund.')]

if __name__=='__main__':
    original=(ROOT/'blog/str-portfolio-diversification/index.html').read_text()
    keep=re.search(r'<div class="callout">\s*<h3>Keep reading</h3>.*?</div>',original,re.S)[0]
    refresh('str-portfolio-diversification','Should You Diversify a Short-Term Rental Portfolio?','Concentration vs Diversification in an STR Portfolio','Before buying another STR, compare shared risks, vendor capacity and funded downside. Use a same-market versus other-market purchase worksheet.',BODY+keep,FAQ,'2026-08-11','data-portfolio-shape-review-link','Before the next purchase, compare <a href="/blog/str-portfolio-diversification/">same-market and other-market risks with a protected-cash worksheet</a>. A property count is not a diversification or tax threshold.')
