"""Scoped evidence-comparison refresh; retains purchase checks and original publication."""
from refresh_dscr_purchase_methods import refresh
import subprocess
import re
from pathlib import Path

BODY = '''<p class="lead">Before buying an Airbnb, compare what each revenue document actually measures. A seller export, modeled address estimate and hand-selected comparable set answer different questions. None becomes verified future income by appearing in a polished report. Build a monthly purchase case with visible availability, rates, check-ins and complete costs, then decide what unresolved evidence changes the offer.</p>
<p>BNB Accelerator publishes this guide and has a commercial interest in acquisition services. This is document-based analysis, not firsthand product testing, an independent provider ranking or a claim about a client's results. <a href="/apply/">Bring the dated revenue comparison and purchase budget to an acquisition call</a>; independent lenders and advisers determine their own requirements.</p>
<h2 id="methods">Compare three evidence methods without a universal winner</h2>
<div class="table-wrap"><table><thead><tr><th>Evidence</th><th>Useful purchase question</th><th>What remains unverified</th></tr></thead><tbody>
<tr><td>Seller operating records</td><td>What did this asset actually earn during the stated period?</td><td>Completeness, cancellations, expense definitions and whether the buyer can reproduce the operating setup</td></tr>
<tr><td>Modeled address estimate</td><td>What could comparable inventory imply under the model's assumptions?</td><td>Subject-specific permission, availability, execution and future demand</td></tr>
<tr><td>Buyer-reviewed comparable set</td><td>Which properties genuinely support the proposed rate and sold nights?</td><td>Data provenance, selection bias and adjustments that have no measured support</td></tr>
</tbody></table></div>
<p>Use seller history where available, but reconcile accommodation dates, refunds, fees and cleared payouts rather than relying on a screenshot or a selectively chosen month. Do not accuse a seller of dishonesty merely because records are incomplete. Request the missing period and explain the consequence. The <a href="/blog/reconcile-airbnb-payout-export/">seller payout reconciliation</a> separates records and receipts; <a href="/blog/seller-proforma-vs-trailing-revenue/">history versus proposed uplift</a> evaluates a seller's improvement case without silently making it the base forecast.</p>
<p>Current <a href="https://help.airdna.co/en/articles/10559022-rentalizer-revenue-calculator">AirDNA Rentalizer documentation, dated June 19, 2026</a>, describes editable capacity inputs, customizable comparable sets, amenity filters and monthly projection ranges. Its address projection assumes 365 days available and includes cleaning fees. Therefore it is inaccurate to claim categorically that such tools cannot account for amenities or guest capacity. Those features still do not independently verify this asset's condition, permit, access, buyer calendar or future revenue. Preserve the version and confirm each field's fee treatment before comparing it with net payouts.</p>
<h2 id="comps">Keep an inclusion-and-exclusion record for comparables</h2>
<p>Record each listing's location, lawful guest capacity, bedroom/bath configuration, access, amenity condition, guest segment, available days, data period and source. A nearby property may serve a different trip purpose. A superior pool or view is not a reason to copy its revenue into an inferior asset; an inferior comparison is not proof that adding an amenity will create a specific uplift. Note the mismatch and retain an unadjusted downside until the proposed adjustment has support.</p>
<p>Separate verified seller records from third-party estimates of another listing's performance. A modeled comparable is not your access to that owner's actual booking ledger. Record reviews and listing age as context, but do not assume a particular review count guarantees higher revenue or apply an unexplained first-year discount. Explain the buyer's opening date, supported marketing plan and evidence uncertainty. Add a sensitivity instead of inventing a universal relationship between reviews and income.</p>
<div class="callout"><h3>Year one is an actual calendar, not a percentage label</h3><p>Place closing, repairs, furnishings, permission and opening on dated milestones. Remove unavailable nights before estimating sales. Count remaining seasonal windows rather than copying a stabilized twelve-month total. The <a href="/blog/first-90-days-after-str-closing/">first-90-days readiness plan</a> helps identify launch dependencies; verify the actual dates with the transaction team.</p></div>
<h2 id="tests">A worked comparison from headline revenue to buyer cash</h2>
<p>Every number below is invented arithmetic, not a market benchmark, provider accuracy test, quote or client outcome. For a simplified full operating year, assume three four-month blocks. Lodge-only rates exclude cleaning charges. Available nights already exclude maintenance and owner use. Sold nights are assumptions, not confirmed reservations.</p>
<div class="table-wrap"><table><thead><tr><th>Four-month block</th><th>Available nights</th><th>Sold nights</th><th>Lodging rate</th><th>Lodging revenue</th></tr></thead><tbody>
<tr><td>Lower-demand block</td><td>100</td><td>40</td><td>$250</td><td>$10,000</td></tr>
<tr><td>Middle block</td><td>110</td><td>65</td><td>$350</td><td>$22,750</td></tr>
<tr><td>Peak block</td><td>110</td><td>90</td><td>$500</td><td>$45,000</td></tr>
<tr><td>Year</td><td>320</td><td>195</td><td>Different seasonal rates</td><td>$77,750</td></tr>
</tbody></table></div>
<p>Assume 65 check-ins, $150 cleaning collected per stay and $180 paid per turnover: $9,750 collected versus $11,700 paid, a $1,950 cleaning deficit. Gross receipts including that cleaning charge are $87,500, not $87,500 of lodging income. Further assume $15,550 distinct non-cleaning variable costs, stipulated as 20% of lodging revenue only, $18,000 fixed operating costs and $48,000 debt payments. Fixed costs include the modeled property tax and insurance; debt here is principal and interest only. Annual owner cash is $77,750 − $1,950 − $15,550 − $18,000 − $48,000 = negative $5,750 before omitted capital work or tax consequences.</p>
<p>For a separate rate-only stress, reduce every lodging rate by 10% while holding sold nights and check-ins unchanged. Lodging revenue becomes $69,975 and the stipulated 20% non-cleaning costs become $13,995. Other assumptions unchanged, owner cash is negative $11,970. The $7,775 lodging decline reduces cash by $6,220 because this fictional variable-cost line also falls. Do not subtract the stress deficit from the base deficit: these are alternative cases, not consecutive years.</p>
<p>An actual first year may miss the peak block entirely. Rebuild the month-by-month opening case rather than prorating this annual example. Annual profit or loss does not show when bills precede payouts; use the <a href="/blog/str-cash-reserves-seasonality/">seasonal receipt-and-reserve schedule</a> and <a href="/tools/first-str-purchase-budget/">purchase cash budget</a>. Retained reserves are an allocation of capital, not another recurring expense.</p>
<h2>Occupancy does not determine the cleaning count</h2>
<p><a href="https://www.airbnb.com/help/article/2715">Airbnb's professional-hosting definitions</a> distinguish booked versus available nights, check-ins, length of stay and nightly rate. In the example, 195 nights over 320 available is about 60.9% occupancy, while 65 check-ins imply three nights per stay. A different plan could sell only 150 nights but require 75 two-night stays. Lower occupancy would then have more turnovers, not fewer. Recalculate cleaning charges, invoices and staffing from the stay pattern; do not infer wear or cleaning expense from occupancy alone. See the <a href="/blog/airbnb-occupancy-rates-explained/">occupancy comparison worksheet</a>.</p>
<h2 id="expenses">Replace expense assumptions with address-specific evidence</h2>
<p>Request a suitable insurance quote, the local assessor's explanation of buyer taxes, manager contract and fee basis, cleaning scope, utilities, inspection findings and replacement estimates. Do not assume every sale resets property tax to purchase price, every STR wears faster than every long-term rental, or revenue errors matter less than expenses. Separate recurring costs, one-time setup, capital repairs and retained cash. Specify which charges include taxes, insurance, HOA and cleaning so neither the lender payment nor an operating line counts them twice.</p>
<p>Compare the same expense scope across every revenue case. A manager's rate alone does not establish the dollars charged if its contract includes a different fee base or additional services. For separate financing analysis, use <a href="/blog/what-lenders-do-with-airdna/">how lenders use AirDNA versus owner cash</a>; a lender's accepted estimate does not certify profitability. Review <a href="/blog/airbnb-insurance-guide/">insurance use and coverage</a> and <a href="/blog/cohosting-vs-self-managing/">management responsibilities</a> with qualified independent professionals.</p>
<h2>Turn unresolved inputs into a purchase decision</h2>
<p>Record source, date, verification owner, cash effect and deadline for each uncertainty. Review supply and demand using consistent geography, listing definitions and periods; a higher listing count alone does not prove a specific future revenue decline. Proceed when permission, supported downside and genuinely available capital fit. Reprice a viable purchase when verified costs change. Seek valid contract protection or a negotiated extension while essential evidence remains missing; counsel determines the available rights. Decline a deal dependent on unsupported revenue or an unfunded opening plan.</p>
<p><a href="/apply/">Discuss the actual shortlist with the evidence comparison and full cash forecast</a>. Continue through the <a href="/blog/buy-str-high-income-large-tax-bill/">high-income buyer roadmap</a> and <a href="/blog/how-to-analyze-airbnb-deal/">complete deal analysis</a>. A large salary or hoped-for tax benefit does not repair the property's assumptions. Keep seller, guest and banking records in agreed secure channels.</p>
<div class="callout warn"><p>My BnB Accelerator, LLC is a real estate acquisition firm, not a CPA firm. <a href="https://aetaxadvisors.com/" target="_blank" rel="noopener">AE Tax Advisors</a> is an independent partner firm. Educational only, not tax, legal, lending or personalized investment advice. Primary documents reviewed October 7, 2026; Airbnb displays no publication date for the cited help article. No revenue, permit, financing, tax benefit, return or indexing is guaranteed.</p></div>'''

FAQ = [
 ('Are Airbnb revenue estimates from data tools accurate?', 'Accuracy for a specific purchase is not established here. Review the report version, comparable selection, availability and fee definitions, then verify subject-specific condition and permission. A modeled estimate is not actual future income.'),
 ('What makes a good short-term rental comparable?', 'Match location, lawful capacity, guest segment, amenities, availability and data period. Document exclusions and distinguish modeled performance from verified owner records rather than cherry-picking higher revenue.'),
 ('Should first-year revenue equal established comparable performance?', 'Not automatically. Build the actual opening calendar and identify supported operating assumptions. Review count does not establish a universal discount or guaranteed revenue advantage.'),
 ('Does lower Airbnb occupancy mean lower cleaning expense?', 'No. Turnovers depend on check-ins and length of stay, not occupancy alone. Compare cleaning receipts and actual turnover charges separately, with the same expense scope in every purchase case.')
]

if __name__ == '__main__':
 BODY = BODY.replace('/blog/first-90-days-after-str-closing/', '/blog/first-90-days-airbnb-launch/')
 refresh('airbnb-revenue-projections', 'Airbnb Revenue Projections: Evidence and Buyer Cash', 'Airbnb Revenue Projections That Hold Up', 'Compare seller history, modeled Airbnb revenue and selected rentals before buying. Use a seasonal forecast, cleaning-cost bridge and owner-cash stress test.', BODY, FAQ, '2026-08-11', 'data-revenue-evidence-review-link', 'Compare the <a href="/blog/airbnb-revenue-projections/">revenue evidence register and seasonal buyer-cash example</a>. Keep availability, cleaning receipts and distinct expenses visible before accepting a purchase forecast.')
 # Use the existing purchase-check formatter's exact word-count/read-time convention.
 root = Path(__file__).resolve().parents[1]
 normalized = subprocess.check_output(['node', '--input-type=module', '-e', "import {readFileSync} from 'node:fs'; import {expandPreclosingKeywords} from './preclosing_keywords.mjs'; const p='blog/airbnb-revenue-projections/index.html'; process.stdout.write(expandPreclosingKeywords(readFileSync(p,'utf8'),p));"], cwd=root, text=True)
 (root/'blog/airbnb-revenue-projections/index.html').write_text(normalized)
 minutes = re.search(r'<span>(\d+) min read</span>', normalized)[1]
 archive = root/'blog/index.html'
 archive.write_text(re.sub(r'<article class="post-card".*?</article>', lambda m: re.sub(r'<span>\d+ min read</span>', '<span>'+minutes+' min read</span>', m[0]) if '/blog/airbnb-revenue-projections/' in m[0] else m[0], archive.read_text(), flags=re.S))
