"""Existing remodel approval owner; no new URL or homepage generation."""
from refresh_dscr_purchase_methods import refresh

BODY='''<p class="lead">Before buying an STR that needs remodeling, establish whether the proposed work requires a new or amended certificate of occupancy, another completion document, or additional approvals under the actual local rules. The seller's existing certificate does not answer every proposed alteration. Keep the current documented use separate from an unapproved bedroom or capacity increase, and fund the purchase without assuming the proposed upside will become rentable.</p>
<p><a href="/apply/">Bring the proposed floor plan and approval-evidence register to an acquisition call</a>. BNB Accelerator assists within its contracted scope; the authority and qualified local professionals determine approval requirements, safety and legal use.</p>
<h2>Ask about this scope, not remodeling in general</h2>
<p>Describe the changes precisely: room conversions, exits, structural work, additional sleeping areas, utility or septic changes and intended use. Give the responsible authority and design professional the existing records and proposed plans. Ask which applications, inspections and issued documents establish permitted occupancy after that scope. Do not substitute listing photos, a contractor's confidence or the seller's booking history for the answer.</p>
<p>A narrowly labeled primary example is <a href="https://www.nyc.gov/site/buildings/property-or-business-owner/certificate-of-occupancy.page">New York City's Department of Buildings certificate-of-occupancy guidance</a>. It describes a current or amended CO for changes in use, egress or occupancy, and a Letter of Completion for certain minor alterations that do not require a new or amended CO. This illustrates why the specific scope matters; it is not a national rule, an STR license or a recommendation to operate rentals in New York City. Obtain the controlling jurisdiction's current determination for your address.</p>
<p>Absence of a certificate in a seller's folder is a question to investigate, not automatic proof of illegal use. Request the actual public record and ask the authority what evidence applies to the property's age, history and proposed work. Conversely, a document labeled final does not establish that later alterations were approved. Match the record's address, scope, date and permitted use to what you intend to buy.</p>
<h2>Build a proposed-work approval register</h2>
<div class="table-wrap"><table><thead><tr><th>Purchase question</th><th>Evidence and reviewer</th><th>Decision before relying on the change</th></tr></thead><tbody>
<tr><td>What is currently approved?</td><td>Current plans, applicable occupancy/use records and unresolved permit history</td><td>Reconcile the actual layout with documented use</td></tr>
<tr><td>What changes?</td><td>Versioned proposed plan and trade/design scope</td><td>Identify altered exits, rooms, systems and intended occupancy</td></tr>
<tr><td>What approval path applies?</td><td>Authority's scope-specific requirements and professional interpretation</td><td>Distinguish application, permit, inspection and issued completion evidence</td></tr>
<tr><td>What else limits the STR?</td><td>Rental permission, association/deed, fire, parking and septic reviews</td><td>A building document does not resolve every separate restriction</td></tr>
<tr><td>Who completes and pays?</td><td>Accepted bids, responsibility, fees and corrective-work scope</td><td>Budget exclusions and reinspection rather than assume seller payment</td></tr>
<tr><td>When can the buyer rely on it?</td><td>Required issued evidence, transaction deadlines and opening approval</td><td>Keep unresolved capacity out of the supported purchase case</td></tr>
</tbody></table></div>
<p>Record unresolved answers as unresolved, including which reviewer supplies the next document. An application received is not the same as a permit issued, and a passed trade inspection is not automatically the final approval for occupancy. Have the local team explain the applicable sequence; this register does not prescribe universal milestones or inspection lists.</p>
<p>The <a href="/blog/str-fire-inspection-closing/">fire-inspection owner</a> addresses its distinct correction and acceptance process. The <a href="/blog/parking-occupancy-str-cap/">capacity-reconciliation guide</a> addresses other binding constraints. Do not replace either review with the proposed bedroom count. A physically furnished bunk room is not evidence of an approved sleeping room or supported guest capacity.</p>
<h2>Underwrite current supported use separately from proposed upside</h2>
<p>Consider a hypothetical den-to-fourth-bedroom conversion. Ask whether the current three-bedroom layout and intended rental use are independently supported. Then ask whether the proposed room, egress and relevant systems can obtain the needed approvals. If the investment case requires the fourth room, an unknown answer remains a decisive acquisition risk—not a minor furnishing detail.</p>
<p>Prepare two property models with appropriately sourced revenue and full buyer costs: the verified current-use case and a separately labeled proposed-use case. Do not raise the base revenue merely because a listing says the den can sleep guests. If current lawful STR use is not established, a smaller-bedroom model does not fix that defect. There is no approved address, market forecast or rentable capacity established by this article.</p>
<p>Compare the proposed project with the <a href="/guides/str-investment/new-construction-home/renovation-budget/">renovation cash and execution worksheet</a>, noting that its new-construction context differs from an existing remodel. Have the actual lender, insurer and transaction advisers evaluate their own conditions. A building approval does not automatically establish funding, coverage or ownership-change rental eligibility.</p>
<h2>Worked remodel cash bridge: an approval delay needs funding</h2>
<p>Hypothetical arithmetic only, not contractor quotes, fees, local processing times or client results. A buyer has $260,000 spendable acquisition capital. The current plan allocates $150,000 down payment, $15,000 closing costs, $25,000 basic setup and a protected $30,000 operating reserve: $220,000 total, leaving $40,000 unassigned. Basic setup excludes every proposed remodel and delay cost below; the reserve is included once.</p>
<p>Assume the additional proposed project requires $30,000 of distinct trade work, $4,000 of separate design/application/inspection costs, and three months of additional carrying bills at $2,000 monthly: $40,000 total. Allocation becomes $260,000, leaving zero unassigned margin while preserving the stated reserve. This arithmetic does not establish that the project will be approved or completed in three months.</p>
<p>If the trade scope rises by $15,000 and the extra carrying interval becomes five months rather than three, incremental project cash becomes $45,000 plus $4,000 plus $10,000, or $59,000. Total allocation is $279,000, creating a $19,000 gap without consuming the protected reserve. Do not add another five months on top of the original three: replace the modeled six-thousand-dollar carrying allowance with ten thousand.</p>
<p>A seller's promised $10,000 concession does not erase that gap until its actual permitted closing treatment is confirmed and the budget is revised. For a pure sensitivity, if it validly reduces modeled buyer cash by exactly $10,000, allocation would be $269,000 and the remaining gap $9,000. This is not a financing rule or a promise of cash reimbursement. The lender and closing professional determine the actual effect and timing; a later benefit cannot pay an earlier invoice.</p>
<p>Obtain a dated payment schedule for design, deposits, inspections, work and carrying bills. Expected revenue from unauthorized or unopened space is not available project money. Use the <a href="/tools/first-str-purchase-budget/">purchase-budget worksheet</a> and exclude double-counted setup, service fees and reserves. An annual return estimate does not solve a pre-opening funding shortfall.</p>
<h2>Set a decision deadline and an acceptable fallback</h2>
<p>Proceed when the supported use, required evidence and complete cash plan fit the purchase. Reprice a viable property when verified work and timing costs change. Delay under available signed protection when a decisive answer can realistically arrive. Decline an acquisition that only works with an unsupported room conversion or unavailable cash. Counsel determines contract rights; this guide supplies no contingency clause or automatic refund remedy.</p>
<p>The <a href="/blog/permit-pending-due-diligence-extension/">permit-extension guide</a> separately tests whether paying for more pre-closing time can produce a decision-changing answer. Moving closing alone may not preserve other protections. If the proposed work occurs after closing, establish a funded no-STR-receipts interval and an actually permissible fallback rather than presume a smaller rental or long-term tenancy is authorized.</p>
<p><a href="/apply/">Discuss the shortlist with a proposed-work acquisition memo</a>: current evidence, desired change, independent reviewer, next milestone, cash limit and stopping date. The <a href="/blog/buy-str-high-income-large-tax-bill/">high-income buyer roadmap</a> connects that review to the broader purchase. Share authorized records through secure channels, not private seller or occupant information in a public worksheet.</p>
<p class="small">NYC Department of Buildings primary guidance reviewed October 7, 2026, geographically limited as labeled. BNB Accelerator is the interested acquisition-service publisher; this is document-based educational analysis, not an inspection, design certification or legal determination. Not legal, engineering, insurance, lending, tax or personalized investment advice. All numerical assumptions are hypothetical. No permit, added capacity, closing protection, opening date, concession or investment result is guaranteed.</p>'''

FAQ=[
('Does every STR remodel require a new certificate of occupancy?', 'No national rule is asserted. Ask the actual authority and qualified local professional which approval and completion documents apply to the specific work and intended use.'),
('Does an existing certificate approve an added STR bedroom?', 'Not by itself. Reconcile existing approved records, proposed plans, egress and other binding restrictions before relying on added capacity.'),
('Does a certificate of occupancy authorize short-term rentals?', 'Do not assume that. Separately verify rental permission, buyer eligibility and applicable association, deed and other restrictions for the intended use.'),
('How should approval delays affect the purchase budget?', 'Model distinct work, professional fees and additional carrying bills on their due dates. Replace overlapping allowances once and preserve protected reserves without relying on projected receipts.')]

if __name__=='__main__':
    refresh('certificate-of-occupancy-str-remodel','STR Remodel: Verify Occupancy Approval Before Buying','Do You Need a New Certificate of Occupancy After an STR Remodel?', 'Before buying an STR remodel, verify occupancy approvals for the proposed work. Compare approved-use evidence and delay cash without assuming added bedrooms.',BODY,FAQ,'2026-09-23','data-co-remodel-review-link','Use the <a href="/blog/certificate-of-occupancy-str-remodel/">proposed-work approval register and remodel-delay cash bridge</a> before pricing an unapproved bedroom into the purchase.')
