"""Existing AirDNA lender-use review; no duplicate provider page or homepage generation."""
import re
import expand_hold_period as publisher
SLUG='what-lenders-do-with-airdna'
BODY='''<p class="lead">An AirDNA report can inform an STR loan application, but the lender's qualifying income and the buyer's operating cash answer different questions. Before buying within the next zero to six months, compare the actual lender's accepted evidence and calculation with an independently supported property budget. A projection, a lender adjustment and a loan approval are not guarantees of bookings, affordability or investment return.</p>
<p><a href="/apply/">Bring the candidate property, dated data report and lender-method worksheet to an acquisition call</a>. This document-based review is published by BNB Accelerator, an acquisition provider with a commercial interest. It is not firsthand software testing, a customer review, an independent ranking or an endorsement of AirDNA or a lender. No affiliation or underwriting authority is claimed.</p>
<h2>Review what AirDNA currently documents</h2>
<p><a href="https://help.airdna.co/en/articles/10559022-rentalizer-revenue-calculator">AirDNA's Rentalizer guidance</a>, dated June 19, 2026 and reviewed October 7, describes an address-specific projection from weighted comparable performance, with property configuration, market conditions and editable comparables. It describes twelve-month projections assuming full 365-day availability, amenity filters, monthly ranges and a variability-based Comp Set Strength. It also allows users to enter operating and startup costs.</p>
<p>That documentation does not support calling the tool merely a national or category average that cannot consider amenities. Nor does it establish that the chosen inputs match the subject, that future performance is assured or that a lender accepts the output. Treat the provider's documented capabilities fairly and validate their application to the address.</p>
<p>The Rentalizer guide says projected revenue includes cleaning fees. <a href="https://help.airdna.co/en/articles/8374548-how-does-airdna-calculate-revenue">AirDNA's revenue-definition page</a>, dated May 20, 2026 and reviewed October 7, also includes cleaning receipts but uses differing descriptions of service-fee treatment in its listing, market and cleaning sections. Ask AirDNA to clarify the exact report field and whether it is before or after relevant fees. Do not silently subtract a fee twice or treat cleaning receipts as pure lodging income.</p>
<p>A consistent comparable set is useful evidence, not a safety certification, permitted-use determination or promise of actual receipts. An attractive score does not replace address-level permission, condition, insurer acceptance, financing or a funded opening plan. Save the report date, selected configuration, original and edited comps and the reasons for changes.</p>
<h2>Obtain the actual lender's method in writing</h2>
<p><a href="https://www.hostfinancial.com/short-term-rental-loans-mortgages/">Host Financial's published STR program page</a>, reviewed October 7, describes using actual rental history, projected income or market rents. Its FAQ describes AirDNA and Rabbu as possible projection sources and different income treatment for some programs and borrower experience. This is a provider-specific example, not proof that most lenders apply one haircut, accept every report or offer these terms to this buyer.</p>
<p>Request current program guidance and an address-specific quote directly from the actual lender or authorized intermediary. Ask which document controls if a sales summary conflicts with the underwriting file. Do not import another lender's percentage, qualification threshold, loan-to-value or expense method. Approval may depend on other borrower, property and transaction conditions.</p>
<div class="table-wrap"><table><thead><tr><th>Comparison row</th><th>Documented lender method</th><th>Independent buyer model</th></tr></thead><tbody>
<tr><td>Evidence and period</td><td>Accepted report, seller history or appraisal evidence; required age and covered dates</td><td>Reconciled subject records, matched comps and intended opening year</td></tr>
<tr><td>Revenue definition</td><td>Which income field, cleaning receipts and adjustments are accepted?</td><td>Separate lodging, cleaning receipts, refunds, fees and taxes</td></tr>
<tr><td>Income adjustment</td><td>Exact percentage, expense treatment and borrower-specific conditions</td><td>Supported rate, nights, availability and downside cases</td></tr>
<tr><td>Ratio denominator</td><td>Exact required payment components and threshold</td><td>All dated operating obligations, debt payments and capital needs</td></tr>
<tr><td>Cash and conditions</td><td>Down payment, reserve qualification and outstanding approval items</td><td>Accessible closing money, retained liquidity and household constraints</td></tr>
</tbody></table></div>
<p>Do not label two ratios comparable until the numerator and denominator are aligned. A lender ratio using gross income and a housing payment is not automatically net operating income divided by debt service. If property tax, insurance or association payments appear in the lender's denominator, do not omit them from buyer costs or count them twice. The <a href="/blog/dscr-loans-for-airbnb/">broader DSCR purchase guide</a> covers the separate financing choice.</p>
<h2>Worked comparison: qualification income versus owner cash</h2>
<p>Independent invented arithmetic only, not an actual AirDNA output, lender quote, qualification rule, market forecast or client result. Assume one report total of $120,000 that, for this example only, includes $12,000 of cleaning receipts and is before the fees modeled below. A fictional lender credits 80% and uses a $6,000 monthly housing-payment denominator. A separate fictional comparison credits 100% with the same denominator. Neither method is attributed to a current provider.</p>
<div class="table-wrap"><table><thead><tr><th>Stipulated method</th><th>Calculation</th><th>Result</th></tr></thead><tbody>
<tr><td>80% qualifying-income case</td><td>$120,000 × 80% / 12 / $6,000</td><td>1.33 ratio, rounded</td></tr>
<tr><td>100% qualifying-income case</td><td>$120,000 / 12 / $6,000</td><td>1.67 ratio, rounded</td></tr>
<tr><td>Buyer lodging income</td><td>$120,000 − $12,000 cleaning receipts</td><td>$108,000</td></tr>
<tr><td>Buyer non-cleaning variable outflows</td><td>Stipulated 20% × $108,000</td><td>$21,600</td></tr>
<tr><td>Net cleaning contribution</td><td>$12,000 receipts − $15,000 cleaning bills</td><td>−$3,000</td></tr>
<tr><td>Other fixed operating bills</td><td>Stipulated separate annual amount</td><td>$18,000</td></tr>
<tr><td>Housing-payment cash outflow</td><td>$6,000 × 12</td><td>$72,000</td></tr>
<tr><td>Buyer remaining cash before omitted items</td><td>$108,000 − $21,600 − $3,000 − $18,000 − $72,000</td><td>−$6,600</td></tr>
</tbody></table></div>
<p>The $72,000 housing amount is stipulated to include debt, property tax, insurance and association payments. The separate $18,000 excludes all those components and cleaning. The 20% covers only the invented non-cleaning variable scope. This counting discipline avoids deducting an item twice. Neither 1.33 nor 1.67 establishes this fictional lender's approval, and neither ratio fixes the buyer's $6,600 modeled shortfall.</p>
<p>Acquisition costs, capital work, additional replacement contributions, income taxes and intrayear receipt timing are omitted. Add them separately before deciding that a model meets a return or liquidity requirement. If supported costs or revenue differ, replace the inputs rather than treating the example's shortfall as an AirDNA accuracy result or an industry benchmark.</p>
<h2>Compare alternatives by the question they answer</h2>
<p>AirDNA with your own qualified local team may fit a buyer who can review comps, obtain real expense evidence and manage diligence deadlines. Another data platform may offer a useful independent method to compare, but two agreeing estimates do not independently verify every assumption. Reconciled seller operating history can test actual past subject results; it is not proof that a new owner's future listing, permission or financing will match.</p>
<p>An acquisition engagement may instead fit a buyer who wants contracted sourcing, property-level analysis and purchase coordination. Confirm the signed scope, fees, exclusions and professional responsibilities. BNB Accelerator is not the data platform or loan decision-maker. See the existing <a href="/compare/alternatives-to-airdna/">AirDNA alternatives comparison</a> rather than treating analytics and an executed purchase service as interchangeable products.</p>
<p>If the lender's figure differs from your supported forecast, reconcile definitions and evidence first. Ask whether permitted additional documentation or a different approved program is appropriate; neither a bigger down payment nor a supplemental study guarantees approval or makes a poor acquisition viable. Use the <a href="/blog/seller-proforma-vs-trailing-revenue/">seller-uplift evidence bridge</a> for proposed improvements and the <a href="/blog/str-cash-reserves-seasonality/">monthly cash worksheet</a> for invoice timing.</p>
<p><a href="/apply/">Compare the candidate with a documented lender method and independent buyer cash case</a>. Bring source dates, revenue definitions, unresolved comps, actual payment components and complete funds through launch. Continue through the <a href="/blog/buy-str-high-income-large-tax-bill/">high-income buyer roadmap</a>; a possible tax benefit does not finance a closing or validate a forecast.</p>
<p class="small">Primary provider documents reviewed October 7, 2026. This is public-document analysis, not firsthand testing or an independent provider ranking. Educational information only, not personalized investment, lending, tax or legal advice. All example figures and lender methods are hypothetical. No financing, revenue, tax benefit or investment result is guaranteed.</p>'''
FAQ=[
('Do all STR lenders use the same AirDNA adjustment?', 'No universal method is established here. Request the actual program guidance, accepted report field, adjustments, payment denominator and buyer-specific conditions from the lender.'),
('Does AirDNA Rentalizer consider amenities?', 'Current provider documentation describes comparable amenities and filters plus editable comparables. That capability does not establish that the selected comps correctly represent a particular property or guarantee performance.'),
('Does a strong lender ratio mean positive buyer cash?', 'No. Compare definitions and all distinct operating, housing, capital and liquidity obligations. A gross-income qualifying ratio and an independently funded purchase answer different questions.'),
('What if provider reports describe fees differently?', 'Ask the provider to clarify the exact report field and document the answer. Separate cleaning receipts, cleaning bills and other fees, and do not deduct an already-netted fee twice.')]
if __name__=='__main__':
 publisher.SLUG=SLUG;publisher.H1='What Lenders Actually Do With AirDNA Numbers'
 publisher.TITLE='How Lenders Use AirDNA: STR Buyer Cash Comparison'
 publisher.DESC='Review AirDNA lender assumptions before buying an STR. Compare accepted income, fee definitions, lender ratios and owner cash with a worked worksheet.'
 publisher.BODY=BODY;publisher.FAQ=FAQ
 si=publisher.ROOT/'sitemap/index.html';old_sitemap=si.read_text()
 publisher.main(expected_publication='2026-08-15',hub_attribute='data-airdna-lender-review-link',hub_paragraph='Compare <a href="/blog/what-lenders-do-with-airdna/">AirDNA qualifying-income assumptions with independent owner cash</a>; analytics, lender approval and an executed acquisition are different decisions.')
 p=publisher.ROOT/'blog'/SLUG/'index.html';s=p.read_text()
 if '<span>Updated October 7, 2026</span>' not in s:
  s,n=re.subn(re.escape('<span>Published August 15, 2026</span><span>&middot;</span>'),'<span>Published August 15, 2026</span><span>&middot;</span><span>Updated October 7, 2026</span><span>&middot;</span>',s,count=1);assert n==1
 p.write_text(s);si.write_text(old_sitemap)
