"""Scoped existing optional appliance premium comparison."""
import re
import expand_hold_period as publisher
SLUG='appliances-roi-short-term-rental'
BODY='''<p class="lead">Does an STR appliance package increase revenue enough to justify its purchase premium? A brand name, attractive photograph or higher-priced neighboring listing does not answer that question. Before buying, distinguish necessary functional equipment from an optional upgrade and compare the upgrade's incremental cash costs with supported incremental contribution. Keep a zero-lift case: the acquisition must not depend on an unverified appliance premium.</p>
<p><a href="/apply/">Bring the functional baseline and optional-upgrade comparison to a BNB Accelerator acquisition call</a>. We help evaluate supported purchase assumptions within our acquisition agreement, not promise a booking premium or investment result.</p>
<h2>Separate readiness from the optional premium</h2>
<p>Establish the equipment expected to convey, its documented condition and required corrective scope. A property needing a safe, functional replacement is a different decision from a property with suitable existing equipment whose buyer prefers a more expensive package. Use qualified reviewers and the <a href="/blog/appliances-inspection-short-term-rental/">inspection scope register</a> before defining either alternative.</p>
<p>Request complete installed bids for the functional baseline and optional alternative, including actual access, removal, connection work and applicable taxes. Subtract the baseline from the alternative to identify the incremental cost. Do not charge the premium decision for required work that occurs in both paths, or count the entire new package on top of an unchanged equipment allowance.</p>
<p>Keep optional aesthetics, extra capacity and supported service differences separately described. None automatically establishes revenue. The <a href="/blog/appliances-repair-replace-short-term-rental/">repair-versus-replacement comparison</a> handles corrective alternatives; this page asks whether an additional discretionary premium has a defensible economic case. A lower optional price does not excuse unresolved safety or permission concerns.</p>
<h2>Use an evidence register rather than a premium assumption</h2>
<div class="table-wrap"><table><thead><tr><th>Proposed benefit</th><th>Evidence question</th><th>Model treatment</th></tr></thead><tbody>
<tr><td>Higher nightly rate</td><td>Do comparable achieved receipts support a difference after other property factors?</td><td>Change supported rate, not an advertised price treated as earned cash</td></tr>
<tr><td>Additional booked nights</td><td>What supports incremental demand within available dates?</td><td>Add contribution from extra nights and their actual variable costs</td></tr>
<tr><td>Lower energy spending</td><td>What supports local use, price and the difference between alternatives?</td><td>Change the existing utility line by the difference once</td></tr>
<tr><td>Lower service or disruption cost</td><td>What documented terms or property evidence support it?</td><td>Use bounded differences or an explicitly hypothetical sensitivity</td></tr>
<tr><td>No revenue lift</td><td>Can the buyer independently fund the optional spending?</td><td>Retain a zero-lift downside rather than forcing a premium</td></tr>
</tbody></table></div>
<p>Record evidence date, exact property or equipment, comparison limitations and who reviewed the assumption. Listings can differ in location, bedrooms, views, condition, season, minimum stays, management and other amenities. A higher advertised rate alongside a premium kitchen is not proof the appliance caused that difference. A calendar showing unavailable dates does not independently establish paid bookings.</p>
<p>Do not add a higher rate to every existing night and also count the same revenue as additional nights. For a combined case, define which nights exist under both alternatives and which are truly incremental. Respect actual permitted use, available dates and capacity; the appliance does not create legal occupancy or open unavailable calendar days. Unsupported inputs belong in sensitivities, not the supported base case.</p>
<h2>Compare contribution, not gross revenue</h2>
<p>Contribution is the incremental receipts remaining after the costs that change with those receipts. Identify actual platform, management, payment, utility, consumable or other relevant terms instead of importing a universal margin. Some fees follow revenue, some follow stays and some are fixed; reconcile the actual structure. Treat guest cleaning charges and cleaning bills consistently rather than keeping the fee and omitting the expense.</p>
<p>The <a href="/underwriting/break-even-occupancy/">property break-even worksheet</a> addresses the entire property's fixed costs and per-night contribution. This equipment comparison is narrower. It cannot show that the acquisition works after debt, property taxes, insurance, all repairs and reserves simply because an upgrade covers its own incremental spending.</p>
<p>The <a href="https://consumer.ftc.gov/articles/how-use-energyguide-label-shop-home-appliances">FTC EnergyGuide explanation</a> says label operating costs are estimates based on typical use and a national average energy price. Actual cost depends on use and local price, and not every appliance has a label. Use it as a comparison input, not a promised STR utility saving. The published guidance is dated August 2022.</p>
<h2>Worked upgrade test: the required rate lift is not a forecast</h2>
<p>Invented educational arithmetic only, not a market figure, achieved premium, quote, client outcome or tax estimate. Assume the optional package costs $5,000 more than a complete functional baseline. Choose a five-year comparison horizon solely for the worksheet; it does not predict lifespan. Ignore financing, tax, discounting, residual value and later replacement initially, then evaluate those separately before a real decision.</p>
<p>Stipulate 150 already-booked nights per year under both alternatives. A hypothetical $10 higher nightly receipt produces $1,500 extra annual gross revenue. Assume, solely for this example, 20% of that extra revenue is absorbed by incremental revenue-linked costs: $300. Remaining contribution is $1,200. Stipulate another $300 annual incremental service cost and $100 annual utility saving, neither included in the 20% nor previously counted elsewhere. Annual incremental net cash is $1,200 − $300 + $100 = $1,000.</p>
<p>Five years of unchanged $1,000 incremental cash totals $5,000, equaling the initial premium in this simplified undiscounted case. That is not a 100% annual return, tax depreciation, a guaranteed payback date or the property's total return. The $5,000 remains an upfront cash payment; future modeled contribution cannot fund the deposit.</p>
<p>To tie under these stipulated inputs, annual contribution must cover $1,000 of chosen capital recovery plus the $200 net recurring difference, or $1,200. At the stipulated 80% contribution fraction, required extra gross receipts are $1,500. Spread over 150 common booked nights, the required average difference is $10 per night. This calculates a hurdle to investigate, not evidence that guests will pay it. Straight-line capital recovery here is a comparison convention, not an IRS classification or deduction.</p>
<h2>Keep the zero-lift and smaller-volume cases</h2>
<p>With no incremental revenue and the same hypothetical $300 service cost/$100 saving, annual incremental cash is negative $200. Across five years, $1,000 of net recurring outflows plus the $5,000 premium leaves the optional path $6,000 behind the functional baseline before omitted effects. The property might still be viable, but this worksheet does not establish that the premium is recovered.</p>
<p>In a separate sensitivity with only 100 common booked nights and the same unverified $10 receipt difference, extra gross revenue is $1,000, contribution is $800 and net annual cash is $600 after the separate recurring differences. Five years provides $3,000 against the $5,000 premium, leaving a $2,000 unrecovered difference. A distinct additional $2,500 work bill in year three would increase that difference to $4,500. Reconcile whether real work duplicates an included scope before adding it.</p>
<p>Neither scenario assigns a failure probability or proves the optional alternative is always wrong. Replace inputs with supported facts; test changes in fee structure, dates and installed scope. Keep extra disruption bills separate from revenue already reduced in the scenario. Model earlier invoices and the pre-receipt cash low point in the <a href="/blog/appliances-budget-short-term-rental/">dated equipment budget</a>, without allocating the same retained cash to several risks.</p>
<h2>Approve the acquisition before approving the premium</h2>
<p>First confirm the property clears permission, diligence, independently funded closing and the full operating downside using the functional baseline. Then approve, defer or omit optional spending on its own evidence and cash limits. An estimated tax benefit or hypothetical booking premium does not replace accessible purchase funds. A high household income does not establish that every optional invoice fits other commitments.</p>
<p><a href="/apply/">Compare the shortlisted STR with the incremental-cost register and zero-lift case</a>. Use the <a href="/blog/appliances-buying-short-term-rental/">equipment buying and seller-treatment guide</a> for actual conveyed units and accepted closing treatment, and the <a href="/blog/buy-str-high-income-large-tax-bill/">high-income acquisition roadmap</a> for the broader decision. Keep private seller receipts and financing records in agreed secure channels.</p>
<p class="small">FTC primary guidance reviewed October 7, 2026. Educational only, not valuation, inspection, lending, legal, tax or personalized investment advice. All worked figures are hypothetical. No demand, revenue premium, equipment life, saving, tax benefit or return is guaranteed.</p>'''
FAQ=[
('Does a premium appliance brand guarantee higher STR revenue?', 'No. Establish a functional baseline and test supported incremental receipts after variable costs, complete installed spending and a zero-lift case. A neighboring advertised rate does not prove causation.'),
('What is the difference between appliance contribution and gross revenue?', 'Contribution subtracts the costs that change with incremental receipts. Reconcile actual fee structures and separate additional service or utility differences without counting either twice.'),
('Is the required appliance rate lift a forecast?', 'No. It is a calculated hurdle under stated inputs. A chosen recovery horizon and hypothetical margin do not establish achieved demand, equipment life, tax treatment or investment return.'),
('Can future upgrade income pay an appliance deposit today?', 'No. Independently fund the actual deposit and invoice dates, then test future cash separately. Estimated tax benefits and unverified booking premiums are not cleared purchase funds.')]
if __name__=='__main__':
 source=(publisher.ROOT/'blog'/SLUG/'index.html').read_text();publisher.SLUG=SLUG
 publisher.TITLE=re.search(r'<title>(.*?)</title>',source)[1];publisher.H1=re.search(r'<h1>(.*?)</h1>',source)[1]
 publisher.DESC='Before buying an STR, test an optional appliance premium using incremental contribution, a required rate-lift worksheet and zero-revenue-lift downside.'
 publisher.BODY=BODY;publisher.FAQ=FAQ
 publisher.main(expected_publication='2026-09-22',hub_attribute='data-appliance-roi-link',hub_paragraph='Test the <a href="/blog/appliances-roi-short-term-rental/">optional appliance premium and zero-lift cash comparison</a> without treating an advertised nightly rate as an achieved benefit.')
 path=publisher.ROOT/'sitemap/index.html';s=path.read_text();s=re.sub(r'(<a href="/blog/'+SLUG+r'/">)[^<]+',lambda m:m[1]+publisher.H1,s);path.write_text(s)
