"""Expand only the existing permit-value owner; preserve homepage and publication."""
from refresh_dscr_purchase_methods import refresh
BODY = '''<p class="lead">A transferable STR permit does not have a universal dollar premium. Its acquisition value depends on the buyer actually retaining lawful use, the incremental property economics that use supports, the period for which those economics are defensible and the price already reflecting them. Before paying extra, compare supported STR operation with an independently verified lawful alternative. A scarce permission can be useful without justifying the seller's requested premium.</p>
<p><a href="/apply/">Bring the permit evidence and incremental-income comparison to an STR acquisition call</a>. BNB Accelerator assists within its contracted acquisition scope; the authority determines permission and independent advisers evaluate legal, financing and valuation questions.</p>
<h2>Establish what the buyer can actually retain</h2>
<p>Ask the issuing authority for a response addressing the exact parcel, unit, proposed buyer and ownership change. Record holder, status, expiry, permitted capacity, conditions, violations, renewal requirements and whether an exception survives the proposed transaction. Review HOA and deed restrictions separately. An agent's transferable label, payment receipt or historical guest calendar is not the buyer's permission.</p>
<p>A current jurisdiction-specific counterexample matters: <a href="https://www.nashville.gov/departments/codes/short-term-rentals/permit-types">Nashville's permit-type guidance</a> says new not-owner-occupied permits are not permitted in AR2A, R, RS or RM zoning. Existing holders there may be eligible for renewal, but those permits are not transferable when the property is sold or transferred. A seller's renewability therefore does not establish a buyer's usable advantage. This example is not a rule for every Nashville parcel or another market; obtain the controlling answer for the actual transaction.</p>
<p>The <a href="/blog/permits-that-do-not-transfer/">ownership-change permission guide</a> covers eligibility evidence. The <a href="/blog/buy-airbnb-without-str-permit/">missing-permit purchase guide</a> addresses absent authorization, and the <a href="/blog/permit-pending-due-diligence-extension/">protected-extension worksheet</a> addresses paying for more review time. This page asks a different question: after permission is supported, does its incremental benefit justify the price?</p>
<h2>Use a premium-evidence register</h2>
<div class="table-wrap"><table><thead><tr><th>Input</th><th>Evidence and reviewer</th><th>Price question</th></tr></thead><tbody>
<tr><td>Buyer permission</td><td>Authority response and counsel review of exact ownership/use</td><td>Can this buyer obtain the assumed benefit at all?</td></tr>
<tr><td>Supported operating period</td><td>Expiry, renewal and compliance conditions</td><td>How much of the assumed duration is established, conditional or unknown?</td></tr>
<tr><td>STR operating case</td><td>Verified seller receipts, independent demand and actual cost quotes</td><td>What remains after the distinct operating costs?</td></tr>
<tr><td>Lawful alternative</td><td>Permission, achievable receipts, required conversion work and costs</td><td>What advantage is genuinely incremental rather than the whole STR income?</td></tr>
<tr><td>Comparable sale and price basis</td><td>Supported transactions and qualified valuation review</td><td>Does the base price already reflect rental permission or income?</td></tr>
<tr><td>Cash and decision deadline</td><td>Actual lender terms, closing budget and counsel-reviewed dates</td><td>Can the buyer fund the price and downside without assuming future receipts?</td></tr>
</tbody></table></div>
<p>Keep the source, period, version, unresolved item and responsible reviewer beside each input. No verified lawful alternative means this comparison is incomplete; inventing a long-term-rental fallback does not fill the gap. Also distinguish an alternate use of the same property from buying another property: different location, condition, furnishing and financing can explain a price difference unrelated to permits.</p>
<h2>Worked comparison: incremental contribution is not gross rent</h2>
<p>All figures below are invented, not market data, an appraisal, provider quote or client result. Assume both uses of the same hypothetical property have been independently verified as lawful for the buyer. Stipulate complete annual operating costs for this simplified comparison, including taxes, insurance, management, maintenance and the other modeled recurring items. Debt payments, income taxes, new capital work and acquisition outlays are excluded and must be tested separately.</p>
<div class="table-wrap"><table><thead><tr><th>Invented annual input</th><th>STR case</th><th>Lawful alternative case</th></tr></thead><tbody>
<tr><td>Accommodation or rental receipts</td><td>$90,000</td><td>$48,000</td></tr>
<tr><td>Distinct operating outflows</td><td>$54,000</td><td>$26,000</td></tr>
<tr><td>Contribution before debt and income tax</td><td>$36,000</td><td>$22,000</td></tr>
</tbody></table></div>
<p>The incremental annual contribution is $14,000, not the $42,000 gross-receipt difference and not the entire $36,000 STR contribution. If an additional $2,000 annual compliance cost was genuinely excluded from the $54,000, the increment becomes $12,000. If already included, subtracting it again would understate the comparison. Actual variable costs and capacity restrictions need their own model.</p>
<p>Suppose the seller requests a separate $60,000 cash premium above a stipulated price that excludes that premium. Dividing $60,000 by $12,000 gives five years of the simplified increment before financing, income tax, time value, new capital work or permission changes. That is arithmetic payback, not an appraisal, recommended price ceiling or promise of five profitable years. If the income-based base price already capitalizes the same rental benefit, adding another permit premium counts that benefit twice.</p>
<h2>Test duration and loss of permission without invented probabilities</h2>
<p>A permit that must renew is not a permanent annuity. Ask counsel and the authority what is established for this buyer, what continuing requirements apply and what could interrupt use. Do not assign an unsupported approval percentage or assume a sale of an entity preserves an exception. Consider an explicit shorter-support scenario instead of multiplying a guessed probability by perpetual income.</p>
<p>In a separate invented sensitivity, assume the net $12,000 annual increment above is earned evenly solely for this arithmetic example and lasts six months. That produces $6,000 incremental contribution. Another $4,000 of distinct transition work, excluded from both original operating cases, leaves $2,000 before the omitted financing and tax items. The $60,000 premium is not recovered by that period. This is not a local renewal timeline or a prediction of revocation. Real receipt timing and seasonality may differ, and the alternative use must actually be available.</p>
<p>Have qualified advisers compare the complete dated purchase, operating and disposition flows, including any tax effects specific to the buyer. The <a href="/blog/seller-proforma-vs-trailing-revenue/">seller forecast bridge</a> helps identify unsupported improvement assumptions; the <a href="/blog/airbnb-reviews-property-sale/">review-goodwill worksheet</a> keeps a different claimed intangible benefit separate. Neither creates an independent value certificate.</p>
<h2>Separate willingness to pay from cash available to close</h2>
<p>For a distinct cash-only example, assume $350,000 accessible funds and a complete $275,000 acquisition-and-launch allocation, including a protected $45,000 reserve. This allocation excludes the proposed $60,000 premium and any new transition work. Adding that premium produces $335,000, leaving $15,000 outside the allocation. Another $20,000 of distinct required cash work brings it to $355,000, a $5,000 funding gap. Do not subtract the reserve a second time; it is already allocated, not another expense.</p>
<p>These invented amounts do not establish loan-to-value, interest or lender acceptance of a permit-related price. If the premium is financed, replace the assumed cash increment with the actual down payment, fees, payment and liquidity consequences. A buyer's high income or expected tax refund does not pay today's cleared-funds requirement or establish a justified valuation. Use the <a href="/tools/first-str-purchase-budget/">full acquisition-budget worksheet</a>.</p>
<p>Proceed when buyer permission, supported incremental economics, the actual price basis and funded downside all fit your requirements. Reprice a viable property when the claimed premium exceeds supported benefit or duplicates value already in the price. Delay only under valid protection while decisive authority or adviser evidence is missing. Reject an STR price case that depends on permission the buyer cannot retain or unavailable funds. Compare another candidate rather than treating seller scarcity language as approval.</p>
<p><a href="/apply/">Compare the shortlist using the permit-evidence register and complete buyer cash plan</a>. See the <a href="/blog/buy-str-high-income-large-tax-bill/">high-income acquisition roadmap</a> for the broader purchase sequence. BNB Accelerator is the publisher and interested acquisition-service provider. This is document-based educational analysis, not firsthand testing or an independent appraisal. Keep seller and borrower records in agreed private channels.</p>
<p class="small">Nashville primary guidance reviewed October 7, 2026; the page reports a March 13, 2026 update. Confirm current parcel-specific rules before relying on it. Educational only, not legal, appraisal, tax, lending or personalized investment advice. All example amounts and durations are hypothetical. No transfer, renewal, revenue, tax benefit, financing or return is guaranteed.</p>'''
FAQ = [
 ('Does a seller’s renewable STR permit establish a transferable buyer benefit?', 'No. Renewal by the existing holder and permission for a new buyer are different questions. Obtain the controlling authority’s answer for the actual ownership and use, and review private restrictions separately.'),
 ('Is the permit premium equal to the extra STR gross revenue?', 'No. Compare incremental contribution after distinct costs against an independently verified lawful alternative. Also test duration, financing, tax, capital work and whether the base price already reflects the same benefit.'),
 ('Does a five-year arithmetic payback justify the purchase price?', 'No. A simple premium divided by annual increment omits time value, financing, tax, changing costs and permission risk. It is a comparison input, not an appraisal or a guaranteed recovery period.')
]
if __name__ == '__main__':
    refresh('str-permit-value-sale', 'How Much Value Does a Transferable STR Permit Add | BNB Accelerator', 'How Much Value Does a Transferable STR Permit Add?', 'Before paying an STR permit premium, compare buyer permission, incremental income and renewal downside. Use a worked acquisition-price and cash test.', BODY, FAQ, '2026-09-23', 'data-permit-value-review-link', 'Test the <a href="/blog/str-permit-value-sale/">permit-premium contribution comparison and renewal downside</a>. Seller scarcity is not buyer permission or a justified extra price.')
