"""Scoped existing-owner expansion; no library/homepage generation."""
from refresh_dscr_purchase_methods import refresh

BODY = '''<p class="lead">An STR sale data room should let the buyer trace the property being sold to the records needed for the purchase decision. A folder full of seller PDFs is not proof of legal use, income, condition or a usable operating handoff. Before offering or removing protections, identify what each record covers, which version is current, what remains missing and who must resolve it. Keep original records, reconciliations and projections separate.</p>
<p><a href="/apply/">Bring the seller-file index and unresolved purchase questions to an STR acquisition call</a>. BNB Accelerator assists within its contracted acquisition scope. Your retained agent, counsel, lender, insurer and tax advisers determine their respective requirements; a data room does not replace their review.</p>
<h2>Request a purchase record, not access to everything</h2>
<p>Start with address-specific permission and association documents, relevant tax registrations, booking and payout exports, monthly operating statements and supporting bills. Add current insurance information, inspection and maintenance records, furnishing inventory, management and vendor agreements, operating procedures and the proposed transition plan. Identify the entity, listing or equipment each document concerns. The seller's existing permit, insurance or service relationship does not establish the buyer's accepted arrangement.</p>
<p>The <a href="/resources/str-acquisition-evidence-room/">acquisition evidence-room hub</a> organizes the overall purchase file. The <a href="/guides/str-deal-evidence-register/">claim-and-review register</a> connects an assumption to its reviewer and decision. This guide handles a narrower problem: controlling the seller's delivered files so a missing period, conflicting version or inappropriate disclosure does not disappear inside that register.</p>
<p>Agree on a secure delivery method with authorized parties. Request only information needed for a defined review; do not ask for seller account passwords, payment-card details or unnecessary guest identities. Where a professional genuinely needs sensitive records, arrange the appropriate restricted channel rather than a publicly accessible folder or broad email list. Redaction alone does not determine whether disclosure is permitted.</p>
<h2>Use a seller-file acceptance index</h2>
<div class="table-wrap"><table><thead><tr><th>Index field</th><th>What to record</th><th>Purchase check</th></tr></thead><tbody>
<tr><td>Record and source</td><td>Unique request ID, descriptive filename and authorized sender</td><td>Is it an original export, statement, summary or projection?</td></tr>
<tr><td>Property and period</td><td>Address/listing/entity, covered dates and relevant operating scope</td><td>Does it answer the requested buyer question rather than a different property or year?</td></tr>
<tr><td>Version and receipt</td><td>Received date, version identifier and prior version it replaces</td><td>Can the reviewer identify the active evidence without silently overwriting history?</td></tr>
<tr><td>Disclosure boundary</td><td>Redactions, permitted recipients and restricted supporting material</td><td>Can the necessary check be performed without unnecessary personal information?</td></tr>
<tr><td>Acceptance and exceptions</td><td>Received, usable for the stated check, unresolved or superseded; reviewer and reason</td><td>What is still missing, inconsistent or outside the requested period?</td></tr>
<tr><td>Decision dependency</td><td>Next request, responsible person and actual contract review deadline</td><td>Which purchase decision remains unsupported until the answer arrives?</td></tr>
</tbody></table></div>
<p>Receiving a document is different from accepting it as usable evidence, and neither establishes investment approval. Save the original and label a derived reconciliation separately. If a replacement export changes a total, record the changed definition or rows and ask the responsible reviewer to resolve the difference. Do not average two unexplained conflicting totals or discard the less attractive one.</p>
<p>A reservation-level file may need stable nonidentifying row references to reconcile refunds or fees. Do not remove every reference in a way that makes matching impossible; have the authorized seller and reviewer agree on an appropriate redacted version and controlled supporting access. This is an organizational worksheet, not a privacy compliance certification or permission to collect guest data.</p>
<h2>Worked file-control example: six received does not mean six usable</h2>
<p>The following is an invented diligence exercise, not a client outcome or measured completion standard. A buyer requests eight specific records for eight different questions. Six arrive. Of those six, five cover the requested property and period; one booking export covers the wrong year. The other two requests have no delivered record. Four older copies are also in the folder, but they are explicitly superseded versions of received records, not answers to additional requests.</p>
<p>The receipt count is six of eight. The usable-for-the-stated-check count is five of eight, before substantive verification. Three requested questions remain unsupported: two missing records and one wrong-period export. Counting the four superseded files would make the folder look fuller without changing either count. These categories are stipulated to be separate in this exercise; a real file can have several problems and should not be counted twice as two different missing requests.</p>
<div class="table-wrap"><table><thead><tr><th>Invented exception</th><th>Next evidence request</th><th>Decision affected</th></tr></thead><tbody>
<tr><td>Wrong-year booking export</td><td>Authorized same-period export with listing and date boundaries</td><td>Do not label the requested trailing period reconciled</td></tr>
<tr><td>Missing manager buyer proposal</td><td>Dated actual buyer scope, fees and service-start acceptance</td><td>Do not carry the seller's management terms into the buyer budget</td></tr>
<tr><td>Missing itemized equipment inventory</td><td>Ownership/exclusions, condition and possession schedule</td><td>Keep included inventory and replacement cash provisional</td></tr>
</tbody></table></div>
<p>Suppose the exercise is reviewed on day eight, the actual relevant decision deadline is day ten, and the seller expects the replacement export on day twelve. A future delivery promise does not supply the day-ten evidence or extend protection. Ask your retained agent and counsel before the deadline what lawful options the actual agreement permits. Do not assume an extension, automatic refund, cancellation right or obligation for the seller to provide a particular file.</p>
<h2>Keep three kinds of seller material visibly separate</h2>
<p>First, preserve raw source records with their definitions and covered periods. Second, keep reviewer calculations that explain adjustments, exclusions and remaining differences. Third, label forecasts and proposed improvements with their assumptions and implementation requirements. A polished pro forma cannot replace the exports and invoices needed to check historical performance.</p>
<p>Use the <a href="/blog/str-1099-payout-reconciliation/">payout reconciliation guide</a> for matching revenue and receipt categories, and the <a href="/blog/seller-proforma-vs-trailing-revenue/">seller forecast bridge</a> for deciding how much supported improvement belongs in an offer. For equipment and furnishings, use the <a href="/blog/str-furniture-bill-of-sale/">ownership and condition acceptance worksheet</a>. This file index does not calculate revenue, validate a permit, value furniture or certify account transfer.</p>
<p>Retain an exception after it is resolved: identify the replacement evidence, reviewer, resolution date and affected decision memo. If the reviewer accepts a different period or a disclosed limitation, record that narrower purpose. Do not silently change an unresolved item to verified because closing occurred or the folder was shared successfully.</p>
<h2>Protect the file and make the purchase decision</h2>
<p>The <a href="https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business">FTC's business information-security guide</a> recommends understanding what personal information is held, limiting collection and access to legitimate needs, safeguarding retained information, and having retention and incident-response practices. It discusses encryption for sensitive transmissions and multifactor authentication. Those general principles support a controlled diligence file; they do not establish your transaction's disclosure rights or complete legal obligations. Obtain appropriate privacy and security advice.</p>
<p>Decide who needs which records, how access will be reviewed when parties change, and how copies are retained or disposed of under actual legal and business requirements. Do not delete evidence needed for a dispute, tax record or professional obligation merely because the deal ended; ask the appropriate adviser. Do not publish seller, guest or client records as marketing examples without valid authorization.</p>
<p>Proceed when the decisive records and independent reviews support the actual purchase case, not when a folder reaches a target file count. Reprice a still-viable property when verified exclusions or additional buyer costs change the offer. Delay only under available contractual protection while decisive evidence is missing. Reject a purchase that requires treating an unsupported claim as established. High deployable capital or an expected tax benefit does not cure a missing operating record.</p>
<p><a href="/apply/">Discuss the acquisition shortlist with the current file index and three most important unresolved decisions</a>. Use the <a href="/blog/buy-str-high-income-large-tax-bill/">high-income buyer roadmap</a> for the remaining capital, underwriting and launch questions. BNB Accelerator is the publisher and an interested acquisition-service provider; this is document-based educational analysis, not a firsthand provider review or a completed professional review of your transaction.</p>
<p class="small">FTC primary guidance reviewed October 7, 2026. All worked file counts and dates are hypothetical. Educational information, not legal, privacy, security, tax, lending or personalized investment advice. No document availability, consent, contract remedy, rental permission, income, tax benefit or investment result is guaranteed.</p>'''

FAQ = [
 ('Does receiving every seller file mean STR diligence is complete?', 'No. Separate receipt, usability for the requested property and period, substantive verification and investment approval. A file count does not establish any of those later conclusions.'),
 ('How should an STR buyer handle conflicting document versions?', 'Preserve originals, label superseded versions and request an explanation of changed definitions or rows. Record the active evidence and unresolved difference rather than averaging unexplained totals.'),
 ('What if a seller record will arrive after my decision deadline?', 'Ask your retained agent and counsel before the actual deadline what options the agreement permits. A promised delivery does not supply evidence or automatically extend protection.')
]

if __name__ == '__main__':
    refresh('str-sale-data-room', 'What Belongs in an STR Sale Data Room | BNB Accelerator', 'What Belongs in an STR Sale Data Room?', 'Before buying an STR, control seller-file versions, missing records and disclosure boundaries. Use a document-acceptance index before contract deadlines.', BODY, FAQ, '2026-09-23', 'data-sale-room-review-link', 'Use the <a href="/blog/str-sale-data-room/">seller-file acceptance index and missing-record deadline example</a> before relying on a complete-looking folder. Receipt is not verification or purchase approval.')
