"""Scoped expansion of the existing residency owner, not a new guide."""
from refresh_dscr_purchase_methods import refresh, publisher
BODY='''<p class="lead">You can buy a property in a market with a primary-residence STR rule, but the proposed buyer and operating plan must actually qualify for the intended rental use. A second address, occasional vacation or nominal owner does not establish residence. Before offering, separate three questions: where you genuinely live, what rental activity the local rule permits, and whether the purchase works within that activity. Substantial capital or a large tax bill does not change the eligibility facts.</p>
<p><a href="/apply/">Bring the actual living pattern and property-use plan to an acquisition call</a>. BNB Accelerator supports acquisition within its agreement; the responsible authority and qualified independent counsel determine legal eligibility, not an acquisition worksheet.</p>
<h2>Test the actual owner against the actual local rule</h2>
<p>Start with the parcel's governing jurisdiction and current permit category. Ask who must own, reside, apply and operate; how residence is defined; what evidence is required; and which absences, rental periods or dwelling arrangements are permitted. Do not import another city's annual-night threshold or assume owner-occupied means the host must be present for every guest stay. Obtain the applicable text and an explanation addressing your facts.</p>
<p><a href="https://www.nashville.gov/departments/codes/short-term-rentals/permit-types">Nashville's permit-types page</a>, updated March 13, 2026 and reviewed October 8, says an owner must permanently reside at the property and be a natural person to qualify for its owner-occupied permit. It lists entities, including LLCs and trusts, as ineligible for that category, and requires primary-residence documentation to match the recorded deed. These are Nashville descriptions, not nationwide ownership or residency rules. Check the actual parcel and applicable category before selecting title.</p>
<p>A family member who genuinely owns and resides at a property requires a fact-specific review; merely naming someone to make an investor plan appear compliant is not the same thing. Do not change documents to misrepresent actual use. The <a href="/blog/nonconforming-str-use-sale/">nonconforming-use guide</a> concerns continuity through transaction events; this page concerns whether the proposed buyer's own living pattern fits a residence-based category.</p>
<h2>Prepare an evidence register before the offer deadline</h2>
<div class="table-wrap"><table><thead><tr><th>Buyer fact</th><th>Evidence and reviewer</th><th>Unresolved purchase question</th></tr></thead><tbody>
<tr><td>Actual residence</td><td>Genuine living plan and current qualifying records</td><td>Does the applicable definition fit, rather than just the mailing address?</td></tr>
<tr><td>Ownership and applicant</td><td>Proposed deed, owner identities and authority/counsel review</td><td>Is this person or structure eligible for this category?</td></tr>
<tr><td>Rental arrangement</td><td>Whole home or part, owner presence, guest use and allowed periods</td><td>Which actual rental activity can be supported?</td></tr>
<tr><td>Property and private limits</td><td>Parcel, dwelling layout, zoning and association documents</td><td>Do separate restrictions defeat an otherwise eligible owner plan?</td></tr>
<tr><td>Changes and renewal</td><td>Absence, move, ownership change and continuing evidence requirements</td><td>What must be reassessed before changing the operation?</td></tr>
</tbody></table></div>
<p>For each row, record the exact source, reviewer, dated answer and transaction deadline. The <a href="https://www.nashville.gov/departments/codes/short-term-rentals/apply-short-term-rental-property-permit">Nashville application page</a>, updated October 1, 2026 and reviewed October 8, requires four current owner-occupation documents: two from each of its two groups, with the owner's name and matching property address. It separately directs sensitive residency information outside the online application to the specified departmental email. Read the actual current instructions rather than uploading private records to a generic lead form.</p>
<p>That local document list is not a substitute for genuine permanent residence or a universal checklist. Confirm official contacts independently, follow the authority's handling instructions, and use agreed secure channels for advisers. An authorized manager, accepted application or seller's old permit does not by itself establish the buyer's eligibility. Keep proof of submission separate from issued permission and conditions.</p>
<h2>Do not turn calendar space into rental entitlement</h2>
<p>Build an honest calendar for the household first. Identify actual residence, travel, family use, maintenance and periods potentially available to guests. Then overlay the applicable legal conditions and realistic operating evidence. Empty nights do not automatically become lawful or bookable nights, and permitted nights are not paid stays.</p>
<p>Hypothetical calendar only, not a local rule or recommended residence pattern: 168 nights of actual owner use, 100 other household-blocked nights and 30 distinct work-blocked nights leave 67 unassigned nights in a 365-night year. A proposed 60 guest nights fits within that arithmetic, but it does not prove residency eligibility, rental permission, demand or access to the most valuable dates. If another distinct 20 nights become unavailable, only 47 remain; a 60-night assumption must change. Categories in this example do not overlap.</p>
<p>Ask whether the operating plan still serves the household if guest receipts are lower or absent. Moving solely to access a permit can change work, schooling, travel and housing costs. A plan to spend a few holiday weeks at the property should not silently become a permanent-residence representation. Do not calculate a tax deduction from this calendar; the CPA must assess actual use and applicable tax rules independently.</p>
<h2>Worked comparison: eligible use and available cash both matter</h2>
<p>All numbers below are invented, not Nashville prices, permit decisions, financing terms, demand estimates or client outcomes. Assume $280,000 genuinely allocated to the acquisition. Option A is a residence-based purchase whose actual eligibility remains subject to review. It requires $200,000 purchase and closing cash, $30,000 distinct setup and a separate $40,000 protected reserve: $270,000 allocated, leaving $10,000 unassigned.</p>
<p>Stipulate $25,000 annual guest receipts for A and $42,000 total distinct annual cash outflows, including the modeled loan payment and operating/housing costs. The difference is negative $17,000 before omitted costs and tax consequences. It is not a pure investment return: the household also lives there, and its alternative housing budget is not supplied. Compare the personal housing choice separately rather than calling $25,000 gross receipts profit or assuming hosting pays for the house.</p>
<p>Option B is a different investment-use candidate whose actual permission and financing also need verification. Assume $225,000 purchase and closing cash, $35,000 setup and $40,000 retained reserve: $300,000, a $20,000 gap to available funds. Its invented annual case is $72,000 receipts minus $32,000 operating outflows minus $36,000 separate loan-related outflows, leaving $4,000 before omitted capital work and taxes. The operating total excludes items already in the loan-related total.</p>
<p>B's annual $4,000 does not provide the missing $20,000 at closing or establish a superior total return. A's $10,000 initial margin does not fund its entire $17,000 annual shortfall. A reserve is counted once in initial allocation and later spending reduces it; do not count retained cash as money already spent. Neither option clears both tests from these partial assumptions. Use the <a href="/tools/first-str-purchase-budget/">dated purchase-budget worksheet</a> for actual receipt and bill dates, household reserves and omitted obligations.</p>
<h2>Choose a lawful purchase path before changing the story</h2>
<p>Proceed when the real living pattern, ownership, permitted operation and independently funded downside fit. Reprice an otherwise viable purchase using supported use, not a permit workaround. Seek valid contract protection while a decisive eligibility answer remains unresolved; deadlines and cancellation rights come from the signed terms. Reject the STR thesis if the intended buyer cannot qualify, or evaluate a genuinely lawful alternative use on its own economics.</p>
<p>Local residence status does not automatically settle mortgage occupancy or tax classification. Review the <a href="/blog/second-home-loan-rental-intent/">disclosed second-home lending plan</a> with the actual lender rather than carrying this local label into financing documents. A large expected tax benefit cannot rescue ineligible rental use. Continue through the <a href="/blog/buy-str-high-income-large-tax-bill/">high-income acquisition roadmap</a>.</p>
<p><a href="/apply/">Compare properties with the completed residence register and funded use-case budget</a>. Share the decision memo and unanswered questions, not unnecessary identity records. BNB Accelerator is the interested acquisition-service publisher. This is document-based education, not firsthand permit testing or legal, tax, lending or personalized investment advice. Primary local materials reviewed October 8, 2026; examples are hypothetical. No permission, income, approval, tax benefit or return is guaranteed.</p>'''
FAQ=[
('Does a second address establish primary-residence STR eligibility?', 'No. Check the applicable definition against genuine residence, eligible ownership and current proof. A mailing address or occasional visit is not a substitute for the actual facts.'),
('Can an LLC qualify for an owner-occupied STR permit?', 'It depends on the applicable category and jurisdiction. Nashville’s cited owner-occupied description excludes LLCs and other listed entities; do not generalize that rule or use ownership paperwork to misrepresent occupancy.'),
('Are unused nights automatically available for paying guests?', 'No. Check residence and rental conditions, household and work blocks, permission and realistic booking evidence separately. Calendar arithmetic is not an entitlement or demand forecast.'),
('Does local owner-occupied permission settle mortgage or tax treatment?', 'No. Have the actual lender and qualified tax advisers assess intended use and documents independently. Local permission, mortgage classification and tax treatment are separate reviews.')]
if __name__=='__main__':
 publisher.DATE='2026-10-08'
 refresh('primary-residence-str-rule','Can You Buy an STR Where a Primary-Residence Rule Applies | BNB Accelerator','Can You Buy an STR Where a Primary-Residence Rule Applies?','Before buying under a primary-residence STR rule, test actual occupancy, proof and permitted use. Compare a residence-based budget with an investment purchase.',BODY,FAQ,'2026-09-23','data-primary-residence-review-link','Use the <a href="/blog/primary-residence-str-rule/">actual-residence evidence register and purchase-use cash comparison</a> before pricing a residence-restricted STR plan.')
 p=publisher.ROOT/'blog/primary-residence-str-rule/index.html';p.write_text(p.read_text().replace('<span>Updated October 7, 2026</span>','<span>Updated October 8, 2026</span>',1))
