"""Existing tier-owner expansion, not a new provider-swapped acquisition guide."""
from pathlib import Path
import re
R=Path(__file__).resolve().parents[1];p=R/'guides/str-insights-service-tiers/index.html';s=p.read_text()
assert '"datePublished": "2026-10-01"' in s and '"dateModified": "2026-10-01"' in s
s=s.replace('"dateModified": "2026-10-01"','"dateModified": "2026-10-07"')
old='Select a tier by delivered work and accountability, not by the number of listings available.'
new='Compare STR Insights tiers by written deliverables, upgrade credits, transaction duties and an opening handoff you can verify before paying.'
assert s.count(old)==5;s=s.replace(old,new)
start=s.index('<section class="section-sm bg-alt"><div class="wrap"><h2>Your proposal review worksheet</h2>')
end=s.index('<section class="section-sm"><div class="wrap wrap-narrow"><h2>Continue your buyer comparison</h2>',start)
body='''<section class="section-sm bg-alt"><div class="wrap"><h2>Your proposal review worksheet</h2><p>Complete this original tier-selection register with the proposal actually offered to you. These are requested records, not authenticated STR Insights contract obligations. A product name or another customer's experience cannot fill the blanks.</p><div class="bc-table-scroll" role="region" aria-label="Proposal review worksheet" tabindex="0"><table><thead><tr><th scope="col">Question</th><th scope="col">Evidence to record</th><th scope="col">Decision gate</th></tr></thead><tbody>
<tr><th scope="row">Which tier am I paying for?</th><td>Product and contracting entity; dated scope attachment; access term; calls or work included; upgrade, expiry and credit terms</td><td>Before payment, separate reusable software access from address-specific advice and executed work</td></tr>
<tr><th scope="row">Who checks a candidate address?</th><td>Model version and sources; legal-use evidence; named condition, insurance and financing reviewers; referrals versus included tasks</td><td>Before offer authorization, retain an unresolved-items list rather than treating a screen's estimate as approval</td></tr>
<tr><th scope="row">Who acts while the contract is live?</th><td>Licensed representation agreement; notice sender; model revision owner; inspection/financing deadlines and buyer approvals</td><td>Before a deadline, distinguish advice from authority to negotiate, issue notices or spend</td></tr>
<tr><th scope="row">What is delivered at opening?</th><td>Itemized scope; installed versus ordered assets; invoices; access handoff; operating responsibilities and support end date</td><td>Before accepting a milestone, identify unfinished work, evidence needed and actual payment terms</td></tr>
</tbody></table></div></div></section>
<section class="section-sm"><div class="wrap wrap-narrow"><h2>Match the advertised path to the proposed tier</h2>
<p>The current <a href="https://www.strinsights.com/">STR Insights homepage</a> describes choosing a consulting package and working with a dedicated consultant to find a deal. Its navigation separately identifies software and analysis services. The <a href="https://www.strinsights.com/introduction">introduction page</a> describes finding and analyzing a property, inspection and negotiation, then design, setup, listing creation and operations support. These public descriptions explain why it is worth requesting a precise scope; they do not prove every product includes every activity.</p>
<p>Ask the provider to identify which description applies to your dated proposal, market and address. Have it mark each requested task as included, separately quoted, referral-only or not supplied. If you only need data and can coordinate specialists yourself, a limited product may fit. If your missing capacity is executing the transaction and setup, a data subscription alone does not assign those duties. A broader package is useful only when its actual scope covers the gaps; this is not an instruction to buy the most expensive tier.</p>
<p>We have not authenticated a paid engagement from either public page, and no individual fee or current availability is authenticated. We have not tested the service firsthand. Request the actual package documents and ask the relevant professional to review the legal, lending, insurance and tax issues. A marketed turnkey path does not establish lawful use, loan approval, a guaranteed opening date or an investment result.</p>
<h2>Original opening-handoff work sample</h2>
<p>Hypothetical purchase example, not an actual STR Insights file: the tier attachment calls for furnishing coordination and listing setup. At the proposed completion meeting, the buyer receives a furniture purchase receipt and listing draft. A bed remains on backorder, installation has not been confirmed and the proposed operator has not accepted responsibility. Record three separate statuses: procurement evidence received; installation unresolved; operator handoff unresolved. A receipt is not evidence that the room is usable, and a draft is not proof the property can lawfully accept guests.</p>
<p>Use a six-field punch list for each item: promised output, evidence received, remaining dependency, named responsible party, buyer decision and the actual payment clause. Ask whether “coordination” includes procurement only or installation and completion checks. Ask who owns the listing account, who receives permitted access and which party confirms insurance, permissions and operating readiness. Keep sensitive credentials out of shared documents; use the platform's appropriate access mechanism rather than copying passwords into the punch list.</p>
<p>Do not unilaterally invent a right to withhold a payment or change its due date. Ask the provider for an agreed correction plan and have your adviser interpret the actual milestone and remedy terms. Likewise, do not count operations support as a management contract unless one actually assigns that work. Preserve dated evidence when the item is resolved, rather than simply deleting the row. The <a href="/guides/str-service-responsibility-matrix/">responsibility matrix</a> helps assign acceptance; the <a href="/blog/str-buyer-agent-vs-acquisition-team/">agent-versus-acquisition-team guide</a> separates representation and coordination.</p>
</div></section>
<section class="section-sm"><div class="wrap wrap-narrow"><h2>Use a missing-answer test: upgrading is not automatically a credit</h2>
<p>Hypothetical worksheet only; none of these amounts is STR Insights or BNB pricing. A buyer has $280,000 accessible and a $240,000 complete property allocation before service payments. That allocation includes down payment, closing, setup, known repairs and a $35,000 retained reserve. Suppose the buyer already spent an invented $3,000 on access and $5,000 on consultation, and is considering an invented $17,000 broader engagement. Do not infer that earlier products were prerequisites or that these tiers actually exist at those prices.</p>
<p>If the new $17,000 invoice is additional with no agreed credit, total capital committed is $240,000 + $3,000 + $5,000 + $17,000 = $265,000, leaving $15,000 margin. If the provider expressly credits the earlier $8,000 against that same $17,000 package, the additional payment is $9,000; total capital committed becomes $257,000, leaving $23,000. Earlier cash was still spent. Count it once; do not both remove the earlier payments and subtract the credit again.</p>
<p>Replace those fictional terms with the quotation, credit conditions, expiration date and payment schedule. A possible refund is not money available to fund closing. If a separate $18,000 completion task is excluded, the no-credit path rises to $283,000 and is $3,000 short; the documented-credit path rises to $275,000 with $5,000 margin. If that exact task is already included, do not add it twice. Neither remaining balance certifies sufficient reserves or an acceptable purchase.</p>
<p>Compare the changed deliverables as well as the cash: which unfinished tasks does the upgrade actually take over, who accepts them and when does responsibility transfer? For choosing between companies rather than inspecting one proposal, use <a href="/compare/alternatives-to-str-insights/">STR Insights alternatives</a>. Use the established <a href="/tools/first-str-purchase-budget/">purchase-cash tool</a> with your real obligations. Keep uncertain tasks unresolved until written scope and funding support a decision, without treating a tax benefit, testimonial or future booking as available cash.</p>
</div></section>'''
s=s[:start]+body+s[end:]
s=s.replace('<a href="/guides/str-insights-service-tiers/">STR Insights Portal vs Acquisition Service Questions</a></p>', '<a href="/guides/str-service-responsibility-matrix/">Acquisition responsibility matrix</a></p>')
s=s.replace('reviewed 2026-10-01.', 'reviewed October 7, 2026. The primary pages display no article publication date; this is our source-review date.')
s=s.replace('This is a public-offer comparison, not a customer review, independent ranking or endorsement.', 'This is document-based analysis, not firsthand testing, a customer review, independent ranking or endorsement. No paid contract, fee quote, credit entitlement or customer result has been authenticated. BNB Accelerator\'s own work depends on its signed engagement, not an automatic inclusion implied by this guide.')
p.write_text(s)
p=R/'sitemap-core.xml';s=p.read_text();s,n=re.subn(r'(<loc>https://www\.bnbaccelerator\.com/guides/str-insights-service-tiers/</loc>\s*<lastmod>)2026-10-01',r'\g<1>2026-10-07',s);assert n==1;p.write_text(s)
